### ISSUE TITLE
cargo recompile all crates when building cross architecture with specifying `+crt-static` in rustflags on Windows

### ISSUE THREAD

**Issue by metaworm** [rust-lang/cargo#11264] opened 2022-10-20 11:35 UTC
### Problem

I specify `rustflags` in `.cargo/config.toml` in my project directory like this
```toml
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
```

Every time when i build project using `cargo build --target <target-triple>` and  switch one target to another, cargo will recompile all crates rather than reuse the compiled result in the `target/<target-triple>` directory

### Steps

1. Put these configuration into `.cargo/config.toml` in your project directory
    ```toml
    [target.i686-pc-windows-msvc]
    rustflags = ["-C", "target-feature=+crt-static"]
    [target.x86_64-pc-windows-msvc]
    rustflags = ["-C", "target-feature=+crt-static"]
    ```
2. Build the `x86_64` version which is the default on Windows using `cargo build`
3. Build the `x86` version using `cargo build --target i686-pc-windows-msvc`
4. Build the `x86_64` version again using `cargo build`, cargo will recompile all crates

### Version

```text
cargo 1.66.0-nightly (b332991a5 2022-10-13)
```

**Comment by ehuss** [comment] 2022-10-20 13:52
Thanks for the report!  This is a known issue where running `cargo build` and `cargo build --target` share the same build-script/proc-macro artifacts, but use different RUSTFLAGS and thus cause a rebuild.

Workarounds involve always using `--target`, separate `target` directories, or [`target-applies-to-host`](https://doc.rust-lang.org/cargo/reference/unstable.html#target-applies-to-host).

Closing as a duplicate of #9453 (and #3739, and #6375, and #8716).

**Closed by ehuss** 2022-10-20 13:52 UTC
Labels: C-bug
