### ISSUE TITLE
`cargo install` command

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/cargo#1917] opened 2015-08-18 17:31 UTC
It would be cool if cargo had a `cargo install` command similar to e.g. `npm install --save`. That command would then look in the index for the most recent version of the crate, install it, and add the dependency to the `Cargo.toml` file.

**Comment by Turbo87** [comment] 2015-08-18 17:35
it seems like https://github.com/killercup/cargo-edit and https://github.com/withoutboats/cargo-add implement something similar to my suggestion, however it would be awesome if that was part of `cargo` itself instead of having to install it as a plugin.

**Comment by huonw** [comment] 2015-08-18 17:40
Dupe of #4, thanks for filing!

**Closed by huonw** 2015-08-18 17:40 UTC

**Comment by Turbo87** [comment] 2015-08-18 17:55
sorry, only searched for "install" before creating this issue ;)

**Comment by brandonros** [comment] 2018-06-25 12:16
How is this not done yet?...

**Comment by cup** [comment] 2019-06-21 02:15
https://github.com/rust-lang/cargo/issues/1917
https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586
https://github.com/rust-lang/cargo/issues/6457
https://github.com/rust-lang/cargo/issues/6488
https://github.com/rust-lang/cargo/issues/651
https://github.com/rust-lang/cargo/pull/5611
