### ISSUE TITLE
Ability to specify version in generic way in doc link

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#4120] opened 2017-06-04 09:30 UTC
Currently, my Cargo.toml looks mostly like this:

```toml
[package]
version = "0.5.0"
documentation = "https://docs.rs/lewton/0.5.0"
```

This means however that I have to remember to update the documentation link each time I make a release. It would be nice if something like this were supported:

```toml
documentation = "https://docs.rs/lewton/$version"
```

**Comment by carols10cents** [comment] 2017-10-03 00:42
Closing as a duplicate of #2075.

FYI, [Crates.io does this automatically if you use docs.rs](https://github.com/rust-lang/crates.io/blob/master/app/routes/crate/version.js#L45-L51) :)

**Closed by carols10cents** 2017-10-03 00:42 UTC

**Comment by est31** [comment] 2017-10-03 02:41
@carols10cents honestly I find it troubling that crates.io is feeling free to replace links as it wishes, without asking the crate authors to opt in or anything.

**Comment by est31** [comment] 2017-10-03 02:44
But generally its good to know that this replacing is happening, thanks for the info.
