### ISSUE TITLE
Ability to conditionally compile from a workspace 

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/cargo#11742] opened 2023-02-20 05:22 UTC
Hi there,

We have recently been having an issue where we can't easily select components for compilation from a workspace based on target_family. We have a generic server binary that can run on all platforms, and two platform/target specific tools for unix vs windows.

What we would like is a way to say:

```
[workspace]

members = [
    "generic_server"
]

[workspace.cfg(target_family = "unix")]
members += [
    "unix tool"
]

[workspace.cfg(target_family = "windows")]
members += [
    "windows tool"
]
```

However, we can't find a way to do this effectively, and even within the tools, we can't do target conditional compilation for libs or bins. This means we are left trying to do cfg based on target family inside the libs and binaries instead which feels a bit messy to us. The alternate is to "de-workspace" our project, but then we lose valuable maintenance features like workspace specified dependencies. 

I think it would be a significant improvement for rust/cargo to support such conditional compilation rules in workspaces.

**Comment by weihanglo** [comment] 2023-02-21 13:42
Looks like a duplicate of #5220? Also somehow related to #11526.

**Comment by weihanglo** [comment] 2023-02-21 13:48
In the meanwhile, you can use empty `fn main()` or empty `lib.rs` with `#[cfg(…)]` to avoid the actual compilation.

**Comment by yaleman** [comment] 2023-02-21 21:47
Definitely looks like #5220 might apply 😄 

> or empty `lib.rs` with `#[cfg(…)]`

Could you expand on this a little? Is it possible to specify an alternate source path on libs per-target?

**Comment by weihanglo** [comment] 2023-02-22 12:06
Take `home` crate as an example. Just create a file and add a `use statement` with a `cfg` above. 

https://github.com/rust-lang/cargo/blob/0c331721d91a154de2ef8f50ffab572e829fb0cb/crates/home/src/lib.rs#L68-L75

In general, you could have several Rust source files. Import them respectively with corresponding `cfg`, such as

```
src/
├── lib.rs
├── this_is_not_windows.rs
└── windows.rs
```

And the code may look like this:

```rust
// lib.rs
#[cfg(windows)] 
use windows::my_function; 
  
#[cfg(not(windows))] 
use this_is_not_windows::my_function; 
```

**Comment by weihanglo** [comment] 2023-02-22 12:07
Going to close this as it is a duplicate of #5220. Let us know if it is wrong. Thank you!

**Closed by weihanglo** 2023-02-22 12:07 UTC

**Comment by Firstyear** [comment] 2023-02-22 23:39
> Take `home` crate as an example. Just create a file and add a `use statement` with a `cfg` above.
> 
> https://github.com/rust-lang/cargo/blob/0c331721d91a154de2ef8f50ffab572e829fb0cb/crates/home/src/lib.rs#L68-L75
> 
> In general, you could have several Rust source files. Import them respectively with corresponding `cfg`, such as
> 
> ```
> src/
> ├── lib.rs
> ├── this_is_not_windows.rs
> └── windows.rs
> ```
> 
> And the code may look like this:
> 
> ```rust
> // lib.rs
> #[cfg(windows)] 
> use windows::my_function; 
>   
> #[cfg(not(windows))] 
> use this_is_not_windows::my_function; 
> ```

We can't do that because Windows doesn't have PAM or Nsswitch or equivalents. So on Windows we'd be compiling empty DLL's for no reason. 

We'd rather see a way to cfg target platforms at the *workspace* level so we don't even consider the pam/nsswitch modules at all on windows. And vice versa, we don't want the windows specific code considered when we are on unix.

So I think while the "lib.rs" hack with cfg works, it's a thin cover up of the real problem which is the ability to have workspace members targeted based on platform.
