### ISSUE TITLE
"cargo metadata" no longer displays "example" kind if example specifies crate-type

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#3654] opened 2017-02-06 02:06 UTC
As of rust-lang/cargo/pull/3556, the `cargo metadata` command does not output the "kind" as "example" if the example specifies a crate-type.  Sample Cargo.toml:

```toml
[package]
name = "scratch"
version = "0.0.0"

[[example]]
name = "elib1"
path = "examples/elib1.rs"
crate-type=["staticlib"]
```

I am working on a tool that uses the metadata output to determine which command-line arguments to pass to Cargo in order to build a target.  Without knowing this is an example, it is impossible to know to pass --example.

I am unsure of what the correct solution is.  Some ideas:
* "kind" can display "example" even if it is an ExampleLib.
* Include an "is_example" field.
* Include an "args" field that indicates how to build this target.

**Comment by jethrogb** [comment] 2017-02-06 02:22
Duplicate of #3572

**Comment by KalitaAlexey** [comment] 2017-02-06 06:04
@alexcrichton,
I think `kind` should still show "example".
If it is right, I will change that. It is easy change.

**Comment by jethrogb** [comment] 2017-02-06 06:17
I think metadata should show both type of output and the required cargo cmd line.

**Comment by KalitaAlexey** [comment] 2017-02-06 06:34
@jethrogb,
You can't execute `cargo run --example` if an example is a library.

**Comment by jethrogb** [comment] 2017-02-06 06:35
But you can execute build, rustc, or test with that flag.

**Comment by KalitaAlexey** [comment] 2017-02-06 06:39
But I would rather prefer to add a field `example` which is either `true` or `false`.

**Comment by jethrogb** [comment] 2017-02-06 06:59
I think that would be sufficient?

**Comment by KalitaAlexey** [comment] 2017-02-06 07:27
@jethrogb,
Yes it would since it allows to determine whether it is an example or not and to determine what it produces.

**Comment by alexcrichton** [comment] 2017-02-07 01:07
I [posted on the PR as well](https://github.com/rust-lang/cargo/pull/3556#issuecomment-277850525) but I think we should revert the breaking change here and just extend the metadata format to otherwise accommodate examples-as-libraries in metadata.

@KalitaAlexey would you be willing to prepare such a PR?

**Comment by KalitaAlexey** [comment] 2017-02-07 04:02
@alexcrichton,
I will send a PR today (in 3 hours).

**Comment by KalitaAlexey** [comment] 2017-02-07 12:52
@alexcrichton,
It is not a breaking change because we didn't accept crate-type for an example.
It seems that `cargo metadata` just reads `crate-type`.
I can specify `crate-type = ["e"]` and it prints it.
So I didn't break anything.
This is why I think we should add a field "is_example" of boolean.
"kind" is what specified in `crate-type`.
What do you think about it?

**Comment by jethrogb** [comment] 2017-02-07 16:45
Sure it is a breaking change. Before it was `kind: ["example"]`, now it's not.

**Comment by KalitaAlexey** [comment] 2017-02-07 16:48
@jethrogb,
If you don't specify any `crate-type` it will be `"kind": ["example"]`.

**Comment by alexcrichton** [comment] 2017-02-07 17:42
@KalitaAlexey yeah this was a breaking change from before because existing code has broken. I think "kind" was probably a misnomer from before, so we should leave "kind" as it was and then add a separate "crate-types" field which has the information about crate types.

**Comment by KalitaAlexey** [comment] 2017-02-07 17:47
@alexcrichton,
Okay.
I will find the solution.

**Comment by alexcrichton** [comment] 2017-02-07 17:49
Thanks @KalitaAlexey

**Comment by KalitaAlexey** [comment] 2017-02-07 18:31
@alexcrichton,
I checked the code.
`"kind"` is actually `"crate-type"`.
I think what can I do with that.

**Comment by KalitaAlexey** [comment] 2017-02-07 18:39
@alexcrichton,
I'd prefer to add a field named `"is_example"`.
If we added `"crate-type"` what values it would have for `"kind": "bin"`?

**Comment by jethrogb** [comment] 2017-02-07 23:00
Can we do the opposite and add a field named `crate-type` which contains the actual crate types? This way we have backwards-compatibility, the ability to determine cargo cmdline flags, and the information about crate types passed by cargo to rustc.

**Comment by alexcrichton** [comment] 2017-02-08 01:04
@jethrogb yes that's what I'd [like to do](https://github.com/rust-lang/cargo/issues/3654#issuecomment-278079197).

**Comment by ehuss** [comment] 2017-02-08 02:42
Just FYI, here are some in-the-wild usages of the "kind" metadata, if it will help you see how it is used:

* [Clippy uses it](https://github.com/Manishearth/rust-clippy/blob/4ea0f72a1573b172e32227be2c386997d3b1a5cf/src/main.rs#L211) to determine the Cargo args to use (via the [cargo_metadata](https://crates.io/crates/cargo_metadata) crate).
* [rustfmt uses it](https://github.com/rust-lang-nursery/rustfmt/blob/b5d4421a83478b36cb424f13a19bcf9ef454ecb2/src/bin/cargo-fmt.rs#L116) to determine which targets it should format.
* [flycheck rust uses it](https://github.com/flycheck/flycheck-rust/blob/f8ae845d4d7a18c1873ee1edd1a4db272fde5dd3/flycheck-rust.el#L99) for finding targets for a given file.
* [My own thing](https://github.com/ehuss/sublime-rust/blob/19b17ebfff3e4960447539ec635f2fc57e2af3c9/SyntaxCheckPlugin.py#L191) I was toying with which uses it to detect Cargo command-line args for building a target.

**Comment by KalitaAlexey** [comment] 2017-02-08 04:11
Okay.
I will add `crate-type` which would duplicate `kind` field for all targets, but example.

**Closed** 2017-02-11 18:46 UTC
