### ISSUE TITLE
Pass `doc` cfg to rustc when running cargo doc

### ISSUE THREAD

**Issue by Fryuni** [rust-lang/cargo#12533] opened 2023-08-20 16:09 UTC
### Problem

From the [issue originally reported to rustdoc](https://github.com/rust-lang/rust/issues/114952) by @notriddle:

I tried this code:

// crate a
pub struct MyStruct;
#[cfg(doc)]
impl MyStruct {
    pub fn doc_only_method() {}
}

// crate b
#[doc(inline)]
pub use a::MyStruct;

I expected to see this happen: I expected doc_only_method to appear in crate b

Instead, this happened: It didn't.

---

### Proposed Solution

Rustdoc adds the `doc` cfg before generating the docs for a crate ([here](https://github.com/rust-lang/rust/blob/0510a1526d4135861226281eed38114ab71a12f0/src/librustdoc/core.rs#L201-L202)), but the metadata from dependencies are generated using rustc without such flag, causing the problem above.

`cargo doc` should add the cfg to the rustc calls that generate the metadata passed to rustdoc.

### Notes

A few possibly related issues:
- https://github.com/rust-lang/cargo/issues/8811
- https://github.com/rust-lang/cargo/issues/8944
- https://github.com/rust-lang/cargo/issues/11570

**Comment by Fryuni** [comment] 2023-08-20 16:15
I learned about this on [a mostly unrelated issue](https://github.com/rust-lang/rust/issues/90435#issuecomment-1683087383), but this inconsistency on when and where the `doc` config if you make a crate re-exporting something using [the exact intended, and documented, use case for this `cfg`](https://doc.rust-lang.org/rustdoc/advanced-features.html#cfgdoc-documenting-platform-specific-or-feature-specific-information).

**Comment by fmease** [comment] 2023-08-29 15:48
I pretty sure that this issue is a duplicate of #8811 which you have already linked. Would you agree?

**Comment by Fryuni** [comment] 2023-08-29 17:55
I might be wrong, but it seems to me like it is two different use cases that could be solved by the same solution (passing `--cfg doc` to `rustc`).

That one seems to be about dependencies breaking because they behave differently when generating docs while this issue is about the _dependent_ crate breaking (or having incorrect docs) due to a difference in the configs passed to it and its dependencies.

If I understood that incorrectly and they are actually the same problem than sure, we can close this one as duplicate.

**Comment by ehuss** [comment] 2023-09-25 19:24
These do appear to be the same issue to me, so closing in favor of #8811.

**Closed by ehuss** 2023-09-25 19:24 UTC
Labels: C-feature-request, S-triage
