### ISSUE TITLE
`cargo doc --no-deps` does nothing

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2658] opened 2016-05-06 20:43 UTC
When I have an empty `target/doc` directory and run `cargo doc --no-deps` it prints nothing and generates no files. If I first run `cargo doc` then `cargo doc --no-deps` then the `--no-deps` step _does_ regenerate just the top level crate docs.

**Comment by carols10cents** [comment] 2017-09-25 19:36
I'm not able to reproduce this bug with `cargo 0.21.0 (5b4b8b2ae 2017-08-12)`:

```
$ rm -rf target/doc/
$ cargo doc --no-deps
 Documenting cargo-registry v0.2.1 (file:///Users/carolnichols/rust/crates.io)
    Finished dev [unoptimized + debuginfo] target(s) in 13.16 secs
$ ls target/doc/
- lots of stuff, including a directory for the toplevel crate that includes an index.html containing the docs for that crate - 
```

So closing!

**Closed by carols10cents** 2017-09-25 19:36 UTC
