### ISSUE TITLE
`cargo build --locked --features <dependency>/<dependency feature>` can compile dependencies not specified in the lockfile

### ISSUE THREAD

**Issue by tofay** [rust-lang/cargo#14156] opened 2024-06-26 19:07 UTC
### Problem

If a dependency feature is activated via CLI arg of a locked build, then cargo may resolve and compile dependencies not listed in the lockfile.

My expectation here is that cargo should reject the use of a dependency feature via `--features`: it's not mentioned at https://doc.rust-lang.org/cargo/reference/features.html#dependency-features that this is supported. Either that or fail to do a locked build if not all dependencies are in the lockfile.

### Steps

1. `cargo init example1 && cd example1`
2. `cargo add openssl`
3. `cargo build --locked --features openssl/vendored`

Note that openssl-src is downloaded and built despite not being recorded in the lockfile.

### Possible Solution(s)

A possible solution is to prevent non-workspace member dependency features from being activated via CLI.

### Version

```text
cargo 1.79.0 (ffa9cf99a 2024-06-03)
release: 1.79.0
commit-hash: ffa9cf99a594e59032757403d4c780b46dc2c43a
commit-date: 2024-06-03
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mariner 2.0.0 [64-bit]
```

**Comment by ehuss** [comment] 2024-06-26 20:13
Thanks for the report! This is essentially a duplicate of #3629, so closing in favor of that.

**Closed by ehuss** 2024-06-26 20:13 UTC
Labels: C-bug, S-triage
