### ISSUE TITLE
Cargo is broken on Windows Docker since #7137

### ISSUE THREAD

**Issue by zeevm** [rust-lang/cargo#7313] opened 2019-08-30 10:45 UTC
[7137](https://github.com/rust-lang/cargo/pull/7137) introduced using fs::canonicalize in fingerprint.rs (https://github.com/rust-lang/cargo/pull/7137/commits/4f6553ab553ca127ab653bec9f2f65e64735912f)

canonicalize on Windows is implemented using GetFinalPathNameByHandleW which fails on directories that are bind mounted, result being Cargo fails building inside Windows containers when building a source tree that is bind mounted from the host.

To reproduce:
1. Create a new crate source tree (cargo new) on Windows
2. Create a Windows container
3. Start the container and bind mount the source tree inside the container
4. Build the source tree inside the container

Result: build fails

**Comment by alexcrichton** [comment] 2019-09-03 14:58
Thanks for the report! Can you gist the error message coming out of this?

Also cc @ehuss, you might be interested in this!

**Comment by sloutsky** [comment] 2019-12-20 09:50
This issue becomes critical to us. Can you please comment if any fix is planned soon?

**Comment by ehuss** [comment] 2023-04-15 16:00
I'm going to close as I cannot reproduce the original issue. Perhaps an update in Docker or Windows has fixed the filesystem issue. Additionally, #11866 has been merged which does a fallback for canonicalization.

If anyone can reproduce this on the latest nightly, please include a complete reproduction, including a Dockerfile, the version of Docker and Windows, WSL information, etc.

**Closed by ehuss** 2023-04-15 16:00 UTC
Labels: C-bug, O-windows, A-filesystem
