### ISSUE TITLE
Use --precise N.N for a git dependency causes odd panics

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#2096] opened 2015-10-31 15:48 UTC
`panicked at 'index 0 and/or 8 in 0.3.17 do not lie on character boundary', ../src/libcore/str/mod.rs:1284`

**Comment by alexcrichton** [comment] 2015-10-31 16:53
I think this is a dupe of https://github.com/rust-lang/cargo/issues/2094, so closing in favor of that.

**Closed by alexcrichton** 2015-10-31 16:53 UTC
