### ISSUE TITLE
Dependency in workspace not recompiled after compiler version change

### ISSUE THREAD

**Issue by euclio** [rust-lang/cargo#2897] opened 2016-07-19 23:11 UTC
# Steps to reproduce

1. Create a new crate.
2. Inside that crate, create another crate. This crate should be both a path dependency and a workspace member of the root crate.
3. Compile both crates.
4. Change your compiler version (using `rustup`, etc.)
5. Compile the member crate.
6. Compile the root crate.

You should get an error `found crate "member" compiled by an incompatible version of rustc`.

# Expected behavior

The dependency is recompiled using the new compiler.

You can see this error happening in the rust-rosetta CI [here](https://travis-ci.org/Hoverbear/rust-rosetta/builds/145948903#L462). It seems that the artifacts in the cache were compiled with an older nightly, so the compilation failed.

**Comment by IvanUkhov** [comment] 2016-07-23 09:41
I’ve experienced the same. After updating the compiler, I tried to run the tests in the nested crate, and I got the following error:

```
error: found crate `foo` compiled by an incompatible version of rustc [E0514]
help: please recompile that crate using this compiler (rustc 1.12.0-nightly (936bfea94 2016-07-20))
```

I believe it should have been automatically recompiled.

**Comment by alexcrichton** [comment] 2016-07-25 20:03
Thanks for the report! After investigating I've concluded that this is a dupe of https://github.com/rust-lang/cargo/issues/2897, so I'm going to close in favor of that.

**Closed by alexcrichton** 2016-07-25 20:03 UTC

**Comment by euclio** [comment] 2016-07-25 20:33
@alexcrichton looks like you linked back to this issue 😄  what is the dupe number?

**Comment by alexcrichton** [comment] 2016-07-25 20:41
Gah sorry about that! I meant to link to https://github.com/rust-lang/cargo/issues/2855
