### ISSUE TITLE
check main branch by default when cargo install --git executed

### ISSUE THREAD

**Issue by non-descriptive** [rust-lang/cargo#8827] opened 2020-11-03 10:10 UTC
Due to recent changes default branch of new git projects will be set to `main` instead of `master`, so it is probably good idea to check both default branch names. Attempt to install project with `main` default branch with just `cargo install --git` currently will fail with

```shell
error: failed to find branch `master`

                                     Caused by:
                                                 cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```
Current workaround requires explicitly pass `--branch main` to cargo. 

last tested on 
`cargo 1.47.0 (f3c7e066a 2020-08-28)`

**Comment by ehuss** [comment] 2020-11-03 14:16
Thanks for the report.  Closing as a duplicate of #3517.

**Closed by ehuss** 2020-11-03 14:16 UTC
Labels: C-feature-request
