### ISSUE TITLE
println order in build.rs bug

### ISSUE THREAD

**Issue by gipsyh** [rust-lang/cargo#11295] opened 2022-10-27 01:09 UTC
### Problem

in build.rs, it workds:
```
fn main() {
    println!("cargo:include=abc/src");
    println!("cargo:rustc-link-search=native=abc");
    println!("cargo:rustc-link-lib=static=abc");
    println!("cargo:rustc-link-lib=dylib=stdc++");
}
```
but it not works in:
```
fn main() {
    println!("cargo:rustc-link-lib=dylib=stdc++");
    println!("cargo:include=abc/src");
    println!("cargo:rustc-link-search=native=abc");
    println!("cargo:rustc-link-lib=static=abc");
}
```
the build can pass, but when run test, it will error:
```
error: linking with `cc` failed: exit status: 1
= note: /usr/bin/ld: abc/libabc.a(AbcGlucose.o): in function `glucose_solver_start()':
          /root/abc-glucose/abc/src/sat/glucose/AbcGlucose.cpp:63: undefined reference to `operator new(unsigned long)'
          /usr/bin/ld: /root/abc-glucose/abc/src/sat/glucose/AbcGlucose.cpp:63: undefined reference to `operator delete(void*, unsigned long)'
          /usr/bin/ld: abc/libabc.a(AbcGlucose.o): in function `Gluco::vec<Gluco::Lit>::capacity(int)':
          /root/abc-glucose/abc/./src/sat/glucose/Vec.h:103: undefined reference to `__cxa_allocate_exception'
          /usr/bin/ld: /root/abc-glucose/abc/./src/sat/glucose/Vec.h:103: undefined reference to `__cxa_throw'
          /usr/bin/ld: abc/libabc.a(AbcGlucose.o): in function `Gluco::vec<int>::capacity(int)':
          /root/abc-glucose/abc/./src/sat/glucose/Vec.h:103: undefined reference to `__cxa_allocate_exception'
          /usr/bin/ld: /root/abc-glucose/abc/./src/sat/glucose/Vec.h:103: undefined reference to `__cxa_throw'
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by ehuss** [comment] 2022-10-27 01:32
The order that libraries are passed to the linker is significant (particularly when mixing dylib and static libs). Some resources on the web may help explain the details if you are interested, such as: https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking or https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc.

**Comment by gipsyh** [comment] 2022-10-27 02:27
> The order that libraries are passed to the linker is significant (particularly when mixing dylib and static libs). Some resources on the web may help explain the details if you are interested, such as: https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking or https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc.

I see, Thanks.

**Comment by weihanglo** [comment] 2022-10-27 07:53
Closing as it is not a bug. Thanks for everyone's participation.

**Closed by weihanglo** 2022-10-27 07:53 UTC
Labels: C-bug
