### ISSUE TITLE
cargo info implementation (similar to npm show/info cmd)

### ISSUE THREAD

**Issue by hltdev8642** [rust-lang/cargo#9032] opened 2020-12-31 16:39 UTC
**Describe the problem you are trying to solve**

So I frequently use with ruby/npm/apt the `show` / `info`  commands to get more package information _(link to git, homepage, keywords, etc)_, but as far as I know this isn't possible with cargo.  I thought it would be really useful to have the ability to use something along the lines of: `cargo show [pkgname]` to get some basic info about a package. 

**Describe the solution you'd like**

I created a script that implements the crates.io api, it is just preliminary and the only requirement is the package `jq` . I included the version I made which has a colored output, although this could easily be removed/disabled by replacing the color-echo cmds simply with echo.

That script is [here](https://gist.github.com/hltdev8642/cdf13c2394dd15c4155eb50b878fe682), id be curious what people think. 

To run:
- Install dependencies (not much, could probably be eliminated altogether using awk anyways)
 > `apt install jq`
- Either save somewhere in  `$PATH`, or just run locally via `./cargo-show`. (obviously chmod +x  it as well)

To search:
`cargo-show [packagename]`

Looks like this:

![cargo-show](https://user-images.githubusercontent.com/39349712/103418510-fe45e500-4b5c-11eb-9f0b-1a5c03b98771.png)

**Notes**

**Comment by epage** [comment] 2022-04-20 21:41
It looks like this is a duplicate of #948, closing in favor of that

**Closed by epage** 2022-04-20 21:41 UTC
Labels: A-new-subcommand, C-feature-request
