### ISSUE TITLE
Default install to --locked when used with --path

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/cargo#10148] opened 2021-12-01 17:43 UTC
### Problem

As a rust developer that eats his own dogfood, I often `cargo build --release` to test some things then `cargo install --path .` to deploy an application on the local machine. This invariably results in a complete from-scratch rebuild because cargo ignores the lock file. Can I please suggest that when used in combination with `--path` (perhaps only for local filesystem paths?) that `cargo install` should default to `--locked`?

* It's far faster
* It's the element of least surprise, since a user would expect to install what they just built and something totally different
* For potential contributors to git projects where the user clones the directory and then uses `cargo install` rather than installing from crates.io or from a git path (to cache build dependencies, to prevent downloading a huge git repo each time, etc, etc) this can often result in breakage because git master is working/passing _with the lock file_ but the user/dev gets a completely different output because the lock file is ignored, potentially causing build issues and a maintenance nightmare for project owners.

### Proposed Solution

When `cargo install --path` is used with a local path, it should by default respect the presence of any lock files.

**Comment by Eh2406** [comment] 2021-12-10 20:28
I'm not going to claim that the current behavior is intuitive. But this is a duplicate of #9436 and #7169, so let's continue the conversation where the history and arguments have been expressed.

**Closed by Eh2406** 2021-12-10 20:28 UTC
Labels: Command-install, C-feature-request

**Comment by mqudsi** [comment] 2021-12-15 00:46
Thanks. I didn’t find anything relevant when I searched.
