### ISSUE TITLE
File permission after "cargo login" too permissive

### ISSUE THREAD

**Issue by cesarb** [rust-lang/cargo#1643] opened 2015-05-22 02:05 UTC
$ ls -la ~/.cargo
    total 16
    drwxrwxr-x.  3 cesarb cesarb 4096 Mai 21 22:58 .
    drwx------. 43 cesarb cesarb 4096 Mai 21 22:55 ..
    -rw-rw-r--.  1 cesarb cesarb   55 Mai 21 22:58 config
    drwxrwxr-x.  5 cesarb cesarb 4096 Mai 17 10:51 registry
    $ cargo --version
    cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

The permission for either the config file or the directory should not be world-readable, since the config file has the API key for crates.io. It should also complain if it finds an already existing world-readable config file.

**Comment by alexcrichton** [comment] 2015-05-26 16:23
Closing as a dupe of https://github.com/rust-lang/cargo/issues/930, but thanks!

**Closed by alexcrichton** 2015-05-26 16:23 UTC
