### ISSUE TITLE
I can't override the dependence of used packages

### ISSUE THREAD

**Issue by bozaro** [rust-lang/cargo#1624] opened 2015-05-18 07:16 UTC
**Problem summary**
I can't override the dependence of used packages.

**Rust/Cargo version**
rustc 1.1.0-nightly (7bd71637c 2015-05-06) (built 2015-05-06)
cargo 0.2.0-nightly (7f810ba 2015-05-03) (built 2015-05-04)

**Problem details**
I try to create crossplatform application on Rust.
After adding dependency to **iron** I have broken linking on Windows: **openssl-sys** try to use library **libeay32.a** and **libssl.32a** instead of **libcrypto.a** and **libssl.a**.
I patch **openssl-sys** and send pull request to package author.

After it I try to add this package to project by adding to **Cargo.toml** code like:
```
[dependencies.openssl-sys]
path = "rust-openssl/openssl-sys"
```
On compilation I have error:
```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

  openssl-sys v0.6.2
  openssl-sys v0.6.2 (file:///C:/Work/github/octobuild)
```
So I can not temporarily replace a library of https://crates.io/ quick to fix problems.

**Workaround 1**
I can workaround the problem by cloning all packages using the **openssl-sys** and set dependency by **path** location.
In my case I need to clone and patch:

* **iron** (https://github.com/iron/iron)
* **hyper** (https://github.com/hyperium/hyper)
* **cookie** (https://github.com/alexcrichton/cookie-rs)
* **openssl** (https://github.com/sfackler/rust-openssl)

But this solution looks very ugly.

**Workaround 2**
Wait when the **openssl-sys** with my fix will be published on https://crates.io/.
But this solution is unacceptable slow.

**Comment by huonw** [comment] 2015-05-18 07:26
One can do this via a path override in a `.cargo/config`, see http://doc.crates.io/guide.html#overriding-dependencies for more info.

Closing as not a bug, but if you encounter problems with that approach, feel free to ask questions. :smile:

**Closed by huonw** 2015-05-18 07:26 UTC

**Comment by bozaro** [comment] 2015-05-18 07:50
Thank you for your response. This solved my problem.
I'm sorry for your trouble. I do not know how I missed this part of the manual.
