### ISSUE TITLE
cargo cannot distinguish between feature & features for multiple flags

### ISSUE THREAD

**Issue by artech-git** [rust-lang/cargo#10854] opened 2022-07-12 14:03 UTC
### Problem

Recently working on a code base which required me to insert certain features from a library.
I accidently introduced the compilation error because
I wrote this, making a typo of **features** as **feature** which should have been avoided by me !
`totp-rs = {version = "2.0.1", feature = ["default", "qr"]}`

which resulted into unknown compilation error by cargo 
```
[E0599] no method named `get_qr` found for struct `TOTP` in the current scope. 
[Note] method not found in `TOTP`
```

### Proposed Solution

I am still not very sure about what should be the way through this 
but maybe what cargo can identify this incorrect relation of multiple flags not to be allowed under a feature flag 
instead of features itself

**Comment by epage** [comment] 2022-07-12 14:19
Earlier in the compilation process, you should have gotten
```
warning: unused manifest key: dependencies.totp-rs.feature
```
I was able to reproduce that warning in making that typo in one of my crates

Cargo doesn't treat unexpected fields as errors.  If nothing else, this allows for a `Cargo.toml` to specify a new field and still (mostly) compile in old versions of rust.  For example, a lot of people specified `package.rust-version` to a version before that field was specified.

The warning does come before anything else but generally one should process compile errors from the top to the bottom since earlier errors might be the cause of later ones.  However, it can be easy to overlook a warning when resolving errors.

**Comment by artech-git** [comment] 2022-07-15 08:45
Alright that made sense, but I had just one doubt about it whether cargo working has nothing to do with the rust compiler version or is it something else ?

**Comment by weihanglo** [comment] 2022-07-15 10:36
> Alright that made sense, but I had just one doubt about it whether cargo working has nothing to do with the rust compiler version or is it something else ?

If you install rust via rustup, a fixed version of Cargo is shipped with the that specific version of Rust compiler. That's the concept [toolchains](https://rust-lang.github.io/rustup/concepts/toolchains.html) in rustup.

Cargo tries to maintain backward compatibility as possible as it could. You surely can use Cargo coming from different toolchains, but that is not guaranteed to work compatibly. Some unstable features or fixes need other components from the same toolchain.

**Comment by weihanglo** [comment] 2022-07-15 10:43
It would be nice to have a better typo fix suggestion than a generalized unused warning. Going to close this as it seems like a duplicate of #9731. If you have different thoughts, leave comments below. Thanks!

**Closed by weihanglo** 2022-07-15 10:43 UTC
Labels: C-feature-request

**Comment by artech-git** [comment] 2022-07-15 11:31
yes  exactly that issue address it decently but something of this kind would be helpful alot if it can insist a message of this  kind

```shell
warning [E12344]: multiple flags detected under a ambgious attribute` 
 --> Cargo.toml:6:32
  |
6 |     package = { version = "x.y.z" feature = ["feature-1", "feature-2", "feature-3"] }
  |                                    ^^^^^ help: did you mean `features`?
  | note: you could only insert single feature flag under toolchain version `x.y.x` for more info check out cargo docs
```

something similar of this kind could be present or maybe different which could aid in detecting it in advance for the specific version of toolchain

or something better would be to insert a new option flag under cargo package manager itself which could warn about `cargo.toml` warning/errors
