### ISSUE TITLE
`patch` table fails to rewrite dep to local path if it’s published in Cargo registry

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/cargo#4936] opened 2018-01-12 15:31 UTC
`cargo 0.25.0-nightly (a88fbace4 2017-12-29)`

Patching crates.io dependencies to use a local path does not work from a [virtual manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#virtual-manifest).

E.g. virtual manifest (`./Cargo.toml`):
```toml
[patch.crates-io]
sitemap = { path = "./in-house-sitemap/" }
```

Workspace member package manifest (`./package/Cargo.toml`):
```toml
[dependencies]
sitemap = "*"
```
This will pull in the `sitemap` crate from crates.io, unlike similarly rewritten dependencies where no crate with the same name is published in the Cargo registry.

**Comment by alexcrichton** [comment] 2018-01-12 15:45
Have you tried updating Cargo.lock? If not, can you provide an example to work with?

**Comment by sanmai-NL** [comment] 2018-01-12 16:08
You mean running `cargo update`? Yes. I’ll try to make a complete example if I have more time.

**Comment by alexcrichton** [comment] 2018-01-12 16:16
Hm so some dependencies are being rewritten when others aren't? Are you sure that `package/Cargo.toml` is in the same workspace as the root one perhaps?

**Comment by sanmai-NL** [comment] 2018-09-18 16:17
This issue is still relevant. Unclear whether any issue blocks this or what can be done other than fixing Cargo.

**Comment by stjepang** [comment] 2018-10-03 12:00
I have a related issue.

Suppose there is a workspace with `workspace/Cargo.toml` and `workspace/member/Cargo.toml`. A `[patch.crates-io]` section is ignored if placed into `workspace/member/Cargo.toml`. It only works when placed into `workspace/Cargo.toml`.

Is this intended behavior? Should we print a warning saying patched versions must go to the root `Cargo.toml` file?

**Comment by sanmai-NL** [comment] 2018-10-04 08:00
@alexcrichton: I’m sorry, I haven’t got around to that. I thought the OP should be enough but so far it isn’t. I’ll make an example ASAP.

**Comment by epage** [comment] 2023-10-17 21:30
As this has been sitting open for 5 years without reproduction steps, I'm closing it.  If someone can figure it how to reproduce this, let us know!

**Closed by epage** 2023-10-17 21:30 UTC
Labels: A-patch

**Comment by sanmai-NL** [comment] 2023-10-18 11:25
> As this has been sitting open for 5 years without reproduction steps, I'm closing it.  If someone can figure it how to reproduce this, let us know!

If anything, the repro steps are in the opening post.

**Comment by weihanglo** [comment] 2023-10-19 01:43
It might be something similar to <https://github.com/rust-lang/cargo/issues/12464>.
But yup a clearer step to reproduce would be really helpful for investigation.
