### ISSUE TITLE
Cargo doesn't understand prerelease versions or build metadata

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#2935] opened 2016-07-31 05:05 UTC
Semver allows specifying versions such as 1.0.0-beta+exp.sha.5114f85, see http://semver.org/#spec-item-9 . Cargo doesn't handle these versions well or at all. See e.g. https://crates.io/crates/core_rustc-serialize which has these versions:

* 0.3.19
* 0.3.19+patch1
* 0.3.20-v0.3.19patch1

Specifying a dependency `core_rustc-serialize = "*"` (or  `core_rustc-serialize = "^0.3"`) results in Cargo choosing 0.3.19, while it should choose the newer 0.3.20-v0.3.19patch1. You can't specify 0.3.20-v0.3.19patch1 in either case by using `cargo update --precise`. Specifying the exact version string does work.

There is simply no way to select `0.3.19+patch1`. Putting it in the `Cargo.toml` results in the error message "the given version requirement is invalid". You also can't select it using `cargo update --precise`. This results in a crate existing on crates.io that can effectively not be used by anyone.

**Comment by alexcrichton** [comment] 2016-07-31 07:10
I think this may be a dupe of https://github.com/rust-lang/cargo/issues/2222 which has been discussed a bit more towards the end of the thread, so I'm going to close in favor of that.

cc @steveklabnik

**Closed** 2016-07-31 07:10 UTC

**Comment by jethrogb** [comment] 2016-07-31 07:44
That bug is currently solely about prerelease versions. There's also an issue with build metadata which has not been discussed in #2222. I'm happy to move that conversation over there too, but then the issue description should be updated.

**Comment by alexcrichton** [comment] 2016-08-01 01:19
Ah ok make sense to me, want to reopen one targeted at build metadata (may be good to start fresh). Thanks!
