### ISSUE TITLE
Idea: Allow path local dev-dependencies for tests

### ISSUE THREAD

**Issue by carllerche** [rust-lang/cargo#4466] opened 2017-09-03 21:12 UTC
The problem:

Cargo expects tests (in the `tests/`) directory to be spread out across multiple files which are compiled to individual executables. When tests get more involved, it can be useful to extract "support" code into separate modules that are reused across each test file. However, this support code gets compiled once for each test file (which leads to slow compilation times). Also, all functions that exist in the support modules might not be used in each test file, which results in dead code compiler warnings.

Current work around:

The current work around that I see is to move all support code into a dedicated crate. This crate can be depended on using a local path dependency. The problem w/ this is that when publishing the crate to crates.io, crates.io returns with an error indicating that there is a path dependency in the Cargo.toml that doesn't live on crates.io itself. Indeed, I would rather not publish my test support junk to crates.io....

Possible solution:

Somehow allow path-local dev dependencies to be included when pushed to crates.io. All the support code could be included in the top level crate so that tests can still be run when pulled from crates.io.

**Comment by lukaslueg** [comment] 2017-09-12 07:41
Possible dupe of #3745

**Comment by carols10cents** [comment] 2017-10-02 19:32
Yep, closing as duplicate of #3745. Thanks!

**Closed by carols10cents** 2017-10-02 19:32 UTC
Labels: Command-publish
