### ISSUE TITLE
Duplicate message on compilation errors

### ISSUE THREAD

**Issue by casey** [rust-lang/cargo#3167] opened 2016-10-05 22:56 UTC
My compilation errors seem to be getting printed twice:

```
: cargo test
   Compiling j v0.1.5 (file:///Users/rodarmor/src/j)
error[E0277]: the trait bound `&std::iter::Peekable<std::slice::Iter<'_, &str>>: std::iter::Iterator` is not satisfied
  --> src/lib.rs:56:5
   |
56 |     for command in &i {
   |     ^
   |
   = note: `&std::iter::Peekable<std::slice::Iter<'_, &str>>` is not an iterator; maybe try calling `.iter()` or a similar method
   = note: required by `std::iter::IntoIterator::into_iter`

error[E0277]: the trait bound `&std::iter::Peekable<std::slice::Iter<'_, &str>>: std::iter::Iterator` is not satisfied
  --> src/lib.rs:56:5
   |
56 |     for command in &i {
   |     ^
   |
   = note: `&std::iter::Peekable<std::slice::Iter<'_, &str>>` is not an iterator; maybe try calling `.iter()` or a similar method
   = note: required by `std::iter::IntoIterator::into_iter`

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: Could not compile `j`.

To learn more, run the command again with --verbose.
```

Some info about my setup:

```
: cargo --version
cargo 0.13.0-nightly (109cb7c 2016-08-19)
: rustc --version
rustc 1.12.0 (3191fbae9 2016-09-23)
: uname -a
Darwin fancypants 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

**Comment by alexcrichton** [comment] 2016-10-06 22:28
Thanks for the report! What's actually happening here is that the library is being compiled twice (once with `--test` and once for doc tests later on), and this is a dupe of https://github.com/rust-lang/cargo/issues/1534 and https://github.com/rust-lang/cargo/issues/851 (now tracked at https://github.com/rust-lang/cargo/issues/1198). This is intended behavior though, and you can use various flags like `--test`, `--lib`, or `-j` to not run `rustc` in parallel, so I'm going to close this.

**Closed by alexcrichton** 2016-10-06 22:28 UTC
