### ISSUE TITLE
Passing target specific command line options to rustc

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/cargo#2284] opened 2016-01-15 22:17 UTC
I'm trying to use cargo to build my [kernel](https://github.com/Zoxc/AveryRust).

I ran into an issue with `cargo rustc` not being able to pass along command line arguments to all crates being used for a specific target.

For example I want to pass along `--sysroot`, `-Z no-landing-pads` and `-C ar` to all crates being built with `--target`, but not compiler plugins.

**Comment by Zoxc** [comment] 2016-01-16 00:22
Looks like #2241 will provide a way to do this.

**Comment by alexcrichton** [comment] 2016-01-16 01:08
Yes I believe that this is a dupe of https://github.com/rust-lang/cargo/issues/2112, so closing in favor of that.

**Closed by alexcrichton** 2016-01-16 01:08 UTC
