### ISSUE TITLE
cargo install does not seem to silence (all) lints

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/cargo#2459] opened 2016-03-09 18:26 UTC
Fresh Rust 1.7 x86_64 MSVC install with `cargo 0.8.0-nightly (28a0cbb 2016-01-17)`. Running `cargo install rustfmt` gives me a warning from a dependency, which AFAIK should be silenced:

```
.cargo\registry\src\github.com-88ac128001ac3a9a\winapi-0.2.5\src\lib.rs:4:21: 4:39 warning: lint raw_pointer_derive has been removed: using derive with raw pointers is ok
.cargo\registry\src\github.com-88ac128001ac3a9a\winapi-0.2.5\src\lib.rs:4 #![allow(bad_style, raw_pointer_derive)]
                                                                                              ^~~~~~~~~~~~~~~~~~
```

**Comment by alexcrichton** [comment] 2016-03-09 18:43
Thanks for the report! I believe this is a dupe of https://github.com/rust-lang/rust/issues/31141 so I'm going to close in favor of that, however.

**Closed by alexcrichton** 2016-03-09 18:43 UTC
