### ISSUE TITLE
Test UX: High noise to signal ratio in test output for large workspaces.

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo#9952] opened 2021-10-01 15:06 UTC
rust workspaces are getting bigger and if I run a named test I get this kind of thing:
```
<snip>
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_consensus_pow-ebde30e7fc601f52)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_consensus_slots-8c4f89b5b5023e60)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_consensus_uncles-ccf4803c4c0275c7)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_executor-f162d5c03810b699)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 81 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_executor_common-b31f7a1b0538b32d)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_executor_wasmi-26dded16175b1765)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_executor_wasmtime-aafc61ecf1051687)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_finality_grandpa-5e29a0a4b6779109)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 78 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/sc_finality_grandpa_rpc-0cf104be186ce752)

running 0 tests
<snip>
```
There's screen fulls of this.

Somewhere in the pages of output is my test that was run....  

The feature request: Can we have a better UX please?

E.g. could we have a `--condenced` flag we could use to see more consolidated results because we like tests, lots of tests are good, but the UX could be improved.

Requests like this are what success looks like - it's a good thing :-)

**Comment by Eh2406** [comment] 2021-10-01 15:50
I'd love to see experimentation with this in a third party sub command. When there is a format that is widely used, we can bring it into Cargo.

**Comment by ehuss** [comment] 2021-10-01 16:08
Yea, I agree it would be nice to have a cleaner summary and output.  I'm going to close this as a duplicate of #4324 and #2832.

**Closed by ehuss** 2021-10-01 16:08 UTC
Labels: C-feature-request
