### ISSUE TITLE
cargo clean when target is a symlink only deletes symlink

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#7510] opened 2019-10-14 18:03 UTC
**Problem**
If `CARGO_TARGET_DIR` is set to a path that is a symlink, or `target` itself is a symlink, `cargo clean` will delete the symlink and not anything in the linked directory.

**Steps**
1. `mkdir foo`
2. `ln -sfn foo target`
3. `cargo build`
4. `cargo clean`
5. `ls foo`
6. `ls target`

**Expected**: `foo` should be empty, `target` should still point to `foo`
**Actual**: `foo` has all build artifacts, `target` has been removed.

**Possible Solution(s)**
If cargo's target directory is a symlink, it should remove the contents of the symlink rather than the symlink itself.

Output of `cargo version`:
cargo 1.38.0 (23ef9a4ef 2019-08-20)

**Comment by ehuss** [comment] 2019-11-08 17:12
I'm going to close this as expected behavior, see discussion in #7527.

**Closed by ehuss** 2019-11-08 17:12 UTC
Labels: C-bug

**Comment by mtekp** [comment] 2019-11-16 10:28
Sorry for commenting on closed issue. I was following the video where @jonhoo did fix this issue. Even though it was closed as expected behavior, I feel it will be better to provide some info to user who did use symlink as target. Either at the beginning of project or when user does clean. Like: "Since the target directory is a symlink cargo doesn't modify actual target, but only deletes symlink upon clean" Or some better message.

**Comment by jonhoo** [comment] 2021-11-06 19:51
Yeah, that would indeed be a possible solution, it's just a little more awkward, and users would need to _know_ to do this, rather than it "just working" however they happened to set it up.

**Comment by junderw** [comment] 2021-11-06 23:59
My original comment was not that clear, I apologize.

What I mean is:

1. The behavior without symlink is "automatically delete the target directory and its contents on cargo clean"
2. Therefore, there will not be any files/folders not managed by cargo inside the designated folder. Since adding such a folder/file would result in deletion upon cargo clean.
3. We can view this as "the act of specifying a folder as `CARGO_TARGET_DIR` is equivalent to giving cargo free reign over its contents."
4. Therefore, cargo, upon creation of the target directory, can detect if it is a symlink, and if so, instead of creating `$CARGO_TARGET_DIR/{debug,release,...}` cargo can create `$CARGO_TARGET_DIR/shared_target/{debug,release,...}` or `$CARGO_TARGET_DIR/target/{debug,release,...}` just as easily.
5. Then, on cargo clean, detect if the `CARGO_TARGET_DIR` is a symlink, and if so, the folder passed to the recursive delete fn is just `$CARGO_TARGET_DIR/target` instead.
6. This admittedly changes the internal folder composition for people using a symlink directly, but since they've already told cargo "do whatever you want with the contents and structure of this folder" it should be safe to do.
7. The only possible issue would be if some external application besides cargo relied on `$CARGO_TARGET_DIR` internal folder structure, which can be solved by making sure the breaking change is documented and only done on a major version change. But to be honest, cargo should not be making guarantees on the internal folder structure to outside applications, and this should be a "private" concern, as if relying on it would be like relying on a private method/member in an API.

This might be better as a separate pull request.

**Comment by junderw** [comment] 2021-11-07 00:19
This can probably be implemented by checking at the beginning for $CARGO_TARGET_DIR is a symlink or not, and if it isn't, store $CARGO_TARGET_DIR internally as cache directory, and if it is a valid symlink, store $CARGO_TARGET_DIR/target internally as the cache directory for the duration of the program (command).

**Comment by jonhoo** [comment] 2021-11-10 02:39
I would definitely worry a bit about `CARGO_TARGET_DIR` not _actually_ being the target dir, but rather something under it. There are almost certainly scripts out there that rely on `$CARGO_TARGET_DIR` (even though they _should_ instead be using the `target_dir` output from `cargo metadata`).

**Comment by junderw** [comment] 2021-11-10 04:15
Is the folder structure of target something that is guaranteed?

If not, then an external script relying on it would be akin to "using a private interface with @ts-ignore in TypeScript"

**Comment by jonhoo** [comment] 2021-11-13 20:42
Heh, "guaranteed" is unclear. There are definitely _lots_ of tools that expect a certain layout of `target`. Whether they _should_ is a different question..

**Comment by junderw** [comment] 2021-11-13 21:16
it should also be noted that a normal `rm -rf` on a symlink to a folder has the same behavior of just deleting the symlink.

Maybe:

1. detect if target is symlink
2. it is, so dislay a warning to stderr saying "target is a symlink. cargo clean will only delete the symlink and not the contents. Try setting the target folder to a subfolder of the symlinked folder if you want the contents to be cleaned."

Or add a command flag to clean ie. `--resolve-symlinks` which resolves target to dest, then does `rm -rf dest/*`
