### ISSUE TITLE
panic on package cleanup

### ISSUE THREAD

**Issue by Byter09** [rust-lang/cargo#8173] opened 2020-04-28 09:36 UTC
**Problem**

The original problem happened after we updated to Rust 1.43. The new builder image of course also includes the new cargo, rustfmt, etc.

Apart from the usual fixes like the new clippy lints, the kcov job started to fail.
Thanks to @Nemo157 on Discord it turned out the problem isn't kcov but an internal call to clean up.

**Steps**

That's kind of tricky because this is a proprietary project and I can not reproduce this using new and empty projects. I will continue trying it when nothing else comes up but otherwise all I can do is report this as good as I can and then continue doing other work related tasks. Anyway, here are the steps using the redacted project names from the log file at the end of the issue:
1. `cd <redacted-project1>/rusty` (this is our rust component)
2. `cargo clean --package rusty`
and you're greeted by `thread 'main' panicked at 'assertion failed: self.host', src/tools/cargo/src/cargo/core/profiles.rs:920:13`

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
`cargo 1.43.0 (3532cf738 2020-03-17)`

```
$ rustc --version
rustc 1.43.0 (4fb7144ed 2020-04-20)
$ uname -a
Linux BTR-PC 5.6.7-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:50:31 UTC 2020 x86_64 GNU/Linux
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
```
Note for the above: We're also building for other toolchains but I don't have them installed because we use the CI for that - it shouldn't matter though, as this happens in kcov which uses `stable-x86_64-unknown-linux-gnu`.

Here's the output from `CARGO_LOG=debug cargo clean --package rusty`:
[redacted.log](https://github.com/rust-lang/cargo/files/4544689/redacted.log)

**Comment by ehuss** [comment] 2020-04-28 12:42
Thanks, this is a known issue, closing as a duplicate of #8149.

**Closed by ehuss** 2020-04-28 12:42 UTC
Labels: C-bug
