### ISSUE TITLE
`cargo package` doesn't work with child packages

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/cargo#849] opened 2014-11-12 15:17 UTC
```
$ cargo package --verbose
   Packaging encoding v0.2.0 (file:///path/to/rust-encoding)
   Archiving .gitignore
[snip]
   Archiving src/util.rs
   Verifying encoding v0.2.0 (file:///path/to/rust-encoding)
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to verify package tarball

Caused by:
  no package named `encoding-index-japanese` found (required by `encoding`)
location searched: the package registry
version required: ^1.0.20140915
```

`Cargo package` only archives files for the *current* package, the strategy which do not work for packages with child packages like rust-encoding (index tables) or gl-rs (generators). This is primarily a problem of `PathSource::list_files_*` excluding child packages, but also a problem of the basic design---"should one archive represent only one package?".

**Comment by alexcrichton** [comment] 2015-01-14 04:26
I'm closing this as it's working as intended, but I've opened https://github.com/rust-lang/cargo/issues/1169 to make this more ergonomic.

**Closed by alexcrichton** 2015-01-14 04:26 UTC
