### ISSUE TITLE
Feature: cargo build --frozen-registry

### ISSUE THREAD

**Issue by kpcyrd** [rust-lang/cargo#4913] opened 2018-01-07 22:41 UTC
### Steps to reproduce:
- `docker run -it --rm rust:latest`
- `git clone https://github.com/some-repo-with-cargo-lock
- `cargo build --release --frozen-registry`

### Expected behaviour:
The dependencies are downloaded right away, without updating the registry

This seems to be a common request (#4783), there's currently --locked, which is still cloning the registry, and --frozen, which refuses any http at all. What I'm looking for is a way in-between, that just downloads the dependencies as specified inside my Cargo.lock. Fetching the registry takes forever on slow networks. :)

**Comment by alexcrichton** [comment] 2018-01-08 15:42
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/3479, however, so I'm going to close in favor of that.

**Closed by alexcrichton** 2018-01-08 15:42 UTC
