### ISSUE TITLE
cargo update - show information on why an update could not choose latest version

### ISSUE THREAD

**Issue by cemoktra** [rust-lang/cargo#14856] opened 2024-11-25 11:15 UTC
### Problem

I wanted to solve an advisory using `cargo update -p <crate>`, the command updated the dependency a bit, but not to the version where the advisory was fixed, e.g. latest version was `0.1.16` but `cargo update -p <crate>` ended in `0.1.12`.

As this what not a direct dependency it was hard to figure out which other indirect dependency would need an update. I tried to figure out the dependencies using `cargo tree -g <growing number> -i -p <crate>@<version>` but with growing depth it was impossible to track this down. 

### Proposed Solution

In case cargo could not update to the latest version, print the dependency that pinned the version to this specific version.
An alternative might be adding some filtering to cargo tree that allows for example to filter out all dependency that are part of the workspace as i knew it was not a direct dependency.

**Comment by epage** [comment] 2024-11-25 14:58
This sounds like a duplicate of #7929 and closing in favor of that.  If there is a reason for us to keep this open on its own, let us know!

**Closed by epage** 2024-11-25 14:58 UTC
Labels: C-feature-request, A-dependency-resolution, S-triage
