### ISSUE TITLE
Print status message when git is going to take a long time

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#3811] opened 2017-03-10 02:08 UTC
Sometimes, libgit's threaded_find_deltas will take several minutes. This causes cargo to appear to do nothing while taking 100% CPU. It would be nice if cargo could print a message when it is going to do so.

One time I've specifically noticed this is when upgrading between cargo versions and I depend on the rand crate (which has a very big git history due to being forked from rust)

**Comment by alexcrichton** [comment] 2017-03-10 16:56
Agreed! Would be awesome to bind these functions and inform what's going on

**Comment by carols10cents** [comment] 2017-10-02 20:49
I'm going to close this as a duplicate of #4261. Please reopen if I'm mistaken! Thanks!!

**Closed by carols10cents** 2017-10-02 20:49 UTC
