### ISSUE TITLE
error: api errors (status 200 OK): invalid upload request: invalid value: string "dep:sendgrid", expected a valid feature name at line 1 column 1080

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/cargo#8862] opened 2020-11-15 21:16 UTC
**Steps**

1. git clone https://github.com/GopherJ/json-rules-engine-rs
2. cd json-rules-engine-rs
3. cargo publish

**Possible Solution(s)**

**Notes**

Output of `cargo version`: cargo 1.49.0-nightly (d5556aeb8 2020-11-04)

**Comment by ehuss** [comment] 2020-11-15 21:35
This has been fixed in a newer nightly.  Can you try the latest (2020-11-15)?

**Comment by GopherJ** [comment] 2020-11-15 21:49
sure let me try

**Comment by GopherJ** [comment] 2020-11-15 22:04
Seems incompatible:

```
error[E0514]: found crate `cc` compiled by an incompatible version of rustc
   --> /home/cheng/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/build.rs:478:21
    |
478 |         let mut c = cc::Build::new();
    |                     ^^
    |
    = help: please recompile that crate using this compiler (rustc 1.50.0-nightly (98d66340d 2020-11-14))
    = note: the following crate versions were found:
            crate `cc` compiled by rustc 1.49.0-nightly (cf9cf7c92 2020-11-10): /home/cheng/Projects/Rust/json-rules-engine-rs/target/debug/deps/libcc-df21a582d0e3383a.rlib

error: aborting due to previous error

error[E0514]: found crate `once_cell` compiled by an incompatible version of rustc
 --> /home/cheng/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.8/src/noop_waker.rs:6:5
  |
6 | use once_cell::sync::Lazy;
  |     ^^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.50.0-nightly (98d66340d 2020-11-14))
  = note: the following crate versions were found:
          crate `once_cell` compiled by rustc 1.49.0-nightly (cf9cf7c92 2020-11-10): /home/cheng/Projects/Rust/json-rules-engine-rs/target/debug/deps/libonce_cell-09b09081dcb28b23.rmeta

error: aborting due to previous error

error[E0514]: found crate `lazy_static` compiled by an incompatible version of rustc
   --> /home/cheng/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.17/src/lib.rs:234:1
    |
234 | extern crate lazy_static;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: please recompile that crate using this compiler (rustc 1.50.0-nightly (98d66340d 2020-11-14))
    = note: the following crate versions were found:
            crate `lazy_static` compiled by rustc 1.49.0-nightly (cf9cf7c92 2020-11-10): /home/cheng/Projects/Rust/json-rules-engine-rs/target/debug/deps/liblazy_static-88e83b46113e8454.rmeta

error: aborting due to previous error

error[E0514]: found crate `futures_core` compiled by an incompatible version of rustc
  --> /home/cheng/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.8/src/mpsc/mod.rs:81:5
   |
81 | use futures_core::stream::{FusedStream, Stream};
   |     ^^^^^^^^^^^^
   |
   = help: please recompile that crate using this compiler (rustc 1.50.0-nightly (98d66340d 2020-11-14))
   = note: the following crate versions were found:
           crate `futures_core` compiled by rustc 1.49.0-nightly (cf9cf7c92 2020-11-10): /home/cheng/Projects/Rust/json-rules-engine-rs/target/debug/deps/libfutures_core-bafe9494a629a15e.rmeta

error: aborting due to previous error

error: build failed

```

**Comment by GopherJ** [comment] 2020-11-15 22:26
but seems `rustc 1.46.0 (04488afe3 2020-08-24)` worked, shall I close this?

**Comment by ehuss** [comment] 2020-11-15 22:33
Which commands did you run to encounter those "incompatible version" errors?  That generally shouldn't happen.  When running `cargo package` or `cargo publish`, it builds in a fresh directory so there shouldn't be any older files.  If you were running `cargo build`, that shouldn't fail either since Cargo should detect the new version and trigger a rebuild.

**Comment by GopherJ** [comment] 2020-11-16 18:03
@ehuss cargo publish

**Comment by ehuss** [comment] 2020-11-23 17:41
Hm, that's strange.  I'm uncertain how that could happen.  The paths `/home/cheng/Projects/Rust/json-rules-engine-rs/target/debug/deps/` indicate it isn't using the correct target directory.

I'm going to close this for now.  If you're ever able to reproduce the "incompatible versions" error, feel free to leave a comment or file a new issue.  Maybe check if you have any environment variables (like `CARGO_TARGET_DIR`) or any cargo config files, or maybe some unusual rustup overrides.

**Closed by ehuss** 2020-11-23 17:41 UTC
Labels: C-bug
