### ISSUE TITLE
path override problem for erlang_nif-sys

### ISSUE THREAD

**Issue by goertzenator** [rust-lang/cargo#3548] opened 2017-01-16 21:18 UTC
I use path overrides to bring in [erlang_nif-sys](https://crates.io/crates/erlang_nif-sys), but since upgrading from rust-1.12.0 this has stopped working.

Here is minimal setup starting with `cargo new hello_world --bin`:

Cargo.toml
```rust
[package]
name = "hello_world"
version = "0.1.0"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]

[dependencies]
erlang_nif-sys = "0.5"
```
src/main.rs
```rust
#[macro_use]
extern crate erlang_nif_sys;

fn main() {
    println!("Hello, world!");
}
```

~/.cargo/config
```
paths = ["/home/goertzen/erlang_nif-sys"]
```

~/erlang_nif-sys
```
git clone https://github.com/goertzenator/erlang_nif-sys
```

With rust-1.12 this builds properly, but with 1.13, 1.14, beta, and nightly I get this:

```
$ cargo build
   Compiling hello_world v0.1.0 (file:///home/goertzen/hello_world)
error[E0463]: can't find crate for `erlang_nif_sys`
 --> src/main.rs:2:1
  |
2 | extern crate erlang_nif_sys;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `hello_world`.
```

I'm not sure what to do here.  The combination of hyphen and underscore in the crate name makes me suspicious.

**Comment by alexcrichton** [comment] 2017-01-17 07:21
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/3191 and has to do with different versions listed. I'd recommend using a `[replace]` section nowadays instead of a `paths` override if you can, as that should work much better! In any case https://github.com/rust-lang/cargo/issues/3191 also covers providing a better error message than the nonexistent one here (from Cargo at least) so I'm going to close.

**Closed by alexcrichton** 2017-01-17 07:21 UTC
