### ISSUE TITLE
cargo fmt doesn't format the match arms

### ISSUE THREAD

**Issue by unworthyEnzyme** [rust-lang/cargo#10786] opened 2022-06-23 22:32 UTC
### Problem

cargo fmt was formatting the match arms correctly until i added more arms.

### Steps

1. clone this [repository](https://github.com/unworthyEnzyme/teeny-tiny-compiler-in-rust)
2. goto match statement at line 141
3. change the indentation at any of the match arms
4. run cargo fmt

### Version

```text
cargo 1.63.0-nightly (03a849043 2022-06-19)
release: 1.63.0-nightly
commit-hash: 03a849043e25104e8b7ad0d4a96c525787b69379
commit-date: 2022-06-19
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Home Single Language) [64-bit]
```

**Comment by ehuss** [comment] 2022-06-23 22:59
Thanks for the report!  `cargo fmt` is just the front-end for the `rustfmt` tool which has its own issue tracker over at https://github.com/rust-lang/rustfmt/issues/.  

I believe this is a duplicate of https://github.com/rust-lang/rustfmt/issues/3863.  The existence of really long strings causes rustfmt to give up.  The [`format_strings`](https://rust-lang.github.io/rustfmt/?version=master&search=#format_strings) option can be used to force it to format those lines.

**Closed by ehuss** 2022-06-23 22:59 UTC
Labels: C-bug

**Comment by unworthyEnzyme** [comment] 2022-06-25 20:33
setting the `format_strings`  to `true` solved it for me thank you.

**Comment by unworthyEnzyme** [comment] 2022-06-25 20:34
> Thanks for the report! `cargo fmt` is just the front-end for the `rustfmt` tool which has its own issue tracker over at https://github.com/rust-lang/rustfmt/issues/.
> 
> I believe this is a duplicate of [rust-lang/rustfmt#3863](https://github.com/rust-lang/rustfmt/issues/3863). The existence of really long strings causes rustfmt to give up. The [`format_strings`](https://rust-lang.github.io/rustfmt/?version=master&search=#format_strings) option can be used to force it to format those lines.

setting the `format_strings`  to `true` solved it for me thank you.
