### ISSUE TITLE
Beta regressions "failed to parse manifest"

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#4365] opened 2017-08-05 14:12 UTC
I've filed a few bugs on rust-lang/rust to track all beta regressions there, but these regressions are in fact caused by cargo:

* https://github.com/rust-lang/rust/issues/43660
* https://github.com/rust-lang/rust/issues/43668
* https://github.com/rust-lang/rust/issues/43675
* https://github.com/rust-lang/rust/issues/43685

They are all of the form:

```
error: failed to parse manifest at `/source/Cargo.toml`

Caused by:
  can't find `tests` test, specify test.path
```

Or similar.

**Comment by alexcrichton** [comment] 2017-08-05 15:13
cc @matklad, mind taking a look here?

**Comment by matklad** [comment] 2017-08-05 17:36
Yeah, those definitely should just work, without any warnings. Will try to take a look this evening!

**Comment by matklad** [comment] 2017-08-06 09:59
Huh, that's curious! 

The root of error here is that all these crates specify `includes` key in Cargo.toml and don't publish tests. So, a **published** crate has a  `[[test]] name = "foo"` in the `Cargo.toml`, but not `tests/foo.rs`.

Previously, Cargo assumed that the path for `foo` would be `tests/foo.rs`, and the actual error would appear only during `cargo test`. After my recent refactoring, Cargo now checks that the file is present during manifest parsing phase. w
So, the two question here are

1) How we should fix regression?

2) What is the expected behavior? 


For the 2), I believe we should give eager errors when you are developing a package (current behavior), but at the same time allow crate authors to easily exclude tests, benchmarks and examples from packaging (old behavior).

With this in mind, a straightforward solution is store all "target not found" errors in a `critical_warnings` field while parsing Cargo.toml, and emit them only for non-dependent packages (the same way that `warnings` works today, but with actually failing the build).

Does this plan sounds reasonable? It's kinda hacky in that critical warnings in dependent packages are legitimate, but looks like this is what we want in the end!

I knew that that refactoring will cause some regressions 😩 On the other hand, now we can make the test-suite more thorough :)

**Comment by alexcrichton** [comment] 2017-08-07 06:47
Thanks for the investigation here @matklad! If that's the case though I think I'd be totally fine calling this "not a regression". This is only a regression in the sense of how crater runs, which is working directly from crates.io crates.

Do you think we should definitely take action here though? I can't think of a reason this'd cause a "real regression" in practice.

**Comment by matklad** [comment] 2017-08-07 08:29
>This is only a regression in the sense of how crater runs, which is working directly from crates.io crates.

Unfortunately this is not the whole truth :( The problem are dependencies. If a dep does not have test code, then the downstream crate will fail to build when parsing dep's manifest.

**Comment by alexcrichton** [comment] 2017-08-07 23:48
Ah ok thanks for the clarification, and no worries about the regression! That's why we have beta :)

In that case your recommendation sounds great to me! Would you be willing to help implement that as well?

**Comment by matklad** [comment] 2017-08-09 09:09
>Would you be willing to help implement that as well?

Sure!

**Comment by est31** [comment] 2017-08-17 21:31
@matklad from the [latest cargobomb report](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/index.html) for `1.20.0-beta.2` it seems the regression is only fixed for glusterfs-exporter. The other crates still give errors.

**Comment by matklad** [comment] 2017-08-20 16:41
More weirdness: https://github.com/rust-lang/cargo/issues/4293#issuecomment-323575131

**Comment by alexcrichton** [comment] 2017-08-22 18:51
I believe the errors are all false positives, the manifests on crates.io are still invalid and the change here was to get them working as dependencies, which they are, so closing.

**Closed by alexcrichton** 2017-08-22 18:51 UTC

**Comment by YoEight** [comment] 2019-09-23 08:00
Greetings,

I'm experiencing that issue with 1.37.0 version (I can't reproduce it with 1.36.0).

```
~/c/eventstore-rs ❯❯❯ cargo package                                                                                                                                                                                                     master
   Packaging eventstore v0.4.2 (/home/ylaupa/code/eventstore-rs)
   Verifying eventstore v0.4.2 (/home/ylaupa/code/eventstore-rs)
error: failed to verify package tarball

Caused by:
  failed to parse manifest at `/home/ylaupa/code/eventstore-rs/target/package/eventstore-0.4.2/Cargo.toml`

Caused by:
  can't find `integration` test, specify test.path
```

I got that issue when I try to package my lib https://github.com/YoEight/eventstore-rs. Fortunately, it is not a blocking issue as I can `--skip-verify` my way out.

If you want to reproduce the bug with my repo, you would probably have to install OpenSSL library. I believe it's `libssl-dev` on Ubuntu.

Thanks for your time.

**Comment by YoEight** [comment] 2019-09-23 08:05
@matklad Thanks for the quick feedback, I create a new issue right away.

**Comment by YoEight** [comment] 2019-09-23 08:28
Done here https://github.com/rust-lang/cargo/issues/7412
