### ISSUE TITLE
rustc-link-lib from crate not referenced from rust code ignored (even if it *is* referenced in C code)

### ISSUE THREAD

**Issue by sporksmith** [rust-lang/cargo#11160] opened 2022-09-29 01:22 UTC
### Problem

At a high level I'm working on migrating [a project](https://github.com/shadow/shadow) from C to Rust, and we currently have several crates that contain both C and Rust code.

We've found that dependencies seem to be silently dropped if they aren't referenced by the Rust code. This ultimately results in a linker failure when the dependency *is* referenced by the C code.

### Steps

Example code: 
[cargo-dep-bug.tar.gz](https://github.com/rust-lang/cargo/files/9669923/cargo-dep-bug.tar.gz)

Here we have 2 crates `foo` and `bar`, each with some C code:

```
./Cargo.toml
./bar
./bar/Cargo.toml
./bar/src
./bar/src/bar.c
./bar/src/lib.rs
./bar/build.rs
./Cargo.lock
./foo
./foo/Cargo.toml
./foo/src
./foo/src/foo.c
./foo/src/foo.h
./foo/src/lib.rs
./foo/build.rs
```

`foo` provides only a single function `foofn`, in its C code.

`bar` calls `foofn` from `barfn` in *its* C code, and has a unit test in its `lib.rs` that calls `barfn`:

```
extern "C" {
    pub fn barfn();
}

#[test]                                                                                   
fn testfn() {
    unsafe { barfn() };
}  
```

Running `cargo test` gives a linker error; it appears that the `foo` crate isn't getting linked at all. There's a corresponding `-L` flag but no `-l` flag.

```
$ cargo test
   Compiling cc v1.0.73
   Compiling foo v0.1.0 (/home/jnewsome/projects/dev-journal/cargo-dep-bug/foo)
   Compiling bar v0.1.0 (/home/jnewsome/projects/dev-journal/cargo-dep-bug/bar)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcmAQtF9/symbols.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.1r65y1mbtyrj82iv.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.1t8egli32fscgar2.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.26sfhe9ioc9tikw.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.29wyyu6zl9xdrfrm.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.2f40atnf65utw7up.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.2k0mo3zcke9q8lvu.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.2y3lbodfyb8ik5w1.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.32jtsm3n7x4e7sg5.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.34k3dwdvcszz0m77.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.38714p0xy3bfyx6g.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.4lag1l7qf1ceu8x2.rcgu.o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4.2nrnv842wjz59fad.rcgu.o" "-Wl,--as-needed" "-L" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps" "-L" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/build/bar-ed4202956f7576ee/out" "-L" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/build/foo-06631a4c4af9b1fa/out" "-L" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lbar-c" "-Wl,--no-whole-archive" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-81437525acdf876f.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-95f26ed43a8edc57.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-bdad580ec1018657.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-d36618b380f7b689.rlib" "-Wl,--start-group" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1d51e5d3b7e10e45.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-6089560e93d34184.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-43d20762d0bb7e09.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-6edd452aefe0a041.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3815ac605faab09f.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-6e3605e972ebb43d.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-f118607e61af33f8.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-8e61bdcba3672756.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-95839217d3b9249e.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-749d449e05f93229.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-7edc02a093eb63c8.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-e7be36355fcf1fc5.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-65da4ccaaaee1509.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-337a10389ca122a0.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-9dba3f083c9eb142.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-bad49ba9d811b615.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "-Wl,--end-group" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-714f8e833892dd98.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/jnewsome/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/jnewsome/projects/dev-journal/cargo-dep-bug/target/debug/deps/bar-6568ecd9858e6fb4" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs
```

### Possible Solution(s)

The workaround I've found is to add some reference to the dependency from the Rust code. Using the same example we can add to `bar/src/lib.rs`:

```
#[allow(unused)]
use foo;
```

After which `cargo test` succeeds.

In the broken version, I suspect that cargo is trying to be clever by dropping the corresponding `-l` flag for `foo` since it doesn't appear to be referenced. Maybe this optimization could just be dropped?

### Version

```text
$ cargo version --verbose
cargo 1.65.0-nightly (ce40690a5 2022-08-09)
release: 1.65.0-nightly
commit-hash: ce40690a5e4e315d3dab0aae1eae69d0252c52ac
commit-date: 2022-08-09
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```
```

**Comment by weihanglo** [comment] 2022-09-29 18:28
Thank you for the report. The root cause is more or less the same as #9391, which [ehuss indicates](https://github.com/rust-lang/cargo/issues/9391#issuecomment-825066972) that,

> `rustc` does not load or link an external crate if there are no references to it.

Adding `extern crate foo as _` could hint rustc to link the correct crate.

Close since it is a duplicate of #9391. Please leave comments here if you think it should remain open.

**Closed by weihanglo** 2022-09-29 18:28 UTC
Labels: C-bug
