### ISSUE TITLE
`cargo build` failed on non-related platform dependency

### ISSUE THREAD

**Issue by cathay4t** [rust-lang/cargo#8848] opened 2020-11-10 14:51 UTC
**Problem**

The `cargo vendor` will include all dependency regardless platform. After removed the windows dependency,
the `cargo build` will fail on missing dependency even compiling on unix.

**Steps**
```bash
cargo new bug_test
cd bug_test
mkdir .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"' > .cargo/config

echo '[target."cfg(windows)".dependencies.winapi]
version = "0.3"' >> Cargo.toml
cargo build
```

**Possible Solution(s)**

No idea

**Notes**

Output of `cargo version`:  cargo 1.47.0 (f3c7e066a 2020-08-28)

**Comment by cathay4t** [comment] 2020-11-10 14:56
This might related to https://github.com/rust-lang/cargo/issues/7058 where people are questing `cargo vendor --platform unix`.

**Comment by ehuss** [comment] 2020-11-10 15:27
Yea, I'm going to close this as a duplicate of #7058 (and related to #5133).  The resolver needs all dependencies regardless of platform, so it is expected that it will fail.

**Closed by ehuss** 2020-11-10 15:27 UTC
Labels: C-bug
