### ISSUE TITLE
Line numbers in Cargo.toml related error messages please

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo#9687] opened 2021-07-14 07:23 UTC
As rust projects grow it becomes more important to have excellent error messages.

Part of that is being able to pinpoint the source span of an issue in a particular Cargo.toml (in the same way that rustc does). This enables IDEs to be able to go directly to the source line in question.

When we're dealing with one crate at a time this is less of an issue, but if you're dealing with 100 crates then line numbers really help speed up getting to the location of the error so that it can be quickly fixed.

(Apoligies if this is a dupe, I did look but surprisingly couldn't find a similar issue)

**Comment by gilescope** [comment] 2021-07-14 10:30
I see we can use `toml::Spanned` for fields in the `TomlManifest` that we're interested in giving detailed line number information about - I'd suggest we start with just dev/build/dependencies having associated line numbers and see where we go from there.

**Comment by ehuss** [comment] 2021-07-14 14:16
There are similar issues such as #7548 and #6144. It would be nice, but quite a large change.

**Comment by ehuss** [comment] 2021-08-03 18:51
I'm going to close as a duplicate of the above linked issues.

**Closed by ehuss** 2021-08-03 18:51 UTC
Labels: C-feature-request
