### ISSUE TITLE
`cargo check` doesn't check documentation code fences

### ISSUE THREAD

**Issue by thegranddesign** [rust-lang/cargo#4565] opened 2017-10-02 21:15 UTC
Considering a lot of people would use the output of `cargo check` in their editors to verify correctness of their code before running their tests, one would assume that `cargo check --all` would run compiler checks of the code in the docs tests, unfortunately that doesn't seem to be the case.

### Current Behavior

It's possible for `cargo check --all` to run clean but `cargo test` to fail with compiler errors.

### Expected Behavior

When docs have code fences that have compiler errors:

`cargo check --all`

and a new command option:

`cargo check --docs`

would fail.

**Comment by carols10cents** [comment] 2017-10-03 18:05
Actually this looks like a duplicate of #3431 -- that issue is still open because `cargo check --all` does not include tests or doc tests. Closing as a duplicate, thank you for the report! ❤️

**Closed by carols10cents** 2017-10-03 18:05 UTC
Labels: C-feature-request, Command-check
