### ISSUE TITLE
`cargo doc --open` doesn't work in WSL

### ISSUE THREAD

**Issue by pearzl** [rust-lang/cargo#7557] opened 2019-11-03 18:52 UTC
I'm using ubuntu(WSL) in windows, and I found this problem.

At the beginning, without any configuration, I got some error message. Following the error message, I set BROSWER environmental variable, and the error was gone and browser is opened. However nothing appear, seems it open browser but forget pass the "*.html".

I'm sure it the BROWSER is set correctly, because follow command `/usr/bin/sensible-browser xxx/inndex.html` works well in shell.

**Comment by aQaTL** [comment] 2020-02-24 20:34
I think it's due to the fact that the browsers gets called with the WSL path to the file. So a browser on windows won't be able to open a link from the linux filesystem. Maybe cargo should detect that we're on WSL and use the windows default browser and convert the path?

**Comment by parker-codes** [comment] 2020-06-22 22:36
A short-term solution is to run `explorer.exe .` or point it to your project path, navigate to `/target/doc/{package_name}`, and then double-click `index.html`.

**Comment by szeiger** [comment] 2020-09-08 21:51
This appears to be a bug in `wslview` which is fixed in wslu (https://github.com/wslutilities/wslu/issues/133) but not yet in Ubuntu's non-standard wslu package (https://bugs.launchpad.net/ubuntu/+source/wslu/+bug/1888869).

**Comment by TheButlah** [comment] 2020-09-21 16:31
In the course of investigating this, I tracked the issue to the `opener` crate. I've filed an issue there: https://github.com/Seeker14491/opener/issues/8

**Comment by DAmNRelentless** [comment] 2020-12-16 11:15
It would be really nice to have this fixed since more and more Windows users are using WSL to develop their projects.
The workaround with opening the `index.html` manually works fine for now.

**Comment by TheButlah** [comment] 2020-12-16 14:51
Yeah I presented to my team to show them Rust and the windows useres were confused when cargo doc didn't work for them out of the box - not a good look

**Comment by DAmNRelentless** [comment] 2020-12-20 18:08
> Yeah I presented to my team to show them Rust and the windows users were confused when cargo doc didn't work for them out of the box - not a good look

Don't know which editor/IDE your team is using but in case of VSCode, there is an extension which provides in-editor preview of the docs. It currently has a bug but I already reported it and if that's sorted, it should be a nice alternative for your Windows users.
Right here: https://github.com/JScearcy/rust-doc-viewer/issues/18

**Comment by aobatact** [comment] 2021-03-05 10:14
This can be solved with below
```shell:open_browser.sh
# open_browser.sh
#! /bin/bash
#echo $1
winPath="file://///wsl$//Ubuntu${1}"
#echo ${winPath}
#firefox
/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe $winPath
#chrome
#/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe $winPath
```
and add`export BROWSER='xxx/open_browser.sh'` to ~/.bashrc

**Comment by devashishdxt** [comment] 2021-03-31 03:48
If you use Brave Browser with Ubuntu 20.04:

- Create `~/.scripts/open_browser.sh`

```
#!/bin/bash
winPath="file://wsl%24/Ubuntu-20.04${1}"
/mnt/c/Program\ Files/BraveSoftware/Brave-Browser/Application/brave.exe $winPath
```

- Mark it as executable `chmod +x ~/.scripts/open_browser.sh`
- Add `export BROWSER='~/.scripts/open_browser.sh'` to `~/.bashrc`

Now, `cargo doc --open` should work as expected.

**Comment by makuzaverite** [comment] 2021-04-23 18:53
@devashishdxt I used your script but seems not helpful to me 

![image](https://user-images.githubusercontent.com/53856673/115917061-f4caea80-a475-11eb-8fc1-5f4adda464c9.png)

**Comment by elinx** [comment] 2021-05-08 15:27
1. To handle the whitespaces in command path issue, create a soft link to windows browser in `.bashrc`:
```
ln -sf "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" $HOME/.local/bin/chrome
export BROWSER=$HOME/.local/bin/chrome.sh
```
2. translate linux path into windows path use `wslpath -w` command(chrome.sh), then use the soft linked browser open the html page:
```bash
filePath=`wslpath -w ${1}`
~/.local/bin/chrome $filePath
```

**Comment by pfesenmeier** [comment] 2021-08-24 22:23
> 
> 
> This can be solved with below
> 
> ```shell
> # open_browser.sh
> #! /bin/bash
> #echo $1
> winPath="file://///wsl$//Ubuntu${1}"
> #echo ${winPath}
> #firefox
> /mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe $winPath
> #chrome
> #/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe $winPath
> ```
> 
> and add`export BROWSER='xxx/open_browser.sh'` to ~/.bashrc

This works! Unfortunately it breaks `gh repo view --web`. Here is a quick fix:
```bash
#! /bin/sh

# firefox
BROWSER="/mnt/c/Program Files/Mozilla Firefox/firefox.exe"

# chrome
# BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe" 

# if launched from gh
if echo $1 | grep -q "github"; then
 "$BROWSER" $1
 exit 0
fi

# if launched from cargo
winPath="file://///wsl$//Ubuntu${1}"
"$BROWSER" $winPath
```

**Comment by shishi** [comment] 2021-09-25 19:12
Thank you for ideas. I add some fixes because I manage local repos by golang style which is often have `github` dir :D

if this script named wsl_browser.sh,

```shell
#! /bin/sh

# firefox
# BROWSER="/mnt/c/Program Files/Mozilla Firefox/firefox.exe"

# chrome
# BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe" 

# vivaldi
BROWSER="/mnt/c/Users/[USER_NAME]/AppData/Local/Vivaldi/Application/vivaldi.exe"

# if need file URI pattern
if echo $0 | grep -q "wsl_browser.sh"; then
  "$BROWSER" "file:////wsl$/Ubuntu${1}"
  exit 0
fi

"$BROWSER" $1
```

**Comment by ehuss** [comment] 2021-09-25 20:08
This issue should be resolved as of 1.55. Cargo should now execute `wslview` from the [`wslu`](https://github.com/wslutilities/wslu) package which should be installed by default in images installed from the Microsoft Store.

If people are still having problems with 1.55 or newer, can you provide more detail in what problems you are experiencing? What kind of errors or behavior are you experiencing? Do you have wslu installed? If not, is that a possible solution for you?

**Comment by shishi** [comment] 2021-09-26 08:05
It works after update Cargo 1.55 without BROWSER env!

**Comment by jagunter** [comment] 2021-10-29 18:37
Several of the distributions listed on the `wslu` page note that it is not preinstalled.  Tested on a kali distribution from Microsoft Store and confirmed not installed by default.

When `wslview` is not installed, a generic file not found error is provided when running `cargo doc --open`. A better error message along with a pointer to the `wslu` repository for guidance on installation would be helpful. Otherwise users may be led to falsely believe that their browser is misconfigured in WSL.

**Comment by ehuss** [comment] 2021-10-31 16:21
Thanks for the information, I have opened https://github.com/Seeker14491/opener/issues/12 to try to get a better error message when wslview is not installed.

**Comment by WeiShengv99** [comment] 2021-11-20 09:02
> This issue should be resolved as of 1.55. Cargo should now execute `wslview` from the [`wslu`](https://github.com/wslutilities/wslu) package which should be installed by default in images installed from the Microsoft Store.
```    
Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Opening /home/XXX/project/rust-hello-world/target/doc/rust_hello_world/index.html
warning: couldn't open docs

command 'wslview' did not execute successfully; exit status: 1
command stderr:
<3>init: (22969) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (22979) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (22981) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (22983) ERROR: UtilConnectToInteropServer:307: connect failed 2
```
```
➜  rust-hello-world git:(master) ✗ wslview 
<3>init: (23053) ERROR: UtilConnectToInteropServer:307: connect failed 2
[error]No input, aborting
```
is this resolved in cargo 1.55? 
i have this problem in  
```
➜  rust-hello-world git:(master) ✗ cargo version --verbose 
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by msdrigg** [comment] 2021-12-09 22:19
@WeiShengv99 Can you use wslview to open normal links? Maybe your wslview is broken? It is working for me once I install wslview.

**Comment by WeiShengv99** [comment] 2021-12-11 06:39
> @WeiShengv99 Can you use wslview to open normal links? Maybe your wslview is broken? It is working for me once I install wslview.

@msdrigg  No, my wslview is not broken, it works well.
but I  find something wrong 
 when I run `wslview www.google.com` in windows shell
```
➜  ~ wslview www.google.com
```
it works well.
but if I run  `wslview www.google.com` in vscode shell, 
```
rust-hello-world git:(master) ✗ wslview www.google.com
<3>init: (3834) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (3844) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (3846) ERROR: UtilConnectToInteropServer:307: connect failed 2
<3>init: (3848) ERROR: UtilConnectToInteropServer:307: connect failed 2
```

so, it looks like vscode extension's problem?

![image](https://user-images.githubusercontent.com/35689628/145667029-480eadfa-5a0f-40bb-a61a-5b022458504b.png)
![image](https://user-images.githubusercontent.com/35689628/145667023-d780429b-9c24-4ce5-9a4a-b5274a5f3a2a.png)
![image](https://user-images.githubusercontent.com/35689628/145667050-5958e4ec-ee81-4b65-9758-dedb786813a1.png)

**Closed** 2021-12-15 14:05 UTC
Labels: C-bug, Command-doc, O-windows
