### ISSUE TITLE
Cargo test prints warnings and errors twice

### ISSUE THREAD

**Issue by SBSTP** [rust-lang/cargo#1534] opened 2015-04-18 20:10 UTC
`cargo test` prints all of the errors/warnings twice.
```
simon@Simon-Desktop:~/Projects/celavy/celavy$ cargo test
src/dispatcher.rs:12:5: 12:9 warning: variant is never used: `Quit`, #[warn(dead_code)] on by default
src/dispatcher.rs:12     Quit,
                         ^~~~
src/dispatcher.rs:68:5: 68:18 warning: struct field is never used: `name`, #[warn(dead_code)] on by default
src/dispatcher.rs:68     name: &'a str,
                         ^~~~~~~~~~~~~
src/dispatcher.rs:12:5: 12:9 warning: variant is never used: `Quit`, #[warn(dead_code)] on by default
src/dispatcher.rs:12     Quit,
                         ^~~~
src/dispatcher.rs:68:5: 68:18 warning: struct field is never used: `name`, #[warn(dead_code)] on by default
src/dispatcher.rs:68     name: &'a str,

```

**Comment by alexcrichton** [comment] 2015-04-19 07:54
This is actually a duplicate of https://github.com/rust-lang/cargo/issues/851, and the underlying cause of this is that your library is being compiled normally and with `--test`. The normal compilation is happening because it's necessary to run doctests afterwards. 

You can specify `doctest = false` for now and we'll eventually add more CLI flags to control which tests are run to only build one. For now though this is working as intended.

**Closed by alexcrichton** 2015-04-19 07:54 UTC
