### ISSUE TITLE
assertion failed: self.host

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#8256] opened 2020-05-18 14:55 UTC
```
$ RUST_BACKTRACE=1 cargo clean --package yottadb
thread 'main' panicked at 'assertion failed: self.host', src/tools/cargo/src/cargo/core/profiles.rs:920:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: cargo::core::compiler::unit_dependencies::compute_deps
  13: cargo::core::compiler::unit_dependencies::deps_of
  14: cargo::core::compiler::unit_dependencies::deps_of_roots
  15: cargo::core::compiler::unit_dependencies::build_unit_dependencies
  16: cargo::ops::cargo_clean::clean
  17: cargo::commands::clean::exec
  18: cargo::cli::main
  19: cargo::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  24: std::panicking::try
             at src/libstd/panicking.rs:281
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: main
  28: __libc_start_main
  29: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Steps**
I am not sure how to reproduce this bug.

**Notes**

Output of `cargo version`:

$ cargo version
cargo 1.43.0 (3532cf738 2020-03-17)

I was playing around with SIGKILL and SIGSTOP on cargo, so that might have gotten `target` in an inconsistent state? Here is some of my bash history:
```
33075  cargo test &
33076  kill %1
33077  fg
33078  cargo check
33079  cargo test & kill -SIGSUSPEND %1   # sigsuspend is not actually a signal, this gave an error from `kill`
33080  cargo clean --package yottadb   # this is where the panic first happened
33081  RUST_BACKTRACE=1 cargo clean --package yottadb
```

**Comment by ehuss** [comment] 2020-05-18 15:03
Thanks, this is a duplicate of #8149. This should be fixed in 1.44.

**Closed by ehuss** 2020-05-18 15:03 UTC
Labels: C-bug
