### ISSUE TITLE
cargo nightly doesn't appear to be honoring "default-features = false"

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang/cargo#3090] opened 2016-09-13 21:44 UTC
I depend on a crate (slog-rs) that has the following default features:

```
[features]

default = ["release_max_level_info", "max_level_debug"]
```

In my Cargo.toml, I've defined my dependency as:
```
[dependencies.slog]
version = "1.0.0-alpha6"
default-features = false
features = ["max_level_trace"]
```

I was never able to enable the trace features.   Running ```cargo build --verbose``` shows that all three features are enabled (plus default), so it appears that cargo is not honoring the ```default-features = false``` configuration option.  I would expect in this case to only see ```--cfg feature=\"max_level_trace\"``` passed to rustc.

```
   Compiling slog v1.0.0-alpha6 (file:///home/jozias/projects/slog-rs)
       Fresh time v0.1.35
     Running `rustc /home/jozias/projects/slog-rs/src/lib.rs --crate-name slog --crate-type lib -g --cfg feature=\"max_level_debug\" --cfg feature=\"max_level_trace\" --cfg feature=\"default\" --cfg feature=\"release_max_level_info\" -C metadata=b5fec68b10428a12 --out-dir /home/jozias/projects/trace/target/debug/deps --emit=dep-info,link -L dependency=/home/jozias/projects/trace/target/debug/deps`
```

**Comment by dpc** [comment] 2016-09-13 23:41
Same on stable.

However, I think I've found a reason for this. It's because you're also using `slog_term` and that does not have `no-default`.

So it looks that features are accumulative. Is that correct? Is this by design and decided for? If so, I might need to rethink some things.

**Comment by dpc** [comment] 2016-09-14 00:14
I got more info on IRC and rethinked whole thing. Comments are still welcome, but I think it can be closed.

**Comment by alexcrichton** [comment] 2016-09-14 05:52
Ah yes to disable the default set of features then *all* dependencies on `slog` will need to disable the default feature set. Perhaps that didn't happen here though?

**Comment by dpc** [comment] 2016-09-14 05:54
Yes, that exactly what was happening. Other libraries were not disabling the defaults.

**Comment by alexcrichton** [comment] 2016-09-14 06:02
Ah ok, in that case this appears to be working as intended, so closing.

**Closed by alexcrichton** 2016-09-14 06:02 UTC
