### ISSUE TITLE
error when using cargo under cygwin with custom .gitconfig

### ISSUE THREAD

**Issue by cyplo** [rust-lang/cargo#2698] opened 2016-05-16 08:36 UTC
Hi !

I have a custom .gitconfig system where I link to the common part and the platform-specific part in the main one. It seems to be bothering cargo though. Other git operations perform without problems using this config. Let me know if I can help in any way here.

thanks a lot !

```shell
$ cargo install rustfmt --verbose
Updating registry `https://github.com/rust-lang/crates.io-index`
[7/-1] Failed to parse config file: Invalid configuration key (in D:/cygwin64/home/cplotnicki/.gitconfig:1, column 0)

$ cat .gitconfig
[include]
    path = dev/dotfiles/.gitconfig_includes.common
    path = dev/dotfiles/.gitconfig_includes.cygwin

$ mv .gitconfig .gitconfig.tmp

$ cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling syntex_syntax v0.32.0
   Compiling regex v0.1.69
   Compiling env_logger v0.3.3
   Compiling rustfmt v0.5.0
  Installing D:\cygwin64\home\cplotnicki\.cargo\bin\cargo-fmt.exe
  Installing D:\cygwin64\home\cplotnicki\.cargo\bin\rustfmt.exe
be sure to add `D:\cygwin64\home\cplotnicki\.cargo\bin` to your PATH to be able to run the installed binaries

$ rustc --version
rustc 1.8.0 (db2939409 2016-04-11)

$  cargo --version
cargo 0.9.0-nightly (8fc3fd8 2016-02-29)


```

**Comment by alexcrichton** [comment] 2016-05-16 16:48
Hm I wonder if there was perhaps something interesting about how that file was encoded? (maybe something like a utf-8 BOM?) I unfortunately can't reproduce locally

**Comment by retep998** [comment] 2016-05-16 17:32
>I have a custom .gitconfig system where I __link__ to the common part and the platform-specific part in the main one.

How exactly are you doing this linking?

**Comment by retep998** [comment] 2016-05-16 17:33
Is that gitconfig using a cygwin symbolic link perhaps?

**Comment by cyplo** [comment] 2016-05-16 19:42
That is correct indeed, I used `ln -s` to create that link.
Here's the very file: https://github.com/cyplo/dotfiles/blob/master/.gitconfig.cygwin

**Comment by alexcrichton** [comment] 2016-05-16 20:18
Ah yeah then this is probably a "cygwin symlinks are not real symlinks" issue. The files that cygwin emits for symlinks aren't actually underlying symlinks, and they require an emulation layer in cygwin itself to deal with that. Cargo, however, calls into system APIs directly rather than through the cygwin APIs, so unfortunately that doesn't work.

As a result though this is working as intended so I'm going to close this for now. I'd recommend either just copying the files into place or using the true symlink support for windows (which may unfortunately be difficult) in the meantime.

**Closed by alexcrichton** 2016-05-16 20:18 UTC
