### ISSUE TITLE
Dependency directory kinds when building dependent crates

### ISSUE THREAD

**Issue by alilee** [rust-lang/cargo#2158] opened 2015-11-20 13:43 UTC
I'm cross-compiling a (very) bare-metal program from osx to arm (along a reasonably well-travelled path!).

    [dependencies]
    core = { path = "core" }
    rlibc = "0.1.4"

Error:

    $ cargo build --target=arm-none-eabi --verbose
       Compiling rlibc v0.1.4
         Running `rustc [...]/rlibc-0.1.4/src/lib.rs \
                        --crate-name rlibc --crate-type lib -g \
                        -C metadata=f21067c861e5133f \
                        -C extra-filename=-f21067c861e5133f \
                        --out-dir [...]/target/arm-none-eabi/debug/deps \
                        --emit=dep-info,link --target arm-none-eabi \
                        -L dependency=[...]/target/arm-none-eabi/debug/deps \
                        -L dependency=[...]/target/arm-none-eabi/debug/deps \
                        --cap-lints allow`
           Fresh core v0.1.0 (file:///Users/alilee/arm/core)
    [...]rlibc-0.1.4/src/lib.rs:1:1: 1:1 error: can't find crate for `core` [E0463]

The `-L dependency=` kind is not being used to find `libcore.rlib` and if I run the rustc command manually changing to `-L crate=` or `-L all=` then the command finishes and `rlibc.rlib` is built.

Is there a way to get cargo to emit different kinds of -L in a dependency? What is the correct way to direct the dependent crate `rlibc` to find core?

I've tried adding the -L as a parameter to my package's cargo call, however these `cargo rustc` parameters don't seem to propagate to the dependency crates.

    	@cargo rustc --target $(TARGET) -- -L all=./target/$(TARGET)/debug/deps

Happy to write this up if you could give me a clue! Many thanks!

**Comment by alexcrichton** [comment] 2015-11-20 17:17
Ah this is actually intentional, currently, because this is compiling rlibc which doesn't have a dependency on core. Crates aren't currently allowed to depend on anything they don't explicitly depend upon. As such, I'm going to close this as working as intended.

Currently when compiling for a new target the best way to do this is to create your own sysroot with libcore/libstd (as appropriate) inside it and then make sure `--sysroot` is passed to the compiler somehow. We hope to make this a better situation in the future!

**Closed by alexcrichton** 2015-11-20 17:17 UTC

**Comment by alilee** [comment] 2015-11-21 09:34
Ok, so this issue lives at the nexus of cross-compiling, cargo and multirust. Don't mind me, just setting up the SEO ring:

http://stackoverflow.com/questions/28031806/cannot-link-against-core-library-when-cross-compiling

https://github.com/brson/multirust/issues/20

**Comment by alilee** [comment] 2015-11-21 10:12
@alexcrichton Thanks very much for the comment. 

Can I get your sense that this is simply a matter of copying my `libcore.rlib` into a `rustlib/arch` directory?

    $ cd ~/.multirust/toolchains/nightly/lib/rustlib/arm-none-eabi/
    $ ls
    libcore-47c0e7f81fd07753.rlib

(You can guess that this didn't work on its own!)

**Comment by alexcrichton** [comment] 2015-11-22 18:49
Yeah in theory that's all you need to do, but did that not work out?

**Comment by alilee** [comment] 2015-11-23 11:19
Great! I was just missing the final lib:

    $ cd ~/.multirust/toolchains/nightly/lib/rustlib/arm-none-eabi/lib
    $ ls
    libcore-47c0e7f81fd07753.rlib
    $

Thanks heaps.

**Comment by Ericson2314** [comment] 2016-08-08 19:56
https://github.com/rust-lang/rfcs/pull/1133 would make rlibc depend on core.
