### ISSUE TITLE
Document that you shouldn't explicitly set --target to the default

### ISSUE THREAD

**Issue by lilith** [rust-lang/cargo#3817] opened 2017-03-11 00:43 UTC
Using a `--target` value that matches `rustup show` causes a range of bugs. 

1. https://github.com/rust-lang/cargo/issues/3665
2. https://github.com/rust-lang/rust/issues/33145#issuecomment-285822372

```
cargo 0.18.0-nightly (5db6d64 2017-03-03)
rustc 1.17.0-nightly (b1e31766d 2017-03-03)
```
Both `target/$PROFILE/` and `target/$TARGET/$PROFILE` folders are populated with binaries, nearly all of which are duplicates. 

Issues seem to be more common in projects with a sufficiently large dependency graph. And when compiling for windows targets.

**Comment by alexcrichton** [comment] 2017-03-12 04:11
I... is there a bug here? Sorry I'm not really following what would be necessary to close this issue...

**Comment by nathanaeljones** [comment] 2017-03-12 20:15
There's a theme; it's possible the two bugs have a shared root cause. Ideas as to where to look would be helpful. 

I would also suggest warning users away from --target=[default] in the meantime.

**Comment by alexcrichton** [comment] 2017-03-13 22:23
Ah ok, would you be ok if I closed this issue in favor of those two then? This issue may not itself facilitate the fix much and we can otherwise continue discussion of the various bugs in those respective places.

**Comment by nathanaeljones** [comment] 2017-03-14 06:57
I would suggest documentation that using `--target` with the default target is not tested/supported yet.

**Comment by dwijnand** [comment] 2019-01-22 22:58
Is that still worth documenting, (almost) 2 years in?

**Closed** 2019-12-22 03:59 UTC
Labels: A-documenting-cargo-itself, C-feature-request
