### ISSUE TITLE
corrupt metadata, .cargo/bin/cargo-fmt does not exist when it should

### ISSUE THREAD

**Issue by maximih** [rust-lang/cargo#2632] opened 2016-05-01 14:18 UTC
I had 2 `rust-fmt` versions installed and I tried to remove both of them. However, after removing the first one, I get an error when trying to remove the second one. 

Here are all the steps:

```
$ cargo install --list
cargo-check v0.1.0:
    cargo-check
rustfmt v0.2.1:
    cargo-fmt
    rustfmt
rustfmt v0.4.1:
    cargo-fmt
    rustfmt

$ cargo uninstall rustfmt
error: There are multiple `rustfmt` packages in your project, and the specification `rustfmt` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  rustfmt:0.2.1
  rustfmt:0.4.1

$ cargo uninstall rustfmt:0.2.1
    Removing /Users/mX/.cargo/bin/cargo-fmt
    Removing /Users/mX/.cargo/bin/rustfmt

$ cargo uninstall rustfmt:0.4.1
error: corrupt metadata, `/Users/mX/.cargo/bin/cargo-fmt` does not exist when it should

$ cargo install --list
cargo-check v0.1.0:
    cargo-check
rustfmt v0.4.1:
    cargo-fmt
    rustfmt
```

**Comment by alexcrichton** [comment] 2016-05-02 16:58
Hm the metadata ahead of time appears corrupt because the same crate was installed twice.

I think this is a dupe of https://github.com/rust-lang/cargo/issues/2275, so I'm gonna close in favor of that, but if you have steps to reproduce please let me know!

**Closed by alexcrichton** 2016-05-02 16:58 UTC
