### ISSUE TITLE
`cargo build` completes in workspace root, but fails in a workspace member.

### ISSUE THREAD

**Issue by drbawb** [rust-lang/cargo#11551] opened 2023-01-07 15:39 UTC
### Problem

I have a small workspace that contains two crates (a client and server) as an exercise in playing around with async I/O. A git tree that exhibits the error can be found [here.](https://git.sr.ht/~hime/protochat/tree/cargo-bug)

The problem is that when I run `cargo build` at the workspace root it compiles the client crate `linetest`, and server crate `smolboi` successfully. However when I `cd` into my server crate it fails to compile with a failure to resolve a trait:

```
drbawb@nagato:rust/protochat/smolboi  8df68f3 ✔ 
▶ cargo build
   Compiling smolboi v0.1.2 (/home/drbawb/dev/rust/protochat/smolboi)
error[E0432]: unresolved imports `futures_util::AsyncReadExt`, `futures_util::AsyncWriteExt`
 --> smolboi/src/util.rs:2:20
  |
2 | use futures_util::{AsyncReadExt, AsyncWriteExt};
  |                    ^^^^^^^^^^^^  ^^^^^^^^^^^^^ no `AsyncWriteExt` in the root
  |                    |
  |                    no `AsyncReadExt` in the root
  |
help: consider importing this trait instead
  |
2 | use futures_util::{smol::io::AsyncReadExt;
  |                    ~~~~~~~~~~~~~~~~~~~~~~~
help: consider importing this trait instead
  |
2 | use futures_util::{AsyncReadExt, smol::io::AsyncWriteExt;
  |                                  ~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0432`.
error: could not compile `smolboi` due to previous error
```

This error _seems to be correct._ In reading [the documentation](https://docs.rs/futures-util/0.3.25/futures_util/io/index.html) for `futures_util` these traits are re-exported from the `futures_util::io` module which is gated behind a feature flag. (One interesting thing to note is that my runtime of choice, `smol`, re-exports these traits. These are shown as a suggestion in the error message; however the error message gives an erroneous path to them.)

My expectation would be that `cargo build` either succeeds or fails uniformly regardless of my position in the workspace directory tree.

My toolchain is as follows:

```
drbawb@nagato:rust/protochat/smolboi  8df68f3 ✔
▶ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/drbawb/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2020-05-31-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.68.0-nightly (0fb8b72ce 2023-01-06)
```

### Steps

1. `git clone --branch cargo-bug https://git.sr.ht/~hime/protochat`
2. `cd protochat` to enter the workspace root
3. `git checkout HEAD~1` to rewind to the problem
4. `cargo build` from the workspace root and observe that it works. (**Which it shouldn't.**)
5. `cd smolboi` and `cargo build` from the member root to observe that it fails.
6. `git checkout cargo-bug` and `cargo build` to observe the issue is now resolved simply by including the `io` feature gate.

### Possible Solution(s)

In hazarding a guess I suspect what may be happening is the async runtime `smol` is enabling this feature flag in their own crate to re-export them. So somehow when running `cargo build` from my workspace root that feature is (incorrectly?) getting applied to one of my member crates.

### Version

```text
cargo 1.68.0-nightly (8c460b223 2023-01-04)
release: 1.68.0-nightly
commit-hash: 8c460b2237a6359a7e3335890db8da049bdd62fc
commit-date: 2023-01-04
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by ehuss** [comment] 2023-01-07 16:38
Thanks for the report! This is intentional behavior where the set of features enabled depends on which packages you are building (only those being built will get unified, those not participating in the build do not influence it). You'll need to make sure that if a package depends on some dependency's features to be enabled that it has them enabled.  There are a few ways to do this:

* Add the dependency with the features desired.
* Use [workspace inheritance](https://doc.rust-lang.org/cargo/reference/unstable.html#workspace-inheritance) and define the dependencies in one place with the features you want.
* Use a "[workspace hack](https://github.com/rust-lang/rust/tree/master/src/tools/rustc-workspace-hack)" where you have an empty workspace member that depends on the packages and features you want, and then have the members depend on that so they all get unified the same.

Closing as a duplicate of #4463

**Closed by ehuss** 2023-01-07 16:38 UTC
Labels: C-bug
