### ISSUE TITLE
Add env var for applying flags to cargo commands

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/cargo#10622] opened 2022-05-02 05:06 UTC
### Problem

I prefer to use `--locked` in some environments where the use of the lock file to ensure an exact reproducible install of a binary is important. However, it is too easy to forget to add the `--locked`.

### Proposed Solution

Add an environment variable for each cargo command that can specify flags that will be applied to the use of that command.

For example:

A new env var could be named `CARGO_INSTALL_FLAGS`. If the env var is defined it is assumed as part of the arguments to the cargo command as if those arguments had been supplied at that specific invocation.

### Notes

This proposal is similar to the RUSTFLAGS env var that exists for rustc.

**Comment by ehuss** [comment] 2022-05-24 15:50
Closing as a duplicate of #8207.  If it is added to the config, then it will also get an environment variable.

**Closed by ehuss** 2022-05-24 15:50 UTC
Labels: C-feature-request
