### ISSUE TITLE
Rebuild triggered after `touch`ing a (git submodule) file under the `registry/src` directory 

### ISSUE THREAD

**Issue by Ben-PH** [rust-lang/cargo#10223] opened 2021-12-21 10:50 UTC
### Initial presentation of bug

In our CI pipeline, one of our dependencies (specifically rocksdb) will run a rebuild, despite being cached.

### Steps

I am using `rocksdb` as a representative 

1. Make minimalist `hello, world!` executable
2. Add `rocksdb = "0.17.0"` as a dependency. 
3. install `clang` or `llvm` as per the [crate requirements](https://crates.io/crates/rocksdb)
4. `cargo build` 
5.a.  `rm -rf ~/.cargo/registry/src`
5.b. (alternate rebuild trigger) `touch /path/to/registry/src/directory/librocksdb-sys-6.20.3/rocksdb`
6. run `cargo build` and observe the rebuild being triggered.

To validate this is unique, I followed the steps with other executables using the `rm` option, without any issues.

### Possible Solution(s)

* given the bug is reproduced with a `touch`, issue #8623  could fix it
* issue #7987 is another issue relating to caching of a submodule
* issue #7935 relates to mtimes, and may offer some insights.

### Notes

The re-build appears to be triggered by [this line of code](https://github.com/rust-rocksdb/rust-rocksdb/blob/86d983987e7cafce90ad8a147b0b325e6007eba6/librocksdb-sys/build.rs#L306)

The CI setup is following the advice outlined [here](https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci)

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by alexcrichton** [comment] 2021-12-21 15:22
You can try seeing why Cargo is rebuilding with:

```
export CARGO_LOG=cargo::core::compiler::fingerprint=info
```

and that should print out why the rebuild is happening

**Comment by Ben-PH** [comment] 2021-12-29 10:00
```
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint] stale: changed "/home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.20.3/rocksdb/"
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint]           (vs) "/home/ben/rust/repro/target/debug/build/librocksdb-sys-66a9853c3d7cfb95/output"
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint]                FileTime { seconds: 1640771696, nanos: 604901852 } != FileTime { seconds: 1640771857, nanos: 395909002 }
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint] fingerprint error for repro v0.1.0 (/home/ben/rust/repro)/Build/TargetInner { name: "repro", doc: true, ..: with_path("/home/ben/rust/repro/src/main.rs", Edition2021) }
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint]     err: current filesystem status shows we're outdated
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint] fingerprint error for rocksdb v0.17.0/Build/TargetInner { ..: lib_target("rocksdb", ["lib"], "/home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/rocksdb-0.17.0/src/lib.rs", Edition2018) }
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint]     err: current filesystem status shows we're outdated
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint] fingerprint error for librocksdb-sys v6.20.3/Build/TargetInner { ..: lib_target("librocksdb-sys", ["lib"], "/home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.20.3/src/lib.rs", Edition2018) }
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint]     err: current filesystem status shows we're outdated
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint] fingerprint error for librocksdb-sys v6.20.3/RunCustomBuild/TargetInner { ..: custom_build_target("build-script-build", "/home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.20.3/build.rs", Edition2018) }
[2021-12-29T09:57:37Z INFO  cargo::core::compiler::fingerprint]     err: current filesystem status shows we're outdated
```

**Comment by Ben-PH** [comment] 2021-12-29 10:09
the following in our `ci.yml` file prevents the rebuild:
```yml
    - name: Zero mtimes of deps
      run: |
        set -euxo pipefail
        CARGO_DIR="${CARGO_HOME:-$HOME/.cargo}"
        for source in "$CARGO_DIR"/registry/cache/*/; do
          pushd "$source"
          source=$(basename -- "$PWD")
          mkdir -p "$CARGO_DIR/registry/src/$source"
          for crate in *.crate; do
            crate=${crate%.crate}
            mkdir "$CARGO_DIR/registry/src/$source/$crate" || continue
            tar --strip-components=1 -xzf "$crate.crate" -C "$CARGO_DIR/registry/src/$source/$crate"
            echo -n ok > "$CARGO_DIR/registry/src/$source/$crate/.cargo-ok"
          done
          popd
        done
        find "$CARGO_DIR/registry/src" -exec touch -cfht 197001010000 {} +
        ```

**Comment by alexcrichton** [comment] 2022-01-04 15:18
Does the rocksdb build script print out a `rerun-if-changed` pointing at the directory? If so that may be the cause of this.

**Comment by epage** [comment] 2023-11-03 14:45
#11613 has us no longer checking the mtime for "immutable" sources.  It looks like that should resolve this, so I'm closing this.  If there is a reason to reconsider, let us know!

**Closed by epage** 2023-11-03 14:45 UTC
Labels: C-bug, A-rebuild-detection
