### ISSUE TITLE
Allow creating new projects from pre-defined templates

### ISSUE THREAD

**Issue by hamza1311** [rust-lang/cargo#9775] opened 2021-08-08 16:26 UTC
**Describe the problem you are trying to solve**

Getting started with Rust frameworks is a cumbersome task. Especially the frameworks which require boilerplate to be used. WASM web frameworks is one example of such frameworks. The user is forced to choose between two options:
1. Create the boilerplate manually - either copy/paste it from documentation or write it out by hand
2. Use a tool like [`cargo-generate`](https://github.com/cargo-generate/cargo-generate)

**Describe the solution you'd like**

- A new command such as `cargo init <template>`
- Add this functionality to `cargo new --template`

PS: I'd be happy to clarify anything in case I missed some information

**Comment by ehuss** [comment] 2021-08-09 13:28
Thanks for the request!  I'm going to close this as a duplicate of #5151.  Adding template support will require an RFC (such as https://github.com/rust-lang/rfcs/pull/2922).

**Closed by ehuss** 2021-08-09 13:28 UTC
Labels: C-feature-request
