### ISSUE TITLE
cargo vendor fetches incomplete crate

### ISSUE THREAD

**Issue by jamin-aws-ospo** [rust-lang/cargo#10532] opened 2022-04-01 22:51 UTC
### Problem

I tried to configure https://github.com/jpeddicord/askalono for building offline.

I clone the repo, change to the cli folder, and issue: `cargo vendor`.  I then create the `.cargo/config` as instructed.  However, attempting an offline build with `cargo build --offline` results in this error:

```
error: failed to run custom build command for `zstd-sys v1.6.0+zstd.1.5.0`
﻿
Caused by:
  process didn't exit successfully: `/home/jamin/tmp/askalono/cli/../target/debug/build/zstd-sys-f29cef9d59229dd4/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Folder 'zstd/lib' does not exists. Maybe you forgot to clone the 'zstd' submodule?', /home/jamin/tmp/askalono/cli/vendor/zstd-sys/build.rs:180:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

The `cli/vendor/zstd-sys` folder is indeed missing the `zstd/lib` folder.

However, checking the same crate version shows that the folder is present in the crate.

### Steps

1. `git clone https://github.com/jpeddicord/askalono`
2. cd `askalono/cli`
3. `cargo vendor`
4. create the suggested `../.cargo/config`
5. `cargo build --offline`

### Version

```text
$ cargo version --verbose
cargo 1.59.0 (49d8809dc 2022-02-10)
release: 1.59.0
commit-hash: 49d8809dc2d3e6e0d5ec634fcf26d8e2aab67130
commit-date: 2022-02-10
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by ehuss** [comment] 2022-04-04 18:42
This is an issue with zstd-sys v1.6.0.  It had an [exclude pattern](https://github.com/gyscos/zstd-rs/blob/3636f9e9f7af04dca3d03e7d3b21b5f142155b5b/zstd-safe/zstd-sys/Cargo.toml#L22-L28) which prevented the `zstd` directory from being included.  You'll need to update to a newer version of zstd (which appears like you already have).

Closing as a duplicate of #9555.

**Closed by ehuss** 2022-04-04 18:42 UTC
Labels: C-bug
