### ISSUE TITLE
DEP_* env variable not set in nightly test run

### ISSUE THREAD

**Issue by kamulos** [rust-lang/cargo#9063] opened 2021-01-11 13:23 UTC
This happens with the nightly version, but not with the stable.

```
> cargo +nightly version
cargo 1.51.0-nightly (329895f5b 2021-01-06)
```
### Reproduce
Cargo.toml
``` toml
[package]
name = "asdf"
version = "0.1.0"
authors = ["xyxy"]
edition = "2018"

[dependencies]
libsodium-sys = "0.2"

[build-dependencies]
cc = "1.0"
```

test.c
``` c
void test() {}
```

build.rs
``` rust
fn main() {
    cc::Build::new()
        .file("test.c")
        .include(std::env::var_os("DEP_SODIUM_INCLUDE").expect("DEP_SODIUM_INCLUDE is not set"))
        .compile("test.a");
}
```

Now just run `cargo +nighly test`. With stable this works perfectly, with nightly the `DEP_SODIUM_INCLUDE` env variable is not set.

**Comment by ehuss** [comment] 2021-01-11 14:39
@alexcrichton I think this was caused by #8969.  When running `cargo test`, the test unit has a dependency edge to the local build script.  Since tests got disconnected, that causes the build script to start building too early (before the libsodium-sys build script runs).

**Comment by alexcrichton** [comment] 2021-01-11 18:45
Thanks for the report! I think this should be fixed by https://github.com/rust-lang/cargo/pull/9065. Sorry about the breakage!

**Comment by rylev** [comment] 2021-01-12 17:26
FYI: This caused only [one breakage](https://crater-reports.s3.amazonaws.com/beta-1.50-1/beta-2021-01-01/reg/allegro_examples-0.0.41/log.txt) in the latest [crater run](https://crater-reports.s3.amazonaws.com/beta-1.50-1/index.html).

**Closed** 2021-01-12 17:47 UTC
Labels: regression-from-stable-to-beta
