### ISSUE TITLE
Make cargo recognize commands from uninstalled plugins

### ISSUE THREAD

**Issue by estebank** [rust-lang/cargo#11226] opened 2022-10-12 21:58 UTC
### Problem

When executing `cargo foo`, without having executed `cargo install cargo-foo` beforehand, the error message will be something along the lines of

```
error: no such subcommand: `foo`

        Did you mean `doc`?
```

Given that we can have the full list crates available to us, we *can* detect that a user is trying to use a not-yet-installed subcommand.

**Comment by weihanglo** [comment] 2022-10-12 22:20
> Given that we can have the full list crates available to us, we can detect that a user is trying to use a not-yet-installed subcommand.

Mind that the precondition might not be fulfilled when the sparse-index becomes the default in the future, unless we address it with a solution like #10928.

**Comment by epage** [comment] 2022-10-12 22:22
btw some recent improvements around "no such command" was done in #10924

**Comment by epage** [comment] 2022-10-12 22:26
Until we have a full list of crates, we could potentially check the registry specifically for `cargo-foo` **but**
- We would want to do this `offline` as it would be surprising to reach out over the network
- Sparse registry only caches locally what you use which would make `offline` checking for `cargo-foo` very limited

**Comment by epage** [comment] 2022-10-12 22:28
Would it be worthwhile to always add a suggestion `To install the command, run 'cargo install cargo-foo'` until we can show it only when needed?

I lean towards "no" but thought it worth bringing up.

**Comment by weihanglo** [comment] 2022-10-12 22:38
If Cargo found a crate with the exact name, but it were a malicious/low-quality/abandoned crate, should Cargo recommend it?

**Comment by epage** [comment] 2022-10-12 22:44
Was going to respond but I finally found the issue is this is a duplicate of (I knew I had seen this before).

Closing in favor of #4682, let's continue the discussion there.

**Closed by epage** 2022-10-12 22:44 UTC
Labels: A-errors, C-feature-request, A-custom-subcommands
