### ISSUE TITLE
Access violation on win10 during "cargo build" when ssh crate url

### ISSUE THREAD

**Issue by briangreenery** [rust-lang/cargo#3574] opened 2017-01-21 00:55 UTC
On Windows 10 with `cargo 0.15.0-nightly (298a012 2016-12-20)`

1. Create a new library with `cargo new repro`.
2. Set this as the `Cargo.toml` file:

```
[package]
name = "repro"
version = "0.1.0"

[dependencies]
some-module = { git = "ssh://github.com/rust-lang/not-a-valid-repo.git" }
```

3. Run `cargo build`. Then I get:

<img width="265" alt="screenshot" src="https://cloud.githubusercontent.com/assets/370343/22170321/27ae34a2-df31-11e6-97ac-9db737dbb06d.png">

**Comment by alexcrichton** [comment] 2017-01-21 17:58
Thanks for the report! This may be a dupe of https://github.com/rust-lang/cargo/issues/3401 (unsure). Could you try out nightly Cargo and see if it's fixed for you?

**Comment by briangreenery** [comment] 2017-01-21 19:36
Ah, that fixes it. I now get a "failed to authenticate" error instead of a crash, so it seems like it is a duplicate.

**Closed** 2017-01-21 23:47 UTC
