### ISSUE TITLE
[doc]: Manifest "license" key documentation: SPDX link broken

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/cargo#12910] opened 2023-11-02 11:29 UTC
### Problem

[The "license" key documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) links to "[SPDX 2.1 license expression](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60)" - that link is broken.

### Steps

1. Go to https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
2. Click on "SPDX 2.1 license expression"
3. See that the link is broken

### Possible Solution(s)

I don't know what the actual link is. There's a "2.3" version, but we want to link to "2.1", right?

**Comment by epage** [comment] 2023-11-02 12:15
Try https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/

Closing as this is a dupe of #12797 which has been fixed

**Closed by epage** 2023-11-02 12:15 UTC
Labels: C-bug, S-triage
