### ISSUE TITLE
Custom x86 target breaks openssl_sys crate

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2043] opened 2015-10-08 23:14 UTC
I've successfully built a rustc for the i586-unknown-linux-gnu target which seems to be working flawlessly (tested on a few projects using an i686 cargo binary) but any project, like cargo itself, that requires the openssl_sys crate fails with something like:

````

Compiling libssh2-sys v0.1.30
     Running `rustc /home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/libssh2-sys-0.1.30/lib.rs --crate-name libssh2_sys --crate-type lib -C opt-level=3 -C metadata=8b1940fda472288c -C extra-filename=-8b1940fda472288c --out-dir /home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps --emit=dep-info,link --target i586-unknown-linux-gnu -L dependency=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps -L dependency=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps --extern libz_sys=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps/liblibz_sys-3cc4483070d58543.rlib --extern libc=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps/liblibc-d5e533d3fc4af810.rlib --cap-lints allow -L native=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/build/libssh2-sys-8b1940fda472288c/out/lib -l static=ssh2 -L native=/usr/lib`
/home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/libssh2-sys-0.1.30/lib.rs:8:1: 8:26 error: can't find crate for `openssl_sys` [E0463]
/home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/libssh2-sys-0.1.30/lib.rs:8 extern crate openssl_sys;
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
   Compiling curl-sys v0.1.25
     Running `rustc /home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/curl-sys-0.1.25/lib.rs --crate-name curl_sys --crate-type lib -C opt-level=3 -C metadata=865cd014190c57f1 -C extra-filename=-865cd014190c57f1 --out-dir /home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps --emit=dep-info,link --target i586-unknown-linux-gnu -L dependency=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps -L dependency=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps --extern libc=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps/liblibc-d5e533d3fc4af810.rlib --extern libz_sys=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps/liblibz_sys-3cc4483070d58543.rlib --cap-lints allow -L native=/usr/lib -l curl -L native=/usr/lib`
       Fresh openssl-sys v0.6.4
Build failed, waiting for other jobs to finish...
/home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/curl-sys-0.1.25/lib.rs:5:14: 5:39 error: can't find crate for `openssl_sys` [E0463]
/home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/curl-sys-0.1.25/lib.rs:5 #[cfg(unix)] extern crate openssl_sys;
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `libssh2-sys`.

Caused by:
  Process didn't exit successfully: `rustc /home/petevine/.cargo-i586/registry/src/github.com-121aea75f9ef2ce2/libssh2-sys-0.1.30/lib.rs --crate-name libssh2_sys --crate-type lib -C opt-level=3 -C metadata=8b1940fda472288c -C extra-filename=-8b1940fda472288c --out-dir /home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps --emit=dep-info,link --target i586-unknown-linux-gnu -L dependency=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps -L dependency=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps --extern libz_sys=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps/liblibz_sys-3cc4483070d58543.rlib --extern libc=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/deps/liblibc-d5e533d3fc4af810.rlib --cap-lints allow -L native=/home/petevine/cargo-master/target/i586-unknown-linux-gnu/release/build/libssh2-sys-8b1940fda472288c/out/lib -l static=ssh2 -L native=/usr/lib` (exit code: 101)
make: *** [cargo-i586-unknown-linux-gnu] Error 101
````

Hopefully I'm not making a mistake reporting this issue here. Thx.
(it's not immediately clear if the github project named rust-openssl refers to the crate in question)

**Comment by alexcrichton** [comment] 2015-10-09 16:29
This is currently an [unfortunate limitation](https://github.com/rust-lang/cargo/issues/1007) of the current target-specific dependency format, which can be seen how [the dependency list](https://github.com/alexcrichton/ssh2-rs/blob/master/libssh2-sys/Cargo.toml#L19-L40) is currently just specified exhaustively instead of with `cfg(unix)`. This all ends up meaning that doesn't work so hot with custom target specifications for now.

Otherwise this is basically a dupe of #1007 which would allow fixing this, so I'm going to close this in favor of that.

**Closed by alexcrichton** 2015-10-09 16:29 UTC

**Comment by petevine** [comment] 2015-10-09 16:41
Ok, thanks. 

I'd still like to complete building cargo so if I just modify the Cargo.toml in ssh2 or any other crate requiring openssl-sys, that's going to solve it?

**Comment by alexcrichton** [comment] 2015-10-09 16:56
Yeah that should do it!

**Comment by petevine** [comment] 2015-10-09 18:25
Tedious but effective, thanks!
