### ISSUE TITLE
lock file version 4 requires `-Znext-lockfile-bump`

### ISSUE THREAD

**Issue by Kelvin-1013** [rust-lang/cargo#14655] opened 2024-10-08 15:51 UTC
Maintainer's note:

Lockfile v4 has been stabilized since Rust 1.78.0 ([#12852](https://github.com/rust-lang/cargo/pull/12852)), and become the default version when generating/updating Cargo.lock ([#14595](https://github.com/rust-lang/cargo/issues/14595)) since Rust 1.83.0.

The cause you're hitting this hard may be because: The tool you're using called to an older cargo either directly (via `cargo` executable), or indirectly (depending on `cargo` as a library). However some other parts of your build system called to a newer cargo that generates a lockfile version 4.

Here are solutions (in order of preference):

* Help maintainers of the tool you use to support the latest Cargo, either bumping `cargo` version to [`0.84.0+`](https://crates.io/crates/cargo/0.84.0), or wrapping the `cargo` binary from Rust toolchain 1.83.0+.
* Setting `package.rust-version` to a value older than `1.83` if you haven't prepared to support newer toolchains. For example,
  ```toml
  # Cargo.toml
  [package]
  name = "foo"
  rust-version = "1.82" # or any version older than 1.83
  ```
  This works because starting from Rust 1.78.0, Cargo respects `package.rust-version` when generating lockfiles ([#12861](https://github.com/rust-lang/cargo/pull/12861)). 
* Manually edit the lockfile version `version = "4"` at the top to `version = "3"`.

---

### Problem

![Image](https://github.com/user-attachments/assets/58f3dccd-3f3f-4c49-9813-51bfa1d40a87)
I have tried so many time  but always fail.
Cargo build act, but anchor build not act
help me seniors

**Comment by epage** [comment] 2024-10-08 15:58
Lockfile v4 has been stable since Rust 1.78.  We are making it the default version as of 1.83 nighties unless your MSRV is below 1.78. 

I would look into
- If you can bump your Rust version
- Enforce a lower Rust version is used for anyone who generates the lockfile
- Set `package.rust-version`, if applicable

**Comment by Kelvin-1013** [comment] 2024-10-10 09:43
Thank you for your response.
![Image](https://github.com/user-attachments/assets/41b1dd0c-fd8b-4d70-9803-f81a96364d5c)


![Image](https://github.com/user-attachments/assets/3d5bc65b-c407-4e5e-9b8f-6d391151ea70)

`[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
`

![Image](https://github.com/user-attachments/assets/4e0ea124-b937-42d6-8603-1bf6a4f2e440)

I provide this info, give me advice, seniors

**Comment by epage** [comment] 2024-10-10 13:35
Can you provide full reproduction steps with only `cargo`?

**Comment by Kelvin-1013** [comment] 2024-10-27 05:26
Thank you for your help.

I just modify `resolver=4` to `resolver=3` in Cargo.toml and run `anchor build`, then this issue is resolved.

**Comment by palash2397** [comment] 2024-11-26 14:59
@Kelvin-1013 
In ### Cargo.toml, I changed###  resolver=2 to ### resolver=3, and then I got the following error:


### palash@DESKTOP-QPUGO84:~/my-project$ anchor build
Error: Error reading manifest from path: /home/palash/my-project/Cargo.toml

Caused by:
    0: TOML parse error at line 5, column 12
         |
       5 | resolver = "3"
         |            ^^^
       unknown variant `3`, expected `1` or `2`
       
    1: TOML parse error at line 5, column 12
         |
       5 | resolver = "3"
         |            ^^^
       unknown variant `3`, expected `1` or `2`

**Comment by epage** [comment] 2024-11-26 15:04
`resolver` is for a different meaning than lockfile version

**Comment by palash2397** [comment] 2024-11-26 15:09
@epage 
Then what should I update? Could you please guide me?

**Comment by epage** [comment] 2024-11-26 16:55
As this issue is about lockfiles and you are changing the manifest, this is different.  It would be good to provide standard details for someone to help you
- Reproduction steps outside of anchor
- What problem you are trying to solve by switching to `workspace.resolver = "3"`
- What version of Cargo is being used.

This also looks to more be a Cargo support concern than a bug or feature request, so I would recommend posting about this on https://users.rust-lang.org/

**Comment by 619** [comment] 2024-11-28 22:58
I'm getting the same error

**Comment by acheroncrypto** [comment] 2024-11-29 19:19
Solution in https://github.com/coral-xyz/anchor/issues/3392#issuecomment-2508412018.

Sorry for the disturbance. It would be nice to lock this issue, given the problem is not about this repository.

**Comment by kaka527** [comment] 2024-12-03 13:27
Modify the version = "4" at the top of the Cargo.lock file to version = "3".

**Comment by palash2397** [comment] 2024-12-03 14:12
@kaka527  Thanks a lot, it’s all good now!

**Comment by soupy0x** [comment] 2024-12-12 04:41
> Modify the version = "4" at the top of the Cargo.lock file to version = "3".

Only solution that worked for me, thanks @kaka527

**Comment by trantrongw** [comment] 2024-12-15 09:39
> Modify the version = "4" at the top of the Cargo.lock file to version = "3".

yes. It worked. I don't understand why.

**Comment by rcolomina** [comment] 2024-12-20 22:34
yes, it worked. Many thanks!

**Comment by weihanglo** [comment] 2024-12-24 16:41
I am going to close this, as there is no action needed.

See the updated PR description that provides some solutions if you're stuck.

**Closed by weihanglo** 2024-12-24 16:41 UTC
Labels: C-bug, S-needs-info

**Comment by MartinGerritsen** [comment] 2025-01-03 09:46
Using `RUST_LOG=debug anchor build` I could see that it was my solana cli giving the issues

```
[2025-01-03T09:42:59.141004000Z INFO  cargo_build_sbf] spawn: "/Users/xxx/.cache/solana/v1.39/platform-tools/rust/bin/rustc" --version
[2025-01-03T09:42:59.660304000Z INFO  cargo_build_sbf] Solana SDK: /Users/xxx/.local/share/solana/install/releases/1.18.4/solana-release/bin/sdk/sbf
[2025-01-03T09:42:59.660565000Z INFO  cargo_build_sbf] spawn: "rustup" toolchain list -v
[2025-01-03T09:42:59.677205000Z INFO  cargo_build_sbf] spawn: "cargo" +solana build --release --target sbf-solana-solana
error: failed to parse lock file at: /Users/xxx/WebstormProjects/crypto/xxx/Cargo.lock

Caused by:
  lock file version 4 requires `-Znext-lockfile-bump`
```

Running `solana-install update` fixed it for me

**Comment by hryer** [comment] 2025-01-14 22:48
> Modify the version = "4" at the top of the Cargo.lock file to version = "3".

Confirmed, worked thank's have a same issues and got stuck an hours ago

**Comment by Kelvin-1013** [comment] 2025-01-18 10:04
Here is very interesting news.
https://github.com/Kelvin-1013/solana-presale-program-app-contract/issues/4

**Comment by weihanglo** [comment] 2025-01-18 13:31
@Kelvin-1013 please don't post unrelated cryptocurrency ads here

**Comment by RastaDjuss** [comment] 2025-01-19 06:48
### error: failed to parse lock file at:  

###  Caused` by:  lock file version 4 requires `-Znext-lockfile-bump`

[anarchsun](https://users.rust-lang.org/u/anarchsun)
[4m](https://users.rust-lang.org/t/fixed-and-resolved-error-failed-to-parse-lock-file-at/124284?u=anarchsun)

i was getting this berror when cargo build-sbf or anchor build ..:

cargo build-sbf
error: failed to parse lock file at: /home/anrchsun/devs/ana-cain/Cargo.lock

but if you all could read carefully the solution was given in error message:

Caused by:
lock file version 4 requires -Znext-lockfile-bump

so i ran :slight_smile:

`cargo` build-sbf -- `-Znext-lockfile-bump`

and everything worked fine...

Compiling borsh v0.9.3
Compiling anchor-attribute-access-control v0.30.1
Compiling anchor-attribute-account v0.30.1
Compiling anchor-attribute-error v0.30.1
Compiling anchor-attribute-event v0.30.1
Compiling anchor-attribute-constant v0.30.1
Compiling anchor-derive-serde v0.30.1
Compiling anchor-attribute-program v0.30.1
Compiling anchor-derive-accounts v0.30.1
^[[B Building [=======================> ] 165/169: solana-program, solana-program
Compiling anchor-lang v0.30.1
Compiling ana-chain v0.0.0 (/home/anrchsun/devs/ana-cain/program)
Finished release [optimized] target(s) in 1m 31s..

> Realise with real Eyes... lok when you read!!

**Comment by Kelvin-1013** [comment] 2025-01-19 20:15
https://solana.com/docs/intro/installation
![Image](https://github.com/user-attachments/assets/f4c4c7fe-b158-4351-a174-0d672947e83b)


https://github.com/coral-xyz/anchor/issues/3392 #14903

**Comment by muhammedsirajudeen** [comment] 2025-01-20 06:49
> Thank you for your help.
> 
> I just modify `resolver=4` to `resolver=3` in Cargo.toml and run `anchor build`, then this issue is resolved.

this solved my issue although i would like to know about the root cause

**Comment by Pioneer220** [comment] 2025-01-21 09:10
good, it works, wonderful

**Comment by Linyxus** [comment] 2025-01-27 05:29
> Thank you for your help.
> 
> I just modify `resolver=4` to `resolver=3` in Cargo.toml and run `anchor build`, then this issue is resolved.

Sorry for continuing this discussion that is irrelevant to this repo but I wanted to note that the typo in this comment (`Cargo.toml` should have been `Cargo.lock`) is a bit misleading. I guess that is the main reason why there are more people following up in this thread. @Kelvin-1013 could you fix it? it would be really helpful for other people following Google to find a solution here.

**Comment by weihanglo** [comment] 2025-01-27 13:32
@Linyxus please read the maintainer's note in the PR description.
