### ISSUE TITLE
Doc-tests do not respect linker settings

### ISSUE THREAD

**Issue by madonuko** [rust-lang/cargo#14189] opened 2024-07-04 14:25 UTC
### Problem

Doc-test in `cargo test --doc` and `cargo test` does not respect linker settings in `~/.cargo/config.toml`.

### Steps

1. Paste the following file into `~/.cargo/config.toml`:
```
[target.x86_64-unknown-linux-gnu]
#linker = "gcc"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
```
2. Make any doc-test, whatever you like, then run `cargo test --doc`
3. Notice during normal test compilation and `cargo build`, `mold` is used, but not for doc-tests
4. uncomment `linker = "gcc"`, try again (same behaviour)
5. use `linker = "clang"`, try again (same behaviour)

### Version

```text
cargo 1.79.0 (ffa9cf99a 2024-06-03)
release: 1.79.0
commit-hash: ffa9cf99a594e59032757403d4c780b46dc2c43a
commit-date: 2024-06-03
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ultramarine Linux 40.0.0 (lostumbrella) [64-bit]
```

**Comment by ehuss** [comment] 2024-07-04 15:29
Thanks for the report! I believe this is a duplicate of #12532 and #7040, so closing in favor of those.

You can use `-Zdoctest-xcompile` on nightly to honor the linker flag.
For rustflags, you need to also specify rustdocflags. Conceptually, doctests are going through `rustdoc` which has a different field for specifying its flags.

**Closed by ehuss** 2024-07-04 15:29 UTC
Labels: C-bug, S-triage
