### ISSUE TITLE
cargo rustc --lib -- --crate-type cdylib results in crate required to be available in rlib format

### ISSUE THREAD

**Issue by dvc94ch** [rust-lang/cargo#7899] opened 2020-02-18 11:04 UTC
Building examples for android works great `cargo rustc --example NAME -- --crate-type cdylib`. When trying `cargo rustc --lib -- --crate-type cdylib` I get `crate required to be available in rlib format`.

I found multiple closed issues here related to this #7339 #6160, and was wondering what the correct approach is. Since the crate type can be set in the `Cargo.toml` I think a reasonable case can be made that overriding it from the cli is in the domain of cargo features (as opposed to it's a rustc flag we won't support it)

Related to #4881.

**Comment by ehuss** [comment] 2020-02-25 00:49
I'm going to close this as a duplicate of #4881.  If you have additional requirements of controlling the crate-type that aren't already captured in that issue, it is probably best to just add a comment over there.

**Closed by ehuss** 2020-02-25 00:49 UTC
Labels: C-bug

**Comment by dvc94ch** [comment] 2020-02-26 23:49
In case you hadn't noticed, #4881 is a feature request, this is a bug report. The difference is that the one requests something to be *added* while the other requests something to be *removed*.
