### ISSUE TITLE
cargo check complains about main() being unused

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/cargo#3445] opened 2016-12-22 20:03 UTC
running cargo check on a binary crate gives:
```
warning: function is never used: `main`, #[warn(dead_code)] on by default
   --> main.rs:86:1
    |
86  | fn main() {
    | ^
```

**Comment by alexcrichton** [comment] 2016-12-25 22:12
I believe this is a dupe of https://github.com/rust-lang/rust/issues/38273, but thanks for the report!

**Closed by alexcrichton** 2016-12-25 22:12 UTC
