### ISSUE TITLE
Cargo Crate Details

### ISSUE THREAD

**Issue by shaneutt** [rust-lang/cargo#8034] opened 2020-03-24 02:05 UTC
**Describe the problem you are trying to solve**

I often find when running `cargo search` I want to browse the source of packages that are returned, but often end up in a web browser at https://crates.io to do so when I would prefer to simply `git clone`.

As a Rust developer I want the convenience of being able to use `cargo` to view crate details that otherwise would be easiest to see by visiting the crate's page on https://crates.io.

**Describe the solution you'd like**

I would like to see standard `cargo` include a new sub-command which allows me to view details of a crate quickly.

Perhaps the default view could simply be a small subset of the `Cargo.toml` `[package]` section, e.g.:

```
$ cargo info libc
name = "libc"
version = "0.2.68"
authors = ["The Rust Project Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/libc"
homepage = "https://github.com/rust-lang/libc"
documentation = "http://doc.rust-lang.org/libc"
description = "Raw FFI bindings to platform libraries like libc."
```

More specifically my ideal workflow would be something like this: I search with cargo to find several crates:

```
$ cargo search libc
libc = "0.2.68"             # Raw FFI bindings to platform libraries like libc. 
libc-interface = "0.1.0"    # A library for types often found in libc or other common platform libraries. 
libc-extra = "0.3.2"        # Additional bits and bobs found in libc libraries that either hasn't been submitted to Rust's offici…
avr-libc = "0.1.3"          # Rust bindings to avr-libc. 
libc-strftime = "0.2.0"     # A wrapper library for the glibc strftime function
libc-print = "0.1.11"       # println! and eprintln! macros on libc without stdlib
rs-libc = "0.2.0"           # A subset of libc that can be used with Rust in freestanding environments. 
owasm-libc = "0.2.0"        # Parity WebAssembly standard library libc bindings
pwasm-libc = "0.2.1"        # Parity WebAssembly standard library libc bindings
memchr = "2.3.3"            # Safe interface to memchr.
```

And I'm interested to see the code for `libc`, so I run:

```
$ cargo info libc --repository
https://github.com/rust-lang/libc
```

I want to clone it so I run:

```
$ git clone $(cargo info libc --repository) ./libc
```

**Notes**

In my review of the [third party cargo sub-commands wiki](https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands) the [cargo-info](https://gitlab.com/imp/cargo-info) third party sub-command seems to be the closest thing but the purpose of this PR is to ask if this functionality would be accepted as a core sub-command of `cargo`.

If this is something the maintainers would want to include, I would be happy to create a PR to do so.

**Comment by epage** [comment] 2022-04-20 18:20
Closing this out as its a duplicate of #948

**Closed by epage** 2022-04-20 18:20 UTC
Labels: A-new-subcommand, C-feature-request
