### ISSUE TITLE
failed to authenticate when downloading repository

### ISSUE THREAD

**Issue by jefflembeck** [rust-lang/cargo#3381] opened 2016-12-10 05:50 UTC
While going through the docs, this one hit me:

```
~/code/rust-projects/guessing_game master [!?] $ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `rand`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

To learn more, run the command again with —verbose.
```

The reason I'm hitting this issue is buried in my gitconfig

```
[url "git@github.com:"]
  insteadOf = https://github.com/
```

I am aware that this bug is a byproduct of how I have things set up locally, but since I'm capable of cloning `https://github.com/rust-lang/crates.io-index` without any issues with the above settings, I was hoping that I'd be able to use cargo in that way as well.

Thanks!

**Comment by alexcrichton** [comment] 2016-12-11 18:50
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/2078, but thanks for the report!

**Closed by alexcrichton** 2016-12-11 18:50 UTC

**Comment by DenisKolodin** [comment] 2017-06-14 15:05
Leave it here to help somebody...
I had a similar issue with `ssh:` dependency, but fixed it by starting ssh agent:
```
eval `ssh-agent -s`
ssh-add
cargo ...
```

**Comment by vors** [comment] 2018-05-27 00:53
I had the same setup in a global `~/.gitconfig`

```
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

This is a somewhat common for few reasons. One is to deal with git submodules in a unified way: so you don't need to handle `https::/` vs `git@` differently.

Running `ssh-agent` as @DenisKolodin suggested, didn't work for me. The only way to workaround it was to remove this global config.

**Comment by vors** [comment] 2018-10-17 03:11
oh good point, I was not aware of this difference.

FWIW, there is some work happening in libgit2 that would allow to avoid all such problems all together https://github.com/libgit2/libgit2/pull/4667

**Comment by lunny** [comment] 2019-06-15 04:39
@HaoZeke it didn't fix my issue even if I use 

```ini
[url "git@github.com:"]
        insteadOf = https://github.com/
```

**Comment by tlightsky** [comment] 2020-01-20 12:17
it seems work after i comment 
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

**Comment by dmitrybirin** [comment] 2020-10-16 18:32
Just in case, somebody will land here from google with the same errors (`https://github.com/rust-lang/crates.io-index`), and above ☝️  approaches didn't work, cause you have complicated auth to git from your machine, for example 🤷  
add to your cargo config.toml:

```toml
[net]
git-fetch-with-cli = true
```

The following links from the docs saved my days:
https://doc.rust-lang.org/cargo/appendix/git-authentication.html?highlight=auth#git-authentication
https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

**Comment by asciifaceman** [comment] 2020-11-12 10:10
> Just in case, somebody will land here from google with the same errors (`https://github.com/rust-lang/crates.io-index`), and above ☝️ approaches didn't work, cause you have complicated auth to git from your machine, for example 🤷
> add to your cargo config.toml:
> 
> ```toml
> [net]
> git-fetch-with-cli = true
> ```
> 
> The following links from the docs saved my days:
> https://doc.rust-lang.org/cargo/appendix/git-authentication.html?highlight=auth#git-authentication
> https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Life saver. https git has always caused issues so I've always forced ssh auth

**Comment by Mofankk** [comment] 2021-07-03 18:00
> Leave it here to help somebody...
> I had a similar issue with `ssh:` dependency, but fixed it by starting ssh agent:
> 
> ```
> eval `ssh-agent -s`
> ssh-add
> cargo ...
> ```

The problem appear when I set a dependencies and run `cargo build`, so，after run `ssh-add`，you shou run `cargo build` to instead of `cargo ...`

**Comment by zhaohuxing** [comment] 2021-08-24 10:43
> Leave it here to help somebody...
> I had a similar issue with `ssh:` dependency, but fixed it by starting ssh agent:
> 
> ```
> eval `ssh-agent -s`
> ssh-add
> cargo ...
> ```

Mark

**Comment by YodaEmbedding** [comment] 2021-11-02 03:29
**Workaround from https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584:**

Add this to `~/.cargo/config`:

```toml
[net]
git-fetch-with-cli = true
```

**Comment by IloveKanade** [comment] 2022-04-20 08:40
> ```toml
> [net]
> git-fetch-with-cli = true
> ```
Wow, It's worked!!!!

**Comment by Integralist** [comment] 2022-07-25 08:15
For future travellers this is what I use:

```ini
# force authentication to use SSH rather than HTTPS.
# be aware this affects everything that tries to use git.
# for example, vim (and other tools) will try to clone plugins using SSH.
#
# git config --global --add url."git@github.com:".insteadOf "https://github.com/"
[url "git@github.com:"]
  insteadOf = https://github.com/

# avoid issues where the cargo-edit tool tries to clone from a repo you do not have WRITE access to.
# we already use SSH for every github repo, and so this puts the clone back to using HTTPS.
[url "https://github.com/rust-lang/crates.io-index"]
  insteadOf = https://github.com/rust-lang/crates.io-index

# avoid issues where the `cargo audit` command tries to clone from a repo you do not have WRITE access to.
# we already use SSH for every github repo, and so this puts the clone back to using HTTPS.
[url "https://github.com/RustSec/advisory-db"]
  insteadOf = https://github.com/RustSec/advisory-db
```

**Comment by rizalgowandy** [comment] 2023-02-27 03:14
export CARGO_NET_GIT_FETCH_WITH_CLI=true

**Comment by edjchapman** [comment] 2023-04-13 20:12
Not a great experience for Rust newcomers... It took a while to find this seemingly hacky solution while following the documentation.

**Comment by aetiurf** [comment] 2023-04-16 12:00
> **Workaround from [#2078 (comment)](https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584):**
> 
> To apply **globally**, add this to `~/.cargo/config`:
> 
> ```toml
> [net]
> git-fetch-with-cli = true
> ```

Life saver!

**Comment by zigang93** [comment] 2023-05-06 13:44
> **Workaround from [#2078 (comment)](https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584):**
> 
> To apply **globally**, add this to `~/.cargo/config`:
> 
> ```toml
> [net]
> git-fetch-with-cli = true
> ```
it doen't work for some cargo packages.. such as `cargo-audit`

cargo audit will failed with ssh error

**Comment by phoenixdevguru** [comment] 2023-05-07 04:18
Hi @jefflembeck

I think this issue's caused by your GitHub authentication failure.

Check if SSH key is properly configured: rustup creates a default SSH key when it's installed, but you might need to add it to your GitHub account. Type `ssh -v git@github.com` in your terminal to see if your key is being offered. If you need to add a new key, follow GitHub's SSH key setup guide.

![Screenshot_9](https://user-images.githubusercontent.com/87322890/236657356-6643eea6-0dc0-4f64-8cb1-4dd2713d239f.png)

**Comment by tolu0x** [comment] 2024-01-24 11:02
> Leave it here to help somebody... I had a similar issue with `ssh:` dependency, but fixed it by starting ssh agent:
> 
> ```
> eval `ssh-agent -s`
> ssh-add
> cargo build
> ```

Lifesaver! phew
