### ISSUE TITLE
Subcommand to add a new dependency to Cargo.toml

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#2179] opened 2015-11-29 00:37 UTC
I've grown to appreciate 

```sh
npm install --save packagename
```

which automatically finds the package and adds it to `package.json`. [`composer require`](https://getcomposer.org/doc/03-cli.md#require) works in a similar way.

Cargo isn't as convenient for adding new dependencies to a project. I need to:

1. Visit the crates.io website find the package I want
2. Copy its latest version
3. Paste it to Cargo.toml myself

That's a bit tedious, especially that I have to switch from terminal to a web browser.

I'd be much nicer if Cargo had a command for adding dependencies, e.g.

```sh
cargo require packagename
```

that would find the package on crates.io and add it with an appropriate version to `[dependencies]` in Cargo.toml.

**Comment by steveklabnik** [comment] 2015-11-29 01:10
https://github.com/killercup/cargo-edit provides this

**Comment by pornel** [comment] 2015-11-29 12:09
Good to see others think it's useful to have too. Judging by the long list of dependencies of cargo-edit it looks like it reimplements cargo's code for communicating with the registry, so the implementation would be much smaller if it were built into cargo.

**Comment by huonw** [comment] 2015-11-29 12:30
This is a dupe of the https://github.com/rust-lang/cargo/issues/4, which was in fact closed pointing to `cargo edit`, since `cargo install` now makes it super easy to install it.

**Comment by pornel** [comment] 2015-11-29 13:20
*Knowing* about existence of cargo-edit is a barrier.

For me it went like this:

```sh
$ cargo install package
…
specified package has no binaries
```

…grumble, grumble, advised to use cargo-edit…

```sh
$ cargo install cargo-edit
…
# long list of compiled deps here
…
$ cargo add package
No such subcommand

	Did you mean `doc`?
$ export PATH=$PATH:~/.cargo/bin
$ cargo add package
```

That's not a great experience. Having it listed in `cargo -h` and working out of the box would be much better.

**Comment by alexcrichton** [comment] 2015-11-30 19:40
Yeah as @huonw mentioned this is basically a dupe of #4 so I'm going to close this, but I think it's a good point that discovering subcommands may not be the easiest thing to do today. I've opened https://github.com/rust-lang/cargo/issues/2187 on this topic and we can perhaps have discussion over there!

**Closed by alexcrichton** 2015-11-30 19:40 UTC

**Comment by lig** [comment] 2017-11-15 16:18
You are kidding me. An official package manager bug about not being able to add a dependency via its cli is closed because some other tool out there can do this. Sic.

**Comment by qm3ster** [comment] 2018-03-29 18:20
This issue was compounded for me by `openssl-sys` failing to build (w/o `sudo apt install libssl-dev`)
While this may not belong in cargo (although it may) it should probably at least be adopted in the default rustup bundle?

**Comment by tom-james-watson** [comment] 2018-10-12 14:05
For anyone else confused about the actual answer, first:

```
cargo install cargo-edit
```

after that, you can:

```
cargo add rand
```

etc.

**Comment by Gilgamesh22** [comment] 2018-10-27 03:15
@tom-james-watson thanks for the awesome explanation but I still don't see why cargo-edit is not install by default.

**Comment by dwijnand** [comment] 2018-10-27 09:38
There's an intent to.  It's now being tracked in #5586 and there's a WIP PR against that too.

**Comment by cup** [comment] 2019-06-21 02:15
https://github.com/rust-lang/cargo/issues/1917

https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586
https://github.com/rust-lang/cargo/issues/6457
https://github.com/rust-lang/cargo/issues/6488
https://github.com/rust-lang/cargo/issues/651
https://github.com/rust-lang/cargo/pull/5611

**Comment by MauroMombelli** [comment] 2019-07-07 21:02
just hit my head against this, while trying to make my first step in rust. SUPER frustrating

**Comment by lavoiesl** [comment] 2019-08-21 17:32
Also, installing cargo-edit was a whopping 239 crates for me, that takes quite a while to download and install. Definitely not a great user experience.

**Comment by cup** [comment] 2019-08-21 17:50
@lavoiesl Jesus Christ, that sounds worse than even JavaScript with NPM. What happened to Rust?

**Comment by BurntSushi** [comment] 2019-08-21 18:05
**Moderator note:** Please don't post off topic and unconstructive rants about other software ecosystems in official Rust spaces.

**Comment by leodutra** [comment] 2019-08-30 02:13
But this is constructive. It's a good sample.

**Comment by lavoiesl** [comment] 2019-08-30 03:14
I believe @burntsushi refers to a comment that was deleted

**Comment by BurntSushi** [comment] 2019-08-30 04:44
Indeed.

**Comment by leodutra** [comment] 2019-08-31 09:36
Is there a specific reason for the `add` command, and maybe whole cargo-edit, to not be packed with the standard cargo?

Different hands working on each or some other more specific reason?
I got really curious for this second possibility... :)

**Comment by goofballLogic** [comment] 2019-09-15 17:28
I suspect there's a good reason. Perhaps someone could link a blog or something explaining this design decision?

**Comment by jcollum** [comment] 2019-12-13 23:18
I was surprised by this too. Coming from node having a command that does "add this package and save it in the list of dependencies" should be available out of the gate. I mean, 90% of the time I install something I'm going to be using it as part of my project, so why not save it and save me the trouble of editing the file?

**Comment by kornelski** [comment] 2019-12-14 01:23
It's being worked on: https://github.com/rust-lang/cargo/issues/5586

**Comment by TomaszWaszczyk** [comment] 2020-10-05 20:19
"just hit my head against this, while trying to make my first step in rust. SUPER frustrating"++;

**Comment by qm3ster** [comment] 2020-10-06 07:37
Until #5586, getting `cargo add`, `cargo rm` and `cargo upgrade` is as simple as doing:
```sh
cargo install cargo-edit
```
One more great thing about it is you don't have to reinstall it for every toolchain update.
It's just there, and works.

You can do it after installing `rustup`, or you can do it once you encounter the `error: no such subcommand: add`. It's really not a big deal.

Finding out it exists is the bigger deal. I understand the unwillingness to add it to documentation (eg to the error text when the subcommand is exactly `add`) because the api of the builtin might be different than this third party utility, but not giving usage instructions and saying it will change and so to use `cargo add help` would go a long way. Basically it would prevent the **cli** -> google cargo add -> github/cargo-add -> see it's deprecated -> click deprecation link -> **cli** journey.

**Comment by wongjiahau** [comment] 2020-10-06 13:48
@qm3ster on top of that, `cargo install cargo-edit` somehow pulled around 200 packages:
![image](https://user-images.githubusercontent.com/23183656/95210045-a2014c80-081d-11eb-8092-2f7a80c0af0a.png)

**Comment by kornelski** [comment] 2020-10-06 14:14
It really matters whether it's built-in or something that needs to be installed. For years now, I've pushed for use of `cargo-edit` on https://lib.rs, but users still ask me to provide copy'n'paste alternative that works without it.

**Comment by lig** [comment] 2020-11-20 21:49
@kornelski I'm curious is it possible to install `cargo-edit` package with the toolchain automatically. Also, it would be helpful for an unfamiliar user to see `cargo-edit` commands in `cargo --help`.

**Comment by kornelski** [comment] 2020-11-20 22:02
This is now tracked in #5586

**Comment by baphomutt** [comment] 2022-04-23 08:13
I can't believe I had to find this github issue in order to learn how to add dependencies from the terminal. :P

**Comment by epage** [comment] 2022-04-23 11:38
For anyone on this thread that didn't switch over to the issue posted above (#5586), cargo-add has been merged.  It will take several months for it to go from the nightly to beta and then stable release channels.
