### ISSUE TITLE
rustdoc: Generate docs for all platforms at once

### ISSUE THREAD

**Issue by valarauca** [rust-lang/cargo#3300] opened 2016-11-18 18:18 UTC
The below code:

```rust
#[cfg(target-platform("windows")]
mod winstuff {
     /// Explanation of Windows-specific tasks
}

#[cfg(target-platfrom("linux")]
mod linstuff {
    /// Explanation of Linux-specific tasks
}
```

Will generate different docs depending where it is run, and how it is targeted. There appears to be noway to generate docs in a cross platform manner.

**Comment by steveklabnik** [comment] 2016-11-18 18:25
This is a sorta-kinda-duplicate of https://github.com/rust-lang/rust/issues/1998

**Comment by alexcrichton** [comment] 2016-11-18 20:29
Yeah this is mostly a rustdoc issue rather than a Cargo issue, so I'm going to close this in favor of https://github.com/rust-lang/rust/issues/1998

**Closed by alexcrichton** 2016-11-18 20:29 UTC
