### ISSUE TITLE
List dependency feature flag in cargo search foo

### ISSUE THREAD

**Issue by flipchan** [rust-lang/cargo#11289] opened 2022-10-26 10:31 UTC
### Problem

Hey, 
Is it possible to add the option for listing feature flags with cargo search?
It would be really handy to be able to:
```
cargo search --show-features foo
```

Right now there is no option for viewing feature flags with cargo search so the user got to go to crates.io and check the feature flags.

### Proposed Solution

```
cargo search --show-features foo
```

### Notes

Functionality to display feature flags with cargo search

**Comment by epage** [comment] 2022-10-26 11:20
We have a separate request for a [cargo info](https://github.com/rust-lang/cargo/issues/948) which imo would be a better fit for this as the intent and display format for `cargo search` wouldn't quite work well for this. 

Workarounds:
- Install [cargo info](https://crates.io/crates/cargo-info)
- Run  `cargo add foo --dry-run` (you could make an alias of this if you want)

**Comment by ehuss** [comment] 2022-12-11 19:55
This does seem like something that would be nice to have. I agree that it probably doesn't fit with `cargo search` very well. I'm going to close as a duplicate of #948, which I think would be a potentially good use case for this, as well as the existing `cargo add --dry-run` and `cargo info`.

**Closed by ehuss** 2022-12-11 19:55 UTC
Labels: C-feature-request
