### ISSUE TITLE
cargo check does not check library unittests

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/cargo#4037] opened 2017-05-12 14:27 UTC
Neither `cargo check`, nor `cargo check --tests`, not `cargo check --libs` check in-library tests, which are in `src` directory and marked `#[cfg(test)] #[test]`, not in `tests`.

**Comment by alexcrichton** [comment] 2017-05-12 15:09
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/4003, but thanks for the report!

**Closed by alexcrichton** 2017-05-12 15:09 UTC
