### ISSUE TITLE
Building from source CFG_TARGET isn't set

### ISSUE THREAD

**Issue by wvxvw** [rust-lang/cargo#1494] opened 2015-04-08 13:59 UTC
Hello,

I've tried to build Cargo from source. After I ran `.configure` this file was generated:

``` conf

CFG_PREFIX           := /usr/local
CFG_LOCAL_RUST_ROOT  := 
CFG_RUSTC            := /usr/local/bin/rustc
CFG_BUILD            := 
CFG_HOST             := 
CFG_TARGET           := 
CFG_LOCALSTATEDIR    := /var/lib
CFG_SYSCONFDIR       := /etc
CFG_DATADIR          := /usr/local/share
CFG_INFODIR          := /usr/local/share/info
CFG_MANDIR           := /usr/local/share/man
CFG_LIBDIR           := /usr/local/lib
CFG_LOCAL_CARGO      := 
CFG_CURLORWGET       := /usr/bin/curl
CFG_PYTHON           := /usr/bin/python
CFG_CC               := /usr/bin/cc
CFG_RUSTDOC          := /usr/local/bin/rustdoc
CFG_SRC_DIR          := /home/wvxvw/projects/cargo/
CFG_BUILD_DIR        := /home/wvxvw/projects/cargo/
CFG_CONFIGURE_ARGS   := 
CFG_PREFIX           := /usr/local
CFG_BUILD            := 
CFG_HOST             := 
CFG_TARGET           := 
CFG_LIBDIR           := /usr/local/lib
CFG_MANDIR           := /usr/local/share/man
CFG_RUSTC            := /usr/local/bin/rustc
CFG_RUSTDOC          := /usr/local/bin/rustdoc
```

As you can see `CFG_TARGET` isn't set, but it needs to be set to something (what?) in order for the `all` recipe to do something. What should I set it to? Why isn't it set to anything?

**Comment by alexcrichton** [comment] 2015-04-08 15:42
what is the output of `/usr/local/bin/rustc -vV`?

**Comment by wvxvw** [comment] 2015-04-08 15:51
Ah, sorry, I forgot to look at that, and I'm at a different computer now. I've built Rust on this machine few weeks later, so it's not the same, but should be very close:

``` sh
rustc 1.0.0-dev (ecf8c64e1 2015-03-21) (built 2015-03-21)
binary: rustc
commit-hash: ecf8c64e1b1b60f228f0c472c0b0dab4a5b5aa61
commit-date: 2015-03-21
build-date: 2015-03-21
host: x86_64-unknown-linux-gnu
release: 1.0.0-dev
```

I'll only be able to tell the one I've actually used in the post above no earlier than Sunday.

**Comment by alexcrichton** [comment] 2015-04-08 15:54
Does `configure` work on the machine you're on right now? I think that the error handling for detecting the target is pretty bad and this error probably means there was an error running the compiler itself that the configure script forgot to report.

**Comment by wvxvw** [comment] 2015-04-08 21:32
Aaaand, on this machine it does work. The `configure` script generated `CFG_TARGET := x86_64-unknown-linux-gnu`.

**Comment by wvxvw** [comment] 2015-04-09 20:15
Minor update. I've rebuilt Rust and now Cargo compiles too:

``` sh
rustc 1.0.0-dev (30e7e6e8b 2015-04-08) (built 2015-04-09)
binary: rustc
commit-hash: 30e7e6e8b0389d407f8b46ab605a9e3475a851d5
commit-date: 2015-04-08
build-date: 2015-04-09
host: x86_64-unknown-linux-gnu
release: 1.0.0-dev
```
with this version. This is probably what I'll do with the other computer as soon as I get there, but if you are interested, I'll also post the version of Rust I have there.

**Comment by alexcrichton** [comment] 2015-04-09 23:23
Hm, so can you get the original issue to still reproduce?

**Comment by wvxvw** [comment] 2015-04-12 11:30
It appears that my installation of `rustc` on the machine where I had the initial issue was broken in a way which has nothing to do with Cargo, so I guess there's not much else to do with this issue (I actually couldn't get `rustc` to even print the version info.)

**Comment by alexcrichton** [comment] 2015-04-13 04:59
Hm ok, thanks for confirming!

**Comment by carols10cents** [comment] 2016-02-11 20:45
> It appears that my installation of rustc on the machine where I had the initial issue was broken in a way which has nothing to do with Cargo, so I guess there's not much else to do with this issue

So can this be closed then? Or is it open for handling errors while detecting the target?

**Comment by least-olegs** [comment] 2016-02-11 21:44
Yup, sorry, it was too long ago, but I remember I was able to make it work back then, and the issue was something else entirely, so this report may be thrown away :)

**Comment by alexcrichton** [comment] 2016-02-11 23:07
Ah yeah I think this is basically about handling errors more robustly in the configure script, right now it's not exactly great :(

**Comment by alexcrichton** [comment] 2018-01-03 00:34
The makefiles have since been removed, so closing.

**Closed by alexcrichton** 2018-01-03 00:34 UTC
Labels: A-building-cargo-itself
