### ISSUE TITLE
Panic in cpus util on Mac (cargo 1.39 beta)

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#7455] opened 2019-09-27 18:52 UTC
**Problem**

Trying to compile reqwest on Mac using `cargo 1.39.0-beta (b6c6f685b 2019-09-19)` panics. I don't know if it's specifically reqwest, I don't have a Mac to try other things, this was noticed in CI: https://travis-ci.org/seanmonstar/reqwest/jobs/590539016

**Notes**

Output of `cargo version`: `cargo 1.39.0-beta (b6c6f685b 2019-09-19)` 

 Backtrace:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/tools/cargo/src/cargo/util/cpu.rs:152:29

stack backtrace:

   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

   1: core::fmt::write

   2: std::io::Write::write_fmt

   3: std::panicking::default_hook::{{closure}}

   4: std::panicking::default_hook

   5: std::panicking::rust_panic_with_hook

   6: std::panicking::continue_panic_fmt

   7: rust_begin_unwind

   8: core::panicking::panic_fmt

   9: core::panicking::panic_bounds_check

  10: cargo::util::cpu::State::current

  11: cargo::core::compiler::job_queue::JobQueue::new

  12: cargo::core::compiler::context::Context::compile

  13: cargo::ops::cargo_compile::compile_ws

  14: cargo::ops::cargo_compile::compile

  15: cargo::commands::build::exec

  16: cargo::cli::main

  17: cargo::main

  18: std::rt::lang_start::{{closure}}

  19: std::panicking::try::do_call

  20: __rust_maybe_catch_panic

  21: std::rt::lang_start_internal

  22: main
```

**Comment by alexcrichton** [comment] 2019-09-27 18:55
Thanks for the report, but this is a duplicate of https://github.com/rust-lang/cargo/issues/7427, https://github.com/rust-lang/cargo/issues/7438, and https://github.com/rust-lang/cargo/issues/7453

**Closed by alexcrichton** 2019-09-27 18:55 UTC
Labels: C-bug

**Comment by seanmonstar** [comment] 2019-09-27 18:56
Sorry, tried searching and those didn't come up somehow.
