### ISSUE TITLE
Post `cargo install` hook

### ISSUE THREAD

**Issue by NicholasLYang** [rust-lang/cargo#11539] opened 2023-01-04 20:30 UTC
### Problem

I'm building a Rust binary that relies on a second binary[^1] that the first one executes. I have the `build.rs` file that builds this second binary and places it next to the Rust binary. However, when I run `cargo install`, if I'm understanding this correctly, the Rust binary is first built then copied into the installation root. Is there a way to execute some code after cargo install that moves the second binary to the installation root as well?

[^1]: I can't link the two programs because of complicated issues.

### Proposed Solution

Either a way of detecting in build.rs that we are running `cargo install` (maybe an environment variable?), or some sort of post-install hook that can let users customize the `cargo install` process.

**Comment by ehuss** [comment] 2023-01-04 20:57
I don't believe there is currently a mechanism to do that. The current recommended approach is to use an outer general-purpose build system (or write your own scripts using the [cargo-xtask](https://github.com/matklad/cargo-xtask) pattern). I believe this is more or less a duplicate of #2386, so closing in favor of that.

**Closed** 2023-01-04 22:29 UTC
Labels: C-feature-request
