### ISSUE TITLE
Doctest fails to link

### ISSUE THREAD

**Issue by dragostis** [rust-lang/cargo#2377] opened 2016-02-10 17:41 UTC
Code runs well in a usual `#[test]` but fails in a doctest:
```
note: Undefined symbols for architecture x86_64:
  "mruby::_$LT$impl$GT$::to_bool::hb7390b50b434ef6bida", referenced from:
      main::ha42f3f275405f749gaa in rust_out.0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
thread 'mruby::MRuby_0' panicked at 'Box<Any>', src/libsyntax/diagnostic.rs:240
```

I'm calling `to_bool` method in the test on a `struct` called `Value`. The issue is [here](https://github.com/dragostis/mrusty/blob/example/src/mruby.rs#L27). (Don't mind the `panic!`.)

**Comment by alexcrichton** [comment] 2016-02-11 00:37
Thanks for the report! Looking at the code structure I think that this is unfortunately a duplicate of https://github.com/rust-lang/rust/issues/16734, so I'm going to close in favor of that.

If you mark the `mruby` module as `pub` though or reexport the `Value` type at the top level I think it should make this go away!

**Closed by alexcrichton** 2016-02-11 00:37 UTC

**Comment by dragostis** [comment] 2016-02-11 07:39
Works like a charm! Thanks, @alexcrichton.
