### ISSUE TITLE
"cargo build" fails with libcurl on OS X Yosemite

### ISSUE THREAD

**Issue by mzaccari** [rust-lang/cargo#1937] opened 2015-08-25 17:20 UTC
Tried this with the rust-1.1, rust-1.2 and rust-nightly packages, all with the same results. It's using the curl provided by OS X:

```bash
$ cargo --version
cargo 0.5.0-nightly (176b5c1 2015-08-21)

$ RUST_BACKTRACE=1 cargo build
 Downloading hyper v0.6.10
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', ../src/libcore/result.rs:732
stack backtrace:
   1:        0x105071ca0 - sys::backtrace::write::ha29ed9eeda09b191Yts
   2:        0x105078153 - panicking::on_panic::h4f0311883f3e75d9Z7w
   3:        0x1050565a2 - rt::unwind::begin_unwind_inner::hcd1c9ab2da35c9410Cw
   4:        0x105056b67 - rt::unwind::begin_unwind_fmt::hfb293892a08f91906Bw
   5:        0x105077b77 - rust_begin_unwind
   6:        0x10509a260 - panicking::panic_fmt::h687aa220bbe8cf9dqgC
   7:        0x104fe56f6 - http::handle::Handle::new::hcb217b347d13c09c3Va
   8:        0x104e479ee - ops::registry::http_handle::h8d0e3336982df8d3E9o
   9:        0x104d18b1c - sources::registry::RegistrySource<'cfg>.Source::download::hae66e40d8cc9719eQ7r
  10:        0x104d5100a - core::registry::PackageRegistry<'cfg>::get::h2d5dca4e11531c05vyg
  11:        0x104d7135f - ops::cargo_compile::compile_pkg::h55a91b0d119e21b5PCh
  12:        0x104d6e554 - ops::cargo_compile::compile::h329bb0c236e2b259Nxh
  13:        0x104ca7684 - call_main_without_stdin::h2051748642563895962
  14:        0x104c96629 - execute::h4bb7a2d5c519fe2dEda
  15:        0x104c92129 - call_main_without_stdin::h13486437972176667287
  16:        0x104c8f2aa - boxed::F.FnBox<A>::call_box::h2601360002103964467
  17:        0x104c8e502 - rt::unwind::try::try_fn::h3361446254641105278
  18:        0x105077b28 - __rust_try
  19:        0x10506acf0 - rt::unwind::try::inner_try::h332543bb689c0967Tyw
  20:        0x104c8e6b7 - boxed::F.FnBox<A>::call_box::h10542716301285423561
  21:        0x105076e1d - sys::thread::Thread::new::thread_start::h6180cb2a7d6f1601eXv
  22:     0x7fff8efe6059 - _pthread_body
  23:     0x7fff8efe5fd6 - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:732
stack backtrace:
   1:        0x105071ca0 - sys::backtrace::write::ha29ed9eeda09b191Yts
   2:        0x105078153 - panicking::on_panic::h4f0311883f3e75d9Z7w
   3:        0x1050565a2 - rt::unwind::begin_unwind_inner::hcd1c9ab2da35c9410Cw
   4:        0x105056b67 - rt::unwind::begin_unwind_fmt::hfb293892a08f91906Bw
   5:        0x105077b77 - rust_begin_unwind
   6:        0x10509a260 - panicking::panic_fmt::h687aa220bbe8cf9dqgC
   7:        0x104c8e013 - main::h13a7ff10974fd1b3Tca
   8:        0x105078f22 - rt::unwind::try::try_fn::h13367925773400092151
   9:        0x105077b28 - __rust_try
  10:        0x105078d1e - rt::lang_start::h5e7749518fb90b0133w
```

The Cargo.toml:

```toml
[package]
name = "nickel-test"
version = "0.1.0"
authors = ["Michael Zaccari <michael.zaccari@gmail.com>"]

[dependencies.nickel]
version = "*"
```

**Comment by alexcrichton** [comment] 2015-08-25 22:12
Did you compile Cargo yourself? If not, where'd you get Cargo from?

**Comment by mzaccari** [comment] 2015-08-26 12:28
It came bundled with the OS X package(s) I installed for 1.1, 1.2 and nightly. I haven't (yet) compiled for myself, but can certainly do so if it will help root out the issue

**Comment by krbullock** [comment] 2015-08-26 13:52
Same issue here when trying to build something that links against libc.

**Comment by krbullock** [comment] 2015-08-26 13:56
A further data point: I had been using the libc crate and got the failure, but switched to using #![feature(libc)] and the build worked. Perhaps nickel also depends on the libc crate?

**Comment by steveklabnik** [comment] 2015-08-26 15:46
You should add `libc = "0.1.10"` to your `Cargo.toml` instead of `#[feature(libc)]`.

**Comment by krbullock** [comment] 2015-08-26 15:48
@steveklabnik That's my point, when I have `libc` listed as a dependency in Cargo.toml, I get the above error.

**Comment by steveklabnik** [comment] 2015-08-26 15:49
Ah, that is _extra_ strange, then.

**Comment by alexcrichton** [comment] 2015-08-26 16:36
When you say OS X package, which medium do you mean? (e.g. homebrew, multirust, pkg, tarball, etc).

Also, do you have a custom build of libcurl? Or are you using the system libcurl? You can find this by running `otool -L` on the cargo binary

**Comment by zmthy** [comment] 2015-08-28 12:43
I'm getting this issue using both the installer on the homepage and an install from homebrew. I tried to run a build of cargo myself, but I can't get it to compile because this same problem comes up during the `make` phase of the build.

The installed cargo is using `/usr/lib/libcurl.4.dylib`. I attempted swapping out that curl installation with a newer version from homebrew, but that didn't appear to change anything.

**Comment by alexcrichton** [comment] 2015-08-28 16:19
Hm, unfortunately I can't reproduce this locally with 10.10.5, what version of OSX are you using?

It looks like there are some `.unwrap()` calls in curl-rust [when we're setting the various options](https://github.com/rust-lang/cargo/blob/fc66290f270689f2f4da974b9f57a899ab06bd2e/src/cargo/ops/registry.rs#L173-L185) for HTTP handles (e.g. timeouts, connection timeouts, etc), and I think that's where the panic is happening. If it could be figured out which one of those options is failing, that'd be great!

**Comment by krbullock** [comment] 2015-08-28 21:02
I dunno about @mzaccari, but I'm also on OS X 10.10.5.

```
$ rustc --version
rustc 1.4.0-nightly (63ba780fd 2015-08-23)

$ otool -L $(which cargo)
/usr/local/bin/cargo:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 44.0.0)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 44.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

Interestingly, I can no longer reproduce the problem with `libc`, but I can do so with `nickel`.

**Comment by alexcrichton** [comment] 2015-08-29 00:21
Hm, was this a recent regression for those experiencing this problem? Or has it always been a problem?

Also, when you mention that the problem is *not* with `libc` but is with `nickel`, in theory this should always happen for any download, so when you use `libc` does cargo print "Downloading ..." for anything? If Cargo is able to download some things but not others, that's super weird!

**Comment by ResumeNothing** [comment] 2015-09-02 01:31
I'm getting something similar when trying to download any dependency. I have a new project with:

```
[dependencies]
chrono = "0.2"
```

Running cargo build fails every time, though with slightly different variations:

```
$ cargo build
 Downloading time v0.1.32
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading rand v0.3.11
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading rand v0.3.11
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading rustc-serialize v0.3.16
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading rustc-serialize v0.3.16
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading kernel32-sys v0.1.4
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading num v0.1.27
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
$ cargo build
 Downloading rustc-serialize v0.3.16
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
```

If I change the dependency to libc, it builds with no problem.

**Comment by krbullock** [comment] 2015-09-05 20:55
Confirmed, it's happening on any dependency I don't already have.

**Comment by krbullock** [comment] 2015-09-06 04:15
@alexcrichton you set me on the right path. I spent a good chunk of time debugging this today, and traced it down (by constructing a minimal test case) to the [constructor](https://github.com/carllerche/curl-rust/blob/master/src/http/handle.rs#L31-L38) for a `curl::http::Handle`.

If either a `cert_file` or `cert_dir` are found by the openssl crate, the constructor tries to set the appropriate option in libcurl, which returns an error. (Apple's bundled libcurl doesn't link against OpenSSL, it uses Apple's own `Security.framework`, so you can't successfully set those options.) But the methods to set those options just [unwrap the result](https://github.com/carllerche/curl-rust/blob/master/src/http/handle.rs#L105-L113) of the setopt call and thus the panic.

I think that normally on OS X, both `cert_file` and `cert_dir` will be `None`. But because I had previously created a `/etc/ssl/certs` directory, the `openssl::probe::probe()` call found a `cert_dir`. (Incidentally I had created that directory and put a dummy CA cert in it so that I could [convince Python's SSL module to use the system certificates](https://mercurial.selenic.com/wiki/CACertificates#Mac_OS_X_10.6_and_higher).)

@mzaccari, @ResumeNothing, @alexcrichton can any of you reproduce by creating the directory `/etc/ssl/certs`?

In any case it seems to me the issue is actually with curl-rust (or possibly the openssl crate).

**Comment by krbullock** [comment] 2015-09-06 04:19
For the record, here's the minimal test case I created, too:

```rust
extern crate curl;
extern crate openssl_sys as openssl;

use curl::http;

fn main() {
    let probe = ::openssl::probe::probe();
    println!("{:?}; {:?}", probe.cert_file, probe.cert_dir);
    let mut h = http::handle();
    println!("created handle");
}
```

**Comment by ResumeNothing** [comment] 2015-09-06 18:40
I had to figure out how to download crates manually and then download all the dependencies by hand. Here's what I'm getting:

```
[test]$ cargo run
     Running `target/debug/test`
Some("/etc/openssl/cert.pem"); Some("/usr/ssl/certs")
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', ../src/libcore/result.rs:731
An unknown error occurred

To learn more, run the command again with --verbose.
```

**Comment by ResumeNothing** [comment] 2015-09-06 18:47
I removed `/usr/ssl/certs` and `/etc/openssl` and now cargo works again. Yay!

**Comment by ResumeNothing** [comment] 2015-09-06 18:53
Also: 

```
[test]$ cargo run
     Running `target/debug/test`
None; None
created handle
```

For additional background, I also do Rails development on this machine, and in the past ran into openssl issues where I pretty much tried everything suggested to try and resolve the issue. I'm pretty sure adding those files and directories was part of the fix, but I just let rvm take care of it now, so I don't think I need them anymore.

**Comment by alexcrichton** [comment] 2015-09-08 17:30
@krbullock oh wow, nice investigation! That does indeed seem to do the trick for me, I'll go update curl and update it here as well to close this out, thanks for finding the cause!

**Closed** 2015-09-09 00:06 UTC

**Comment by mzaccari** [comment] 2015-09-17 19:04
Hey, my apologies for not getting back to this sooner, it's been crazy busy. I can confirm that removing the custom `/etc/ssl/certs` directory fixes the problem. Thank you @krbullock for looking into this, and everyone else for their help, it is much appreciated.

**Comment by royalaid** [comment] 2015-09-22 09:37
Just to add to this, the file /etc/openssl/cert.pem was also causing the same issue

**Comment by kkirsche** [comment] 2015-09-30 14:46
Fixed it for me as well
