### ISSUE TITLE
error: failed to update registry Caused by:   Operation not supported (os error 45)

### ISSUE THREAD

**Issue by agaviria** [rust-lang/cargo#2892] opened 2016-07-19 03:32 UTC
I've recently installed in OSX 10.11, cargo.  `which cargo` reveals it's location at `/usr/local/bin/cargo` .  I can create, `cargo new` works.  However if I attempt a `cargo build` or `cargo update`, etc.., I get the following error:

```
error: failed to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  Operation not supported (os error 45)
```

Please also note, the installation did not seem to create a `CARGO_HOME`path created, such as in `$HOME/.cargo.`  The error message does not help me as well.   Any suggestions?

```
cargo --version
cargo 0.13.0-nightly (15c1cd2 2016-07-17)

rustc --version
rustc 1.12.0-nightly (34f35ed29 2016-07-17)
```

**Comment by alexcrichton** [comment] 2016-07-19 03:52
Thanks for the report! I've seen this error message when HTTPS or SSH support isn't compiled into libgit2 (which is linked into Cargo). Where'd you install Cargo from? That's probably the next place to look.

**Comment by agaviria** [comment] 2016-07-19 04:12
@alexcrichton Installation was done using rustup.

**Comment by alexcrichton** [comment] 2016-07-19 05:37
Uh oh, that's not good! It looks like this may also be related to filesystem things, I wonder do you have an NFS mount? There's been problems with that in the past with using Cargo but those should in theory be fixed now.

**Comment by agaviria** [comment] 2016-07-19 06:11
@alexcrichton I use a time capsule, not sure if that qualifies as an NFS mount.  I will build from source, and will let you know if the latter works.

**Comment by agaviria** [comment] 2016-07-19 06:40
Well, that did not go as expected.  Rust source build panicked and did not install successfully.  I realize this may not be a suitable ground to disclose this next error, but in any event I will just paste the output failure in case it may contribute to debugging.

```
warning: source code was requested to be rendered, but processing `src/libstd/lib.rs` had an error: Permission denied (os
 error 13)
         skipping rendering of source code
thread '<unnamed>' panicked at 'failed to open lockfile: Permission denied (os error 13)', src/librustdoc/flock.rs:145
note: Run with `RUST_BACKTRACE=1` for a backtrace.
make[1]: *** [doc/std/index.html] Error 101
make: *** [install] Error 2
```

**Comment by alexcrichton** [comment] 2016-07-19 15:44
Aha, definitely sounds like something fishy is going on with the filesystem. Can you try to use a tool like `dtruss` or perhaps `RUST_LOG=cargo` to get some more debug information and see what's failing?

**Comment by agaviria** [comment] 2016-07-19 16:56
Ok so back to a rustup install; it managed to create `$CARGO_HOME` but still generates the same os error.  A trace output can be seen [here](https://gist.github.com/agaviria/020cec9a5c5278d08599adc1c5005db4) 

Here is the process which exited the build failure.

```
Caused by:
  Process didn't exit successfully: `rustc /Users/ag/tmp/rust/src/main.rs --crate-name main --crate-type bin -g --out-dir /Users/ag/tmp/rust/guess/target/debug --emit=dep-info,link -L dependency=/Users/ag/tmp/rust/guess/target/debug -L dependency=/Users/ag/tmp/rust/guess/target/debug/deps --extern rand=/Users/ag/tmp/rust/guess/target/debug/deps/librand-49a08859d086fffe.rlib` (exit code: 101)
wait4(0x157CF, 0x7FFF5C6CCE24, 0x0)		 = 88015 0
sigaltstack(0x7FFF5C6CCDF8, 0x0, 0x0)		 = 0 0
munmap(0x103CA5000, 0x20000)		 = 0 0
```

Cargo.toml
```
[package]

name = "rust"
version = "0.0.1"
authors = [ "Alejandro Gaviria <mr.gaviria@gmail.com" ]

[[bin]]
name = "main"
path = "/Users/ag/tmp/rust/src/main.rs"

[dependencies]

rand = "0.3.14"
```




﻿﻿﻿

**Comment by agaviria** [comment] 2016-07-19 17:28
`cargo build` also created a binary in `target/debug`

<img width="426" alt="screen shot 2016-07-19 at 1 24 28 pm" src="https://cloud.githubusercontent.com/assets/226974/16959688/4905a6a8-4db4-11e6-84ed-b867efe3f543.png">

**Comment by alexcrichton** [comment] 2016-07-19 17:58
Oh sorry I may be missing the context here, but in [this comment](https://github.com/rust-lang/cargo/issues/2892#issuecomment-233697092) you mentioned an OS error, but the log looks like it doesn't have that?

**Comment by agaviria** [comment] 2016-07-19 19:30
Ok, so `cargo new --bin $NAME` scaffolds a project directory as expected.  Once the Cargo.toml is updated and `Cargo build --verbose` is issued; the compiler returns an (os error 45)  It does not seem to create `target/debug` folder or git dependencies.

However, if I run `sudo dtruss cargo build --verbose` it seems to create the target/debug with expected dylibs and binary.   `sudo dtruss cargo run` also works but without the prefix command it fails.  See the screen capture above for more context.  The only reason you see a target directory was because I had ran a trace command prior.  But I concur my statement as true, just re-verified it.

**Comment by alexcrichton** [comment] 2016-07-19 20:45
Hm ok, let's take this one error at a time :). So the first error you get is:

```
$ cargo new --bin foo
$ cd foo
$ cargo build --verbose # this fails?
```

Is it the last command that fails? Can you gist the full logs of that? We should specifically handle ENOTSUP (error 45) on OSX [here](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/flock.rs#L273-L277), but it's perhaps coming from somewhere else.

**Comment by agaviria** [comment] 2016-07-19 21:24
Ok, thanks for the help!  The above does not fail.  [First Tracelog](https://gist.github.com/agaviria/a73d1390e9de8bf695e8cd40250d9e6b)

```
~/tmp/rust cargo new --bin foo
~/tmp/rust cd foo
~/tmp/rust/foo(master ✗) cargo build --verbose
   Compiling foo v0.1.0 (file:///Users/ag/tmp/rust/foo)
     Running `rustc src/main.rs --crate-name foo --crate-type bin -g --out-dir /Users/ag/tmp/rust/foo/target/debug --emit=dep-info,link -L dependency=/Users/ag/tmp/rust/foo/target/debug -L dependency=/Users/ag/tmp/rust/foo/target/debug/deps`
```

Cargo issues the (error 45) when an external dependancy is added to `Cargo.toml` and `cargo build` command is re-issued.  [Second Tracelog](https://gist.github.com/agaviria/e60cfe2f20222bcab42fcc675ae6d51f)

```
error: Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  Operation not supported (os error 45) 
```

**Comment by alexcrichton** [comment] 2016-07-19 22:40
Hm ok, getting closer! Does that second trace include the error? It looks like it has the output of the first trace, so I just wanted to confirm. Also, could you post a gist of `RUST_LOG=cargo=trace` for the failing build as well (the one where a dependency was added)

**Comment by agaviria** [comment] 2016-07-19 23:39
[Line 305](https://gist.github.com/agaviria/e60cfe2f20222bcab42fcc675ae6d51f) from second trace is where you can see the compiling of the rustc-serialize dependency added.  Here is the [RUST_LOG](https://gist.github.com/agaviria/83a0057bf4b977a69d608224f7595cf6) for `cargo build --verbose`.

**Comment by agaviria** [comment] 2016-07-20 05:52
Ok so I realized that rustup installs `$CARGO_HOME` with the following rights and ownership.  

```
~/.cargo la    
total 16
-rw-r--r--   1 root  staff   149B Jul 20 01:00 .crates.toml
drwxr-xr-x  13 ag    staff   442B Jul 20 01:11 bin
-rw-r--r--   1 root  staff    37B Jul 19 10:54 env
drwxr-xr-x   4 root  staff   136B Jul 19 11:13 git
drwxr-xr-x   5 root  staff   170B Jul 19 11:13 registry
```

However, the underlying files inside `bin` all belonged to `root.`  A `chown` command was issued to rectify this to all the binaries below:

```
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 cargo
-rwxr-xr-x  1 ag  staff   991K Jul 20 01:00 dybuk
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 multirust
-rwxr-xr-x  1 ag  wheel   4.6M Jul 19 23:50 racer
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 rust-gdb
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 rust-lldb
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 rustc
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 rustdoc
-rwxr-xr-x  7 ag  staff   5.1M Jul 19 10:53 rustup
```

Running the same cargo command, `cargo build` on our foo example returns a palatable error.   File system permission access: `(os error 13)`

```
~/tmp/rust/foo(master ✗) cargo build --verbose
error: failed to open: /Users/ag/tmp/rust/foo/target/debug/.cargo-lock

Caused by:
  Permission denied (os error 13)
```

Sure enough, `sudo` gives us our expected behavior and result.  So after all this, I think this issue should be filed with the rustup dev team?  Not sure if this was their intended ownership structure.   Let me know your thoughts on how to proceed.

**Comment by alexcrichton** [comment] 2016-07-20 22:41
Interesting! Did you perhaps use `sudo` when installing rustup initially? I think Cargo can also do a lot better to give a better error here in any case, so I'd still be interested in seeing how to reproduce.

I tried setting everything in my home directory to owned by root, but I ended up always getting different errors :(

**Comment by agaviria** [comment] 2016-07-21 00:49
Yes it's possible I may have used `sudo` to install rustup.  I uninstalled rustup made a git pull and reinstalled without `sudo` but could not replicate the errors previously reported.  All seems to be working well...

**Comment by alexcrichton** [comment] 2016-07-21 20:43
Ok, I'm gonna tag this as `A-errors` to ensure that it's logged under "where to improve errors", but cc @brson as well this was some confusion which derived from installing rustup with `sudo`

**Comment by brson** [comment] 2016-07-21 21:13
Oh that's unexpected. I always forget that sudo doesn't change `HOME`. https://github.com/rust-lang-nursery/rustup.rs/issues/608

**Comment by kellda** [comment] 2020-06-06 12:34
rust-lang/rustup#608 is closed, so maybe this issue can be closed as well ?

**Comment by ehuss** [comment] 2020-06-07 22:49
Yea, I'm going to consider this resolved.

**Closed by ehuss** 2020-06-07 22:49 UTC
Labels: A-errors
