### ISSUE TITLE
Running 2 instances of cargo with the same CARGO_HOME can result in failures due to "File Exists"

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/cargo#1700] opened 2015-06-09 20:24 UTC
An example of (the entire) output from a failed invocation of `cargo build --verbose`:
```
 Downloading bitflags v0.1.1
Unable to get packages from source

Caused by:
  Failed to unpack package `bitflags v0.1.1`

Caused by:
  File exists (os error 17)
```

This was triggered on 'nightly' a few hours ago.

**Comment by alexcrichton** [comment] 2015-06-09 21:42
This is a dupe of https://github.com/rust-lang/cargo/issues/354, but thanks!

**Closed by alexcrichton** 2015-06-09 21:42 UTC
