### ISSUE TITLE
Moving repository to a virtual manifest can cause surprising dependency resolution errors due to resolver fallback

### ISSUE THREAD

**Issue by thomaseizinger** [rust-lang/cargo#11811] opened 2023-03-08 12:02 UTC
I am not entirely sure this is a bug report or a feature request but I'll describe anyway what happened.

We have a fairly large workspace over at https://github.com/libp2p/rust-libp2p. Previously, the root `Cargo.toml` was both a crate and a workspace manifest. For various reasons, I wanted to move away from that.

That root crate is `edition = 2021` which implies the new dependency resolver (version `2`). Thus, we did not specify `resolver = 2` explicitly as part of the `[workspace]` table. We need the new feature resolver because we have some target-specific features to activiate:

https://github.com/libp2p/rust-libp2p/blob/7069d78ee333c92a3b99bbad100d9c6ba2fe361a/transports/noise/Cargo.toml#L26-L30

What happened now is that by splitting the root manifest into a separate crate, the `edition = 2021` disappeared and cargo was now falling back using v1 of the resolver, resulting in a failing build because the `features` of the `snow` dependency within the `Cargo.toml` of `libp2p-noise` were incorrectly merged.

This was especially surprising because I was running `cargo build --package libp2p` which does have `edition = 2021`. I guess this could be considered a bug? I am not sure.

The problem was fixed by explicitly specifying `resolver = 2` in the `[workspace]` table.

Here is the PR: https://github.com/libp2p/rust-libp2p/pull/3536

**Comment by weihanglo** [comment] 2023-03-08 12:35
> This was especially surprising because I was running `cargo build --package libp2p` which does have `edition = 2021`. I guess this could be considered a bug? I am not sure.

If you're under a workspace running that, it will respect workspace settings. That means without `resolver = "2"` it still running with resolver v1.

**Comment by ehuss** [comment] 2023-03-08 13:04
Closing as a duplicate of the above linked issues.

**Closed by ehuss** 2023-03-08 13:04 UTC
