### ISSUE TITLE
Recommendations for workspace creation

### ISSUE THREAD

**Issue by tonycody** [rust-lang/cargo#13954] opened 2024-05-23 06:45 UTC
### Problem

Currently, to use Workspace, we need to modify the cargo.toml file to do this

### Proposed Solution

It is recommended that Workspace creation support be created via the cargo command, which is relatively inexpensive to use.

Just like Java Maven.

**Comment by epage** [comment] 2024-05-23 15:58
This looks to be a duplicate of #8365.  Closing in favor of that.  If there is a reason we should have this be separate, let us know!

**Closed by epage** 2024-05-23 15:58 UTC
Labels: Command-new, C-feature-request, S-triage
