### ISSUE TITLE
Setting CARGO_TARGET_DIR to empty causes cargo clean to remove all files

### ISSUE THREAD

**Issue by bilgincoskun** [rust-lang/cargo#7551] opened 2019-10-29 13:13 UTC
**Problem**
When CARGO_TARGET_DIR is set to empty,cargo clean removes all files including source code,not just compilation artifacts. I expected it to remove only  artifact files inside the directory as default behavior. 

**Steps**
1. run 'export CARGO_TARGET_DIR=' in bash (or 'set -xg CARGO_TARGET_DIR' in fish)
2. run cargo clean command inside the project directory.

**Notes**

Output of `cargo version`:
cargo 1.38.0 (23ef9a4ef 2019-08-20)

**Comment by ashtneoi** [comment] 2019-11-03 23:29
I reproduced this on cargo 1.40.0-nightly (5da4b4d47 2019-10-28). Looks like it removes the whole working directory.

```none
maia@fluff (/tmp)$ cd $(mktemp -d)
maia@fluff (/tmp/tmp.Vw7q4M4hhg)$ cargo init --name=foo
     Created binary (application) package
maia@fluff (/tmp/tmp.Vw7q4M4hhg)$ ls -AF
.git/  .gitignore  Cargo.toml  src/
maia@fluff (/tmp/tmp.Vw7q4M4hhg)$ CARGO_TARGET_DIR= cargo clean
maia@fluff (/tmp/tmp.Vw7q4M4hhg)$ ls -AF
maia@fluff (/tmp/tmp.Vw7q4M4hhg)$ stat .
  File: .
  Size: 0         	Blocks: 8          IO Block: 4096   directory
Device: 805h/2053d	Inode: 391264      Links: 0
Access: (0700/drwx------)  Uid: ( 1000/    maia)   Gid: ( 1000/    maia)
Access: 2019-11-03 15:24:42.954294362 -0800
Modify: 2019-11-03 15:24:57.959637060 -0800
Change: 2019-11-03 15:24:57.959637060 -0800
 Birth: -
maia@fluff (/tmp/tmp.Vw7q4M4hhg)$ 
```

```none
maia@fluff (~)$ cd $(mktemp -d)
maia@fluff (/tmp/tmp.VT8tAhGmXR)$ cargo init --name=foo
     Created binary (application) package
maia@fluff (/tmp/tmp.VT8tAhGmXR)$ ls -AF
.git/  .gitignore  Cargo.toml  src/
maia@fluff (/tmp/tmp.VT8tAhGmXR)$ cd src
maia@fluff (/tmp/tmp.VT8tAhGmXR/src)$ CARGO_TARGET_DIR= cargo clean
maia@fluff (/tmp/tmp.VT8tAhGmXR/src)$ ls -AF
maia@fluff (/tmp/tmp.VT8tAhGmXR/src)$ stat .
  File: .
  Size: 0         	Blocks: 8          IO Block: 4096   directory
Device: 805h/2053d	Inode: 394599      Links: 0
Access: (0775/drwxrwxr-x)  Uid: ( 1000/    maia)   Gid: ( 1000/    maia)
Access: 2019-11-03 15:26:56.415050953 -0800
Modify: 2019-11-03 15:27:07.262666402 -0800
Change: 2019-11-03 15:27:07.262666402 -0800
 Birth: -
maia@fluff (/tmp/tmp.VT8tAhGmXR/src)$ cd ..
maia@fluff (/tmp/tmp.VT8tAhGmXR)$ ls -AF
.git/  .gitignore  Cargo.toml
maia@fluff (/tmp/tmp.VT8tAhGmXR)$ 
```

**Comment by ashtneoi** [comment] 2019-11-03 23:31
I'm going to try to fix this. I haven't worked on Cargo before so we'll see how far I get.

**Comment by joshtriplett** [comment] 2021-02-20 19:38
This and https://github.com/rust-lang/cargo/issues/8866 are the same bug; closing this one in favor of #8866.

**Closed by joshtriplett** 2021-02-20 19:38 UTC
Labels: C-bug, Command-clean
