### ISSUE TITLE
Add a way to update a thing installed by `cargo install`

### ISSUE THREAD

**Issue by staktrace** [rust-lang/cargo#3645] opened 2017-02-03 20:33 UTC
See https://bugzilla.mozilla.org/show_bug.cgi?id=1336555 for backstory. It would be nice to have a way to update a tool installed by `cargo install` to the latest available version of that tool. e.g. running `cargo install --update cargo-vendor` would download and install the latest version of `cargo-vendor`, but only if your version is out-of-date.

**Comment by est31** [comment] 2017-02-03 20:49
Dupe of  #3496 and #2082

**Comment by alexcrichton** [comment] 2017-02-03 21:20
Indeed, I'm going to close in favor of https://github.com/rust-lang/cargo/issues/2082

**Closed by alexcrichton** 2017-02-03 21:20 UTC
