### ISSUE TITLE
Add an option to build only dependencies or only the current crate

### ISSUE THREAD

**Issue by HybridEidolon** [rust-lang/cargo#1891] opened 2015-08-11 16:17 UTC
For the purposes of linting plugins for text editors, it would be convenient to have an option that _only_ builds the default crate, or the crate specified by the `-p` option, and return an error code and/or message that indicates that the build failed because the dependencies are out of date or not built. Alongside this, an option to build _only_ the dependencies of the default crate or the `-p` crate, since the current crate is much more likely to be in a state that it can't be compiled.

**Comment by cloderic** [comment] 2016-03-14 17:55
This option would be very helpful to create Dockerfile that caches the dependency retrieval properly (cf. https://users.rust-lang.org/t/creating-official-docker-image-for-rust/4165/4)

**Comment by loa** [comment] 2017-02-14 17:47
My current work-around:

```
ADD Cargo.toml Cargo.lock /app/
RUN mkdir -p /app/src && echo "fn main() {}" > /app/src/main.rs && \
    cargo build --release

ADD . /app
RUN cargo build --release

CMD ["/app/target/release/BINARY"]
```

**Comment by kellda** [comment] 2020-06-06 13:39
This looks like a duplicate of #2644

**Closed** 2020-06-07 23:23 UTC
Labels: A-configuration
