### ISSUE TITLE
"cargo install --git" requires a crate name when a workspace has multiple binaries

### ISSUE THREAD

**Issue by teor2345** [rust-lang/cargo#8958] opened 2020-12-08 06:43 UTC
**Problem**

What I did:

I tried running the command:
```
cargo install --git https://github.com/ZcashFoundation/zebra --branch main
```
But I got the error:
```
    Updating git repository `https://github.com/ZcashFoundation/zebra`
error: multiple packages with binaries found: zebra-utils, zebrad  
```

I tried:
* specifying `--bin zebrad`
* specifying `--bins`
* modifying the `default-members` in the workspace Cargo.toml to exclude `zebra-utils`

Then I found the correct command syntax in #7194:
```
cargo install --git https://github.com/ZcashFoundation/zebra --branch main zebrad
```

**Steps**

1. Run `cargo install --git https://github.com/ZcashFoundation/zebra --rev 65e38b3c74eb06b14939448e368848f8ff0598b1`

**Possible Solution(s)**

Here's what I expected:
1. `--bin zebrad` should install the binary with that name, if there are multiple packages with binaries
2. `--bins` should install all binaries, if there are multiple packages with binaries
3. if there is only one binary in the workspace `default-members`, that binary should be installed
4. a `multiple packages with binaries found` error should give users a hint about how to specify a single crate

**Notes**

Output of `cargo version`:
```
cargo 1.45.1 
```

Output of `uname -a`:
```
Linux ... 5.4.75 #1-NixOS SMP Thu Nov 5 10:43:38 UTC 2020 x86_64 GNU/Linux 
```

**Comment by ehuss** [comment] 2021-01-07 02:50
Closing as a duplicate of #4830.  These all sound like reasonable suggestions to me, though.

**Closed by ehuss** 2021-01-07 02:50 UTC
Labels: C-bug
