### ISSUE TITLE
`paths` config override does not override `path` of nested dependencies

### ISSUE THREAD

**Issue by lucab** [rust-lang/cargo#1863] opened 2015-07-31 14:46 UTC
According to the [cargo guide](http://doc.crates.io/guide.html#overriding-dependencies), `paths` parameter in a config file should be used to add local overrides for dependencies. However, I found this not to be working for many crates, due to nested dependencies declaring an explicit `path`. Nested dependencies are NOT being picked up from my local paths.
The scenario to reproduce is as follow.

I have a test project that needs `env_logger`. The Cargo.toml is as follow:
```
[project]
name = "test"
version = "0.1.0"
authors = [ "me <me@example.com>" ]

[dependencies]
env_logger = "0.3"

[[bin]]
name = "test"
```

I have a local copy of all the crates I need under `/srv/deps/`, so:
 * env_logger under `/srv/deps/env_logger-0.3.1`
 * log under `/srv/deps/log-0.3.1/` (needed by env_logger)

I have a local override under `.cargo/config` which looks like this:
```
paths = [
"/srv/deps/log-0.3.1",
"/srv/deps/env_logger-0.3.1"
]
```

However, trying to build with cargo fails with:
```
Unable to update file:///srv/deps/env_logger-0.3.1

Caused by:
  Could not find `Cargo.toml` in `/srv/deps`
```

This is because `env_logger` currently has a dependency on `log` specified as follow:
```
[dependencies.log]
version = "0.3"
path = ".."
```

I believe this is a bug, as it is my understanding that local  config overrides should take precedence over library manifests.

**Comment by alexcrichton** [comment] 2015-08-03 16:44
This sounds like you're taking the source directly from crates.io and then using it as a path dependency? That's unfortunately not going to work for this reason (Cargo rewrites path dependencies to be crates.io dependencies).

Otherwise this is working as intended because the path override for `env_logger` says it depend on a crate which doesn't exist, so I'm going to close this as working as intended.

**Closed by alexcrichton** 2015-08-03 16:44 UTC

**Comment by lucab** [comment] 2015-08-03 22:21
> This sounds like you're taking the source directly from crates.io and then using it as a path dependency? That's unfortunately not going to work for this reason

Yes I am. I'm taking released artifacts and making them locally available for offline/reproducible/signed builds. Maybe I took the wrong approach also given the lack of answers [here](https://internals.rust-lang.org/t/how-to-distro-package-a-cargo-using-rust-executable/1785), but this should be a fairly normal scenario for a package builder/manager.

> (Cargo rewrites path dependencies to be crates.io dependencies)

If I understand correctly, this means that "entries for dependencies fetched to disk are synthesized to Cargo.lock in the parent project and then they override the original path."

> Otherwise this is working as intended because the path override for env_logger says it depend on a crate which doesn't exist, so I'm going to close this as working as intended.

Are you suggesting that all those crates are declaring buggy dependency paths? They don't make much sense when speaking about released artifacts/crates, but only in a git repo context. But it is my understanding that dependencies are declared in term of crates. Can you please clarify, as I fear I have some misunderstanding on the intended design?

**Comment by lucab** [comment] 2015-08-03 22:59
> But it is my understanding that dependencies are declared in term of packages.

I've been corrected by @steveklabnik, this was my root misunderstanding. Dependencies are declared in terms of crates, not packages.

**Comment by alexcrichton** [comment] 2015-08-04 16:27
Ah and to also clarify, Cargo doesn't modify `Cargo.toml` when it uploads a crate to crates.io. Hence the `Cargo.toml` in the `env_logger` crate is indeed valid (it's path dependency on `log` points to an actual package) within the context of the repo it came from, it's just that from the context of the crates.io download that it's invalid.

If you're downloading crates to have them available locally, you'll probably want to rewrite all `Cargo.toml` entries to point use `path` dependencies (instead of overrides) and that'll auto-apply for transitive dependencies through crates.io that originally came from paths
