### ISSUE TITLE
Third-party crate warnings exposed in my crate

### ISSUE THREAD

**Issue by SamuelMarks** [rust-lang/cargo#14232] opened 2024-07-10 21:24 UTC
### Problem

When I build my project `foo` it gives warnings from a third-party crate's test directory

### Steps

1. Add this dependency (confirmed at this commit https://github.com/offscale/cargo-make/tree/6cf59426a6e33ebaf5a769f88f5dda51a7e4cc1f )
```toml
[dependencies]
cargo-make = { git = "https://github.com/offscale/cargo-make", branch = "publicise" }
```
2. 
```
$ cargo build
warning: skipping duplicate package `member1` found at `.cargo/git/checkouts/cargo-make-1147f9fdbe23da7e/6cf5942/src/lib/test/workspace-inherit/member1`
warning: skipping duplicate package `member1` found at `.cargo/git/checkouts/cargo-make-1147f9fdbe23da7e/6cf5942/src/lib/test/workspace1/member1`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.50s
```

### Notes

Official Rust discord told me that the warning shouldn't be exposed to me

### Version

```text
cargo 1.81.0-nightly (154fdac39 2024-07-07)
release: 1.81.0-nightly
commit-hash: 154fdac39ae9629954e19e9986fd2cf2cdd8d964
commit-date: 2024-07-07
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.8.0-DEV (sys:0.4.73+curl-8.8.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 24.4.0 (noble) [64-bit]
```

**Comment by epage** [comment] 2024-07-10 21:45
This appears to be a duplicate of #10752 and closing in favor of that.  If there is a reason we should keep this open, let us know!

**Closed by epage** 2024-07-10 21:45 UTC
Labels: C-bug, S-triage
