### ISSUE TITLE
About `CARGO_TARGET_DIR` again

### ISSUE THREAD

**Issue by ssrlive** [rust-lang/cargo#12673] opened 2023-09-15 07:27 UTC
### Problem

As of today, the value of the `CARGO_TARGET_DIR` environment variable that `cargo` returns to me is still `Err(NotPresent)`. Like #7458

I use this code to print all of environment variables in `build.rs` file, not including `CARGO_TARGET_DIR`.
```rust
use std::env;
use std::fs::File;
use std::io::Write;

fn main() -> std::io::Result<()> {
    let mut f = File::create("build.log")?;
    for (key, value) in env::vars() {
        f.write_all(format!("{}: {}\n", key, value).as_bytes())?;
    }
    Ok(())
}
```

This issue exits on Windows/Linux/macOS.

### Version

```text
cargo 1.72.0 (103a7ff2e 2023-08-15)
```

I hope somebody add an item `CARGO_TARGET_DIR` to here:

https://github.com/rust-lang/cargo/blob/0ed01489d8d29d5335bd8b66899c988dd7386693/src/cargo/core/compiler/custom_build.rs#L279-L284

Ref links: #7325  and  #8710

**Comment by hi-rustin** [comment] 2023-09-15 08:07
Can I ask why do you want `CARGO_TARGET_DIR `?

**Comment by ssrlive** [comment] 2023-09-15 08:47
I need to put some files to the target dir.

**Comment by weihanglo** [comment] 2023-09-15 10:51
Without a more detailed sharing of your use case, maintainers are not able to evaluate the need of the feature request.

This is also a duplicate of <https://github.com/rust-lang/cargo/issues/9661>. Close in favor of that.

**Closed by weihanglo** 2023-09-15 10:51 UTC
Labels: C-bug, S-triage

**Comment by ssrlive** [comment] 2023-09-15 11:31
This variable is guaranteed in the [cargo documentation](https://doc.rust-lang.org/cargo/reference/environment-variables.html), and I'm curious why all the project maintainers refuse to add it. That is, why don't you remove this description from the documentation?

This implementation could be: if the `CARGO_TARGET_DIR` variable already exists, do nothing, if it does not exist, add it. Is there anything wrong with this?

**Comment by ssrlive** [comment] 2023-09-16 04:17
Through the information displayed in this image, we can infer the exact path of `CARGO_TARGET_DIR`, it's `d:\mytoy\target\x86_64-pc-windows-msvc\release`. My problem is solved.

Since `OUT_DIR` is unique, then `CARGO_TARGET_DIR` is also unique.

Now my question is: why you guys are so stubborn in not providing `CARGO_TARGET_DIR` .

![image](https://github.com/rust-lang/cargo/assets/30760636/ac2cf731-2892-4813-a160-420ddf33ca2f)

In addition, I also found a bug in your recent implementation: the two strings `d:\mytoy\target\release\deps` and `d:\mytoy\target\release` you added to the `Path` environment variable are Wrong, it should be `d:\mytoy\target\x86_64-pc-windows-msvc\release\deps` and `d:\mytoy\target\x86_64-pc-windows-msvc\release`

**Comment by ssrlive** [comment] 2023-09-16 12:05
Through the information displayed in this image, we can infer the exact path of `CARGO_TARGET_DIR`, it's `d:\mytoy\target\x86_64-pc-windows-msvc\release`. My problem is solved.

Since `OUT_DIR` is unique, then `CARGO_TARGET_DIR` is also unique.

Now my question is: why you guys are so stubborn in not providing `CARGO_TARGET_DIR` .

![image](https://github.com/rust-lang/cargo/assets/30760636/ac2cf731-2892-4813-a160-420ddf33ca2f)

Here is my code to find out `CARGO_TARGET_DIR`, hope it can help somebody.
```rust
fn get_cargo_target_dir() -> Result<std::path::PathBuf, Box<dyn std::error::Error>> {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR")?);
    let profile = std::env::var("PROFILE")?;
    let mut target_dir = None;
    let mut sub_path = out_dir.as_path();
    while let Some(parent) = sub_path.parent() {
        if parent.ends_with(&profile) {
            target_dir = Some(parent);
            break;
        }
        sub_path = parent;
    }
    let target_dir = target_dir.ok_or("not found")?;
    Ok(target_dir.to_path_buf())
}
```

In addition, I also found a **bug** in your recent implementation: the two strings `d:\mytoy\target\release\deps` and `d:\mytoy\target\release` you added to the `Path` environment variable are Wrong, it should be `d:\mytoy\target\x86_64-pc-windows-msvc\release\deps` and `d:\mytoy\target\x86_64-pc-windows-msvc\release`.

**Comment by YashankGarg04** [comment] 2023-12-21 17:40
HEY @ssrlive can you help me with environment variables setup like i tried a lot setting it up and it keep giving me the same error
![Screenshot 2023-12-21 230337](https://github.com/rust-lang/cargo/assets/110475712/188148b9-902d-468b-af44-fb0702434a2c)

I hope you can help me with it

**Comment by ohjoij-ys** [comment] 2024-02-07 07:35
> HEY @ssrlive can you help me with environment variables setup like i tried a lot setting it up and it keep giving me the same error嘿，你能帮我设置环境变量吗，就像我尝试了很多设置一样，但它一直给我同样的错误 <img alt="Screenshot 2023-12-21 230337" width="582.5454711914062" height="45.397727966308594" src="https://private-user-images.githubusercontent.com/110475712/292278041-188148b9-902d-468b-af44-fb0702434a2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODkxMDAsIm5iZiI6MTcwNzI4ODgwMCwicGF0aCI6Ii8xMTA0NzU3MTIvMjkyMjc4MDQxLTE4ODE0OGI5LTkwMmQtNDY4Yi1hZjQ0LWZiMDcwMjQzNGEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNjUzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2I4ZTdhZmUxMWI4NWY0NzNkOTdhNzZjNWUzN2VlMTUxYTQ3ZGVhNGI1MWJhMGMxZTRkMTdmYTI5NjgyNDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I8nIssmH6aTQ3_4Dy-sbM1r-lIU7lzef4jh09muNkbU">
> 
> I hope you can help me with it我希望你能帮助我


This tip tells you how to set a path to use a downloaded file.
The current error is related to the command font.
for example:
This is my error code
![image](https://github.com/rust-lang/cargo/assets/119778444/ce36e86d-99e8-4eec-9e6f-d3258c600b67)

I need to solve first Error(E0635),it's seen to related with rustc version,
so i update the rustc ,well,new error occured,
![image](https://github.com/rust-lang/cargo/assets/119778444/cc2fe684-3716-4dc7-999b-d762fce936ef)

at last,i removed folder stable-x86_64-pc-windows-msvc by mumual,
and reinstall rustc
“rustup toolchain install stable-x86_64-pc-windows-msvc”
and,all right!

**Comment by Eh2406** [comment] 2024-02-10 16:21
> This variable `CARGO_TARGET_DIR` is guaranteed in the [cargo documentation](https://doc.rust-lang.org/cargo/reference/environment-variables.html), and I'm curious why all the project maintainers refuse to add it. Another words, why don't you remove the description of `CARGO_TARGET_DIR` from the documentation?

Because the documentation does not guarantee that we provide it to build scripts. The environment variable is described in a section called "Environment variables Cargo reads". "Environment variables Cargo sets for build scripts" is the relevant section for your code snippet, and correctly does not have `CARGO_TARGET_DIR`. Do you have a suggestion for how we could make this clearer?
