### ISSUE TITLE
cargo package fails with submodules

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2657] opened 2016-05-06 18:30 UTC
[This tree](https://github.com/brson/rust-sha2/tree/broken) fails `cargo package` with:

```
   Packaging sha2 v0.1.0 (file:///home/brian/dev/rust-sha2)
   Verifying sha2 v0.1.0 (file:///home/brian/dev/rust-sha2)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rustc-serialize v0.3.19
   Compiling sha2 v0.1.0 (file:///home/brian/dev/rust-sha2/target/package/sha2-0.1.0)
target/package/sha2-0.1.0/lib.rs:5:9: 5:15 error: couldn't read "target/package/sha2-0.1.0/rust-crypto/src/buffer.rs": No such file or directory (os error 2)
target/package/sha2-0.1.0/lib.rs:5 pub mod buffer;
                                           ^~~~~~
error: failed to verify package tarball

Caused by:
  Could not compile `sha2`.

To learn more, run the command again with --verbose.
```

I've tried adding `include` directives to Cargo.toml and moving the submodule under `src`.

**Comment by brson** [comment] 2016-05-06 18:34
Oh, I did work around this with `include` after I realized I had to specify every file.

**Comment by brson** [comment] 2016-05-06 18:42
This may have to do with something else besides submodules. Even after removing the submodule I can't get this to package.

**Comment by alexcrichton** [comment] 2016-05-06 19:48
Was the submodule not checked out? Cargo doesn't automatically check out local submodules, and if it was checked out it worked locally for me

**Comment by brson** [comment] 2016-05-06 19:48
It was checked out. `cargo build` works, `cargo package` fails.

**Comment by alexcrichton** [comment] 2016-05-06 19:58
How are you repro'ing? This works for me:

```
$ git clone https://github.com/brson/rust-sha2 --branch broken --recursive
$ cd rust-sha2
$ cargo package
```

**Comment by brson** [comment] 2016-05-06 20:14
Those exact commands don't work for me.

* `rustc 1.10.0-nightly (8da2bcac5 2016-04-28)`
* `cargo 0.11.0-nightly (afac7fc 2016-04-27)`

**Comment by brson** [comment] 2016-05-06 20:16
No matter what I do `rust-crypto` doesn't exist in `target/package/sha2-0.1.0`.

**Comment by alexcrichton** [comment] 2016-05-06 20:17
Looks like this is a beta regression, I can reproduce on beta's cargo and not on stable's

**Comment by brson** [comment] 2016-05-06 20:18
Ah. Well, I'll publish this with stable, then!

**Comment by alexcrichton** [comment] 2016-05-06 20:46
Oh actually this may have been a bug fix. The traversal logic for including crates is skipping rust-crypto because it looks like a sub-crate (e.g. it has a Cargo.toml).

**Comment by carols10cents** [comment] 2017-09-25 19:32
This sounds like the change was intentional, and if this continued to have been a problem, I would have expected this issue to have had activity in the last year. Closing, please reopen if I'm mistaken!

**Closed by carols10cents** 2017-09-25 19:32 UTC
