### ISSUE TITLE
Better support for --emit

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/cargo#2342] opened 2016-01-31 17:54 UTC
I use `--emit=obj=<path>` with `cargo rustc` when building my OS. However cargo will not produce that file if the crate has already been built.

**Comment by alexcrichton** [comment] 2016-01-31 18:28
I'm going to close this as a dupe of https://github.com/rust-lang/cargo/issues/2304 (which is also about `--emit obj` and touches on this issue as well.

I'll ask the same question as over there, though, in that is there any reason a `staticlib` output is not sufficient?

**Closed** 2016-01-31 18:29 UTC

**Comment by Zoxc** [comment] 2016-01-31 19:20
You can get a object file with `ld -r $CARGO_TARGET_DIR/$target/$build_type/lib$cratename.a -o <obj-path>`, it is just that `--emit=obj=<obj-path>` is faster and more convenient.
