### ISSUE TITLE
Provide option to install packages released on or before a given date

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/cargo#10095] opened 2021-11-18 16:34 UTC
### Problem

I have the source of a rust program where I didn't store a cargo.lock. I know a date + compiler version on which "cargo build" worked, but now cargo downloads more up to date minor releases of packages + their dependancies, which don't produce a working executable

### Proposed Solution

I'm not sure exactly the best way to fix this, but the ability to somehow say "build using the state of packages on date X" would, I hope, allow me to get the program to build + run. Obviously storing cargo.lock would be better, but it's easy to forget.

**Comment by ehuss** [comment] 2021-11-18 21:27
Thanks for the feature request!  I believe this is a duplicate of #5221, so closing in favor of that.

**Closed by ehuss** 2021-11-18 21:27 UTC
Labels: C-feature-request
