### ISSUE TITLE
`cargo doc` doesn't regenerate after code change/directory removal

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1502] opened 2015-04-09 21:41 UTC
E.g. only the first `cargo doc` below runs, whereas the `cargo build` runs each time

```
$ cargo new doc-regen
$ cd doc-regen

$ cargo build
   Compiling doc-regen v0.0.1 (file:///home/huon/projects/test-rust/doc-regen)
$ touch src/lib.rs
$ cargo build
   Compiling doc-regen v0.0.1 (file:///home/huon/projects/test-rust/doc-regen)

$ cargo doc
   Compiling doc-regen v0.0.1 (file:///home/huon/projects/test-rust/doc-regen)
$ touch src/lib.rs
$ cargo doc
$ rm -rf target/doc
$ cargo doc
$
```

AFAICT, the only way to get docs to regenerate is `cargo clean`, which is... annoying for projects with lots of deps.

**Comment by FreeFull** [comment] 2015-04-09 22:46
Can reproduce with both
`cargo 0.0.1-pre-nightly (33b6aa7 2015-04-08) (built 2015-04-07)`
and
`cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-03-31)`

**Comment by alexcrichton** [comment] 2015-04-09 23:18
I believe that this is a dupe of #1447

**Closed by alexcrichton** 2015-04-09 23:18 UTC
Labels: C-doc
