### ISSUE TITLE
`OUT_DIR` variable not set

### ISSUE THREAD

**Issue by Razican** [rust-lang/cargo#3368] opened 2016-12-04 20:57 UTC
Some Travis jobs are not compiling due to `OUT_DIR` not being present on nightly on my build.rs script. Is this an expected behaviour? how could it be fixed?

Example failure: https://travis-ci.org/SUPERAndroidAnalyzer/super/jobs/181113222#L146

**Comment by joshtriplett** [comment] 2016-12-05 00:50
I can reproduce this with "cargo install ripgrep" using a cargo built from latest cargo git.  Debugging...

**Comment by joshtriplett** [comment] 2016-12-05 01:32
Looks like commit 41579bada5c7091e2be1ece45d7f7e02e62fd6b3 caused this issue.

**Comment by upsuper** [comment] 2016-12-07 08:17
This breaks building servo/rust-bindgen as well.

**Comment by JIghtuse** [comment] 2016-12-07 10:54
cargo even has failing test for me with the same symptoms: http://paste.fedoraproject.org/500936/48110771/

Can't build ripgrep too.

**Comment by SimonSapin** [comment] 2016-12-07 23:00
I’ve managed to build bindgen by replacing `env!` in the build script with `std::env::var`: https://github.com/servo/rust-bindgen/pull/323

**Comment by SimonSapin** [comment] 2016-12-07 23:02
Still, it looks like this is a breaking change. So Cargo should probably revert to providing these variables when compiling a build script. At least for a while, with a warning that this will change.

**Comment by joshtriplett** [comment] 2016-12-07 23:13
It looks like commit 95193ca773a668b993891eefe08f3436752b7556 clarified the documentation to state that Cargo doesn't set these environment variables when building the build script, only when running it, even though Cargo did actually set them when building the build script as well.  A later commit in Cargo then made the behavior match the documentation.

This does indeed represent a breaking change from the existing behavior, and existing build.rs scripts relied on the existing behavior.

**Comment by alexcrichton** [comment] 2016-12-09 00:44
Ah this is definitely an accidental regression! Yes `env!("OUT_DIR")` is likely not what you want but rather `std::env::var` is correct in build scripts. The `env!` version is the out dir that the build script was built with, and the `env::var` version is for when the build script is being run.

I'm kinda surprised that `env!` ever worked...

**Comment by alexcrichton** [comment] 2016-12-09 00:52
Well... so this was a "regression" but also a bug fix at the same time. The `OUT_DIR` environment variable can be different when the build script is being compiled compared to when the build script is being run. Notably during cross compilation these two can be different. This means that crates which use `env!("OUT_DIR")` I believe are broken for cross compiles where crates which use `env::var("OUT_DIR")` will correctly work with cross compiles.

To those hitting this issue, could you confirm that the crate hasn't been used for cross compiles? And perhaps if it has have weird issues arisen?

We could add a fix for this but I'm tempted to avoid doing so if we can (as it's "incorrect" to rely on the old behavior). If it's possible to fixup the packages in question quickly that'd be best, but if there's ongoing pain then I can change Cargo back to the previous behavior.

**Comment by joshtriplett** [comment] 2016-12-09 03:11
@alexcrichton I've seen various crates get fixed for this change (which, at a minimum, needs documentation in release notes).

It'd be good to be able to build existing packages with new Cargo.  For the most part, Cargo has maintained backward compatibility across many versions.  On the other hand, I do agree that crates shouldn't rely on the old behavior, and it would indeed have broken cross-compiles.

I don't see an obvious way to work-but-warn in this case, without awful hacks (such as somehow substituting in a version of `env!` that produces a warning).

**Comment by alexcrichton** [comment] 2016-12-11 18:59
Yes my only worry is if crates can't be updated. Crates can use `std::env::var` and work across all versions of Cargo, so if a crate can be proactively updated I'm not too worried about it.

**Comment by SimonSapin** [comment] 2016-12-11 19:54
Can crater be used to find out what on crates.io is broken by this change?

**Comment by alexcrichton** [comment] 2016-12-13 00:02
@SimonSapin I believe so, yes, we should see it in the next crater run (as soon as it's working)

**Comment by brson** [comment] 2016-12-30 21:17
pinyin-0.0.5 hits this.

**Comment by brson** [comment] 2016-12-30 22:05
zip_codes-0.0.1 is affected cc @SkylerLipthay

**Comment by SkylerLipthay** [comment] 2016-12-31 00:17
Alex fixed this with SkylerLipthay/zip_codes#2, which has been merged! `zip_codes 0.1.0` was subsequently released.

**Comment by brson** [comment] 2016-12-31 00:57
Affects rasen-0.1.0

https://tools.taskcluster.net/task-inspector/#_6XeY7pIRjKvuBDVVuFMFQ/0

**Comment by brson** [comment] 2016-12-31 00:57
Great @SkylerLipthay! Sorry for the inconvenience.

**Comment by alexcrichton** [comment] 2016-12-31 03:22
@brson I think pinyin and rasen were both addressed here -- https://github.com/rust-lang/rust/issues/38391#issuecomment-269524203

**Comment by brson** [comment] 2017-01-05 01:53
lmdb-rs 0.7.3's test suite is affected.

**Comment by alexcrichton** [comment] 2017-01-06 01:26
@brson looks like that was fixed by https://github.com/vhbit/lmdb-rs/commit/25c1fdc71f3ee1099de4341cf165532f57f94dea

**Comment by alexcrichton** [comment] 2017-01-12 17:10
Ok we've decided to close this as working as intended, but if any projects need help migrating please just let me know!

**Closed by alexcrichton** 2017-01-12 17:10 UTC

**Comment by abonander** [comment] 2018-03-12 07:12
@alexcrichton The story isn't over, however: https://github.com/abonander/mime_guess/issues/33

This invocation is at the build time of the crate: https://github.com/abonander/mime_guess/blob/master/src/lib.rs#L16

When `OUT_DIR` should be defined at that point because there is a build.rs.

**Comment by alexcrichton** [comment] 2018-03-12 14:01
@abonander maybe the version of Cargo there is too old to recognize the implicit build script via `build.rs`?

**Comment by abonander** [comment] 2018-03-12 21:31
@alexcrichton Good call! The issue reporter was running a Docker container with a super-outdated Cargo.
