### ISSUE TITLE
running `cargo test` when a rebuild is needed causes mixed text output

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/cargo#2550] opened 2016-04-07 21:04 UTC
This results in (due to `rustc` emitting warnings) the bolding and coloring of lines to be wrong (some parts that wanted to be yellow are bold & yellow, for example) and some of the warning lines begin at the end of others, or are otherwise mixed together.

`cargo` should probably be buffering rustc output and emitting rustc output from different invocations separately. I believe [ninja](https://ninja-build.org) is a build system that has already solved this in a similar manner, perhaps it can provide some impl hints.

**Comment by alexcrichton** [comment] 2016-04-08 00:13
This is a dupe of https://github.com/rust-lang/cargo/issues/1198 (also reported as https://github.com/rust-lang/cargo/issues/1854), and I think the best course of action here is actually https://github.com/rust-lang/rust/issues/32486, but unfortunately it's impossible to fix the problem everywhere on windows :(

**Closed by alexcrichton** 2016-04-08 00:13 UTC
