### ISSUE TITLE
Cargo doc does not pass `--cfg doc` for build scripts

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/cargo#8944] opened 2020-12-05 01:40 UTC
The issue of needing to be able to disable things like pkg-config checks in build scripts for FFI `-sys` crates has been raised previously (for example [this](https://github.com/crate-ci/meta/issues/13) or [this](https://github.com/rust-lang/docs.rs/issues/147)). We now have `cfg(doc)` as of Rust 1.41, however it seems that this is not used when running build scripts. Why? Please could this be changed/fixed?

I have just successfully converted some of my crates to use `cfg(doc)` outside of the build script, from previously using the `dox` feature technique. Wanting to rid my crates now of the `dox` feature I tried fixing the last remaining use of it - the build script. Unfortunately I have found that `cfg(doc)` does not work there, nor does `CARGO_CFG_DOC`. Looking at the output from `cargo doc -vv` it is clear that cargo is not signalling doc mode to `rustc` when executing the build script.

I am aware of the `rustc-args` key of `docs.rs` metadata, and I believe that setting it to `["--cfg", "doc"]` may work around this problem for docs.rs, allowing me to ditch my `dox` feature.

However, (1) why am I having to implement such a workaround, why is cargo not passing it along itself? (2) although this helps in the docs.rs case, it does not enable users generating local documentation to get to do so without the presence of the system library, and it would be nice to allow them to do so, because why have such a restriction.

I could leave the `dox` feature in place to address point 2, but it only helps for direct generation of crate docs, not so much when it's a dependency of something else. Additionally, it complicates things compared to cargo just passing `--cfg doc` along, and I don't really want the messy cruft of keeping `dox` around.

I'm using the Debian Sid cargo package, which is currently version 1.42.1 (0.43.1). I did check through the cargo changelog and saw no signs that this has already been addressed.

**Comment by jnqnfe** [comment] 2020-12-05 03:23
Related to / dup of #8811

**Comment by jnqnfe** [comment] 2020-12-05 19:10
I've updated to cargo v1.46 (0.47) and there seems to be no difference.

**Comment by ehuss** [comment] 2021-01-07 02:29
Linking some similar issues: #3053 and #4001.  Currently build scripts don't differentiate on any of the commands/modes.

**Comment by epage** [comment] 2023-09-30 00:23
See also https://github.com/rust-lang/cargo/issues/8811#issuecomment-1531988870

**Comment by epage** [comment] 2023-09-30 00:27
As far as I can tell, this is a dupe of #8811, I'm closing this in favor of it.

If there is a reason we need this separate issue, let us know and we can revisit!

**Closed by epage** 2023-09-30 00:27 UTC
Labels: C-bug, Command-doc, A-build-scripts
