### ISSUE TITLE
relative target-dirs cause spurious rebuilds

### ISSUE THREAD

**Issue by metajack** [rust-lang/cargo#1694] opened 2015-06-08 19:10 UTC
If you have two packages in a repo and wish to use shared target dirs to avoid rebuilds, you might use relative target-dir specs (one in each package) to do this by setting them to `../target` or something.

This causes cargo to rebuild everything, probably because it sees the two target dirs as `/path/to/package_a/../target" and "/path/to/package_b/../target".

Right now you can workaround this by using absolute paths through the CARGO_TARGET_DIR environment var.

**Comment by alexcrichton** [comment] 2015-06-08 21:41
After some investigation I've found this to be a dupe of https://github.com/rust-lang/cargo/issues/497

**Comment by alexcrichton** [comment] 2015-06-08 22:19
Hm actually, I'm going to swap these around, so I'm going to reopen this (but a fix will be posted very soon).

**Closed** 2015-06-08 22:46 UTC
