### ISSUE TITLE
cannot publish clippy anymore: ValueAfterTable

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/cargo#4092] opened 2017-05-24 13:19 UTC
Relevant Cargo.toml: https://github.com/Manishearth/rust-clippy/blob/master/Cargo.toml

building in debug and release works fine, installing debug/release works fine, just publishing fails.

backtrace is

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: cargo::core::package::Package::to_registry_toml
  11: cargo::ops::cargo_package::package
  12: cargo::ops::registry::publish
  13: cargo::try_execute_builtin_command
  14: cargo::execute
  15: cargo::call_main_without_stdin
  16: cargo::main
  17: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  18: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:56
  19: __libc_start_main
  20: <unknown>
```

Rustc version is rustc 1.19.0-nightly (5b13bff52 2017-05-23)
Cargo version is cargo 0.20.0-nightly (397359840 2017-05-18)

last publish on 2017-05-19 worked fine with rustc 1.19.0-nightly (0ed1ec9f9 2017-05-18) 

A related change might be that we moved to workspaces since then, but even so, the error message should produce something more useful I think. Removing workspaces doesn't fix it. This error is occurring even before the publish starts the first build of any dependencies.

**Comment by alexcrichton** [comment] 2017-05-24 15:41
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/4081 which was fixed in https://github.com/rust-lang/cargo/issues/4085, but I'll go update the submodule in rust-lang/rust so we can get this released

**Closed by alexcrichton** 2017-05-24 15:41 UTC
