### ISSUE TITLE
cargo_metadata requires rustc to be on the $PATH

### ISSUE THREAD

**Issue by illicitonion** [rust-lang/cargo#9295] opened 2021-03-23 14:41 UTC
**Problem**

I tried to run `cargo metadata` with only a `cargo` binary on my `$PATH`, and no `rustc`.

I got an error that `rustc` could not be found.

**Steps**

1. Remove `rustc` from your `$PATH`
2. Run `cargo metadata` in some directory containing a `Cargo.toml` file

**Notes**

It appears to be because of this line of code:

https://github.com/rust-lang/cargo/blob/58a961314437258065e23cb6316dfc121d96fb71/src/cargo/ops/cargo_output_metadata.rs#L113

Which calls `RustcTargetData::new`.

This value doesn't appear to actually be used by any of the following code-paths, it's only used if some conditionals are hit which aren't triggered in the `cargo metadata` path (or at least, aren't without additional flags).

It would be useful to not need a `rustc` binary present in order to run `cargo metadata`.

**Possible Solution(s)**

I can imagine either making the `rustc -vV` invocation lazy, or a refactoring to not need to pass that arg around (or accept an `Option`)?

**Comment by ehuss** [comment] 2021-03-23 17:20
Hi!  `rustc` is needed for computing target-specific features.  Closing as a duplicate of #8219.

**Closed by ehuss** 2021-03-23 17:20 UTC
Labels: C-bug
