### ISSUE TITLE
Publish Workspace

### ISSUE THREAD

**Issue by kyledecot** [rust-lang/cargo#14347] opened 2024-08-03 14:38 UTC
### Problem

When publishing a workspace based crate that has path based dependencies `A -> B -> C -> D` you need to run a separate cargo publish command for each dependency:

```
cargo publish -p d
cargo publish -p c
cargo publish -p b
cargo publish
```

This requires that the publish commands are ran in the correct order which becomes more difficult as the dependency graph grows.

### Proposed Solution

Support publishing all local/path based crates via:

```
cargo publish --workspace
```

**Comment by weihanglo** [comment] 2024-08-03 14:52
Thanks. This is a duplicate of <https://github.com/rust-lang/cargo/issues/1169> so going to close in favor of that.

People are currently working on some prerequisite for `cargo publish --workspace`. See <https://github.com/rust-lang/cargo/issues/10948> its related PR #13926 #13947.

**Closed by weihanglo** 2024-08-03 14:52 UTC
Labels: C-feature-request, S-triage
