### ISSUE TITLE
cargo publish --dry-run - missing validation e.g. number of keywords

### ISSUE THREAD

**Issue by 2ndTaleStudio** [rust-lang/cargo#8731] opened 2020-09-25 08:40 UTC
**Problem**
When running `cargo publish --dry-run` several validations does not seem to be executed. One example is the usage of too many keywords. While `cargo publish --dry-run` succeeds with e.g. 9 keywords the actual publishing will fail with the message that too many keywords have been passed.

**Steps**
1. create a project (eg. `cargo new`)
2. adjust the `keywords` in `Crago.toml` to contain 6 or more entries
3. run `cargo publish --dry-run` - it will not complain

**Possible Solution(s)**
crates.io may provide a proper validation endpoint to also run the verifications on the server when running `--dry-run` without actually publishing the crate

**Notes**

Output of `cargo version`:

cargo 1.47.0-nightly (aa6872140 2020-07-23)

**Comment by ehuss** [comment] 2020-09-25 15:30
Thanks for the report!  I think this is a duplicate of #4377, #4300, and #2098, so closing in favor of those.

**Closed by ehuss** 2020-09-25 15:30 UTC
Labels: C-bug
