### ISSUE TITLE
Cargo config.toml - "access is denied"

### ISSUE THREAD

**Issue by Inari-Whitebear** [rust-lang/cargo#3986] opened 2017-05-02 10:56 UTC
System:
OS: Windows Home 10 (Anniversary Update)
toolchain: nightly-x86_64-pc-windows-gnu (default)
`cargo: cargo 0.19.0-nightly (fa7584c14 2017-04-26)`

I have a project at D:\Dev\Rust\arduino-cli. I have tried creating a "config" folder in D:\Dev\Rust\arduino-cli\.cargo and it won't work properly. Trying to use C:\Users\Inari\.cargo\config doesn't work either.
When that config folder in .cargo is present, cargo just refuses to work, whether or not I put a file inside. 

    D:\Dev\Rust\arduino-rs>cargo build --verbose
    error: Couldn't load Cargo configuration
    
    Caused by:
      Access is denied. (os error 5)

I tried turning Windows Defender off, it didn't help. I tried running Dr.Memory's strace thingy, relevant things form that I can find there is a bunch of this:

```
NtQueryVolumeInformationFile.FileFsVolumeInformation
	arg 0: 0x1d4 (type=HANDLE, size=0x8)
	arg 1: 0x0000000000f4b318 (type=IO_STATUS_BLOCK*, size=0x8)
	arg 2: 0x0000000000f4b3a0 (type=<struct>*, size=0x8)
	arg 3: 0x18 (type=unsigned int, size=0x4)
	arg 4: 0x1 (type=named constant, size=0x4)
    succeeded =>
	arg 1: status=0x0, info=0x12 (type=IO_STATUS_BLOCK*, size=0x8)
	arg 2: _FILE_FS_VOLUME_INFORMATION {_LARGE_INTEGER {0x1d0d12c03ab2ab1}, int=0xda0486f5, int=0x0, byte|bool=0x1, array(2)={0x0, 0x0}} (type=<struct>*, size=0x8)
	retval: 0x0 (type=NTSTATUS, size=0x4)
NtQueryInformationFile.FileAllInformation
	arg 0: 0x1d4 (type=HANDLE, size=0x8)
	arg 1: 0x0000000000f4b318 (type=IO_STATUS_BLOCK*, size=0x8)
	arg 2: 0x0000000000f4b330 (type=<struct>*, size=0x8)
	arg 3: 0x68 (type=unsigned int, size=0x4)
	arg 4: 0x12 (type=named constant, size=0x4)
    failed (error=0x80000005) =>
	arg 1: status=0x80000005, info=0x68 (type=IO_STATUS_BLOCK*, size=0x8)
	arg 2: _FILE_ALL_INFORMATION {_FILE_BASIC_INFORMATION {_LARGE_INTEGER {0x1d12a1051f2f630}, _LARGE_INTEGER {0x1d2c321e13a5fd0}, _LARGE_INTEGER {0x1d2c321e13a5fd0}, _LARGE_INTEGER {0x1d2c321e13a5fd0}, int=0x10}, _FILE_STANDARD_INFORMATION {_LARGE_INTEGER {0x1000}, _LARGE_INTEGER {0x1000}, int=0x1, byte|bool=0x0, byte|bool=0x1}, _FILE_INTERNAL_INFORMATION {_LARGE_INTEGER {0x5a000000016df4}}, _FILE_EA_INFORMATION {int=0x0}, _FILE_ACCESS_INFORMATION {int=0x100080}, _FILE_POSITION_INFORMATION {_LARGE_INTEGER {0x0}}, _FILE_MODE_INFORMATION {int=0x20}, _FILE_ALIGNMENT_INFORMATION {int=0x1}, _FILE_NAME_INFORMATION {int=0x26, array(2)={0x5c, 0x0}}} (type=<struct>*, size=0x8)
	retval: 0x80000005 (type=NTSTATUS, size=0x4)
```

The NtQueryVolumeInformationFile.FileFsVolumeInformation succeeds, but the NtQueryInformationFile.FileAllInformation following it fails. (Full log: https://gist.github.com/Inari-Whitebear/ee1cfb6aec0b464cf2b94ac56ba8dd26 )

I also tried running procmon, it seems to disagree and instead says the NtQueryInformationFile.FileAllInformation calls fail repeatedly with BUFFER_OVERFLOW results. I was told on IRC those are expected, it just means the caller hasn't provided a big enough buffer for the result. The callers apparently would just recall it with a bigger buffer. But it never seems to succeed. (Procmon log (CSV): https://gist.github.com/Inari-Whitebear/6674b8975617edfbb24700f44ae71042 )

**Comment by alexcrichton** [comment] 2017-05-02 14:23
Could you gist the relevant configure files you've got on the system? That may help indicate what error is happening here perhaps?

**Comment by alexcrichton** [comment] 2017-05-02 14:24
(we also definitely need to improve this error message!)

**Comment by Inari-Whitebear** [comment] 2017-05-02 15:04
Sure, but it also happens when I even only create the config directory, not putting anything into it.
https://gist.github.com/Inari-Whitebear/f10fe36bb7d8c691453a40d51a97e9e0
I tried modifying the paths too, since I use windows. Tried "D:\Dev\Rust\libusb-1.0.21\<platform>\static" as well as "/D/Dev/Rust/libusb-1.0.21/<platform>/static"

**Comment by alexcrichton** [comment] 2017-05-03 17:01
I've opended [a PR](https://github.com/rust-lang/cargo/pull/3991) to hopefully improve the error message here

**Comment by Inari-Whitebear** [comment] 2017-05-14 20:38
Hm, did the PR already make it into the new release?

```
Inari@Neptune MINGW64 /d/dev/rust/arduino-rs (master)
$ cargo build --verbose
error: Couldn't load Cargo configuration

Caused by:
  Access is denied. (os error 5)

Inari@Neptune MINGW64 /d/dev/rust/arduino-rs (master)
$ cargo -V
cargo 0.20.0-nightly (cf17c9f71 2017-05-09)

```

**Comment by alexcrichton** [comment] 2017-05-15 14:32
@Inari-Whitebear could you try running `strace` to home in on where the error is coming from? Looks like the PR didn't help :(

**Comment by carols10cents** [comment] 2017-10-02 23:31
> I have a project at D:\Dev\Rust\arduino-cli. I have tried creating a "config" folder in D:\Dev\Rust\arduino-cli.cargo and it won't work properly. Trying to use C:\Users\Inari.cargo\config doesn't work either.

Hm, it looks to me like the problem is that `.cargo` is supposed to be a *subdirectory* and `config` is supposed to be a *file*. That is, instead of creating this directory:

```
D:\Dev\Rust\arduino-cli.cargo\config\
```

What cargo is looking for is a subdirectory of `arduino-cli` whose name is `.cargo`:

```
D:\Dev\Rust\arduino-cli\.cargo
```

And within that directory, a file named `config`:

```
D:\Dev\Rust\arduino-cli\.cargo\config
```

I'm pretty sure that's the problem, so I'm going to close this issue (also since it hasn't had any recent activity). If this is *not* the problem, and the problem is still happening, or if you have ideas on how to improve the documentation, please reopen! Thanks!!

**Closed by carols10cents** 2017-10-02 23:31 UTC
