### ISSUE TITLE
`cargo check` produces dead_code warnings for bin targets

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#3420] opened 2016-12-17 10:28 UTC
For a project generated with `cargo new --bin`:

```
warning: function is never used: `main`, #[warn(dead_code)] on by default
 --> src/main.rs:1:1
  |
1 |   fn main() {
  |  _^ starting here...
2 | |     println!("Hello, world!");
3 | | }
  | |_^ ...ending here

```

**Comment by alexcrichton** [comment] 2016-12-17 22:56
I believe this is a dupe of https://github.com/rust-lang/rust/issues/38273, but thanks for the report!

**Closed by alexcrichton** 2016-12-17 22:56 UTC
