### ISSUE TITLE
Cargo install: spurious network error

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [rust-lang/cargo#11344] opened 2022-11-06 16:14 UTC
### Problem

Hi, I'm new to Rust and would like to start learning it. Problem is that I have to turn off my windows firewall completely to install packages. I also allowed cargo.exe to pass trough, yet the rule doesn't seem to apply. 

How do you set your firewall rules for Rust correctly?
I'm allowing it inbound, as well as outbound.

![d912593878c782111a866767a5e0324cf1e58d7c](https://user-images.githubusercontent.com/45887282/200181858-1f9b5772-14f5-4d98-bc08-0114b50e87f2.png)

npm, git and other package managers work.

update: tried to edit the cargo conf with use github cli true... now it just hangs in updating. and then throws: 

```
    Updating crates.io index
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to crates.io port 443 after 17 ms: Bad access)
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server (Failed to connect to crates.io port 443 after 20 ms: Bad access)
error: failed to download from `https://crates.io/api/v1/crates/tokio/1.21.2/download`

Caused by:
  [7] Couldn't connect to server (Failed to connect to crates.io port 443 after 39 ms: Bad access)

```

Here are some Proxifier Logs when Windows Firewall is disabled: 

```
[11.06 13:34:24] cargo.exe (11792) - 127.0.0.1:54760 matching any:allow rule : direct connection
[11.06 13:34:24] cargo.exe (11792) - api.github.com(140.82.121.5):443 matching any:allow rule : direct connection
[11.06 13:34:25] cargo.exe (11792) - 127.0.0.1:54763 matching any:allow rule : direct connection
[11.06 13:34:25] cargo.exe (11792) - crates.io(13.226.153.36):443 matching any:allow rule : direct connection
[11.06 13:34:25] svchost.exe (2368) - o.ss2.us resolve via 192.168.178.1:53 : DNS
[11.06 13:34:25] lsass.exe (528) - o.ss2.us(13.226.156.205):80 matching any:allow rule : direct connection
[11.06 13:34:25] svchost.exe (2368) - ocsp.rootg2.amazontrust.com resolve via 192.168.178.1:53 : DNS
[11.06 13:34:25] lsass.exe (528) - ocsp.rootg2.amazontrust.com(13.226.156.74):80 matching any:allow rule : direct connection
[11.06 13:34:25] svchost.exe (2368) - ocsp.rootca1.amazontrust.com resolve via 192.168.178.1:53 : DNS
[11.06 13:34:25] lsass.exe (528) - ocsp.rootca1.amazontrust.com(13.226.156.65):80 matching any:allow rule : direct connection
[11.06 13:34:25] cargo.exe (11792) - 127.0.0.1:54769 matching any:allow rule : direct connection
[11.06 13:34:25] svchost.exe (2368) - static.crates.io resolve via 192.168.178.1:53 : DNS
[11.06 13:34:25] cargo.exe (11792) - static.crates.io(108.157.4.10):443 matching any:allow rule : direct connection

```

Now why is cargo using svchost.exe to connect? And how would I create a firewall rule for it's use with cargo?

These are the Logs when Windows Firewall is Enabled and cargo fails: 

```
[11.06 13:37:18] cargo.exe (9688) - 127.0.0.1:54808 matching any:allow rule : direct connection
[11.06 13:37:18] svchost.exe (2368) - api.github.com resolve via 192.168.178.1:53 : DNS
[11.06 13:37:18] cargo.exe (9688) - api.github.com(140.82.121.6):443 matching any:allow rule : direct connection
[11.06 13:37:18] svchost.exe (2368) - github.com resolve via 192.168.178.1:53 : DNS
[11.06 13:37:18] cargo.exe (9688) - github.com(140.82.121.4):443 matching any:allow rule : direct connection
[11.06 13:37:18] cargo.exe (9688) - github.com(140.82.121.4):443 matching any:allow rule : direct connection
[11.06 13:37:18] cargo.exe (9688) - github.com(140.82.121.4):443 matching any:allow rule : direct connection


```

### Steps

cargo install tokio

### Possible Solution(s)

turn off ssl revoke check
set github fetch with cli

### Version

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
```

## curl
```

C:\Users\_\Desktop\test-core>curl https://github.com/rust-lang/crates.io-index
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
```

after that I tried:

```
[http]
check-revoke = false
```

> It seems that a curl call works if i add the off ssl revoke flag!

Still cargo won't install anything.
The config file won't work.

#### Last state of my config.toml file:

```
[net]
git-fetch-with-cli = true
[http]
debug = true
check-revoke = false
```

I'm really curious about whats causing this. Nobody knows?

**Comment by weihanglo** [comment] 2022-11-07 11:30
I am sorry to hear you having this issue. I don't think I am helpful enough, as my experience with Windows is not sufficient 😞.

If you use `git-fetch-with-cli = true` but is still failing, could you try `git clone https://github.com/rust-lang/crates.io-index` and see if it works?

By the way, you may get more advice on the user forums https://users.rust-lang.org/, where people are likely with more experience with this specific network issue.

**Comment by weihanglo** [comment] 2022-11-07 12:02
Oh. Now I see your error. It seems not directly related to git. 

Could you try and see what `curl https://crates.io/api/v1/crates/tokio/1.21.2/download` report as well?

**Comment by weihanglo** [comment] 2022-11-07 12:09
My fault. We need `-L` flag. Try `curl -vL https://crates.io/api/v1/crates/tokio/1.21.2/download` instead.

**Comment by ehuss** [comment] 2022-12-11 19:32
I'm going to close, as I think this is a duplicate of #8688 and #7104. Windows, unlike all other platforms, defaults to checking for TLS revocation certificates. We have considered disabling that on Windows, but have not followed through. This might also be resolved if crates.io leaves Heroku and switches to a service that supports OCSP stapling.

**Closed by ehuss** 2022-12-11 19:32 UTC
Labels: C-bug, O-windows, A-networking
