### ISSUE TITLE
Intermediate JSON output in next `test` run after running cargo bloat

### ISSUE THREAD

**Issue by barafael** [rust-lang/cargo#10162] opened 2021-12-04 15:47 UTC
### Problem

Under certain reproducible conditions, namely after running `cargo bloat --time`, I am seeing json-like output when running `cargo test`, before it prints anything else.

This seems like cargo-bloat is involved somehow, but the erroneous output happens in `cargo test`, hence the report here.

After running `cargo clean`, everything is fine again.

### Steps

1. Checkout this repo at this commit: [https://github.com/barafael/aoc-2021/commit/e12dcbd0bb4bd9e197088e9da6da0f72c19e7975](https://github.com/barafael/aoc-2021/commit/e12dcbd0bb4bd9e197088e9da6da0f72c19e7975
)
2. Run `cargo clean` for good measure
3. Run `cargo bloat --time`
4. Run `cargo test`
Observe output of last command.
On my machine:
```
> cargo test                                                                                                                               4636ms  Sa 04 Dez 2021 16:36:30 CET
json-time {"crate_name":"proc_macro2","time":269595042,"build_script":true}
json-time {"crate_name":"unicode_xid","time":96045337,"build_script":false}
json-time {"crate_name":"syn","time":254209896,"build_script":true}
json-time {"crate_name":"memchr","time":233940419,"build_script":true}
json-time {"crate_name":"regex_syntax","time":1925829366,"build_script":false}
json-time {"crate_name":"either","time":143754807,"build_script":false}
json-time {"crate_name":"proc_macro2","time":498470754,"build_script":false}
json-time {"crate_name":"itertools","time":1096157067,"build_script":false}
json-time {"crate_name":"quote","time":244878428,"build_script":false}
json-time {"crate_name":"memchr","time":464017479,"build_script":false}
json-time {"crate_name":"syn","time":1765319992,"build_script":false}
json-time {"crate_name":"aho_corasick","time":851403862,"build_script":false}
json-time {"crate_name":"thiserror_impl","time":1099171127,"build_script":false}
json-time {"crate_name":"regex","time":1546058852,"build_script":false}
json-time {"crate_name":"thiserror","time":78013683,"build_script":false}
json-time {"crate_name":"aoc","time":353675576,"build_script":false}
   Compiling aoc v0.1.0 (/home/rafaelbachmann/AoC/aoc)
    Finished test [unoptimized + debuginfo] target(s) in 1.04s
     Running unittests (target/debug/deps/aoc-7696c8db73797144)

running 36 tests
test day01::tests::sonar_sweep_returns_0_increases_on_emtpy_array ... ok
test day01::tests::sonar_sweep_returns_2_increases ... ok
test day01::tests::sonar_sweep_filtered_returns_5_increases ... ok
test day01::tests::sonar_sweep_returns_3_increases ... ok
test day01::tests::sonar_sweep_returns_7_increases ... ok
test day02::problem_1::tests::basic_input_results_in_15 ... ok
test day02::problem_2::tests::basic_input_results_in_900 ... ok
test day03::problem_1::tests::computes_basic_input ... ok
test day03::problem_2::tests::calculates_basic_co2_is_10 ... ok
test day03::problem_2::tests::calculates_basic_oxygen_is_23 ... ok
test day03::test::counts_ones_in_all_columns ... ok
test day03::problem_2::tests::splits_by_bit ... ok
test day03::test::parses_basic_input ... ok
test day04::board::tests::detects_columns ... ok
test day03::test::counts_ones_in_column ... ok
test day04::board::tests::detects_rows ... ok
test day04::board::tests::marks_numbers ... ok
test day04::board::tests::detects_win ... ok
test day04::board::tests::parses_board_from_basic_example_str ... ok
test day04::game::test::parses_game ... ok
test day04::board::tests::sums_up_unmarked ... ok
test day04::problem_1::test::computes_basic_input ... ok
test day01::tests::sonar_sweep_returns_amount_of_increases ... ok
test day03::problem_2::tests::computes_solution ... ok
test day03::problem_1::tests::computes_result ... ok
test day02::parse::test::accepts_empty_input ... ok
test day01::tests::sonar_sweep_filtered_returns_amount_of_increases ... ok
test day02::parse::test::parses_sample_str ... ok
test day04::problem_2::tests::computes_basic_input ... ok
test day04::game::test::parses_input_ok ... ok
test day02::parse::test::rejects_invalid_input ... ok
test day04::problem_1::test::computes_solution ... ok
test day02::problem_1::tests::computes_result ... ok
test day02::parse::test::parses_input_str_ok ... ok
test day02::problem_2::tests::computes_result ... ok
test day04::problem_2::tests::computes_result ... ok

test result: ok. 36 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

   Doc-tests aoc

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

### Notes

The content of file e.g. `target/debug/.fingerprint/regex-dd9363dd410b6a25/output-lib-regex` is 
`json-time {"crate_name":"regex","time":1632050408,"build_script":false}
`
which is a line from the superfluous output. There are many other files like it in `target/debug/.fingerprint/`. Just an observation.

### Version

```text
> cargo version --verbose                                                                                                                  2355ms  Sa 04 Dez 2021 16:47:18 CET
cargo 1.58.0-nightly (2e2a16e98 2021-11-08)
release: 1.58.0
commit-hash: 2e2a16e983f597da62bc132eb191bc3276d4b1bb
commit-date: 2021-11-08
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.50+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.04 (focal) [64-bit]```
```

**Comment by ehuss** [comment] 2021-12-04 16:14
Thanks for the report!  I believe this is a duplicate of #9553, so closing in favor of that.

**Closed by ehuss** 2021-12-04 16:14 UTC
Labels: C-bug
