### ISSUE TITLE
Quieter build output

### ISSUE THREAD

**Issue by opeik** [rust-lang/cargo#9724] opened 2021-07-25 05:54 UTC
Hi there,

**Describe the problem you are trying to solve**
One of the few issues I have with Cargo is the amount of output on a typical `cargo build` invocation. The line per crate is built is pretty to look at but consumes my terminal.

**Describe the solution you'd like**
A `--progress={bar | full}` flag or something to that effect would be nice. The `bar` option would only display the progress bar. The `full` option would be the current behaviour, one line per crate as well as the progress bar. It would also be nice to be able to set this globally via `Cargo.toml`.

**Notes**
I was thinking of implementing this feature and opening a full request. Related to #8889 (overhauling the entire output).

**Comment by ehuss** [comment] 2021-08-04 18:53
Thanks for the suggestion!  I think we generally agree that it would be nice to avoid too much verbose output.  However, we generally try to avoid adding too many options for adjusting settings like that.  I'm going to close, as I think this is essentially a duplicate of #8889, and I think it would be best to keep the discussion of changing the output in one place.

**Closed by ehuss** 2021-08-04 18:53 UTC
Labels: C-feature-request
