### ISSUE TITLE
Retry package downloads when they fail

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/cargo#1605] opened 2015-05-13 05:14 UTC
Right now I'm dealing with a flaky internet connection, and sometimes when Cargo is downloading packages, I get `Unable to get packages from source`. If I retry the command, it is usually able to reconnect instantly, but I sometimes need to retry it 3-4 times before it finishes downloading everything. Cargo should retry downloads once or twice to prevent this situation.

**Comment by huonw** [comment] 2015-05-13 05:46
https://github.com/rust-lang/cargo/issues/1602 is related, but even if that is implemented it may also make sense to have a default retry count larger than 1 (per this issue).

**Comment by alexcrichton** [comment] 2015-05-13 16:02
Thanks for the report! I think I'd consider this a dupe of #1602 as in implementing that we're either going to say the default retry count is 1 or we're going to make it higher.

**Closed by alexcrichton** 2015-05-13 16:02 UTC
