### ISSUE TITLE
Allow specifying `cfg` expressions for `lib` targets

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#4900] opened 2018-01-05 01:54 UTC
Hi! It looks like it's not possible to specify architecture-specific fields for a `lib` target. I tried adding a `[target.'cfg(any(target_os="android", target_os="ios"))'.lib]` section to `Cargo.toml`, as in https://github.com/mozilla-prototypes/sync-storage-prototype/pull/10#discussion_r159790273, but Cargo warns that it's an unused manifest key.

In case it helps, the crate in question, `toodle`, is a library that's cross-compiled for iOS and Android, and also imported as a regular Rust crate by another crate (`toodlext`). `crate-type = ["staticlib", "cdylib"]` seems to be necessary for cross-compiling (`cargo lipo` fails without it), but leaving it under `lib` breaks `toodlext`, with `cargo build` complaining that it can't find the `toodle` crate (kitcambridge/sync-storage-prototype#1).

/cc @fluffyemily

**Comment by epage** [comment] 2023-10-17 20:45
The thing I'm wondering is if it is best to handle this in a single package or to have different packages that exhibit the behavior needed for each of those platforms.

**Comment by epage** [comment] 2023-10-31 01:18
It looks like #12260 is a duplicate of this but #12260 has more discussion, so closing in favor of that.  If there is anything I overlooked, let us know!

**Closed by epage** 2023-10-31 01:18 UTC
Labels: C-feature-request, A-cross-compiling, A-manifest, S-needs-info
