### ISSUE TITLE
Dependencies that should not be built in the target arch are still built

### ISSUE THREAD

**Issue by xxuejie** [rust-lang/cargo#8940] opened 2020-12-04 01:42 UTC
**Problem**

https://github.com/xxuejie/cargo-target-dep-test This is a minimal repo reproducing the problem. As denoted [here](https://github.com/xxuejie/cargo-target-dep-test/blob/61b721e0047300089bdf6207d59bd2750db3bbae/Cargo.toml#L12), the included dependency should not be built in riscv64 targets, yet it is still built.

**Steps**

1. git clone https://github.com/xxuejie/cargo-target-dep-test
2. cd cargo-target-dep-test
3. rustup target add riscv64imac-unknown-none-elf
4. cargo build --target riscv64imac-unknown-none-elf

This would result an error. Even though `ckb-x64-simulator` is marked as a dependency only in non-riscv64 envnvironment, it is still built here.

When [those lines](https://github.com/xxuejie/cargo-target-dep-test/blob/61b721e0047300089bdf6207d59bd2750db3bbae/Cargo.toml#L12-L13) are commented out, the crate could be built just fine.

**Possible Solution(s)**

Target specific dependency should be handled propoerly.

**Notes**

Output of `cargo version`:
cargo 1.48.0 (65cbdd2dc 2020-10-14)

**Comment by ehuss** [comment] 2020-12-04 02:02
Features for dependencies are unified, even if they are for targets that are not currently enabled.  This means that the features of the `molecule` package that `ckb-x64-simulator` enables causes it to add optional dependencies that are not compatible with no_std.

You can work around this with [`-Zfeatures=itarget`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#features).  The tracking issue for that is #7914.

**Comment by xxuejie** [comment] 2020-12-04 06:41
That seems to be the reason for this problem, many thanks.

**Comment by ehuss** [comment] 2021-01-07 02:08
Closing as a duplicate of #7914, and note it has now been stabilized.

**Closed by ehuss** 2021-01-07 02:08 UTC
Labels: C-bug
