### ISSUE TITLE
Unused patch warnings when using `-Zbuild-std` with `-Zbuild-std-features=compiler-builtins-mem`

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/cargo#8963] opened 2020-12-10 16:18 UTC
**Problem**

There are multiple `Patch [...] was not used in the crate graph` warnings when building a project using `-Zbuild-std` and `-Zbuild-std-features=compiler-builtins-mem` on nightly:

<details><summary>Warning output</summary>

> warning: Patch `gimli v0.23.0 (/home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/gimli)` was not used in the crate graph.
> Patch `object v0.22.0 (/home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/object)` was not used in the crate graph.
> Patch `adler v0.2.3 (/home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/adler)` was not used in the crate graph.
> Patch `addr2line v0.14.0 (/home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/addr2line)` was not used in the crate graph.
> Patch `miniz_oxide v0.4.0 (/home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/miniz_oxide)` was not used in the crate graph.
> Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.

</details>

**Steps**

1. `cargo new --lib example && cd example`
2. `echo "#![no_std]" > src/lib.rs`
3. `cargo +nightly check --target x86_64-unknown-linux-gnu -Z build-std=core -Zbuild-std-features=compiler-builtins-mem`

(The actual target doesn't seem to matter, the `build-std` feature just requires that we pass a `--target` argument.)

**Notes**

These warnings appeared between https://github.com/rust-lang/cargo/compare/d5556aeb8...2af662e22. My guess is that https://github.com/rust-lang/cargo/pull/8834 introduced them. They still happen on the latest nightly.

Output of `cargo version`:

> cargo 1.50.0-nightly (d274fcf86 2020-12-07)
release: 1.50.0
commit-hash: d274fcf862b89264fa2c6b917b15230705257317
commit-date: 2020-12-07

**Comment by alexcrichton** [comment] 2020-12-10 18:54
Ah yes this is indeed caused by #8834. There's some discussion on https://github.com/rust-lang/cargo/issues/8962 about the impact of that PR and how we may back it out.

**Comment by clubby789** [comment] 2020-12-15 19:26
Are there currently any workarounds for this?

**Comment by alexcrichton** [comment] 2020-12-15 19:29
Oh this was actually fixed in https://github.com/rust-lang/cargo/pull/8968, and now it's just updating the Cargo submodule in rust-lang/rust. In the meantime there are no workarounds.

**Closed by alexcrichton** 2020-12-15 19:29 UTC
Labels: C-bug
