### ISSUE TITLE
Provide a way to run build.rs and then cancel the build because it decides nothing has changed

### ISSUE THREAD

**Issue by golddranks** [rust-lang/cargo#5663] opened 2018-06-28 12:05 UTC
There is the `rerun-if-changed` and `rerun-if-env-changed` which are very useful to avoid needless reruns. However, I'd like to rerun when there has been a new commit, because I'm using `build.rs` to embed the commit hash and title into the binary. `build.rs` can't find this out using just filesystem and environment variable monitoring. Currently I pass `cargo:rerun-if-changed=.git`, but it's prone to false positives, because any git operation will trigger rerun.

It would be useful if `build.rs` could be built and run, but it could then decide by itself whether anything has changed or not. Then I could check the latest git commit inside `build.rs` and act according to that. There is surely other cases too where "env var changed" and "file modified" don't cut it as the only rerun triggers; one might want to check if the contents of a file changed, or do some further processing, like parse a file and check if a specific field changed.

**Comment by golddranks** [comment] 2018-07-01 04:38
Btw. a quick question: would a feature like this need an RFC, or would it be sufficient to just implement it? I'm a bit out of the loop how the decision process works W.R.T Cargo features.

**Comment by fenhl** [comment] 2019-09-08 00:25
So the idea would be to use something like `cargo:rerun-if-script-changed=git rev-parse --verify HEAD`, right? That would be very useful.

**Comment by dtolnay** [comment] 2021-03-13 06:28
I think this is a near duplicate of #3404.

**Comment by ehuss** [comment] 2021-03-15 20:01
Yea, seems like the same, closing as a duplicate of #3404.

**Closed by ehuss** 2021-03-15 20:01 UTC
Labels: A-build-scripts, C-feature-request
