### ISSUE TITLE
Fish doesnt work

### ISSUE THREAD

**Issue by iMonZ** [rust-lang/cargo#11163] opened 2022-09-30 07:57 UTC
### Problem

If the famous fish shell is used, it's hard to install

### Steps

1. Use Fish
2. install rust and cargo over the cli command from the website

### Notes

Message after cargo and rust is installed
> Rust is installed now. Great!
> 
> To get started you may need to restart your current shell.
> This would reload your PATH environment variable to include
> Cargo's bin directory ($HOME/.cargo/bin).
> 
> To configure your current shell, run:
> source "$HOME/.cargo/env"

Then I execute this command:

>  ~  source "$HOME/.cargo/env"

And I get this error message:

> ~/.cargo/env (line 4): 'case' builtin not inside of switch block
> case ":${PATH}:" in
> ^
> from sourcing file ~/.cargo/env
> source: Error while reading file '/Users/mvg/.cargo/env'

So please fix the detection of the fish shell.

**Comment by ehuss** [comment] 2022-09-30 13:28
Unfortunately fish shell isn't fully supported by rustup at this time. This seems to be more or less a duplicate of https://github.com/rust-lang/rustup/issues/478, so closing in favor of that.

**Closed by ehuss** 2022-09-30 13:28 UTC
Labels: C-bug
