### ISSUE TITLE
Allow `cargo fetch` to work without `src` existing

### ISSUE THREAD

**Issue by jbg** [rust-lang/cargo#9443] opened 2021-05-01 05:04 UTC
**Describe the problem you are trying to solve**
I'm using a [multi-stage container build](https://gist.github.com/jbg/dc7d271f7da261e424393c73b73024a1) to prevent network access after the `cargo fetch` stage, to reduce risks associated with build scripts and help to catch cases where crates download untrusted binaries from the Internet.

To use image layer caching to its fullest, `cargo fetch` would ideally only be run when `Cargo.toml` or `Cargo.lock` has changed (which is relatively infrequent), rather than when any source code has changed (which is frequent).

The easiest way to achieve this is something like:

```
COPY Cargo.toml Cargo.lock ./
RUN cargo fetch --locked
```

However, this fails because `cargo` expects `src/main.rs` or `src/lib.rs` to exist, so we have to `touch` one of those files before `cargo fetch` will work.

Copying the actual `src/main.rs` or `src/lib.rs` would cause it to become part of the hash for the image layer, so `cargo fetch` would be run again if those files changed. Using `touch` avoids that.

**Describe the solution you'd like**

`cargo fetch` should ideally not require `src/main.rs` or `src/lib.rs` to exist, since it doesn't need them in order to perform the requested task (fetch).

**Comment by Eh2406** [comment] 2021-05-01 15:08
cc https://github.com/rust-lang/cargo/issues/2644

**Comment by ehuss** [comment] 2021-06-02 22:36
I'm going to close as a duplicate of #2644.  The thrust of that issue is finding a way implement better caching with Docker, and one of the approaches is doing essentially what you suggest here (copy Cargo.lock and Cargo.toml, and generate a synthetic src/lib.rs). That doesn't work in the general case, but I suspect whatever solution will be the same for this issue.

**Closed by ehuss** 2021-06-02 22:36 UTC
Labels: C-feature-request
