### ISSUE TITLE
'cargo doc --open' from file causing CORS issues

### ISSUE THREAD

**Issue by frehberg** [rust-lang/cargo#11834] opened 2023-03-12 13:29 UTC
### Problem

'cargo doc --open'  will use the default browser reading html document as file instead of using http

As the rustdocs are structured in hierarchical directory structure, each document is reading the following definition to load further static files
```
var rootPath = document
         .getElementById('rustdoc-vars')
         .attributes['data-root-path']
         .value;
```
Just, reading from local file system the  "import(..)" from dynamic location rootPath+"static.files/...js" is causing a CORS alarm in browser, for example Chrome:

![image](https://user-images.githubusercontent.com/4435830/224546947-4c8d9add-a37c-4b4c-a511-bacac8add01d.png)

To prevent this warning, the configuraiton must permit "local file access" by browser, for example 
```
google-chrome --allow-file-access-from-files  /.../target/doc/aquamarine_demo_crate/index.html
```
The problem is that this flag is not standardized, firefox does not provide this flag on command line, but requires setting via UI.

Otherwise cargo should start a small local web-server  listening at 127.0.0.1:8000 to serve the rustdoc pages, and the web-browser should be started to read from this location. http://127.0.0.1:8000/aquamarine_demo_crate/index.html

Note: replace aquamarine_demo_crate with your project name

### Steps

1. configure google chrome as default browser and execture "cargo doc --open", or start manually:
```
google-chrome   ./target/doc/aquamarine_demo_crate/index.html 
```
2.now  open dev-console (Ctrl-Shift-C)in chrome and see the errors caused by import of local source files (see screenshot)

Now start google chrome with flag and you will see that the errors no longer appear.
```
google-chrome --allow-file-access-from-files  ./target/doc/aquamarine_demo_crate/index.html 
```

### Possible Solution(s)

Either figure out kind of browser is used and set the appropriate flags to "allow local file access"
Or open a local web-browser to serve the rustdoc pages when being called as
```
cargo doc --open
```

### Version

```text
cargo 1.69.0-nightly (82c3bb79e 2023-02-04)
release: 1.69.0-nightly
commit-hash: 82c3bb79e3a19a5164e33819ef81bfc2c984bc56
commit-date: 2023-02-04
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]

Google Chrome Version 111.0.5563.64 (Official Build) (64-bit)
```

**Comment by ehuss** [comment] 2023-03-12 14:04
Thanks for the report!  This is essentially a duplicate of #4966, so closing in favor of that.

**Closed by ehuss** 2023-03-12 14:04 UTC
Labels: C-bug
