### ISSUE TITLE
Replace target dependencies by a free-form target_filter field

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/cargo#1364] opened 2015-02-28 16:11 UTC
There are currently two problems with with the handling of target specific dependencies:

- They don't work with dev-dependencies (`[target.x86_64-unknown-linux-gnu.dev-dependencies.hammer]`)
- They are very verbose (https://github.com/carllerche/curl-rust/blob/5d0f5c8848e3cf1e12480a1923ae888e24d58f63/curl-sys/Cargo.toml#L18-L30)

Instead replace it by a free-form target_filter field in dependency sections:

```
[dev-dependencies.hammer]
target_filter = "os = 'linux' && arch = 'x86_64'"
git = "https://github.com/wycats/hammer.rs"
```

Cargo will parse it and evaluate it the same way rustc evaluates `#[cfg(all(target_os = "linux", target_arch = "x86_64"))]` except that the syntax is much nicer.

If the evaluation returns true, the dependency is included, otherwise it will not be touched.

The following expressions should be available:

```
arch = <string>
arch != <string>
os = <string>
os != <string>
unix
windows
!<expr>
(<expr>)
<expr> && <expr>
<expr> || <expr>
```

Similarly multiple [features] sections should be allowed where each has its own target_filter.

**Comment by alexcrichton** [comment] 2015-02-28 18:23
I believe that if we take this route we are likely to use the `cfg` syntax of the compiler itself exactly, in which case I'm going to close this as a dupe of https://github.com/rust-lang/cargo/issues/1007.

**Closed by alexcrichton** 2015-02-28 18:23 UTC
