### ISSUE TITLE
Add ability to add a description to the `feature`s.

### ISSUE THREAD

**Issue by Jerrody** [rust-lang/cargo#11290] opened 2022-10-26 14:24 UTC
### Problem

It's very often to understand what the feature of the `N` crate does and as a rule maintaners neglect to add the description to the feature in documentation. And the user of this crate cannot understand what feature does, for an example:
`nalgebra` crate has a `cuda` feature. What does it mean? Do all math computations perform on the GPU?
In reality, when I asked the maintainer in Discord server what it does he said that this is for interop with CUDA.

### Proposed Solution

Add additional field to the feature, like:
```my_feature = { features = ["dep:serde", "another_feature"], description = "This is does cool magic" }```

And add an option to the maintainer if he doesn't want to add any description to the feature:
```my_feature = { features = ["dep:serde", "another_feature"], description = false }```

And after this `rustdoc` parses it or `Cargo` provides additional data to it and as the result we can see at this page description of each feature (just imagine how it can looks like):
![image](https://user-images.githubusercontent.com/68968657/198052256-8c680875-4973-49bd-8f46-f40041980837.png)

**Comment by weihanglo** [comment] 2022-10-26 14:47
Thanks for your proposal. 

This seems to be a duplicate of <https://github.com/rust-lang/cargo/issues/4956>, and there is a kinda tracking issue <https://github.com/rust-lang/cargo/issues/10882> for some extensions of feature field. Closing in favour of those. Thank you.

**Closed by weihanglo** 2022-10-26 14:47 UTC
Labels: C-feature-request
