### ISSUE TITLE
Difficulties enabling features of workspace members

### ISSUE THREAD

**Issue by ctsrc** [rust-lang/cargo#7039] opened 2019-06-18 02:45 UTC
**Problem**
The following problem is demonstrated in https://github.com/ctsrc/cargo_features_problem_repro/tree/025224ea773461b17c7a90856676dab209c36cd3

I have a `Cargo.toml` virtual manifest which specifies a couple of workspace members like so:

```
[workspace]
members = [
  "badabing",
  "foobar",
  "quux",
]
```

In one of these packages (`foobar`) I make use of feature flags. Let's call this feature `bazinga`.

When I compile everything in the workspace from the directory with the virtual manifest, the feature is not activated when I ask for it to be, unless I do it by specifying all features.

So the following works:

```
cargo clean ; cargo run --all-features -vv
```

But none of the following enable the feature:

```
cargo clean ; cargo run --features foobar/bazinga -vv
```

```
cargo clean ; cargo run --features bazinga -vv
```

```
cargo clean ; cargo run --package foobar --features bazinga -vv
```

```
cargo clean ; cargo run --package foobar --features foobar/bazinga -vv
```

```
cargo clean ; cargo run --package foobar --bin foobar --features bazinga -vv
```

```
cargo clean ; cargo run --package foobar --bin foobar --features foobar/bazinga -vv
```

All of them just compile and run it as if no feature flag was requested at all.

Whereas enabling the feature when standing in the directory of the workspace member package works:

```
cargo clean ; ( cd foobar && cargo run --features bazinga -vv )
```

Setting the RUSTFLAGS environment variable works too:

```
cargo clean ; RUSTFLAGS='--cfg feature="bazinga"' cargo run -vv
```

**Steps**

1. When the feature flag `bazinga` is enabled in this minimal reproduction of the problem, the program `foobar` will print "Bazinga!". https://github.com/ctsrc/cargo_features_problem_repro/blob/025224ea773461b17c7a90856676dab209c36cd3/foobar/src/main.rs#L3-L4
2. `git clone git@github.com:ctsrc/cargo_features_problem_repro.git`
3. `cd cargo_features_problem_repro`
4. `git checkout 025224e`
5. `cargo run --features foobar/bazinga -vv`
6. There is no print of "Bazinga!"
7. `cargo clean ; cargo run --all-features -vv`
8. With all features enabled, cargo enables the `bazinga` feature and "Bazinga!" is printed.

**Notes**

Additional context:

It is desirable to be able to enable specific features of specific workspace members.

If `cargo clean ; cargo run --features foobar/bazinga` would work that would be ideal.

Output of `cargo version`:

cargo 1.37.0-nightly (545f35425 2019-05-23)

**Comment by ehuss** [comment] 2019-06-18 03:33
There are several known problems with features in workspaces (see #4463).  You can try the unstable flag `-Z package-features` to see if that might provide better behavior (see #5364).

**Comment by ctsrc** [comment] 2019-06-18 20:06
Thank you @ehuss. In my particular case the unstable flag you suggested solves the problem I had because the feature flags I have created are ones that I use during development only, and I am using the nightly release of Rust and cargo in my development environment.

**Comment by ehuss** [comment] 2019-06-18 21:43
Ok, I'm going to close this as duplicate of the above linked issues. You can follow those for any updates in the future.

**Closed by ehuss** 2019-06-18 21:43 UTC
Labels: C-bug

**Comment by TotalKrill** [comment] 2020-12-10 14:25
Wanted to add an example how to use the unstable flag `-Z package-features`, which seems to solve the problem, and anyone finding their way to this issue doesnt have to go down the rabbit hole.

`cargo build -Z package-features --package foo --features bazinga`

Which will build only foo with the feature bazinga, and not the other packages as it would seem

**Comment by nnmm** [comment] 2021-11-05 13:06
For anyone stumbling onto this issue, this is now possible with `--features mypackage/myfeature`. If you have several features to enable, you also need to pass `--features` each time.

**Comment by kostik-b** [comment] 2024-06-26 16:40
Hey, just wanted to share my experience with this feature. I have a workspace containing, let's say, pkg1 and pkg2. pkg1 includes pkg2 in its Cargo.toml. pkg2 has a library dependency that is marked optional. When I build those packages separately, I can pass in `--features mypackage/myfeature` for pkg2 and all is working as intended.

However, when I build all packages in a workspace together (i.e. without specifying `-p` flag), and I pass the same option to the `cargo build` command, then pkg1 and pkg2 are BOTH built with the same dependency.

Furthermore, if I pass the features option when I build pkg1 only, it will also build with the same dependency.

I believe that since the feature option has the format of `mypackage/myfeature` it should only work for that package and not for any other package, even though one might include the other.
