### ISSUE TITLE
Unable to upgrade binaries installed via cargo

### ISSUE THREAD

**Issue by tarrant** [rust-lang/cargo#2392] opened 2016-02-18 07:00 UTC
I noticed there was a new version of `rustfmt` out and decided to upgrade. When I ran `cargo install` to update it I got an error about `rustfmt` already being installed. So I start looking through the `--help` output and can't find a `--upgrade` flag of any sort.

I was able to fix my issue by running `cargo install cargo` to get to cargo 0.8 and then `~/.cargo/bin/cargo uninstall rustfmt && cargo install rustfmt` but it should be easier than this. If no one objects I'd like to add an `--upgrade` flag to cargo. Does adding new flags require an RFC?

**Output**
```
[I] Aldgate ~$ cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt v0.3.0
binary `cargo-fmt` already exists in destination as part of `rustfmt v0.2.1`
```

**Cargo Version**
```
[I] Aldgate ~$ which cargo && cargo version
/usr/local/bin/cargo
cargo 0.7.0 (1af03be 2015-12-08)
```

**Comment by steveklabnik** [comment] 2016-02-18 15:16
Yes, you have to `uninstall` and then `install`.

I think there's another bug for this open...

**Comment by alexcrichton** [comment] 2016-02-18 17:50
We do indeed have an issue for this! I'm gonna close this as a dupe of https://github.com/rust-lang/cargo/issues/2082, but as @steveklabnik you'll just need to uninstall and then reinstall for now

**Closed by alexcrichton** 2016-02-18 17:50 UTC
