### ISSUE TITLE
[cargo doc] build.rs does not cover the use cases very well

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#3053] opened 2016-08-28 20:20 UTC
With docs.rs out, we’ve noticed a problem with cargo running `build.rs` scripts when documenting each crate, while it shouldn’t be necessary in majority of the cases.

Namely, most of the crates use build.rs scripts for one of these three large categories:
- Native library discovery (pkgconfig/etc);
- Building of dependencies written in other languages (gcc-rs/etc);
- Generating rust code (syntex/lalrpop/etc).

First and second use case will not influence the resulting documentation in meaningful ways, while the third use-case almost always will. First and second use-cases are target-dependent and may require cross-compilation toolchains, whereas the third use-case as well as documentation generation are obviously target-agnostic and can be done without any extra tooling or knowledge about the target platform.

It is counter-productive to not make any distinction between these cases. A project like docs.rs ideally shouldn’t need to install any native dependencies (see https://github.com/onur/docs.rs/issues/23) in order to generate documentation (because they are irrelevant for documentation generation purposes!)

There’s multiple ways one could proceed here:
- Introduce `generate.rs`, do not run `build.rs` scripts on `cargo doc`;
- Introduce extra keys to `Cargo.toml` (e.g. `run_build_script_for_docs = false`) defaulting to not running build.rs before generating documentation and making people using third use case specify that variable to true;
- The least breaking change would be to add a way in cargo API to not run build.rs scripts when building docs, so docs.rs could implement some sort of scheme itself (e.g. via `[metadata]` Cargo.toml section instructing docs.rs to run `build.rs`);
- etc.

cc @onur

**Comment by cuviper** [comment] 2016-08-28 20:32
Build scripts can also output `rustc-cfg` features, which may affect the documentation.

**Comment by nagisa** [comment] 2016-08-28 20:51
@cuviper I do not disagree, but as I already said, the influence is not meaningful. Those cfgs reflect the build environment of whatever is building your documentation and not the environment your user (the person reading documentation) has. This leads to essentially the same problem as showing linux documentation for a user using windows (resulting in empty `os` modules etc).

In order to specify cfgs for docs.rs, I think one would end up using similar scheme as the one you’d use to specify features (https://github.com/onur/docs.rs/issues/29).

**Comment by alexcrichton** [comment] 2016-08-29 16:28
Yeah it's true that build scripts are basically just large black boxes today, so I think it's correct for now to default to trying to run them to generate docs. I'd be up for exploring the space of more targeted build scripts for situations like this, but that's certainly RFC territory to be implemented.

**Comment by nagisa** [comment] 2016-08-29 17:38
@alexcrichton what about 

> The least breaking change would be to add a way in cargo API to not run build.rs scripts when building docs, so docs.rs could implement some sort of scheme itself (e.g. via [metadata] Cargo.toml section instructing docs.rs to run build.rs);

**Comment by alexcrichton** [comment] 2016-08-29 20:04
We could perhaps add a flag to `cargo doc` that doesn't run build scripts like that, yeah, but I don't think we could switch the default behavior to not running build scripts when building documentation.

**Comment by durka** [comment] 2016-09-09 19:53
Can't the build script check `$PROFILE` and skip things that aren't relevant to docs?

**Comment by BusyJay** [comment] 2017-07-04 11:00
Any progress on this issue?

**Comment by carols10cents** [comment] 2017-09-26 18:39
This sounds like it might fall under [eRFC 2136, Cargo build system integration](https://github.com/rust-lang/rfcs/pull/2136).

**Comment by epage** [comment] 2023-09-30 00:26
As far as I can tell, #8811 is a dupe of this but since it has more recent notes on direction, I'm closing this in favor of it.

**Closed by epage** 2023-09-30 00:26 UTC
Labels: Command-doc, C-feature-request, A-build-scripts, S-triage
