### ISSUE TITLE
Support for installing data files?

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#3851] opened 2017-03-21 00:37 UTC
It would be great to get support for `cargo install`ing purely data/resource files. This has come up as a need in [this issue of rust-locale](https://github.com/rust-locale/rust-locale/issues/19). Any chance of getting this?

**Comment by alexcrichton** [comment] 2017-03-21 14:07
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/2729, so I'm going to close in favor of that.

**Closed by alexcrichton** 2017-03-21 14:07 UTC
