### ISSUE TITLE
Cargo nightly no longer working

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/cargo#4189] opened 2017-06-19 04:12 UTC
This was with the most recent rustup'ing of nightly:

![image](https://user-images.githubusercontent.com/547158/27269239-59214c2e-5509-11e7-9f95-12f80de5a747.png)

It seems like cargo just hangs there, showing no status.  It does "finish" but I don't see the build artefact I'd expect.  "cargo run" also doesn't work correctly, returning to the cmd line with no message instead of running the application.

**Comment by jonathandturner** [comment] 2017-06-19 04:18
I tried uninstalling and reinstalling rustup to see if there was something that got goofed there, but seeing the same issue.

**Comment by K-Finlay** [comment] 2017-06-19 05:17
I'm getting the same thing here.
"cargo new" is also broken. It just hangs for a bit then returns to the cmd, failing to create a new project.

**Comment by pravic** [comment] 2017-06-19 10:08
I am not sure about the new issue, may be all these problems caused by single bug.

Cargo messages are broken too on nightly (messed newlines):

```
  Compiling utf8-ranges v1.0.0
  num-traits v0.1.39
   Compiling libc v0.2   Compiling regex-syntax v0.4.1
   Compiling gcc v0.3


   Compiling thread-id v3.1.0
```

**Comment by alexcrichton** [comment] 2017-06-19 14:31
It looks like Cargo's doing things it's just not printing to the console, probably related to https://github.com/rust-lang/cargo/pull/4162. When run directly (not through rustup) I see messages getting printed out.

@K-Finlay I can't confirm that `cargo new` fails to create a new project. Can you confirm versions of what you're using and also confirm that it fails to create a new project.

@pravic I cannot reproduce the interleaving you're seeing, can you provide details on the versions used and how to reproduce?

**Comment by pravic** [comment] 2017-06-19 15:03
cargo 0.21.0-nightly (e53e2f8d5 2017-06-17)

Windows 7 x64 SP1, ConEmu 170118 (without ConEmu almost the same behavior).

```
t:\tamp>cd weird_nightly\

t:\tamp\weird_nightly>tail -n +6 Cargo.toml
[dependencies]
getopts = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"
rust-crypto = "*"
flate2 = "*"
byteorder = "*"
widestring = "*"
chrono = "*"
```

Nightly:
```
t:\tamp\weird_nightly>cargo +nightly build
  Compiling byteorder v1.0.   Compiling log v0.3.8
   Compiling num-traits v039
   Compiling utf8-ranges v1.0.0
   getopts v014
   Compiling libc v0.2.24
   Compiling winapi v v0.6.3
.2.36
```

Stable:
```
t:\tamp\weird_nightly>cargo +stable build
   Compiling winapi v0.2.8
   Compiling gcc v0.3.51
   Compiling num-traits v0.1.39
   Compiling getopts v0.2.14
   Compiling log v0.3.8
   Compiling utf8-ranges v1.0.0
   Compiling void v1.0.2
   Compiling widestring v0.2.2
   Compiling unreachable v0.1.1
   Compiling rustc-serialize v0.3.24
   Compiling regex-syntax v0.4.1
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.24
   Compiling kernel32-sys v0.2.2
   Compiling num-integer v0.1.34
   Compiling rand v0.3.15
   Compiling memchr v1.0.1
   Compiling byteorder v1.0.0
   Compiling num-iter v0.1.33
   Compiling aho-corasick v0.6.3
   Compiling num v0.1.39
   Compiling miniz-sys v0.1.9
   Compiling rust-crypto v0.2.36
   Compiling flate2 v0.2.19
   Compiling thread-id v3.1.0
   Compiling time v0.1.37
   Compiling thread_local v0.3.3
   Compiling regex v0.2.2
   Compiling chrono v0.3.1
   Compiling env_logger v0.4.3
   Compiling weird_nightly v0.1.0 (file:///T:/tamp/weird_nightly)
    Finished dev [unoptimized + debuginfo] target(s) in 34.78 secs
```

Direct (no output at all):
```
t:\tamp\weird_nightly>%RUSTUP_HOME%\toolchains\nightly-i686-pc-windows-msvc\bin\cargo.exe build -v

t:\tamp\weird_nightly>
```

**Comment by alexcrichton** [comment] 2017-06-19 15:33
@pravic for the direct invocation was that with with a removed `target` directory? If not, is cargo compiling things in the background?

**Comment by alexcrichton** [comment] 2017-06-19 15:46
I believe this is fixed by https://github.com/BurntSushi/ripgrep/pull/523 after looking into it a bit, or at least it fixes a number of issues for me locally. I think rustup was a red herring.

**Comment by pravic** [comment] 2017-06-19 16:34
> for the direct invocation was that with with a removed  target  directory? 

Yes, it was after `cargo clean`.

**Comment by LLBlumire** [comment] 2017-06-19 21:49
```
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo clean
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo build
   Compiling hellotest v0.1.0 (file:///C:/Users/Lucille/Documents/Code/Rust/hellotest)
    Finished dev [unoptimized + debuginfo] target(s) in 0.24 secs
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\hellotest.exe`
Hello, world!
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> rustup default nightly
info: using existing install for 'nightly-x86_64-pc-windows-msvc'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'

  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.19.0-nightly (10d7cb44c 2017-06-18)

PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo clean
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo build
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo run
PS C:\Users\Lucille\Documents\Code\Rust\hellotest> cargo -V
cargo 0.21.0-nightly (50b1c24d1 2017-06-17)
```

I'm getting what appears to be similar issues with nightly right now.

**Comment by K-Finlay** [comment] 2017-06-20 01:53
@alexcrichton "cargo new" failing seems to be an error on my end.
I was trying to create a project named "test" which I forgot is not allowed by cargo, and due to there being no output, I assumed it was broken.

**Comment by EPashkin** [comment] 2017-06-20 03:44
On windows it same with nightly. Piping errors to file helps: `cargo build 2>_`

**Closed** 2017-06-20 05:02 UTC
