### ISSUE TITLE
The usage of weak dependencies pollutes `Cargo.lock`

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/cargo#11426] opened 2022-11-26 02:54 UTC
Feel free to close if duplicated or if it is a "feature" of Cargo.

### Problem

A feature declared with optional weak dependencies will unnecessarily pollute `Cargo.lock` with all the declared non-activated items as well as their **transients**, which is crazy.

Take for example the [rust_decimal](https://github.com/paupino/rust-decimal) crate. If declared as `rust_decimal = { default-features = false, version = "1.0" }`, then `Cargo.lock` will contain 5 dependencies but if declared as `rust_decimal = { default-features = false, features = ["std"], version = "1.0" }`, then `Cargo.lock` will contain **+40 dependencies**.

```toml
# Cargo.toml (https://github.com/paupino/rust-decimal/blob/master/Cargo.toml#L80)

# ...

std = ["arrayvec/std", "borsh?/std", "bytecheck?/std", "byteorder?/std", "bytes?/std", "rand?/std", "rkyv?/std", "serde?/std", "serde_json?/std"]

# ...
```

```
$ cargo tree

rust_decimal v1.27.0
    ├── arrayvec v0.7.2
    └── num-traits v0.2.15
        [build-dependencies]
        └── autocfg v1.1.0
```

### Version

```text
1.65.0
```

**Comment by weihanglo** [comment] 2022-11-26 10:19
Is this kinda a duplicate of #10801?

**Comment by c410-f3r** [comment] 2022-11-26 11:07
It is, indeed.

**Comment by epage** [comment] 2022-11-26 14:17
@weihanglo I thought #10801 is about lock files including optional features of direct dependencies.  Does it also include indirect dependencies?

Note that in this issue, the lock file for
- `rust_decimal = { default-features = false, version = "1.0" }` contains 5 items
- `rust_decimal = { default-features = false, features = ["std"], version = "1.0" }` contains 40+ items

The number of lock file entries when `std` isn't specified I think confirms that #10801 is only about direct dependencies and shows this issue is independent of #10801.

The key part here is weak dependencies.  It seems we are resolving the lock file as if none of those weak dependencies were weak.

Re-opening for now so this doesn't get lost track of.  If there was something I missed, we can always re-close.

**Comment by weihanglo** [comment] 2022-11-26 14:39
#10801 is 

* `bar` depends on `foo` with feature `serialization` enabled.
* Feature `serialization` contains a weak dep feature `time?/serde-well-known`.
* Optional dep `time` ended up in the lockfile.

#11426 is

* `some_pkg` depends on `rust_decimal` with feature `std` enabled. 
* Feature `std` contains weak dep features `borsh?/std`, `bytecheck?/std`…
* Those optional deps ended up in the lockfile.

I didn't see the difference between them 🤔.

**Comment by epage** [comment] 2022-11-26 21:56
Somehow I had missed the weak dependency aspect of the other one.  I've re-titled it to call that out.  Of course, if there is another angle to **that** that I missed, let me know and we can fix it :)

**Closed by epage** 2022-11-26 21:56 UTC
Labels: C-bug, A-features, A-lockfile
