### ISSUE TITLE
`cargo build` updates Cargo.lock?

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#3265] opened 2016-11-07 15:23 UTC
Originally reported in this tweet: https://twitter.com/duelinmarkers/status/795313099477762049

if you:

```
$ git clone https://github.com/sunng87/cargo-release.git
$  cd cargo-release/
$  cargo build
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Cargo.lock
```

A diff: https://gist.github.com/duelinmarkers/fcb8b0da4e905c9c5d6f0590f1219399

Given that `Cargo.lock` exists and we didn't `cargo update`, the lockfile shouldn't be modified. I can't tell why this is happening.

/cc @sunng87 since it's their library.

**Comment by alexcrichton** [comment] 2016-11-07 22:47
Yeah `cargo build` will update the lock file if the manifest has also changed as part of routine `cargo build`. If though the manifest was the exact same as before and there was a lock file then this is definitely a bug!

To clarify, are we sure there were no updates to the manifest since the lock file was created?

**Comment by steveklabnik** [comment] 2016-11-07 23:05
```
-rw-r--r-- 1 steve steve  8582 2016-11-07 10:19:51.015593067 -0500 Cargo.lock
-rw-r--r-- 1 steve steve   443 2016-11-07 10:19:43.643657517 -0500 Cargo.toml
```

so yeah, lockfile was created 8 minutes later?

**Comment by steveklabnik** [comment] 2016-11-07 23:06
On a fresh clone:

```
$ ls -a --full-time
-rw-r--r-- 1 steve steve  3299 2016-11-07 18:05:47.723095806 -0500 Cargo.lock
-rw-r--r-- 1 steve steve   443 2016-11-07 18:05:47.723095806 -0500 Cargo.toml
```

they have the exact same time. which everything does, since it's a fresh clone

**Comment by sunng87** [comment] 2016-11-08 03:35
I can reproduce this issue too. Cargo updates my dependencies to latest version even when I hard-coded a version number in Cargo.toml. I was using a crate.io mirror provided by `ustc.edu.cn` as you can see from `Cargo.lock`. Not sure if it has something to do with this issue. `Cargo.lock` got modified on `cargo build` on both mirror and original repository.

**Comment by alexcrichton** [comment] 2016-11-08 15:01
@sunng87 to clarify, was `Cargo.lock` modified after generation if `Cargo.toml` was not changed? Or did you find that when changing `Cargo.toml` it then later changed the lock file? (the latter is expected where the former would be a bug)

Also, do you have the exact diff in the manifest that's happening?

**Comment by sunng87** [comment] 2016-11-09 06:22
@alexcrichton I did a clean git clone and then `cargo build` without changing anything in `Cargo.toml`, the `Cargo.lock` changed.

All crates seems to be updated to latest version and mirror url is changed to default central repository:

https://gist.github.com/sunng87/8b5dfca7d46625c4b459a8f460d791b2

**Comment by alexcrichton** [comment] 2016-11-11 19:49
@sunng87 do you have a repo I can poke around in? A fresh git clone doesn't necessarily imply Cargo shouldn't modify Cargo.lock because it could be in a checked-in state that Cargo.toml and Cargo.lock are out of sync

**Comment by steveklabnik** [comment] 2016-11-11 20:15
@alexcrichton does the repo in the OP not reproduce for you?

**Comment by alexcrichton** [comment] 2016-11-11 21:54
Ah! Sorry I must have missed that...

@sunng87 it looks like you have a number of non-crates.io URLs in your Cargo.lock:

```toml
dependencies = [                                                       
 "clap 2.2.5 (registry+git://crates.mirrors.ustc.edu.cn/index)",       
 "quick-error 0.1.4 (registry+git://crates.mirrors.ustc.edu.cn/index)",
 "regex 0.1.65 (registry+git://crates.mirrors.ustc.edu.cn/index)",     
 "semver 0.2.3 (registry+git://crates.mirrors.ustc.edu.cn/index)",     
 "toml 0.1.28 (registry+git://crates.mirrors.ustc.edu.cn/index)",      
]                                                                      
```

When you do a normal `cargo build` that's not configured to use that mirror, then the entire lock file is no longer applicable, so it's as-if it was all thrown out.

This may have happened if you're using `registry.index` inside of `.cargo/config`, but instead of that it's recommended to use [source replacement](http://doc.crates.io/source-replacement.html) nowadays (which solves this problem)

**Comment by sunng87** [comment] 2016-11-12 03:21
@alexcrichton This makes sense.The Cargo.lock is created in early days when source replacement haven't been introduced in. 

I think we can close the issue now.

**Comment by alexcrichton** [comment] 2016-11-12 05:33
Ok!

**Closed by alexcrichton** 2016-11-12 05:33 UTC

**Comment by steveklabnik** [comment] 2016-11-12 17:19
Ah! So simple!
