### ISSUE TITLE
Optionally show dependencies on `std` in `cargo tree`

### ISSUE THREAD

**Issue by kpreid** [rust-lang/cargo#9784] opened 2021-08-13 02:45 UTC
**Describe the problem you are trying to solve**

Evaluate the feasibility of making a library crate `no_std` compatible, which requires not just adding `#![no_std]` but also ensuring that all of its dependencies do.

**Describe the solution you'd like**

Add an option to `cargo tree` which includes `std` (and perhaps while we're here anyway, `alloc`) in the displayed tree.

**Notes**

It occurs to me that this is nontrivial compared to the current functionality of `cargo tree`, because these dependencies are not in the Cargo dependency graph and so would have to be be detected by, at a minimum, parsing the crate's `lib.rs` and evaluating its `cfg` expressions (if not actually compiling/checking the crate). However, this feature would still be an improvement over the strategy “compile for a target without `std` support and see what breaks” since it would list _all_ dependencies, not just which ones stop the build.

Doing a full check would also allow detecting dependencies on the `alloc` crate, also of interest to users of limited targets, whereas looking only for `#![no_std]` could not.

**Comment by ehuss** [comment] 2021-09-11 19:12
I don't think it will be possible for `cargo tree` to do this. As you mentioned, it would need to parse the source to find the corresponding attribute, and it could depend on cfg expressions and other complications.  For now, [`cargo nono`](https://github.com/hobofan/cargo-nono) is probably your best bet.  

There is a closely related issue #5090, so I'm going to close as a duplicate of that.  I think it is well understood that it can be frustrating trying to wrangle no_std compatibility.  There are other approaches such as a unified `std` that may approach this from a different angle.

**Closed by ehuss** 2021-09-11 19:12 UTC
Labels: C-feature-request
