### ISSUE TITLE
Cargo needs a way to run an executable out of a build-dependency

### ISSUE THREAD

**Issue by erickt** [rust-lang/cargo#872] opened 2014-11-14 06:34 UTC
As best as I can tell, cargo only builds the libraries from a dependency. This has the unfortunate side effect of preventing build scripts from being able to execute a binary. This is unfortunately preventing @dwrensha's [capnproto-rust](https://github.com/dwrensha/capnproto-rust) from being used by a cargo build script to generate files.

The reason why is due to the design of the Cap'n Proto project. According to [doc](http://kentonv.github.io/capnproto/otherlang.html), the way Cap'n Proto does code generation for languages is that there is a driver executable, `capnp` that parses the `.capnp` file and generates a schema, which is then passed off to a plugin executable to generate the language specific files. There are 3 options to do this right now:

* build `capnproto-rust` outside of the project, generate the code and check it into the project.
* have `build.rs` clone `capnproto-rust`, run `cargo build` in there and execute the binary to generate the code.
* modify the upstream project to turn `capnp` into a library, and use that in a `build.rs` script. I'm not familiar with that codebase, but it does seem pretty [big](https://github.com/kentonv/capnproto/tree/master/c++/src/capnp), so this would probably be a lot of work.

Instead, I think things would be a lot more simple if a cargo dependency could be built to include the executables. Then it would be pretty trivial to do this code generation.

**Comment by alexcrichton** [comment] 2015-01-14 04:28
I'm going to close this as working as intended, and I'm also not sure that this has come up recently as a desire for various build scripts.

**Closed by alexcrichton** 2015-01-14 04:28 UTC

**Comment by comex** [comment] 2015-02-26 04:33
I'm trying to do the same thing.  I don't see why there is no story for depending on or installing executables other than manually checking out and building... unless I'm missing something?

**Comment by alexcrichton** [comment] 2015-02-26 08:27
Does your build dependency not offer its functionality through the interface of a library? (that is the recommended method)

**Comment by comex** [comment] 2015-02-26 18:54
The dependency is bindgen, so yes, but this seems like a waste of time to me... I already have a (hacky) Python script to do some extra processing on the output, so I can't just use the plugin version.  I could redo the processing in Rust in order to use the bindgen library (rather than popen), but what is the point of requiring me to do that when the executable is right there in the repo and just needs a way to be compiled?

**Comment by alexcrichton** [comment] 2015-02-27 00:49
> what is the point of requiring me to do that when the executable is right there in the repo and just needs a way to be compiled?

Calling a library has a few benefits:

1. It is *far* faster than calling a whole separate proces
2. Avoids conversions between languages through stdout/stderr/args/env vars. You can use native Rust types everywhere (and get compilation warnings, etc)
3. Cargo can manage everything from the upstream dependencies to what architecture it's built for.
4. Cargo can precisely tell you where bindgen is. Otherwise a `bindgen` executable elsewhere in PATH may cause bugs.
5. Cargo can allow a project to end up running two versions of bindgen if necessary (by saying which links to which)

**Comment by torarnv** [comment] 2015-07-08 18:11
Not all build dependencies can be made into libraries I think. Eg, https://github.com/stepancheg/rust-protobuf, where the binary is a plugin for protoc.

At the moment Cargo effectively builds all deps with --lib, is that what we want? What if I as a package author know that my package consists of both a lib and a binary, wouldn't it make sense for me to be able to override it in my manifest? Or as a user of package, where I know the package provides more than just a lib, wouldn't it make sense be able to declare in the dependency section of my manifest that the dependency should include more than just the lib target?

**Comment by per-gron** [comment] 2017-11-21 07:42
+1 for reopening this ticket. I am also trying to use protobuf (gRPC in my case), and I really don't like that the way people seem to do it is to ask their users to install grpc_rust_plugin and a bunch of other things globally. I would like my crate to be able to have versioned dependencies to these things.

**Comment by simonbuchan** [comment] 2020-05-13 02:39
My use case is embedding the dependency binary in the dependant binary. Am I missing some obvious alternative?

**Comment by tchernobog** [comment] 2021-08-17 13:40
See also https://github.com/rust-lang/cargo/issues/2267#issuecomment-900307541

**Comment by zopsicle** [comment] 2024-09-03 12:28
If support is added for `build.rs` to invoke an executable from a dependency, it would be great if it is also possible to have that dependency be cross-compiled.

My use case for this would be to have build.rs invoke Wine to invoke a cross-compiled Rust executable that invokes a function from a proprietary Windows DLL. Currently I have to jump through hoops to get this to work.
