### ISSUE TITLE
Check Cargo.lock in version control for libraries

### ISSUE THREAD

**Issue by tiziano88** [rust-lang/cargo#8728] opened 2020-09-24 23:20 UTC
**Describe the problem you are trying to solve**

[The official FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) and [various other places](https://github.com/rust-lang/cargo/issues/315) strongly suggest (almost mandate) that libraries do not check in Cargo.lock. This serves so that if the library is used as a dependency from another crate, the parent crate should get to decide what particular versions of dependencies to use for itself and all its transitive dependencies, respecting versioning restrictions indicated in the relevant Cargo.toml files.

**Describe the solution you'd like**

- strongly suggest versioning Cargo.lock in version control even for libraries; without this, it is practically impossible to achieve reproducibility of builds, tests and CI pipelines: the same exact version (commit checksum) of a library may compile / pass at some point in time on someone's machine, but spuriously break / fail later on or on some other machine, just because some dependency published a new version on crates.io
- add an option to `cargo` to skip packaging the local Cargo.lock when publishing a library to crates.io (by default it will exclude it for libraries and include it for binaries)
  + perhaps it is sufficient to [manually exclude](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) `Cargo.lock` from a package until this is implemented
- suggest relying on https://dependabot.com/rust/ or manually bumping dependencies in order to detect incompatibilities with new version of dependent crates in an automated way that is tracked under version control and maintains the hermeticity and reproducibility of builds, even for libraries

**Notes**

**Comment by Eh2406** [comment] 2020-09-25 01:39
Just to be clere a libraries `Cargo.lock` has no effect on resolution for a project that depends on that library. That is true if the library does not commit its `Cargo.lock`, and it is true if it commits it but does not include it when publishing, and it is true even if it ends up in the final published artifact. If you commit your `Cargo.lock`, so your CI is not broken by some new version on crates.io, then the first you will hear about the brokege is from your users.

Whether it is better to have flakey but real test in CI or to have reliable but mocked tests in CI, really depends on the priorities of the library. It is not so different from every other time a project considers using mock objects. Do you call that other microservice, then you will now fast if they broke their api but tests will be flakey, or do you mock it so you have fast reliable test of what that microservice used to respond.

**Comment by ehuss** [comment] 2020-10-20 19:51
I think it would be fine to add some more details to the documentation. There's a tradeoff, if `Cargo.lock` is included in source control, you'll likely be testing out-of-date dependencies. That's good for reproducibility as you say, but is bad because you won't quickly catch problems with new dependencies. If you have the CI budget, you can of course test both with `Cargo.lock`, and with the latest versions (by calling `cargo update && cargo test`).

**Comment by tiziano88** [comment] 2020-10-20 19:56
Catching problems with new dependencies should not happen when someone is trying to test an unrelated change. Which often results in a new dependency breaking CI, which prevents even other, unrelated changes from going through. 

dependabot (or something similar) seems the ideal solution to me, since it guarantees deterministic and hermetic CI, while at the same time allowing testing against new dependencies, in their own PR, so that if there is any issue after the fact it is also easy to narrow it down to the specific commit that introduced the new dependency version.

`cargo update && cargo test` has again reproducibility issues, since the result of `cargo update` depends on the exact point in time at which it is run.

**Comment by epage** [comment] 2022-12-26 13:32
Another reason to revisit this decision is interest in MSRV testing. Until we have a minimal versions resolver feature stablized, the lockfile is the easiest way to emulate it when verifying MSRV in libraries.

**Comment by demurgos** [comment] 2023-06-16 08:10
I sent a PR to update the book and recommend always using a lock file: https://github.com/rust-lang/cargo/pull/12275

**Comment by epage** [comment] 2023-06-27 18:19
Wanted to add on some more data points around MSRV.

We've seen some people misuse version requirements (rather than using a lock file) to make working with MSRV easier, including:
- https://github.com/rust-lang/cargo/issues/6584#issuecomment-1308032517
- https://www.reddit.com/r/rust/comments/p8clcx/how_to_fix_cargo_dependency_issue/

Apparently, the version requirement approach is common enough that its a top google search (haven't been able to find it myself)

> Some quick Googling suggested that I could explicitly depend on half in my own Cargo.toml, and therefore choose a compatible version there; 

See https://www.reddit.com/r/rust/comments/14khqdt/is_there_something_different_about_cargos/

And I've noticed that for winnow that [16 out of 26 dependents exist for MSRV version req hacks](https://crates.io/crates/winnow/reverse_dependencies).  That number would be higher except I've specifically reached out to some of the dependents and tried to steer them to doing things a different way.

**Comment by epage** [comment] 2023-06-27 21:48
See also [a zulip thread from earlier this year](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Commit.20lockfiles.20for.20libs.3F)

Motivations in addition to MSRV include
- Green CI
  - CI turning red for a PR from an unrelated change is a bad contributor experience
    - The contributor assumes its their fault and looks into it, wasting their time.  Hopefully they recognize its not their fault.  If they don't, then they waste even more time figuring out how their change broke it
    - Maintainers need to drop everything and fix it to not make the experience worse for contributors
    - This is delayed by `(detection_time + report_time + maintainer_availability + fix_time + review_time + ci_time_pr + ci_time_bors)`
  - Example: Before `cargo` had its own lockfile, snapshot tests would fail when human readable output from a dependency changed, causing CI to go red
  - Example: Before `cargo` had its own lockfile, CI would turn red if a new dependency was released that deprecated parts of it API (#10742 was also considered for resolving it)
  - Example: if `-Zdirect-minimal-versions` (#5657) is merged and people verify it, then a dependency updating a shared dependency can cause a breakage
- `git bisect`
  - Example: I had to bisect a problem with `cargo` but found no "root cause" commit.  Most likely, the cause was in some dependency but I couldn't control for that
- Documents a "golden stack" for debugging problems
- Not being broken by dependencies that yank versions (see also [internals](https://internals.rust-lang.org/t/suggestion-cargo-yank-is-a-misfeature-and-should-be-deprecated-and-eventually-removed/18486))

Downsides with having a policy of checking-in lockfiles
- `[lib]`s CI jobs act as a distributed ecosystem-focused "crater" run.  This puts peer pressure on the ecosystem for fixing bugs and yanking unintended breakages, helping maintain quality and adherence to semver.
  - Note that this is limited to `[lib]`-only repos that are following the guideline (e.g. `clap` checks in its lockfile).  It also only captures the version
- Testing the latest dependencies reflects what dependents will be doing
  - This is also true for workspaces with `[[bin]]` crates (#7169) but isn't covered in the policy
  - This is only sampling dependencies at specific times and does not reflect if a dependent is locked to a version that wasn't not covered in CI or newer than the last CI run.  Even worse is bugs can be dependent on the specific versions of dependencies and dependents.

Potential routes
- #9930 and #5221
- Recommend maintaining a `Cargo.lock.msrv`
  - A CI job copies it into place and does verification with `--locked` (to ensure it isn't stale)
  - High friction for adding or changing dependencies
- Change the `Cargo.lock` policy to check it in, updating `cargo new` to not exclude it in the `.gitignore` file
  - Recommend either staying up-to-date with dependencies (e.g. [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot) or [RenovateBot](https://docs.renovatebot.com/)) or verify the latest dependencies always work with a job that runs `cargo update` before doing its verification (whether just `cargo check` or `cargo test`)
    - The verification job should likely be a scheduled job to avoid making CI go red for contributors *but* Github will auto-disable the full Workflow for all Triggers if it is scheduled and there has been a lull in activity (2 months?), hurting projects that are passively maintained
  - Also recommend #374 once its available to reduce breaking of dependents

**Comment by epage** [comment] 2023-06-28 19:44
#12275 highlights the approach taken from other ecosystems

- [Yarn for Node.js](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored)
  > Which files should be gitignored?
  >
  > [...]
  >
  > - yarn.lock should always be stored within your repository ([even if you develop a library](https://yarnpkg.com/getting-started/qa#should-lockfiles-be-committed-to-the-repository)).
- [Poetry for Python](https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control)
  > As a library developer
  >
  > A simple way to avoid such a scenario [testing with latest transitive dependencies] is to omit the `poetry.lock` file. However, by doing so, you sacrifice reproducibility and performance to a certain extent. Without a lockfile, it can be difficult to find the reason for failing tests, because in addition to obvious code changes an unnoticed library update might be the culprit. [...]
  >
  > If you do not want to give up the reproducibility and performance benefits, consider a regular refresh of `poetry.lock` to stay up-to-date and reduce the risk of sudden breakage for users.
- [Bundler for Ruby](https://bundler.io/guides/faq.html#using-gemfiles-inside-gems)
  > Q: Should I commit my `Gemfile.lock` when writing a gem?
  >
  > A: Yes, you should commit it. The presence of a `Gemfile.lock` in a gem’s repository ensures that a fresh checkout of the repository uses the exact same set of dependencies every time. We believe this makes repositories more friendly towards new and existing contributors. Ideally, anyone should be able to clone the repo, run `bundle install`, and have passing tests. If you don’t check in your `Gemfile.lock`, new contributors can get different versions of your dependencies, and run into failing tests that they don’t know how to fix.

**Comment by epage** [comment] 2023-06-29 21:54
@zachw and I met during office hours to discuss their concerns over lockfiles.

This is going to be a rough recollection of the discussion that I'm hoping people find helpful.

There were bad experiences with lockfiles in other ecosystems
- "I downloaded a thing; it doesn't work.  I deleted the lockfile; now it works"
  - For example, the compilers having broken compatibility and new dependency versions are needed to work with the current compiler versions
- Lockfiles affecting dependents in node
  - Someone locked a dependency on something that only used TLS 1.1 (which was no longer being supported by services)
- *How do we build trust with people who have used similar looking techniques, even if our approach is different?*

From this came up a concern:  Would cargo eventually follow node and have lockfiles from dependencies affect dependents?
- I don't think this will happen.  The role of a lockfile is for your current project and version requirements are for your dependents
- Unsure if any of this is codified.  If not, I might codify it as part of https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Version.20Requirements.20documentation

Testing
- Testing a lockfile only tests a specific version
  - Minimum version requirements might be wrong
  - Bugs might have happened outside of the locked version that won' be caught
- Unfortunately, CI resources are limited (and we can't time travel to test future versions of dependencies), so the question is which combination of dependencies should be tested
- At this point, this seems orthogonal to lockfiles (checking in tests one set, not checking-in just tests a different set though it does evolve over time)
- If we make a change in our `Cargo.lock` recommendation, we'd likely also recommend in our CI section for people to have a CI job that first runs `cargo update`, so people test `Cargo.lock` + latest
  - If #5657 was stable, then that too

"Dependanbot"-like bots
- These cause extra work and most of it wouldn't be needed if lockfiles didn't exist (some of us would still want automation of upgrading across breaking releases)
- For me, I've found RenovateBot took away most of the churn
- I also see it beneficial to have PRs for updating the lockfile because I then get CI runs to verify the upgrade worked rather than unpredictable CI failures on unrelated PRs

"I add a dependency on `foo` and its failing.  I go to contribute a fix to `foo` and I can't reproduce it"
- Yes, for first-time contributors not having a lockfile checked-in produces fewer chances of confusion
- However, if its your second time interacting with `foo`, you can have the opposite experience where your local `Cargo.lock` from last time can't reproduce a failure in CI for your PR
- Ends up being a trade off of which experience you focus on (along with all of the other trade offs)

Is checking-in a lockfile for MSRV just a hack?
- Mostly
- I started checking in my lockfiles because I found there was no way to maintain my MSRV  policy without doing so
- Ideally #9930 would make this need go-away but that is dependent on whether MSRV is set in dependencies
  - I'll also conservatively say its a year out from stable versions of Rust.  Longer if we have problems getting good error messages

How is it with the experience with old, unmaintained Rust projects?
- For dependents, the lockfile doesn't matter
- For "CI running latest helps verify new dependencies", the point is moot because CI isn't being run
  - You could have scheduled jobs but at least for Github, they deactivate the entire workflow if it has a cron trigger
- For forking the project, I've just updated dependencies as part of the cleanup and it hasn't been a big deal

**Comment by epage** [comment] 2023-07-01 01:19
@rfcbot fcp merge

I'm recommending we change the policy to always checking-in `Cargo.lock` while expanding on our CI best practices to suggest having a `cargo update && cargo test` job (non-blocking for PRs).

Earlier this year, I broached the subject of changing this default on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Commit.20lockfiles.20for.20libs.3F).  Since then I've been seeing a lot more cases of people using version requirements that can break their dependents, partially for the sake of us having a policy to not commit `Cargo.lock` ([example](https://www.reddit.com/r/rust/comments/p8clcx/how_to_fix_cargo_dependency_issue/)).    In writing guidance in #12323 for people not to use upper-bounds that aren't semver-breaking-aligned, I felt like I really had no alternative solution to offer than to use a `Cargo.lock` and I just glossed over in the initial draft of that guidance the whole discussion of "bin vs lib" (wrt to `Cargo.lock`)

Even "bin vs lib" is messy because of workspaces and muilti-crate packages.  For example, I regularly use [`ignore`](https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore) which lives in the same workspace as ripgrep.

Earlier in this thread I've summarized:
- Problems people are having due to this policy (https://github.com/rust-lang/cargo/issues/8728#issuecomment-1610008113)
- What we've learned from discussing this in the past (https://github.com/rust-lang/cargo/issues/8728#issuecomment-1610265047)
- What other ecosystems are doing (https://github.com/rust-lang/cargo/issues/8728#issuecomment-1612006473)

This is all a matter of trade offs and the question is which set of pros/cons do go with.

**Comment by epage** [comment] 2023-07-06 15:56
> Is there a diff of the changes to the recommendations? Would cargo new change?

My expectations
- Update the recommendation
- Update `cargo new`
- Update CI to encourage testing

> What would be the actual guidance for having projects test with latest updates be? If it is to run cargo test && cargo update && cargo test in CI, then it seems like you'll still have problems for contributors. It also seems like asking users to essentially double their CI time would be very significant.

I would expect CI recommendations to be to verify the latest version (at time of run) is still valid for your project in a way that is non-blocking for contributors.  

This can happen in one of several ways
- A "continue on failure" job in CI
  - This might might cause noise and slow CI for contributors
- A scheduled workflow
  - If your project updates on a less-frequent basis, your CI host might disable the workflow (e.g. github does this)
- A bot that updates all dependencies on a regular basis

The level of verification is dependent on your project,  your dependencies, the level of risk, and CI costs.  A baseline would be to select a representative platform (if the project is platform agnostic) and have a single job on that platform run `cargo update && cargo test --all-features`.

This means that either the extra jobs might not be part of CI and might be minimal (1 job) so overall CI resources should be minimally impacted.  Similarly, I run only MSRV verification on a single platform but I only do `cargo check` and not `cargo test`.

> The number of people who are users of a library can be much larger than the number of contributors to it. An inconvenience for the contributors can be overwhelmed by the inconvenience to the users (who are in much less of a position to understand what is wrong).

Which inconvenience are you referring for both the contributors and the users?

For maintainers wanting to maintain an MSRV policy, there options are
- Abandon it completely or as a "always update to latest" without any lookback, **impacting users relying on the MSRV policy**
- Maintain a lockfile
- Hack up their version requirements, **breaking other users**

This will be reduced once we get an MSRV-aware resolver in but
- That is likely a year out for stable, longer for propagating to enough versions
- That doesn't help with dependencies that don't specify an MSRV

For contributors, there is the "inconvenience" of master being red.  I would not classify that as an inconvenience but something that can harm the growth of the project which can hurt the long term maintenance of the project **which will hurt users**

As for users, an "inconvenience" is that there might be incompatibilities (bugs in a dep, bugs in how caller users dep, actual breaking changes) that could be detected sooner with the current approach.  However, this is dependent on many factors
- The last PR for the direct dep to see any issues can be fairly old (ideally most packages are well defined and go into a maintenance mode) so there are many releases in aggregate of dependencies that won't be verified
- If I have a lockfile (because I have a bin), I might do some action that upgrades the indirect dep without updating the direct dep for any changes it might need

> Since cargo doesn't have an --unlocked flag, testing in some environments with updates can be awkward or impossible due to read-only mounting.

How theoretical is this or are you aware of the scope of how much people do this?  This can give us an idea of how much we need to define general recommendations around it, including caveats, or leaving it to them to figure out how to adapt guidance to an esoteric environment.

I would also expect a place doing this is likely also creating binaries and they would already run into this problem.

> I would be much less concerned about changing recommendations if cargo did semver checks during publish. That wouldn't help with behavioral breakage, but could cover a significant amount of post-publish breakage.

This is nice in theory but, as I pointed out earlier, the scope of people benefiting from the "distributed crater" is limited and is likely shrinking as people are feeling the pain of MSRV or non-reproducible builds and are checking in lockfiles.

Where this isn't being limited, there are other workarounds going in place that are far worse, like restricting the upper bounds on version requirements.  As I pointed out earlier, as one example of the scope of this is that more than half of `winnow`'s direct dependents are pinning the version in their `Cargo.toml`.  Not being familiar with all of the projects, its not quite clear to me when some of them may be depended on, so I can't filter that number down for how many could be breaking their dependents.

This is also creating a situation where people "in the know" do one thing while newer users or users less confident in breaking away from guidelines are dealing with the problems and likely solving them in the wrong way.

**Comment by fintelia** [comment] 2023-07-06 18:16
Having deterministic / reproducible CI runs could equally be achieved by capturing the `Cargo.lock` as a workflow artifact.

For testing with your MSRV, a common recommendation is to check in a `Cargo.lock.msrv` that gets used _only_ for the specific runs that test with an old Rust version. It thus has no bearing on whether a normal `Cargo.lock` should also be checked into the repository.

It seems like a main goal of this suggestion is to keep CI green more often. And it does so by having nearly all your CI runs repeatedly testing against pinned dependency versions __rather than running against newer versions that would be more likely to discover bugs__ and turn CI red. That... seems backwards to me?

**Comment by ia0** [comment] 2023-07-06 18:25
> It seems like a main goal of this suggestion is to keep CI green more often.

That's only partially true. Both the original post and [later posts](https://github.com/rust-lang/cargo/issues/8728#issuecomment-1610265047) mention build reproducibility which is useful for other reasons than just CI. In particular all things debugging related, like `git bisect` or debugging between multiple developers.

**Comment by epage** [comment] 2023-07-06 19:31
>  rather than running against newer versions that would be more likely to discover bugs

Also, note that my proposal includes encouraging people to regularly test the latest versions of their dependencies in some way.  See https://github.com/rust-lang/cargo/issues/8728#issuecomment-1623921676 for more details

**Comment by fintelia** [comment] 2023-07-06 20:03
A bunch of the arguments here would also apply to checking in a `rust-toolchain.toml` file. My understanding is that this isn't very common across the ecosystem, but it raises the question of whether it should be?

**Comment by tiziano88** [comment] 2023-07-06 20:05
> A bunch of the arguments here would also apply to checking in a `rust-toolchain.toml` file. My understanding is that this isn't very common across the ecosystem, but it raises the question of whether it should be?

IMO yes, in fact ideally a completely deterministic [nix](https://nixos.org/) configuration should be checked in in every project (regardless of its language(s)).

**Comment by ehuss** [comment] 2023-07-08 18:37
> Which inconvenience are you referring for both the contributors and the users?

The inconvenience I'm thinking of for a contributor is: I push a change, CI is red, I spend a few minutes to figure it out and push a fix and move on (possibly reporting a bad semver update in a dependency). My expectation, based on the issues I've experienced, is that this takes relatively little time.

The inconvenience for a user is that they try to add your crate to their project (or update to a new version), and it fails because of some issue (like an broken semver update). They hit a roadblock that they either don't understand, or don't know how to fix, or need to spend time tracking down, informing some dependency that something is wrong (though they might now know which one). My experience, based on seeing user reports, is that some people get confused or frustrated, and may not be in a position to understand how to fix the problem.

> How theoretical is this or are you aware of the scope of how much people do this? This can give us an idea of how much we need to define general recommendations around it, including caveats, or leaving it to them to figure out how to adapt guidance to an esoteric environment.

rust-lang/rust runs with read-only mounts, and wouldn't be able to test unlocked libraries. My understanding is that it is not too uncommon to mount the source tree in read-only mode with Docker.

----

I'm very much in favor of updating the documentation to make to tradeoffs clearer to the user, and to provide suggestions on how to keep their project in a healthy state (like using dependency bots, scheduled jobs, different CI strategies, etc.). I think it should be made clear to users that it isn't *wrong* to check in `Cargo.lock`, or that it has any impact to users (other than the hazards of not testing latest version). I think it might also be good to put some suggestions for the `cargo publish` workflow to consider testing against latest versions. I'm less confident about specifically changing the default behavior (like `cargo new`) until cargo has better facilities for testing and verification.

**Comment by parasyte** [comment] 2023-07-10 23:38
The "distributed crater" idea is very disappointing. By the time a semver-incompatible library is published, **it's already too late**. Following semver is the responsibility of the crate maintainer, not its users. The fact that CI can be abused to test for semver incompatibilities is a happy accident, it's not what the ecosystem needs for addressing the problem.

My suggestion for that is encouraging semver compatibility tests in CI, e.g. [`cargo public-api`](https://github.com/Enselic/cargo-public-api) or [`cargo semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks). [^1] I don't know the effectiveness of these tools, but even if they catch just over than half of common problems it could have a bigger positive impact than "distributed crater" with less accidental work (toil) for maintainers of other projects.

[^1]: There is also https://github.com/rust-lang/rust-semverver, which is deprecated and links to the other two projects as potential alternatives.

**Comment by epage** [comment] 2023-07-11 00:46
FYI #374 is for tracking automated semver checking (for what can be checked).

**Comment by epage** [comment] 2023-07-17 21:24
I've updated my [earlier comment](https://github.com/rust-lang/cargo/issues/8728#issuecomment-1610265047) with the various trade offs that have been discussed.

If we do this, we should decide what the appropriate level of communication is.  For example, should this be an Inside Rust blog post?

To make the proposal more concrete, I'm going to include a rough draft of the PR description and the documentation changes.  The intent is to not  nitpick the language (the PR will be for that) but to give people a more concrete idea of what is being proposed (and to nitpick that)

---
*PR Description*

fix: Change the defaults to always check-in `Cargo.lock`

Having libraries leave `Cargo.lock` "on the float" has been serving the ecosystem well, including
- Encouraging people to validate latest dependencies work
- Encouraging ecosystem-wide health by acting as a "distributed crater"

These benefits are limited though.  The policy is inconsistent between workspaces with or without `[[bin]]`s, reducing the affect of testing the latest.  This is also subject to when CI last ran; for passively maintained projects, there is little coverage of new dependencies.

There are also costs associated with this policy
- `git bisect` is using an unpredictable set of dependencies, affecting the ability to identify root cause
- This is another potential cause for Red CI / broken local development if version is yanked or a bug is introduced
  - Impacting the perceived level of quality for a project
  - Confusing to new contributors who might not recognize why CI failed and assume its their fault
  - Requiring context switching from maintainers to get fixes in

In particular, since this policy was decided, there has been an increased interest in supporting an MSRV (as recently as v1.56.0, cargo gained support for specifying a package's MSRV).   This has led to fatiguing discussions on *what* MSRV a package should use (e.g. https://github.com/rust-lang/libs-team/issues/72,. https://github.com/time-rs/time/discussions/535).  Worst, there has been a growing trend for people to set an non-semver upper bound on dependencies, making it so packages can't work well with other packages.  Tooling support would help with this (#9930) but the sooner we address this, the less entrenched bad practices will be.

On the positive side, since the policy was decided
- In general, CI became easier to setup and maintain with Github Actions compared to TravisCI
- Dependabot went GA on Github in 2021 (https://github.blog/changelog/2021-03-31-dependabot-version-updates-are-now-generally-available)
  - I believe Dependabot will post security update PRs even when Dependabot is not more generally enabled

So to get some of the benefit from not checking in `Cargo.lock`, we can recommend either automatically applying updates or having CI check the latest dependencies in a way to get this out of the critical path of PRs and releases.

Since there is no one right answer on how to solve all of these problems, we're documenting these trade offs so people can make the choice that is most appropriate with them.

Prior art
- [Yarn (Javascript)](https://yarnpkg.com/getting-started/qa#should-lockfiles-be-committed-to-the-repository)
- [Poetry (Python)](https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control)
- [Bundler (Ruby)](https://bundler.io/guides/faq.html#using-gemfiles-inside-gems)

---
*[Cargo.toml vs Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)*

Old:

> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put Cargo.lock in your .gitignore. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git. If you’re curious about why that is, see [“Why do binaries have Cargo.lock in version control, but not libraries?” in the FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

New:

> When in doubt, check `Cargo.lock` into git. For a better understanding of why and what the alternatives might be, see [“Why have Cargo.lock in version control?” in the FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).  We recommend pairing this with Verifying Latest Dependencies (link to new CI section, see below)

---
*[Why do binaries have Cargo.lock in version control, but not libraries?](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)*

### Why have `Cargo.lock` in version control?

While `cargo new` defaults to tracking `Cargo.lock` in version control, whether you do is dependent on the needs of your package.

The purpose of a Cargo.lock lockfile is to describe the state of the world at the time of a successful build. Cargo uses the lockfile to provide deterministic builds on different times and different systems, by ensuring that the exact same dependencies and versions are used as when the Cargo.lock file was originally generated.

Deterministic builds help with
- Running `git bisect` to find the root cause of a bug
- Ensuring CI fails due to new commits and not external factors
- Reducing confusion when contributors see different behavior as compared to other contributors or CI

Having this snapshot of dependencies can also help when projects need to be verified against consistent versions of dependencies, like when
- Verifying a minimum-supported Rust version that is less than the what latest version of a dependency supports
- Verifying human readable output which won't have compatibility guarantees (e.g. snapshot testing error messages to ensure they are "understandable", a metric too fuzzy to automate)

However, this determinism can give a false sense of security because `Cargo.lock` does not affect the consumers of your package, only `Cargo.toml`, for example:
- `cargo install` will select the latest dependencies unless `--locked` is passed in (see #7169)
- New dependencies added via `cargo add` will be locked to the latest version

For strategies to verify newer dependencies, see Verifying Latest Dependencies

---
*In a new [Reference](https://doc.rust-lang.org/cargo/reference/index.html)-level CI page that the [CI guide](https://doc.rust-lang.org/cargo/guide/continuous-integration.html) links to*

### Continuous Integration

#### Verifying latest dependencies

When [specifying dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) in `Cargo.toml`, a range of versions are possible.  Testing every possible version combination would be unwieldy.  At minimum, it would help dependents of your package to at least verify the latest versions.

When testing the latest versions some considerations are:
- Minimizing external factors affecting local development or CI
- Rate of new dependencies being published
- Level of risk a project is willing to accept
- CI costs, including indirect costs like if a CI service has a maximum for parallel runners, causing additional jobs to be serialized when affected

Some potential solutions include:
- Not checking in the `Cargo.lock` (links to FAQ)
  - Depending on PR velocity, many versions may go untested
  - This comes at the cost of determinism
- Have a CI job verify the latest dependencies but mark it to "continue on failure"
  - Depending on the CI service, failures might not be obvious
  - Depending on PR velocity, may use up more resources than necessary
- Have a scheduled CI job to verify latest dependencies
  - A hosted CI service may disable scheduled jobs for repositories that haven't been touched in a while, affecting passively maintained packages
  - Depending on the CI service, notifications might not be routed to people who can act on the failure
  - If not balanced with dependency publish rate, may not test enough versions or may do redundant tests
- Regularly update dependencies through PRs, like with Dependabot or RenovateBot
  - Can isolate dependencies to their own PR or roll them up into a single PR
  - Only uses the resources necessary

An example CI job to verify latest dependencies, using Github Actions:
```yaml
jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
```
For projects with higher risks of per-platform or per-Rust version failures, more combinations may want to be tested.

**Comment by epage** [comment] 2023-07-19 16:50
I've posted #12382 for this.  It is a draft while we wait for the final comment period.

**Comment by fintelia** [comment] 2023-07-21 03:55
I think the "What should `Cargo.lock` represent as opposed to `Cargo.lock.<topic>` if used?" related question needs to be answered at the same time the rest of this proposal is.

Right now there seems to be some switching back and forth between `Cargo.lock` meaning a "nearly current version of all dependencies" (maintained via Dependabot or similar) or "versions that work with your crate's MSRV" (which is useful to track but can't be automated without the relevant tooling becoming msrv aware).

**Comment by epage** [comment] 2023-07-21 15:01
> I think the "What should Cargo.lock represent as opposed to Cargo.lock.<topic> if used?" related question needs to be answered at the same time the rest of this proposal is.

I don't think we need one answer for this.  The `Cargo.lock` is *a* snapshot of what works at a given time.  There can be different motivations for different projects for what that snapshot should reflect and if more than one snapshot is needed.

> Right now there seems to be some switching back and forth between Cargo.lock meaning a "nearly current version of all dependencies" (maintained via Dependabot or similar) or "versions that work with your crate's MSRV" (which is useful to track but can't be automated without the relevant tooling becoming msrv aware).

This is because the answer is "it depends".  There are multiple strategies for how you test latest and how you test MSRV.  We are leaving that in users hands to make a decision.  We aren't saying you have to use Dependabot and keep all dependencies at latest.

**Comment by fintelia** [comment] 2023-07-21 16:14
The guidelines should list out what strategies there are to pick from, and the associated trade-offs. Instead, the draft text just has a co-mingled list of benefits from different strategies without clarifying that some are mutually incompatible. (It also strongly implies that certain benefits are only possible by checking in a Cargo.lock, which as has been discussed a few times in this thread, isn't true)

**Comment by epage** [comment] 2023-07-21 16:21
Please be more specific as with that I have no idea which parts you are referring to and can't act or respond.

**Comment by fintelia** [comment] 2023-07-21 16:51
All the discussion around `Cargo.lock.msrv` that didn't make it into any of the draft guidelines

**Comment by fintelia** [comment] 2023-07-21 17:01
And "Why have Cargo.lock in version control?" for a place that's assuming specific strategies without saying so

**Comment by epage** [comment] 2023-07-21 17:14
Please provide more detail than that.  I feel like you have a specific set of ideas in mind but I have not been able to discern them from what has been said so far.

I am well aware of the past conversations and I just re-read the new FAQ entry that is in #12382.  I'm not quite seeing what you are referring to.

**Comment by fintelia** [comment] 2023-07-21 19:32
I give up. I cited a specific section ("Why have Cargo.lock in version control?") of your [previous comment](https://github.com/rust-lang/cargo/issues/8728#issuecomment-1638903420) that lists benefits of checking in Cargo.lock but assumes a `Cargo.lock = MSRV` strategy will be used, without saying so. I also give a specific topic ("Cargo.lock.msrv") that was discussed here, but isn't mentioned in the PR description or the FAQ changes

**Comment by ogoffart** [comment] 2023-07-22 05:31
I would like to offer a counterpoint against checking in the `Cargo.lock` file in the repository. 
While there are valid arguments for including it, there are also considerations against doing so:

 - Conflicts between branches: When working with different branches, conflicts can arise due to changes in dependencies within the branches. Checking in the `Cargo.lock` file can lead to conflicts when merging or switching between branches.

 - Noise in commits and pull requests: Including the `Cargo.lock` file in version control can clutter the commit history and pull requests with unnecessary changes. The frequent changes in the `Cargo.lock` file create noise.

 - Testing with the latest dependencies: This has already be said, but it is essential to test code with the latest dependency versions as that is what users will ultimately experience.
   This ensures any potential issues arising from dependency incompatibilities are detected early, allowing proactive actions, such as releasing new versions of the crate to avoid roadblocks for users.
   
 - Regarding MSRV workaround, I've added `cargo update --precise` in my CI: https://github.com/slint-ui/slint/blob/e9286c11890a66e39b1779b7f20854d65baaf9b9/.github/workflows/ci.yaml#L70

**Comment by epage** [comment] 2023-07-22 13:00
Thanks @ogoffart with this info! Will be updating the PR with merge conflicts and what I'm about to say.

The purposed change is from cargo telling people what to do to giving them a starting point, or default, and giving them the information to make their own choice, if needed.

So the question for defaults is who are we targeting? For a default path in documentation, it would be for new to intermediate users. By the time you form a company around a large `[workspace]`, you are more likely to be in a position to make a choice that works for you and its more likely it will be bespoke.

As for `cargo new`, we've been prioritizing new users over those that run it frequently (boiler plate comment, bin is default, etc).

**Comment by epage** [comment] 2023-07-28 18:45
FCP is finished but we will be waiting until the next beta branch is created before moving forward so we get a full 12 weeks of feedback.

**Closed** 2023-08-21 23:13 UTC
Labels: A-documenting-cargo-itself, C-feature-request, T-cargo, finished-final-comment-period, disposition-merge, to-announce, S-needs-team-input

**Comment by safinaskar** [comment] 2023-08-30 18:53
This fiasco is possibly related: https://github.com/rust-lang/rust/issues/113152#issuecomment-1699673552 . Nearly all my binary projects created nearly May 2023 (assuming they have `Cargo.lock`) don't build anymore. Removing `Cargo.lock` fixes them

**Comment by parasyte** [comment] 2023-08-30 19:03
@safinaskar That breakage is unrelated to `Cargo.lock`; it is caused by a change to the nightly compiler. You can either build with the latest stable compiler (as mentioned in a response to your comment on that ticket) or, more appropriately perhaps, pin your nightly version with a [toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file).

**Comment by Nemo157** [comment] 2023-08-30 19:09
(or try to apply pressure on crate authors to not silently opt their users into unstable breakage simply because they use a nightly compiler)

**Comment by epage** [comment] 2023-08-30 19:49
I agree with @Nemo157  that that was a bug in proc-macro2 to use nightly features without a users consent (usually a `unstable` or `nightly` feature flag).

**Comment by ctz** [comment] 2023-10-04 10:47
> suggest relying on https://dependabot.com/rust/ 

Note that dependabot uses the existence of `Cargo.lock` as a heuristic that a crate is an application. The behaviour seems not configurable, and by default means a library-with-a-lockfile will churn dependency versions forwards in the `Cargo.toml`.

**Comment by Nemo157** [comment] 2023-10-04 12:51
This might be a good incentive to open an issue about having that configurable in dependabot, it's a big reason I don't use it on most of my repos.

**Comment by epage** [comment] 2023-10-04 13:54
The primary reason I switched to RenovateBot was to make dependency updating faster (dropped my monthly updates from a couple days to part of a day) but the greater control was a close second.  For example, [here is the config for clap](https://github.com/clap-rs/clap/blob/master/.github/renovate.json5)
