### ISSUE TITLE
$CARGO_CFG_DEBUG_ASSERTIONS is set to the empty string in build scripts for both debug and release modes

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/cargo#6148] opened 2018-10-06 19:57 UTC
The following build script will print `""` when run with both `cargo build` and `cargo build --release`.

```rust
use std::env;

fn main() {
    if let Ok(s) = env::var("CARGO_CFG_DEBUG_ASSERTIONS") {
        panic!("\"{}\"", s);
    } else {
        panic!("CARGO_CFG_DEBUG_ASSERTIONS not set");
    }
}
```
I would expect the `CARGO_CFG_DEBUG_ASSERTIONS` environment variable to be unset in release mode (where `cfg!(debug_assertions)` is false by default).

Version info:
`cargo 1.30.0-nightly (b917e3524 2018-09-09)`

**Comment by alexcrichton** [comment] 2018-10-08 17:38
Thanks for the report! I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/5777, so I'm going to close in favor of that.

**Closed by alexcrichton** 2018-10-08 17:38 UTC
