### ISSUE TITLE
Crash at `cargo run`

### ISSUE THREAD

**Issue by palango** [rust-lang/cargo#2132] opened 2015-11-10 20:37 UTC
I just ran `cargo update` and then `cargo run` on a project with a simple `Cargo.toml` like the following:
```
[package]
name = "gltest"
version = "0.1.0"

[dependencies]
glium = "*"
image = "*"
```

It panics with the following message. The ids contain what I guess to be all resolved dependencies. It's really long so I didn't put everything here. It happens on `rustc 1.4.0 (8ab8581f6 2015-10-27)` and `cargo 0.5.0-nightly (833b947 2015-09-13)`.
```
thread '<unnamed>' panicked at 'could not get packages from registry; ids=[...], ..src/cargo/core/registry.rs:103
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:732
```

**Comment by nstoddard** [comment] 2015-11-10 21:48
I'm seeing the same thing. It's preventing me from running some of my projects :(

**Comment by alexcrichton** [comment] 2015-11-11 02:25
cc @bvssvni, looks like this is due to a "corrupt tarball" on for the `png` crate on crates.io. It's definitely Cargo's fault for this (hence the referenced PR to fix this bug), so hopefully it doesn't happen in the future!

The gist of the problem is that the tarball for 0.3.1 of the `png` crate contains the `inflate` dependency bundled inside of it:

```
$ curl -L https://crates.io/api/v1/crates/png/0.3.1/download | tar xzf -
$ ls png-0.3.1
Cargo.toml LICENSE    README.md  examples   inflate    png_new.rs src
```

Normally this doesn't happen, but it looks like `png` [specifies the `exclude` key](https://github.com/PistonDevelopers/image-png/blob/master/Cargo.toml#L8-L10) which ends up including everything else (probably mostly by accident right now). Cargo unfortunately wasn't prepared to handle this, so it's generating an error if you depend on `png` 0.3.1 and `inflate` directly via some other means.

If you want to fix this in the interim it can be fixed with a new publish of `png` without the bundled `inflate` directory (e.g. by removing `exclude` or specifying `include` instead). 

Sorry for the trouble here guys, but let me know if there's anything I can do to help!

**Closed** 2015-11-11 02:47 UTC

**Comment by palango** [comment] 2015-11-11 19:16
Thanks for the fix. Is there any way to circumvent that behaviour for now, till the fix arrives in stable?

**Comment by bvssvni** [comment] 2015-11-11 20:12
I'm updating the ecosystem now to png 0.4.0, where inflate is moved to another repo.

**Comment by alexcrichton** [comment] 2015-11-11 20:22
@palango yeah for now if everything uses png 0.4.0 or if a new png 0.3.2 is published it should fix the problem
