### ISSUE TITLE
cargo check duplicated info

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/cargo#9005] opened 2020-12-21 11:00 UTC
**Problem**
after upgrading to latest rustc 1.50.0-nightly (eb4fc71dc 2020-12-17), I start to get duplicated warnings

**Steps**

1.
```rust
use std::fs::File;
fn main() {
    println!("Hello, world!");
}
```
2. set alias `alias ck='cargo check --all-targets'`
3. run `ck`
4.

![image](https://user-images.githubusercontent.com/33961674/102770254-1c089280-4384-11eb-96cf-442e2ba67e9f.png)

**Possible Solution(s)**

**Notes**

Output of `cargo version`: `cargo 1.50.0-nightly (d274fcf86 2020-12-07)`

**Comment by GopherJ** [comment] 2020-12-21 11:08
This error happens on the first `cargo check`, it disappears since the second run of `cargo check`

**Comment by ehuss** [comment] 2020-12-21 17:24
Hm, I'm having a hard time trying to figure out how to reproduce this.  Is this easily reproducible for you?  Did you maybe use other flags like `--all-targets`?  Can you show the whole output of `cargo check -v` after running `cargo clean`?

**Comment by GopherJ** [comment] 2020-12-21 18:44
@ehuss yes I'm using `--all-targets`, thanks for reminding me if this

**Comment by ehuss** [comment] 2020-12-21 18:57
Ah, in that case I'll close as a duplicate of #5128.  When you check multiple targets, some code gets checked multiple times (for example, the library gets checked as a normal library, and checked separately with the `--test` flag to check unit tests).  That fundamentally can't be avoided, but I do intend to add some kind of message deduplication logic to Cargo.

**Closed by ehuss** 2020-12-21 18:57 UTC
Labels: C-bug
