### ISSUE TITLE
Cargo build doesn't work when system has self-signed certificates installed.

### ISSUE THREAD

**Issue by rwz** [rust-lang/cargo#1801] opened 2015-07-12 04:55 UTC
I have some self-signed certificates in my `/etc/openssl/cert.pem` on my working machine that I need for work. Because of that cargo build doesn't work:

```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.1.9
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.9` from https://crates.io/api/v1/crates/libc/0.1.9/download

Caused by:
  SSL peer certificate or SSH remote key was not OK
```

Now if I remove or rename the `cert.pem` file, everything works fine. The problem is, I do need these certificates for number of other things, and Cargo is the only tool complaining about it.

Is there a way make it work AND have self-signed certificates at the same time?

Versions:

```
$ cargo -V
cargo 0.3.0 (b030d35 2015-06-25) (built 2015-06-26)
$ rustc -V
rustc 1.1.0
```

**Comment by rwz** [comment] 2015-07-12 05:17
After some digging around I found this issue: https://github.com/rust-lang/cargo/issues/976

Seems like the problem is only present in 1.1 stable and fixed in 1.2 beta. Is it possible to recompile 1.1 against fixed openssl and release rust 1.1.1 and cargo 0.3.1?

**Comment by alexcrichton** [comment] 2015-07-12 06:38
Currently we haven't been issuing new stable releases for small bug fixes like this, but it does seem to be hitting a lot of people. @brson what do you think about this? The buildbots have been updated so we'd literally be building the same source code, we'd just bump some version numbers and link against some new native libraries.

@rwz in the meantime I'd recommend just downloading a beta cargo binary and copying it over the 1.1 cargo binary, after that you should be good to go :)

**Comment by brson** [comment] 2015-07-12 21:08
I'd like to have a sense of how widespread the problem is, and to know how @rwz and others that are hitting this feel about moving to 1.2 beta until it becomes stable. If we can I prefer to tell people just wait a few weeks for 1.2, but if necessary it should not be too hard to create a point release.

**Comment by nealharris** [comment] 2015-07-12 23:55
I'm seeing a similar issue with the nightlys:
```
~/Development/hello-rust/guessing_game master * cargo build --verbose
 Downloading rand v0.3.8
Unable to get packages from source

Caused by:
  Failed to download package `rand v0.3.8` from https://crates.io/api/v1/crates/rand/0.3.8/download

Caused by:
  Peer certificate cannot be authenticated with given CA certificates
```

I'm using `rustc 1.3.0-nightly (0c052199b 2015-07-11)` and `cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-10)`

**Comment by nealharris** [comment] 2015-07-13 00:28
Argh, ignore my previous comment.  For posterity, I'm on OS X 10.10.4, and discovered that I had an expired Apple code signing cert at `/usr/lib/ssl/cert.pem`.  Of course, that raise other questions for me about OS X...

**Comment by bIgBV** [comment] 2015-07-17 10:47
I got this error when going through the guessing_game exercise and got here by searching for the same error on google. Plus I checked if I had any certificates that I created which expired in keychain access (New to ssl stuff so if there is anywhere else my certificates are stored then do tell because I checked in `/usr/lib` and the ssl directory wasn't present)

I'm using `rustc 1.1.0 (35ceea399 2015-06-19)` and `cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)`

**Comment by rats-gr** [comment] 2015-07-25 01:57
I have the same issue (I think):

**Comment by towry** [comment] 2015-09-02 08:16
Same issue here:

```bash
➜ test (master) ✗ cargo -V
cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-09)
➜ test (master) ✗ rustc -V
rustc 1.2.0 (082e47636 2015-08-03)
```

**Comment by radare** [comment] 2015-09-09 14:25
Related https://github.com/rust-lang/cargo/issues/1978

**Comment by Byron** [comment] 2015-09-17 06:19
I experience the same issue. Good to know how to workaround it though !

**Comment by kulbida** [comment] 2015-09-30 20:06
The same here, any progress in this direction?

**Comment by alexcrichton** [comment] 2015-10-01 00:23
I believe the original root cause was fixed some time ago, and otherwise this look like it's a dupe of https://github.com/rust-lang/cargo/issues/1689 so closing in favor of that.

**Closed by alexcrichton** 2015-10-01 00:23 UTC
