### ISSUE TITLE
error: failed to compile `bat v0.12.1`, intermediate artifacts can be found at `/tmp/cargo-installsQOPWY`

### ISSUE THREAD

**Issue by lgd8069465** [rust-lang/cargo#7747] opened 2019-12-27 06:07 UTC
**Problem**

~~~
error: failed to compile `bat v0.12.1`, intermediate artifacts can be found at `/tmp/cargo-installsQOPWY`

Caused by:
  cannot produce proc-macro for `failure_derive v0.1.6` as the target `x86_64-unknown-linux-musl` does not support these crate types
~~~
**Steps**

1.
~~~
[root@docker opt]# cat Dockerfile 
FROM rust:alpine
MAINTAINER 1071858797@qq.com
RUN cargo -V  && cargo install bat
~~~
2.
~~~
[root@docker opt]# docker build -t lgd/rust:alpine -f Dockerfile .
~~~

**Notes**

Output of `cargo version`:

~~~
cargo 1.40.0 (bc8e4c8be 2019-11-22)
~~~

**Comment by ehuss** [comment] 2019-12-27 17:19
Thanks, this is a known issue. Closing as a duplicate of #7563.

**Closed by ehuss** 2019-12-27 17:19 UTC
Labels: C-bug

**Comment by lgd8069465** [comment] 2020-03-18 07:32
it is a problem with glibc from alpine , i solved it, for reference only, plaese see [here](https://github.com/lgd8069465/Dockerfile-china/blob/alpine/rust-ustc/Dockerfile)

**Comment by sandy125vn** [comment] 2022-12-21 19:09
tks po
