### ISSUE TITLE
Can't re-export features of optional dependency

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#5023] opened 2018-02-08 21:36 UTC
As far as I can tell, there's no way to re-export features of an optional dependency.

Take these crates:
rayon - only compiles on targets with threads
jpeg_decoder - has a default feature "rayon" to enable faster decoding where possible
image - has a default feature "jpeg" which enables the jpeg decoder

Now the first problem is that `image` has an unconditional dependency on rayon. This isn't great, but it should be possible to fix by re-exporting a "rayon" feature from `image`.

However this doesn't work, because the "rayon" feature would have to automatically include the "jpeg_decoder" dependency, even if the "jpeg" feature is not enabled.

There should be a way to enable a dependency or dependency feature based on an intersection of top-level features.

**Comment by alexcrichton** [comment] 2018-02-09 16:00
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/3494, so closing in favor of that

**Closed by alexcrichton** 2018-02-09 16:00 UTC
