### ISSUE TITLE
cargo update fails: "The SSL certificate is invalid"

### ISSUE THREAD

**Issue by spinda** [rust-lang/cargo#3346] opened 2016-11-29 23:12 UTC
Issue:

```
$ cargo update --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `num_cpus`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [16/-17] The SSL certificate is invalid
```

System/version information:

```
$ cargo --version --verbose
cargo 0.16.0-nightly (3568be9 2016-11-26)
$ rustc --version --verbose
rustc 1.15.0-nightly (03bdaade2 2016-11-27)
binary: rustc
commit-hash: 03bdaade2a0c39118a5be927c667776a5de0d681
commit-date: 2016-11-27
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.13.0 (2c6933acc 2016-11-07)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.15.0-nightly (03bdaade2 2016-11-27)

$ uname -a
Linux ubuntu 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by alexcrichton** [comment] 2016-11-29 23:13
Thanks for the report! I believe this is a dupe of https://github.com/rust-lang/cargo/issues/3340, which should hopefully be fixed in the next nightly!

**Comment by spinda** [comment] 2016-11-29 23:13
Thank you! Next time I'll remember to check closed issues as well as open ones.

**Closed by alexcrichton** 2016-11-29 23:13 UTC
