### ISSUE TITLE
command for new workspace

### ISSUE THREAD

**Issue by tinsel-grumble** [rust-lang/cargo#9825] opened 2021-08-22 18:51 UTC
**Describe the problem you are trying to solve**
use cargo new to make workspace for multi bins and libs

**Describe the solution you'd like**
option to cargo new to setup workspace Cargo.toml not just bin or lib. maybe relate to https://github.com/rust-lang/cargo/issues/9823

**Notes**

**Comment by ehuss** [comment] 2021-09-11 20:22
Thanks for the suggestion!  I think this is pretty much the same as #8365 (combined with #9823), so closing as a duplicate of that.

**Closed by ehuss** 2021-09-11 20:22 UTC
Labels: Command-new, C-feature-request
