### ISSUE TITLE
Cargo cannot find emcc in path on Windows

### ISSUE THREAD

**Issue by paulcbetts** [rust-lang/cargo#3446] opened 2016-12-22 20:30 UTC
```
C:\Users\paulb\code\akavache\akavache-rs [master ≡]> cargo test --target wasm32-unknown-emscripten
   Compiling akavache v0.1.0 (file:///C:/Users/paulb/code/akavache/akavache-rs)
error: could not exec the linker `emcc`: The system cannot find the file specified. (os error 2)

C:\Users\paulb\code\akavache\akavache-rs [master ≡]> gcm emcc

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     emcc.bat                                           0.0.0.0    C:\Program Files\Emscripten\emscripten\1.35.0\emcc.bat
```

`emcc` is in %PATH% but cargo can't find it somehow

**Comment by alexcrichton** [comment] 2016-12-25 22:14
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/38489, so I'm going to close in favor of that. Thanks for the report though!

**Closed by alexcrichton** 2016-12-25 22:14 UTC

**Comment by paulcbetts** [comment] 2016-12-26 03:02
:+1:, will go subscribe
