### ISSUE TITLE
Global `cargo-features`

### ISSUE THREAD

**Issue by Flippette** [rust-lang/cargo#11552] opened 2023-01-08 04:03 UTC
### Problem

Currently it's not possible as far as I'm aware of to use `cargo-features` in `$CARGO_HOME/config.toml`, even when using a nightly build. Am I missing something?

**Comment by weihanglo** [comment] 2023-01-08 19:01
AFAIK, that is intentional. `cargo-features` is for enabling `Cargo.toml` extensions for a certain `Cargo.toml`, whereas a `config.toml` is more like an environment setting. This is documented in ["Unstable Features"](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html) chapter in The Cargo Book.

I'd like to know which feature you want to use but is blocked. Having a more specific example may help. Thank you.

**Comment by Flippette** [comment] 2023-01-09 15:10
I wanted to do something similar to this:

```toml
cargo-features = ["profile-rustflags", "codegen-backend"]

[profile.dev]
codegen-backend = "cranelift"

[profile.rel_local]
inherits = "release"
rustflags = ["-Ctarget-cpu=native"]
```

**Comment by weihanglo** [comment] 2023-01-10 14:21
My poor memomry! I found this is a duplicate of #9926. I'll close it in favor of that. We could have more discussions there. Thank you!

**Comment by weihanglo** [comment] 2023-01-10 22:05
Reopen this as the feature in #9926 has been stabilized. It is more clear to jot down notes on this issue.

Cargo team talked about this in today's meeting. The team decided not to have a general purpose way enabling features via configuration (`.cargo/config.toml`). Instead, we will enable `-Z` flag for an unstable Cargo syntax case by case.

For #11552 in `[profile]` Cargo should allow

- [`rustflags` option](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option), and
- [`codegen-backend` option](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#codegen-backend)

to be set via config.toml.

**Closed** 2023-01-14 14:34 UTC
Labels: A-configuration, C-feature-request, A-unstable
