### ISSUE TITLE
Please, consider making versioned cargo binary releases.

### ISSUE THREAD

**Issue by jauhien** [rust-lang/cargo#2258] opened 2016-01-01 22:32 UTC
It seems that only nightly binary releases are available for cargo now. Please, consider making versioned binary releases as well. That would simplify importing cargo package in some distros (e.g. in Gentoo we have no cargo source package now because of some issues with its build system and having upstream binary releases would be really helpfull, as we could directly package them).

**Comment by steveklabnik** [comment] 2016-01-01 23:18
We already pair cargo releases with Rust releases, so that would make natural sense.

**Comment by alexcrichton** [comment] 2016-01-11 19:08
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2109, so closing in favor of that. Thanks for the report though!

**Closed by alexcrichton** 2016-01-11 19:08 UTC
