### ISSUE TITLE
Conditional RUSTFLAGS in .cargo/config?

### ISSUE THREAD

**Issue by jerryc05** [rust-lang/cargo#8768] opened 2020-10-11 06:46 UTC
**Describe the problem you are trying to solve**

I know that there is a `[build]` section in `.cargo/config` file that accepts `rustflags`, but the problem is, it is effective **all the time**.

I would like to use some `rustflags` **ONLY** under several profiles separately. For example, it would be best if there exists something equivalent to:
```
[build.dev]
rustflags = [
    "-Ctarget-cpu=native",
    # some other flags
]
```

Note that I only want those flags under RELEASE builds, and they shall have no effect under DEV builds.

**Describe the solution you'd like**

Probably a `[build.dev]` section?

**Notes**

**Comment by jerryc05** [comment] 2020-10-11 08:14
Oops, just found a possible dup of this issue #7878 . Anyway, are we making progress on this feature request?

**Comment by ehuss** [comment] 2020-10-20 20:03
Closing as a duplicate of #7878.

**Closed by ehuss** 2020-10-20 20:03 UTC
Labels: C-feature-request
