### ISSUE TITLE
Cargo should not run git gc manually

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#8195] opened 2020-05-02 21:15 UTC
Saw this on twitter:
https://twitter.com/indygreg/status/1256656752944111616
and it turns out
a) cargo is checking how many packs there are on its own
b) if there are too many, it runs git gc, which is blocking.

There is a git command to do both of that automatically, with b) being done in the background, not blocking anything else: `git gc --auto`. The `maybe_gc_repo` function should just call that unconditionally. This also has the advantage of respecting the various gc.* git config items, instead of a manual __CARGO_PACKFILE_LIMIT.

**Comment by matthiaskrgr** [comment] 2020-05-03 17:21
Duplicate of https://github.com/rust-lang/cargo/issues/4495 ?

**Comment by epage** [comment] 2023-11-04 01:58
Closing in favor of #4495 so we consolidate the conversation on this.

**Closed by epage** 2023-11-04 01:58 UTC
Labels: A-git, C-feature-request
