### ISSUE TITLE
`cargo fix` does not fix documentation lints

### ISSUE THREAD

**Issue by Flying-Toast** [rust-lang/cargo#12304] opened 2023-06-22 23:57 UTC
### Problem

rustfix-able lints generated by `cargo doc` are not applied when running the `cargo fix` command suggested by the lint.

### Steps

1. `cargo new --lib hello`
2. Contents of `src/lib.rs`:
```rust
/// https://example.com
pub fn foo() -> i32 {
    12
}
```
3. `cargo doc`, output:
```
warning: this URL is not a hyperlink
 --> src/lib.rs:1:5
  |
1 | /// https://example.com
  |     ^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://example.com>`
  |
  = note: bare URLs are not automatically turned into clickable links
  = note: `#[warn(rustdoc::bare_urls)]` on by default

warning: `hello` (lib doc) generated 1 warning (run `cargo fix --lib -p hello` to apply 1 suggestion)
```
4. `cargo fix --lib -p hello` (the command hinted by the lint)
5. Note that no fixes are applied

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-unknown-linux-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
os: Fedora 38 (ThirtyEight) [64-bit]
```

**Comment by weihanglo** [comment] 2023-06-23 00:08
Thanks for reporting this.

It seems to be a duplicate of <https://github.com/rust-lang/cargo/issues/12277>. Close in favor of that.

**Closed** 2023-06-23 00:08 UTC
Labels: C-bug, S-triage
