### ISSUE TITLE
Fails to build with `--frozen` although cache and `Cargo.lock` is up-to-date

### ISSUE THREAD

**Issue by orhun** [rust-lang/cargo#12543] opened 2023-08-23 11:52 UTC
### Problem

I'm unable to build with `--frozen` flag although the dependencies are up-to-date for the [`bob`](https://github.com/MordechaiHadad/bob) project.

cc @MordechaiHadad (the author)

Also reported here: https://github.com/MordechaiHadad/bob/issues/153

### Steps

1. `git clone https://github.com/MordechaiHadad/bob && cd bob/`
2. `cargo fetch --locked --target "x86_64-unknown-linux-gnu"`
3. `cargo build --release --frozen`

```
thread 'main' panicked at 'packages downloaded: failed to download `flate2 v1.0.27`

Caused by:
    attempting to make an HTTP request, but --frozen was specified', src/cargo/ops/cargo_compile/mod.rs:910:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Possible Solution(s)

If you remove the `--frozen` flag, build once and repeat the process, then it works magically.

### Notes

I don't know this is an error specific to the `bob` project but it is reproducible so I thought it would be better to report this to `cargo` directly.

Another thing to note, this is not a `flate2` specific error since I got errors related to other crates as well:

```
thread 'main' panicked at 'packages downloaded: failed to download `tar v0.4.40`

Caused by:
    attempting to make an HTTP request, but --frozen was specified', src/cargo/ops/cargo_compile/mod.rs:908:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version

```text
cargo 1.72.0-nightly (5b377cece 2023-06-30)
release: 1.72.0-nightly
commit-hash: 5b377cece0e0dd0af686cf53ce4637d5d85c2a10
commit-date: 2023-06-30
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Arch Linux Rolling Release [64-bit]
```

**Comment by MordechaiHadad** [comment] 2023-08-23 12:00
To add to this:
This also fails on `cargo 1.65.0 (4bc8f24d3 2022-10-20)` on Arch Linux
But runs successfully when running the same commands(changing to (`"x86_64-pc-windows-msvc"`)

Dont have any info on this regarding other linux distros or macOS

**Comment by weihanglo** [comment] 2023-08-23 12:02
Could you also try running `cargo build` with `--target "x86_64-unknown-linux-gnu"`?

**Comment by orhun** [comment] 2023-08-23 12:04
Running `cargo build --target "x86_64-unknown-linux-gnu"` works just fine for me.

**Comment by MordechaiHadad** [comment] 2023-08-23 16:07
I dunno why this works on windows without any issue.

**Comment by weihanglo** [comment] 2023-08-23 16:17
Sorry I was on my phone. Now it looks like having the same root cause as <https://github.com/rust-lang/cargo/issues/11352>.

**Comment by orhun** [comment] 2023-08-23 16:39
You are right, `flate2` is a MacOS dependency defined here: https://github.com/MordechaiHadad/bob/blob/master/Cargo.toml#L79

But it is being downloaded during build on Linux:

```
thread 'main' panicked at 'packages downloaded: failed to download `flate2 v1.0.27`
```

**Comment by MordechaiHadad** [comment] 2023-08-23 16:40
yeah exactly and winreg is a windows dependency

**Comment by orhun** [comment] 2023-08-23 16:41
So is there a workaround/fix for this issue? @weihanglo

**Comment by weihanglo** [comment] 2023-08-23 16:47
I guess no. #11352 is still open. The only workaround I am aware of is avoiding platform filtering when running `cargo fetch`.

I'll close this and let's discuss in #11352. Thank you for the report anyway!

**Closed by weihanglo** 2023-08-23 16:47 UTC
Labels: C-bug, S-triage
