### ISSUE TITLE
Error when trying to re-build examples

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/cargo#1144] opened 2015-01-10 01:44 UTC
To make the error, follow the steps described [here](https://github.com/GuillaumeGomez/cargo-issue/blob/master/README.md). Then you should get a message like:

```Shell
no package named `rtest` found (required by `rtest-examples`)
location searched: file:///home/imperio/rust/cargo-issue/example
version required: = 0.9.11
```

Don't hesitate to ask if you have any question !

**Comment by huonw** [comment] 2015-01-10 11:51
Closing as a dupe of #1145, as discussed there. Thanks for filing nonetheless!

**Closed by huonw** 2015-01-10 11:51 UTC
