### ISSUE TITLE
Cargo fails when git is configured to use SSH for github.com

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/cargo#3900] opened 2017-04-05 18:30 UTC
Trying to build a Rust program on [Circle CI](https://circleci.com/):

```
cargo test -v
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: spurious network error (2 tries remaining): [12/-12] Malformed URL 'ssh://git@github.com:/rust-lang/crates.io-index'
warning: spurious network error (1 tries remaining): [12/-12] Malformed URL 'ssh://git@github.com:/rust-lang/crates.io-index'
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [12/-12] Malformed URL 'ssh://git@github.com:/rust-lang/crates.io-index'

cargo test -v returned exit code 101
```

I'd never seen this error before, but I found this blog post (not English, but you can get the gist): https://andelf.github.io/blog/2016/11/18/circleci-meets-rust/

In case that link 404s, the issue is that Circle CI has something in ~/.gitconfig that configures Git to use the SSH protocol for connections to github.com. The workaround recommended in the blog post is to use sed in a previous build step to make the line a no-op:

```
sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig
```

Is there something Cargo can do to mitigate this?

This is the closest Cargo issue I could find is https://github.com/rust-lang/cargo/issues/2845. Not sure if it's related.

**Comment by alexcrichton** [comment] 2017-04-05 23:53
Historically issues with Circle CI and Rust have boiled down to https://github.com/rust-lang/cargo/issues/1851, so maybe this is just a dupe of that?

**Comment by est31** [comment] 2017-04-10 04:11
I'm not really sure, but it seems that this is more of a libgit2 issue than a cargo issue. 

The relevant cargo code seems to be [this](https://github.com/rust-lang/cargo/blob/a5a298f1fd5b5ccf03ccb71c0cb6b97867e26d18/src/cargo/sources/registry/remote.rs#L72-L104). From the output we see that the url it talks about is the https one. 

[In the fetch call](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/utils.rs#L549-L573), the url is not changed, but given directly to the git2 crate, which is only a wrapper over libgit2.

Also, while the string "Malformed URL" doesn't appear in the cargo codebase, [it does in the libgit2 one](https://github.com/libgit2/libgit2/search?q=malformed+url&type=Code).

AFAIK it is possible to compile libgit2 without ssh support. Maybe that's what Circle CI has done, and now libgit2 considers the ssh url as malformed?

**Comment by est31** [comment] 2017-04-10 04:19
Yup, I can't reproduce.

I've added this to `.gitconfig` (like described in #2845):

```
[url "git@github.com:"]
    insteadOf = https://github.com/
```

and doing `cargo build` I got:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `git2`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

To learn more, run the command again with --verbose.

```

This is not the error message from above.
Then, after `ssh-add`ing my key, I did `cargo build` again, and it worked. So its very likely that circleCI's copy of libgit2 doesn't have ssh support.

**Comment by alexcrichton** [comment] 2017-04-10 14:04
Cargo statically links libgit2 so this may not be related to the version on Circle CI I think? My guess is it's the colon after `github.com` in the URL, that's invalid but I'm not sure where it's coming from.

**Comment by est31** [comment] 2017-04-10 14:34
>My guess is it's the colon after github.com in the URL, that's invalid but I'm not sure where it's coming from.

Yup seems you are right with your guess. According to [this post](https://discuss.circleci.com/t/is-it-ok-for-me-to-delete-gitconfig-in-the-box/5566) (apparently by a person with the same issue), the gitconfig looks like:

```
[url "ssh://git@github.com:"]
        insteadOf = https://github.com
```

Note the missing `/` in comparison to the gitconfig entry I had above. Setting it makes me reproduce the issue. Git cloning it works out of some weird reason though, this is why I earlier thought the URL was valid.

**Comment by alexcrichton** [comment] 2017-04-10 15:59
@est31 oh interesting! Can you clarify the behavior of with-and-without-trailing slash? With it you're getting https://github.com/rust-lang/cargo/issues/2845? (circleci doesn't use ssh-agent, we don't parse ~/.ssh/config for keys on the filesystem). Without it you get the error in the OP?

**Comment by est31** [comment] 2017-04-10 16:24
> Can you clarify the behavior of with-and-without-trailing slash?

This comment describes the behaviour for me with `insteadOf = https://github.com/`, generating an url `ssh://git@github.com:rust-lang/crates.io-index`: https://github.com/rust-lang/cargo/issues/3900#issuecomment-292846424

The behaviour for me with `insteadOf = https://github.com`, generating an url `ssh://git@github.com:/rust-lang/crates.io-index` is consistent with what @jimmycuadra reported.

I never got #2845.

**Comment by alexcrichton** [comment] 2017-08-28 14:29
I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/2078 as I believe that's the root cause here.

**Closed by alexcrichton** 2017-08-28 14:29 UTC
