### ISSUE TITLE
Cargo patch ignores gitlab ssh urls 

### ISSUE THREAD

**Issue by natekc** [rust-lang/cargo#10467] opened 2022-03-08 21:25 UTC
### Problem

Cargo ignores gitlab patch URLs (Ex. `ssh://git@gitlab.xyz.com:2222/project/repo.git`) in the cargo home config. 

### Steps

1. In the project Cargo.toml, add a dependency with a git repo source, such as 
```toml
mydep = { git = "ssh://git@gitlab.xyz.com:2222/project/repo.git"  }
```
2. In $CARGO_HOME/config, add the following patch section
```toml
[patch."ssh://git@gitlab.xyz.com:2222/project/repo.git"]
mydep = { path = "mydep" }
```
3. Run any cargo command
```bash
cargo update
```
4. Cargo uses git URL instead of patch path.

### Possible Solution(s)

If extra slashes are added to the gitlab URL (Ex. `ssh://git@gitlab.xyz.com:2222/project///repo.git`), the patch URL is recognized and cargo patches the original source as expected.

### Version

```text
1.58.1
```

**Comment by weihanglo** [comment] 2022-03-26 13:24
I am sorry you encountered that. I've tested on public GitLab and it works for me. Do you use a self-hosted GitLab? 


[This comment] contains some tips to help debug. The most relevant one is setting the environment variable `CARGO_LOG=trace`. Can you re-run the command and post logs here? Something like

```console
$ CARGO_LOG=trace cargo build
[2022-03-26T13:22:11Z DEBUG cargo::core::registry] registering a patch for `ssh://git@gitlab.com/weihanglo/cargo.git` with `cargo`
[2022-03-26T13:22:11Z DEBUG cargo::core::registry] load/missing  /home/weihanglo/projects/git-issue/cargo
[2022-03-26T13:22:11Z DEBUG cargo::core::registry] loading source /home/weihanglo/projects/git-issue/cargo
...
...
```

Also, it would be better if you can provide the full version info from the output of `cargo -vV`.

[This comment]: https://github.com/rust-lang/cargo/issues/10230#issuecomment-1000942704

**Comment by DevelAngel** [comment] 2022-03-29 10:48
I can confirm this issue. My cargo version (installed via rustup):
```
cargo 1.58.0 (7f08ace4f 2021-11-24)
release: 1.58.0
commit-hash: 7f08ace4f1305de7f3b1b0e2f765911957226bd4
commit-date: 2021-11-24
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Debian 10 (buster) [64-bit]
```

Workaround:
Single quotes for the git repo path seems to work well. Can anyone confirm that single quotes are working for you, too?

```
mydep = { git = 'ssh://git@gitlab.xyz.com:2222/project/repo.git'  }
```
```
[patch.'ssh://git@gitlab.xyz.com:2222/project/repo.git']
mydep = { path = "mydep" }
```

The main difference between https and ssh paths is that `@` is very often used in ssh paths. Thus, I would expect that this behavior could be reproduced with https-urls including `@` as well.

Most languages, including bash, make a difference between string literals with single quotes and double quotes.

If it is not a bug, it should be documented in [Specifying dependencies from git repositories](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) to prevent this trap.

**Comment by ehuss** [comment] 2022-04-08 20:21
There shouldn't be a difference between single and double quotes in this case.  The format for strings is documented [here](https://toml.io/en/v1.0.0#string). The main difference is that single-quotes are raw and don't interpret backslashes, but this isn't using backslashes.  Would you be able to put together a minimal example, and the exact steps taken, and what exactly didn't seem to work as expected?

**Comment by AdamLeyshon** [comment] 2023-05-11 09:17
It's not just GitLab URLs but any SSH dependency as far as I can tell.

I created MRE repo: https://github.com/AdamLeyshon/cargo-mre-10467

Tested with Cargo:
    
    # cargo -Vv
    release: 1.69.0
    commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
    commit-date: 2023-04-12
    host: x86_64-unknown-linux-gnu
    libgit2: 1.5.0 (sys:0.16.0 vendored)
    libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
    os: Manjaro 22.1.1 (Talos) [64-bit]

Git version is 
    
    # git -v
    git version 2.40.1

My `~/.gitconfig` file:

    # cat ~/.gitconfig 
    [user]
    name = Adam Leyshon
    email = aleyshon@thecodecache.net

The output from `RUST_LOG=trace cargo build`

```
  [2023-05-11T09:08:52Z DEBUG cargo::core::registry] locking patch Summary { inner: Inner { package_id: PackageId { name: "example-lib", version: "0.1.0", source: "/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-lib" }, dependencies: [], features: {}, checksum: None, links: None } }
  [2023-05-11T09:08:52Z TRACE cargo::core::registry] locking summary of example-lib v0.1.0 (/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-lib)
  [2023-05-11T09:08:52Z DEBUG cargo::core::registry] load/locked   /home/aleyshon/source/tcc-src/cargo-ssh-mre/example-bin
  [2023-05-11T09:08:52Z DEBUG cargo::core::registry] load/locked   /home/aleyshon/source/tcc-src/cargo-ssh-mre/example-lib
  [2023-05-11T09:08:52Z TRACE cargo::core::registry] locking summary of example-bin v0.1.0 (/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-bin)
  [2023-05-11T09:08:52Z TRACE cargo::core::registry]      example-lib/*/ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git
  [2023-05-11T09:08:52Z TRACE cargo::core::registry]      nope, unlocked
  [2023-05-11T09:08:52Z TRACE cargo::core::registry] locking summary of example-lib v0.1.0 (/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-lib)
  [2023-05-11T09:08:52Z DEBUG cargo::core::resolver] initial activation: example-bin v0.1.0 (/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-bin)
  [2023-05-11T09:08:52Z TRACE cargo::core::resolver] activating example-bin v0.1.0 (/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-bin)
  [2023-05-11T09:08:52Z DEBUG cargo::core::registry] found 1 patches with an unlocked dep on `example-lib` at ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git with `*`, looking at sources
  [2023-05-11T09:08:52Z DEBUG cargo::core::registry] load/missing  ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git
  [2023-05-11T09:08:52Z DEBUG cargo::core::registry] loading source ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git
  [2023-05-11T09:08:52Z DEBUG cargo::sources::config] loading: ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git
  [2023-05-11T09:08:52Z TRACE cargo::core::source::source_id] loading SourceId; ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git
  Updating git repository `ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git`
```

Which finishes with

```
    Updating git repository `ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git`
    error: failed to get `example-lib` as a dependency of package `example-bin v0.1.0 (/home/aleyshon/source/tcc-src/cargo-ssh-mre/example-bin)`
    
    Caused by:
    failed to load source for dependency `example-lib`
    
    Caused by:
    Unable to update ssh://git@github.com/AdamLeyshon/cargo-mre-10467.git
    
    Caused by:
    failed to fetch into: /home/aleyshon/.cargo/git/db/cargo-mre-10467-cd8c94d9cdb533f4
    
    Caused by:
    failed to authenticate when downloading repository
    
    * attempted ssh-agent authentication, but no usernames succeeded: `git`
    
    if the git CLI succeeds then `net.git-fetch-with-cli` may help here
    https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
    
    Caused by:
    error authenticating: no auth sock variable; class=Ssh (23)
```

I hope this helps

**Comment by ehuss** [comment] 2024-05-06 19:13
@AdamLeyshon Even when a git dependency is patched, it still needs to be downloaded to know what is being patched. I don't think that is the same as the original report, which said that the patch wasn't working at all.

Without more information I don't think we can help here, so closing. If more information is available, please let us know.

**Closed by ehuss** 2024-05-06 19:13 UTC
Labels: C-bug, S-needs-info
