### ISSUE TITLE
Cargo Workspace Provided build scripts ROOT Directory

### ISSUE THREAD

**Issue by mtthw-meyer** [rust-lang/cargo#7036] opened 2019-06-14 19:31 UTC
I'm trying to write a build script that uses a shared configuration in the workspace. In this case I'm playing with cbindgen and want a global base configuration to share between crates.

I think it would be useful for workspace build script to be provided an environment variable that has the path to the workspace root directory.

**Comment by ehuss** [comment] 2020-03-05 19:02
Closing as a duplicate of #3946.

**Closed by ehuss** 2020-03-05 19:02 UTC
Labels: A-build-scripts, A-workspaces, C-feature-request
