### ISSUE TITLE
Cargo not picking up paths option (?)

### ISSUE THREAD

**Issue by djc** [rust-lang/cargo#2762] opened 2016-06-02 09:34 UTC
```
djc@dochtman-dev servo $ cat ~/.cargo/config
paths = ["/home/djc/src/devices"]

djc@dochtman-dev servo $ cat ~/src/devices/Cargo.toml
[package]
name = "device"
version = "0.0.1"
authors = ["The Servo Project Developers"]

[features]
default = ["bluetooth"]
bluetooth = ["blurz"]

[target.'cfg(target_os = "linux")'.dependencies]
blurz = { version = "0.1.7", optional = true }

djc@dochtman-dev servo $ ./mach build --dev
error: Package `device v0.0.1
(https://github.com/servo/devices#cac09521)` does not have these
features: `bluetooth`
Build completed in 0:00:01

djc@dochtman-dev devices $ cd ~/src/devices/

djc@dochtman-dev devices $ git diff Cargo.toml 
diff --git a/Cargo.toml b/Cargo.toml
index ea1c9a5..897d5f9 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -3,5 +3,9 @@ name = "device"
 version = "0.0.1"
 authors = ["The Servo Project Developers"]

+[features]
+default = ["bluetooth"]
+bluetooth = ["blurz"]
+
 [target.'cfg(target_os = "linux")'.dependencies]
-blurz = "0.1.7"
+blurz = { version = "0.1.7", optional = true }

djc@dochtman-dev devices $ cargo -V
cargo 0.11.0-nightly (3ff108a 2016-05-24)
```

**Comment by Manishearth** [comment] 2016-06-02 09:41
What's important to note is:

> error: Package `device v0.0.1
> (https://github.com/servo/devices#cac09521)` does not have these
> features: `bluetooth`

where it still has the GH url instead of the path.

**Comment by alexcrichton** [comment] 2016-06-02 13:21
Ah yeah unfortunately this is a feature of path overrides that won't work. The resolution graph is computed before path overrides are applied and features are part of resolution (as they introduce new dependencies).

Certainly seems like something we could give a better error for though!

**Comment by djc** [comment] 2016-06-03 17:53
Why are path overrides computed before path overrides? I'm not sure it makes sense to me.

**Comment by ehuss** [comment] 2020-06-07 23:14
Closing as a duplicate of #2582.

**Closed by ehuss** 2020-06-07 23:14 UTC
Labels: A-errors
