### ISSUE TITLE
Duplicate commands in Cargo

### ISSUE THREAD

**Issue by GilShoshan94** [rust-lang/cargo#9755] opened 2021-08-02 15:09 UTC
Hi,

**Problem**

When using the command `cargo --list` to list the installed commands, I am receiving duplicate commands, specifically I get listed twice `clippy` and twice `fmt`.
See screenshot below:
![image](https://user-images.githubusercontent.com/29143941/127881434-60d25b40-a987-4cfa-8dfc-529fe348eada.png)

It doesn't seem normal to me, but I have to admit that I am very new to Rust and its tooling.
Is it normal? 

**Steps**

1. Follow [the installation (I did it on Windows 10) process according to the Book](https://doc.rust-lang.org/book/ch01-01-installation.html#installing-rustup-on-windows).
2. Having finished the Book, I did ran `rustup component add rustfmt` [as suggested](https://doc.rust-lang.org/book/appendix-04-useful-development-tools.html#automatic-formatting-with-rustfmt), and also `rustup component add clippy`, also [as suggested ](https://doc.rust-lang.org/book/appendix-04-useful-development-tools.html#more-lints-with-clippy). (To my recent understanding, this is not necessary anymore because they both comes bundled with the default rustup installation, anyway )
3. Run `cargo --list`.

**Notes**
I am very new to Rust (just finished to read the whole book `The Rust Programming Language`).

Output of `cargo version`:
cargo 1.54.0 (5ae8d74b3 2021-06-22)

I ran again `rustup component add clippy`, I am getting this output:
`info: component 'clippy' for target 'x86_64-pc-windows-msvc' is up to date`

I ran again `rustup component add rustfmt`, I am getting this output:
`info: component 'rustfmt' for target 'x86_64-pc-windows-msvc' is up to date`

And it did not alter the output of `cargo --list`.

**Comment by ehuss** [comment] 2021-08-02 15:45
Thanks for the report!  I'm going to close this as a duplicate of #6088 as it is a known issue.

**Closed by ehuss** 2021-08-02 15:45 UTC
Labels: C-bug

**Comment by GilShoshan94** [comment] 2021-08-02 15:47
Thank you. 
I searched first for a similar issue but didn't find it. 
Sorry for the duplicate issue. 

Have a nice day.
