### ISSUE TITLE
Changing workspace Cargo.toml doesn't invalidate build cache for workspace members

### ISSUE THREAD

**Issue by illicitonion** [rust-lang/cargo#14154] opened 2024-06-26 12:30 UTC
### Problem

[The environment variables Cargo sets when building crates](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) don't appear to get updated if the crate's Cargo.toml inherits values from the workspace, and the only change between builds is the value in the workspace's Cargo.toml.

### Steps

```console
% cat >Cargo.toml <<EOF
[workspace]
members = ["lib"]
package.version = "0.2.0"
package.readme = "beep.md"
EOF
% mkdir -p lib/src
% cat >lib/Cargo.toml <<EOF
[package]
name = "lib"
version = "0.1.0"
edition = "2021"
readme = { workspace = true }
EOF
% cat >lib/src/main.rs <<EOF
fn main() {
    println!("Readme: {}", env!("CARGO_PKG_README"));
}
EOF
% cargo run -p lib 2>/dev/null
Readme: ../beep.md
% cat >Cargo.toml <<EOF
[workspace]
members = ["lib"]
package.version = "0.2.0"
package.readme = true
EOF
% # Next command should print ../README.md because the workspace value changed:
% cargo run -p lib 2>/dev/null
Readme: ../beep.md
% # Clearing the cache forces a rebuild, which gives the correct value:
% rm -rf target
% cargo run -p lib 2>/dev/null
Readme: ../README.md
```

### Version

```text
cargo 1.79.0 (ffa9cf99a 2024-06-03)
release: 1.79.0
commit-hash: ffa9cf99a594e59032757403d4c780b46dc2c43a
commit-date: 2024-06-03
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.1.2 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 13.5.2 [64-bit]
```

**Comment by epage** [comment] 2024-06-26 13:31
Just reproduced this without workspace inheritance involved.

**Comment by epage** [comment] 2024-06-26 13:39
Not seeing an existing issue for cargo-generated env variables but this seems similar in internals to #13280 and #10358.

**Comment by weihanglo** [comment] 2024-10-09 04:02
Actually this doesn't need workspace to involve. Simply with a single package change `package.readme = "foo"` to `package.readme = "bar"`, and observe it doesn't rebuild.

I believe the bug shares the same root cause from <https://github.com/rust-lang/cargo/issues/13280#issuecomment-1887225691>, where `CARGO_PKG_README` was removed.

**Comment by weihanglo** [comment] 2024-10-09 04:05
I'll go ahead a close this in favor of #13280. Thanks for the report and reproduction!

**Comment by weihanglo** [comment] 2024-10-17 13:39
Reopen since #13280 could have a partial fix not covering internal environment variables like `CARGO_PKG_README`.

**Closed** 2024-12-24 14:41 UTC
Labels: C-bug, A-rebuild-detection, A-environment-variables, S-accepted, A-dep-info
