### ISSUE TITLE
Build is always executed if mtimes are missing

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4425] opened 2017-08-23 13:06 UTC
Today a user handled me a `rar` archive (from a windows machine) with a Cargo package. When I extracted it on my linux machine, I've noticed that `cargo build` always rebuilds the project, instead of doing zero builds. Looks like the problem is that extracted files miss `mtime`s, so we always rebulid in here:

https://github.com/rust-lang/cargo/blob/f46d485b8d149b06aeab62b207e9a8f2c1015aea/src/cargo/ops/cargo_rustc/fingerprint.rs#L250-L252

Seems like a niche use case, and I am not sure how to fix it properly (touching files seems inappropriate?), but lets log the issue anyways!

**Comment by alexcrichton** [comment] 2017-08-23 14:07
Hm I'm not actually sure how an mtime can be missing... Did the archive include the `target` directory with fingerprints?

**Comment by matklad** [comment] 2017-08-23 14:31
Hm, that's super weird. I've tried to reproduce it now, and I can't =/ I would say it was a hallucination, if not for the fact that I happen to have one of terminal tabs with experiments laying around, which clearly shows rebuild happening: https://gist.github.com/matklad/0fe6554ecf473b3af9e511e197921614

>Did the archive include the target directory with fingerprints?

Yeah, but I think I've tried removing the target directory, and rebuilds still happened, but given that I can't reproduce even the original issue, I am not sure in anything now...

**Comment by eminence** [comment] 2022-11-23 04:06
Triage:  This issue is quite old, and seemingly hard to reproduce.  There's a lot of discussion (some even recent!) in #6529 about moving away from mtimes and to try things like checking hashes.

Given this issue here doesn't seem particularly actionable, it probably makes the most sense to just close it.

**Comment by ehuss** [comment] 2022-11-23 05:31
Yea, without a clear reproduction this probably isn't actionable.
Also, the fingerprint code has changed a lot since this was written, and it may be possible that it no longer behaves the same.

**Closed by ehuss** 2022-11-23 05:31 UTC
Labels: C-bug, A-rebuild-detection
