### ISSUE TITLE
Don't display error messages multiple times when building test crates

### ISSUE THREAD

**Issue by euclio** [rust-lang/cargo#3128] opened 2016-09-28 14:37 UTC
When using `cargo test`, compiler errors may be displayed multiple times if there is an error in the main crate. This is because test crates are built in parallel.

It's distracting to see the same error reported multiple times.

**Comment by alexcrichton** [comment] 2016-09-28 18:27
Thanks for the report! What's actually happening here is that the library is being compiled twice (once with `--test` and once for doc tests later on), and this is a dupe of https://github.com/rust-lang/cargo/issues/1534 and https://github.com/rust-lang/cargo/issues/851 (now tracked at https://github.com/rust-lang/cargo/issues/1198). This is intended behavior though, and you can use various flags like `--test`, `--lib`, or `-j` to not run `rustc` in parallel, so I'm going to close this.

**Closed by alexcrichton** 2016-09-28 18:27 UTC
