### ISSUE TITLE
Can't run fetch/build on dependencies only

### ISSUE THREAD

**Issue by sedrik** [rust-lang/cargo#5098] opened 2018-02-28 11:03 UTC
Cargo requires a src/main.rs or src/lib.rs to be able to fetch and build dependencies for a project. This makes it less than ideal to use in a Dockerfile.

I tried this:
This dockerfile currently does not work with cargo (assuming you stand in a rust project).
```Dockerfile
FROM rust
COPY Cargo.toml .
COPY Cargo.lock .
RUN cargo fetch # or RUN cargo build
```

I expected to see this happen: Cargo should be able to perform the actions for the dependencies only to allow us to utilize the docker build cache.

Instead, this happened: I get the following error about main.rs (or lib.rs for libs) missing.

```
error: failed to parse manifest at `/home/rust/Cargo.toml`
Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

I'm using cargo 0.26.0-nightly (1d6dfea44 2018-01-26) but I believe this is a feature that is missing.

You can work around this issue by adding a very basic main.rs file to your dockerfile.

```Dockerfile
FROM rust
COPY Cargo.toml .
COPY Cargo.lock .
RUN echo "fn main() {}" > src/main.rs
RUN cargo build

# It seems like docker COPY instruction does not update the modified time of
# the files so unless we touch our real src/main.rs it will use the cached
# version of our dummy program
COPY . .
RUN sudo touch src/main.rs
```

It would be nice if we could add a flag to instruct cargo that we expect to only work on the dependencies for the project.

Sorry if this has been reported earlier.

**Comment by alexcrichton** [comment] 2018-02-28 15:43
I think this is a dupe of https://github.com/rust-lang/cargo/issues/2644 so I"m going to close in favor of that.

**Closed by alexcrichton** 2018-02-28 15:43 UTC
