### ISSUE TITLE
Index at github.com-1ecc6299db9ec823 isn't updated

### ISSUE THREAD

**Issue by missingdays** [rust-lang/cargo#12523] opened 2023-08-18 10:22 UTC
### Problem

When updating the index, only `index.crates.io-6f17d22bba15001f` index is updated, but not `github.com-1ecc6299db9ec823`.

### Steps

1. Run any command that should update the index (e.g. `cargo update --dry-run `)
2. Check that `index.crates.io-6f17d22bba15001f` index is updated
3. Check that `github.com-1ecc6299db9ec823` index **isn't** updated

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-pc-windows-msvc
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Home Single Language) [64-bit]
```

**Comment by weihanglo** [comment] 2023-08-18 12:25
This is expected and exactly the purpose sparse registry index was designed for — skipping the update of Git-based registry index. Cargo updates only the registry index for the default protocol of your choice. By default it is [the `sparse` protocol since 1.68](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html). 

Is there any issue you encountered with this behavior?

**Comment by missingdays** [comment] 2023-08-18 14:24
@weihanglo thank you for your answer
As discussed in https://github.com/rust-lang/cargo/issues/3377, this index is used in various tools (intellij-rust in my case) to gather information about the crates. I've noticed that the `github` index stopped updating, and it was causing problems for us, for example https://github.com/intellij-rust/intellij-rust/issues/10644
I'll try setting the github index as default one, thank you!

**Comment by weihanglo** [comment] 2023-08-18 23:29
I am not sure what it wasn't reported earlier, since sparse registry was in beta for a long while, and got stabilized in March this year. For intellij-rust perhaps some bugs were introduced in recent. 

Anyway, here is a workaround to forced update the Git-based registry index: `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=git cargo fetch`

Closing in favor of other prior issues:

* #3377
* #10928
* #11034

Thank you for the report!

**Closed by weihanglo** 2023-08-18 23:29 UTC
Labels: C-bug, S-needs-info

**Comment by Coolebrelittletakis6** [comment] 2025-12-16 15:31
Help
