### ISSUE TITLE
Separate global cache/registry and bin/package management directories and files

### ISSUE THREAD

**Issue by Destroy666x** [rust-lang/cargo#12725] opened 2023-09-22 19:02 UTC
### Problem

Mixing these together is definitely not a great idea. It makes automated setups harder as they have to go for specific files/subdirs instead of just one directory, if you don't want to copy random package cache between machines. It also makes cleanup etc. harder and more confusing as can be seen by e.g. the advice here: https://github.com/rust-lang/cargo/issues/3289#issuecomment-260368352 (and the whole issue has been hanging on "needs input" status for few years now).

### Proposed Solution

Separate these directories and allow separate environment variables for them, e.g. `CARGO_HOME` and `CARGO_CACHE`.

Some examples from other package managers:
- npm/yarn: https://docs.npmjs.com/cli/v8/using-npm/config#cache
- PHP's Composer: https://getcomposer.org/doc/03-cli.md#composer-cache-dir
- C#'s NuGet: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

**Comment by epage** [comment] 2023-09-22 19:22
If I'm understanding correctly, this appears to be a duplicate of #1734

**Comment by Destroy666x** [comment] 2023-09-22 20:13
Not quite, it's a similar request which I also support, but it's related.

**Comment by epage** [comment] 2023-09-28 01:11
Solving this kind of problem needs to be done in the context of #1734, so I'm closing in favor of that.  We wouldn't want to design part way on this and realize there is a problem.  Granted, if we decide support for these variables is important, it'll likely be stable in one of the earliest stages of the effort.

**Closed by epage** 2023-09-28 01:11 UTC
Labels: C-feature-request, S-triage
