### ISSUE TITLE
cargo master fails to build with latest nightly

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#7594] opened 2019-11-15 20:23 UTC
**Problem**

`cargo +nightly test` fails

**Steps**

1. `cargo +nightly test`

This errors starting with:
```
$ cargo +nightly test                            
    Updating crates.io index
   Compiling cargo-test-macro v0.1.0 (/home/r/src/rust/cargo/crates/cargo-test-macro)
   Compiling syn v1.0.8
   Compiling clap v2.32.0
   Compiling serde_derive v1.0.70
   Compiling libnghttp2-sys v0.1.2
   Compiling backtrace-sys v0.1.23
   Compiling libssh2-sys v0.2.13
   Compiling flate2 v1.0.12
   Compiling openssl v0.10.11
error[E0432]: unresolved imports `crate::ffi::Deflate`, `crate::ffi::Inflate`
 --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.12/src/mem.rs:6:33
  |
6 | use crate::ffi::{self, Backend, Deflate, DeflateBackend, Inflate, InflateBackend};
  |                                 ^^^^^^^                  ^^^^^^^ no `Inflate` in `ffi`
  |                                 |
  |                                 no `Deflate` in `ffi`

error: cannot find macro `__cfg_if_items` in this scope
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.12/src/ffi/mod.rs:40:1
   |
40 | / cfg_if::cfg_if! {
41 | |     if #[cfg(target_arch = "wasm32")] {
42 | |         mod rust;
43 | |         pub use self::rust::*;
...  |
50 | |     }
51 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `uInt` in `ffi`
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.12/src/mem.rs:242:45
    |
242 |             assert!(dictionary.len() < ffi::uInt::max_value() as usize);
    |                                             ^^^^ could not find `uInt` in `ffi`
```

**Notes**

```
$ cargo +nightly version
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
$ rustc +nightly --version
rustc 1.41.0-nightly (82cf3a448 2019-11-14)
```

**Comment by ehuss** [comment] 2019-11-15 21:41
Hm, I can't seem to find a way to reproduce this. 

This: `cannot find macro `__cfg_if_items` in this scope`  seems really strange.

Can you maybe try to update your `Cargo.lock` and see if that helps?  It's almost like cfg_if/flate2/miniz-sys are maybe using a too-old version?

**Comment by RalfJung** [comment] 2019-11-15 22:01
Oh, I thought `Cargo.lock` would be version controlled... deleting that file fixes the problem.

Wouldn't it be better to have that file in git so that things are more reproducible?

**Comment by ehuss** [comment] 2019-11-15 22:29
> Wouldn't it be better to have that file in git so that things are more reproducible?

It is in a sense on rust-lang/rust.  That is the official lock file that Cargo is built with.  I wouldn't want to maintain and sync two different lock files. 

A solution might be to implement minimal versions for immediate dependencies, which can help catch situations like this.

**Comment by ehuss** [comment] 2019-11-27 04:27
I'm going to close this since it looks like it has been resolved, and I don't think we want to manage `Cargo.lock` in repo.

**Closed by ehuss** 2019-11-27 04:27 UTC
Labels: C-bug

**Comment by RalfJung** [comment] 2019-11-27 07:44
> and I don't think we want to manage Cargo.lock in repo.

Fair. I'll just throw in the remark that Miri and Clippy both *do* have a `Cargo.toml` in their repo, and for Miri this has saved us some pain and so far not caused pain. The file is indeed not synced with the one in the rustc repo, but just having a stable baseline for local development and CI *at all* is tremendously useful for us.

YMMV.
