### ISSUE TITLE
crates produced by cargo have errors in them

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#4712] opened 2017-11-12 01:46 UTC
Crates produced by any recent cargo (including the latest nightly) are compressed incorrectly. The `tar` compression is not correctly following the spec causing some decompressors to report errors and fail to get all the contents. 7-zip is one such decompressor which is having issues. It's really frustrating not being able to view the contents of crates.

![](https://i.imgur.com/nfXI7P2.png)

cc @alexcrichton

**Comment by est31** [comment] 2017-11-12 02:35
Easy to reproduce example:

```
wget https://crates.io/api/v1/crates/syntect/1.8.2/download
7z x download
7z l syntect-1.8.2.crate
```

You'll see only a partial listing, without any src directory.

**Comment by bluss** [comment] 2017-11-12 03:05
We can spot a hint in the tar output:

7z reads all the files before `Cargo.toml`, and that's the file that cargo rewrites when packaging, too

```
$ tar tfv syntect-1.8.2.crate 
-rw-r--r-- 501/20           29 2016-06-09 17:13 syntect-1.8.2/.gitattributes
-rw-r--r-- 501/20           18 2017-08-29 22:43 syntect-1.8.2/.gitignore
-rw-r--r-- 501/20          466 2017-07-06 03:16 syntect-1.8.2/.gitmodules
-rw-r--r-- 501/20         1283 2017-11-11 16:12 syntect-1.8.2/.travis.yml
-rw-r--r-- 501/20         5037 2017-11-11 16:12 syntect-1.8.2/assets/default.themedump
-rw-r--r-- 501/20       277415 2017-10-14 01:07 syntect-1.8.2/assets/default_newlines.packdump
-rw-r--r-- 501/20       277462 2017-10-14 01:07 syntect-1.8.2/assets/default_nonewlines.packdump
-rw-r--r-- 501/20         2295 2017-04-04 21:17 syntect-1.8.2/benches/highlighting.rs
-rw-r--r-- 501/20         1053 2016-06-27 21:24 syntect-1.8.2/benches/loading.rs
-rw-r--r-- 501/20         1470 2016-06-29 02:18 syntect-1.8.2/benches/parsing.rs
-rw-r--r-- 501/20         2195 2017-11-11 16:13 syntect-1.8.2/Cargo.toml.orig
-rw-r--r-- 0/0            2226 1970-01-01 01:00 syntect-1.8.2/Cargo.toml
-rw-r--r-- 501/20           72 2017-11-11 16:12 syntect-1.8.2/codecov.yml
-rw-r--r-- 501/20         5333 2016-06-29 04:05 syntect-1.8.2/DESIGN.md
-rw-r--r-- 501/20         1576 2017-04-04 21:17 syntect-1.8.2/examples/gendata.rs
-rw-r--r-- 501/20         2272 2017-07-06 03:16 syntect-1.8.2/examples/parsyncat.rs
-rw-r--r-- 501/20         3983 2017-09-05 21:54 syntect-1.8.2/examples/syncat.rs
-rw-r--r-- 501/20         1102 2017-10-14 01:07 syntect-1.8.2/examples/synhtml.rs
-rw-r--r-- 501/20         6027 2017-05-31 03:46 syntect-1.8.2/examples/synstats.rs
-rw-r--r-- 501/20        12524 2017-10-14 01:07 syntect-1.8.2/examples/syntest.rs
-rw-r--r-- 501/20         1116 2017-07-06 03:16 syntect-1.8.2/LICENSE.txt
-rw-r--r-- 501/20          720 2017-04-04 21:17 syntect-1.8.2/Makefile
-rw-r--r-- 501/20        15564 2017-11-11 16:12 syntect-1.8.2/Readme.md
-rw-r--r-- 501/20         3248 2016-06-27 21:24 syntect-1.8.2/scripts/id_rsa.enc
-rw-r--r-- 501/20         7711 2017-10-14 01:07 syntect-1.8.2/src/dumps.rs
-rw-r--r-- 501/20         9332 2017-10-14 01:07 syntect-1.8.2/src/easy.rs
-rw-r--r-- 501/20         1883 2017-10-14 01:07 syntect-1.8.2/src/escape.rs
-rw-r--r-- 501/20        12784 2017-10-14 01:07 syntect-1.8.2/src/highlighting/highlighter.rs
-rw-r--r-- 501/20          542 2016-06-27 21:24 syntect-1.8.2/src/highlighting/mod.rs
-rw-r--r-- 501/20          496 2016-06-27 21:24 syntect-1.8.2/src/highlighting/Readme.md
-rw-r--r-- 501/20        15992 2017-10-14 01:07 syntect-1.8.2/src/highlighting/selector.rs
-rw-r--r-- 501/20         1771 2017-05-25 16:31 syntect-1.8.2/src/highlighting/settings.rs
-rw-r--r-- 501/20         3442 2017-10-14 01:07 syntect-1.8.2/src/highlighting/style.rs
-rw-r--r-- 501/20        17079 2017-10-14 01:07 syntect-1.8.2/src/highlighting/theme.rs
-rw-r--r-- 501/20         2916 2017-10-14 01:07 syntect-1.8.2/src/highlighting/theme_set.rs
-rw-r--r-- 501/20        11988 2017-10-14 01:07 syntect-1.8.2/src/html.rs
-rw-r--r-- 501/20         3375 2017-11-11 16:13 syntect-1.8.2/src/lib.rs
-rw-r--r-- 501/20          670 2017-05-25 16:31 syntect-1.8.2/src/parsing/mod.rs
-rw-r--r-- 501/20        31059 2017-11-11 16:12 syntect-1.8.2/src/parsing/parser.rs
-rw-r--r-- 501/20        21616 2017-10-14 01:07 syntect-1.8.2/src/parsing/scope.rs
-rw-r--r-- 501/20        10832 2017-11-11 16:12 syntect-1.8.2/src/parsing/syntax_definition.rs
-rw-r--r-- 501/20        19454 2017-10-14 01:07 syntect-1.8.2/src/parsing/syntax_set.rs
-rw-r--r-- 501/20        25411 2017-10-14 01:07 syntect-1.8.2/src/parsing/yaml_load.rs
-rw-r--r-- 501/20         2114 2017-05-25 16:31 syntect-1.8.2/src/util.rs
```

**Comment by Arnavion** [comment] 2017-11-12 06:00
@bluss The output of the tar command is fine, but hides the underlying issue.

The issue is that cargo is writing the mtime of Cargo.toml as 11 NUL bytes (`0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00`) instead of ASCII (`0x30 0x30 0x30 0x30 0x30 0x30 0x30 0x30 0x30 0x30 0x30`), which 7-zip apparently doesn't like. GNU tar seems to treat both the same, which is why it doesn't have a problem showing it as the unix epoch like in your output.

Changing those 11 mtime bytes to `0x30` and modifying the checksum accordingly (`0o7556` -> `0o10576`) allows 7-zip to read the archive just fine.

**Comment by bluss** [comment] 2017-11-12 11:10
I didn't think it hides it, it does give a hint that the Cargo.toml was probably the one to break the archive.

**Comment by Arnavion** [comment] 2017-11-12 11:24
Even if the archive contained an mtime of 0 in the proper format (11x `0x30`), the `tar` output would look identical. I was saying that the fact that `tar` shows the Unix epoch and no errors for the file listing hides the fact that the mtime for that entry is actually bad (as far as 7-zip is concerned, atleast).

**Comment by nossralf** [comment] 2017-11-14 09:27
I haven't found an authoritative standards document for tar archives, but both the [GNU documentation](http://www.gnu.org/software/tar/manual/html_node/Standard.html) and an [Open Group document covering the ustar header format](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html#tag_20_92_13_06) concur that:

> The mtime field is the data modification time of the file at the time it was archived. It is the ASCII representation of the octal value of the last time the file's contents were modified, represented as an integer number of seconds since January 1, 1970, 00:00 Coordinated Universal Time.

(Open Group states "ISO/IEC 646:1991" instead of ASCII, but they are equivalent in this context.)

That GNU tar accepts null bytes for _mtime_ is probably Postel's law in action.

IMHO this implies tar-rs should be updated to use the correct format, instead of patching this in Cargo.

**Comment by alexcrichton** [comment] 2017-11-18 08:31
Thanks for the investigation @nossralf! Want to open an issue/PR against the `tar` crate?

**Comment by nossralf** [comment] 2017-11-18 08:39
Sure.

**Comment by nossralf** [comment] 2017-12-02 11:50
The tar-rs fix is in the Cargo nightly now. It seems to have missed the stable train since the released 0.23 version of Cargo still produces invalid tar files.

**Comment by Eh2406** [comment] 2018-03-26 15:38
move to close?

**Comment by alexcrichton** [comment] 2018-03-26 20:04
Indeed!

**Closed by alexcrichton** 2018-03-26 20:04 UTC
