### ISSUE TITLE
Race condition during compiling due to IDEs calling cargo

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/cargo#1646] opened 2015-05-23 11:05 UTC
This may be a duplicate of #1014, but I'm not seeing an internal compiler error.

Around 50% of the time, when running `cargo build` I get errors of the form:

```
$ cargo build
An unknown error occurred

To learn more, run the command again with --verbose.
```

Running `cargo build` again fixes the issue. If I use `-v` every time, I can get more information:

```
$ cargo build -v
...
error: could not copy "/home/wilfred/projects/linkdoc/target/debug/linkdoc.0.o" to "/home/wilfred/projects/linkdoc/target/debug/linkdoc.o": the source path is not an existing file
error: failed to remove /home/wilfred/projects/linkdoc/target/debug/linkdoc.0.o: No such file or directory (os error 2)
error: aborting due to 2 previous errors
Could not compile `linkdoc`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name linkdoc --crate-type bin -g --out-dir /home/wilfred/projects/linkdoc/target/debug --emit=dep-info,link -L dependency=/home/wilfred/projects/linkdoc/target/debug -L dependency=/home/wilfred/projects/linkdoc/target/debug/deps --extern hyper=/home/wilfred/projects/linkdoc/target/debug/deps/libhyper-7af3be4b39937ea7.rlib --extern html5ever_dom_sink=/home/wilfred/projects/linkdoc/target/debug/deps/libhtml5ever_dom_sink-607173334db3188e.rlib --extern url=/home/wilfred/projects/linkdoc/target/debug/deps/liburl-4df5ef82d37fdef0.rlib --extern html5ever=/home/wilfred/projects/linkdoc/target/debug/deps/libhtml5ever-6ea0d790b7d5e904.rlib -L native=/usr/lib -L native=/home/wilfred/projects/linkdoc/target/debug/build/openssl-sys-5040130ff99796a0/out -L native=/home/wilfred/projects/linkdoc/target/debug/build/time-e758cbe877e9589d/out` (exit code: 101)
```

I eventually realised that some Emacs plugins (including [flymake-rust](https://github.com/jxs/flymake-rust)) call `cargo build` to show compilation errors. If I happen to run `cargo build` at the same time as the plugin, I get an error.

This is rather confusing. Could Cargo be more defensive and refuse to run if there's another Cargo instance running on the current project?

**Comment by alexcrichton** [comment] 2015-05-26 14:41
Closing as a dupe of https://github.com/rust-lang/cargo/issues/354, but thanks!

**Closed by alexcrichton** 2015-05-26 14:41 UTC
