### ISSUE TITLE
All possible versions conflict with previously selected versions of...

### ISSUE THREAD

**Issue by disconsented** [rust-lang/cargo#4776] opened 2017-12-05 03:37 UTC
As per https://github.com/shepmaster/sxd-document/pull/53#issuecomment-349184896 I am reporting an issue where updating a crate results in
```bash
   Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `sxd-document` (required by `sxd-xpath`):
all possible versions conflict with previously selected versions of `sxd-document`
  version 0.2.5 in use by sxd-document v0.2.5
  possible versions to select: 0.2.4
```
[Cargo.lock and Cargo.toml](https://gist.github.com/disconsented/740912b8c7b2d3dd91770d0bea53d5e4)

This issue has been resolved, reporting it in case it is something that needs to be fixed in cargo.

**Comment by shepmaster** [comment] 2017-12-05 03:45
Running `cargo update -p sxd-document` did seem to solve the problem when I was using the provided `Cargo.toml` and `Cargo.lock` files.

**Comment by alexcrichton** [comment] 2017-12-05 15:00
I think this may be a dupe of https://github.com/rust-lang/cargo/issues/4127?

**Comment by alexcrichton** [comment] 2018-03-01 06:12
Closing in favor of https://github.com/rust-lang/cargo/issues/4127

**Closed by alexcrichton** 2018-03-01 06:12 UTC
