### ISSUE TITLE
Support for cargo update while behind proxy

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/cargo#1135] opened 2015-01-08 16:07 UTC
Does cargo support update when behind proxy?  

I tried 
    export ALL_PROXY=http://localhost:8098

 but  Cargo update  command hangs at 

    cargo update -v
        Updating registry `https://github.com/rust-lang/crates.io-index`

Looking at the source, it seem to be using curl which does support ALL_PROXY.  Not sure rust module for curl has the support though.

**Comment by rohitjoshi** [comment] 2015-01-08 16:21
Note:  export ALL_PROXY=http://localhost:8098  works fine for brew upgrade

**Comment by alexcrichton** [comment] 2015-01-08 17:03
Unfortunately this is because libgit2 does not support proxies just yet. As a result I believe that this is a dupe of https://github.com/rust-lang/cargo/issues/636, but thanks for the report!

**Closed by alexcrichton** 2015-01-08 17:03 UTC
