### ISSUE TITLE
cargo-beta unpacks as cargo-nightly

### ISSUE THREAD

**Issue by rillian** [rust-lang/cargo#3571] opened 2017-01-20 22:19 UTC
The 1.15.0-beta.4 manifest links https://static.rust-lang.org/dist/2017-01-20/cargo-beta-x86_64-unknown-linux-gnu.tar.gz, hash `0a1064a5fc5fff404e1521241ce96643a2c5a581db870c99c7f30278504432b7` but that tarball unpacks into a directory named `cargo-nightly-x86_64-unknown-linux-gnu`.

This is confusing, and broke my script.

**Comment by rillian** [comment] 2017-01-20 22:20
Possibly related to https://github.com/rust-lang/rust/issues/38519?

**Comment by alexcrichton** [comment] 2017-01-20 22:23
cc @brson, caused by https://github.com/rust-lang/rust-buildbot/pull/148

**Comment by rillian** [comment] 2017-01-20 22:58
If the packaging system is renaming the tarballs, it should rewrite the relative paths inside to match. That changes the checksum, but I think least-surprise on the filename wins over comparing the artifact hashes.

Maybe cargo could have actual beta and stable build channels, like rust?

**Comment by alexcrichton** [comment] 2017-01-20 23:01
@brson can speak more to renaming directories. 

Cargo probably won't get this sort of build channel any time soon, so that's probably aways away.

**Comment by carols10cents** [comment] 2017-09-29 19:06
Cargo does have these build channels now, so I'm closing this issue! Thanks!

**Closed by carols10cents** 2017-09-29 19:06 UTC
