### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by GildedHonour** [rust-lang/cargo#1217] opened 2015-01-24 13:24 UTC
An error:

```
$ cargo test
An unknown error occurred

To learn more, run the command again with --verbose.

$ cargo build
An unknown error occurred

To learn more, run the command again with --verbose.

$ cargo -V
cargo 0.0.1-pre-nightly (b3ce593 2014-11-19 07:12:26 +0000)

$ ls -al
total 144
drwxr-xr-x  14 alex  staff    476 Jan 24 21:21 .
drwxrwxr-x   8 alex  staff    272 Jan 24 21:06 ..
drwxr-xr-x  14 alex  staff    476 Jan 24 21:12 .git
-rw-r--r--   1 alex  staff     99 Dec  7 21:41 .gitignore
-rw-------   1 alex  staff   1058 Jan 23 13:29 Cargo.lock
-rw-rw-r--   1 alex  staff    500 Jan 23 18:41 Cargo.toml
-rw-rw-r--   1 alex  staff  10847 Dec  7 17:50 LICENSE-APACHE
-rw-r--r--   1 alex  staff   1080 Dec  7 17:53 LICENSE-MIT
-rw-r--r--   1 alex  staff    769 Dec  8 21:34 README.md
drwxr-xr-x   4 alex  staff    136 Jan 24 21:11 src

```

**Comment by emanueLczirai** [comment] 2015-01-24 16:46
Possibly dupe of #1201 .
What does `cargo build -v` say? if at all

**Comment by GildedHonour** [comment] 2015-01-24 17:31
```
$ cargo build -v
An unknown error occurred
Process didn't exit successfully: `rustc -v verbose` (status=101)
--- stderr
error: couldn't read verbose: IoError { kind: FileNotFound, desc: "couldn\'t open path as file", detail: Some("no such file or directory (No such file or directory); path=verbose; mode=open; access=read") }

```

**Comment by emanueLczirai** [comment] 2015-01-24 18:04
That's weird, the command is missing the `--` before the `verbose` looks like it

**Comment by alexcrichton** [comment] 2015-01-24 19:47
This looks like you just need to update cargo, `-v verbose` was the old way of asking the compiler for `-vV`.

**Closed by alexcrichton** 2015-01-24 19:47 UTC

**Comment by GildedHonour** [comment] 2015-01-25 02:05
Cargo comes with rust, right? I updated rust yesterday and, as you can see, it's the last version.

**Comment by alexcrichton** [comment] 2015-01-25 03:12
How did you update rustc? Your Cargo version is from this past November and should be much newer than that.

**Comment by GildedHonour** [comment] 2015-01-25 04:13
Really? I did by brew install rust. How can I update Cargo?

**Comment by alexcrichton** [comment] 2015-01-25 05:40
We recommend currently installing rust through the [nightly channel](http://rust-lang.org/install.html) as it ensures that Cargo is installed as well, perhaps the homebrew script for rust isn't installing Cargo as well?

**Comment by GildedHonour** [comment] 2015-01-25 05:41
Thanks.

**Comment by GildedHonour** [comment] 2015-01-25 06:15
```
$ cargo test
error: the trait `core::fmt::String` is not implemented for the type `core::option::Option<collections::string::String>` [E0277]
/Users/alex/.cargo/git/checkouts/gcc-rs-49038096d5e74406/master/src/lib.rs:28     println!("{} = {}", v, r);
                                                                                                         ^
note: in expansion of format_args!
<std macros>:2:42: 2:75 note: expansion site
<std macros>:1:1: 2:77 note: in expansion of println!
/Users/alex/.cargo/git/checkouts/gcc-rs-49038096d5e74406/master/src/lib.rs:28:5: 28:31 note: expansion site
/Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.0/src/lib.rs:102:29: 102:32 error: the trait `core::fmt::Display` is not implemented for the type `&mut std::io::process::Command` [E0277]
/Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.0/src/lib.rs:102     println!("running: {}", cmd);
                                                                                                                 ^~~
note: in expansion of format_args!
<std macros>:2:42: 2:75 note: expansion site
<std macros>:1:1: 2:77 note: in expansion of println!
/Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.0/src/lib.rs:102:5: 102:34 note: expansion site
/Users/alex/.cargo/git/checkouts/gcc-rs-49038096d5e74406/master/src/lib.rs:106:29: 106:32 error: the trait `core::fmt::Display` is not implemented for the type `&mut std::io::process::Command` [E0277]
/Users/alex/.cargo/git/checkouts/gcc-rs-49038096d5e74406/master/src/lib.rs:106     println!("running: {}", cmd);
                                                                                                           ^~~
note: in expansion of format_args!
<std macros>:2:42: 2:75 note: expansion site
<std macros>:1:1: 2:77 note: in expansion of println!
/Users/alex/.cargo/git/checkouts/gcc-rs-49038096d5e74406/master/src/lib.rs:106:5: 106:34 note: expansion site
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: aborting due to 2 previous errors
Could not compile `gcc`.

```

**Comment by GildedHonour** [comment] 2015-01-25 06:20
```
$ cargo -V
cargo 0.0.1-pre-nightly (bb28e71 2015-01-22 06:06:34 +0000)
```
