### ISSUE TITLE
Add a configuration to Cargo.toml to specify which git submodules have to be fetched

### ISSUE THREAD

**Issue by sdroege** [rust-lang/cargo#11048] opened 2022-09-03 10:25 UTC
### Problem

In [gtk-rs](https://github.com/gtk-rs/gtk-rs-core) we have various git submodules that are only necessary for running the code generator. That is, they're not necessary for compiling the crates inside the repository.

If a crate currently depends on a git version of gtk-rs then cargo will download all those (not very small) git submodules too, unnecessarily.

That it downloads all git submodules currently as a default seems like reasonable behaviour as they might be required for building the crates, but it's not optimal in all cases.

### Proposed Solution

Something like the following in `Cargo.toml` for the repository example above

```toml
[package.metadata.git.submodules.gir]
fetch = false

[package.metadata.git.submodules.gir-files]
fetch = false
```

For backwards compatibility reasons this would obviously default to `fetch = true`.

**Comment by GuillaumeGomez** [comment] 2022-09-03 10:27
Nice idea1 👍

**Comment by ehuss** [comment] 2022-09-03 13:42
Thanks for the suggestion! I believe this is essentially a duplicate of #4247, so closing in favor of that.  If possible, you can adjust the submodule update strategy in .gitmodules.

**Closed by ehuss** 2022-09-03 13:42 UTC
Labels: C-feature-request

**Comment by sdroege** [comment] 2022-09-03 15:43
Thanks, I was not aware of the configuration in `.gitmodules`. I *believe* this would work but I'll have to try that. Apart from that, yes this is a duplicate of that other issue :)

**Comment by sdroege** [comment] 2022-09-06 08:33
Yes that solves it nicely for our use case, thanks!
