### ISSUE TITLE
One invalid crate-type value causes cargo to ignore all crate-type settings

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1900] opened 2015-08-13 03:29 UTC
```toml
[package]
name = "testlib"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]

[lib]
crate-type = ["dylib", "asdf"]
```

With the above `Cargo.toml`, cargo doesn't emit any warnings/errors, and just builds into `libtestlib.rlib`. I would expect cargo to instead build all valid crate types, and either ignore or emit a warning for any invalid crate-type values.

**Comment by alexcrichton** [comment] 2015-08-13 16:06
Weird!

**Comment by thirtythreeforty** [comment] 2015-08-19 20:55
Duplicate of #1914.

**Comment by alexcrichton** [comment] 2015-08-20 00:12
Thanks for the fix @thirtythreeforty!

**Closed by alexcrichton** 2015-08-20 00:12 UTC
Labels: E-easy, I-wrong
