### ISSUE TITLE
running 'cargo update' multiple times results in continually changing versions of dependencies

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/cargo#2277] opened 2016-01-12 18:49 UTC
I presume this is caused by some versioning requirements that (for some reason) aren't resolved stably.

```
cody@two /home/cody/C/coattail % cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding byteorder v0.3.13
      Adding libc v0.2.4
      Adding syntex v0.26.0
      Adding syntex_syntax v0.25.0
cody@two /home/cody/C/coattail % cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding byteorder v0.3.13
      Adding libc v0.1.12
      Adding syntex v0.25.0
      Adding syntex_syntax v0.25.0
cody@two /home/cody/C/coattail % cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding byteorder v0.3.13
      Adding libc v0.1.12
      Adding syntex v0.26.0
      Adding syntex_syntax v0.26.0
cody@two /home/cody/C/coattail % cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding byteorder v0.4.2
      Adding libc v0.1.12
      Adding syntex v0.26.0
      Adding syntex_syntax v0.25.0
cody@two /home/cody/C/coattail % cargo -V
cargo 0.6.0-nightly (e1ed995 2015-10-22)
```

**Comment by alexcrichton** [comment] 2016-01-12 21:03
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2164, so closing in favor of that, but thanks for the report!

**Closed by alexcrichton** 2016-01-12 21:03 UTC
