### ISSUE TITLE
Circular dev-dependency enables features in release mode with resolver 2

### ISSUE THREAD

**Issue by sokki** [rust-lang/cargo#14807] opened 2024-11-11 15:38 UTC
### Problem

In a workspace with 2 packages:

**main**
```toml
[dev-dependencies]
sub = { path = "../sub" }
[features]
testing = []
```

**sub**
```toml
[dependencies]
main = { path = "../main", features = ["testing"] }
```

The feature `testing` is enabled when running `main` in release mode.

Repro: https://github.com/sokki/resolve-circular-dev-dependencies-features

### Version

```text

```

**Comment by epage** [comment] 2024-11-11 15:59
Dependency resolution is independent of `--release`.

This is actually a duplicate of #8157.  Top-level features are selected based on the set of selected packages.  When run in the root of a workspace with a virtual manifest, all packages are selected.  We then walk the dependencies and unify their features..  Cargo then just selects a specific bin within the workspace.

**Closed by epage** 2024-11-11 15:59 UTC
Labels: C-bug, A-features, S-triage
