### ISSUE TITLE
feature request: `cargo doc` should create an index page and doc pages should link to the index page

### ISSUE THREAD

**Issue by andrewrk** [rust-lang/cargo#1221] opened 2015-01-25 01:07 UTC
When I read online documentation, the docs are for the library assuming all the features are turned on. When I search with `s` I see traits, modules, and functions which are only available for certain features. If I have those features turned off in `Cargo.toml` then this documentation is at best distracting and at worst misleading. So, the generated documentation UI should provide checkboxes or some other way to toggle features on/off so that you can remove the features that you don't have on when browsing documentation.

I understand that this may require changes in rustdoc.

**Comment by andrewrk** [comment] 2015-01-29 01:58
I think there is a better solution to this, and it is already part way implemented.

When you run `cargo doc` it creates documentation for all dependencies and takes into account features, which is great. But the generated documentation is missing an index page that lists all the crates.

I tried running `cargo doc --open` to see what page it defaulted to, but that feature appears to be broken for me.

The search functionality works with all the dependencies' docs together, which is great. I think additionally each doc page should link back to the index. (And there should be an index).

**Comment by huonw** [comment] 2015-01-29 02:35
cc https://github.com/rust-lang/rust/issues/16103 (`cargo doc` basically just calls `rustdoc` on the various crates.)

**Comment by alexcrichton** [comment] 2015-05-18 23:13
Closing as a dupe of https://github.com/rust-lang/cargo/issues/1016

**Closed by alexcrichton** 2015-05-18 23:13 UTC
Labels: C-doc
