### ISSUE TITLE
Dependencies with submodules containing submodules with relative urls fail to fetch

### ISSUE THREAD

**Issue by Jesse-Bakker** [rust-lang/cargo#10959] opened 2022-08-09 13:39 UTC
### Problem

Depending on a crate with a submodule that contains a nested submodule with a relative url will fail to fetch.

Example:
```toml
[package]
name = "parent"

[dependencies]
dep1 = {git = "https://github.com/example/dep1"}
```
dep1/.gitmodules
```ini
[submodule "dep2"]
    path = dep2
    url = https://github.com/example2/dep2.git
```
dep2/.gitmodules
```ini
[submodule "dep3"]
    path = dep3
    url = ../dep3
```

This generates the error:
```
error: failed to get `dep1` as a dependency of package `parent`

Caused by:
  failed to load source for dependency `dep1`

Caused by:
  Unable to update https://github.com/example/dep1

Caused by:
  failed to update submodule `dep2`

Caused by:
  failed to update submodule `dep3`

Caused by:
  failed to fetch submodule `dep3` from ../dep3.git
```

An example of this happening in the wild is with `mupdf-rs = {git = "https://github.com/messense/mupdf-rs"}`

### Version

```text
cargo 1.62.1 (a748cf5a3 2022-06-08)
release: 1.62.1
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1n)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by ehuss** [comment] 2022-08-09 14:52
Thanks for the report!  I believe that relative-path submodules are not supported at all at this time.  Closing as a duplicate of #7992.

**Closed by ehuss** 2022-08-09 14:52 UTC
Labels: C-bug
