### ISSUE TITLE
"cargo check" shows false positive compiler errors when using API-altering #[cfg(feature = ...)] attributes in a workspace

### ISSUE THREAD

**Issue by recatek** [rust-lang/cargo#11704] opened 2023-02-12 23:52 UTC
### Problem

When a #[cfg(feature = ...)] alters a type or function signature, cargo check displays incorrect errors where compiling is fine.

### Steps

Create a cargo workspace with the following files:

temp/Cargo.toml
```toml
[workspace]
resolver = "2"
members = [
    "crates/*", 
]
```
temp/crates/client/Cargo.toml
```toml
[package]
name = "client"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = [ "client" ] }
```
temp/crates/server/Cargo.toml
```toml
[package]
name = "server"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = [ "server" ] }
```
temp/crates/common/Cargo.toml
```toml
[package]
name = "common"
version = "0.0.0"
edition = "2021"

[features]
client = []
server = []
```
temp/crates/client/src/main.rs
```rust
fn main() {
    common::do_thing(());
}
```
temp/crates/server/src/main.rs
```rust
fn main() {
    common::do_thing(common::ServerThing);
}
```
temp/crates/common/src/lib.rs
```rust
#[cfg(feature = "server")]
pub struct ServerThing;

#[cfg(feature = "server")]
pub type ServerThingAlias = ServerThing;
#[cfg(not(feature = "server"))]
pub type ServerThingAlias = ();

pub fn do_thing(_thing: ServerThingAlias) {}
```

Then run `cargo check` in the workspace directory, which yields the following error:
```
    Checking client v0.0.0 (temp\crates\client)
error[E0308]: mismatched types
 --> crates\client\src\main.rs:2:22
  |
2 |     common::do_thing(());
  |     ---------------- ^^ expected struct `ServerThing`, found `()`
  |     |
  |     arguments to this function are incorrect
  |
note: function defined here
 --> temp\crates\common\src\lib.rs:9:8
  |
9 | pub fn do_thing(_thing: ServerThingAlias) {}
  |        ^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `client` due to previous error
```

Then run `cargo build -p client` and `cargo build -p server` and observe no errors.

### Possible Solution(s)

This can be worked around by newtyping and adding attributes to inner types, but quickly gets out of hand as far as ergonomics.

### Notes

This has come up a lot in my current application (game networking) due to a desire to strip server code out of the client and vice versa. Currently the only compile-time tool for doing this is build features, but they aren't functioning correctly in in the tooling available. Since rust-analyzer (I believe) uses cargo check for this type of resolution, it creates spurious errors in r-a that can't be disabled or skipped.

### Version

```text
cargo 1.67.1 (8ecd4f20a 2023-01-10)
release: 1.67.1
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-pc-windows-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
```

**Comment by ehuss** [comment] 2023-02-13 00:04
Thanks for the report! This is expected behavior since features are unified for all packages being built. When building packages separately, only the features needed by those packages are enabled. Features are intended to be additive such that it should be safe to enable any combination of features. 

Closing as a duplicate of #4463.

**Closed by ehuss** 2023-02-13 00:04 UTC
Labels: C-bug
