### ISSUE TITLE
cargo install --git hardcodes master, doesn't use the default remote branch (HEAD)

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/cargo#8380] opened 2020-06-18 20:26 UTC
**Problem**

`cargo install --git` uses the `master` branch by default. A better default would be to use the default remote branch (aka `HEAD`), which is typically `master` but more people have been setting to other names recently.

**Steps**

```sh
cargo install --git https://github.com/sunshowers/non-master-branch
```

The output is:

```
    Updating git repository `https://github.com/sunshowers/non-master-branch`error: failed to find branch `master`

Caused by:
  cannot locate local branch 'master'; class=Reference (4); code=NotFound (-3)
```

**Possible Solution(s)**
* Use the default remote branch (a minor BC breakage, but I'd be surprised if it broke anyone).
* If the BC breakage is too severe, at least warn about this.

**Notes**

Output of `cargo version`:

```
cargo 1.44.0 (05d080faa 2020-05-06)
```

**Comment by Eh2406** [comment] 2020-06-18 20:28
CC #8364

**Comment by sunshowers** [comment] 2020-06-18 20:29
> CC #8364

Thanks! Looks like this is addressed by that PR.

**Comment by Erk-** [comment] 2020-06-18 21:00
Duplicate of #3517

**Comment by carols10cents** [comment] 2020-06-24 15:31
Closing as duplicate of #3517

**Closed by carols10cents** 2020-06-24 15:31 UTC
Labels: C-bug
