### ISSUE TITLE
Allow specification of the output directory for `cargo doc`

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#760] opened 2014-10-26 21:17 UTC
I'm hosting documentation for multiple crates in the same github.io repository. Rustdoc can only properly setup the crate list, search indices, etc, if it's writing directly into the same folder for each crate. Right now I'm symlinking `target/doc` to the right folder in each project, but that's pretty fragile. Ideally, I'd be able to specify `cargo doc --out-dir=../sfackler.github.io/doc` or something.

**Comment by alexcrichton** [comment] 2015-05-18 21:44
Closing as a dupe of https://github.com/rust-lang/cargo/issues/482 as it's likely how this will be solved.

**Closed by alexcrichton** 2015-05-18 21:44 UTC
Labels: A-configuration, C-doc, E-easy

**Comment by chloekek** [comment] 2024-01-03 00:24
I don’t think #482 solves this properly, in the case where crates are built for different targets, for instance:

```rust
cargo doc foo --target x86_64-unknown-linux-gnu
cargo doc bar --target x86_64-pc-windows-msvc
```

The docs for `foo` and `bar` are written to `target/x86_64-unknown-linux-gnu/doc` and `target/x86_64-pc-windows-msvc/doc`, respectively. With separate crate lists and search indexes, etc.

Having an output directory option specifically for `cargo doc` (as suggested by OP) would therefore still be useful.
