### ISSUE TITLE
cargo test -p ignores dev-dependencies

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2651] opened 2016-05-05 19:04 UTC
In rustup I have a `rustup` crate that depends on a `rustup-dist` crate.

In the Cargo.toml for rustup-dist I have:

```
[dev-dependencies]
url = "1.1.0"
```

And in my 'tests' folder tests with import the url crate.

When I run tests from the 'workspace' level with `cargo test -p rustup-dist` the url crate does not resolve, but if I `cd` into the `rustup-dist` directory and run `cargo test` it works correctly.

**Comment by alexcrichton** [comment] 2016-05-05 21:51
Dupe of https://github.com/rust-lang/cargo/issues/860, but definitely an unfortunate bug. Will be fixed with workspaces!

**Closed by alexcrichton** 2016-05-05 21:51 UTC
