### ISSUE TITLE
Support for `clone` subcommad

### ISSUE THREAD

**Issue by UebelAndre** [rust-lang/cargo#8888] opened 2020-11-23 23:49 UTC
**Describe the problem you are trying to solve**
I'd like a sub command (`cargo clone`) to exist that fetches a crate source. 

**Describe the solution you'd like**
This would be very similar to `cargo vendor` but would accept an arbitrary crate and version and not require a manifest. Perhaps https://github.com/ehuss/cargo-clone-crate or https://github.com/JanLikar/cargo-clone could be integrated or something entirely new created from existing code. Cargo obviously has the ability to fetch crate source from a registry, I'd just like to be able to specify what exactly to fetch from a customizable registry and where to put it.

**Notes**
This request is partially related to https://github.com/rust-lang/cargo/issues/8708 and inspired by https://github.com/google/cargo-raze/issues/218. Cargo-raze now handles binary dependencies in a unique way this is fine for the time being but the ability to use cargo to fetch a crate's source from a registry would simplify things.

**Comment by ehuss** [comment] 2020-11-30 18:56
Closing as a duplicate of #1545, though feel free to leave a comment if I misunderstood the request.

**Closed by ehuss** 2020-11-30 18:56 UTC
Labels: C-feature-request

**Comment by UebelAndre** [comment] 2020-11-30 18:58
Ah thanks, I missed that ticket. Closing as duplicate is the right thing to do here. 🙏
