### ISSUE TITLE
cargo check in the workspace discards crate-specific configurations; such as --target

### ISSUE THREAD

**Issue by WildCryptoFox** [rust-lang/cargo#7600] opened 2019-11-18 02:07 UTC
**Problem**

Running `cargo check --all` in the root of a workspace discards the per-crate cargo configuration. In my case this results in the `[build] target = "xxx"` being ignored.

**Steps**

1. Setup a workspace containing a crate with its own `.cargo/config`
2. Run `cargo check` inside that crate's dir. It successfully uses the config.
3. Run `cargo check --all` from the root of the workspace. It fails to use the config.

**Possible Solution(s)**

Always use the crate's cargo configuration if it exists.

**Notes**

Output of `cargo version`:

I think this is a digression but I haven't verified any older versions worked.

```
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
```

**Comment by ehuss** [comment] 2019-11-19 22:54
Thanks for the report!  This is a duplicate of #2930, so closing in favor of that.  Cargo currently only looks at the current directory and up.  It indeed can be surprising, but it is a bit difficult to nail down different rules, and can be tricky with backwards compatibility.

**Closed by ehuss** 2019-11-19 22:54 UTC
Labels: C-bug
