### ISSUE TITLE
cargo doc mixes [package] name and [[bin]] target name resulting in silent collision

### ISSUE THREAD

**Issue by djeedai** [rust-lang/cargo#8898] opened 2020-11-25 17:26 UTC
**Problem**

`cargo doc` on binary package of workspace uses `name` property instead of crate name and silently collides with another same-named crate.

At the very least even if the answer is "this is not a valid setup" (see Steps below) then there should be a name collision warning instead of silently ignoring it and outputting both crates' docs in the same folder, overwriting one with the other.

**Steps**

1. [GitHub repository](https://github.com/djeedai/weldr/tree/gltf) with cargo workspace ([`Cargo.toml`](https://github.com/djeedai/weldr/blob/gltf/Cargo.toml)) containing 2 packages:
   - A pure library under `lib/`, which publishes to a `weldr` crate ([`Cargo.toml`](https://github.com/djeedai/weldr/blob/gltf/lib/Cargo.toml))
     ```toml
     [package]
     name = "weldr"
     [lib]
     name = "weldr"
     ```
   - A binary tool under `bin/weldr/`, which publishes to a crate `weldr-bin`, but uses `name = "weldr"` in its `Cargo.toml` to ensure the executable produced is named `weldr(.exe)` ([`Cargo.toml`](https://github.com/djeedai/weldr/blob/gltf/bin/weldr/Cargo.toml))
     ```toml
     [package]
     name = "weldr-bin"
     [[bin]]
     name = "weldr"
     ```
2. Run `cargo doc --open --package weldr` from the root of the repository

This opens the docs for the `weldr-bin` crate (from `bin/weldr/`), whose title is "Crate weldr" instead of "Crate weldr-bin". It seems the "name" attribute was (wrongly?) used as the crate name and output path, and overwrote the other doc for the other package.

![image](https://user-images.githubusercontent.com/6532395/100260936-f5e90180-2f41-11eb-9204-c1170f41d5bc.png)
_This should be the `weldr-bin` crate (0.0.1) here, and the docs overwrote the ones for the other crate `weldr` (0.2.0)_

**Possible Solution(s)**

No idea. This is blocking me from releasing. I would have named the library `libweldr` on Linux, but that seems uncommon practice in Rust / crates.io, so went with the bare name. The binary CLI tool would be very ugly as `weldr-bin(.exe)` too, so I really want to keep it named like its sister library.

**Notes**

Output of `cargo version`: `cargo 1.48.0 (65cbdd2dc 2020-10-14)`

The [documentation](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries) states that (emphasize mine):

> The name field specifies the name of the target, which **corresponds to the filename of the artifact that will be generated**. For a library, this is the crate name that dependencies will use to reference it.

So it seems a priori invalid to have 2 libraries with the same `name=` target, but nothing said about binaries since binaries are not referenced as crates. I read that as the fact that `name=` for binaries should only be taken as the target name and nothing else, and therefore `cargo doc` shouldn't use it in the title as "Crate <target_name>" but instead use the `[package]` name (crate name).

I suspect this is an under-specified case in practice. I hope we can make that work though.

**Comment by ehuss** [comment] 2020-11-25 17:46
From a clean `target/doc` directory (`rm -rf target/doc`), the command `cargo doc --open --package weldr` seems to work correctly for me.  Did you maybe run `cargo doc` without the `-p` flag at some point in the past?  If you do, you should see a warning like this:

```
warning: output filename collision.
The bin target `weldr` in package `weldr-bin v0.0.1 (/Users/eric/Proj/rust/cargo/scratch/weldr/bin/weldr)` has the same output filename as the lib target `weldr` in package `weldr v0.2.0 (/Users/eric/Proj/rust/cargo/scratch/weldr/lib)`.
Colliding filename is: /Users/eric/Proj/rust/cargo/scratch/weldr/target/doc/weldr/index.html
The targets should have unique names.
This is a known bug where multiple crates with the same name use
the same path; see <https://github.com/rust-lang/cargo/issues/6313>.
```

This is a known issue where rustdoc directories use a crate name (without any differentiators), which can cause a collision in various situations (such as what you have stumbled upon).  There's more detail in #6313 along with links to the rustdoc-specific issues. 

There are a few things you can do.  One is to add `doc = false` to the `[[bin]]` section of weldr-bin.  Another is to just run `cargo doc -p weldr` instead of documenting multiple workspace members at once.  I believe if you are planning to publish to crates.io, that docs.rs should do the right thing (it only documents one package at a time).

**Comment by djeedai** [comment] 2020-11-25 18:20
Alright, so not sure what I did, I certainly ran before without `-p` but now was trying and you're right:

```shell
cargo clean
cargo doc -p weldr --open
```

works as intended. And:

```shell
cargo clean
cargo doc -p weldr-bin --open
```

indeed has a warning about name collision, and will in the end get me the doc for `weldr-bin` but not its dependency `weldr` (but I don't really care during local dev, and it seems docs.rs should do the right thing).

I therefore assume from your answer @ehuss that:

1. My use case / setup is actually not so weird and should be supported, is that correct?
2. docs.rs probably does the right thing so I shouldn't be worried about publishing
3. The warning is indeed there, I had missed it the first time due to another warning with some dependencies using 2 different versions of `rand_core`.

...and therefore it seems that there is nothing else to do here. Can you confirm I got everything right please?

**Comment by djeedai** [comment] 2020-11-25 18:20
...well except from the fact that the doc page title is still "Crate weldr" for the weldr-bin crate, is that really expected?

**Comment by djeedai** [comment] 2020-11-25 19:03
I actually thought about this more and came to the conclusion that I probably want to use `doc = false` here and that everything is working as intended:

- the name collision is not a problem for crates.io which as I actually understand/realize will manage _packages_ (despite its name), but for docs.rs this will be a problem since that time it deals with actual crates and there are indeed 2 _crates_ with the same name (the library one and the binary one)
- corollary to that, I now understand why docs.rs uses the `name = ` field in the page title and side navbar; this makes sense and rightfully collides. I thought about a package containing multiple binaries and realized that using the package name would not work indeed.
- the `weldr-bin` package (not crate) is a pure binary executable package, it makes little sense to have its documentation on docs.rs, as it doesn't have any API surface to use programatically. Some docs in a `doc/` folder or on github.io is probably good enough and even more suited.

I'd be glad if anyone can validate my claims above before I go down the route of trying to ship (and close this bug) 😉

**Comment by ehuss** [comment] 2020-11-25 19:07
Yea, that all sounds correct. It should work without the hassle, it's just a bug. Unfortunately it's not easy to fix.  There needs to be a new layout strategy for the directories, and rustdoc needs to have additional options to tell it how to map the directories to crates, and someone needs to figure out how all that should interact.

I think setting `doc=false` for the bin crate sounds like the right way to go.

**Comment by ehuss** [comment] 2020-11-30 18:59
I'm going to close this as a duplicate of #6313 (and the linked rustdoc issues within that issue).

**Closed by ehuss** 2020-11-30 18:59 UTC
Labels: C-bug
