### ISSUE TITLE
Replacements should allow for version mismatch

### ISSUE THREAD

**Issue by vvuk** [rust-lang/cargo#3309] opened 2016-11-21 15:40 UTC
Right now, if I'm developing updates to package A that package B depends on, if I use the replacements mechanism, I cannot bump the version number in package A -- even if the work I'm doing is intertwined, and I'm not going to bump the version that B requires until A is ready.  For example, I may have introduced a new api in A that I want to use in B -- but B's usage is uncovering issues in A, that need patching (after the original PR would have already been accepted in A).

Replacements would be far more useful if I could specify `"foo:0.1" = { git="..." }` and have this mean "assume whatever is in the git dir is 0.1, even if it indicates otherwise in a version.  A warning can get printed (e.g. `"Warning: replacement create 'foo' has version 0.2, but it's replacing version 0.1"`) so that when this isn't desirable it's easily caught.

**Comment by alexcrichton** [comment] 2016-11-21 16:18
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2649, but thanks for the report!

**Closed by alexcrichton** 2016-11-21 16:18 UTC
