### ISSUE TITLE
`cargo:rustc-cfg` and rustdoc

### ISSUE THREAD

**Issue by dgrunwald** [rust-lang/cargo#1622] opened 2015-05-17 17:13 UTC
I have a library that uses a build script with `cargo:rustc-cfg` to pass cfg options depending on the configuration of system libraries.

However, when running `cargo doc`, cargo does not pass any cfg options to rustdoc, causing my build to fail. Cargo should pass `rustc-cfg` options to rustdoc, or alternatively, allow build scripts to use `cargo:rustdoc-cfg`.

**Comment by alexcrichton** [comment] 2015-05-17 20:29
Ah indeed, good point!

**Comment by hauleth** [comment] 2015-05-27 08:05
What is worse Cargo isn't passing all linker flags to `rustdoc` when running `cargo test`.

I'm using LinuxBrew, and when building [my `ucl` lib](https://github.com/hauleth/ucl-rs), `ssl` and `crypto` libraries aren't linked as there is no path to them given to linker. When I manually add `-L "$HOME/.linuxbrew/Cellar/openssl/1.0.2a-1/lib"` to `rustdoc` then it works fine.

`cargo test --verbose`: https://gist.github.com/hauleth/1fe456288cd0c9be2358
`cargo --version`: `cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)`

**Comment by IvanUkhov** [comment] 2015-06-16 21:53
I’d like to put my two cents in. I use `build.rs` to enable additional features via `rustc-cfg`, and the documentation is generated on a machine that supports all the features. However, since `rustc-cfg` doesn’t reach `rustc`, the resulting documentation ends up being a bit incomplete.

**Comment by alexcrichton** [comment] 2015-06-17 21:06
Closing as a dupe of https://github.com/rust-lang/cargo/issues/1592 (just forgetting to pass build script flags to rustdoc)

**Closed by alexcrichton** 2015-06-17 21:06 UTC
Labels: C-doc, E-easy
