### ISSUE TITLE
Non-deterministic errors resolving multple versions of openssl-sys in rust beta 1.13.0-beta.3

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#3268] opened 2016-11-08 02:00 UTC
I found this on crater in our new builds of cargo that we paired with the Rust 1.13 beta. It affects cargo-edit-0.1.3 and megam_api-0.1.10 at least, but seems to be non-deterministic, so may affect others.

When building either of these crates without a lockfile I _sometimes_ get this error:

```
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.9.0
  openssl-sys v0.7.17
```

Rerunning `cargo build` _sometimes_ makes it go away.

**Comment by brson** [comment] 2016-11-08 02:01
cc @alexcrichton

**Comment by brson** [comment] 2016-11-08 02:01
[Crater report](https://gist.github.com/anonymous/419e2a231cf0db6b94d513af9b343c66).

**Comment by brson** [comment] 2016-11-08 03:00
I've also seen this once with cargo on stable (`cargo +stable build` in rustup):

```
brian@host:~/dev/test/cargo-edit-0.1.3⟫ cargo +stable clean
brian@host:~/dev/test/cargo-edit-0.1.3⟫ rm Cargo.lock
brian@host:~/dev/test/cargo-edit-0.1.3⟫ cargo +stable build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling strsim v0.5.1
   Compiling rustc-serialize v0.3.19
   Compiling utf8-ranges v0.1.3
   Compiling lazy_static v0.2.1
   Compiling nom v1.2.4
   Compiling unicode-normalization v0.1.2
   Compiling pkg-config v0.3.8
   Compiling semver v0.2.3
   Compiling gcc v0.3.38
   Compiling log v0.3.6
   Compiling unicode-width v0.1.3
   Compiling pad v0.1.4
   Compiling openssl-sys v0.7.17
   Compiling libc v0.2.17
   Compiling libz-sys v1.0.6
   Compiling regex-syntax v0.3.9
   Compiling memchr v0.1.11
   Compiling matches v0.1.4
   Compiling aho-corasick v0.5.3
   Compiling unicode-bidi v0.2.3
   Compiling winapi-build v0.1.1
   Compiling idna v0.1.0
   Compiling winapi v0.2.8
   Compiling kernel32-sys v0.2.2
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.7
   Compiling curl-sys v0.1.34
   Compiling regex v0.1.80
   Compiling url v1.2.3
   Compiling quick-error v1.1.0
   Compiling toml v0.1.30
   Compiling docopt v0.6.86
   Compiling curl v0.2.19
   Compiling cargo-edit v0.1.3 (file:///mnt2/dev/test/cargo-edit-0.1.3)
    Finished debug [unoptimized + debuginfo] target(s) in 90.81 secs
brian@host:~/dev/test/cargo-edit-0.1.3⟫ cargo +stable build
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up
once

  openssl-sys v0.9.0
  openssl-sys v0.7.17
101 brian@host:~/dev/test/cargo-edit-0.1.3⟫ cargo +stable -V
cargo 0.13.0-nightly (109cb7c 2016-08-19)
brian@host:~/dev/test/cargo-edit-0.1.3⟫ rustc +stable -V
rustc 1.12.1 (d4f39402a 2016-10-19)
```

**Comment by brson** [comment] 2016-11-08 03:09
This command fails for me 7/17 times:

```
$ rm -f Cargo.lock && cargo +stable build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.9.0
  openssl-sys v0.7.17
```

**Comment by brson** [comment] 2016-11-08 03:12
Whatever is happening here seems to be in the stable release.

**Comment by alexcrichton** [comment] 2016-11-08 05:20
The nondeterminism is a very long lasting "bug" in Cargo (https://github.com/rust-lang/cargo/issues/2064) so in that sense I don't believe this is a regression. This is showing up now because openssl-sys was release, which unfortunately breaks a few crates by default (for various, but unrelated, reasons).

Basically tl;dr; this is a known bug but not a regression

**Comment by alexcrichton** [comment] 2016-11-08 21:06
I believe I've fixed all crates in question

**Comment by brson** [comment] 2016-11-08 22:05
[Here's a list with some more such errors](https://github.com/rust-lang/rust/pull/37602#issuecomment-259114908).

**Comment by brson** [comment] 2016-11-08 22:06
Why are these results non-deterministic?

**Comment by alexcrichton** [comment] 2016-11-08 22:36
I believe all of those are related to the curl 0.2 library, which I just fixed with a new publish to crates.io. The results are nondeterministic because Cargo's graph traversal is slightly nondeterministic (uses a `HashMap` somewhere)

**Comment by brson** [comment] 2016-11-09 04:24
Thanks for the explanation @alexcrichton!

**Closed** 2016-11-09 04:32 UTC
