### ISSUE TITLE
Allow `cargo install` to overwrite existing binaries

### ISSUE THREAD

**Issue by panicbit** [rust-lang/cargo#2274] opened 2016-01-12 14:41 UTC
It would be useful to have something like a `--force` or `--update` parameter to overwrite existing binaries.

**Comment by alexcrichton** [comment] 2016-01-12 17:02
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2082, so I'm going to close in favor of that, thanks for filing though!

**Closed by alexcrichton** 2016-01-12 17:02 UTC
Labels: C-install
