### ISSUE TITLE
Keyword limitations are not apparent

### ISSUE THREAD

**Issue by WaDelma** [rust-lang/cargo#2098] opened 2015-10-31 22:43 UTC
There is no information in cargo's manifest information about the limitations on keywords.
I tried to add keyword "object distribution" and "blue noise" to my crate and when I tried to publish it, it complained:

```
api errors: invalid upload request: ApplicationError("invalid keyword specified: object distribution")
```

With no information what was wrong (though I was able to guess that it was the space in the keyword).
There seems to be #1736 that touches on the problem, but from different angle.
There should be clearer indication on what is and what is not valid for Cargo.toml to contain.
And the limitation of not having space on keyword seems overly restrictive: While using separate tags for "object" and "distribution" seem fine, using separate tags for "blue" and "noise" seems silly and bad.

**Comment by joshtriplett** [comment] 2016-06-21 23:38
Similarly, cargo should warn about having too many keywords; crates.io has a maximum of 5.

**Comment by weihanglo** [comment] 2023-05-14 16:29
Triage: This looks like an duplicate of #4300, and #4377 tracks some more validation people are interested in. Closing in favor of those.

**Closed by weihanglo** 2023-05-14 16:29 UTC
Labels: A-errors
