### ISSUE TITLE
Git dependency with slashes in branch name fails

### ISSUE THREAD

**Issue by calebmer** [rust-lang/cargo#2543] opened 2016-04-03 19:22 UTC
In my git repositories, feature branches have a slash, e.g. `feat/new`. When I try to depend on this in cargo via:

``` toml
name = "my-crate-name"

[dependencies]
hello-world = { git = "https://github.com/hello/world", branch = "feat/new" }
```

The following error occurs:

```
    Updating git repository `https://github.com/hello/world`
Unable to update https://github.com/hello/world?branch=feat/new

Caused by:
  Could not find `Cargo.toml` in `/Users/calebmer/.multirust/toolchains/stable/cargo/git/checkouts/hello-world-dfc7cedab8ae57e6/feat/my-crate-name`
```

**Comment by alexcrichton** [comment] 2016-04-04 16:20
I think this is a bug [around here](https://github.com/rust-lang/cargo/blob/12f76a542a9f0c2a5791432ea1df7b30ae28d0c6/src/cargo/sources/git/source.rs#L155-L160) where we assume that a branch is a reasonable choice for a filesystem component. I think that my not be correct!

Should be a relatively easy bug to tackle though :)

**Comment by srinivasreddy** [comment] 2016-04-05 18:51
Why am i not getting the same error?
```
srinivas@Srini:~/workspace/github/hyper$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/srinivasreddy/cargo.git`
srinivas@Srini:~/workspace/github/hyper$ git diff
diff --git a/Cargo.toml b/Cargo.toml
index 8dc5490..ab9a5a6 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -12,6 +12,7 @@ authors = ["Sean McArthur <sean.monstar@gmail.com>",
 keywords = ["http", "hyper", "hyperium"]
 
 [dependencies]
+cargo = { git = "https://github.com/srinivasreddy/cargo.git", branch = "reddy/raja" }
 httparse = "1.0"
 language-tags = "0.2"
 log = "0.3"

```

**Comment by calebmer** [comment] 2016-04-05 20:01
Some potential significant differences I spotted @srinivasreddy:
- I tried on OSX, not sure if that's the same for the both of us.
- To get the dependency I was using `cargo build`/`cargo test`, not sure if that makes a huge difference over `cargo update`.
- I didn't use a `.git` extension in my dependency URL (not sure if this is a big diff either).

**Comment by alexcrichton** [comment] 2016-04-05 22:00
Maybe it's running `cargo build` instead of just `cargo update`?

**Comment by srinivasreddy** [comment] 2016-04-05 22:57
@calebmer 
- I am on ubuntu
- I just did `cargo build/cargo test`, none of it gives me that error
- I removed git extension as well.

Here is my meta
```
srinivas@Srini:~/workspace/github/hyper$ uname --all
Linux Srini 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:41 UTC 2016 i686 i686 i686 GNU/Linux
srinivas@Srini:~/workspace/github/hyper$ rustc --version
rustc 1.6.0 (c30b771ad 2016-01-19)
srinivas@Srini:~/workspace/github/hyper$ cargo version
cargo 0.7.0-nightly (1af03be 2015-12-08)

```

**Comment by alexcrichton** [comment] 2016-04-06 00:45
@calebmer what version of Cargo are you using?

**Comment by calebmer** [comment] 2016-04-07 20:04
@alexcrichton 0.8.0, here's the direct output from `rustc` and `cargo`:

```
~$ rustc --version
rustc 1.7.0 (a5d1e7a59 2016-02-29)
~$ cargo version
cargo 0.8.0-nightly (28a0cbb 2016-01-17)
```

**Comment by alexcrichton** [comment] 2016-04-08 16:58
Hm ok, do you have a standalone example that reproduces the bug for you? I also wasn't able to reproduce locally unfortunately.

**Comment by bspeice** [comment] 2017-05-29 13:56
Sorry for necromancy, but is it worth closing this? I'm unable to reproduce the problem as well, and stumbled here looking for easier projects to pick off.

**Comment by alexcrichton** [comment] 2017-05-30 14:35
Sure yeah, sounds good!

**Closed by alexcrichton** 2017-05-30 14:35 UTC
Labels: A-git, E-easy
