### ISSUE TITLE
Tests crashes in mingw x86_64

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang/cargo#7764] opened 2020-01-04 15:20 UTC
**Problem**

My project includes a CI on Travis, and it failed since couple months ago with exactly the same errors:

Link: https://travis-ci.org/shadowsocks/shadowsocks-rust/jobs/632660549

Related logs:

```
running 1 test
[0K[31;1mThe command "cargo test --no-fail-fast --features miscreant --tests" exited with 132.[0m
     Running target\debug\deps\udp-bf73777b2f282f87.exe
error: test failed.

Caused by:
  process didn't exit successfully: `C:\Users\travis\build\shadowsocks\shadowsocks-rust\target\debug\deps\shadowsocks-1b5194fe9687f253.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
process didn't exit successfully: `C:\Users\travis\build\shadowsocks\shadowsocks-rust\target\debug\deps\socks5-03719b500f22d92f.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
process didn't exit successfully: `C:\Users\travis\build\shadowsocks\shadowsocks-rust\target\debug\deps\udp-bf73777b2f282f87.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
/c/Users/travis/.travis/functions: line 109:   929 Illegal instruction     cargo test --no-fail-fast --features miscreant --tests
```

**Notes**

Output of `cargo version`:

```
cargo 1.40.0 (bc8e4c8be 2019-11-22)
```

**Comment by ehuss** [comment] 2020-01-06 21:18
I'm a little confused, as there doesn't seem to be any "doc tests" involved?

Also, I'm not sure I see how exactly this is related to Cargo.  It looks like your tests are crashing, and Cargo is reporting that.  Why do you think this is an issue in Cargo?

If you can maybe create an isolated reproduction with exact steps, that would be helpful.  I took a look at your project, but it is not obvious how to build it for windows-gnu (I got errors about libsodium not found).  Otherwise this issue doesn't seem actionable.

**Comment by zonyitoo** [comment] 2020-01-07 01:12
> I'm a little confused, as there doesn't seem to be any "doc tests" involved?

Yes, my fault. Tests were crashing.

> but it is not obvious how to build it for windows-gnu (I got errors about libsodium not found)

The error was reported from [libsodium-sys](https://github.com/sodiumoxide/sodiumoxide/tree/master/libsodium-sys). I don't know why, but maybe you can just install libsodium manually and specifying installed path with `SODIUM_LIB_DIR` env var.

**Comment by zonyitoo** [comment] 2020-01-07 01:38
I don't have any Windows device accessable. So please @ehuss retry building it on windows-gnu. It should be reproduciable because it can always be reproduced on travis-ci build.

For libsodium, you can try to remove the default feature: `sodium`.

**Comment by ehuss** [comment] 2020-01-23 18:17
> But recently [my cross build docker script](https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/build-release) failed with linker errors only for windows-gnu:

There was a temporary regression on nightly where the `CARGO_TARGET_triple_LINKER` environment variable was not working correctly. It should be fixed now.

As for the seg-fault issue, I think it is because you are trying to link an MSVC library (OpenSSL) into a gnu binary. They are not compatible, so I think you'll need to find a way to get a gnu version of openssl.

I'm going to close this since it doesn't seem related to Cargo.  I would recommend trying the user forums if you are having linking issues, or need help with openssl.

**Closed by ehuss** 2020-01-23 18:17 UTC
Labels: C-bug
