### ISSUE TITLE
Cargo should be able to conditionally build targets

### ISSUE THREAD

**Issue by asomers** [rust-lang/cargo#6617] opened 2019-02-01 17:01 UTC
**Describe the problem you are trying to solve**
Some targets, especially `[[test]]` targets, don't make sense to run on every platform.  Cargo should allow you to conditionally enable them in the manifest.  On Nix this merely causes an annoyance; some tests must have their entire bodies `#[cfg()]`ed out.  But on libc the problem is more severe; the s390x and sparc64 targets crash in the test harness before executing any tests.  There's no way to fix that problem from within test code itself; a Cargo solution is required.

**Describe the solution you'd like**
It would be great if the `[[test]]` section could be conditionally enabled, like this:
```toml
[[test]]
name = "test-something"
only-on = 'cfg(target_os = "multics")'
```
or this:
```toml
[[test.'cfg(target_os = "multics")']]
name = "test-something"
```

**Notes**
Here's a PR that shows s390x and sparc64 failing early in the test harness.
https://github.com/rust-lang/libc/pull/1235

**Comment by tasogare3710** [comment] 2019-02-12 13:41
I also having similar same problem.
However, in order to solve this, I think that concept like configuration of apache ivy which can be freely customized is necessary.

cargo profile may be replaced in this configuration concept?

**Comment by epage** [comment] 2023-10-31 01:16
Looks like #9208 is a duplicate of this but it has more discussions, so I'm closing this in favor of that.  If there is something I overlooked, let us know!

**Closed by epage** 2023-10-31 01:16 UTC
Labels: C-feature-request, A-cross-compiling
