### ISSUE TITLE
Simplified Target-Specific Dependencies

### ISSUE THREAD

**Issue by excaliburHisSheath** [rust-lang/cargo#1758] opened 2015-06-27 05:18 UTC
As I understand it to specify target-specific dependencies you need to use the full target triple:

```toml
[target.x86_64-unknown-linux-gnu.dependencies]
openssl = "1.0.1"

[target.x86_64-pc-windows-gnu.dependencies]
winhttp = "0.4.0"
```

But a platform like Windows has multiple target triples and if I want to declare windows specific dependencies I have to repeat them across all of the target triples:

```toml
[target.i686-pc-windows-gnu.dependencies]
libc = "*"
winapi = "*"
ole32-sys = "*"

[target.x86_64-pc-windows-gnu.dependencies]
libc = "*"
winapi = "*"
ole32-sys = "*"

[target.x86_64-pc-windows-msvc.dependencies]
libc = "*"
winapi = "*"
ole32-sys = "*"
```

This quickly becomes tedious. I'd like a simplified version where I can specify a set of dependencies for a platform, something like `[target.windows.dependencies]`. The broader platform sets could match those used by the `[cfg()]` attribute (e.g. "windows", "unix", "macos", etc.).

Related to #1197 this could also be applied to features as `[target.windows.features]`.

Thanks.

**Comment by alexcrichton** [comment] 2015-06-27 20:21
Dupe of https://github.com/rust-lang/cargo/issues/1007, but thanks for the report!

**Closed by alexcrichton** 2015-06-27 20:21 UTC

**Comment by excaliburHisSheath** [comment] 2015-06-27 23:51
Sorry about that! Must have missed it when looking over the existing issues.
