### ISSUE TITLE
cargo check/clippy: filter out warning report from external crate ?

### ISSUE THREAD

**Issue by YruamaLairba** [rust-lang/cargo#7957] opened 2020-03-02 18:15 UTC
**Describe the problem you are trying to solve**

**Describe the solution you'd like**

**Notes**

Hello,
When i run `cargo clippy` or `cargo check` from CLI, I also get warning report for external crate. I'd like to filter this out to get only warning coming from my current project. I Already tried to use `-p` or `--bin _NAME_`, but it don't give the result i want.

So, an option to filter out report for external crate would be useful, especially when using `cargo clippy -- D OPT` in continuous integration tool like travis to enforce particular coding style in a project

**Comment by ehuss** [comment] 2020-03-02 19:12
Thanks for the report.  This is a duplicate of https://github.com/rust-lang/rust-clippy/issues/3025 and #7850 and #5998, so closing in favor of those.

**Closed by ehuss** 2020-03-02 19:12 UTC
Labels: C-feature-request
