### ISSUE TITLE
warning: unused manifest key: package.categories

### ISSUE THREAD

**Issue by sunjay** [rust-lang/cargo#3607] opened 2017-01-28 02:26 UTC
This is my `Cargo.toml` file:

```toml
[package]
name = "brain"
version = "0.0.1"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Compiler for the brain programming language. Compiles brain into optimized brainfuck code. Also includes a brainfuck interpreter."
repository = "https://github.com/sunjay/brain"
readme = "README.md"
keywords = ["brain", "brainfuck", "compiler", "interpreter", "optimizer"]
# crates.io/category_slugs
categories = ["command-line-interface"]
license = "MIT"

[dependencies]
clap = "^2.0"

[dependencies.nom]
version = "^2.0"
features = ["verbose-errors"]

[[bin]]
name = "brain"
doc = false

[[bin]]
name = "brainfuck"
```

Every time I run `cargo run`, I get the following output:

```
$ cargo run --bin brain
warning: unused manifest key: package.categories
   Compiling brain v0.0.1 (file:///~/Documents/projects/brain)
    Finished debug [unoptimized + debuginfo] target(s) in 3.78 secs
     Running `target/debug/brain`
...blah...
```

The warning probably shouldn't be there because package.categories is a valid key as documented in [The Manifest Format](http://doc.crates.io/manifest.html#package-metadata).

**Comment by sfackler** [comment] 2017-01-28 23:57
Your version of cargo is presumably too old to have category support.

**Comment by sunjay** [comment] 2017-01-29 00:08
@sfackler Have categories landed in stable? I notice that if I use `rustup override set nightly`, the warning disappears but then if I unset and use the default (stable), I get the warning again.

```
$ cargo --version
cargo 0.15.0-nightly (298a012 2016-12-20)
$ cargo build
warning: unused manifest key: package.categories
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
```

**Comment by sfackler** [comment] 2017-01-29 00:09
The PR adding them merged 11 days ago, so it is not in the stable release: https://github.com/rust-lang/cargo/pull/3301

**Comment by sunjay** [comment] 2017-01-29 00:14
@sfackler Okay. This doesn't seem to be much of an issue then since the warning will go away when #3301 lands in stable. Looks like @briansmith [commented](https://github.com/rust-lang/cargo/pull/3301#issuecomment-274320204) in that pull request about this.

**Comment by alexcrichton** [comment] 2017-01-29 02:03
Yes the fields here are supported, just in nightly Rust right now and not yet on stable. I believe there's other bugs about the docs mismatch, but otherwise this is working as intended so I'm going to close. Thanks though for the report!

**Closed by alexcrichton** 2017-01-29 02:03 UTC
