### ISSUE TITLE
Invocation of external cargo commands defies the platform norms

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#7615] opened 2019-11-21 16:23 UTC
**Problem**

When invoking `cargo subcommand` with `cargo-subcommand` executables present in both `$PATH` and `$HOME/.cargo/bin`, the `$HOME/.cargo/bin` option will be preferred to the binaries in `$PATH`.

On setups that extensively use `$PATH` to control availability and order of preference, cargo will behave counter-intuitively. In our particular case a developer had an old version of `cargo-clippy` installed in `~/.cargo/bin` and an appropriate version (among with the matching versions of rustc and cargo) had been made available in one of the directories listed in `$PATH`. 

`cargo clippy` then failed to work as intended because it was invoking an old version of `cargo-clippy`.

IMHO if `~/.cargo/bin` is used, it should be a *fallback*, not an override, because *that* matches the users’ expectations.

**Steps**
1. ln -s $(which false) ~/.cargo/bin/cargo-banana
2. MYTMPDIR="$(mktemp -d)"
3. ln -s $(which true) $MYTMPDIR/cargo-banana
3. PATH=$MYTMPDIR:$PATH cargo banana # should return exit code 0 not 1

**Possible Solution(s)**

Use `~/.cargo/bin` as a fallback, not an override.

**Notes**

Output of `cargo version`: test case above written for `cargo 1.40.0-nightly (a429e8cc4 2019-10-04)`, but also reproducible with the most recent nightly as of date of writing.

**Comment by luser** [comment] 2020-05-06 14:27
Duplicate of #6507 I believe.

**Comment by ehuss** [comment] 2020-05-07 18:04
Yea, this looks essentially as a duplicate of #6507.

**Closed by ehuss** 2020-05-07 18:04 UTC
Labels: A-custom-subcommands, C-bug
