### ISSUE TITLE
Add option to `clean` command, to clean the no need dependencies

### ISSUE THREAD

**Issue by asuper0** [rust-lang/cargo#13326] opened 2024-01-19 02:43 UTC
### Problem

We would add and remove some dependencies during the development, which leads to large space in `target` folder.

### Proposed Solution

I suggest to add option to `clean`, which just clean build files of the removed dependencies.

**Comment by epage** [comment] 2024-01-19 03:03
Going to close this as a duplicate of #13136.  If there is a reason we should keep this open, let us know!

**Closed by epage** 2024-01-19 03:03 UTC
Labels: C-feature-request, S-triage
