### ISSUE TITLE
workspace dependency options for  `cargo add`

### ISSUE THREAD

**Issue by akabinds** [rust-lang/cargo#11527] opened 2023-01-02 19:51 UTC
### Problem

`cargo add`, although an already extensive command, currently doesn't have support for easily adding dependencies to `[workspace.dependencies]` or for specifying that a dependency should be workspace-inherited. This issue proposes an option for both of these use cases.

### Proposed Solution

# Adding to `[workspace.dependencies]`

Adding to the `[workspace.dependencies]` section could be done through a `--workspace` option. Chapter 3.3 of the Cargo Book, under  **[The dependencies table](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table)** section, states that:

> - Dependencies from this table cannot be declared as `optional`

This would mean that the `--workspace` option would have to be mutually exclusive with the `--optional` option. 

# Adding workspace-inherited dependencies

Workspace-inherited dependencies could be added through a `--workspace-inherited` option. Chapter 3.1 of the Cargo Book, under the **[Inheriting a dependency from a workspace](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace)** section, states that: 

> - Other than `optional` and `features`, inherited dependencies cannot use any other dependency key (such as `version` or `default-features`).

This would mean that the `--workspace-inherited` option would have to be mutually exclusive with all of the **[Source options](https://doc.rust-lang.org/cargo/commands/cargo-add.html#source-options)**, and all of the **[Dependency options](https://doc.rust-lang.org/cargo/commands/cargo-add.html#dependency-options)** besides `--optional`, `--no-optional`, `--default-features` (since it doesn't add to the dependency keys), `--features`, and `--dry-run`.

The `--workspace-inherited` option would just add `crate_name.workspace = true` to the desired dependencies section or `crate_name = { workspace = true, ... }` if `--optional` and/or `--features` were specified.

**Comment by weihanglo** [comment] 2023-01-02 21:06
Thank you for your detailed proposal. This is effectively a duplicate of https://github.com/rust-lang/cargo/issues/10608. Going to close this in favour of that :)

**Closed by weihanglo** 2023-01-02 21:06 UTC
Labels: C-feature-request

**Comment by akabinds** [comment] 2023-01-02 21:38
> Thank you for your detailed proposal. This is effectively a duplicate of https://github.com/rust-lang/cargo/issues/10608. Going to close this in favour of that :)

No problem. I guess I overlooked an issue or didn't look far enough when I was looking to see if it had been proposed already 😄

**Comment by epage** [comment] 2023-01-02 22:37
> > Thank you for your detailed proposal. This is effectively a duplicate of #10608. Going to close this in favour of that :)
> 
> No problem. I guess I overlooked an issue or didn't look far enough when I was looking to see if it had been proposed already 😄

While not obvious from the outside, we have labels for each command which can make it a lot easier to see what has been proposed before, e.g. [Command-add](https://github.com/rust-lang/cargo/labels/Command-add)

**Comment by akabinds** [comment] 2023-01-02 22:56
> > > Thank you for your detailed proposal. This is effectively a duplicate of #10608. Going to close this in favour of that :)
> > 
> > 
> > No problem. I guess I overlooked an issue or didn't look far enough when I was looking to see if it had been proposed already 😄
> 
> While not obvious from the outside, we have labels for each command which can make it a lot easier to see what has been proposed before, e.g. [Command-add](https://github.com/rust-lang/cargo/issues?q=is%3Aopen+label%3ACommand-add+sort%3Aupdated-desc)

Great, thanks for that! Will reference that in the future.
