### ISSUE TITLE
`run --{example,bin} fake` should give "unknown example" error

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1296] opened 2015-02-12 12:23 UTC
```rust
$ cargo new test
$ cd test
$ cargo run --example fake
a bin target must be available for `cargo run`
```

This isn't the real error, it should say "unknown example `fake`" (or similar).

The same thing is emitted when a bin target does exist, and for `--bin fake`.

**Comment by alexcrichton** [comment] 2015-02-12 18:14
Dupe of https://github.com/rust-lang/crates.io/issues/130 and PR at https://github.com/rust-lang/cargo/pull/1283

**Closed by alexcrichton** 2015-02-12 18:14 UTC
Labels: A-errors, C-run
