### ISSUE TITLE
allow cargo doc --dev to include the documentation of dev dependencies

### ISSUE THREAD

**Issue by cdecompilador** [rust-lang/cargo#11154] opened 2022-09-27 20:42 UTC
### Problem

When you generate documentation for your crate, unless specific conditions it won't include development dependencies. For the people that use the "cargo doc" while developing to look at the documentation this might be useful

### Proposed Solution

Just that adding `--dev` would enable development depenencies

**Comment by ehuss** [comment] 2022-09-27 20:58
Thanks for the suggestion! I believe this is a duplicate of #3475, so closing in favor of that.

**Closed by ehuss** 2022-09-27 20:58 UTC
Labels: C-feature-request
