### ISSUE TITLE
cargo init makes .gitignore without trailing newline

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/cargo#6846] opened 2019-04-14 00:53 UTC
**Problem**

The initial `.gitignore` created by `cargo init` does not end in a newline. This makes it annoying to append lines to it from the command line or via a text editor.

**Steps**

1. `cargo init --bin` in an empty directory.

2. Examine the resulting `.gitignore`.

**Possible Solution**

Add a newline.

**Notes**

Output of `cargo version`:

        cargo 1.34.0 (6789d8a0a 2019-04-01)

Debian Linux x86-64

**Comment by fluffysquirrels** [comment] 2019-04-14 21:05
I can take a look at this.

**Comment by fluffysquirrels** [comment] 2019-04-14 21:29
The newline is present for me on master (currently 2510c0cd7bfc902dd318d1cce60ed46bf6ff4ece) and using the nightly from 2019-04-14, so it looks like this was fixed already. Fix commit: https://github.com/rust-lang/cargo/commit/5a5d924c3eaef0c1038af2e44bea631a0d42cf57 , fix PR: https://github.com/rust-lang/cargo/pull/6732 .

**Comment by fluffysquirrels** [comment] 2019-04-14 21:41
Looks like the patch is merged into the 1.35.0 (the newline test is present: https://github.com/rust-lang/cargo/blob/rust-1.35.0/tests/testsuite/init.rs#L469-L480) and I can confirm that with the current cargo beta (`cargo 1.35.0-beta (6f3e9c367 2019-04-04)`) this works. All going well I think this will ship on the next stable 2019-04-11 + 6 weeks = 2019-05-23.

**Comment by BartMassey** [comment] 2019-04-14 22:08
Thanks!

**Comment by ehuss** [comment] 2019-04-16 15:51
Thanks for the investigation @fluffysquirrels !

**Closed by ehuss** 2019-04-16 15:51 UTC
Labels: C-bug
