### ISSUE TITLE
`cargo build -p app1 -p app2` produces different results than `cargo build -p app1 && cargo build -p app2`

### ISSUE THREAD

**Issue by sleiner** [rust-lang/cargo#11225] opened 2022-10-12 21:50 UTC
### Problem

When calling `cargo build` in a workspace to build multiple packages at the same time (e.g. `cargo build --workspace` or `cargo build -p app1 -p app2`), the results differ from building each package using a separate `cargo` invocation. This manifests in the fact that after `cargo build -p app1 -p app2` has finished successfully, `cargo build -p app2` still triggers a new build of the `app2` binary.

I can trigger this behaviour by having two executable targets share the same crate as a dependency, but with _different features_, e.g.:

- **Cargo.toml**:
  ```toml
  [workspace]
  members = ["app1", "app2"]
  ```
- **app1/Cargo.toml**:
  ```toml
  [dependencies]
  proc-macro2 = { version = "1.0.46", features = ["span-locations"] }
  ```
- **app2/Cargo.toml**:
  ```toml
  [dependencies]
  proc-macro2 = "1.0.46"
  ```

See also: A [full example workspace](https://codeberg.org/sleiner/cargo-workspace-build-mwe).

### Steps

1. In the [example workspace](https://codeberg.org/sleiner/cargo-workspace-build-mwe)
2. Run `cargo build -p app1 -p app2`. It terminates successfully:
   ```bash
   simon@machina ~/repos/cargo-workspace-build-mwe (git)-[main] % cargo build -p app1 -p app2
      Compiling proc-macro2 v1.0.46
      Compiling unicode-ident v1.0.4
      Compiling app2 v0.1.0 (/Users/simon/repos/cargo-workspace-build-mwe/app2)
      Compiling app1 v0.1.0 (/Users/simon/repos/cargo-workspace-build-mwe/app1)
       Finished dev [unoptimized + debuginfo] target(s) in 2.83s
   ```
   Also, two executable files `app1` and `app2` can now be found in `./target/debug`.
3. Build `app1` by itself:
   ```
   simon@machina ~/repos/cargo-workspace-build-mwe (git)-[main] % cargo build -p app1        
       Finished dev [unoptimized + debuginfo] target(s) in 0.08s
   ```
   As expected, nothing needs to be done here 👍🏻
4. Build `app2` by itself:
   ```
   simon@machina ~/repos/cargo-workspace-build-mwe (git)-[main] % cargo build -p app2
      Compiling proc-macro2 v1.0.46
      Compiling app2 v0.1.0 (/Users/simon/repos/cargo-workspace-build-mwe/app2)
       Finished dev [unoptimized + debuginfo] target(s) in 2.11s
    ```
    Contrary to what I was expecting, `app2` is getting rebuilt even though none of its sources have changed.
    If I interpret the contents of `./target/debug/build` correctly, a second version of `proc-macro2`, now without `span-locations` feature is being built and linked into this new build of `app2`.

### Possible Solution(s)

From a mere user perspective, I would expect `cargo build -p app1 -p app2` to produce the exact same results as `cargo build -p app1 && cargo build -p app2`. So if cargo builds multiple executables at the same time, it should not unify features between shared dependency crates but instead, if different binaries can do with multiple feature sets in a dependent crate, build multiple versions of the dependent crate during the `cargo build` call.

### Notes

see: [related discussion on users.rust-lang.org](https://users.rust-lang.org/t/cargo-build-p-app1-p-app2-behaves-differently-than-cargo-build-p-app1-cargo-build-p-app2/82431/8)

### Version

```text
cargo 1.66.0-nightly (3cdf1ab25 2022-10-07)
release: 1.66.0-nightly
commit-hash: 3cdf1ab25dc4fe56f890e8c7330d53a23ad905d3
commit-date: 2022-10-07
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by epage** [comment] 2022-10-12 22:31
A common workaround is to have a "workspace hack" which enables all of the features for you.  For example, see https://crates.io/crates/cargo-hakari.

**Comment by epage** [comment] 2022-10-12 22:33
This looks to be a duplicate of #4463.  If that is a mistake, let us know and we can re-open,.

**Closed by epage** 2022-10-12 22:33 UTC
Labels: C-bug

**Comment by sleiner** [comment] 2022-10-16 09:11
Hi @epage,

> This looks to be a duplicate of https://github.com/rust-lang/cargo/issues/4463.

Yes - that's exactly the issue! Thanks for pointing me to it 😊

> A common workaround is to have a "workspace hack" which enables all of the features for you. For example, see https://crates.io/crates/cargo-hakari.

For my use case, I prefer crate-specific feature selection (to be speaking in terms of #4463). So I will likely build a fairly simple `xtask` that issues a single `cargo build` target for each call :-)
