### ISSUE TITLE
build.rs scripts are locked to host crate debug/release settings

### ISSUE THREAD

**Issue by jamesmunns** [rust-lang/cargo#3903] opened 2017-04-06 11:35 UTC
Hello,

I am working on a project that uses bindgen to generate a pretty significant amount of bindings (produces ~35k lines of rust). I noticed that this process was very slow in debug mode (5 minutes), and very fast in release mode (10 seconds). Here is an example of what I mean (both release and debug have been built before, so only the build.rs actions are re-triggered):

```bash
root@c34a43368c3b:/host/smooth_blue# touch build.rs 
root@c34a43368c3b:/host/smooth_blue# xargo build --release --target thumbv7em-none-eabihf
   Compiling smooth_blue v0.1.0 (file:///host/smooth_blue)
    Finished release [optimized] target(s) in 10.47 secs


root@c34a43368c3b:/host/smooth_blue# touch build.rs 
root@c34a43368c3b:/host/smooth_blue# xargo build --target thumbv7em-none-eabihf
   Compiling smooth_blue v0.1.0 (file:///host/smooth_blue)
    Finished dev [unoptimized + debuginfo] target(s) in 311.79 secs
```
For reference, you can see the setup in this repo: https://github.com/jamesmunns/nrf52dk-sys (let me know if you need help reproducing, this repo is still a WIP).

In my opinion, it would make sense to default to using release mode for `build.rs` scripts, perhaps that could be overriden in the `cargo.toml`. In either way, it would be nice to have a way to set release mode for `build.rs` independently from the host crate.

**Comment by jamesmunns** [comment] 2017-04-06 11:35
Tagging @SimonSapin since he suggested I open an issue.

**Comment by SimonSapin** [comment] 2017-04-06 12:42
This could tie maybe into Firefox’s request to have different settings that are currently in "profiles" (specifically enabling debug assertions and checked arithmetic) for different crates.

**Comment by alexcrichton** [comment] 2017-04-07 02:54
Thanks for the report! I believe though that this is a dupe of https://github.com/rust-lang/cargo/issues/2424, so closing in favor of that.

**Closed by alexcrichton** 2017-04-07 02:54 UTC
