### ISSUE TITLE
Transitive dependency enabled with feature flags not vendored or fetched properly

### ISSUE THREAD

**Issue by ePirat** [rust-lang/cargo#8812] opened 2020-10-27 19:28 UTC
**Problem**
When using `fetch` or `vendor` commands, its impossible to indicate feature flags. Dependencies that
are only needed for transitive dependencies when specific features are enabled are not downloaded
during `fetch` or `vendor` causing later cargo runs with `--offline` to fail.

As an example you can check with cargo-c before https://github.com/lu-zero/cargo-c/commit/39a7021f96bc49d03fb5b84d1daf31074878f98d.

**Steps**

1. Make sure cargo has nothing already downloaded, for example by removing it: `rm -rf ~/.cargo/registry/*`
1. `git clone https://github.com/lu-zero/cargo-c.git`
2. `git checkout v0.6.15`
3. `cargo fetch`
4. `cargo build --features=cargo/vendored-openssl --release --offline`

Fails with:

```
error: failed to download `openssl-src v111.12.0+1.1.1h`

Caused by:
  can't make HTTP request in the offline mode
```

**Possible Solution(s)**

This was worked-around by https://github.com/lu-zero/cargo-c/commit/39a7021f96bc49d03fb5b84d1daf31074878f98d

**Notes**

Output of `cargo version`: cargo 1.47.0 (f3c7e066a 2020-08-28)

**Comment by ehuss** [comment] 2020-10-27 19:39
Thanks for the report!  This is a duplicate of #3629, so closing in favor of that.

**Closed by ehuss** 2020-10-27 19:39 UTC
Labels: C-bug
