### ISSUE TITLE
Using build.rustflags is awkward right now

### ISSUE THREAD

**Issue by CamJN** [rust-lang/cargo#3052] opened 2016-08-28 19:59 UTC
Based on https://github.com/rust-lang/cargo/issues/2535 and https://github.com/rust-lang/rust/pull/23238 and https://github.com/rust-lang/rust/issues/13841. I thought I could add 

```
[build]
rustflags = ["-C target-cpu=native"]
```

to my ~/.cargo/config file to pass that flag to my builds. But that breaks everything. Turns out I have to use `["-C", "target-cpu=native"]` which is weird but it works, so w/e. However when I run `cargo build --verbose` I noticed that the `-C target-cpu=native` flag gets passed to rustc twice in immediate succession. ie: `rustc src/main.rs --crate-name min --crate-type bin -g --out-dir /Users/camdennarzt/Developer/Rust/min/target/debug --emit=dep-info,link -L dependency=/Users/camdennarzt/Developer/Rust/min/target/debug -L dependency=/Users/camdennarzt/Developer/Rust/min/target/debug/deps -C target-cpu=native -C target-cpu=native`

rustc: 1.11.0
cargo: 0.11.0 (259324c 2016-05-20)
uname -a: Darwin SECUR-T.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Comment by nagisa** [comment] 2016-08-28 20:33
"-C target-cpu=native" is a single argument (i.e. shell does not split them for you), so what the target binary really receives is not `"rustc" "-C" "target-cpu=native"` but `"rustc" "-C target-cpu=native"` which is completely different both behaviour and semantics wise.

Alas, you cannot do such splitting either, because that would preclude people from passing over stuff (i.e. filenames) with spaces in it.

**Comment by CamJN** [comment] 2016-08-28 23:15
I dunno, I would expect that the command is simply concatenated together and passed to the shell, as that's less work (a huge priority of cargo's) and more flexible. You can pass files with spaces in them the same way as people have done for my entire life, by escaping the space with `\`. 

Either way I think we can agree that passing the flag twice is wrong.

**Comment by alexcrichton** [comment] 2016-08-29 16:44
@CamJN did you happen to also have `RUSTFLAGS` or `CARGO_BUILD_RUSTFLAGS` environment variables set at the time? Passing twice definitely seems wrong, and I couldn't reproduce locally unfortunately.

Also we can and should accept configuration like:

```toml
[build]
rustflags = "-C target-cpu=native"
```

99% of the time splitting on spaces is all you want, and the list (`[]`-syntax) is there if you need to pass an argument with spaces in it.

**Comment by CamJN** [comment] 2016-08-30 22:39
@alexcrichton nope, both RUSTFLAGS and CARGO_BUILD_RUSTFLAGS are unset.

**Comment by alexcrichton** [comment] 2016-08-31 16:47
Weird! In any case I'm going to tag this as an easy bug as it should be pretty easy to knock out. There's basically a point where we call `get_list` or something like that for the `build.rustflags` configuration key, and we just need to also call `get_string` (or similar) in the error case. The string version would then split on spaces.

**Comment by jhbabon** [comment] 2016-09-09 18:05
If the config with the `rustflags` is in the home directory maybe the problem is the same as in this issue https://github.com/rust-lang/cargo/issues/3070

**Comment by CamJN** [comment] 2016-09-09 18:08
Yup, that's the same issue.

**Comment by dgellow** [comment] 2017-01-25 19:52
Is this still an issue? I can see that the PR #3356 has been merged

**Comment by alexcrichton** [comment] 2017-01-25 20:00
Indeed!

**Closed by alexcrichton** 2017-01-25 20:00 UTC
Labels: E-easy
