### ISSUE TITLE
Cargo initializes a new git repo within existing git repo when using a deep/path/to/project

### ISSUE THREAD

**Issue by aryzing** [rust-lang/cargo#11946] opened 2023-04-08 13:17 UTC
### Problem

I'm trying to understand whether cargo's behavior when creating a new project inside a git repo is working as intended. When creating a new project at the top level of an existing repo, it does not initialize a new git repo within the created project. However, when initializing a new project deep within an existing git repo, e.g., `cargo new deep/path/to/project`, a new git repo will be initialized despite the project being inside an already existing git repo.

### Steps

```bash
# create in project at root of git repo
cd /repo
git init # creates /repo/.git
cargo new foo # no git repo created inside /repo/foo

# create project in subdir of git repo
cd /repo2
git init # creates /repo2/.git
cargo new foo/bar/baz # initializes new git repo at /repo2/foo/bar/baz/.git
```

### Possible Solution(s)

If this behavior is intended, perhaps doc update will be enough?

### Version

```text
cargo 1.68.2 (6feb7c9cf 2023-03-26)
```

**Comment by hi-rustin** [comment] 2023-04-08 14:14
Duplicate of https://github.com/rust-lang/cargo/issues/10981

It is similar to this issue.

**Comment by weihanglo** [comment] 2023-04-09 01:35
Thanks for the report. As @hi-rustin mentioned this is somewhat a duplicate. Let's track the issue there :)

**Closed** 2023-04-09 01:35 UTC
Labels: C-bug
