### ISSUE TITLE
cargo publish fails with mysterious ValueAfterTable error

### ISSUE THREAD

**Issue by TedDriggs** [rust-lang/cargo#4093] opened 2017-05-24 17:43 UTC
I ran into this today on cargo 0.20.0-nightly (397359840 2017-05-18)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: cargo::core::package::Package::to_registry_toml
  10: cargo::ops::cargo_package::package
  11: cargo::ops::registry::publish
  12: cargo::try_execute_builtin_command
  13: cargo::execute
  14: cargo::call_main_without_stdin
  15: cargo::main
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start
```

For some reason, [this commit](https://github.com/TedDriggs/darling/commit/a14ac7c9b68d2d6641542224e394299b2e826483) fixed the issue. I don't think the old data was invalid TOML, so I'm not sure what went wrong here.

**Comment by alexcrichton** [comment] 2017-05-24 19:59
Thanks for the report! I believe this is a dupe of https://github.com/rust-lang/cargo/issues/4081 which should soon make its way into the nightlies!

**Closed by alexcrichton** 2017-05-24 19:59 UTC
