### ISSUE TITLE
Resolver 2.0 unifying features when doing cargo build

### ISSUE THREAD

**Issue by huguesBouvier** [rust-lang/cargo#10423] opened 2022-02-25 01:29 UTC
### Problem

I have a **crate a** that depends on **crate b**.
 **crate b** has a feature flag test.

**crate a** has the following in Cargo.toml:
```
[package]
name = "cratea"
version = "0.1.0"
edition = "2021"

[dependencies]
crateb = { path = "../crateb "  }
[dev-dependencies]
crateb = { path = "../crateb ", features = ["tests"]  }
```
When I do **cargo build** with 2021 edition,  I expect crateb to be build without the feature tests but it looks like it is still unifying.

Is there a possible workaround?

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 18.04 (bionic) [64-bit]
```

**Comment by ehuss** [comment] 2022-02-25 02:01
Can you provide a complete example, and run with `cargo build -v` and show the output?  There should not be any `--cfg` flags passed to `crateb`.

**Comment by huguesBouvier** [comment] 2022-02-25 18:49
Thanks for the prompt reply. I found the issue.
I have a workspace, I had to specify the resolver=2 to my workspace and it worked.
![image](https://user-images.githubusercontent.com/33438817/155771066-c034b0c9-7df0-4d2a-b0ed-14d76b48c5ff.png)

**Comment by ehuss** [comment] 2022-02-25 20:58
Ah, glad it got figured out. I'm going to close this as a duplicate of #10112 then.

**Closed by ehuss** 2022-02-25 20:58 UTC
Labels: C-bug
