### ISSUE TITLE
`cargo metadata`'s `resolved` output includes features from all packages in workspace, cannot be filtered.

### ISSUE THREAD

**Issue by JarredAllen** [rust-lang/cargo#12735] opened 2023-09-25 17:41 UTC
### Problem

I'm working on a tool that wraps multiple `cargo build` invocations and trying to make a progress bar for the overall output. Towards this end, I need to know, for each invocation, how many artifacts it needs to build, which I believe is the point of the `cargo metadata` command (and corresponding `cargo_metadata` crate that wraps it for Rust).

The problem is that I'm building in a workspace where I have something like the following setup:

* Crate A exists in my workspace.
* Crate B has an optional dependency on Crate A, if the `a` feature is supplied.
* Crate C depends on Crate B but doesn't require the `a` feature.
* Crate D depends on Crate B and requires the `a` feature.

When I run `cargo metadata`, it builds the dependency tree for the entire workspace, so I see that Crate B depends on Crate A (because Crate D requires the feature, and features are additive). However, when I run `cargo build -p C` to only build Crate C, the feature is not enabled (because Crate D doesn't appear) so only crates B and C are built. Thus, naively reading the dependency tree provided says 3 crates, but then cargo build only reports 2 crates.

The docs for `cargo metadata` say the following about how it decides which features are enabled:

> The enabled features are based on the enabled features for the "current" package. Inactivated optional dependencies are not listed.

I want to set this "current package" to Crate C, which will set the features based on that. However, as far as I can tell, `cargo metadata` always sets this "current package" to be every package in the workspace, and it takes all the features from combining every crate. This even happens if I use `--manifest-path` to explicitly specify the `Cargo.toml` file from Crate C.

### Proposed Solution

My preferred interface would be to add a `--package` option to `cargo metadata` which allows you to explicitly filter packages in the workspace, repeatable if you want to have multiple packages at the root of your dependency tree.

If combined with `--no-deps`, then only the explicitly-listed packages are included in the output. Otherwise, it outputs the listed packages and all of their transitive dependencies, from the workspace or from outside. I primarily care about the `resolve` field, and don't care much how this interacts with the `packages` field.

If only one `--package` argument is required, then any features listed in a `--features` argument applies to that one package (e.g. `cargo metadata --package my_package --features foo,bar` will enable the `foo` and `bar` features of `my_package`).

Beyond those two, I think the interactions with the other existing flags and arguments are straightforward and uncomplicated.

### Notes

[Coming from this rust-users forum thread](https://users.rust-lang.org/t/how-to-set-current-package-in-cargo-metadatas-resolve-output/100282), I assume what I want isn't currently possible based on the lack of responses, please correct me if I'm wrong.

**Comment by epage** [comment] 2023-09-25 18:28
It looks like this is a duplicate of #7754.  Closing in favor of that.  If there is some difference I missed, let us know!

**Closed by epage** 2023-09-25 18:28 UTC
Labels: Command-metadata, C-feature-request, S-triage
