### ISSUE TITLE
`required-features` doesn't work with non-top-level features

### ISSUE THREAD

**Issue by sgrif** [rust-lang/cargo#3727] opened 2017-02-17 14:32 UTC
When adding the following to `Cargo.toml`

```toml
[[test]]
name = "tests"
path = "tests/test.rs"
required-features = ["diesel/postgres", "diesel/sqlite"]
```

I'd expect that `cargo test --features "diesel/postgres diesel/sqlite"` would run the tests. Instead, it makes it impossible to run them. That command runs the tests (and enables the features) properly when the `required-features` line is removed.

As an aside, the documentation is unclear as to whether `required-features` enables those features for a given target, or whether it skips it when those features aren't enabled.

**Comment by alexcrichton** [comment] 2017-02-17 15:20
cc @jbendig, mind taking a look?

**Comment by jbendig** [comment] 2017-02-17 19:01
I'll take a look at this. I should have time later this afternoon.

**Comment by alexcrichton** [comment] 2017-02-17 19:05
Thanks @jbendig! Lemme know though if it takes up too much time and I can take over

**Comment by jbendig** [comment] 2017-02-18 00:44
I've been able to reproduce this issue. It's because dependency based features are being resolved before being checked against `required-features`. If you pass `--features "diesel/postgres diesel/sqlite"`, then `required-features` will only see the "diesel" feature as enabled. 

This is easy enough to fix with respect to the `--features` flag but I think there is a deeper problem here. For example, the following should build foo without the `--features` flag because the "bar/a" feature is enabled:
```toml
[dependencies]
bar = { path = "bar", features = ["a"] }

[[bin]]
name = "foo"
required-features = ["bar/a"]
```
I'm still investigating the best way to approach this.

Regarding the documentation, I can see where the text is not clear as it should be. I'll try to change it after this issue is fixed.

**Comment by jbendig** [comment] 2017-02-23 16:47
@sgrif This should be fixed in the newest nightly. Can you please see if it work for you? If not, I'd be happy to take another look.

**Comment by sgrif** [comment] 2017-02-24 00:16
Sure, I'll take a look tomorrow

**Comment by cyplo** [comment] 2017-09-21 10:01
Any news on this one - does it work as expected now ?

**Comment by sgrif** [comment] 2017-09-21 12:55
I think so. Should `required-features` for `[[test]]` apply to examples as well?

**Comment by alexcrichton** [comment] 2017-09-21 14:48
@sgrif hm can you clarify? What do you mean about tests applying to examples?

**Comment by sgrif** [comment] 2017-09-21 14:56
If I have the entry in my `Cargo.toml` listed in the original issue, and I run `cargo test`, it will still fail because there are files in `examples` which need those features to compile as well.

**Comment by alexcrichton** [comment] 2017-09-21 14:57
Does adding `required-features` to the `[[example]]` sections work?

**Comment by sgrif** [comment] 2017-09-21 16:30
Yes, but that would require one entry per-example file, requiring me to list every example explicitly in `Cargo.toml` which wasn't otherwise required.

**Comment by alexcrichton** [comment] 2017-09-21 17:30
Indeed it would! That's covered by https://github.com/rust-lang/cargo/issues/4013, so I'm going to close this now

**Closed by alexcrichton** 2017-09-21 17:30 UTC
Labels: A-features
