### ISSUE TITLE
Unnecessary index fetching upon patching two dependencies with same package name

### ISSUE THREAD

**Issue by ldm0** [rust-lang/cargo#13862] opened 2024-05-04 23:24 UTC
### Problem

If you have two patches on two dependencies with same package name, you will see `Updating crates.io index` every time you run cargo check. The index update is unnecessary and slows down development speed. 

### Steps

Simple reproduction repo: 
https://github.com/ldm0/cargo-bug-repo/tree/31fb297e58ffa3be877062940a300883d2cb580a

1. Run cargo check
2. Run cargo check (you will still see `Updating crates.io index`)

### Possible Solution(s)

I'll file a fix PR later.

### Version

```text
Can't find a cargo version which doesn't have this issue.
```

**Comment by epage** [comment] 2024-05-06 03:55
Sounds like this is a duplicate of #13405.  Is that right?

**Comment by ldm0** [comment] 2024-05-06 04:24
Yeah, the root cause is the same. Bug behaviour differs though.

**Comment by weihanglo** [comment] 2024-05-19 14:57
Since <https://github.com/rust-lang/cargo/pull/13572> is merged, I'll go ahead and close this as resolved. Let us know if things are still wrong. Thank you.

**Closed by weihanglo** 2024-05-19 14:57 UTC
Labels: C-bug, A-dependency-resolution, A-lockfile, S-triage
