### ISSUE TITLE
Cargo doesn't run doctest for staticlib

### ISSUE THREAD

**Issue by rasendubi** [rust-lang/cargo#2442] opened 2016-03-05 22:07 UTC
Steps to reproduce:
- `cargo new mylib`
- open `src/lib.rs` and add:
```
/// ```
/// assert_eq!(1, 3);
/// ```
pub fn func() {
}
```
- add following to `Cargo.toml`:
```
[lib]
crate-type = ["staticlib"]
```
- `cargo test`

Build passes. Doctests aren't run.

**Comment by alexcrichton** [comment] 2016-03-06 07:15
Ah yeah this is probably just something that needs to be filtered when we run doctests, I think we already handle other pieces specially?

**Comment by jespino** [comment] 2016-03-07 06:58
I think this is the correct behavior, this is filtered here: https://github.com/rust-lang/cargo/blob/8b0c007ac1c4b705570479326bb9be215fff2c76/src/cargo/core/manifest.rs#L312

and reasoned here https://github.com/rust-lang/cargo/blob/8b0c007ac1c4b705570479326bb9be215fff2c76/src/cargo/ops/cargo_test.rs#L147

If cargo run doctests will fail in any test that needs to be linked to the module.

**Comment by alexcrichton** [comment] 2016-03-07 07:37
Hm weird, so shouldn't we already handle this in that case?

**Comment by jespino** [comment] 2016-03-07 08:34
We can add a warning when you run tests and doctested function return false.

**Comment by alexcrichton** [comment] 2016-03-07 17:12
In theory given that logic we shouldn't even attempt to test staticlibs b/c only rlibs are tested. We may just be forgetting a conditional somewhere to check that method return value.

**Comment by jespino** [comment] 2016-03-07 17:31
Not really, the only problem with staticlibs is on "doctests" not on code tests. The problem is related with linking, then, to run doctests with staticlibs you have to compile it in another linkable format (lib or rlib). An approach (a bit weird in my opinion) when you dont have lib or rlib in your crate-type, compile it anyway and run doctests using it.

I think the solution is to warn the user that doctests aren't run when you don't have one of the doctesteable crate types.

**Comment by rasendubi** [comment] 2016-03-07 17:41
From the user point of view, I advocate producing a warning. That's enough to resolve the issue as nobody will be surprised by the behavior.

I don't like silently producing lib or rlib as I found that may change compilation result. (My library once failed to build as rlib due to linkage error to `_Unwind_Resume`. staticlib worked fine.)

**Comment by alexcrichton** [comment] 2016-03-07 19:05
Wait whoa, I'm sorry! I misread this bug and thought it was saying that we were trying to run doctests but they were failing (legitimately).

This is intentional behavior in that case because as pointed out by @jespino it's fundamentally not possible to run documentation tests for staticlibs (like executables). We tend to not print warnings that aren't really actionable (there's no great way to solve this), so this is currently intended, so closing.

**Closed by alexcrichton** 2016-03-07 19:05 UTC
Labels: E-easy
