### ISSUE TITLE
document external cargo subcommand PATH precedence

### ISSUE THREAD

**Issue by eval-exec** [rust-lang/cargo#13194] opened 2023-12-22 09:25 UTC
### Problem

I have encountered an issue with the `cargo nextest` subcommand where it does not select the expected subcommand's version. 

### Steps

Here are the details of the problem:

1. I have `cargo-nextest` in my PATH, located at `/nix/store/3yl7vgm2qkp7skr5gskbfd457f6g43cg-cargo-nextest-0.9.66/bin/cargo-nextest`, and its version is 0.9.66.
```bash
bash-5.2$ which cargo-nextest
/nix/store/3yl7vgm2qkp7skr5gskbfd457f6g43cg-cargo-nextest-0.9.66/bin/cargo-nextest
```

3. Additionally, I have `cargo-nextest` installed in `~/.cargo/bin`, and its version is 0.9.59.
```bash
bash-5.2$ ~/.cargo/bin/cargo-nextest --version
cargo-nextest 0.9.59
```

4. Running `~/.cargo/bin/cargo-nextest --version` confirms that the version installed in `~/.cargo/bin` is indeed 0.9.59.

5. However, when I execute `cargo nextest --version`, it incorrectly selects version 0.9.59 from `~/.cargo/bin`, instead of the desired version 0.9.66 from `/nix/store/3yl7vgm2qkp7skr5gskbfd457f6g43cg-cargo-nextest-0.9.66/bin/cargo-nextest`.
```bash
bash-5.2$ cargo nextest --version
cargo-nextest-nextest 0.9.59
```

This behavior seems inconsistent and unexpected. It would be helpful if the `cargo` command could prioritize the version in the path `/nix/store/3yl7vgm2qkp7skr5gskbfd457f6g43cg-cargo-nextest-0.9.66/bin` when invoking the `cargo nextest` subcommand.

Thank you for your attention to this issue, and please let me know if you need any further information to reproduce or investigate the problem.

### Version

```text
cargo 1.72.1 (103a7ff2e 2023-08-15)
release: 1.72.1
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: NixOS 24.5.0 [64-bit]
```

**Comment by linyihai** [comment] 2023-12-22 09:37
Hello,

`cargo-nextest` is not the cargo built-in command and this issue may not be related to cargo.

And I see you desired `cargo` is in `/nix/store/...`,  is there something like `.env` to activate it ?

**Comment by epage** [comment] 2023-12-22 12:25
This is a concern not with cargo-nextest but with how third-party subcommands are loaded.

On mobile so can't look everything up but cargo intentionally prefers the copy of packages it has installed. You can customize this by putting cargo's bin directory in PATH. If cargo sees it there, it will respect the users precedence.

**Comment by ehuss** [comment] 2023-12-22 15:56
Thanks for the report! As @epage mentioned, I believe cargo looks at PATH to determine the priority, so you can put `~/.cargo/bin` later in the PATH. Closing as a duplicate of #11020 and #6507.

**Comment by weihanglo** [comment] 2023-12-22 16:04
Have we documented this behavior in The Cargo Book? If not, I would like to propose this as a documentation issue.

https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/bin/cargo/main.rs#L247-L270

**Comment by ehuss** [comment] 2023-12-22 17:53
Updating the documentation sounds good to me!

**Comment by linyihai** [comment] 2023-12-25 03:47
@rustbot claim

I plan to add  `this behavior`  in the [custom-subcommands](https://doc.rust-lang.org/cargo/reference/external-tools.html?highlight=custom#custom-subcommands) section. (a `note block` in the last )

**Closed** 2023-12-27 12:39 UTC
Labels: A-documenting-cargo-itself, S-accepted, A-custom-subcommands
