### ISSUE TITLE
Failure for some target values: panic unwrapping None

### ISSUE THREAD

**Issue by drewcrawford** [rust-lang/cargo#1237] opened 2015-01-28 20:10 UTC
This seems suspiciously close to #442, although that one's closed and 6 months old.

cargo nightly panics when given a target other than the host:

```bash
$ cargo build --target=armv7-apple-ios --verbose
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:361
```

works fine for host:

```bash
$ cargo build --target=x86_64-apple-darwin --verbose
       Fresh lazy_static v0.1.7
       Fresh myproject v0.0.1 (file:///Users/drew/Code/myproject)
```

Version

```bash
$ cargo --version
cargo 0.0.1-pre-nightly (e20caae 2015-01-26 02:53:23 +0000)
$ rustc --version
rustc 1.0.0-dev (d15192317 2015-01-25 16:09:48 +0000)
```

**Comment by alexcrichton** [comment] 2015-01-29 06:46
Closing as a dupe of https://github.com/rust-lang/cargo/issues/1234, but thanks for the report!

**Closed by alexcrichton** 2015-01-29 06:46 UTC
