### ISSUE TITLE
`workspace = true` dependencies don't use `package` renaming

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#14673] opened 2024-10-11 13:14 UTC
### Problem

In some crates within a workspace I want to load a workspace-dependency while renaming it (e.g. to test macro hygienity), my expectation was that with both `workspace = true` and `package` specified this would work and use the `package` as the key to look in the `[workspace.dependencies]` table, but it just uses the dependency key still.

### Steps

```console
> cat >>Cargo.toml <<-END
[workspace]
resolver = "2"
END

> cargo new foo --lib && cargo new bar
    Creating library `foo` package
      Adding `foo` as member of workspace at `/tmp/scratch.rust.2024-10-11T15-10.izaVqc`
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
    Creating binary (application) `bar` package
      Adding `bar` as member of workspace at `/tmp/scratch.rust.2024-10-11T15-10.izaVqc`
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

> cat >>Cargo.toml <<-END
[workspace.dependencies]
foo.path = "foo"
END

> cat >>bar/Cargo.toml <<-END
my-foo = { package = "foo", workspace = true }
END

> cargo check
error: failed to load manifest for workspace member `/tmp/scratch.rust.2024-10-11T15-10.izaVqc/bar`
referenced by workspace at `/tmp/scratch.rust.2024-10-11T15-10.izaVqc/Cargo.toml`

Caused by:
  failed to parse manifest at `/tmp/scratch.rust.2024-10-11T15-10.izaVqc/bar/Cargo.toml`

Caused by:
  error inheriting `my-foo` from workspace root manifest's `workspace.dependencies.my-foo`

Caused by:
  `dependency.my-foo` was not found in `workspace.dependencies`
```

### Version

cargo 1.83.0-nightly (15fbd2f60 2024-10-08)
release: 1.83.0-nightly
commit-hash: 15fbd2f607d4defc87053b8b76bf5038f2483cf4
commit-date: 2024-10-08
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: NixOS 24.5.0 [64-bit]

**Comment by epage** [comment] 2024-10-11 14:08
I believe this is a duplicate of #12546.  If there is something I'm missing in how this is different, let us know!

**Closed by epage** 2024-10-11 14:08 UTC
Labels: C-bug, A-workspace-inheritance, S-triage
