### ISSUE TITLE
Changing RUSTFLAGS to use JSON errors causes whole rebuild of a project

### ISSUE THREAD

**Issue by White-Oak** [rust-lang/cargo#3095] opened 2016-09-15 11:22 UTC
I beleive it's intended, but we use RUSTFLAGS to provide `--error-format=json` to rustc to use JSON errors in a linter (issue https://github.com/AtomLinter/linter-rust/issues/77), so whenever I switch between terminal and editor, cargo rebuilds the whole project, which can take a long time.

I've heard that JSON errors are to be in stable soon -- will there be some kind of cargo switch to avoid changing RUSTFLAGS to avoid the rebuilding of a project?

**Comment by matklad** [comment] 2016-09-15 23:51
>- will there be some kind of cargo switch to avoid changing RUSTFLAGS to avoid the rebuilding of a project?

Yes it will: #3000!

**Comment by alexcrichton** [comment] 2016-09-26 17:33
This is indeed a problem! And intended to be solved with https://github.com/rust-lang/cargo/pull/3000, so closing in favor of that.

(in the sense that this is intended behavior today but the intended implementation strategy is #3000)

**Closed by alexcrichton** 2016-09-26 17:33 UTC
