### ISSUE TITLE
During `cargo build --verbose`, also output custom build command lines and output

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/cargo#1324] opened 2015-02-19 16:44 UTC
Currently, custom build commands are not printed and their output appears to also be only available to Cargo. It would be great if compiling with `--verbose` also printed that output.

In Servo, we very frequently shell out to a makefile in these custom build steps, and not being able to see the steps makes it quite difficult to debug them (especially since it can be challenging to recreate the exact lines that cargo passes in, due to the hash-specific directory names, etc.).

**Comment by alexcrichton** [comment] 2015-02-19 19:32
Dupe of #1106 (will copy comment over)

**Closed** 2015-02-19 19:32 UTC
