### ISSUE TITLE
Changing `profile.*.lto` in Cargo.toml shouldn't rebuild everything

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#3244] opened 2016-11-01 17:39 UTC
Neither should adding, modifying or removing linker flags via `-C link-arg` or `-C link-args` in `.cargo/config` (`build.rustflags` or `target.*.rustflags`).

These only affect the compilation of the top crate.

**Comment by alexcrichton** [comment] 2016-11-01 23:08
I'd prefer to keep Cargo from parsing `rustflags` and trying to learn about specific flags, but Cargo already has intrusive knowledge of lto to fixing that seems reasonable to me!

**Comment by bluss** [comment] 2016-11-03 10:53
codegen-units is the same kind of thing, isn't it. Nothing needs to be rebuilt.

In rustbuild, I would like it to not rebuild anything when `-Ccodegen-units=x` is added in rustflags. (Maybe rustbuild has some specific option for this).

**Comment by jonas-schievink** [comment] 2020-08-31 11:54
We just ran into this one again. It seems that adding `lto = true` to the `dev` profile means that switching between `cargo build` and `cargo build --tests` will now rebuild the entire crate graph every time, which is pretty unfortunate (and was also fairly hard to track down to this issue).

I think this should be considered a bug instead of a feature request.

**Comment by ehuss** [comment] 2020-09-01 17:08
@jonas-schievink That sounds like a different issue. This issue is about changing the `LTO` setting.  What you're mentioning sounds like a rebuild-detection issue when switching between commands.  Can you file a new issue with a reproduction? Also, beware, there has been a recent change which might affect the behavior that will appear in the next nightly.

**Comment by jonas-schievink** [comment] 2020-09-01 18:03
@ehuss Okay, filed https://github.com/rust-lang/cargo/issues/8669

**Comment by epage** [comment] 2024-12-06 16:54
Since this was created, #8192 was merged which optimized LTO builds by doing work in dependencies that isn't needed.  This makes LTO affect dependencies and not just the final artifact.  There are times where sharing *could* occur which is being tracked in #8343.  The lack of sharing can also cause surprising rebuilds like in #8762.

rust-lang/rfcs#3310 was proposed as a general mechanism for specifying final-artifact-only rustflags.  However, that was postpined.

**Comment by epage** [comment] 2024-12-06 16:55
Between LTO changing dependencies and the tracking of link-only arguments in #4349, I'm going to close this.

**Closed by epage** 2024-12-06 16:55 UTC
Labels: A-linkage, Command-build, C-feature-request, A-rebuild-detection, S-needs-mentor, A-lto
