### ISSUE TITLE
SSL error during fetching of the index

### ISSUE THREAD

**Issue by astynax** [rust-lang/cargo#1157] opened 2015-01-13 13:22 UTC
I have a SSL error during fetching of the index:
```shell
$ cargo --version
cargo 0.0.1-pre-nightly (c2c6f40 2015-01-09 23:38:12 +0000)

$ cargo fetch --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized
```

**Comment by alexcrichton** [comment] 2015-01-13 15:40
What platform/OS are you running on? Also, is this error reproducible?

**Comment by astynax** [comment] 2015-01-13 16:10
Error is reproducible on my work machine (Ubuntu 12.04 32bit; Internet access is squid-proxied, but environment is properly configured).
I was tried to reproduce this error on my home machine (Ubuntu 12.04 64bit, direct Internet connection) - cargo works as should.

**Comment by alexcrichton** [comment] 2015-01-13 16:16
Do you have Cargo configured to use an HTTP proxy? Currently we don't respect proxies for git requests: https://github.com/rust-lang/cargo/issues/636

**Comment by astynax** [comment] 2015-01-13 16:34
I was tried to launch my cargo over the ``proxychain`` (as is was advised in #636), but it isn't works for me...

**Comment by alexcrichton** [comment] 2015-01-13 16:45
Sorry I'm not quite sure what `proxychain` is, but do you have Cargo configured to use an HTTP proxy?

**Comment by astynax** [comment] 2015-01-13 17:05
Yes, Cargo configured to use HTTP(S) proxy.

**Comment by alexcrichton** [comment] 2015-01-13 17:08
Ok, in that case I think this is a dupe of #636 because it sounds like libgit2 just isn't using the proxy you've configured.

**Closed by alexcrichton** 2015-01-13 17:08 UTC

**Comment by nwin** [comment] 2015-02-05 11:17
Same error here, no proxy. OSX

     [12] SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized

    $ cargo --version
    cargo 0.0.1-pre-nightly (453ae9f 2015-01-29 00:56:56 +0000)

**Comment by alexcrichton** [comment] 2015-02-05 17:40
@nwin is it reproducible for you or intermittent? If you don't have a proxy, are you sure there's no firewall in play?

**Comment by nwin** [comment] 2015-02-06 08:18
Ok I think it is a problem with my connection. Using a VPN solved it.

**Comment by msiemens** [comment] 2015-03-30 01:21
I got the same error message when trying to work offline (laptop with WiFi disabled, Fedora 21, 64 bit)
