### ISSUE TITLE
Add an option to use relative paths or full paths when building projects

### ISSUE THREAD

**Issue by tenderlove** [rust-lang/cargo#11043] opened 2022-09-01 18:57 UTC
### Problem

We are using Rust / Cargo to develop a JIT for Ruby called YJIT.  [YJIT is kind of a sub project of the Ruby programming language](https://github.com/ruby/ruby/tree/master/yjit).  The Ruby programming language is written in C and uses normal C build tools (`autoconf`, `make`, etc).  [YJIT is a subproject](https://github.com/ruby/ruby/tree/master/yjit), but we've integrated the build in to the normal Ruby compilation process.  However, if there is any problem compiling the Rust files, the reported file will be relative to the YJIT directory and not the working directory.  This causes a problem with Vim (and apparently other IDEs https://github.com/rust-lang/cargo/issues/8506) because they can't find the file.

Here is a screenshot to kind of illustrate the problem:

<img width="1641" alt="ruby — fish :home:aaron:git:ruby — ssh whiteclaw — 188×59 2022-09-01 11-50-08" src="https://user-images.githubusercontent.com/3124/187990994-fb58ac9a-90c1-4462-b36d-ea70c83d4e8e.png">

I would like a command line option to ask `Cargo` to report either full paths, or paths relative to the current working directory.

### Proposed Solution

I would like a command line option that allows me to see files either as a full path, or as a path relative to the current working directory.

### Notes

I found [this issue](https://github.com/rust-lang/cargo/issues/8506) which is similar, and they said it should be a feature request instead of a bug, so I'm filing a feature request.

We have a constraint in the Ruby project that we can't just move the `Cargo.toml` file to the root of the directory.  Additionally I spend my time changing the C source code in tandem with Rust source code, so presumably I could keep changing Vim's working directory depending on what I'm editing, but that's kind of onerous.

Thanks for your time!!

**Comment by tenderlove** [comment] 2022-09-01 19:03
Sorry, I should have also mentioned that our Make system is just calling `cargo` with `--manifest-path`.  So without `make` involved, the issue is like this:

<img width="1187" alt="ruby — fish :home:aaron:git:ruby — ssh whiteclaw — 188×59 2022-09-01 12-02-37" src="https://user-images.githubusercontent.com/3124/187992597-c63b21da-1fc0-4809-ab49-0c47af7ebf53.png">

**Comment by weihanglo** [comment] 2022-09-09 21:10
There are some complications about caching artifacts and metadata when changing paths in Cargo. Here is [one thread](https://github.com/rust-lang/cargo/issues/9887) discussing such issue. 

You could check this rustc flag [`--remap-path-prefix`] to see if it works for you. Something like:

```
RUSTFLAGS='--remap-path-prefix =yjit' cargo b
```

[`--remap-path-prefix`]: https://doc.rust-lang.org/stable/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output

**Comment by epage** [comment] 2023-10-19 01:39
This appears to be duplicate of #5450, closing in favor of that.

**Closed by epage** 2023-10-19 01:39 UTC
Labels: A-errors, C-feature-request
