### ISSUE TITLE
cargo for a project becomes unusable after dependency is removed remotely

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/cargo#4799] opened 2017-12-09 17:02 UTC
I'm not entirely sure if my analysis of the situation is correct, but I suddenly became unable to use cargo to build [a project](https://github.com/neosmart/tcpproxy/tree/futures%23671-2):

```
mqudsi@ZBook /m/c/U/M/g/tcpproxy> cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [9/-3] object not found - no match for id (bd665fa9d2e51a8080f01cbaeea4755f0bcb4126)
```

`cargo update` is similarly broken:

```
mqudsi@ZBook /m/c/U/M/g/tcpproxy> cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `abstract-ns`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [9/-3] object not found - no match for id (bd665fa9d2e51a8080f01cbaeea4755f0bcb4126)
```

Removing the cargo registry entirely (`find ~/.cargo/registry/ -delete`) made cargo usable again.

Suggestion: `cargo update` should check for alternate versions of the resource not found.

**Comment by alexcrichton** [comment] 2017-12-10 15:14
I think this is a dupe of https://github.com/rust-lang/cargo/issues/3561, so closing in favor of that.

**Closed by alexcrichton** 2017-12-10 15:14 UTC
