### ISSUE TITLE
Select required sub-modules of a git dependency

### ISSUE THREAD

**Issue by kvark** [rust-lang/cargo#9872] opened 2021-09-03 18:12 UTC
When cargo sees a git dependency, it fetches all the submodules - https://github.com/gfx-rs/wgpu/pull/1903/checks?check_run_id=3508714595#step:5:9

**Describe the problem you are trying to solve**
This can take minutes of CI time, which is a waste if these submodules aren't really needed.

**Describe the solution you'd like**
```toml
foo  = { git = "https://foo.com/foo", submodules = ["x", "y"] }
```

**Notes**
Related to https://github.com/gfx-rs/wgpu/pull/1903

**Comment by ehuss** [comment] 2021-09-03 18:18
Thanks for the request!  I think this is a duplicate of #4247 (and #7987 to a lesser extent), so closing in favor of that.

**Closed by ehuss** 2021-09-03 18:18 UTC
Labels: C-feature-request

**Comment by kvark** [comment] 2021-09-03 19:15
Oh great! I did look for the duplicates and somehow missed these.
