### ISSUE TITLE
Cargo does not track env!("FOO") for rebuilding

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/cargo#3434] opened 2016-12-20 22:21 UTC
Given the code below, I would expect Cargo to rebuild the crate when `FOO` changes, but this currently does not happen. I don't know if Cargo currently has enough information to handle this, though.

```rust
fn foo() -> &'static str {
    env!("FOO")
}
```

**Comment by alexcrichton** [comment] 2016-12-21 00:18
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/2776, so I'm going to close it in favor of that

**Closed by alexcrichton** 2016-12-21 00:18 UTC

**Comment by Imberflur** [comment] 2025-01-03 17:57
For future readers, cargo now tracks these via https://github.com/rust-lang/cargo/pull/8421
