### ISSUE TITLE
Inconsistent data in `cargo metadata`

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#7841] opened 2020-01-28 11:00 UTC
**Problem**

`cargo metadata` produces inconsistent dependency graph (there's an edge to the node which does not exist)

**Steps**

```
$ git clone https://github.com/ChaseElectr/analyzer-panic
$ cd analyzer-panic
$ cargo metadata
```

Notice how the `packages` section has

```
"diesel 1.4.3 (git+https://github.com/ChaseElectr/diesel?branch=1.4.x#066bc412d7ead423e71de811b1dac9428a63712c)"
```

but the `resolve` section has 

```
"diesel 1.4.3 (git+https://github.com/ChaseElectr/diesel?branch=1.4.x#24af5f700c111c2b995953a40f7a262d0872a00d)"
```

**Notes**

This is using master (c326fcb37e7eacbcc1f3671193db133440ea1968) cargo. Here's the gist with various printouts:

https://gist.github.com/matklad/eed0d46f427af5abf3c024cc07c59663

(I've added some printfs to the code which produces metadata)

This is what I gather from that output:

* Cargo.lock uses diesel `#24af5f7`, I assume this is what we want to see.
* `cargo metadata` uses the right `#24af5f7` in the deps section, and the wrong one in the packages section.
* the [`package_map`](https://github.com/rust-lang/cargo/blob/c326fcb37e7eacbcc1f3671193db133440ea1968/src/cargo/ops/cargo_output_metadata.rs#L129-L130) contains the wrong diesel (this I think the bug)
* the [`node_map`](https://github.com/rust-lang/cargo/blob/c326fcb37e7eacbcc1f3671193db133440ea1968/src/cargo/ops/cargo_output_metadata.rs#L137-L146) contains both diesels. 

I haven't looked into this further yet, as I am hoping someone from cargo team immediately knows what's the issue :)

**Comment by ChaseElectr** [comment] 2020-01-31 07:28
I split my demo's commit to make it clear which modify made it wrong, you could check that :p

**Comment by ehuss** [comment] 2020-10-23 19:18
I'm inclined to close this. After further inspection, it looks like the issue is related to specifying both a branch and a revision at the same time.  Cargo specifically warns about this:

```
warning: dependency (diesel) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
warning: dependency (diesel_derives) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
```

Of course it's probably best for Cargo not to stumble on it, but since it isn't supported to start with, I'm not sure it is worth putting time into.  We could change the warning to an error, since it has been around for a few years. 

Does that sounds reasonable?

**Comment by matklad** [comment] 2020-10-23 20:13
Yeah, I think upgrading to an error would be totally OK here. Well, maybe adding some asserts internally to elevate this to an ICE of sorts would also be prudent, but only if that doesn’t require much new logic.

**Comment by UebelAndre** [comment] 2020-12-15 16:07
Hey, any updates here? 😅 🙏

**Closed** 2020-12-16 22:09 UTC
Labels: C-bug, Command-metadata
