### ISSUE TITLE
indirect artifact dependency with non-default target causes panic

### ISSUE THREAD

**Issue by Freax13** [rust-lang/cargo#10647] opened 2022-05-10 16:31 UTC
### Problem

My package uses a dependency  (the upcoming version of [`bootloader`](https://github.com/rust-osdev/bootloader)) which itself has a artifact dependency on another package (`bootloader-x86_64-bios`) with a non-default target (`x86_64-unknown-none`). Trying to compile causes a panic:
```console
$ RUST_BACKTRACE=1 cargo run -p runner -- 
thread 'main' panicked at 'no entry found for key', src/tools/cargo/src/cargo/core/compiler/build_context/target_info.rs:875:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/option.rs:1855:5
   5: <cargo::core::compiler::build_context::target_info::RustcTargetData>::info
   6: <core::iter::adapters::map::Map<std::collections::hash::set::Iter<cargo::core::compiler::compile_kind::CompileKind>, <cargo::core::compiler::compilation::Compilation>::new::{closure#0}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<(cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf), <hashbrown::map::HashMap<cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf, std::collections::hash::map::RandomState> as core::iter::traits::collect::Extend<(cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf)>>::extend<core::iter::adapters::map::Map<std::collections::hash::set::Iter<cargo::core::compiler::compile_kind::CompileKind>, <cargo::core::compiler::compilation::Compilation>::new::{closure#0}>>::{closure#0}>::{closure#0}>
   7: <std::collections::hash::map::HashMap<cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf> as core::iter::traits::collect::FromIterator<(cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf)>>::from_iter::<core::iter::adapters::map::Map<std::collections::hash::set::Iter<cargo::core::compiler::compile_kind::CompileKind>, <cargo::core::compiler::compilation::Compilation>::new::{closure#0}>>
   8: <cargo::core::compiler::compilation::Compilation>::new
   9: <cargo::core::compiler::context::Context>::new
  10: cargo::ops::cargo_compile::compile_ws
  11: cargo::ops::cargo_compile::compile
  12: cargo::ops::cargo_run::run
  13: cargo::commands::run::exec
  14: cargo::cli::main
  15: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps

I setup a small project to reproduce this easily:
1. Clone https://github.com/Freax13/bindeps-failure
2. Run `cargo +nightly build -Z bindeps`

### Notes

AFAICT this code is the root of the problem: It only collects compile kinds for artifact dependencies of direct dependencies of any workspace crate:
https://github.com/rust-lang/cargo/blob/9fa2bba6791f9df06a13dbfe18bf7add9b9b2d1b/src/cargo/core/compiler/build_context/target_info.rs#L796-L819

### Version

```text
cargo 1.60.0 (d1fd9fe 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by ehuss** [comment] 2022-05-10 17:11
Thanks for the detailed report! Yea, your analysis is correct, binary dependencies only work for direct (local) dependencies.  I believe this is a duplicate of #10405, so closing in favor of that.

**Closed by ehuss** 2022-05-10 17:11 UTC
Labels: C-bug
