### ISSUE TITLE
Compilation inconsistency when referencing the same code over path and git/version

### ISSUE THREAD

**Issue by k06a** [rust-lang/cargo#7850] opened 2020-01-31 15:25 UTC
**Problem**
I got the true compilation errors when referenced dependency with `path`. And see no errors when reference over `git` of `version` in TOML file.

**Steps**
Check this demo repo: https://github.com/k06a/usize-issue

**Notes**
Output of `cargo version`:
cargo 1.41.0-nightly (626f0f40e 2019-12-03)

**Comment by ehuss** [comment] 2020-02-01 02:41
This is intentional.  Dependencies are usually built with `--cap-lints=allow` to hide lint warnings (and deny-by-default lints).  Workspace members and path dependencies are not capped. This is done with the intent that you are working on the package and want to see the warnings.

**Comment by k06a** [comment] 2020-02-03 14:42
@ehuss having such kind of problems was highly unexpected. I mean assigning out-of-range values to integral types.

**Comment by weihanglo** [comment] 2023-06-03 20:26
With <https://github.com/rust-lang/cargo/issues/12115>, we may have lint control over warnings from Cargo itself in the future. This issue can gain some benefits from that.

**Comment by weihanglo** [comment] 2023-06-03 20:35
I think this is kinda a duplicate of #5998, and both of them are waiting for the `[lints]` feature stabilization, so that we will have a dedicated documentation for how Cargo handles lints. Close in favor of #5998.

**Closed by weihanglo** 2023-06-03 20:35 UTC
Labels: C-bug, A-documenting-cargo-itself
