### ISSUE TITLE
Cargo doesn't work on Debian 11 ARM32v7 container (emulated using Qemu)

### ISSUE THREAD

**Issue by aryanbdps9** [rust-lang/cargo#10763] opened 2022-06-16 22:56 UTC
### Problem

If you try installing any package using cargo in a container on Debian 11 ARM32v7 (or Ubuntu 20.04 ARM32v7), it fails with very mysterious errors.

The main repro sequence is mentioned in "Steps". I also tried setting `net.git-fetch-with-cli = true` in config.toml, it crashes saying: 
```error: could not find `cargo-deb` in registry `crates-io` with version `*` ```

Interesting part is that it works on Ubuntu 18.04/ARM32v7

This makes it hard to create ARMv7 packages in a containerized environment. Any suggestions would be appreciated. Happy to provide more info.

### Steps

1. Create a docker container using:
`docker run -it arm32v7/debian:11` 

2. Inside the container, install cargo using rustup.
3. One done, try installing any package:
```
root@cb0e579174c7:/# source $HOME/.cargo/env
root@cb0e579174c7:/# cargo install cargo-deb
    Updating crates.io index
warning: spurious network error (2 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
warning: spurious network error (1 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
root@cb0e579174c7:/#
```

### Notes

Here is the full sequence of steps:
```bash
$ sudo docker run  -it arm32v7/debian:11 /bin/bash
[sudo] password for aryanaryan:
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
root@c9fd89b3b1d0:/# apt update && apt install -y vim git wget curl
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main armhf Packages [155 kB]
Get:5 http://deb.debian.org/debian bullseye/main armhf Packages [7944 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main armhf Packages [2604 B]
Fetched 8301 kB in 11s (730 kB/s)
Reading package lists... Done
Setting up libexpat1:armhf (2.2.10-2+deb11u3) ...
Setting up libxau6:armhf (1:1.0.9-1) ...
Setting up libpsl5:armhf (0.21.0-1.2) ...
Setting up libgpm2:armhf (1.20.7-8) ...
Setting up wget (1.21-1+deb11u1) ...
Setting up perl-modules-5.32 (5.32.1-4+deb11u2) ...
Setting up libbrotli1:armhf (1.0.9-2+b2) ...
Setting up libcbor0:armhf (0.5.0+dfsg-2) ...
Setting up libsasl2-modules:armhf (2.1.27+dfsg-2.1+deb11u1) ...
Setting up libnghttp2-14:armhf (1.43.0-1) ...
Setting up less (551-2) ...
Setting up libldap-common (2.4.57+dfsg-3+deb11u1) ...
Setting up xxd (2:8.2.2434-3+deb11u1) ...
Setting up libsasl2-modules-db:armhf (2.1.27+dfsg-2.1+deb11u1) ...
Setting up vim-common (2:8.2.2434-3+deb11u1) ...
Setting up libx11-data (2:1.7.2-1) ...
Setting up librtmp1:armhf (2.4+20151223.gitfa8646d.1-2+b2) ...
Setting up patch (2.7.6-7) ...
Setting up libsasl2-2:armhf (2.1.27+dfsg-2.1+deb11u1) ...
Setting up libmd0:armhf (1.0.3-3) ...
Setting up git-man (1:2.30.2-1) ...
Setting up libssh2-1:armhf (1.9.0-2) ...
Setting up netbase (6.3) ...
Setting up vim-runtime (2:8.2.2434-3+deb11u1) ...
Setting up libfido2-1:armhf (1.6.0-2) ...
Setting up openssl (1.1.1n-0+deb11u2) ...
Setting up libbsd0:armhf (0.11.3-1) ...
Setting up publicsuffix (20211207.1025-0+deb11u1) ...
Setting up libgdbm6:armhf (1.19-2) ...
Setting up libxdmcp6:armhf (1:1.1.2-3) ...
Setting up libxcb1:armhf (1.14-3) ...
Setting up vim (2:8.2.2434-3+deb11u1) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
Setting up libedit2:armhf (3.1-20191231-2+b1) ...
Setting up libldap-2.4-2:armhf (2.4.57+dfsg-3+deb11u1) ...
Setting up libcurl3-gnutls:armhf (7.74.0-1.3+deb11u1) ...
Setting up ca-certificates (20210119) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Updating certificates in /etc/ssl/certs...
129 added, 0 removed; done.
Setting up libgdbm-compat4:armhf (1.19-2) ...
Setting up libperl5.32:armhf (5.32.1-4+deb11u2) ...
Setting up libcurl4:armhf (7.74.0-1.3+deb11u1) ...
Setting up libx11-6:armhf (2:1.7.2-1) ...
Setting up curl (7.74.0-1.3+deb11u1) ...
Setting up libxmuu1:armhf (2:1.1.2-2+b3) ...
Setting up openssh-client (1:8.4p1-5) ...
Setting up libxext6:armhf (2:1.3.3-1.1) ...
Setting up perl (5.32.1-4+deb11u2) ...
Setting up xauth (1:1.1-1) ...
Setting up liberror-perl (0.17029-1) ...
Setting up git (1:2.30.2-1) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Processing triggers for ca-certificates (20210119) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
root@c9fd89b3b1d0:/# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup: command failed: grep ^Features /proc/cpuinfo
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /root/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  /root/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /root/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /root/.profile
  /root/.bashrc

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: armv7-unknown-linux-gnueabihf
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is armv7-unknown-linux-gnueabihf
info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
info: latest update on 2022-05-19, rust version 1.61.0 (fe5b13d68 2022-05-18)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 19.7 MiB /  19.7 MiB (100 %)  15.5 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 24.7 MiB /  24.7 MiB (100 %)  14.9 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 79.3 MiB /  79.3 MiB (100 %)  15.7 MiB/s in  5s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
  5.9 MiB /   5.9 MiB (100 %)   2.2 MiB/s in  2s ETA:  0s
info: installing component 'clippy'
  2.4 MiB /   2.4 MiB (100 %)   2.0 MiB/s in  1s ETA:  0s
info: installing component 'rust-docs'
 19.7 MiB /  19.7 MiB (100 %)   1.5 MiB/s in 14s ETA:  0s
info: installing component 'rust-std'
 24.7 MiB /  24.7 MiB (100 %)   2.2 MiB/s in 12s ETA:  0s
info: installing component 'rustc'
 79.3 MiB /  79.3 MiB (100 %)   2.2 MiB/s in 35s ETA:  0s
info: installing component 'rustfmt'
  3.5 MiB /   3.5 MiB (100 %)   2.1 MiB/s in  1s ETA:  0s
info: default toolchain set to 'stable-armv7-unknown-linux-gnueabihf'

  stable-armv7-unknown-linux-gnueabihf installed - rustc 1.61.0 (fe5b13d68 2022-05-18)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source $HOME/.cargo/env
root@c9fd89b3b1d0:/# source $HOME/.cargo/env
root@c9fd89b3b1d0:/# cargo install cargo-deb
    Updating crates.io index
warning: spurious network error (2 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
warning: spurious network error (1 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
root@c9fd89b3b1d0:/# cargo install grcov
    Updating crates.io index
warning: spurious network error (2 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
warning: spurious network error (1 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  could not read directory '/root/.cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
root@c9fd89b3b1d0:/# cat > ~/.cargo/config.toml
[net]
git-fetch-with-cli = true
root@c9fd89b3b1d0:/# cargo install cargo-deb
    Updating crates.io index
error: could not find `cargo-deb` in registry `crates-io` with version `*`
root@c9fd89b3b1d0:/#
```

### Version

```text
cargo 1.61.0 (a028ae42f 2022-04-29)
release: 1.61.0
commit-hash: a028ae42fc1376571de836be702e840ca8e060c2
commit-date: 2022-04-29
host: armv7-unknown-linux-gnueabihf
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Linux [32-bit]
```

**Comment by weihanglo** [comment] 2022-06-19 13:55
Thanks for the report and detailed reproducible steps!

I think this is a duplicate of #7451 and #8719. Let's track it there.

**Closed by weihanglo** 2022-06-19 13:55 UTC
Labels: C-bug
