### ISSUE TITLE
Cargo ignores a native library in a mixed bin/lib crate on Windows

### ISSUE THREAD

**Issue by samolisov** [rust-lang/cargo#8919] opened 2020-11-30 15:45 UTC
**Problem**
Hello, I use a build script just to compile several libraries written in C and than use it in my Rust code. When my crate contains no lib.rs and therefore is only a binary crate, everything works fine.

I have the following build script (I run in on Windows, so I'm trying to "emulate" omitted `libm` on this platform):

```rust
// Example custom build script.
fn main() {
    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo:rerun-if-changed=src/hello.c");
    println!("cargo:rerun-if-changed=src/m.c");
    // Use the `cc` crate to build a C file and statically link it.
    cc::Build::new()
        .file("src/hello.c")
        .compile("hello");
    
    cc::Build::new()
        .file("src/m.c")
        .compile("m");
}
```

**I have to note**, the build script forever runs fine: regardless is there the lib.rs file or not, I get my libhello.a and hello.lib as well as libm.a and m.lib

Then I'm trying to use the generated libraries in my Rust code (`main.rs`):

```rust
fn main() {
    unsafe { callme(); }
}

extern "C" {
    fn callme();
}
```
(I also tried set `#[link(name = "hello")]` just before `extern "C"` but it doesn't help, the linker just started complain to `__impl_callme` instead of `callme`).

Also, I use the libm somewhere in my modules, which accessible from `main.rs` only (not `lib.rs`), and libm forever works fine, so linker have no problem with libm.

When I work without the `lib.rs` file (just after renaming it) everything works fine, my application can be compiled and linked. But once the `lib.rs` file has been added, the linked generates the following error:

```
error: linking with `link.exe` failed: exit code: 1120

note: rbe.3urfoqvy7511iheg.rcgu.o : error LNK2019: unresolved external symbol callme referenced in function _ZN3rbe4main17h7e8112776a0485e4E
```

I see the following difference in the linker command line: when there is no `lib.rs` file, the command line accepts the `hello.lib` library:

```
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\link.exe" ... "hello.lib" "/WHOLEARCHIVE:hello.lib" "m.lib" "/WHOLEARCHIVE:m.lib" ...
```

But once the `lib.rs` file has been added, the command line is changed:

```
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\link.exe" ... "m.lib" ...
```

So, no `hello.lib` is there.

I tried to remove any references to `libm` and work with `hello` only, but it doesn't help.

**Steps**
1. `cargo new demo`
A new binary crate is created. The `src/main.rs` should be changed as the following:

```rust
fn main() {
    unsafe { callme(); }
}

extern "C" {
    fn callme();
}
```

2. create a new `src/hello.c` file with the following content:

```c
#include <stdio.h>

int callme() {
  printf("Hello, World!\n");
  return 0;
}
```

3. create a new `src/m.c` file with the following content:

```c
typedef struct Complex {
  float re, im;
} Complex;

Complex ccosf(Complex z) {
  /* not implemented yet */
  return z;
}
```

4. create a build file `build.rs` with the following content:
```rust
// Example custom build script.
fn main() {
    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo:rerun-if-changed=src/hello.c");
    println!("cargo:rerun-if-changed=src/m.c");
    // Use the `cc` crate to build a C file and statically link it.
    cc::Build::new()
        .file("src/hello.c")
        .compile("hello");
    
    cc::Build::new()
        .file("src/m.c")
        .compile("m");
}
```

5. add `cc` as a build dependency in `Cargo.toml`:

```
[build-dependencies]
cc = "^1.0"
```

5. at this step everything build fine:
$ cargo build

```
Finished dev [unoptimized + debuginfo] target(s) in 5.51s 
```

6. add a `src/lib.rs` file:

```rust
pub fn add(a: i32, b: i32) {
    a + b
}
```

And the linker **will fail** after this.

```
fatal error LNK1120: 1 unresolved externals
```

**Possible Solution(s)**
If a function from `lib.rs` is used in the main file, the cargo is able to build the project. But this solution is not obvious: I use the C library in the binary crate (`main.rs`) and it is unclear why a symbol from a new created `lib.rs` must be used there to let cargo generate the right command line for the linker.

Output of `cargo version`:

cargo 1.48.0 (65cbdd2dc 2020-10-14)  
Windows 10 x64,

**Comment by alexcrichton** [comment] 2020-11-30 16:55
This is currently expected behavior in Cargo. Cargo links the native libraries to the Rust library but then doesn't link them to the binary, assuming that the Rust library is linked to in the binary. If you add `extern crate demo`  to your `src/main.rs` does it work?

**Comment by samolisov** [comment] 2020-12-01 07:28
Thank you @alexcrichton, `extern crate demo` does help me. If I right understand the cause is how cargo manages dependencies: by default the native libraries are dependencies of the Rust library (if a library is in the project) and not of a binary crate, so the library must be marked as a dependency for the binary crate by using something from the library in the binary or just by the `extern crate` stanza?

If everything works as designed, can I close the issue?

Thank you very much.

**Comment by alexcrichton** [comment] 2020-12-01 15:30
Indeed that's how it works! And yeah since it's working for you as well I'm going to close this issue.

**Closed by alexcrichton** 2020-12-01 15:30 UTC
Labels: C-bug
