### ISSUE TITLE
cargo::util::ProcessBuilder::debug_string needs to shell-quote its arguments

### ISSUE THREAD

**Issue by andersk** [rust-lang/cargo#1489] opened 2015-04-06 08:21 UTC
If you run `cargo test --verbose --features=gif`, and it fails with a message like

```
Could not compile `image`.

Caused by:
  Process didn't exit successfully: `rustc examples/opening.rs --crate-name opening --crate-type bin -g --cfg feature="gif" --out-dir /home/anders/rust/image/target/debug/examples --emit=dep-info,link -L dependency=/home/anders/rust/image/target/debug -L dependency=/home/anders/rust/image/target/debug/deps --extern glob=/home/anders/rust/image/target/debug/deps/libglob-a0d0fe83c10e9061.rlib --extern byteorder=/home/anders/rust/image/target/debug/deps/libbyteorder-919e9a7c69df6496.rlib --extern num=/home/anders/rust/image/target/debug/deps/libnum-798fe7e31b30dacd.rlib --extern image=/home/anders/rust/image/target/debug/libimage-1d85aeba82463203.rlib` (exit code: 101)
```

you would expect to be able to copy and paste the displayed command and have it do the same thing. But that doesn’t work, because `feature="gif"` needs to be quoted as `'feature="gif"'` for the shell to run the same command that `cargo` ran.

**Comment by alexcrichton** [comment] 2015-04-06 16:31
Dupe of #744, but thanks!

**Closed by alexcrichton** 2015-04-06 16:31 UTC
