### ISSUE TITLE
Add support for --features and --no-default-features flags in workspace builds

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/cargo#4753] opened 2017-11-27 21:26 UTC
When using `cargo cmd --all --no-default-features` on virtual manifest cargo should disable default features for all crates in the workspace. `cargo cmd --all --features feature1,feature2` should enable feature if crate in the workspace has it and ignore it otherwise.

Old issue text:
In [RustCrypto/hashes](https://github.com/RustCrypto/hashes) `xargo` is used in CI to verify if all crates are indeed `no_std`. But with the addition of `std` feature (see branch `digest_v0.8`) which per convention is enabled by default, `xargo` does not work correctly anymore. I've changed CI config to use the following command on workspace (Travis [build](https://travis-ci.org/RustCrypto/hashes/jobs/308030682)):
```sh
xargo build --all --no-default-features --verbose --target armv7-unknown-linux-gnueabihf
```
But it fails with this error:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed
```

It looks like that problem originates from the fact that `cargo` does not propagate `--no-default-features` when it builds all crates in workspace. In this particular case it causes `digest` (and all other crates) to be built with enabled `std` feature which is quite undesirable.

Is this behaviour intentional? In my opinion this flag (and others?) should be propagated to all crates in the workspace on which subcommand is called.

[Old xargo issue.](https://github.com/japaric/xargo/issues/180)

**Comment by est31** [comment] 2017-11-28 01:03
The way serde_bytes, which depends on serde, and which both have optional no_std support, [is doing it](https://github.com/serde-rs/bytes/blob/master/Cargo.toml) is via the following setup:

```toml
[features]
default = ["std"]
std = ["serde/std"]

[dependencies]
serde = { version = "1.0", default-features = false }
```

**Comment by newpavlov** [comment] 2017-11-28 07:00
@est31 
I am not sure why you wrote it here, as you can see for example [here](https://github.com/RustCrypto/hashes/blob/digest_v0.8/sha3/Cargo.toml) RustCrypto/hashes uses the same approach. (`std` feature in `digest` crate is disabled by default to simplify configuration a bit)

**Comment by est31** [comment] 2017-11-28 07:23
@newpavlov oh I see. nvm then :)

**Comment by alexcrichton** [comment] 2017-11-29 20:55
I think this is either a bug or a feature depending on how you look at it, right now the feature selection applies to a "root crate" (which doesn't have much meaning any more really) rather than all crates (aka if you specify `--feature foo --all` how would we interpret it where it works?)

In that sense this is sort of working as expected, albeit surprisingly.

**Comment by newpavlov** [comment] 2017-11-30 19:20
> aka if you specify --feature foo --all how would we interpret it where it works?

I think intuitive behaviour in this case will be to enable feature if crate in the workspace has it and ignore otherwise. At the very least if cargo does not support working with features when building workspace (aka virtual manifest) in my opinion it should display warning/error, as currently it's essentially ignores feature related flags.

**Comment by nbigaouette-eai** [comment] 2017-12-19 03:35
Instead of _disabling_ all features with `--no-default-features`, I need to enable a specific feature using `--features foo`, which is not possible right now when I put my crates in a workspace. :(

**Comment by ishitatsuyuki** [comment] 2018-03-20 04:30
Duplicate of #5015.

**Comment by est31** [comment] 2018-03-20 09:11
@ishitatsuyuki I'd say that that bug is a dupe of this one, no? Because the other bug has been filed later.

**Comment by ishitatsuyuki** [comment] 2018-03-20 09:12
@est31 I'm in favour of using #5015 because that one has a clearer title. This bug affects `--features`, not only `--no-default-features`.

**Comment by newpavlov** [comment] 2018-03-20 09:34
I've updated issue title and text.

**Comment by est31** [comment] 2018-03-20 09:38
@ishitatsuyuki I see, that's a point.

**Comment by ishitatsuyuki** [comment] 2018-03-20 09:39
Well, given that the title is updated, feel free to close #5015.

**Comment by norru** [comment] 2019-03-19 10:25
So, just stumbled upon this problem.

What is the recommended workaround?

**Comment by photex** [comment] 2019-06-21 07:28
I am likewise being bitten by this issue. It isn't clear how to properly work with features when you have a rather large workspace already in place. :D

**Comment by photex** [comment] 2019-06-21 07:32
In fact... none of my intuition has even lead me to a solution. If I have a crate in a workspace that must use a feature in order to build, unless I specify a default feature set then I'm unable to build my workspace now. 

Specifying a default feature is a bad idea in this case, because if a developer wants to work on this crate, they can't use --no-default-features to override the default in order to work with the other features.

In my particular case the features are determining which graphics api to use, which means that any developers on osx wouldn't be able to develop or contribute to this project without unnecessary trouble.

**Closed** 2020-04-09 16:00 UTC
Labels: A-features, C-feature-request

**Comment by Ponewor** [comment] 2021-11-26 10:14
Any progress? This is really counterintuitive right now.

**Comment by weihanglo** [comment] 2021-11-26 10:55
`package-features` has been stabilized since 1.51. The `member/feature` syntax can be used to enable features defined in member packages.

```
cargo build --features member/feature
```

https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options
https://doc.rust-lang.org/cargo/reference/features.html#resolver-version-2-command-line-flags
