### ISSUE TITLE
The SSL certificate is invalid

### ISSUE THREAD

**Issue by radare** [rust-lang/cargo#1978] opened 2015-09-09 10:22 UTC
For some reason I get this:
```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [16] The SSL certificate is invalid
```
But i can't find a way to get more information (why this cert is invalid), and having at least one commandline option or environment variable to ignore them would be helpful

**Comment by radare** [comment] 2015-09-09 14:16
```
$ rustc -vV
rustc 1.2.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.2.0-dev
$ cargo -vV
cargo 0.4.0 (built 2015-08-17)
```

**Comment by kulbida** [comment] 2015-09-30 17:35
Is there any progress on this?

**Comment by alexcrichton** [comment] 2015-10-01 00:22
This looks like Cargo may have been built from scratch rather than being a nightly, @radare how'd you install Cargo/Rust to get this error?

Unfortunately I think we're giving as much information as we've got right now, I'm not sure if there's more contextual information cargo has to propagate upwards.

**Comment by radare** [comment] 2015-10-02 07:43
I can reproduce it with the package of voidlinux. The nightly build from the cargo web page works as expected

**Comment by alexcrichton** [comment] 2015-10-02 17:07
Oh interesting! What's voidlinux? Is there something I can do to reproduce this locally?

**Comment by radare** [comment] 2015-10-03 12:59
http://voidlinux.eu <http://voidlinux.eu/>

I guess you can reproduce this issue by downloading the r2live iso http://bin.rada.re/r2live-20150901.iso <http://bin.rada.re/r2live-20150901.iso> which is based on voidlinux, and then install cargo like this:

xbps-install cargo

git clone any rust project and run cargo update. iirc downloading the nightly official build seems to work fine.

you can check the pkg template here:

https://github.com/voidlinux/void-packages/blob/master/srcpkgs/cargo/template <https://github.com/voidlinux/void-packages/blob/master/srcpkgs/cargo/template>

thanks!

**Comment by alexcrichton** [comment] 2015-10-03 23:50
Hm so I didn't quite go the route of installing from scratch, but I ran the [docker image](https://hub.docker.com/r/voidlinux/voidlinux/) for voidlinux after which I did:

```
$ xbps-install -S cargo git
$ git clone https://github.com/alexcrichton/tar-rs
$ cd tar-rs
$ cargo test
```

And everything worked out ok? Perhaps something is misconfigured locally? Do the certificates installed need to be updated perhaps?

**Comment by petevine** [comment] 2015-10-11 21:58
I'm also seeing this issue on 64-bit Porteus.

There was no problem with the 32-bit version of Porteus using my own builds of cargo but the 64-bit version and the official x86_64 nightly are producing the error. 

The system date is correct and no other app complains about certificates.

**Comment by alexcrichton** [comment] 2015-10-12 02:03
@petevine like with the case above, is there a way that I would be able to reproduce this? Cargo has to do a little work to discover the system certificates and it could be that they're not being discovered

**Comment by petevine** [comment] 2015-10-12 02:28
Almost certainly the problem here as the filesystem layout is a little different between the two versions.

You probably shouldn't waste too much time on trying to run the live distro yourself (http://build.porteus.org/) but maybe you could provide a few hints where cargo's expecting to find the certs so that symlinking would be enough.

I'm going to find out if the certs' locations are different and report back.

**Comment by alexcrichton** [comment] 2015-10-12 02:29
You can find the [current search locations](https://github.com/sfackler/rust-openssl/blob/aad933e5077b2c73e1f05d7314e442531a562bcf/openssl-sys/src/probe.rs#L16-L27) in the `openssl-sys` crate, but I can also try to run something in docker if there's an image available somewhere perhaps?

**Comment by petevine** [comment] 2015-10-12 02:39
Thx, I'll have a look. 

The porteus link above will lead you to an image creation wizard so as long as you pick 64bit (uefi) it probably won't matter what other options you choose.

**Comment by petevine** [comment] 2015-10-12 03:49
I was right asking you to hold back :) 

After investigating both setups it looks like I'd stumbled on a distro bug - the certificates package is missing from the 64bit version (could be related to different browser and DE choices somehow).

**Comment by alexcrichton** [comment] 2015-10-12 16:04
Oh holy cow sorry! I think I accidentally deleted @petevine's last comment, so here it is:


> I was right asking you to hold back :)
> 
> After investigating both setups it looks like I'd stumbled on a distro bug - the certificates package is missing from the 64bit version (could be related to different browser and DE choices somehow).


Thanks for taking a look @petevine! @radare any updated on the voidlinux side of things?

**Comment by radare** [comment] 2015-10-12 16:39
@alexcrichton no news, still the same problems

**Comment by petevine** [comment] 2015-10-12 18:00
@radare, you had better eliminate the obvious as well and if you do have the certificates, try locating cert.pem and then look at the output from `strace cargo build` which should show which paths are being checked.

**Comment by radare** [comment] 2015-10-12 18:40
Yeah i have managed to fix this thing.

1) a clean voidlinux installation works as expected

2) my system was still failing, so i straced, and noticed that it was unable to find *any* cert.pem, the most similar filename was /etc/ssl/certs.pem, just renamed certs.pem to cert.pem and it worked.

i guess that was a distro issue, but its strange that the nightly build of cargo was working as expected and not this one.

thanks for the tips

**Comment by petevine** [comment] 2015-10-12 19:47
Just to be on the safe side, a symlink to certs.pem is probably a good idea or other stuff might break :)

**Comment by alexcrichton** [comment] 2015-10-12 20:47
@radare if you [add another case here](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/probe.rs#L60) for `certs.pem`, does it work "out of the box" for you/

**Comment by radare** [comment] 2015-10-12 21:21
Thanks for pointing out.

I just did a pullreq: https://github.com/sfackler/rust-openssl/pull/287

Btw, voidlinux uses libressl. which can be the reason behind this different path.

**Comment by rasendubi** [comment] 2016-01-23 13:34
@alexcrichton, @radare, the pull request is merged. I think we should close the issue.

**Comment by alexcrichton** [comment] 2016-01-24 05:10
@rasendubi ok thanks for the reminder!

**Closed by alexcrichton** 2016-01-24 05:10 UTC

**Comment by nazar-pc** [comment] 2016-11-30 21:40
Still experiencing this issue when installing cargo in Ubuntu 17.04 Docker container as following:
```
root@540d11ba4446:/rust# RUST_ARCHIVE=rust-nightly-x86_64-unknown-linux-gnu.tar.gz
root@540d11ba4446:/rust# RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
root@540d11ba4446:/rust# curl -fsOSL $RUST_DOWNLOAD_URL \
    && curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c - \
    && tar -C /rust -xzf $RUST_ARCHIVE --strip-components=1 \
    && rm $RUST_ARCHIVE \
    && ./install.sh
```

The same script works fine in Debian Jessie image

**Comment by steveklabnik** [comment] 2016-11-30 21:52
@nazar-pc see https://github.com/rust-lang/cargo/issues/3346

**Comment by lu-zero** [comment] 2016-12-04 13:42
Just reproduced the problem on a current Gentoo system and today's nightly.

**Comment by sanmai-NL** [comment] 2016-12-05 09:18
I also did, on current Arch Linux and today's nightly.

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `chrono`                                                                                                                                                            

Caused by:                                                                                                                                                                                                           
  Unable to update registry https://github.com/rust-lang/crates.io-index                                                                                                                                             

Caused by:                                                                                                                                                                                                           
  failed to fetch `https://github.com/rust-lang/crates.io-index`                                                                                                                                                     

Caused by:                                                                                                                                                                                                           
  [16/-17] The SSL certificate is invalid     
```

`openssl version`
```
OpenSSL 1.0.2j  26 Sep 2016
```

`sudo pacman -Qi openssl`
```
Please touch the device.
Name            : openssl
Version         : 1.0.2.j-1
Description     : The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
Architecture    : x86_64
URL             : https://www.openssl.org
Licenses        : custom:BSD
Groups          : None
Provides        : None
Depends On      : perl
Optional Deps   : ca-certificates [installed]
Required By     : coreutils  curl  git  iputils  ldns  libarchive  libevent  libgit2  libsasl  libshout  libssh  libssh2  libu2f-server  lynx  mupdf  net-snmp  nmap  nodejs  openslp  openssh  python  python2
                  python2-pyopenssl  rkt  rtmpdump  ruby  unbound  wget  wpa_supplicant  xmlsec
Optional For    : apr-util
Conflicts With  : None
Replaces        : None
Installed Size  : 6,99 MiB
Packager        : Pierre Schmitz <pierre@archlinux.de>
Build Date      : di 27 sep 2016 15:52:48 CEST
Install Date    : wo 28 sep 2016 09:01:28 CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

`uname -a`
```
Linux Onkyo 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux
```
`/etc/os-release`:
```
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by lukehinds** [comment] 2016-12-24 16:18
Getting the same in a Fedora 25 docker container:

```
# cargo run --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `log`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [16/-17] The SSL certificate is invalid
[root@d6e7c553326f hello_world]# openssl version
OpenSSL 1.0.2j-fips  26 Sep 2016
```

**Comment by alexcrichton** [comment] 2016-12-25 18:33
@lukehinds it looks like that case isn't handled by the [`openssl-probe` crate](https://github.com/alexcrichton/openssl-probe/blob/master/src/lib.rs#L52-L71) which Cargo relies on to find certificates on various systems. Want to send a PR to update that, though?

**Comment by lukehinds** [comment] 2016-12-30 09:26
@alexcrichton , sure, will take a look.
