### ISSUE TITLE
rust upgrade to 1.68.0 after cargo run error

### ISSUE THREAD

**Issue by Yakumo-Yukari** [rust-lang/cargo#11832] opened 2023-03-11 07:13 UTC
### Problem

```text
$ cargo run
   Compiling hellorust v0.1.0 (E:\Klee\code\hellorust)
error: could not compile `hellorust`

Caused by:
  process didn't exit successfully: `rustc --crate-name hellorust --edition=2021 'src\main.rs' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=79 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=31af1aa08fb0c465 --out-dir 'E:\Klee\code\hellorust\target\debug\deps' -C 'incremental=E:\Klee\code\hellorust\target\debug\incremental' -L 'dependency=E:\Klee\code\hellorust\target\debug\deps'` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

### Version

```text
hellorust v0.1.0 (E:\Klee\code\hellorust)
rustc 1.68.0 (2c8cc3432 2023-03-06)
cargo 1.68.0 (115f34552 2023-02-26)
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Alice\.rustup
stable-x86_64-pc-windows-msvc (default)
```

**Comment by weihanglo** [comment] 2023-03-11 07:56
Hello. I suspect it panicked. Do you have a reproducible code example to share?

Also, could you run again with backtrace? Something like

```console
$env:RUST_BACKTRACE=1; cargo run
```

will give us richer error information.
(Use `set RUST_BACKTRACE=1` if on cmd)

**Comment by ehuss** [comment] 2023-03-11 15:02
This looks like it could be a duplicate of https://github.com/rust-lang/rust/issues/108978.

Which CPU do you have?

**Comment by GregGorin** [comment] 2023-03-13 07:33
I have the same problem. CPU AMD Phenom II X6 1090T

**Comment by weihanglo** [comment] 2023-04-25 09:58
Going to close this as rust-lang/rust#108978 states it has been resolved. I guess the latest stable (1.69) is fine. If the issue still ocurrs please reply back.

**Closed as completed by weihanglo** 2023-04-25 09:58 UTC
Labels: C-bug, S-needs-info
