### ISSUE TITLE
Cargo does not compile code: no such file or directory

### ISSUE THREAD

**Issue by greggawatt** [rust-lang/cargo#1337] opened 2015-02-23 01:17 UTC
Cargo giving a weird error, following directions exactly from the rust book. My code is here if you want to test it out: https://github.com/greggawatt/rust-intro

Running OSX yosemite, zsh shell

```
cargo build --verbose
   Compiling hello_world v0.0.1 (file:///Users/gregg/Development/rust-intro)
     Running `rustc src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/gregg/Development/rust-intro/target --emit=dep-info,link -L dependency=/Users/gregg/Development/rust-intro/target -L dependency=/Users/gregg/Development/rust-intro/target/deps`
Could not compile `hello_world`.

Caused by:
  Could not execute process `rustc src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/gregg/Development/rust-intro/target --emit=dep-info,link -L dependency=/Users/gregg/Development/rust-intro/target -L dependency=/Users/gregg/Development/rust-intro/target/deps` (status=never executed)

Caused by:
  no such file or directory
```

**Comment by steveklabnik** [comment] 2015-02-23 01:20
It's also worth noting that when @greggawatt runs the `rustc` command by itself, it does work, so it's something weird in cargo

**Comment by alexcrichton** [comment] 2015-02-23 08:04
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/987. Unfortunately I have not been able to track down why this is happening because I am unable to duplicate it myself. If you've got anything more to add to the thread though, please feel free to post a comment!

**Closed by alexcrichton** 2015-02-23 08:04 UTC

**Comment by greggawatt** [comment] 2015-02-23 17:10
Would it be at least useful to improve the verbose output so we know what file or directory is not found?

**Comment by alexcrichton** [comment] 2015-02-23 17:42
Unfortunately the only cause for "no such file or directory" when executing a process that I know of is that the executable `rustc` was not found. That's quite puzzling, however, because you clearly have `rustc` and it's in your `PATH` so I'm not quite sure what's going on :(

**Comment by greggawatt** [comment] 2015-02-23 17:43
Was the other person running zsh? I know there are sometimes weird path issues there.

**Comment by alexcrichton** [comment] 2015-02-23 17:44
It's not mentioned specifically, but I would suspect the answer would be yes.

**Comment by greggawatt** [comment] 2015-02-23 17:45
I will try this in straight terminal and see what happens.
