### ISSUE TITLE
Vendoring is not able to provide offline test env

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/cargo#7474] opened 2019-10-03 02:28 UTC
**Problem**
When using cargo vendor, test --offline fails.

**Steps**

1. cargo vendor
2. cargo test --offline
3. 
```
CARGO_TARGET_DIR=/home/william/build/ds/rs  \
	cargo test --offline --manifest-path=/home/william/development/389ds/ds/src/librslapd/Cargo.toml
warning: unused manifest key: source
error: unable to fetch registry `https://github.com/rust-lang/crates.io-index` in offline mode
```

**Possible Solution(s)**
Test/dev dependencies should be fetched in vendoring to allow test --offline to operate. 

**Notes**

Output of `cargo version`:
1.37

**Comment by alexcrichton** [comment] 2019-10-03 14:42
It looks like you may have configured vendoring in the wrong location? the `warning: unused manifest key: source` looks like the configuration was placed in the manifest (`Cargo.toml`) instead of `.cargo/config`

**Comment by Firstyear** [comment] 2019-10-03 22:55
Ahhh all the communication in cargo vendor has been super unclear and dense to read. I've really been struggling to understand this process.

I have had values in .cargo/config, and these messages keep appearing so it appears like they are doing nothing. When you have no dependencies it gives you an incomplete configuration and doesn't prompt to say it did nothing. (I already opened that issue I think). Cargo vendor always shows absolute paths too, which is really worrying for something that should be getting vendored and shipped to other hosts too.

I think that perhaps the overall experience is cargo vendors gives a lot of 'false warnings' which meant that I switched off reading the warnings because it kinda-i-guess worked until it didn't.

Anyway, vendoring worked with this change, so I'll leave it up to you if you want to close this, or if you think there is something here communication wise that can be improved :) Thanks heaps!

**Comment by alexcrichton** [comment] 2019-10-07 23:36
Ah ok, in that case I'm gonna go ahead and close this.

It'd be great if you could be more concrete about the false warnings though! It sounds like you didn't have a great experience with `cargo vendor` and we'd love to help fix that! I'm not really sure what you mean about false warnings though, so having detailed instructions to reproduce would be quite helpful. (and opening a new issue should be fine)

**Closed by alexcrichton** 2019-10-07 23:36 UTC
Labels: C-bug

**Comment by Firstyear** [comment] 2019-10-07 23:40
See this issue here https://github.com/rust-lang/cargo/issues/7473 :)

**Comment by Firstyear** [comment] 2019-10-08 22:09
Hey, @alexcrichton can you re-open this - just yesterday I did this again and with "cargo test --locked --offline" the test failed with "unable to fetch metadata". I think that perhaps the issue here is that the workflow for cargo vendor and getting --offline to work is not really documented on  https://doc.rust-lang.org/nightly/cargo/commands/cargo-vendor.html . It talks about the commands in isolation, but not what the workflow should be. What I have come up with I have no idea if it's correct but the only way I got it to work was:

```
cargo vendor
cargo fetch
cargo build --offline --locked
```

Even with fetch+vendor, `cargo test --offline --locked` is still failing for me claiming it needs to update. So I think there is some really missing process guides here about how to tie it all together to a working offline build system.

**Comment by alexcrichton** [comment] 2019-10-15 14:11
Sorry for the delay in getting back here, @Firstyear can you open a new issue for that perhaps? This issue as-is is not correct because vendoring does handle the test environment, so having a detailed workflow of what went wrong would be helpful to figure out where the documentation is wrong or where it went awry.

**Comment by Firstyear** [comment] 2019-10-16 22:30
Thanks @alexcrichton, see #7520
