### ISSUE TITLE
REQUEST: Allow cargo to use non-standard hierarchy for tests and benches

### ISSUE THREAD

**Issue by Kreyren** [rust-lang/cargo#7879] opened 2020-02-11 16:58 UTC
Disclaimer: This may be a pebcak.

### Describe the problem you are trying to solve

I have project on https://github.com/RXT0112/Zernit/pull/40 which is using multiple programming languages where cargo is expected to use `/tests/rustlang` instead of `/tests/` and `/benches/rustlang/` instead of `/benches` to avoid conflicts with other langs which based on available infromations from Cargo book and me asking community for help is not possible. -> Requesting it to be added

### Describe the solution you'd like

Allow non-standard file hierarchy for cargo's tests and benches

**Comment by ehuss** [comment] 2020-02-12 18:22
Thanks for the report.  I think this is more or less a duplicate of #5766, so I'm going to close in favor of that.

**Closed by ehuss** 2020-02-12 18:22 UTC
Labels: C-feature-request
