### ISSUE TITLE
`cargo run` should wait for child termination in case of SIGINT/SIGTERM

### ISSUE THREAD

**Issue by troplin** [rust-lang/cargo#2525] opened 2016-03-27 20:33 UTC
I'm not sure if this is the same issue as #2343, at least it is related

If the child application handles signals, `cargo run` exits before the child process. This leads to strange effects like the output of the child process appearing on/after the prompt:
```
root@29c089056c4d:/shares/Development/test# RUST_LOG=test=debug cargo run --release
     Running `target/release/test`
INFO:test: test v0.1.0 started
^C
root@29c089056c4d:/shares/Development/test# INFO:test: Recieved signal [Int], shutting down
INFO:test: test v0.1.0 stopped
```
If I run the `test` application directly it looks like:
```
root@29c089056c4d:/shares/Development/test# RUST_LOG=test=debug target/release/test 
INFO:test: test v0.1.0 started
^CINFO:test: Recieved signal [Int], shutting down
INFO:test: test v0.1.0 stopped
root@29c089056c4d:/shares/Development/test# 
```
I think `cargo run` should handle the signals and wait for the exit of the child process.

**Comment by alexcrichton** [comment] 2016-03-28 03:53
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/2343, and my preferred solution here would be to use `CommandExt::exec` on Unix once stabilized, as that'd "proxy" even SIGKILL :)

**Closed** 2016-03-28 03:53 UTC

**Comment by dagit** [comment] 2016-09-25 03:31
I just tested this on Windows with cmd.exe and powershell. My program has a repl and so if you hit Ctrl-C I want it to interrupt the current computation and return you to the repl. If I run the program manually this works. If I use `cargo run` instead then Ctrl-C causes cargo and my program to exit. This seems to be happening because cargo is exiting on ctrl-c instead of letting my program handle it.

**Comment by alexcrichton** [comment] 2016-09-26 23:28
@dagit yeah the semantics of running the executable directly vs `cargo run` are subtle but different. I think you'd witness similar behavior on Unix as well (perhaps a zombie as well I think)
