### ISSUE TITLE
Notify Users of `cargo +nightly install` when using `cargo install +nightly`

### ISSUE THREAD

**Issue by DrRuhe** [rust-lang/cargo#10362] opened 2022-02-05 10:29 UTC
### Problem

When running `cargo install +nightly ...` there is no indication that it does not actually use the nightly toolchain, until the compilation runs into errors because e.g. features need nightly.

### Proposed Solution

Either:
Let the user know that `cargo install +nightly ...` doesn't actually use nightly and instead they should use `cargo +nightly install ...`.

Or:
just use nightly...

**Comment by weihanglo** [comment] 2023-05-24 17:47
Should be fairly easy to tackle for only `cargo install`. That being said,  I personally want a solution for all cargo commands. People may also type `cargo build +nightly` and we should catch that. The difficult part is that `rustup` proxy name can be custom defined. 

If we got #11702 or clap-rs/clap#4706 landed, I think it's sufficient that we target only a subset of most common ones like `+stable`, `+beta`, `+nightly`.

**Comment by epage** [comment] 2023-05-24 18:13
The problem is `+<channel>` isn't a flag per se but a positional argument.

`cargo install` and `cargo add` are some of the few commands that even accept a positional argument, so I can see doing this in a one-off way.

(some others accept positional arguments but those are just meant to forward to an underlying command)

**Comment by danilhendrasr** [comment] 2023-06-02 03:09
Hi, I would like to take on this issue. But, just to confirm, from what I understand in order to resolve this issue we only need to make cargo emits the above error message whenever the add and install command is run with a crate name that has `+` in it. Is it correct?

**Comment by weihanglo** [comment] 2023-06-02 06:32
That's exactly my plan so far!

You may want to tweak the message a bit. Mine is not as good as it looks.

**Comment by danilhendrasr** [comment] 2023-06-02 10:09
Got it, I'll see what I can come up with.

@rustbot claim

**Comment by danilhendrasr** [comment] 2023-06-02 14:57
I think I need more clarification. 

If the error is emitted any time the command is given a crate name that starts with `+` regardless if the rest of the crate name is actually the same as one of the three toolchain channels name (stable, beta, nightly), then the following part:

```
  Use `cargo +<crate name> add` if you meant to use `<crate name>` toolchain.
``` 

of the error should only be printed when the crate name is actually the same as one of the three toolchain channels name. 
Is that correct?

**Comment by weihanglo** [comment] 2023-06-02 16:46
[Toolchain name](https://rust-lang.github.io/rustup/concepts/toolchains.html#custom-toolchains) can be anything, such like `cargo +stage1 build`.

My best guess is, from the array of crates name strings (`krates` and `crates` in source code), if there is a string starting with `+`, give the user an error.

**Closed** 2023-06-03 15:03 UTC
Labels: E-easy, A-errors, Command-install, C-feature-request, S-accepted, Command-add
