### ISSUE TITLE
cargo new: automatically add to workspace

### ISSUE THREAD

**Issue by theduke** [rust-lang/cargo#10670] opened 2022-05-15 11:18 UTC
### Problem

When running `cargo new` in a workspace a warning is printed, but you have to manually add the new crate to the `members = []` section.

### Proposed Solution

Add a new `--workspace` / `-w` flag to `cargo new` that automatically adds the new crate with the correct path to `members`.

Print a hint about the flag when `cargo new` is run in a workspace.

This is admittedly a small quality of life feature, but I do it often enough that it becomes annoying.

**Comment by ehuss** [comment] 2022-05-15 16:59
Thanks for the report. This is a known issue, closing as a duplicate of #8365.

**Closed by ehuss** 2022-05-15 16:59 UTC
Labels: C-feature-request

**Comment by ehuss** [comment] 2022-05-15 17:30
Sorry, I should have linked to #6378.

**Comment by felipetesc** [comment] 2022-10-05 17:56
Any news about this proposal ? What's the current situation ? Thanks.
