### ISSUE TITLE
Incorrect RUSTFLAGS parsing (part deux)

### ISSUE THREAD

**Issue by lrascao** [rust-lang/cargo#8614] opened 2020-08-12 18:25 UTC
**Problem/Steps**
```
% cargo new aa
% cd aa
$ RUSTFLAGS="--codegen link-args='-flat_namespace -undefined suppress'" cargo build

error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --codegen 'link-args='\''-flat_namespace' -undefined 'suppress'\''' --crate-type bin --crate-type rlib --crate-type dylib --
crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
--- stderr
error: Unrecognized option: 'u'
```

(Ugly) Alternative that does work:
```
RUSTFLAGS="--codegen link-arg=-flat_namespace --codegen link-arg=-undefined --codegen link-arg=suppress" cargo build
   Compiling aa v0.1.0 (/private/tmp/aa)
    Finished dev [unoptimized + debuginfo] target(s) in 1.29s
```
**Notes**

$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)

**Comment by lrascao** [comment] 2020-08-12 18:26
Previous discussion of same issue [here](https://github.com/rust-lang/cargo/issues/3287)

**Comment by ehuss** [comment] 2020-08-12 20:00
Hi, thanks for the report!  I'm going to close this as a duplicate of #6139, #3686, and #7406.  See #7406 for a nightly-only option which allows TOML syntax in environment variables.

**Closed by ehuss** 2020-08-12 20:00 UTC
Labels: C-bug

**Comment by lrascao** [comment] 2020-08-12 22:18
👍
