### ISSUE TITLE
Cargo clean removes target directory, even when it is a softlink

### ISSUE THREAD

**Issue by SeseMueller** [rust-lang/cargo#13670] opened 2024-03-30 23:10 UTC
### Problem

Running `cargo clean` deletes the target directory, which is usually fine, because it is regenerated on the next `cargo build`.
However, I used a symlink for my target directory because I want my code to be synced across devices, but not bloat it with the build artifacts. 

`cargo clean` simply removed the symlink.
In my opinion, it should either give a warning or follow the symlink; not fail silently. 

### Steps

1. Create a new empty project
2. Create a sylink for the target directory to somewhere else
3. Run `cargo build`
4. Run `cargo clean` 

The symlink is gone and on the next `cargo build`, it will be a regular directory instead.

### Possible Solution(s)

Always following symlinks might not be a good idea, so it should probably warn the user and abort. (To work proberly, that would require a new flag for `cargo clean` though)

### Version

```text
cargo 1.79.0-nightly (d438c80c4 2024-03-19)
release: 1.79.0-nightly
commit-hash: d438c80c45c24be676ef5867edc79d0a14910efe
commit-date: 2024-03-19
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.4.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.4.1 [64-bit]
```

**Comment by weihanglo** [comment] 2024-03-31 00:45
See <https://github.com/rust-lang/cargo/issues/7510#issuecomment-551912667> and dicussions in the closed PR, which consider this as an expected behavior. See also alternaive designs like <https://github.com/rust-lang/rfcs/pull/3371> for templating target directories.

Besides alternatives, is there any specific reason you can't set `CARGO_TARGET_DIR` to the actual directory instead of using a symlink?

**Comment by SeseMueller** [comment] 2024-03-31 08:43
> See [#7510 (comment)](https://github.com/rust-lang/cargo/issues/7510#issuecomment-551912667) and dicussions in the closed PR, which consider this as an expected behavior. See also alternaive designs like [rust-lang/rfcs#3371](https://github.com/rust-lang/rfcs/pull/3371) for templating target directories.

Ok, yeah. That makes sense. But given that `cargo clean` is mostly a manual command, maybe it should warn the user, but proceed as normal?

> Besides alternatives, is there any specific reason you can't set `CARGO_TARGET_DIR` to the actual directory instead of using a symlink?

I didn't realize that setting the `target-dir` would propagate through modules in my context, that did in fact work. Thanks for pointing that out.

**Comment by weihanglo** [comment] 2024-03-31 13:43
From [the manual](https://doc.rust-lang.org/nightly/cargo/commands/cargo-clean.html#description):

> With no options, cargo clean will delete the entire target directory.

Basically `cargo clean` is an `rm -rf` taking effect like immediately, so when seeing a warning it's too late. There is a [`--dry-run`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-clean.html#option-cargo-clean---dry-run) flag. When with doubt, users can dry-run a clean before the actual clean, such as `cargo clean --verbose --dry-run`. Interactive console is also an option, but due to compatibility reasons, that won't become the default behavior of `cargo clean` in my opinion.

Going to close this in favor of <https://github.com/rust-lang/rfcs/pull/3371> and `CARGO_TARGET_DIR`. Thank you for the report :)

**Closed** 2024-03-31 14:01 UTC
Labels: C-bug, Command-clean, S-needs-info
