### ISSUE TITLE
`[patch.crates-io]` ignores all features

### ISSUE THREAD

**Issue by qiujiangkun** [rust-lang/cargo#9629] opened 2021-06-26 19:02 UTC
**Problem**
I was trying to patch some of my deps, with additional features enabled in my workspace. However, features specified in `[patch.crates-io]` are all ignored.

**Steps**
```toml
[path.crates-io]
async-tungstenite = { git = "https://github.com/qiujiangkun/async-tungstenite", rev="1a544fb13fe46b22aa6df94e49277f49f8ffa8ca", features=["there-is-no-such-feature-whatsoever", "no-verbose-logging"] }
```
The features are ignored, no error is given(there-is-no-such-feature-whatsoever), and no feature is actually enabled(no-verbose-logging)

**Possible Solution(s)**
I think we can simply fix it, gives a hard error saying this is not supported, or gives a warning saying features are currently ignored

Output of `cargo version`:
```rust
cargo 1.54.0-nightly (44456677b 2021-06-12)
```

**Comment by weihanglo** [comment] 2021-06-28 12:51
IIRC `[patch]` is used only  for patching sources of dependencies at this moment. For fields related to "conditional compilation", such as `features` and `optional`, you still need to specify them in the original `[dependencies]` section.

**Comment by ehuss** [comment] 2021-07-02 01:24
I believe this is a duplicate of #3034, so closing in favor of that.  Cargo should at least emit a warning about the unused features.

**Closed by ehuss** 2021-07-02 01:24 UTC
Labels: C-bug
