### ISSUE TITLE
SIGINT can't terminate subprocess on OS X

### ISSUE THREAD

**Issue by cissusnar** [rust-lang/cargo#3460] opened 2016-12-26 11:07 UTC
```
$ ps -ef   
501 38117 24809   0  7:00下午 ttys001    0:00.01 cargo run
501 38118 38117   0  7:00下午 ttys001    0:00.08 target/debug/myproj

$ kill -SIGINT 38117

$ ps -ef 
501 38118     1   0  7:00下午 ttys001    0:00.08 target/debug/myproj
```

'cargo run' process is terminated, but it's subprocess is still running. 

```
$ cargo --version
cargo 0.15.0-nightly (298a012 2016-12-20)

$ rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)

$ uname -a
Darwin localhost.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```
CTRL+C can terminate cargo process and it's subprocess.

**Comment by KalitaAlexey** [comment] 2016-12-26 11:09
@cissusnar, add that it terminates by pressing CTRL+C.

**Comment by alexcrichton** [comment] 2016-12-26 19:29
Thanks for the report! This is currently expected behavior, as Cargo doesn't proxy signals to the child. This has changed recently on Unix where Cargo will `exec` the child, so signals are proxied automatically, however, so closing.

**Closed by alexcrichton** 2016-12-26 19:29 UTC

**Comment by KalitaAlexey** [comment] 2016-12-26 19:48
@alexcrichton,
I don't understand.
Could you provide more details?
Why `cargo run` is terminated on Unix, but isn't on MacOS?

**Comment by alexcrichton** [comment] 2016-12-26 20:36
@KalitaAlexey On Unix (including OSX) Cargo will [use the `exec` syscall](https://github.com/rust-lang/cargo/pull/2818) for `cargo run`. This means that the Cargo process itself is just replaced by the target executable. That was merged relatively recently, though, so it may not be in all releases of Rust.

If you find it's *not* terminated on OSX, I'd verify that you've got a recent version of Cargo with that PR in it. Otherwise you'll need to use the old (and more reliable) strategy of sending signals to the process *group*, not individual processes.

**Comment by KalitaAlexey** [comment] 2016-12-27 04:36
@alexcrichton,
@cissusnar has `cargo 0.15.0-nightly (298a012 2016-12-20)`.
It is recent, isn't it?
So if I understood right `cargo run`  should terminate on OSX, but it doesn't.

**Comment by alexcrichton** [comment] 2016-12-27 17:08
Yes that Cargo should include #2818. Are you using rustup perchance? If so you may be seeing https://github.com/rust-lang-nursery/rustup.rs/issues/806

**Comment by KalitaAlexey** [comment] 2016-12-27 17:13
I can't understand how a problem with `cargo run`  maybe caused by rustup.
Can you explain it please?

**Comment by alexcrichton** [comment] 2016-12-27 17:14
Can you confirm whether rustup is being used?

Rustup is a process wrapper that doesn't exec. The `cargo run` killed in the logs above could be rustup, not Cargo.

**Comment by KalitaAlexey** [comment] 2016-12-27 17:16
You mean `cargo` to be a simlink to `rustup`, don't you?

**Comment by KalitaAlexey** [comment] 2016-12-27 17:18
@alexcrichton,
I have got.
According to https://github.com/rust-lang-nursery/rustup.rs/#how-rustup-works
cargo is a proxy.

**Comment by KalitaAlexey** [comment] 2016-12-27 18:57
@cissusnar,
Can you find **cargo** in rustup current toolchain and execute **cargo run** with **cargo** from the current toolchain?

**Comment by cissusnar** [comment] 2016-12-28 02:08
@KalitaAlexey 
```
$ rustup --version
rustup 1.0.0 (17b6d21 2016-12-15)

$ rustup show
Default host: x86_64-apple-darwin

stable-x86_64-apple-darwin (default)
rustc 1.14.0 (e8a012324 2016-12-16)
```

**Comment by KalitaAlexey** [comment] 2016-12-28 05:13
@cissusnar,
You misunderstood me.
Open a terminal.
Execute in the terminal:
```
RUST_SYSROOT=$(rustc --print sys-root)
```
It should give you a path.
Execute in the terminal:
```
ls ${RUST_SYSROOT}/bin
```
There should be **cargo**.
Execute in the terminal:
```
cd <path/to/your/project>
${RUST_SYSROOT}/bin/cargo run
```
It should start running your project.
Try killing that with SIGINT.
Write your results.

**Comment by KalitaAlexey** [comment] 2016-12-29 11:34
I checked it on Linux.
The problem happens with rustup.

**Comment by KalitaAlexey** [comment] 2016-12-29 11:56
@cissusnar,
It is really the problem of rustup.
