### ISSUE TITLE
Cfgs from build script not passed to rustdoc

### ISSUE THREAD

**Issue by gkoz** [rust-lang/cargo#1980] opened 2015-09-09 22:00 UTC
The `cfg` directives returned by the build script via the `cargo:rustc-cfg=foo` convention are not passed to `rustdoc` when invoking `cargo doc`.

`rustdoc` seems to accept them just fine i.e. invoking it manually with `--cfg foo` produces the expected results.

**Comment by alexcrichton** [comment] 2015-09-10 03:53
I think this is a dupe of #1277, but thanks for the report!

**Comment by gkoz** [comment] 2015-09-10 10:18
Not really. #1277 talks about features. It appears to have been fixed back then.

**Comment by alexcrichton** [comment] 2015-09-10 16:54
Hm, good point. I could of sworn we had a few dupes for this issue, but I guess this one will now become the "one true issue"!

**Closed** 2015-10-12 02:36 UTC
Labels: C-doc
