### ISSUE TITLE
allow runner configuration to use feature flags

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/cargo#14314] opened 2024-07-27 22:46 UTC
### Problem

In the embedded space, I have several chips with the same target triple, but which require a different runner. My `Cargo.toml` contains features that are sufficient to know which runner to use. However, my `.cargo/config.toml` cannot choose a runner based on those features. Error-prone manual editing is required.

(Specifically, target is `thumbv7em-none-eabihf`, runner is `probe-rs run --chip=nrf52833-xxAA` or `probe-rs run --chip=nrf52840-xxAA` depending on board feature flags.)

### Proposed Solution

It would be great to be able to have the full Cargo `cfg()` available in `cargo.toml`. Specifically, it would be nice to be able to write something like

    [target.'cfg(feature = "myfeature")']

I'm not wedded to the particulars: anything that lets me pick the correct runner automagically would be fine.

**Comment by weihanglo** [comment] 2024-07-27 23:27
Thanks for providing your use case. This seems like a duplicate of <https://github.com/rust-lang/cargo/issues/8170>. In the meanwhile custom `--cfg` is an alternative.

See also <https://github.com/rust-lang/cargo/issues/14306>

**Closed by weihanglo** 2024-07-27 23:27 UTC
Labels: C-feature-request, S-triage
