### ISSUE TITLE
cargo publish --all?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/cargo#4860] opened 2017-12-24 10:06 UTC
It would be really nice to release workspace projects with `cargo publish --all`, where cargo automatically finds out the "core" crate in the workspace and finds its way up to the "top level" of the workspace and releases each individual crate.

A `publish --dry-run` should happen (on all crates) _before_ the actual release. This includes that `publish --dry-run`ing a "upper level" crate with the workspace in mind. For example, if one has a dependency tree like this:

```
UpperLevelA
  - LowerLevelA
  - LowerLevelB
```

`cargo publish --dry-run` fails on `UpperLevelA` crate because the lower levels are not yet released. This should be considered in a `publish --all` command!

---

I hope there is no such issue already.

**Comment by alexcrichton** [comment] 2017-12-25 15:43
Thanks for the report! I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/1169 which I believe it's a dupe of

**Closed by alexcrichton** 2017-12-25 15:43 UTC
