### ISSUE TITLE
cargo should allow debug=true without turning off ndebug

### ISSUE THREAD

**Issue by metajack** [rust-lang/cargo#1432] opened 2015-03-18 20:55 UTC
We turned debug=true on for release builds in Servo because otherwise debug symbols are missing on Linux. However, this is terrible performance because this setting also turns of ndebug, which turns on task state, which is bad.

We'd like to get the symbols and keep the debug asserts off.

**Comment by alexcrichton** [comment] 2015-03-18 22:44
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/1398, so closing in favor of that.

**Closed by alexcrichton** 2015-03-18 22:44 UTC
