### ISSUE TITLE
Cargo install triggering new compilation after cargo build

### ISSUE THREAD

**Issue by gbrlsnchs** [rust-lang/cargo#9272] opened 2021-03-15 23:48 UTC
**Problem**
While learning Rust, I created a simple CLI just to learn some core concepts. To build it, I run `cargo build --release`, and all goes well: code compiles and a binary is generated.

However, when trying to install it using `cargo install --path . --locked`, just after building it, Cargo triggers a new build, totally ignoring the build process that just occurred.

**Steps**

1. [Clone my simple CLI](https://github.com/gbrlsnchs/quist)
2. Checkout commit [a8cb746](https://github.com/gbrlsnchs/quist/commit/a8cb746b1b5b7bd7311d784bc02b2b9f05a8b750), which is guaranteed to retrigger compilation
3. Go to the project's root and run `cargo build --release`
4. Check whether the compilation was successful and then run `cargo install --path . --locked`

**Possible Solution(s)**
N/A

**Notes**
[I posted this issue on the forums](https://users.rust-lang.org/t/cargo-install-triggering-new-compilation-after-cargo-build/54123) and was advised to open this issue here.

Output of `cargo version`: `cargo 1.50.0 (f04e7fab7 2021-02-04)`

**Comment by ehuss** [comment] 2021-03-16 02:45
This is caused by `cargo install` using a different set of features than a normal `cargo build`.  `cargo install` ignores dev-dependencies, so those don't influence the feature resolution.

**Comment by gbrlsnchs** [comment] 2021-03-16 02:53
> This is caused by `cargo install` using a different set of features than a normal `cargo build`. `cargo install` ignores dev-dependencies, so those don't influence the feature resolution.

Should it be because of dev-dependencies, wouldn't this behavior also happen for projects like [hyperfine](https://github.com/sharkdp/hyperfine) (cited on my forum post, only compiles once with those same steps).

**Comment by ehuss** [comment] 2021-03-16 03:09
Hyperfine doesn't appear to have any dev-dependencies that add features to any shared dependencies, so the feature set ends up being the same with or without the dev-dependencies.

**Comment by ehuss** [comment] 2021-03-30 15:35
I'm going to close this as working as intended, though I understand that it can be surprising or confusing.  Issue #2904 is tracking adding something that would help explain why this is happening.

**Closed by ehuss** 2021-03-30 15:35 UTC
Labels: C-bug
