### ISSUE TITLE
cargo build thiserror failed

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/cargo#11363] opened 2022-11-11 07:36 UTC
### Problem

Execute `cargo clean` to solve the compilation pass. Why directly execute cargo b to report this error

```bash
~ cargo b
...
...
    Checking webpki-roots v0.22.5
    Checking cpufeatures v0.2.5
    Checking polling v2.4.0
    Checking async-channel v1.7.1
    Checking tokio-rustls v0.23.4
    Checking thiserror v1.0.37
    Checking rust_decimal v1.26.1
    Checking sha1 v0.10.5
    Checking async-lock v2.6.0
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/baoyachi/.cargo/registry/src/crates.io/thiserror-1.0.37/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to previous error
warning: build failed, waiting for other jobs to finish...

```

The Detail error: https://github.com/dtolnay/thiserror/issues/192

### Possible Solution(s)

https://github.com/dtolnay/thiserror/issues/192

### Version

```text
~ rustc -Vv
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
➜  ~ cargo -Vv
cargo 1.65.0 (4bc8f24d3 2022-10-20)
release: 1.65.0
commit-hash: 4bc8f24d3e899462e43621aab981f6383a370365
commit-date: 2022-10-20
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by weihanglo** [comment] 2022-11-11 08:27
Thank you for the report. 

I read the thread (and other referenced threads). Seems that almost all people eventually found that it was a bug from rust-analyzer[^1], and it already got fixed. I am not sure if there is anything Cargo can do. If rust-analzyer needs to coordinate with Cargo we're happy to.

Going to close this out soon. If you think it's wrong, please attach a reproducible example to help the investigation.
(I cannot reproduce this either)

[^1]: https://github.com/rust-lang/rust-analyzer/pull/13010

**Closed by weihanglo** 2022-11-11 08:27 UTC
Labels: C-bug

**Comment by baoyachi** [comment] 2022-11-11 09:42
Thx @weihanglo
