### ISSUE TITLE
override "current package believes it's in a workspace"

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#5418] opened 2018-04-26 03:34 UTC
If you create a crate inside another one, sometimes you get the above quoted error when trying to build it.

As far as I can tell, there's no solution. You can never build the crate because it's not really in the workspace, yet you can't build it separately either. The only recourse is to move the whole thing to another directory.

I propose a new flag, called something like `--no-workspace` or `--believe-nothing--reality-is-fake--just-build-here`, that would ignore the surrounding workspace and build the crate as it would have done before workspaces were invented. Does this make sense?

**Comment by sfackler** [comment] 2018-04-26 03:49
It sounds like `workspace.exclude`? https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-section

**Comment by durka** [comment] 2018-04-26 03:58
I guess that's a workaround, but modifying the outer crate (the one that's interfering with my ability to build the one I just created) is not an ideal solution.

**Comment by gnzlbg** [comment] 2018-04-27 10:04
I ran into this here, https://github.com/rust-lang/cargo/issues/5421 which arnavion suggested on IRC is a duplicate of this one. I worked around the issue by adding a:

```toml
[workspace]
members = []
```

to the crate in question.

**Comment by matklad** [comment] 2018-04-27 15:09
Yeah, the current solutions to this are

* add exclude to the parent crate
* add

  ```
  [workspace]
  ```
  to the current crate (note that `members = []`) is not really required. 

I wonder if `cargo new` should add an empty `workspace` key by default?

**Comment by durka** [comment] 2019-01-12 04:47
This gets me every time. Would a PR to change the behavior of `cargo new` as @matklad suggested be accepted?

**Comment by dwijnand** [comment] 2019-01-12 10:47
I think if it's conditional on being nested in another crate, then yes, allowing regular `cargo new` to remain unaffected.

**Closed** 2019-04-01 12:55 UTC
Labels: C-feature-request

**Comment by vjgaur** [comment] 2022-04-06 16:44
I encountered similar error  where I added flipper smart contract folder `cargo contract new flipper` as I was working on this tutorial [Smart Contract using ink! ](https://docs.substrate.io/tutorials/v3/ink-workshop/pt1/)
After adding this folder I did not add flipper as member in Cargo.toml workspace of substrate node template.  If any one going through the same tutorial you will probably  come across the same error. Use the below solution.
`[workspace]
members = [
    'node',
    'pallets/template',
    'runtime',
    'flipper' // added flipper smart contract folder 
]
[profile.release]
panic = 'unwind'`

**Comment by brson** [comment] 2024-06-03 22:44
I hit this problem today and modifying either manifest is not an option (setting an environment variable would be). It seems the only workaround for me is to make the directory structures of the two projects disjoint.

**Comment by hydra** [comment] 2025-05-05 13:17
I ran into this today.  I have a project, which has a workspace in the root, it has crates that the workspace uses, one of the crates has a 'demo' folder in which I want to place a stand-alone demo that users can just copy as-is and use the demo.

```
.
├── Cargo.toml <-- workspace
├── crates
│   ├── library_crate
│   │   ├── Cargo.toml <-- member
│   │   ├── demo
│   │   │   ├── Cargo.toml  <-- standalone
│   │   │   └── src
│   │   │       └── main.rs
│   │   ├── README.md
│   │   └── src
│   │       └── lib.rs
│   └── <other crates>
│       ├── Cargo.toml
│       └── src
│           └── lib.rs
└── target
```

Is there really no way to have a standalone demo crate?
