### ISSUE TITLE
[patch] section is unused, but causes a dependency to downgrade

### ISSUE THREAD

**Issue by kuviman** [rust-lang/cargo#6204] opened 2018-10-22 13:43 UTC
**Problem**

[patch] section is unused, but causes a dependency to downgrade.

**Steps**

1. Sample `Cargo.toml`:
```toml
[package]
name = "hello"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]

[dependencies]
glutin = "0.18.0"
rusttype = { version = "0.7.1", features = [ "gpu_cache" ] } # Without this thing everything works as expected
```
2. Everything works correctly (uses the latest version of `winit` which is going to be patched)
3. Try to apply a patch:
```toml
[patch.crates-io]
winit = { git = "https://github.com/tomaka/winit" }
```
4. `cargo update`:
```
    Updating git repository `https://github.com/tomaka/winit`
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding redox_syscall v0.1.40
      Adding remove_dir_all v0.5.1
    Updating smithay-client-toolkit v0.3.0 -> v0.2.6
      Adding tempfile v3.0.4
    Updating winit v0.17.2 -> v0.17.1
```

5. Further `cargo update`s don't even try to update patch's git repository, the patch itself is shown as unused in `Cargo.lock`:

```toml
[[patch.unused]]
name = "winit"
version = "0.17.2"
source = "git+https://github.com/tomaka/winit#062bb0cef23b82ae31085ca25b79429474adca3e"
```

**Possible Solution(s)**

I think it would be useful to at least be notified that the patch is not being used. I would prefer to have an error here.

**Notes**

Output of `cargo version`:
```
cargo 1.29.0 (524a578d7 2018-08-05)
```

Nightly cargo does the same thing.

So, this was noticed because I was using a patched version of `winit`. Since I added the patch, a new version of the crate was published. When that happened `cargo update` downgraded `winit`, so neither the initial patched version nor the newly published one was used, resulting in the patch being effectively undone.

**Comment by kuviman** [comment] 2018-10-22 14:05
Is is also interesting that `cargo run` actually shows the error when you apply the patch first time:

```
    Updating git repository `https://github.com/tomaka/winit`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `rusttype`.
    ... required by package `andrew v0.1.2`
    ... which is depended on by `smithay-client-toolkit v0.4.0`
    ... which is depended on by `winit v0.17.2 (https://github.com/tomaka/winit#062bb0ce)`
    ... which is depended on by `glutin v0.18.0`
    ... which is depended on by `hello v0.1.0 (file:///P:/temp/hello)`
versions that meet the requirements `= 0.7.1` are: 0.7.1

all possible versions conflict with previously selected packages.

  previously selected package `rusttype v0.7.2`
    ... which is depended on by `hello v0.1.0 (file:///P:/temp/hello)`

failed to select a version for `rusttype` which could resolve this conflict
```

But `cargo update` doesn't fail, instead it uses another version

**Comment by alexcrichton** [comment] 2018-10-23 14:03
@kuviman the first comment here is expected behavior where `cargo update` can update anything and `[patch]` simply augments a source, it doesn't force a candidate to be used. The second comment here I'm not really sure how you got but it may be something over constrained? Do you have a reproduction of the second issue?

**Comment by kuviman** [comment] 2018-10-23 15:36
Ok, rereading the docs I noticed this:

>This will effectively add the local checked out version of uuid to the crates.io registry for our local project.

> This means that the version number of the local checkout is significant and will affect whether the patch is used.

So, this explains why it behaves like this: the patch I am trying to use is incompatible (conflicting versions of the dependencies), so cargo uses another version.

But why is it so? Is there no way to enforce the patch? I expected that `[patch]` would replace all versions of the crate in the local registry, not add to the list.

And, I guess, there is still an issue that the patch is not being updated once ignored. So if the patch's repository was updated to be compatible, cargo would not try to pull the updates and still use another version.

```
C:\Users\kuviman\Projects\playground>cargo update
    Updating git repository `https://github.com/tomaka/winit`
    Updating registry `https://github.com/rust-lang/crates.io-index`
      Adding redox_syscall v0.1.40
      Adding remove_dir_all v0.5.1
    Updating smithay-client-toolkit v0.3.0 -> v0.2.6
      Adding tempfile v3.0.4
    Updating winit v0.17.2 -> v0.17.1

C:\Users\kuviman\Projects\playground>cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`

C:\Users\kuviman\Projects\playground>
```

There is no `"Updating git repository 'https://github.com/tomaka/winit'"` on second update

**Comment by alexcrichton** [comment] 2018-10-27 06:54
You can use `=a.b.c` dependencies to force a particular version to get used, but otherwise you cannot force a particular `[patch]` to get used. It looks like this was figured out though? I'm gonna go ahead and close this, but if there's remaining questions please feel free to post here still!

**Closed by alexcrichton** 2018-10-27 06:54 UTC
Labels: A-dependency-resolution, Command-update
