### ISSUE TITLE
target.rustflags and build.rustflags conflict

### ISSUE THREAD

**Issue by conradludgate** [rust-lang/cargo#14934] opened 2024-12-14 10:48 UTC
### Problem

Semi-related to #13774 (I couldn't find an exact match while searching).

Given a `~/.cargo/config.toml` with the following contents:
```toml
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-fuse-ld=/path/to/ld"]
```

And a `<project>/.cargo/config.toml` with the following contents:
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
```

When building for `--target aarch64-apple-darwin`, the `tokio_unstable` config is not set.

This makes it very awkward to have layered configuration. The linker settings I choose might be specific to my personal setup and target, whereas any config flags are specific to the project in question.

### Notes

Given a `~/.cargo/config.toml` with the following contents:
```toml
[build]
rustflags = ["-C", "link-args=-fuse-ld=/path/to/ld"]
```

And a `<project>/.cargo/config.toml` with the following contents:
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
```

Then they are correctly merged.

### Version

```text
cargo 1.83.0 (5ffbef321 2024-10-29)
release: 1.83.0
commit-hash: 5ffbef3211a8c378857905775a15c5b32a174d3b
commit-date: 2024-10-29
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.1.1 [64-bit]
```

**Comment by conradludgate** [comment] 2024-12-14 10:49
I filed this issue primarily because it took me an hour to debug why my rustflags was not being respected.

**Comment by weihanglo** [comment] 2024-12-14 14:36
Thanks for the detailed issue report!

While this is the current intended behaviour ([`target.<cfg>.rustflags` has higher precedence](https://doc.rust-lang.org/nightly/cargo/reference/config.html#buildrustflags)), this is indeed surprising sometimes. 

Here are some relevant discussions:

* #13774 as you mentioned it is slightly different than yours.
* #11885 is in the same situation, with a proposed solution (emit a warning).
* #5376 is exactly where people talk about the merge strategy of rust flags

Let's close this  in favour of others so we don't discuss the same thing in different places.

**Closed** 2024-12-14 14:41 UTC
Labels: C-bug, S-triage
