### ISSUE TITLE
cargo install fails with ssh

### ISSUE THREAD

**Issue by Niondir** [rust-lang/cargo#4444] opened 2017-08-28 08:04 UTC
**How to reproduce?**
Add the following lines to your git config:

```
[url "git@github.com:"]
	insteadOf = https://github.com/
```

running `cargo install xargo` fails like this:

```
$ cargo install xargo --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  [23/-1] error authenticating: failed connecting agent
```

**System**

Windows 10

```
$ cargo --version
cargo 0.20.0 (a60d185c8 2017-07-13)
```

**Comment by alexcrichton** [comment] 2017-08-28 14:29
Thanks for the report! I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2078 though so I'm going to close in favor of that.

**Closed by alexcrichton** 2017-08-28 14:29 UTC
