### ISSUE TITLE
neither RUSTFLAGS nor RUSTDOCFLAGS passed to rustdoc by "cargo test --doc"

### ISSUE THREAD

**Issue by decathorpe** [rust-lang/cargo#13697] opened 2024-04-03 20:13 UTC
We're running `cargo test` for many Rust crates we package in Fedora Linux to ensure they work in our environment and on all CPU architectures that we support. We define `RUSTFLAGS="--cap-lints=warn"` (among other things) to avoid crates starting to fail to build due to things like `#![deny(warnings)]` with newer Rust versions that add new lints.

Passing "--cap-lints=warn" with RUSTFLAGS works fine for normal library code and test code, but it doesn't get applied to rustdoc when it checks / compiles doctests, and this often causes problems because many crates use `#![deny(warnings)]` for their doctests / example code in doc comments.

I tried defining `RUSTDOCFLAGS="--cap-lints=warn"` in addition to having this flag already present in RUSTFLAGS, it didn't change the behaviour. I tried adding a `build.rustdocflags = "--cap-lints=warn"` setting to `.cargo/config`, and it didn't change anything either.

It appears that `cargo test --doc` isn't passing either RUSTFLAGS or RUSTDOCFLAGS to rustdoc correctly.

Good test cases might be the rand_core or pyo3 crates, which fail to build doctests with latest Rust stable due to `deny(warnings)`.

---

Originally filed here:
https://github.com/rust-lang/rust/issues/123424

**Comment by weihanglo** [comment] 2024-04-03 20:42
If you have this doc comment and run either

* `RUSTDOCFLAGS="--cfg mycfg" cargo t --doc`, or
* `cargo t --doc --config "build.rustdocflags='--cfg mycfg'"`

it will fail as expected.

```rust
/// ```
/// #[cfg(mycfg)]
/// assert!(false, "--cfg mycfg");
/// ```
pub fn f() {}
```

Cargo basically passes the user-provided flags as-is to rustc/rustdoc, so I wonder if rustdoc hijacks lint-level flags for something special. Needs some investigations...

**Comment by weihanglo** [comment] 2024-04-03 20:51
Found this: <https://github.com/rust-lang/rust/issues/67533>. So this is a duplicate of that.

**Comment by weihanglo** [comment] 2024-04-04 03:13
Close in favor of https://github.com/rust-lang/rust/issues/67533. Thanks for the report.

**Closed by weihanglo** 2024-04-04 03:13 UTC
Labels: A-doctests, S-triage
