### ISSUE TITLE
`cargo clean` hook to clean up arbitrary stuff.

### ISSUE THREAD

**Issue by vext01** [rust-lang/cargo#5078] opened 2018-02-26 12:17 UTC
Following on from #5077, we had a project which built some C code using an external build system (make in this case, but it could be autotools or cmake for example):
https://github.com/vext01/rust_link_test

Currently there is no way to clean the externally built code at `cargo clean` time. Such a feature would be very useful.

**Comment by alexcrichton** [comment] 2018-02-26 23:22
I think this is a dupe of https://github.com/rust-lang/cargo/issues/572, so I'm going to close in favor of that

**Closed by alexcrichton** 2018-02-26 23:22 UTC

**Comment by vext01** [comment] 2018-02-27 13:59
Thanks
