### ISSUE TITLE
Require a method to avoid vendoring target deps that will never be used

### ISSUE THREAD

**Issue by flukejones** [rust-lang/cargo#12393] opened 2023-07-23 22:41 UTC
### Problem

This is best illustrated with some screenshots.

![Screenshot from 2023-07-24 10-26-26](https://github.com/rust-lang/cargo/assets/2015870/37b31a3e-98cc-4005-a7c3-2ad8dc382407)

![Screenshot from 2023-07-24 10-28-01](https://github.com/rust-lang/cargo/assets/2015870/a41274f6-1e7a-4e32-aa77-1e588247fe8a)

I have a project that will only ever be built for Linux. I don't see any obvious way to specify this as such and so I'm not sure how best to handle it. But it *is* an issue because this project gets built on external servers for packaging for distros, and having such an absurdly high vendoring size can adversely affect these constrained environments.

### Proposed Solution

Something along the lines of:

```toml
[package]
name = "named_thing"
version.workspace = true
license = "MPL-2.0"
target = "unix"
target_arch = "x86_64"
```

which would then restrict all chained `[target.'cfg(TARGET_OS)'.dependencies]` automatically as they could then never be built, and as such vendoring for these targets can be fully ignored.

**Comment by weihanglo** [comment] 2023-07-23 22:58
Thanks for the report.
Feel like this is a duplicate of <https://github.com/rust-lang/cargo/issues/7058> to some extent. The solution of each of them is very likely the same.

**Comment by weihanglo** [comment] 2023-07-23 23:01
These are all feature requests for partial vendoring:

- <https://github.com/rust-lang/cargo/issues/9234> for vendoring from certain sources.
- <https://github.com/rust-lang/cargo/issues/7058> for vendoring on certain platforms.
- <https://github.com/rust-lang/cargo/issues/9980> for vendoring on a certain feature set.

**Comment by flukejones** [comment] 2023-07-24 22:30
Sounds like a much needed feature then. Especially for target-os and feature sets, where both of these would contribute *heavily* to reduced source package sizes for Linux distribution builds.

**Comment by weihanglo** [comment] 2023-07-26 12:02
Thanks. I'll close this in favor of the aforementioned issues.

**Closed** 2023-07-26 12:02 UTC
Labels: C-feature-request, S-triage
