### ISSUE TITLE
Schrödinger's dependency graph

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/cargo#13373] opened 2024-01-31 12:18 UTC
### Problem

At https://github.com/robertbastian/icu4x/commit/3a722623e13bde14db65c925deb19c59d60d6fd9:

```
> cargo --version
cargo 1.75.0 (1d8b05cdd 2023-11-20)
> cargo check
thread 'main' panicked at src/cargo/util/graph.rs:149:20:
the only path was a cycle, no dependency graph has this shape
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by epage** [comment] 2024-01-31 19:28
This looks to be a duplicate of #12941 which was fixed in #12977 (1.76). Closing in favor of that issue.  If there is a reason this should be re-opened, especially if its still reproducible with 1.76, let us know!

**Closed by epage** 2024-01-31 19:28 UTC
Labels: C-bug, S-triage
