### ISSUE TITLE
error: "/home/xiaguangbo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist

### ISSUE THREAD

**Issue by xiaguangbo** [rust-lang/cargo#14371] opened 2024-08-08 11:01 UTC
### Problem

```
$ cargo build
error: "/home/xiaguangbo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
```

delete `Cargo.lock` `target/` at my project, do `rustup update`, rebuild, report this err.
reinstall rust not solution

### Possible Solution(s)

at `...rustlib/src/rust/`, do `nano Cargo.lock`, rebuild is ok

**Comment by weihanglo** [comment] 2024-08-08 11:11
Close as duplicate of https://github.com/rust-lang/rust/issues/128808

**Closed** 2024-08-08 11:11 UTC
Labels: C-bug, S-triage
