### ISSUE TITLE
Cargo apparently does not forward opt level to doctest

### ISSUE THREAD

**Issue by IceTDrinker** [rust-lang/cargo#12877] opened 2023-10-25 13:24 UTC
### Problem

When running cargo doctest with a release profile with lto = "fat" I encountered the following miscompile https://github.com/rust-lang/rust/issues/116941

as advised here https://github.com/rust-lang/rust/issues/116941#issuecomment-1779226644

I am opening this issue to ask whether the potential lack of forwarding of opt levels (as identified in the comment) is a conscious decision ?

As a user of doctests I would expect the cargo profile to apply to the doctests being compiled and at the moment it seems some parts of it are not forwarded to doctests.

### Steps

From my understanding from the linked issue above any doctest does not get the proper opt levels from cargo at the moment

### Possible Solution(s)

I'm guessing that if the opt levels (and other flags) are not forwarded to the doctests that they perhaps ought to be to match a simple binary compilation that one would trigger via `cargo build`?

### Version

```text
cargo 1.75.0-nightly (6fa6fdc76 2023-10-10)
release: 1.75.0-nightly
commit-hash: 6fa6fdc7606cfa664f9bee2fb33ee2ed904f4e88
commit-date: 2023-10-10
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.3.0-DEV (sys:0.4.66+curl-8.3.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by ehuss** [comment] 2023-10-25 20:06
This was originally intentional because rustdoc did not support codegen arguments. It has since partially gained that ability, but cargo was never updated to start passing them in. I'm going to close as a duplicate of #6570.

**Closed by ehuss** 2023-10-25 20:06 UTC
Labels: C-bug, A-doctests, S-triage

**Comment by IceTDrinker** [comment] 2023-10-25 22:04
My bad, missed that issue, thanks for the answer!
