### ISSUE TITLE
cargo clean doesn't work well from Windows

### ISSUE THREAD

**Issue by emptyfist** [rust-lang/cargo#12214] opened 2023-06-01 15:33 UTC
### Problem

I tried to build rust project with Cargo but faced `Blocking waiting for xxxxx`.
So I tried to clean cargo cache as following
`cargo clean`

But caches are not cleared from Windows OS so I manually remove those files from System drive.

**Comment by weihanglo** [comment] 2023-06-01 17:40
Due to the lack of a minimal set of steps to reproduce, it's hard to help with this issue. Could you add a minimal reproducer and attach the version information via `cargo -vV` as well?

Besides, a related pull request just got merged <https://github.com/rust-lang/cargo/pull/11442>. The fix should be released in the next few days on nightly channel.

**Comment by emptyfist** [comment] 2023-06-02 05:43
Sorry for lack information.

> cargo 1.69.0 (6e9a83356 2023-04-12)
> release: 1.69.0
> commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
> commit-date: 2023-04-12
> host: x86_64-pc-windows-msvc
> libgit2: 1.5.0 (sys:0.16.0 vendored)
> libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
> os: Windows 10.0.19044 (Windows 10 Pro N) [64-bit]

**Comment by weihanglo** [comment] 2023-06-02 07:45
What did you want to achieve, what have you done, and what did it exactly mean by “caches are not cleared”?

We need a clear description and a reproducer of the problem to proceed. Thank you.

**Comment by weihanglo** [comment] 2023-06-15 12:22
Dud you have any other editor opening the same project? Usually Rust Analyzer or some IDE integration will run `cargo check` which does block other command from running, as they are downloading and unpacking dependency source code.

If you were stuck in “Blocking waiting for xxxx” for a long while, say 3 minutes, without any IDE integration in the background, it might be a real issue.

If in that case you could try deleting `~/.cargo/registry/.package-cache`. That should unlock your registry cache.

**Comment by emptyfist** [comment] 2023-06-15 13:23
Thank you for your advice.
In addition, there are no other editor opening the same project.
Anyway, I manually deleted the above file and after than, it worked well.
Thank you.

**Comment by weihanglo** [comment] 2023-06-15 13:39
Cargo uses [`LockFileEx`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-lockfileex) on Windows to do file locking on `.package-cache`, if that makes any sense to you.

If you can reproduce it very constantly, would you be willing to provide a minimal reproducible example?

**Closed** 2024-02-29 09:42 UTC
Labels: C-bug, S-needs-info
