### ISSUE TITLE
build.rs should be the default

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#2814] opened 2016-06-29 17:28 UTC
If you have a `src/main.rs`, you don't need to define a `[bin]` section, and if you have a `src/lib.rs`, you don't need to define a `[lib]` section.

Almost all of the build scripts I see have 

```
build = "build.rs"
```

and very occasionally

```
build = "src/build.rs"
```

in their `Cargo.toml`. Could we convention over configuration this, like we do for crate roots?

**Comment by alexcrichton** [comment] 2016-06-29 23:08
Yeah I feel that build.rs next to Cargo.toml is so overwhelmingly the convention today that it'd be good to codify this in Cargo itself today. My only concern here is backwards compatibility, where if `build.rs` *weren't* a build script we'd now accidentally pick it up as a build script. I suspect this would be pretty rare, however, if it ever happened at all.

We'd also want to be sure to add `build = false` to disable the default logic and guarantee that your crate has no build script.

**Comment by kinetiknz** [comment] 2017-02-13 19:18
Is this a duplicate of #3391?

**Comment by alexcrichton** [comment] 2017-02-13 19:36
Indeed!

**Closed by alexcrichton** 2017-02-13 19:36 UTC
Labels: A-configuration
