### ISSUE TITLE
Publish build date as environment variable

### ISSUE THREAD

**Issue by digama0** [rust-lang/cargo#2476] opened 2016-03-13 10:07 UTC
Currently, it is possible to query the build version in a crate via `env!("CARGO_PKG_VERSION")`, but there does not seem to be any support for getting the build date, which is commonly also bundled with the application. Might I suggest a similar `CARGO_BUILD_DATE` environment variable, ideally in an easily parsable format for `rust-chrono` such as ISO 8601?

**Comment by alexcrichton** [comment] 2016-03-13 20:31
This might actually be best done as a rustc feature rather than a Cargo feature, in theory all sorts of compiles would want this kind of info!

**Comment by digama0** [comment] 2016-03-14 01:11
As a rustc feature, is there any way to execute an arbitrary console command at compile time and put the result in a `&'static str`, similar to `env!`? That would also be a reasonable solution, although it would rely on the existence of certain commands, such as `date`, which might be better left to a build script.

**Comment by alexcrichton** [comment] 2016-03-14 05:34
Not currently, unfortunately, but it seems like something that wouldn't be totally unreasonable for the compiler to define.

The build script can print out:

```
cargo:rustc-cfg=foo="bar"
```

but unfortunately you can't get the value at compile-time (you can only test against it).

**Comment by joshtriplett** [comment] 2016-03-19 21:27
Embedding the build date would make the build not reproducible: two builds of the same source would produce different binaries.  See https://reproducible-builds.org/ and https://reproducible-builds.org/specs/source-date-epoch/ .

I would suggest using the version number, git commit hash, or similar values that won't change unless the source does.

**Comment by sunjay** [comment] 2016-06-20 00:26
Is there a way to embed the git commit hash?

**Comment by alexcrichton** [comment] 2016-06-20 03:57
@sunjay the "easiest" way to do that now is to have a build script that extracts the hash, writes it to a file, and then `include_str!` is in the main program. Not exactly easy per se but gets the job done!

**Comment by carols10cents** [comment] 2017-09-25 17:42
I'm going to close this since it sounds like this should be in rust-lang/rust instead.

**Closed by carols10cents** 2017-09-25 17:42 UTC
