### ISSUE TITLE
Mutually exclusive features support

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/cargo#7924] opened 2020-02-24 09:16 UTC
**Describe the problem you are trying to solve**

Say that we would like to develop a crate which has two features mutually exclusive:

- `runtime-tokio`
- `runtime-async-std`

I would like to keep the same api, in this case if I run:
```
cargo test --all-features
```
it will show `duplicated elements`.

I think what's missing here is the notion of `mutually exclusive` features, if we can say two features are mutually exclusive, it will be able to solve the problem because we can then let `cargo` to run them one by one.

For example, we would like to design a crate with features: `a`, `b`, `c`, `d`, `a` and `b` are mutually exclusive.

Then `cargo test --all-features` should run two times:

```
cargo test  --no-default-features --features a,c,d
cargo test  --no-default-features --features b,c,d
```

**Describe the solution you'd like**

**Notes**

**Comment by ehuss** [comment] 2020-02-24 15:00
Thanks for the report.  This appears to be essentially a duplicate of #2980, so I'm going to close in favor of that.

**Closed by ehuss** 2020-02-24 15:00 UTC
Labels: C-feature-request
