### ISSUE TITLE
cargo recompiles even without any modifications

### ISSUE THREAD

**Issue by theemathas** [rust-lang/cargo#1388] opened 2015-03-07 03:00 UTC
Simple reproduction steps:

```bash
cargo new asdf
cd asdf
cargo build
cargo build
```

The original behavior of cargo is that the second `cargo build` does nothing. However, it currently recompiles the crate (which is probably wrong).

For crates with dependencies, cargo apparently recompiles only local dependencies, and not dependencies on crates.io or anything else.

**Comment by alexcrichton** [comment] 2015-03-07 05:21
This is a dupe of https://github.com/rust-lang/cargo/issues/1386 and should be fixed by https://github.com/rust-lang/rust/pull/23090, but thanks for the report!

**Closed by alexcrichton** 2015-03-07 05:21 UTC
