### ISSUE TITLE
`cargo install` using massive memory footprint under Docker/Buildx/QEMU

### ISSUE THREAD

**Issue by simbleau** [rust-lang/cargo#11371] opened 2022-11-14 02:21 UTC
### Problem

Docker with QEMU and Buildx seems to be incapable of any cargo command without enough memory demand to crash GitHub Actions. Which means it's using at least 4GB Ram (GitHub Actions free version capacity), which seems unreasonable...

Example:
https://github.com/simbleau/cddns/actions/runs/3457952620/jobs/5771886161

### Steps

Inside a Dockerfile, run `cargo install ...`

**Comment by weihanglo** [comment] 2022-11-14 12:21
Looks like it failed during `Updating crates.io index`. It is likely an issue of libgit2 memory usage. Please try out this solution https://github.com/rust-lang/cargo/issues/10583#issuecomment-1129997984 or use unstable feature [`sparse-registry`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#sparse-registry) to fetch registry data on demand.

I am going to close this at this moment, as it seems to be a duplicate of #10583. If you think this is a different one, please comment below. We'll consider reopen then. Thank you!

**Closed by weihanglo** 2022-11-14 12:21 UTC
Labels: C-bug
