### ISSUE TITLE
Add `--workspace` to `cargo add`

### ISSUE THREAD

**Issue by jmg-duarte** [rust-lang/cargo#13915] opened 2024-05-15 10:21 UTC
### Problem

I am working on a project where we're placing all dependencies in the workspace. Whenever I add a new dependency I want to be able to add it to the workspace rather than the local `Cargo.toml` file.

### Proposed Solution

The command
```bash
cargo add tokio -F full --workspace
```
Should add `tokio` to the the current `Cargo.toml` like so:
```toml
[dependencies]
tokio = { workspace = true, features = ["full"] }
```
And to the workspace `Cargo.toml`:
```toml
[dependencies]
tokio = "1" # or whatever version it would add
```

To find the workspace file, the command would go up the directories looking for `Cargo.toml` where `members` contains the current package.

Additionally, the `--workspace` flag could take a parameter with the workspace `Cargo.toml`'s path.

### Notes

If the feature is to be implemented, I am available to do it!

**Comment by weihanglo** [comment] 2024-05-15 12:36
Thanks for the proposal. This is probably a duplicate of <https://github.com/rust-lang/cargo/issues/10608>?

**Comment by jmg-duarte** [comment] 2024-05-15 13:21
> This is probably a duplicate of https://github.com/rust-lang/cargo/issues/10608?

Yes and no 😅 the ideas are clearly siblings but the interface I was looking for is not the same as the one proposed on that issue.

I feel that my interface is much more clear cut than those discussed there. It's clear where you're adding by default (the current package) and the flag makes it explicit where it goes to.

But let me know if I should move this discussion there!

**Comment by weihanglo** [comment] 2024-05-15 13:42
Thanks for the clarification! Yeah the design space is quite the same, so better discussing the needs and alternatives altogether :)

Closing this and feel free to drop ideas there.

**Closed by weihanglo** 2024-05-15 13:42 UTC
Labels: C-feature-request, S-triage
