### ISSUE TITLE
Add option to disable --document-private-items for targets that have it by default

### ISSUE THREAD

**Issue by Pand9** [rust-lang/cargo#8237] opened 2020-05-12 16:57 UTC
Building a documentation for a Rust project - which at this stage is just a single crate with single binary target - I've discovered that all private items are included. Running `-vv` helped me discover that Cargo has ran `rustdoc` with flag `--document-private-items`, even though I haven't passed it to cargo. There is no option `cargo doc --no-document-private-items` either.

I would like to have such option.

**Comment by ehuss** [comment] 2020-05-23 23:56
Thanks for the report!  Closing as a duplicate of #7963.

**Closed by ehuss** 2020-05-23 23:56 UTC
Labels: C-feature-request
