### ISSUE TITLE
It should be possible to pass multiple workspace crates to `cargo publish [--dry-run]`

### ISSUE THREAD

**Issue by anp** [rust-lang/cargo#8459] opened 2020-07-07 00:29 UTC
I have a [script in my project's CI](https://github.com/anp/moxie/blob/main/ofl/src/published.rs#L20-L29) which is responsible for publishing crates. It resolves ordering issues when publishing by only publishing crates [in order of their reverse deps](https://github.com/anp/moxie/blob/main/ofl/src/workspace.rs#L92-L116). If I promote the versions of multiple crates in a single PR, they all upload correctly when it lands. While this works pretty well for the "production" use case, it doesn't support dry-running more than one crate version change at a time. As far as I can tell, all of a crate's dependencies must be published before validating it and there's no way to tell cargo to "just assume a crate'll be there".

I think the minimal requirement is some way to tell a single `cargo publish --dry-run` invocation that it's safe to assume certain packages will have been published. To me, a more attractive alternative would be supporting the behavior I linked above in a single command. Specifying all of the crates to publish (or dry run) at once, cargo would be able to infer which dry-run assumptions could be made.

**Comment by ehuss** [comment] 2020-07-07 01:32
Thanks for the report!  This is more or less a duplicate of #1169, so closing in favor of that.

**Closed by ehuss** 2020-07-07 01:32 UTC
Labels: C-feature-request
