### ISSUE TITLE
Cargo update hangs with a specific configuration of dependency crates

### ISSUE THREAD

**Issue by golddranks** [rust-lang/cargo#4474] opened 2017-09-06 13:53 UTC
It appears to be a some kind of a livelock. It never prints anything after `Updating registry https://github.com/rust-lang/crates.io-index`, but if I enable the tracelog, it seems to be doing copious amounts of... something. Eventually I stopped it with ctrl-c. Here's a gist of the tracelog: https://gist.github.com/golddranks/3c8bfb3dfe7b8e26b8052cdfd02af7da

Here's a repository that triggers the behaviour for me. I tried it on two networks, but unfortunately I haven't been able to try it on multiple computers. I also tested it on the latest nightly, latest stable (1.20) and the stable before that (1.19). They all seem to trigger it. I'll be curious to see if it hangs on other people's computers too. https://github.com/golddranks/cargo_test

This affects my daily work so hopefully this gets resolved soon. First of all, I'm curious to hear whether it happens on other computers too!

**Comment by golddranks** [comment] 2017-09-06 14:21
I got a confirmation that it happens on other people's computers too. It seems that it happens with the combination of the crates rust-s3 and postgres in the dependencies. Updated the demo repository.

**Comment by pgerber** [comment] 2017-09-06 20:42
Sounds like #4066

**Comment by pgerber** [comment] 2017-09-06 22:28
Looks like this is caused by the update of rust-s3 from 0.6.1 to 0.6.2. I'm experiencing the same issue with the aws-sdk-rust crate which hasn't been updated for some time. My guess is that they have some dependency in common that causes the issue.

You may want to explicitly use rust-s3 0.6.1 for now:

`rust-s3 = "=0.6.1"`

**Comment by pgerber** [comment] 2017-09-06 23:12
@golddranks I looked at it a bit closer, the `generic-array` crate appears to cause the issue. Looks like `postgres` 0.15 depends on 0.7 which conflict with some of the other dependencies.

Generic-array [has been updated](https://github.com/sfackler/rust-postgres/commit/58133f37e1a535822860e8b29172c01fc4d2df75) and the next release should fix the issue.

You can directly use the git repository from `Cargo.toml` if you want:

`postgres = { git = "https://github.com/sfackler/rust-postgres" }`

**Comment by golddranks** [comment] 2017-09-07 04:15
It seems that rust-s3 0.6.2 contained breaking changes. I reported the issue: https://github.com/durch/rust-s3/issues/18

Some takeaways: 
1) A re-affirmation that https://github.com/rust-lang/rfcs/pull/1977 is a very valuable RFC to have :)
2) Also having tooling that helps reasoning with API changes and version bumps would be valuable.
3) I don't understand why mismatching versions of `generic-array` often break the build even though any types of it are not exposed in the API. I'd be happy if someone could enlighten me.
4) Cargo should try and have some heuristic to fix https://github.com/rust-lang/cargo/issues/4066

Closing this issue.

**Comment by golddranks** [comment] 2017-09-13 03:56
I encountered another breaking change with crates updating to `generic-array 0.8` which brought me to reopen this issue.

Is there a some *reason* that cargo can't find compatible versions of the crates? `generic-array` seems to induce the breakage, but it isn't a public dependency of the crates as far as I know, yet cargo seems to consider it as such. Why?

**Comment by alexcrichton** [comment] 2017-09-13 14:03
This is likely https://github.com/rust-lang/cargo/issues/4066

**Comment by carols10cents** [comment] 2017-10-03 15:19
Closing this since it sounds like it will be solved by solutions to #4066 and/or implementing public/private dependencies.

**Closed by carols10cents** 2017-10-03 15:19 UTC

**Comment by golddranks** [comment] 2017-10-04 03:34
For the record, this was caused by `generic-array` having a needlessly strict dependency constraint: https://github.com/fizyk20/generic-array/issues/49#issuecomment-329170351
