### ISSUE TITLE
Custom location for output directory (`target` path)

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#1156] opened 2015-01-13 12:55 UTC
It should be possible to change the location of Cargo's output from the default `target` subdirectory. I'm not sure whether it's not possible or I just don't know how to read the Cargo doc.

Use case: I have project `foo` with several sub-directories `arnold`, `bethany`, `chris`, etc. I use CMake to build the main project which builds each sub-project in paths like `build/arnold`. One of these sub-projects now uses Rust and Cargo (because Cargo has awesome dependency management), so from the point of view of the project Cargo should place its output in `build/bethany` not `bethany/target`.

This is not currently a significant issue, but it could be with larger projects.

A related issue is that rustc warning/error messages should now give either absolute paths or paths relative to the root of the project, i.e. `bethany/src/lib.rs:36` instead of `src/lib.rs:36`.

**Comment by nick29581** [comment] 2015-01-21 01:29
+1 This pains me.

**Comment by marcbowes** [comment] 2015-01-23 13:13
+1. My use case also stems from integrating with another build system.

I'd also like it if this sort of thing picked up config from the env, to avoid passing flags all over the show.

**Comment by gentoo90** [comment] 2015-04-12 15:03
+1

**Comment by TimNN** [comment] 2015-04-24 15:46
+1 I use SublimeLinter to automatically run cargo in the background and display any errors in Sublime Text. This however means that there is still a cargo process running in the background when I switch back to the terminal and run `cargo test` (or something similar). Running two build processes at the same usually leads to one of them exiting unsuccessfully because some file was already moved and no longer exists. This could easily be solved by having SublimeLinter build in a separate directory, if it were possible to do so.

**Comment by alexcrichton** [comment] 2015-05-18 21:43
Closing as a dupe of https://github.com/rust-lang/cargo/issues/482

**Closed by alexcrichton** 2015-05-18 21:43 UTC
