### ISSUE TITLE
Option for whether `lib.rs` should be rebuilt after build.rs is rerun

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1422] opened 2015-03-15 21:01 UTC
Currently, whenever `build.rs` is re-run, both `lib.rs` *and* `main.rs` get rebuilt. It would be useful if there were some option to only rebuild `main.rs` after `build.rs` is rerun, not both. This wouldn't want to be the default behaviour, as most build scripts will affect content in `lib.rs`, but some will only affect `main.rs`, and an option for that would be nice.

This isn't that urgent, and it may not actually want to be built, but it would probably be useful.

This would probably depend on https://github.com/rust-lang/cargo/issues/1162.

**Comment by alexcrichton** [comment] 2015-03-16 13:25
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/1162 because Cargo does not currently ever assume that a binary is the location where a native library should be linked if a library is also present. Cargo will instruct the compiler to link the native library to the Rust library and then purposefully not link the native library to the binary generated.

Unfortunately this means that this is not possible for Cargo to know that a build script (or native dependency) is in fact for just a binary, not a library.

**Closed by alexcrichton** 2015-03-16 13:25 UTC

**Comment by daboross** [comment] 2015-03-17 04:53
Would it be possible for this to be a configuration though? I realize it isn't going to be what most people want, but it seems like there would be some projects where build.rs only affects main.rs, not lib.rs (where it is used for something other than native library linking).

**Comment by alexcrichton** [comment] 2015-03-17 16:42
That sounds reasonable to me, I've opened https://github.com/rust-lang/cargo/issues/1430 on the topic.
