### ISSUE TITLE
`cargo test` prints build errors twice, mixed together, as it runs rustc twice in parallel

### ISSUE THREAD

**Issue by kballard** [rust-lang/cargo#1569] opened 2015-05-02 00:10 UTC
Running `cargo test` on a library crate that has a build error ends up printing the error output twice, with the lines mixed together. It turns out this is because it runs two parallel invocations of `rustc`, one for the library and one for the tests, and when both invocations print errors they get printed concurrently. Even more confusingly, it doesn't just mix lines together, but it mixes pieces of lines together.

cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

Example:

> ```
> > cargo test
   Compiling alfred v0.3.0 (file:///Users/kevin/Dev/Alfred/alfred-rs)
src/lib.rs:547:1: 547:21src/lib.rs:547:1: 547:21  error: error: The attribute `unsafe_destructor` is currently unknown to the compiler and may have meaning added to it in the futureThe attribute `unsafe_destructor` is currently unknown to the compiler and may have meaning added to it in the future

> src/lib.rs:547 src/lib.rs#[unsafe_destructor]:
547                #[unsafe_destructor]
^~~~~~~~~~~~~~~~~~~~               
src/lib.rs:547:1: 547:21 ^~~~~~~~~~~~~~~~~~~~help: 
add #![feature(custom_attribute)] to the crate attributes to enable
src/lib.rs:547:1: 547:21 help: add #![feature(custom_attribute)] to the crate attributes to enable
error: aborting due to previous error
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `alfred`.

> To learn more, run the command again with --verbose.
```

And here it is with `--verbose`:

> ```
> > cargo test --verbose
   Compiling alfred v0.3.0 (file:///Users/kevin/Dev/Alfred/alfred-rs)
     Running `rustc src/lib.rs --crate-name alfred --crate-type lib -g --out-dir /Users/kevin/Dev/Alfred/alfred-rs/target/debug --emit=dep-info,link -L dependency=/Users/kevin/Dev/Alfred/alfred-rs/target/debug -L dependency=/Users/kevin/Dev/Alfred/alfred-rs/target/debug/deps`
     Running `rustc src/lib.rs --crate-name alfred --crate-type lib -g --test -C metadata=0ff1011de3d9dce6 -C extra-filename=-0ff1011de3d9dce6 --out-dir /Users/kevin/Dev/Alfred/alfred-rs/target/debug --emit=dep-info,link -L dependency=/Users/kevin/Dev/Alfred/alfred-rs/target/debug -L dependency=/Users/kevin/Dev/Alfred/alfred-rs/target/debug/deps`
src/lib.rs:547:1: 547:21src/lib.rs:547:1: 547:21  error: error: The attribute `unsafe_destructor` is currently unknown to the compiler and may have meaning added to it in the futureThe attribute `unsafe_destructor` is currently unknown to the compiler and may have meaning added to it in the future

> src/lib.rssrc/lib.rs::547547  #[unsafe_destructor]#[unsafe_destructor]

>                               ^~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~

> src/lib.rs:547:1: 547:21src/lib.rs:547:1: 547:21  help: help: add #![feature(custom_attribute)] to the crate attributes to enableadd #![feature(custom_attribute)] to the crate attributes to enable

> error: error: aborting due to previous erroraborting due to previous error

> Build failed, waiting for other jobs to finish...
Could not compile `alfred`.

> Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name alfred --crate-type lib -g --out-dir /Users/kevin/Dev/Alfred/alfred-rs/target/debug --emit=dep-info,link -L dependency=/Users/kevin/Dev/Alfred/alfred-rs/target/debug -L dependency=/Users/kevin/Dev/Alfred/alfred-rs/target/debug/deps` (exit code: 101)
```

**Comment by kballard** [comment] 2015-05-02 02:53
This seems like a dupe of #851, although it's very slightly different. #851 says `cargo test` was compiling twice, apparently once for tests and once for doctests. My crate doesn't actually have any regular tests, just doctests, so `cargo test` actually only compiles once if I've previously run `cargo build`. But in this case I had just done a clean, so `cargo test` was actually doing the normal build in parallel with the test build.

I understand why it's compiling twice. The problem isn't compiling twice, it's the mixing of the output and the fact that it ends up printing the errors twice.

A simple workaround would be to buffer all output from the second compilation until the first compilation is complete. If the first compilation fails, it can then discard the results of the second compilation (although it is technically possible for the second compilation to succeed when the first failed if the failure was in code marked as `#[cfg(not(test))]`, but that should be rare, and it could handle that by printing the output from the second one if it actually compiled successfully despite the first compile failing). Basically, make it print output as if it did the `cargo build` and `cargo test` steps in series instead of in parallel (which means don't print the output from `cargo test` as it would not have been run at all in series if `cargo build` failed). Although this doesn't actually handle the case of a package that compiles successfully, but prints warnings during compilation.

A more ideal solution would be to teach `rustc` to have some sort of `-C diagnostics-format=json` flag that makes it emit a stream of JSON objects describing each diagnostic, as opposed to the current human-oriented textual output. `cargo` could then consume the streams of diagnostics from the parallel builds and print them without mixing, as well as detecting when it's getting a duplicate diagnostic and suppressing it.

**Comment by alexcrichton** [comment] 2015-05-04 16:25
Yeah I do agree that this is a dupe of #851 (see https://github.com/rust-lang/cargo/issues/1023 and https://github.com/rust-lang/cargo/issues/1534 as well). Unfortunately, however, capturing the output of the compiler isn't the best course of action as this [has been done and reverted before](https://github.com/rust-lang/cargo/pull/612) as it led to bugs like [losing color](https://github.com/rust-lang/cargo/issues/490) and [not printing warnings](https://github.com/rust-lang/cargo/issues/496). Additionally, holding up diagnostics until the actual compilation is done can often be quite unwieldy (e.g. what if warnings get printed sooner before the optimizer is done running?)

Overall we've had a pretty bad experience capturing output, and I don't think we're ready to go back to that yet (missing solutions for many of the problems). As a result this is unfortunately just a facet of how Cargo works today and likely isn't going to change. I would recommend using `-j1` when this happens to prevent interleaving (or running `cargo build` ahead of time like you mentioned).

As this is working as intended, though, I'm going to close this for now. Thanks regardless for the issue!

**Closed by alexcrichton** 2015-05-04 16:25 UTC

**Comment by kballard** [comment] 2015-05-04 22:06
@alexcrichton Did you have a chance to consider the idea of adding a `-C diagnostics-format=json` flag to `rustc` to allow it to emit diagnostics in a fashion that `cargo` can consume? That would let `cargo` handle the colors directly as well as letting it squelch duplicate errors from the simultaneous invocations.

**Comment by alexcrichton** [comment] 2015-05-05 16:51
@kballard yes but that would require Cargo to have real-time capturing of diagnostics where it parses them all on the fly, and in general it would be quite a complicated solution (and would have to start in the compiler regardless). I suspect that we would want some more motivation before moving forward on that kind of argument to the compiler.

**Comment by kballard** [comment] 2015-05-05 19:19
@alexcrichton The general motivation here is being able to write tooling around `rustc`, such as an IDE. Existing tooling that cares about warnings/errors (such as editor plugins for displaying errors) have to parse out the current ASCII format, which can be error-prone and may not be able to reliably parse out as much information as is desired. Being able to consume a stream of JSON objects would make this sort of thing much easier and more predictable.

For reference, Swift provides a mechanism to emit diagnostics as a stream of JSON objects, and Xcode uses this in order to display the errors in its UI. That's the kind of IDE integration that I'm talking about.

**Comment by alexcrichton** [comment] 2015-05-05 23:04
Sure, but discussion streaming JSON output of the compiler is quickly getting out of the scope of Cargo, so this is not necessarily the best place to discuss it? I certainly don't disagree that it would be useful!
