### ISSUE TITLE
Cargo is unable to work with two included workspaces

### ISSUE THREAD

**Issue by vporton** [rust-lang/cargo#14862] opened 2024-11-27 16:11 UTC
### Problem

Cargo is unable to work with two included workspaces:
```
cargo locate-project' failed: error: multiple workspace roots found in the same workspace:
  /home/porton/Projects/zondirectory/src/ic_eth
  /home/porton/Projects/zondirectory
```

This prevents me to use a Git submodule that contains a workspace. There is no easy workaround, apparently.

### Steps

1. Create a Cargo workspace project.
2. Create another Cargo workspace project in a subdir.
3. Run compilation.

### Possible Solution(s)

Use workspaces in a subdirectory as a part of a parent workspace.

### Version

```text
cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 24.4.0 (noble) [64-bit]
```

**Comment by weihanglo** [comment] 2024-11-27 16:30
This is likely a duplicate of <https://github.com/rust-lang/cargo/issues/5042>. Close in favor of that.

Let us know if there is a reason to keep this open separately.

**Closed by weihanglo** 2024-11-27 16:30 UTC
Labels: C-bug, S-triage
