### ISSUE TITLE
Add new command `cargo why` (as an alias for `cargo tree --invert`)

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang/cargo#12909] opened 2023-11-02 05:45 UTC
### Problem

Sometimes the user wants to find out why a particular package is installed in my dependency tree. `cargo tree --invert` is precisely what they need but it's too obscure to figure out. It's also hard to type.

### Proposed Solution

New command called `cargo why`

**Comment by epage** [comment] 2023-11-02 12:19
Closing as a duplicate of #10006.  if you want us to consider re-opening it, let us know that and why it would be valuable to have this alias vs teaching people of existing commands.

Note: someone is working on #948 and some things we might consider is rendering the relevant trees or telling people of the commands to find more information.

**Closed by epage** 2023-11-02 12:19 UTC
Labels: C-feature-request, S-triage
