### ISSUE TITLE
git could use subdirectory paramiter.

### ISSUE THREAD

**Issue by cheako** [rust-lang/cargo#7153] opened 2019-07-20 07:53 UTC
By example:
```toml
# https://github.com/MaikKlein/ash/tree/master/ash
[patch.crates-io]
ash = { git = 'https://github.com/MaikKlein/ash.git/ash' }
```

```dir = 'ash'``` OR ```subdir = 'ash'```

Should fetch git and then extract/use content from a subfolder.  I also noted that using a URL of a zip or tar file isn't supported, not that this would help here as github won't generate zip downloads for subfolders either.

**Comment by ehuss** [comment] 2019-07-20 19:20
Thanks for the request! This has been brought up a few times before.  I'm going to close this as a duplicate of #6822, which seems to be the most similar.  Perhaps you can leave a comment on that issue detailing *why* you want to narrow the search to a path; what issues it would solve for you.

**Closed by ehuss** 2019-07-20 19:20 UTC
Labels: C-feature-request

**Comment by Kixunil** [comment] 2020-11-16 10:56
I don't think that's a duplicate or at least there's a different use case that I hit just now:

`serde` consists of two libraries: `serde` and `serde_derive`. `serde_derive` is a subdirectory of `serde`, which has a valid `Cargo.toml`. If I want to patch `serde_derive`, I now have to clone it separately and use `path` instead of `git`. This feature would avoid cloning.

**Comment by cheako** [comment] 2020-11-17 03:52
Reason for specifying the path to a file?  You mean cargo has a feature were it'll look at 3 git subfolders that are all at the same depth each with a Cargo.toml and there doesn't need to be an option to specify which is meant to be used?  I think I would rather like to specify what folder to use if for no other reason than to stay well clear of ever trying to run that codepath looking for favorable results.

**Comment by Kixunil** [comment] 2020-11-18 21:54
@cheako I don't understand your comment, could you reword it please?

**Comment by cheako** [comment] 2020-11-20 02:05
Automation is good...  Sometimes.  If the choices are to use automation or blow up, ppl will complain when the automation blows up AND when not using the automation it blows up ppl will also complain.

If ppl don't care about hearing users endlessly complain, then fine don't ever offer an override on git sub-path automatic detection.  If ppl'd prefer silence than it's important to have well documented overrides on every piece of automation.

So yes, having an option to specify what path within a git tree is the path that should be used would seam important...  Even if it's only ever used as a response to issues like this, as an optional feature that would be the point.

**Comment by Kixunil** [comment] 2020-11-21 20:14
Yeah, I agree.

**Comment by ehuss** [comment] 2020-11-23 22:10
> I now have to clone it separately and use `path` instead of `git`. This feature would avoid cloning.

@Kixunil can you clarify why the patch doesn't work for you?  Something like the following should patch just `serde_derive`:

```toml
[patch.crates-io]
serde_derive = { git = "https://github.com/serde-rs/serde.git" }
```

**Comment by Kixunil** [comment] 2020-11-24 12:18
@ehuss sorry, forgot to clarify that I got confused and the appearance of the crate being ignored was caused by something different. But I believe that's also an argument for allowing explicit parameter - less moving parts.
