### ISSUE TITLE
error: failed to fetch `https://github.com/rust-lang/crates.io-index` - `Caused by:   [16/-17] The SSL certificate is invalid`

### ISSUE THREAD

**Issue by gac55** [rust-lang/cargo#3344] opened 2016-11-29 07:37 UTC
I am using a dockerfile to build an environment with Rust. I have been using [this](https://github.com/schickling/dockerfiles/tree/master/rust) as a base. 
Error:
```    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index```

It has previously functioned fine. What has changed to cause this?

Steps to reproduce -

Clone above `repo` and build via `docker build -t "test:latest" /path/to/repo/`

Edit, I added the verbose output and got the following:

`Caused by:
  [16/-17] The SSL certificate is invalid`

**Comment by apanda** [comment] 2016-11-29 07:45
I am seeing the same thing on Debian and on (Travis)[https://travis-ci.com/NetSys/NetBricks#L3392] with Rust nightly toolchain. This is not a problem when either using the nightly build from the 26th (through `rustup default nightly-2016-11-26-x86_64-unknown-linux-gnu`) or when using OS X.

**Comment by apanda** [comment] 2016-11-29 07:48
Seems to have also happened to some of the builds for #3342 [e.g.,](https://travis-ci.org/rust-lang/cargo/jobs/179644339)

**Comment by est31** [comment] 2016-11-29 07:50
Dupe of #3340

**Comment by gac55** [comment] 2016-11-29 07:53
Thanks guys. Trying to understand how to rectify. Can you help me with what action I should take?

**Comment by est31** [comment] 2016-11-29 07:56
As its fixed on master, I'd say you should wait until the next nightly, or alternatively, manually roll back the version on your travis setup. I see from reading the other issue that this workaround might fix it: https://github.com/rust-lang/cargo/issues/598#issuecomment-56089462

**Comment by gac55** [comment] 2016-11-29 08:01
Thanking you. 

Workaround - `ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt`

**Closed** 2016-11-29 08:12 UTC
