### ISSUE TITLE
Install resources files with cargo install

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#3271] opened 2016-11-08 02:39 UTC
`cargo install` already auto-downloads, builds and installs a crate. It would be handy if it could also install resources files, like images, html/js files...

**Comment by alexcrichton** [comment] 2016-11-08 14:59
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2729, but thanks for the report!

**Closed by alexcrichton** 2016-11-08 14:59 UTC

**Comment by Yamakaky** [comment] 2016-11-08 15:02
Sorry, couldn't find something with "resource" in the title ^^
