### ISSUE TITLE
Fetching git repositories via SSH makes cargo crash

### ISSUE THREAD

**Issue by muja** [rust-lang/cargo#2250] opened 2015-12-27 21:27 UTC
How to reproduce:

First, append this in your .gitconfig:
```
  [url "git@github.com:"]
         insteadOf = https://github.com/
```

Then, run any cargo command (install, update, even build) - it will crash with a rather cryptic message of `failed to authenticate when downloading repository`.

**Comment by Jragonmiris** [comment] 2015-12-28 09:05
Probably a duplicate of:

https://github.com/rust-lang/cargo/issues/1851

?

**Comment by alexcrichton** [comment] 2016-01-11 17:42
Yeah I believe this is a dupe of https://github.com/rust-lang/cargo/issues/1851, but thanks for the report!

**Closed by alexcrichton** 2016-01-11 17:42 UTC
