### ISSUE TITLE
Cargo does not update documentation on a minimal example

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/cargo#1447] opened 2015-03-24 14:06 UTC
With Mac nightly from today, just did:

```
$ cargo new test
$ cd test
$ vi src/lib.rs # Then add at the top //! I'm here
$ cargo doc # This produces a doc as desired
$ vi src/lib.rs # Then add at the top  //! Do you see me?
$ cargo doc # This does not update the docs
```

The workaround is to do:
```
$ cargo clean
$ cargo doc
```

**Comment by nwin** [comment] 2015-03-31 09:17
Same problem here(Mac). This might be a wider problem. If I abort `cargo package` with ^c it refuses to do anything afterwards unless I do `cargo clean`.

For the doc problem I somehow suspected #1453 to be the reason…

**Comment by alexcrichton** [comment] 2015-04-10 20:51
Perhaps this was recently fixed?

```
$ rustc -V                     
rustc 1.0.0-nightly (6b95d8bed 2015-04-09) (built 2015-04-10)
$ cargo -V                       
cargo 0.0.1-pre-nightly (471c519 2015-04-08) (built 2015-04-09)
$ cargo new test            
$ cd test                                
$ cargo doc                  
   Compiling test v0.0.1 (file:///home/alex/code/rfcs/wut/test)
$ cargo doc                       
$ touch src/lib.rs            
$ cargo doc                       
   Compiling test v0.0.1 (file:///home/alex/code/rfcs/wut/test)
$ cargo doc               
$                     
```

@huonw does this still reproduce for you as well?

**Comment by huonw** [comment] 2015-04-11 02:07
Hm, it seems to, with the same `cargo` version as you.

```
$ uname -a
Linux huon-laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-1 (2015-01-16) x86_64 GNU/Linux
```

**Comment by alexcrichton** [comment] 2015-04-13 04:23
@huonw to clarify, you ran the same commands and it didn't recompile as it should have?

**Comment by huonw** [comment] 2015-04-13 04:53
Yeah, the behaviour I'm seeing is still the same as #1502.

**Comment by alexcrichton** [comment] 2015-04-14 01:34
Hm, are you testing with a script? Sometimes if a file is modified within the same second of wall time Cargo won't pick up modifications (due to the fs time resolution not being super high).

**Comment by huonw** [comment] 2015-04-14 04:52
No script, I just tried again being careful to leave several seconds delay between all steps and the behaviour is the same as before.

**Comment by luiz-pv9** [comment] 2015-07-04 01:47
I had the same issue with 1.0.0 in Linux Mint 32bit. Just downloaded 1.1.0 and `cargo doc` is working correctly.

**Comment by alexcrichton** [comment] 2015-11-11 20:05
A number of refactorings around freshness and such have happened in the meantime, so I'm going to close this as I unfortunately still can't reproduce, but feel free to reopen if it still happens!

**Closed by alexcrichton** 2015-11-11 20:05 UTC
Labels: C-doc
