### ISSUE TITLE
Cargo Build Fails with Github Deploy Key

### ISSUE THREAD

**Issue by orlandoc01** [rust-lang/cargo#5731] opened 2018-07-16 18:28 UTC
**I tried this**: 
Ran `cargo build --release` with the ssh-agent already running and a dependency listed in `Cargo.toml` that points to a private repo. The ssh-agent had a key added that was a github `deploy key` for this private repo.

**I expected to see this happen**: 
No Error

**Instead, this happened**: 
```
error: failed to load source for a dependency on `privatepkg`

Caused by:
  Unable to update ssh://git@github.com/myorg/private-repo.git

Caused by:
  failed to clone into: /usr/local/cargo/git/db/private-repo-6a628acde2ebe751

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  error authenticating: no auth sock variable; class=Ssh (23)
```

I'm using `cargo 1.27.0 (1e95190e5 2018-05-27)`

**Additional Information**: 
I am running the above commands in a `docker build` process. Because I don't want my ssh keys added into the final docker image and I don't want my github credentials stored in the image as well, I decided to make a `deploy key` with just read access to the `myorg/private-repo` package. Because this deploy key only has read access, there is security threat to checking it into the image and so this should work. When I run `git clone ssh://git@github.com/myorg/private-repo.git` natively in the container, it correctly fetches the repo which means the keys are formed properly and have access. However, when I run `cargo build --release` it fails with the above error message. Moreover, when I instead use my own private github user RSA key for building the image and running the `cargo build --release` command (to aid in debugging the problem), the process succeeds without error. Therefore, this leads me to believe that there must be some problem with authenticating the username of a github deploy key?. When I run `ssh -T git@github.com` with the deploy key I get the following output:

```
Hi myorg/private-repo! You've successfully authenticated, but GitHub does not provide shell access.
```

But when I run the command with my private github user RSA key I get:
```
Hi orlandoc01! You've successfully authenticated, but GitHub does not provide shell access.
```

Not sure if I'm doing something run in the process or if this is a Bug

**Comment by alexcrichton** [comment] 2018-07-16 19:46
Thanks for the report! The final part of the error message:

```
Caused by:
  error authenticating: no auth sock variable; class=Ssh (23)
```

may mean that `ssh-agent` isn't set up or running perhaps? One thing `git` does which Cargo does not do is read `~/.ssh/config`, which has also caused problems in the past. Do you know if there's anything funny with `ssh-agent` though?

**Comment by orlandoc01** [comment] 2018-07-19 22:32
I don't think so. I start the ssh agent in the build process by running `eval \`ssh-agent -s\` `. Moreover, if something was wrong with it, I would expect the command `git clone ssh://git@github.com/myorg/private-repo.git` to not work but it succeeds if I run it as a build command before the `cargo build`. This leads me to believe that its not the ssh-agent but some process in cargo which is the problem

**Comment by sfackler** [comment] 2018-07-19 22:36
The command line `git` is able to directly load the private key without an ssh-agent, unlike the libgit2 library that cargo uses.

**Comment by richardwhiuk** [comment] 2019-08-21 13:17
I'm suspicious that git will try multiple keys, whereas I think Cargo only uses the first one? 🤷‍♂

**Comment by stormdpzh** [comment] 2020-04-26 07:06
try
eval `ssh-agent -s`
ssh-add

**Comment by marcelosousa** [comment] 2020-09-15 09:11
As others pointed out, I believe the issue is that the ssh agent is not actually running at the time you get to the `cargo build` command. I would first double check that with `RUN ps x` in your dockerfile. 

I was having this exact same issue where I was able to run `git clone` but `cargo build` was not working. 

I was able to fix by adding the following to the `.cargo/config`:
```
[net]
git-fetch-with-cli = true
```

I also needed to set `ENV CARGO_HOME=/yourworkdir/.cargo` to the correct .cargo directory - I hope this helps!

**Comment by ehuss** [comment] 2023-04-03 00:49
Since this issue doesn't have a clear reproduction, and it is quite old, I'm going to close this out. It does sound like the ssh-agent isn't running at the point needed. If someone can put together a reproduction that others can try where ssh-agent should be running, feel free to re-open.

**Closed by ehuss** 2023-04-03 00:49 UTC
Labels: A-git
