### ISSUE TITLE
Cargo does not accept prerelease versions as constraints

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#2145] opened 2015-11-14 11:38 UTC
E.g. trying to depend on https://crates.io/crates/arrayfire/3.2.0-rc0 via

```toml
[package]
authors = [""]
name = "test"
version = "0.1.0"

[dependencies]
arrayfire = "3.2.0-rc0"
```

Gives an error:

```
failed to parse manifest at `.../Cargo.toml`

Caused by:
  the given version requirement is invalid
```

(Notably, changing it to `3.2.0` works fine.)

**Comment by alexcrichton** [comment] 2015-11-16 00:23
I think this is a dupe of https://github.com/rust-lang/cargo/issues/952, so closing in favor of that.

cc @steveklabnik, perhaps a new semver could be released?

**Comment by alexcrichton** [comment] 2015-11-16 00:23
I think this is a dupe of https://github.com/rust-lang/cargo/issues/952, so closing in favor of that.

cc @steveklabnik, perhaps a new semver could be released?

**Closed by alexcrichton** 2015-11-16 00:23 UTC

**Comment by steveklabnik** [comment] 2015-11-16 01:39
I'll do a release tomorrow :+1:
