### ISSUE TITLE
Ability to cargo-check mutually exclusive target/feature/other cfgs branches at the same time

### ISSUE THREAD

**Issue by Frederick888** [rust-lang/cargo#8367] opened 2020-06-16 06:44 UTC
**Describe the problem you are trying to solve**

I'm using NeoVim with coc-rust-analyzer. Currently if I've got code branches with mutually exclusive features like:

```rust
#[cfg(feature = "example")]
fn example() -> Result<()> {
    // implementation 1
}

#[cfg(not(feature = "example"))]
fn example() -> Result<()> {
    // implementation 2
}
```

I have to run `cargo check` twice with different `--feature` flags or update coc-rust-analyzer `rust-analyzer.checkOnSave.features` every now and then to see all the errors.

**Describe the solution you'd like**

Show all errors from all branches. This will be really handy for IDE integration.

**Notes**

Related: #4803

**Comment by ehuss** [comment] 2020-07-01 21:21
Thanks for the report!  I'm going to close this as a duplicate of #4803.  There are some workarounds mentioned in that issue (like `cargo hack` which can do different permutations of features).  I don't think rustc will ever be able to handle this natively, and doing permutations of features in cargo seems very expensive, and probably would have some complexity in handling it properly in an editor.  I'm not sure what rust-analyzer has planned for that, but might be worth discussing with them.

**Closed by ehuss** 2020-07-01 21:21 UTC
Labels: C-feature-request
