### ISSUE TITLE
Should bin crates be allowed to depend on yanked crates?

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#4111] opened 2017-05-31 07:55 UTC
If a binary crate wants to publish on crates.io, it seemingly can't depend on yanked crates, even with a `Cargo.lock` checked out in version control.

Is this behavior intended, or would it be a good idea to change it? If `cargo install` does use the `Cargo.lock` of the project, it seems like it would be alright to allow this.

I'm not sure what the specification for "binary crate" should be in `cargo publish`, but I believe that allowing projects to update that currently depend on yanked crates is a good idea - especially if no replacement is yet available/built for the yanked crate.

**Comment by alexcrichton** [comment] 2017-05-31 17:39
Ah I think this is just a dupe of https://github.com/rust-lang/cargo/issues/2263, but thanks for the report!

**Closed by alexcrichton** 2017-05-31 17:39 UTC

**Comment by daboross** [comment] 2017-05-31 17:44
Sounds good! So, this means that if Cargo.lock was included, cargo publish would be allowed with yanked crates?

**Comment by alexcrichton** [comment] 2017-05-31 17:45
Indeed!
