### ISSUE TITLE
Allow specification of dependencies on a per-bin basis

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/cargo#4536] opened 2017-09-25 16:43 UTC
> for example, I want to provide a binary for the "semver" crate, and use clap. but I don't want library users to need clap.

Something like the following (but with correct / easy to recall syntax) would be useful:

```toml
# Cargo.toml

[[bin."binnamehere".dependencies]]
clap = "1.2.3"
```

This would be most useful in codebases with multiple `bin`s that have different dependency requirements.

**Comment by alexcrichton** [comment] 2017-09-25 16:58
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/1982, though, so I'm going to close in favor of that

**Closed by alexcrichton** 2017-09-25 16:58 UTC

**Comment by Phrohdoh** [comment] 2017-09-25 18:15
Thanks Alex, this is indeed a dupe of https://github.com/rust-lang/cargo/issues/1982#issuecomment-288537363.
