### ISSUE TITLE
Progressbar doesn't respond to window resize on macos

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo#5703] opened 2018-07-10 12:16 UTC
Example after shrinking window width

![schermafbeelding 2018-07-10 om 14 19 21](https://user-images.githubusercontent.com/17426603/42509498-628351a4-844c-11e8-8d1c-781644f595ef.png)

**Comment by alexcrichton** [comment] 2018-07-10 13:55
I think this is a duplicate of https://github.com/rust-lang/cargo/issues/4732 but thanks for the report!

**Closed by alexcrichton** 2018-07-10 13:55 UTC
