### ISSUE TITLE
Renaming Validation and Underscores/Hyphens

### ISSUE THREAD

**Issue by cramertj** [rust-lang/cargo#6138] opened 2018-10-05 18:21 UTC
Currently with the "rename-dependency" feature it's possible to have something like `futures-01 = { version = "0.1", optional = true, package = "futures" }`. However, this will cause a `--extern futures-01=...` flag to rustc, which results in an unusable crate name of `futures-01`, rather than the usable `futures_01`. I think there should either be a warning/error on invalid renamings, possibly with an additional conversion of renamed-names from hyphens to underscores (as is normally done with the package name specified in Cargo.toml).

**Comment by ehuss** [comment] 2018-10-05 18:30
I think this is a duplicate of #51795.

**Comment by cramertj** [comment] 2018-10-05 18:36
@ehuss Yup, thanks-- closing as dup of https://github.com/rust-lang/rust/issues/51795

**Comment by cramertj** [comment] 2018-10-05 18:36
Actually-- that issue is filed against rust-lang/rust-- maybe we should keep this one open, since it's actually an issue against cargo?

**Comment by ehuss** [comment] 2018-10-05 18:49
Yea, keeping this open is fine.  I can take a look to see how difficult it would be to fix.

**Closed** 2018-10-05 22:58 UTC
