### ISSUE TITLE
Failed to prepare local package for uploading

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/cargo#1419] opened 2015-03-15 01:32 UTC
I'm currently attempting to update `readline`, but Cargo just tells me `failed to prepare local package for uploading`.

```bash
[18:30:19](readline)$ cargo publish --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging readline v0.0.10 (file:///home/npm/Dropbox/home/Documents/Workspace/Rust/Langs/readline)
   Archiving .gitignore
   Archiving Cargo.toml
   Archiving LICENSE
   Archiving README.md
   Archiving src/common.rs
   Archiving src/lib.rs
   Archiving src/linux.rs
failed to prepare local package for uploading

Caused by:
  No such file or directory (os error 2)
```

**Comment by alexcrichton** [comment] 2015-03-16 13:38
Could I poke around at the source code of the crate as well?

**Comment by GBGamer** [comment] 2015-03-16 14:54
Oh yeah, sorry.
https://github.com/GBGamer/readline-sys

**Comment by alexcrichton** [comment] 2015-03-16 17:43
Does the master branch of that repo return an error for you? On a fresh clone `cargo package` succeeds for me.

**Comment by GBGamer** [comment] 2015-03-16 19:55
Yeah it does, it's the weirdest thing.

**Comment by GBGamer** [comment] 2015-03-16 20:02
Okay, freshly cloning it has fixed the error. I have no idea why that would happen... I am so confused.

**Comment by alexcrichton** [comment] 2015-03-16 20:59
Hm interesting! If it happens again though you may want to try making a tarball or saving the state somehow to see if it can reproduce later.

**Comment by GBGamer** [comment] 2015-03-17 05:59
I definitely will.

**Comment by GBGamer** [comment] 2015-05-04 03:15
@alexcrichton I'm having the issue again.

**Comment by GBGamer** [comment] 2015-05-04 03:26
And it's fixed again... :cry:

**Comment by alexcrichton** [comment] 2015-05-04 16:59
Could you be a little more specific? It sounds like it's broken, then fixed, but this issue is still open?

**Comment by GBGamer** [comment] 2015-05-04 22:11
Yeah, so its happened twice so far; with a new repository, I attempt to cargo package. This fails with the above message. I then go to the upper directory, reclone, and it works in the new directory. Then I go to the other directory, and attempt to package, and it works.

**Comment by alexcrichton** [comment] 2015-05-05 23:13
Do you have any untracked files in the checkout locally when this fails? For example folders, submodules, etc?

**Comment by GBGamer** [comment] 2015-05-05 23:43
Unfortunately, I don't know. My computer just formatted itself :/

**Comment by palango** [comment] 2015-07-28 15:42
Had the same error just now. I had some files added to git, but not yet committed. After the commit everything worked fine. log from the failing attempt is below

```
% cargo package --verbose
   Packaging bencoders v0.1.0 (file:///Users/paul/Projects/rust/bencoders)
   Archiving .gitignore
   Archiving .travis.yml
   Archiving Cargo.toml
   Archiving LICENSE
   Archiving README.md
   Archiving src/lib.rs
   Archiving Cargo.toml
   Archiving src/lib.rs
failed to prepare local package for uploading

Caused by:
  No such file or directory (os error 2)
```

**Comment by alexcrichton** [comment] 2015-11-11 20:03
I believe the error messages here have improved in the meantime, so I'm going to close this (still unable to reproduce)

**Closed by alexcrichton** 2015-11-11 20:03 UTC

**Comment by Storyyeller** [comment] 2016-07-24 16:46
I just ran into this error message

   Packaging cryptominisat v0.1.0 (file:///home/rsg/Rust/cryptominisat-rs)
   Archiving .gitignore
   Archiving .gitmodules
   Archiving Cargo.toml
   Archiving LICENSE
   Archiving build.rs
   Archiving cryptominisat/.gitignore
   Archiving cryptominisat/.gitmodules
   Archiving cryptominisat/.travis.yml
   Archiving cryptominisat/AUTHORS
   Archiving cryptominisat/CMakeLists.txt
   Archiving cryptominisat/LICENSE
   Archiving cryptominisat/README.markdown
   Archiving cryptominisat/appveyor.yml
   Archiving cryptominisat/cmake/AddGTestSuite.cmake
   Archiving cryptominisat/cmake/AddSTPGTest.cmake
   Archiving cryptominisat/cmake/FindM4RI.cmake
   Archiving cryptominisat/cmake/FindMpiCompilers.cmake
   Archiving cryptominisat/cmake/FindMySQL.cmake
   Archiving cryptominisat/cmake/FindPerftools.cmake
   Archiving cryptominisat/cmake/FindPkgMacros.cmake
   Archiving cryptominisat/cmake/FindSqlite3.cmake
   Archiving cryptominisat/cmake/FindTBB.cmake
   Archiving cryptominisat/cmake/FindValgrind.cmake
   Archiving cryptominisat/cmake/GetGitRevisionDescription.cmake
   Archiving cryptominisat/cmake/GetGitRevisionDescription.cmake.in
   Archiving cryptominisat/cmake/cmake_uninstall.cmake.in
   Archiving cryptominisat/cmsat_mysql_setup.sh
   Archiving cryptominisat/cmsat_tablestructure.sql
   Archiving cryptominisat/cryptominisat5Config.cmake.in
   Archiving cryptominisat/debian/changelog
   Archiving cryptominisat/debian/compat
   Archiving cryptominisat/debian/control
   Archiving cryptominisat/debian/rules
   Archiving cryptominisat/debian/source/format
   Archiving cryptominisat/docs/HOWTO-ANALYSIS
   Archiving cryptominisat/docs/HOWTO_WEB
   Archiving cryptominisat/docs/HOWTO_opcontrol
   Archiving cryptominisat/docs/HOWTO_perf
   Archiving cryptominisat/docs/satcomp14-pdf/Makefile
   Archiving cryptominisat/docs/satcomp14-pdf/cmsv4.tex
   Archiving cryptominisat/docs/satcomp14-pdf/ieee.cls
   Archiving cryptominisat/docs/satcomp14-pdf/sigproc.bib
   Archiving cryptominisat/docs/satcomp14-pdf/splncs.bst
   Archiving cryptominisat/docs/satcomp15-pdf/Makefile
   Archiving cryptominisat/docs/satcomp15-pdf/cmsv4.kilepr
   Archiving cryptominisat/docs/satcomp15-pdf/cmsv4.tex
   Archiving cryptominisat/docs/satcomp15-pdf/ieee.cls
   Archiving cryptominisat/docs/satcomp15-pdf/sigproc.bib
   Archiving cryptominisat/docs/satcomp15-pdf/splncs.bst
   Archiving cryptominisat/docs/satcomp16-pdf/Makefile
   Archiving cryptominisat/docs/satcomp16-pdf/cmsv5.kilepr
   Archiving cryptominisat/docs/satcomp16-pdf/cmsv5.tex
   Archiving cryptominisat/docs/satcomp16-pdf/ieee.cls
   Archiving cryptominisat/docs/satcomp16-pdf/sigproc.bib
   Archiving cryptominisat/docs/satcomp16-pdf/splncs.bst
   Archiving cryptominisat/python/CMakeLists.txt
   Archiving cryptominisat/python/LICENSE
   Archiving cryptominisat/python/Makefile
   Archiving cryptominisat/python/README.rst
   Archiving cryptominisat/python/pycryptosat.cpp
   Archiving cryptominisat/python/setup.py.in
   Archiving cryptominisat/python/test_pycryptosat.py
   Archiving cryptominisat/scripts/aws/RequestSpotClient.py
   Archiving cryptominisat/scripts/aws/add_lemma_ind.py
   Archiving cryptominisat/scripts/aws/build_cryptominisat.sh
   Archiving cryptominisat/scripts/aws/build_drat-trim2.sh
   Archiving cryptominisat/scripts/aws/build_lingeling_ayv.sh
   Archiving cryptominisat/scripts/aws/build_swdia5by.sh
   Archiving cryptominisat/scripts/aws/build_swdia5by_old.sh
   Archiving cryptominisat/scripts/aws/client.py
   Archiving cryptominisat/scripts/aws/common_aws.py
   Archiving cryptominisat/scripts/aws/ec2-spot-instance-test.cfg
   Archiving cryptominisat/scripts/aws/ec2-spot-instance.cfg
   Archiving cryptominisat/scripts/aws/launch_server.py
   Archiving cryptominisat/scripts/aws/pre-server.py
   Archiving cryptominisat/scripts/aws/satcomp091113
   Archiving cryptominisat/scripts/aws/satcomp0911131415
   Archiving cryptominisat/scripts/aws/satcomp14
   Archiving cryptominisat/scripts/aws/server.py
   Archiving cryptominisat/scripts/aws/server_option_parser.py
   Archiving cryptominisat/scripts/aws/test_spot_req.py
   Archiving cryptominisat/scripts/docker/Dockerfile
   Archiving cryptominisat/scripts/fuzz/CMakeLists.txt
   Archiving cryptominisat/scripts/fuzz/debuglib.py
   Archiving cryptominisat/scripts/fuzz/fuzz_test.py
   Archiving cryptominisat/scripts/fuzz/intersperse.py
   Archiving cryptominisat/scripts/fuzz/verifier.py
   Archiving cryptominisat/scripts/fuzz/verifier_test.py
error: failed to prepare local package for uploading

Caused by:
  No such file or directory (os error 2)

**Comment by Storyyeller** [comment] 2016-07-24 16:54
I noticed that the next file in the directory after cryptominisat/scripts/fuzz/verifier_test.py is a broken symlink. So that may be the cause.

**Comment by alexcrichton** [comment] 2016-07-25 05:03
@Storyyeller oh dear, that's not good! Cargo could definitely give a better error here at the very least. Could you open a separate bug about that?
