### ISSUE TITLE
Feature request, Get all features with Cargo.toml

### ISSUE THREAD

**Issue by flipchan** [rust-lang/cargo#8676] opened 2020-09-04 15:29 UTC
**Describe the problem you are trying to solve**
So when defining what features you want in Cargo.toml, you define features, example:

```toml
[dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
serde_json = "*"

```

**Describe the solution you'd like**
It would be nice if there would be some enumerate function, that lists all the avaliable functions so that a user 
can request all the features with a syntax like features = ["all"] or features = ["*"]  or something similar

**Notes**
Maybe there already is some kind of feature for this?? if so let me know

Thanks!

**Comment by epage** [comment] 2023-05-17 22:20
If I'm understanding correctly, this looks like a duplicate of #6794.  If I missed something, let us know

**Closed by epage** 2023-05-17 22:20 UTC
Labels: A-features, C-feature-request
