### ISSUE TITLE
Crates used by proc-macro crates can change features enabled in normal crates

### ISSUE THREAD

**Issue by eqrion** [rust-lang/cargo#5304] opened 2018-04-06 05:47 UTC
Context: You need to set `default-features = false` when using `proc-macro2` in a binary or it will crash when running the executable with dylib errors.

Here's a minimal version of the problem I'm running into:

```toml
[package]
name = "example"

[dependencies]
proc-macro2 = { version = "0.3", default-features = false }
example_derive = { path = "../example_derive" }
```

```toml
[package]
name = "example_derive"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "0.3" }
```

When I add a dependency on `example_derive` it force-enables `default-features` for the `proc-macro2` that is linked with the binary, even though the `default-features` are only needed at compile time.

It'd be really nice if there was a way to allow two different `proc-macro2`'s to be in use here, because they have different features and are used at different times.

**Comment by alexcrichton** [comment] 2018-04-06 15:01
Thanks for the report! I think this is a duplicate of https://github.com/rust-lang/cargo/issues/2589 so I'm going to close in favor of that

**Closed by alexcrichton** 2018-04-06 15:01 UTC
