### ISSUE TITLE
Warning for misspelling of cargo directives in build scripts

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/cargo#12353] opened 2023-07-12 20:41 UTC
### Problem

Misspelling of cargo directives in build scripts is a huge footgun. For example:
```Rust
println!("cargo:rerun-if-changed=somefile.cpp");
println!("cargo:rerun-if-chagned=src/main.rs");
```
Here cargo will silently ignore the `src/main.rs` file (the typo is `chagned`) and one would wonder why their build script is not working. It happend in real world to me, in my case it was `rust-link-lib` instead of `rustc-link-lib`.

### Proposed Solution

Cargo should warn against any unknown directive in build scripts. Either it is a misspelling, which a warning is very helpful, or it is a directive that newer cargo versions support, which a warning still has useful information, and if ignoring is the desired behavior, user can allow the warning by #12235

**Comment by epage** [comment] 2023-07-12 21:03
The challenge with this is that there is a [catch-all directive of `cargo:KEY=VALUE`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script), so we don't know for certain there is a typo.

Similarly, because of this catch-all, we can't actually add new directives... (#11461).

However, we have found a way forward as noted in that issue.  We'll make a low-probability breaking change of disallowing `KEY=VALUE`s to start with `:` and then switch the build directive syntax to use `cargo::` as a prefix.  **This will allow unrecognized build directives to be a hard error.**

Work on #11461 was started in #12201 but we were concerned about people using the new syntax on old cargo and ... dropping building directives.  So we are looking to have a 6 month or so transition period where `cargo::` is a hard error and then we will support `cargo::` as the new prefix.

**Comment by HKalbasi** [comment] 2023-07-12 22:23
That's unfortunate. New prefix seems good. Meanwhile I think a crate that provide functions for each directive probably helps. That crate could also check for other footguns, for example warn/error for `rerun-if-chagned` with non existent path.

**Comment by epage** [comment] 2023-07-12 22:27
Yes, there has been some interest in having an official Rust API for build scripts.  Part of the problem is our processes don't scale up for more crates which we have been working on.

**Comment by Mrt3383x38** [comment] 2023-07-20 22:52
Selam acemi adrese korgo

**Comment by weihanglo** [comment] 2023-08-16 11:34
Label this as <https://github.com/rust-lang/cargo/labels/S-accepted>, but it is currently blocked on <https://github.com/rust-lang/cargo/issues/11461>.

#12432 is related somewhat.

**Comment by after-ephemera** [comment] 2024-01-08 13:38
This issue is currently marked as https://github.com/rust-lang/cargo/labels/S-accepted, but it appears that with the ongoing work on #12432 it may end up being irrelevant/part of the larger project? Are we waiting on a finalized API spec before proceeding with detection of unrecognized directives?

**Comment by epage** [comment] 2024-01-08 14:06
imo this warning would be independent of #12432.  The API would help people avoid having typos but not everyone will use it once its available.

Hmm, I'm not too sure what is actually left for this after #11461.  That PR makes it so misspellings are hard errors *but* only if you use the new syntax (`cargo::`).  That just leaves the old syntax (`cargo:`).  We could just do a similarity match and only warn if the similarity match succeeds.  It would be unlikely to be a `metadata` field and it would only be a warning, so no one would be blocked if we were wrong.  However, the further away we are from #11461 being released and more people migrate to it, the less value adding a warning would give.

**Comment by epage** [comment] 2024-12-06 14:41
Between #11461 and [build-rs](https://crates.io/crates/build-rs) being adopted as an official API where people won't need to type out directives anymore, I'm going to close this as resolved.

**Closed by epage** 2024-12-06 14:41 UTC
Labels: E-easy, A-diagnostics, C-feature-request, A-build-scripts, S-accepted
