### ISSUE TITLE
Redundant registry update when adding a dependency to several worksapace members

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3096] opened 2016-09-16 00:03 UTC
I have a workspace with two packages, one of which depends on `regex="*"`. If I add `regex="*"` to the second member as well, I hit a registry update on the next rebuild. It is not necessary, because the existing regex dependency of the workspace will be reused. 

I think the general property we  want is:
* If after an update the lock file contains the subset of the packages before the update, then we have not hit the Internet.

**Comment by matklad** [comment] 2016-09-21 14:16
May or may not be relevant, but [`updated` field](https://github.com/rust-lang/cargo/blob/939922974bc18df2daac055fd1bcb2c2d87d629d/src/cargo/sources/registry/mod.rs#L181) of the `RegistrySource` is never used.

**Comment by alexcrichton** [comment] 2016-09-26 20:37
I think this is a dupe of https://github.com/rust-lang/cargo/issues/2895, so closing in favor of that. Agreed a bug though!

**Closed by alexcrichton** 2016-09-26 20:37 UTC
