### ISSUE TITLE
cargo fails to parse generated manifest at publish time when there are conditional features activated on an ignored dev-dependency

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/cargo#12964] opened 2023-11-12 19:09 UTC
### Problem

In cargo, it is possible to conditionally activate a feature on a dependency based on the main crate features, using the [`crate/feature` syntax](https://doc.rust-lang.org/cargo/reference/features.html):

```toml
[features]
# Enables parallel processing support by enabling the "rayon" feature of jpeg-decoder.
parallel = ["jpeg-decoder/rayon"]
``` 

This works if `jpeg-decoder` is in the main `[dependencies]` section of `Cargo.toml`. However, if `jpeg-decoder` is in the `[dev-dependencies]` section, and it is not included at publish time ([because path dev-dependencies are ignored](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies), for instance), then it fails with the following error:

```
error: failed to verify package tarball

Caused by:
  failed to parse manifest at `.../Cargo.toml`

Caused by:
  feature `parallel` includes `jpeg-decoder/rayon`, but `jpeg-decoder` is not a dependency
```

It looks like cargo auto-generated a faulty Cargo.toml by removing the path dev dependency in the `dev-dependencies` section, but not removing it from the `features` section.

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by epage** [comment] 2023-11-13 15:33
We need to update [prepare_for_publish](https://github.com/rust-lang/cargo/blob/a4764b0dd88f4bf801d5d761ca035d20339bae78/src/cargo/util/toml/mod.rs#L191) to strip these feature activations when stripping dependencies.

**Comment by weihanglo** [comment] 2023-11-15 03:15
Seems like a duplicate of <https://github.com/rust-lang/cargo/issues/12225>? There is an open PR but gets stale.

**Comment by epage** [comment] 2023-11-15 03:25
Closing in favor of #12225.  If there is a mistake and we should keep this open, let us know!

**Closed by epage** 2023-11-15 03:25 UTC
Labels: C-bug, Command-package, S-accepted

**Comment by lovasoa** [comment] 2023-11-15 08:22
Yes, this was indeed a duplicate. Sorry.
