### ISSUE TITLE
Cargo rejects SPDX 3.0 license identifiers

### ISSUE THREAD

**Issue by zgtm** [rust-lang/cargo#5137] opened 2018-03-06 23:01 UTC
The [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html) describes the license field of a Cargo.toml with

> This is a string description of the license for this package. Currently
> crates.io will validate the license provided against a whitelist of known
> license identifiers from http://spdx.org/licenses/. Multiple licenses can be
> separated with a `/`.

http://spdx.org/licenses/ lists GPL3 with the identifiers `GPL-3.0-only` and `GPL-3.0-or-later`. However using the latter one, `cargo publish` gives me the error message:

```
error: api errors: unknown license or other term: GPL-3.0-or-later; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
```

I'm using
```
$ cargo --version
cargo 0.25.0 (8c93e0895 2018-02-01)
```

As someone pointed out to me in the IRC, this might be due to the cargo registry using the crate [license-exprs](https://crates.io/crates/license-exprs), which only parses SPDX v2 identifiers.

**Comment by sfackler** [comment] 2018-03-06 23:04
Duplicate of #4930.

**Comment by carols10cents** [comment] 2018-07-12 02:34
Closing as duplicate of #4930.

**Closed by carols10cents** 2018-07-12 02:34 UTC
