### ISSUE TITLE
"failed to remove `.dSYM`" when cross compiling to 32-bit macOS

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#4699] opened 2017-11-04 16:18 UTC
I don't have a mac to investigate further but I'm seeing this error on Travis ([build log](https://travis-ci.org/japaric/xargo/jobs/297248792)) when cross compiling Xargo to `i686-apple-darwin` on a 64-bit macOS builder. (The travis builder is using Cross to build Xargo but Cross is simply doing `rustup target add i686-apple-darwin && cargo build --target i686-apple-darwin`).

This was working before but I haven't tried to bisect.

Seems related to #4671. cc @kennytm

**Comment by kennytm** [comment] 2017-11-04 16:21
Seems to affect 64-bit as well. https://travis-ci.org/japaric/xargo/jobs/297248793

**Comment by kennytm** [comment] 2017-11-04 16:37
@japaric No repro with a fresh `cargo build`. It is repro only with the following steps:

```sh
$ rm target/debug/xargo.dSYM
$ cp -r target/debug/deps/xargo-0b99a456403c6af1.dSYM/ target/debug/xargo.dSYM
$ cargo build
```

which suggests that probably it is caused by the cache polluted by code before the #4672 landed. The debug log associated with the above was:

```
INFO:cargo::ops::cargo_rustc::job_queue: start: xargo v0.3.9 (file://$DIR/xargo) => Target(bin: xargo)/Profile(build) => Host
DEBUG:cargo::ops::cargo_rustc: linking $DIR/xargo/target/debug/deps/xargo-0b99a456403c6af1 to $DIR/xargo/target/debug/xargo
DEBUG:cargo::ops::cargo_rustc: linking $DIR/xargo/target/debug/deps/xargo-0b99a456403c6af1.dSYM to $DIR/xargo/target/debug/xargo.dSYM
INFO:cargo::ops::cargo_rustc::job_queue: end: xargo v0.3.9 (file://$DIR/xargo) => Target(bin: xargo)/Profile(build) => Host
DEBUG:cargo: exit_with_error; err=CliError { error: Some(CargoError(Msg("failed to remove: $DIR/xargo/target/debug/xargo.dSYM"), State { next_error: Some(Error { repr: Os { code: 1, message: "Operation not permitted" } }), backtrace: None })), unknown: false, exit_code: 101 }
```

This should be fixed once you deleted the cache.

**Comment by kennytm** [comment] 2017-11-04 16:51
This bug itself is a more general problem than #4671. Here's a repro step on Linux:

```
$ cargo new a
$ cd a
$ cargo build
$ rm target/debug/liba.rlib
$ mkdir target/debug/liba.rlib
$ cargo build
```

![screenshot_2017-11-05 00 49 33_ovrrku](https://user-images.githubusercontent.com/103023/32407412-6fef9024-c1c3-11e7-9ea6-468fafc55347.png)

**Comment by japaric** [comment] 2017-11-04 17:17
@kennytm Thanks for looking into this. I'll try clearing the cache. (I think I tried that before before but it probably was before #4672 landed).

**Comment by alexcrichton** [comment] 2017-11-06 15:20
Thanks for investigating @kennytm! Sounds like we should just update the cache removal/cleaning to just handle files as well as directories?

**Comment by kennytm** [comment] 2017-11-07 01:43
@alexcrichton Yes I think so. If failed to remove as file, try to remove as directory recursively (may need to be careful with NTFS junction point though).

**Comment by Luthaf** [comment] 2017-11-20 14:46
This does also happen when compiling directly on OS X with the beta toolchain (see https://www.reddit.com/r/rust/comments/7e8sms/travis_failure_for_rust_beta_on_osx/).

**Comment by KillTheMule** [comment] 2017-11-23 13:28
Beta seems fixed now, but I'm seeing this on stable (travis).

**Comment by alexcrichton** [comment] 2018-03-01 06:16
I think this was fixed in https://github.com/rust-lang/cargo/pull/4672, so closing.

**Closed by alexcrichton** 2018-03-01 06:16 UTC

**Comment by victusfate** [comment] 2019-03-25 10:44
bumped into this but I think it was due to a dropbox restore on a new system, just removed target and reinstalled aok
