### ISSUE TITLE
Random error "failed to fetch `https://github.com/rust-lang/crates.io-index`" on CI runs

### ISSUE THREAD

**Issue by xoxys** [rust-lang/cargo#9187] opened 2021-02-18 22:06 UTC
**Problem**
I get random errors like this during CI runs:

```
      Updating crates.io index
  warning: spurious network error (2 tries remaining): error inflating zlib stream; class=Zlib (5)
  warning: spurious network error (1 tries remaining): error inflating zlib stream; class=Zlib (5)
  error: failed to get `pyo3` as a dependency of package `cryptography-rust v0.1.0 (/tmp/pip-install-7e_k98bl/cryptography_9db4bb72c5224efc97549c8e71dbe2f7/src/rust)`
  
  Caused by:
    failed to fetch `https://github.com/rust-lang/crates.io-index`
  
  Caused by:
    error inflating zlib stream; class=Zlib (5)
```

Restarting the failed pipeline works in most cases and the build finished without issues. Full log:
Failed - https://drone.thegeeklab.de/thegeeklab/git-batch/50/7/2
Worked - https://drone.thegeeklab.de/thegeeklab/git-batch/51/7/2

Any idea where to look or how to fix it? The ARM pipelines are running within arm32v7/python:3.9-alpine containers on AWS EC2 a1.xlarge machines.

Output of `cargo version`: cargo 1.47.0

**Comment by ehuss** [comment] 2021-02-18 23:30
Thanks for the report! This should be fixed in the 1.50 release (#8998).  I'm not too familiar with alpine, or how Rust is built there, so the exact details may differ (like if they are packaging their own libgit2, that would need to be updated).  As a workaround, if you have `git` installed, you can set the [`net.git-fetch-with-cli`](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) option to use the `git` command-line tool instead of the built-in git library.

**Comment by xoxys** [comment] 2021-02-18 23:33
Thanks for your fast reply. I'll try the workaround tomorrow. Not sure how to get the latest rust release easily running on alpine arm as rustup seems to be not working on armv7.

**Comment by ehuss** [comment] 2021-02-22 23:51
Closing as a duplicate of #8517.  Feel free to reopen if it still doesn't work on 1.50 or newer.

**Closed by ehuss** 2021-02-22 23:51 UTC
Labels: C-bug
