### ISSUE TITLE
Unsetting configuration values in deeper configuration files should be possible

### ISSUE THREAD

**Issue by gspr** [rust-lang/cargo#10057] opened 2021-11-07 18:44 UTC
### Problem

The [Cargo configuration documentation](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure) states:

> If a key is specified in multiple config files, the values will get merged together. Numbers, strings, and booleans will use the value in the deeper config directory taking precedence over ancestor directories, where the home directory is the lowest priority. Arrays will be joined together.

This seems to lead to it being impossible to use deeper configuration directories to un-set values for keys that have been set in ancestors, which seems counter to the documented idea that deeper levels should take presedence.

For example, if `~/.cargo/config.toml` has
```
[source.crates-io]
replace-with = "foo"
```
then `~/some-project/.cargo/config.toml` cannot disable source replacement for the `crates-io` source. It could very well change the `replace-with` key's value string to something else than `"foo"`, but that doesn't actually disable source replacement. For that, the key would have to be unset.

### Proposed Solution

If it is indeed desired that deeper configuration files should take presedence (something that seems reasonable), then it should also be possible to unset/undefine keys defined by ancestors. Otherwise this presedence is only partial.

**Comment by ehuss** [comment] 2021-12-06 21:36
I believe this is a duplicate of #8687 and #8112, so closing in favor of those.

**Closed by ehuss** 2021-12-06 21:36 UTC
Labels: C-feature-request
