### ISSUE TITLE
`error: could not remove build directory`

### ISSUE THREAD

**Issue by loynoir** [rust-lang/cargo#12871] opened 2023-10-24 12:42 UTC
### Problem

I use `devcontainer`.

And `/path/to/repo/target` is a mountpoint.

When I run `cargo clean`, cargo try to delete mount point, which leads to `error: could not remove build directory`.

### Steps

```sh
$ mountpoint /path/to/repo/target && cargo clean
/path/to/repo/target is a mountpoint
error: could not remove build directory

Caused by:
  failed to remove directory `/path/to/repo/target`

  Caused by:
      Device or resource busy (os error 16)

  Error: failed to remove directory `/path/to/repo/target`

Caused by:
  Device or resource busy (os error 16)
```

### Possible Solution(s)

Don't try to delete mountpoint.

### Related

I run `cargo clean` because https://github.com/rust-lang/rust-analyzer/issues/15057#issuecomment-1777062345

**Comment by epage** [comment] 2023-10-24 13:16
This looks to be a duplicate of #11887, closing in favor of that.  If there is a distinction between these that I missed, let us know!

**Closed by epage** 2023-10-24 13:16 UTC
Labels: C-bug, Command-clean, S-triage
