### ISSUE TITLE
cargo doc: include all available features in generated docs.

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/cargo#8103] opened 2020-04-14 16:11 UTC
**Describe the problem you are trying to solve**

*Problem:* I can't find the feature-gated API's I need from dependencies by viewing the local `cargo doc` docs. Instead I have to either do online searches or go view `~/.cargo/registry/src/…/<CRATE>-<VERSION>/Cargo.toml` and even then sometimes guess which features are relevant.

**Describe the solution you'd like**

*Minimum Viable Solution:*

When I open the crate-level docs using `cargo doc --open`, I would like it to have a section called "Features" on the top-level page, or linked from the side-bar to the left. That section lists the features that are currently enabled *and* all of the available disabled features, with clear markings for which state each feature is in: enabled or disabled.

*Ideal Solution:*

In addition to the Minimum Viable Solution, the ideal doc improvement would:

1. Include in every module page all APIs gated behind disabled features, where it explicitly says for each one "this fn/struct/enum/trait is only available when the FEATURE is enabled. It is currently disabled." To avoid clutter all disabled APIs could be separated out into the bottom of module doc page in a "disabled features" section, or collapsed by default, or something like that.

2. Provide a page (or section) for every feature that links to every *item* that feature enables. Cross link everything. In the *item* documentation, always explicitly name any features that affect its availability (whether enabled or not) with cross links to the feature page.

**Notes**

Some dependencies, especially large frameworks, gate many APIs behind feature flags. For example I've had this issue with `tokio` and `wasm-bindgen`. It's difficult to discover feature-gated APIs, especially because without explicit doc strings from the author, there's no indication which APIs are feature gated.

Motivation for this feature request based on my work flow; I often have this flow:

1. Add a dependency,
2. `cargo doc --open`,
3. With the docs open in one window, write code in my editor.

Also:

- I make heavy use of the built-in browser search `S` hotkey.
- I often develop offline, such as during flights or commutes or spots with flaky/slow wifi, and can't always do online searches. Also, offline searches of `cargo doc` are always immediately relevant, whereas sometimes google searches include irrelevant results, ads, etc. Finally, offline searches are almost always faster, which helps speed up the study/write/review cycle.

**Comment by nrabulinski** [comment] 2020-07-02 18:17
As a workaround for now to include feature-specific items in docs you can use [doc_cfg](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html) feature.

Example:
```rust
#[cfg(any(feature = "foo", doc))]
#[doc(cfg(feature = "foo"))]
pub mod foo;
```
Will be displayed as:
![image](https://user-images.githubusercontent.com/24574288/86394731-516ad800-bc9f-11ea-9981-d3e464539eab.png)
![image](https://user-images.githubusercontent.com/24574288/86395657-e7533280-bca0-11ea-822c-7f67887a6577.png)

**Comment by spikespaz** [comment] 2022-04-20 03:11
@nrabulinski I'm not understanding how to use this. I am trying to run this:
```
cargo doc --cfg docsrs --all-features
```
Where this is on one of the fields in my struct
```rust
    #[cfg_attr(docsrs, doc(cfg(feature = "unknown-fields")))]
    #[cfg(any(feature = "unknown-fields"))]
    #[serde(flatten)]
    pub other_fields: serde_json::Value,
```

My `Cargo.toml` looks like this:
```toml
...

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

...

[features]
#default = ["unknown-fields"]
unknown-fields = []
```

The output I see is this:
```
❯ cargo doc --cfg docsrs --all-features
error: Found argument '--cfg' which wasn't expected, or isn't valid in this context

        If you tried to supply `--cfg` as a value rather than a flag, use `-- --cfg`

USAGE:
    cargo doc [OPTIONS]

For more information try --help

```

**Comment by epage** [comment] 2022-04-22 19:34
@spikespaz I'd recommend checkout out [argfile](https://github.com/rust-cli/argfile) as its a fairly minimal crate that show cases that feature.

Things to note:
- Your `lib.rs` needs a `#![cfg_attr(docsrs, feature(doc_auto_cfg))]`
- `--cfg docsrs` needs to be passed to rustdoc, not cargo-doc

**Comment by epage** [comment] 2022-04-22 19:35
I believe this issue is a duplicate of https://github.com/rust-lang/rust/issues/96318, so I'm closing in favor of that.  If there is something I missed in that analysis, feel free to speak up!

**Closed by epage** 2022-04-22 19:35 UTC
Labels: A-features, Command-doc, C-feature-request

**Comment by nathan-at-least** [comment] 2023-06-09 20:41
In addition to the `doc_auto_cfg` approach in the discussion above which can be used to provide full item docs with clear feature-gating indicators, I've also just discovered the [document_features](https://docs.rs/document-features/0.2.7/document_features/) crate.

Those two pieces basically fulfill the spirit of my original post with this ticket! Love to see the ecosystem evolving like this.

Now my only desire is that it could all work more seamlessly out of the box, but we'll get there eventually. ;-)
