### ISSUE TITLE
Cargo publish fails with 'Too many open files'

### ISSUE THREAD

**Issue by kureuil** [rust-lang/cargo#4403] opened 2017-08-13 22:57 UTC
While trying to publish a crate to a local instance of crates.io, cargo fails with a 'Too many open files' error while creating its lock file:

```
$ cargo publish --host http://localhost:8888/git/index
    Updating registry `http://localhost:8888/git/index`
warning: spurious network error (2 tries remaining): [2/-1] failed to create locked file '/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack_git2_Xiidx.lock': Too many open files
warning: spurious network error (1 tries remaining): [2/-1] failed to create locked file '/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack_git2_Aoidx.lock': Too many open files
error: failed to update registry http://localhost:8888/git/index

Caused by:
  failed to fetch `http://localhost:8888/git/index`

Caused by:
  [2/-1] failed to create locked file '/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack_git2_PPidx.lock': Too many open files
```

To put things into context, I have approximatively a thousand version of a single crate published in my local registry (maybe not a *legit* use-case per se, but I still think the problem is worth an issue).
By running the program with `strace`, we can see that cargo tries to open every git pack file in the registry:

```
open("/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack-280d79e0d7e028bbd92b132a35b6aa2d5d862c91.pack", O_RDONLY) = 1022
```

One working wordaround is updating the file descriptor limit with `ulimit` to more than 1024.

I'm not familiar enough with cargo to know why it would need to have all these git pack files open at the same time. Is this an expected behaviour of cargo ? Would this happen with 1 published version for 1000 crates ?

Complete `strace -e open,close -f`'d cargo log:
https://gist.github.com/kureuil/989b1f4c6d283384c8b70fdd1ddf2e87

**Comment by alexcrichton** [comment] 2017-08-14 04:17
Oh dear, this is definitely not expected! I'm not really sure what's going on here. Would it be possible to get stack traces of Cargo when it starts opening files it's not closing? I'm curoius what API we're calling in libgit2 that causes this...

**Comment by onur** [comment] 2017-08-14 08:25
This is similar to https://github.com/onur/docs.rs/issues/76. I've temporary solved this problem with running `git gc` on the repository.

**Comment by alexcrichton** [comment] 2017-09-08 16:32
This is probably caused by https://github.com/libgit2/libgit2/issues/2758

**Comment by alexcrichton** [comment] 2017-09-08 16:56
If we want to fix this, which I think we should, I think it'd look something like --

On the "slow path" of doing a git fetch, just before we do that we should check how many pack files are in the repository. Above some threshold we "do a gc" by blowing away the entire index. That means that sporadically an update could take awhile but it never would on the "fast path" and otherwise it'd help keep the repo in a relatively pristine state.

**Comment by alexcrichton** [comment] 2017-09-08 18:13
Further discussion on #libgit2 --

* We should count pack files in `.git/objects/pack/*`
* Before blowing away the repo we should try a `git gc` (the command line tool)
* Failing that, blowing away seems fine

**Closed** 2017-09-14 22:27 UTC
Labels: A-git, C-bug, Command-publish
