### ISSUE TITLE
cargo build --bin bin_name fails due to features conflict in workspace, but cargo build -p bin_crate works

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/cargo#8457] opened 2020-07-06 13:25 UTC
**Problem**

When running
```
cargo build --bin the_bin
```
for some reason we get a compilation error if the package where this binary resides depends on a crate with features different from at least one other package in the same cargo workspace.

**Steps**
```bash
git clone https://github.com/Veetaha/cargo-run-bin-bug-report

# Compile error:
cargo build --bin the_bin

# Successful compilation:
cargo build --package bin_crate
cargo build --package bin_crate --bin the_bin
```

**Notes**
Checked this on `cargo 1.43.0`, `cargo 1.44.0`, `cargo 1.44.1`, all of them have this bug.

**Comment by ehuss** [comment] 2020-07-06 13:31
Thanks for the report! This is a duplicate of #8157, so closing in favor of that.

**Closed by ehuss** 2020-07-06 13:31 UTC
Labels: C-bug
