### ISSUE TITLE
Cargo test: redundant sections are bloating output by default

### ISSUE THREAD

**Issue by ikamensh** [rust-lang/cargo#9072] opened 2021-01-13 20:29 UTC
**Describe the problem you are trying to solve**
By default, cargo test can give bloated output for projects that don't have e.g. Doc-tests or other test groups.

I have a small project and have started writing first tests for it. When running `cargo test`, I get output:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/sorts-6fd673432937221c

running 3 tests
test examine::tests::correct_not_sorted ... ok
test examine::tests::correct_sorted ... ok
test examine::tests::trivial_sorted ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/compare_sorts-06ef0930fe6c2e91

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests sorts

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

The end of the output has two redundant sections that contribute no information and makes it a harder to get an idea at a glance of what has just happened (admittedly this might be less of a problem with experienced users - they know where to look).

**Describe the solution you'd like**
I would like either to have sections with 0 tests hidden completely, or at least reduced to single lines "Doc-tests {}: none found" or similar. Definitely not 0 count for many categories, as I must scan them all to make sure all are zero.

**Notes**
I recognize that this is less of an issue for experienced users that a) use selectors for the test they want to run; b) know where to look in the output. So this benefits beginners more. Streamlining the default behavior should make e.g. live demos easier on the other hand.

**Comment by ehuss** [comment] 2021-01-20 02:45
Thanks for the report!  Closing as a duplicate of #4324 and #2832.

**Closed by ehuss** 2021-01-20 02:45 UTC
Labels: C-feature-request
