### ISSUE TITLE
Cargo metadata includes unused crates

### ISSUE THREAD

**Issue by arlyon** [rust-lang/cargo#10384] opened 2022-02-12 09:04 UTC
### Problem

Hello!

I am working on [arlyon/async-stripe](https://github.com/arlyon/async-stripe) which uses tarpaulin for coverage tracking. I recently introduced the `tracing` crate to clean up the logging story, whose MSRV is `1.49.0` (same at the library). However, the MSRV of a transitive dependency, `valuable`, is `1.51.0` because it uses the new resolver. Now, `valuable` is not actually included in the build (as evidenced by `cargo tree -i valuable`) because it is disabled by default, but `cargo metadata` fails:

```shell
❯ cargo metadata        
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
error: failed to download `valuable v0.1.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/arlyon/.cargo/registry/src/github.com-1ecc6299db9ec823/valuable-0.1.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

My question / bug report is:

- does it make sense to report metadata about crates that are not being built
- if it does, can we support a flag to filter out those we don't want to include?

It feels strange having to bump my MSRV because of an unused optional transitive dependency breaking CI.

### Steps

1. Create a project with rust 1.49.0: `cargo +1.49.0 new metadata-repro`
3. Add `tracing-subscriber` to your project: `cargo +1.49.0 add tracing-subscriber`
5. Run: `cargo metadata`: `cargo +1.49.0 metadata`

### Possible Solution(s)

Assuming omitting the data for unused features is a breaking change, consider providing a flag such that only the dependencies actually used by your program are emitted.

### Version

```text
cargo 1.49.0 (d00d64df9 2020-12-05)
release: 1.49.0
commit-hash: d00d64df9f803bf5bba8714ca498d8f9159d07f6
commit-date: 2020-12-05
```

**Comment by ehuss** [comment] 2022-02-27 21:18
Hm, I'm not quite seeing the issue with tracing.  Can you say which version you have, or more detail on how to reproduce?

```
~/Temp> cargo +1.49.0 new foo
     Created binary (application) `foo` package
~/Temp> cd foo
~/Temp/foo> cargo add tracing
    Updating 'https://github.com/rust-lang/crates.io-index' index
      Adding tracing v0.1.31 to dependencies
~/Temp/foo> cargo +1.49.0 metadata
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
    Updating crates.io index
{"packages":…}
```

I also don't see `valuable` in tracing's dependency tree.

**Comment by arlyon** [comment] 2022-03-01 10:29
Hi! Thanks for taking a look. Sorry, my bad, seems you also need to include the `tracing-subscriber` package. I have updated the repro instructions.

**Comment by ehuss** [comment] 2022-03-01 18:45
Ah, I see.  The issue is that `tracing-core` has `[target."cfg(tracing_unstable)".dependencies.valuable]`.  `cargo metadata` needs to download the package in order to display the package information in the `"packages"` array.  It is normal behavior for `cargo metadata` to include *all* packages that could potentially be used.

This can be avoided by using the `--filter-platform` option to limit which targets are included.  Otherwise, I can't think of a way to avoid this issue.  The only thing I can think of is for cargo to have first-class support for "unstable" features that would avoid the need for using the `cfg(tracing_unstable)` expression.

**Comment by epage** [comment] 2023-10-11 18:24
Looking over this, I'm not seeing any remaining action items (or opportunities to avoid this confusion in the future), so I'm going to close this.  If there is a reason we should re-open it, let us know!

**Closed by epage** 2023-10-11 18:24 UTC
Labels: C-bug, Command-metadata
