### ISSUE TITLE
Cargo burns 100% processor forever while updating registry

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/cargo#2447] opened 2016-03-08 03:20 UTC
I've only been able to reproduce this bug on a single Cargo.toml file.  

Simply make a new directory, put this file in it, and run `cargo update`

**Cargo.toml**

```toml
[package]
name = "trident"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[[bin]]
name = "gui"
path = "./src/gui.rs"


[dependencies]
lux = "0.0.4"
```

Commenting out the dependency on Lux fixes it.  As does replacing the Lux dependency a newer version (0.1.0).

**Comment by srinivasreddy** [comment] 2016-03-08 14:10
can you please paste Cargo.lock file as well?

**Comment by alexcrichton** [comment] 2016-03-08 16:04
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2090 which has a number of linked reports at the end for counts of this.

**Comment by TyOverby** [comment] 2016-03-08 17:13
@alexcrichton Yep, looks like it's a dup.

**Closed** 2016-03-08 22:32 UTC
