### ISSUE TITLE
[git] ~ in init.templatedir

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#1140] opened 2015-01-09 18:36 UTC
Hi

In my git config file, `init.templatedir` is set to `~/.config/git/template`. When I launch `cargo new -v test`, it fails saying that `~/.config/git/template` doesn't exist. When I replace `~` by `/home/<user>`, the command successes.

It seems that cargo doesn't expand ~.

**Comment by alexcrichton** [comment] 2015-01-09 23:22
Looks like this is a bug in libgit2 right now, I've opened a bug with them: https://github.com/libgit2/libgit2/issues/2814

**Comment by Yamakaky** [comment] 2015-01-10 09:07
Cool, thanks !

**Comment by alexcrichton** [comment] 2015-03-24 00:50
I believe this was fixed in a recent libgit2 update, but please reopen if it still happens!

**Comment by Yamakaky** [comment] 2015-03-24 15:51
No, the problem is still there with 2015-03-24...

**Comment by alexcrichton** [comment] 2015-03-24 15:54
Ah well.

**Comment by alexcrichton** [comment] 2015-05-18 23:10
Oh right this was a time when cargo nightlies weren't getting built, I just checked again and confirmed that this is fixed, yay!

**Closed by alexcrichton** 2015-05-18 23:10 UTC
Labels: A-git
