### ISSUE TITLE
Updating registry fails with "Object not found - no match for id"

### ISSUE THREAD

**Issue by hawkw** [rust-lang/cargo#3561] opened 2017-01-18 22:01 UTC
Running `cargo update` or `cargo build` fails with
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `log`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [9/-3] Object not found - no match for id (5dcd4b130384bb9d2123dd1af8d0edbca4b04acb)                                
```

The name of the dependency and the hash differ depending on the project the command was run for. 

Issue persists after deleting `~/.cargo/registry` and `~/.cargo/git`. However, completely uninstalling and then reinstalling the nightly toolchain with `rustup` temporarily fixes this issue.

I'm using cargo 0.17.0-nightly (a43403b 2017-01-17) on macOS 10.11.6 (15G1108).

**Comment by alexcrichton** [comment] 2017-01-18 23:02
Whoa weird! Can't say I've ever seen this error before... Do you have a way to reproduce this deterministically? If so, could you gist `RUST_LOG=trace` to see if there's any other output that'll show up? (it may not end up being too helpful)

**Comment by hawkw** [comment] 2017-01-19 00:10
@alexcrichton: Sure, [here you go](https://gist.github.com/hawkw/05224cca14f4efb4385e2ca98b8e4a7b)!

Some more information that might be useful:

- It appears that one specific cargo project is effected by this issue, which only happens when a new dependency has been added to `Cargo.toml`.
- Once I try to build this project, any time I attempt to build any Cargo project fails with this error.
- Restarting my machine seems to fix this until I try to build the effected project again.
- The effected project is being built using [Xargo](https://github.com/japaric/xargo), which I suspect might have something to do with this issue?

**Comment by alexcrichton** [comment] 2017-01-19 17:30
@hawkw thanks for the extra logs! I think this is happening whenever Cargo tries to update the registry, which it typically doesn't do unless you change `Cargo.toml` and need fresh information.

My *guess* is that this is just a corrupt git repo (which Cargo should certainly handle, of course), but the fact that you blew it away and it *still* didn't work is quite fishy.

@hawkw out of curiosity, would you be able to build a debug version of Cargo to perhaps get some more output? I could send you a commit with extra logging statements which may help in debugging this.

@japaric xargo doesn't change the location of the Cargo registry (e.g. via `CARGO_HOME`), does it?

**Comment by hawkw** [comment] 2017-01-19 17:55
@alexcrichton sure, I'd be happy to! Send it my way?

**Comment by japaric** [comment] 2017-01-19 18:38
@alexcrichton no context: No, Cargo doesn't touch CARGO_HOME. (cross does though, if that matters at all)

**Comment by alexcrichton** [comment] 2017-01-19 18:56
@hawkw ok awesome, thanks! Could you try building [this tree of Cargo](https://github.com/alexcrichton/cargo/tree/debug) and then using that Cargo to run `cargo build`?

@japaric thanks for the info! That's all I was wondering :)

**Comment by hawkw** [comment] 2017-01-19 19:08
@alexcrichton of course! should I build the debug or release executable?

**Comment by alexcrichton** [comment] 2017-01-19 19:10
Either should be fine, but I'd go with debug b/c it builds faster :)

**Comment by hawkw** [comment] 2017-01-19 19:23
@alexcrichton here's the output: https://gist.github.com/hawkw/05224cca14f4efb4385e2ca98b8e4a7b#file-with-extra-debug-statements

**Comment by alexcrichton** [comment] 2017-01-19 19:29
Ok now that's super fishy. So the error is happening inside libgit2 during the fetch operation. If you blow away `/Users/eliza/.cargo/registry/index/github.com-1ecc6299db9ec823/` though the problem persists?

**Comment by hawkw** [comment] 2017-01-19 20:48
After deleting the registry again, the issue appears to be fixed. Which is strange, since I'm about 90% sure that the first time I wiped `~/.cargo/registry`, the error persisted. I could be wrong though – sorry if I gave you incorrect information!

**Comment by alexcrichton** [comment] 2017-01-19 20:55
Hm ok, in that case I think we can probably chalk it up to a corrupted git repository. In that case this should probably be handled by Cargo gracefully with an attempt to re-clone the entire registry.

**Comment by pravic** [comment] 2017-03-09 08:40
This happened again today (cargo search something):


>    Updating registry `https://github.com/rust-lang/crates.io-index`
> DEBUG:cargo::sources::registry::remote: attempting github fast path for https://github.com/rust-lang/crates.io-index
> DEBUG:cargo::sources::registry::remote: fast path failed, falling back to a git fetch
> DEBUG:cargo: exit_with_error; err=CliError { error: Some(ChainedError { error: failed to update registry https://github.com/rust-lang/crates.io-index, cause: ChainedError { error: failed to fetch `https://github.com/rust-lang/crates.io-index`, cause: Error { code: -3, klass: 9, message: "object not found - no match for id (99b4e2e3cf7cb587d4b3eabcc25ff82cac00760b)" } } }), unknown: false, exit_code: 101 }
error: failed to update registry https://github.com/rust-lang/crates.io-index

> Caused by:
>   failed to fetch `https://github.com/rust-lang/crates.io-index`

> Caused by:
>   [9/-3] object not found - no match for id (99b4e2e3cf7cb587d4b3eabcc25ff82cac00760b)
```

**Comment by pravic** [comment] 2017-03-11 05:49
Looks like remiving local registry fixes this issue, despite of error message which points to fetch error.

**Comment by koivunej** [comment] 2017-04-11 23:57
I just ran into this. As the dependency is one of my own, I think a force push might have caused this? Or the fact that I was previously using this dependency as a path dependency, like `eventstore-tcp = { path = "../eventstore-tcp" }`?

Removing `~/.cargo/registry` did not fix the issue. Removing repo related directories from `~/.cargo/git` don't seem to help either.

I wonder where is the id reference stored? Strange that I'm unable to force the revision even by specifying it as `rev = "..."` with the dependency.

**Comment by alexcrichton** [comment] 2017-04-12 14:04
@koivunej oh interesting! If the fact that it was a submodule relevant here wasn't surfaced in the error message, that definitely sounds like something we should fix! Do you have an example error message you were seeing?

**Comment by koivunej** [comment] 2017-04-13 09:34
@alexcrichton please see: https://gist.github.com/koivunej/a24d06c40b5913f18c6d4c8cf67495ae ... Looking back, this looks like PEBKAC error on my part:
 1. I did not understand that `failed to update submodules` on verbose was from git -- I was thinking that it's cargos message "failing to update eventstore-tcp" just repeated
 2. I found this bug by googling and assumed there's a bug in play, wasted time clearing caches before thinking this through

Perhaps if anything, the `caused by" could be as follows:

```
-  failed to update submodules
+  git: failed to update submodules
```

Of course troubleshooting something like this on someone elses crate would be even more confusing. Hopefully nobody is using my crate at this point in time :)

**Comment by alexcrichton** [comment] 2017-04-13 16:21
Ah yeah that error *definitely* shouldn't get hidden behind `--verbose` by default, and we should also mention the submodule in question most likely.

@koivunej would you be interested in making a PR for improving this? I could help you walk through Cargo internals if you'd like.

**Comment by thibaultdelor** [comment] 2018-03-04 10:05
I had the same error today.
Stupidly I didn't saved anything and just removed .cargo and .rust and then went for the reinstall which fixed it.
Next time it happens I'll archive everything and investigate further...

**Comment by alexcrichton** [comment] 2018-03-04 19:49
Ah actually I think this was fixed in https://github.com/rust-lang/cargo/pull/5110, so I'm going to close this now that that's merged.

**Closed by alexcrichton** 2018-03-04 19:49 UTC
Labels: A-errors, A-git, C-bug
