### ISSUE TITLE
--nocapture only works when passed to the test runner itself

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/cargo#1613] opened 2015-05-15 10:55 UTC
`cargo test -- --nocapture` works, but `cargo test --nocapture` doesn't.

What about adding a pass-through option so that cargo would add that argument for us?

**Comment by alexcrichton** [comment] 2015-05-15 18:29
Thanks for the report! This is currently intentional, however, as we want to be able to support other testing frameworks for Cargo and Rust code eventually. We don't currently recognize any special options of the test runner itself nor the compiler, and we're likely going to keep it that way for the time being. As a result, I'm going to close this as working as intended.

**Closed by alexcrichton** 2015-05-15 18:29 UTC
