### ISSUE TITLE
Adding an `update` subcommand to `install` to update locally installed binaries 

### ISSUE THREAD

**Issue by cocool97** [rust-lang/cargo#10190] opened 2021-12-10 21:05 UTC
### Problem

It is currently a bit of a mess to update local installed binaries. We have to re-install all of them to get to the point.

The goal of the `install` subcommand would be only to install new packages (and throw an error if the package is already installed), and the `update` subcommand could update locally installed packages.

### Proposed Solution

It could be a good idea to add an `update` subcommand to `install` to allow people to update one, more or all locally installed binaries.

**Comment by Eh2406** [comment] 2021-12-10 22:58
> If the package is already installed, Cargo will reinstall it if the installed version does not appear to be up-to-date. If any of the following values change, then Cargo will reinstall the package:

https://doc.rust-lang.org/cargo/commands/cargo-install.html

Also `cargo update` is an existing command that is entirely unrelated.

**Comment by ehuss** [comment] 2021-12-13 18:09
Yea, `cargo install` already updates packages if they are out of date.  Updating all out-of-date packages is tracked in other issues like #9527, so closing as a duplicate of that.

**Closed by ehuss** 2021-12-13 18:09 UTC
Labels: C-feature-request
