### ISSUE TITLE
cannot install cargo-c

### ISSUE THREAD

**Issue by journeym** [rust-lang/cargo#14117] opened 2024-06-20 19:07 UTC
### Problem

cargo install cargo-c
    Updating crates.io index
error: cannot install package `cargo-c 0.10.0+cargo-0.80.0`, it requires rustc 1.76 or newer, while the currently active rustc version is 1.75.0
`cargo-c 0.9.31+cargo-0.78.0` supports rustc 1.75

### Steps

Latest ubuntu
Install cargo
cargo install cargo-c

### Possible Solution(s)

-

### Version

```text
cargo 1.75.0
```

**Comment by weihanglo** [comment] 2024-06-20 19:14
> error: cannot install package cargo-c 0.10.0+cargo-0.80.0, it requires rustc 1.76 or newer, while the currently active rustc version is 1.75.0

The latest version of cargo-c requires the 1.76.0 toolchain. The version supports 1.75.0 is <https://crates.io/crates/cargo-c/0.9.31+cargo-0.78.0>. You should either upgrade your rust tooolchain or consult with maintainers of <https://github.com/lu-zero/cargo-c>. This is expected behavior not a bug in Cargo, so going to close this.

**Closed by weihanglo** 2024-06-20 19:14 UTC
Labels: C-bug, S-triage

**Comment by journeym** [comment] 2024-06-21 08:07
I dont get it. Under ubuntu im unable install cargo w/o the old version of rust, and when im doing apt remove rustc, it also removes cargo.
This needs to be dealt with somehow.

**Comment by weihanglo** [comment] 2024-06-21 11:12
@journeym 
The recommended way is via rustup
https://www.rust-lang.org/tools/install
