### ISSUE TITLE
Confusing import errors for `build.rs` script

### ISSUE THREAD

**Issue by kraktus** [rust-lang/cargo#11598] opened 2023-01-19 13:39 UTC
### Code

```toml
# Cargo.toml
build = "src/build.rs"
```

```rust
// src/build.rs
mod foo;

use crate::foo::Foo;

fn main() -> std::io::Result<()> {
	Foo;
	Ok(())
}
```

```rust
// src/foo.rs
use crate::Lib;

pub struct Foo;
```

```rust
// src/lib.rs
pub mod foo;

pub use foo::Foo;

pub enum Lib {
    A,
    B,
}

fn main() {
    println!("Hello, world!");
}
```

### Current output

```Shell
error[E0432]: unresolved import `crate::Lib`
 --> src/foo.rs:1:5
  |
1 | use crate::Lib;
  |     ^^^^^^^^^^ no `Lib` in the root

For more information about this error, try `rustc --explain E0432`.
```

### Desired output

```diff
I am not sure, but at least should say the error comes from the build script

+ When compiling the build script `src/build.rs`
error[E0432]: unresolved import `crate::Lib`
 --> src/foo.rs:1:5
  |
1 | use crate::Lib;
  |     ^^^^^^^^^^ no `Lib` in the root

For more information about this error, try `rustc --explain E0432`.
+ Help: you may want to declare that module in the build script
```

### Rationale and extra context

This error got me puzzled for a while before I had the thought to look at the build script.

**Comment by weihanglo** [comment] 2023-01-20 18:05
AFAIK a build script is expected to be built before its package being built[^1]. I usually debug with `cargo build --verbose` so that I can clearly see it's a crate named `build_script_build`, which compiles `src/build.rs`, that failed.

```console
   Compiling issue-11598 v0.1.0 (/home/user/projects/issue-11598)
     Running `rustc --crate-name build_script_build --edition=2021 src/build.rs ...`
error[E0432]: unresolved import `crate::Lib`
 --> src/foo.rs:2:5
  |
2 | use crate::Lib;
  |     ^^^^^^^^^^ no `Lib` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `issue-11598` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build --edition=2021 src/build.rs ...` (exit status: 1)
```

I don't really have a good idea at hand. We could possibly denote which kind of target is failing. Cargo warnings already got that logic [here](https://github.com/rust-lang/cargo/blob/985d561f0bb9b76ec043a2b12511790ec7a2b954/src/cargo/core/compiler/job_queue.rs#L1265-L1273). Could possiblly reuse it a bit with a refined message like:

```patch 
   Compiling issue-11598 v0.1.0 (/home/user/projects/issue-11598)
error[E0432]: unresolved import `crate::Lib`
 --> src/foo.rs:2:5
  |
2 | use crate::Lib;
  |     ^^^^^^^^^^ no `Lib` in the root

For more information about this error, try `rustc --explain E0432`.
+ error: could not compile `issue-11598` (build-script) due to previous error
```

[^1]: (https://doc.rust-lang.org/cargo/reference/build-scripts.html#life-cycle-of-a-build-script

**Comment by ehuss** [comment] 2023-01-20 18:27
I think this is essentially the same as #10834, so closing as a duplicate of that.

**Closed by ehuss** 2023-01-20 18:27 UTC
Labels: C-bug, A-errors, A-build-scripts
