### ISSUE TITLE
Cargo complains about missing cert when none is required

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/cargo#6642] opened 2019-02-07 20:30 UTC
**Problem**
I am currently on a Windows 10 computer on a corporate network. We are running an internal BitBucket. A repository on this BitBucket is set to have global read permissions. It is possible to clone this repository at the command line without any client certificate simply using `git clone` with the appropriate https URL. Adding this URL as the `git` field in a dependency entry in `Cargo.toml` of a downstream project results in a bug (some things omitted and replaced with `<...>`:

```
$ cargo test
    Updating git repository `https://<...>.git`
warning: spurious network error (2 tries remaining): failed to send request: A certificate is required to complete client authentication
; class=Os (2)
warning: spurious network error (1 tries remaining): failed to send request: A certificate is required to complete client authentication
; class=Os (2)
error: failed to load source for a dependency on `<...>`

Caused by:
  Unable to update https://<...>.git

Caused by:
  failed to fetch into <...>

Caused by:
  failed to send request: A certificate is required to complete client authentication
; class=Os (2)
```

**This does not happen on Ubuntu 18.04.**

On Ubuntu the exact same thing works as expected on a system without a client side cert and without entering any credentials (password or having an ssh key attached to the BitBucket). It works globally on Ubuntu 10.04 systems, but not Windows 10. I have not yet tried this on other versions of Windows or Linux.

**Steps**

1. Create a BitBucket instance (using v5.15.1) (custom configuration could also come into play)
2. Create a Rust library (**A**) in a repository on the instance.
3. Create a new Rust project (**B**)
4. Set **A** as a dependency in the Cargo.toml of **B** and set the upstream `git` to be the https URL of **A**'s repository.
5. Run any Cargo command that fetches source on a Windows 10 machine.

**Notes**

Output of `cargo version`:
It fails on the nightly I was on.
```
$ cargo --version
cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)
```

It also fails on the nightly I just upgraded to.
```
$ cargo --version
cargo 1.34.0-nightly (4e74e2fc0 2019-02-02)
```

It works fine on Ubuntu on at least 2 versions of nightly throughout the last few months and continues to work on the latest nightly (the same one as just above).

**Comment by vadixidav** [comment] 2019-02-07 21:09
I also disabled my firewall and checked that it didn't affect this. It still works from the command line, but not when Cargo does it.

**Comment by vadixidav** [comment] 2019-02-07 21:58
It works fine with the public BitBucket at bitbucket.org.

**Comment by alexcrichton** [comment] 2019-02-11 13:53
This seems like it's likely a difference in SSL libraries used by Cargo? Cargo uses schannel on Windows which may behave differently for this custom server than OpenSSL on Linux. Do you know of other Windows clients that work for your server? We may just need to set an option for schannel or something like that

**Comment by vadixidav** [comment] 2019-02-11 15:04
I can say that normal git commands work as expected on Windows. Are there any other tools using schannel that I can investigate with?

**Comment by alexcrichton** [comment] 2019-02-11 16:24
Does curl work? 

TBH this isn't something we're going to easily or magically fix. I at least wouldn't know where to start to reproduce this, and a solution will likely require digging around some code somewhere. I can try to provide helpful directions of where to investigate, but beyond that this will require some other volunteer to investigate.

You may be able to learn a bit more information with Cargo's HTTP debugging (the [`http.debug` key](https://doc.rust-lang.org/cargo/reference/config.html)) as well, but that's just a guess

**Comment by vadixidav** [comment] 2019-02-11 21:01
If you think this will require that level of attention, I can probably do some debugging myself. When I get a chance I will try out the logging and attempt to debug it as well.

**Comment by vadixidav** [comment] 2020-01-10 18:28
It has been a while since this issue happened, but we worked around it with git submodules. It has come up again, and I will start investigating the issue today.

**Comment by eminence** [comment] 2022-11-24 04:19
Hi @vadixidav -- I know it's been many years since you opened this issue, but are you still having problems?  Unfortunately this issue sounds like it could be triggered by something specific to your internal BitBucket instance, which means it will be hard to make progress without help.

If you are still having issues, I'm curious if the [fetch-with-cli](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) setting does anything for you?

If you've resolved or worked around the issues, let us know if you think we can close this.

**Comment by vadixidav** [comment] 2022-11-25 15:04
I don't have access to the BitBucket anymore. It is possible that this issue has been fixed by now, but I cannot test it anymore. We can close this since nobody else is currently reporting the issue.

**Closed** 2022-11-25 18:33 UTC
Labels: C-bug, A-networking
