### ISSUE TITLE
Running cargo twice in the same time should fail.

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#2030] opened 2015-10-06 23:50 UTC
Hi,

Currently if one runs cargo twice in the same time, the two instance will collide with how they use temporary files etc. . Eg.:

```
error: failed to remove /home/user/rust/test1/target/debug/test.0.bc: No such file or directory (os error 2)
```

It would be much better if unique, temporary directories would be used for intermediate files, and atomic operations would place the final files into the right place. Doesn't mater which instance "wins", as long as they don't collide.

**Comment by alexcrichton** [comment] 2015-10-06 23:59
Thanks for the report! This is a duplicate of https://github.com/rust-lang/cargo/issues/354, though, so I'm going to close in favor of that.

**Closed by alexcrichton** 2015-10-06 23:59 UTC
