### ISSUE TITLE
Don't pass `--features` from `dev-dependencies` to `dependencies`

### ISSUE THREAD

**Issue by valarauca** [rust-lang/cargo#4664] opened 2017-10-27 00:58 UTC
Working on a smallish project. 

The main reason this came up was `nom`. Which has a feature flag that gates its new errors [linky](http://rust.unhandledexpression.com/src/nom/internal.rs.html#96-99). If I include a dependency my whole build breaks as a `dev-dependency` is building nom with verbose errors.

**Comment by roblabla** [comment] 2017-11-10 18:11
I have a similar issue, but with `build-dependencies` to `dependencies`, with `bindgen` as a build-dependency and `libc` as a dependency in a nostd project.

Basically, `bindgen` depends (eventually) on libc with std support. I'm building libc with nostd (my project is meant to be ran on a custom target with no std support), but it fails, saying it cannot find the crate std. If we turn on the verbosity of cargo, we can clearly see the use_std feature being passed to libc. Here's what I have : https://gist.github.com/anonymous/a42cc000486d5551d3849f3517d4b3a7

**Comment by radix** [comment] 2017-12-29 20:18
I have this problem too, working with serde in project with optional std support: https://github.com/radix/uom/blob/serde/Cargo.toml

If I'm building this uom branch with `cargo build --features f32,serde --no-default-features`, it still builds serde with `std` support. This is because the `serde_json` dependency in `dev-dependencies` depends on `serde` with default features. This is strange, because serde_json isn't even being built!

Shouldn't this be a bug instead of a feature-request?

**Comment by radix** [comment] 2017-12-29 20:22
btw this seems related to, or maybe the same as #4361

**Comment by roblabla** [comment] 2017-12-29 20:26
it's related yeah. 4361 is about build-deps, we're about dev-deps, but a fix for one should probably fix the other.

**Comment by Eh2406** [comment] 2018-03-26 15:50
This appears to be related to https://github.com/rust-lang/cargo/issues/2589

**Comment by mbrubeck** [comment] 2018-08-23 16:39
Also duplicated by #4866.

**Comment by tarcieri** [comment] 2019-01-27 00:59
#2589 and #4866 appear to be the same to me. Of these three, I prefer the write up in #4866

**Comment by dwijnand** [comment] 2019-02-11 18:21
Duplicate of #4866

**Comment by Nemo157** [comment] 2019-02-12 10:20
#4866 is referring to `build-dependencies` in its OP, despite the title saying `dev-dependencies`. #2589 and #4866 are duplicates about `build-dependencies` features affecting `dependencies` always, while this is in relation to features from `dev-dependencies` affecting `cargo build` in a crate (or also when included as a `path` dependency of another crate when in a workspace). It's a bit different in that `dev-dependencies` _should_ affect (public) `dependencies` features when running `cargo test`, as the dependency used in the tests needs to match the dependency used in the build.

**Comment by ehuss** [comment] 2020-02-24 15:32
Non-unification of dev-dependency features has been implemented and is available as a nightly-only feature on the latest nightly 2020-02-23. See the tracking issue at #7916.

If people following this issue could try it out, and leave your feedback on the tracking issue (#7916), I would appreciate it. Particularly we'd like to know if it helps your project, does it cause any breakage, and is it a problem that binaries are still unified with `cargo test`?

**Closed by ehuss** 2020-02-24 15:32 UTC
Labels: A-features, C-feature-request
