### ISSUE TITLE
default features always resolved for dependency in workspace mode

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/cargo#10636] opened 2022-05-06 16:26 UTC
### Problem

If a workspace contains three crates `a`, `b`, `c`, where `a` and `b` both depend on `c`, and `c` has a default feature `cf`, `cf` is _always_ enabled when building in workspace mode even if one or both of `a` and `b` have default features disabled.

This happens on the resolver v1 or v2.

This is a problem because in workspaces it is common to build and run tests for the entire workspace, especially in build/CI environments. Incompatibilities and bugs arise that are not caught when workspace mode is used.

### Steps

A full reproduction of the issue is here: https://github.com/leighmcculloch/rustlang--cargo--issue-10636

For a workspace with three crates `a`, `b`, and `c` where `a` and `b` are dependent on `c`. `a` depends on `c` with default-features disabled. `b` depends on `c` with default-features enabled. `c` has one default feature, `std`.

![README-diagram-1 excalidraw](https://user-images.githubusercontent.com/351529/167173966-f06d43fa-190e-4ffc-865d-981cf158f5ac.png)

`c` contains some invalid code when built without its `std` feature. `c` contains this invalid code. The code is invalid because when the `std` feature is disabled, the `no_std` attribute is enabled and the `String` type is unknown.

```rust
#![cfg_attr(not(feature = "std"), no_std)]

pub type CS = String;
```

When building the workspace which builds all crates, all tests pass because the default features are enabled, enabling the `std` feature, even for the `a` crate that has `std` disabled. To try this out, run this command:

```
$ cargo build --all
   Compiling c v0.1.0 (/Users/dev/workspace/c)
   Compiling b v0.1.0 (/Users/dev/workspace/b)
   Compiling a v0.1.0 (/Users/dev/workspace/a)
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
```

When building individual crates, crate `a` fails to compile and crate `c` fails to compile when explicitly told to build without the `std` feature.

```
$ cargo build -p c
    Checking c v0.1.0 (/Users/dev/workspace/c)
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

```
$ cargo build -p c --no-default-features
   Compiling c v0.1.0 (/Users/dev/workspace/c)
error[E0412]: cannot find type `String` in this scope
 --> c/src/lib.rs:3:15
  |
3 | pub type CS = String;
  |               ^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `c` due to previous error

```

```
$ cargo build -p a
   Compiling c v0.1.0 (/Users/dev/workspace/c)
error[E0412]: cannot find type `String` in this scope
 --> c/src/lib.rs:3:15
  |
3 | pub type CS = String;
  |               ^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `c` due to previous error
```

```
$ cargo build -p b
    Checking c v0.1.0 (/Users/dev/workspace/c)
    Checking b v0.1.0 (/Users/dev/workspace/b)
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

### Possible Solution(s)

When building each crate in a workspace its feature selection should be identical to when building the crate in isolation.

### Version

```text
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: aarch64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/3.3.5)
os: Mac OS 12.3.1 [64-bit]
```

**Comment by ehuss** [comment] 2022-05-06 18:22
Thanks for the very detailed report!  This is a known issue tracked in #4463.  For now you'll need to build/test each package individually if you want to build them with different features in shared dependencies. I realize that's a hazard as in your example where `--workspace` works but `-p` doesn't, but that is unfortunately the only way available for now.

Closing as a duplicate of #4463.

**Closed by ehuss** 2022-05-06 18:22 UTC
Labels: C-bug

**Comment by andreisilviudragnea** [comment] 2023-08-10 13:13
@ehuss I think this issue title better describes the problem of default features always enabled in workspace mode for a dependency. Is this going to be changed or fixed in the future?
