### ISSUE TITLE
`cargo build|test|bench|...` traverses entire source tree for unknown reason

### ISSUE THREAD

**Issue by Byron** [rust-lang/cargo#1524] opened 2015-04-15 07:24 UTC
In my project, I see a multi-second delay before `cargo build` and friends even start to operate. The following excerpt shows that trying to build an already built project takes a long time. Within that time, `cargo` will traverse the entire source tree and consume one entire core for more than 10 seconds.

```bash
➜  google-apis-rs git:(master) ✗ time cargo build
cargo build  2.42s user 6.83s system 99% cpu 9.259 total
➜  google-apis-rs git:(master) ✗ time cargo build
cargo build  2.33s user 7.73s system 99% cpu 10.069 total
➜  google-apis-rs git:(master) ✗
```
I can only assume that it tries to find something. Usually this will not play a huge role, my project tree is massive though so it starts to matter.

```bash
➜  google-apis-rs git:(master) ✗ du -sch *
4.0K    CONTRIBUTING.md
 12K    Cargo.lock
4.0K    Cargo.toml
4.0K    LICENSE.md
4.0K    Makefile
8.0K    README.md
 16M    etc
 22G    gen
376K    src
112M    target
 22G    total
➜  google-apis-rs git:(master) ✗ find . -type f | wc -l
  500798
```

I am posting this here just to verify that this recursive search is indeed required. Maybe there can be a  way to turn it off. I could imagine that it tries to find Cargo.toml files to get an idea of inter-project dependencies. However, my [primary Cargo.toml](https://github.com/Byron/google-apis-rs/blob/master/Cargo.toml) file refers to no project `path`, so no search should be required.

# How to reproduce

Please note that the following snippet will take hours to complete, but generates at least 250k files on disk. Generation of docs could fail depending the crate.io versions of certain dependencies - for now I maintain overrides to local repositories with working versions.

```bash
git clone https://github.com/Byron/google-apis-rs
cd google-apis-rs
make gen-all-cli docs-all
# first time build
cargo build
# now to reproduce the overhead
time cargo build
time cargo build
```

# Meta

```bash
➜  google-apis-rs git:(master) ✗ cargo --version
cargo 0.0.1-pre-nightly (3499c8e 2015-04-05) (built 2015-04-05)
```

**Comment by alexcrichton** [comment] 2015-04-15 22:36
I've definitely been put off by this in the past and have wanted to fix this as well. I'll note though that if you depend on a repository (e.g. a git dependency) then Cargo *must* crawl the entire repository looking for `Cargo.toml` as you don't specify relative paths in the repository looking for dependencies.

Within the source repo, however, we should definitely only need to follow `path` depenencies.

**Comment by alexcrichton** [comment] 2015-04-15 22:37
I think this will be pretty easy to do as well, so tagging with E-easy

**Comment by Diggsey** [comment] 2015-05-03 18:38
This is much more of a problem than just poor performance. If any of the subdirectories contains a broken symlink or for some other reason is untraversable, cargo with fail with the unhelpful error message:

`The system cannot find the path specified. (os error 3)`

(Note that nowhere does it actually print the problematic path, and to even get this much information requires passing --verbose!)

**Comment by alexcrichton** [comment] 2015-11-11 20:07
Ah I think this is a dupe of https://github.com/rust-lang/cargo/issues/1423, so closing in favor of that.

**Closed by alexcrichton** 2015-11-11 20:07 UTC
Labels: E-easy
