### ISSUE TITLE
Crate graph resolution on parity-wasm with a lockfile is noticeably slow

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5817] opened 2018-07-27 23:52 UTC
Following https://github.com/alexcrichton/cargo-vendor/issues/89 I cloned the parity-ethereum repository and ran `cargo build`, but on subsequent tries, much to my surprise, it took a noticeably long time for Cargo to start printing "Compiling ..."!

This typically means that Cargo is spending too long in crate graph resolution, although it could be other things! Very unscientific testing shows ~.8s before "Compiling..." shows up on nightly. Interestingly `CARGO_PROFILE=1` only shows ~100ms ms (!!) in resolution. 

We may be able to do much better in this regard! cc @Eh2406, would you be curious to dig into this?

**Comment by Eh2406** [comment] 2018-07-28 00:20
Thanks for the cc, I am happy to help. The next step IMO is to run the problematic invocation in a profiler perf/wpr and see where we are spending the time. I can't promise when I can get to reproducing hear.

**Comment by ehuss** [comment] 2018-07-28 02:10
I took a quick look.  It looks like there is a massive slowdown starting in 1.27.  I don't think it is graph resolution, which is not significantly different.  Things like `build_unit_dependencies` have had a huge increase in time (going from almost 0% to ~15% of the total time before first `Compiling`).  I would guess it's the introduction of `Profile` to `Unit`, which I worried was a little heavy.  I can continue digging around to get a better picture.

**Comment by ehuss** [comment] 2018-07-28 19:03
I did some rough measurements of time-to-first-compile.

Version | Time
------- | ----
1.21 | 5.97s +/- 0.769 (!!!)
1.22 | 0.48s +/- 0.023
1.23 | 0.49s +/- 0.024
1.24 | 0.47s +/- 0.036
1.25 | 0.49s +/- 0.026
1.26 | 0.50s +/- 0.024
Just before Profiles(3b14988d423b1858252ee05c5395abd035bbea5f) | 0.54s +/- 0.080
Profiles (c24a09772c2c1cb315970dbc721f2a42d4515f21) | 0.60s +/- 0.025
1.27-stable | 0.62s +/- 0.022
1.28-beta | 0.65s +/- 0.059
1.29-nightly | 0.63s +/- 0.059
master | 0.63s +/- 0.026
master no profiles | 0.62s +/- 0.035

The last one is a hacked version where I replaced Profile in `Unit` with `&'static Profile` and used a global profile and removed profile computation.  I was surprised it didn't improve performance much.  The patch is kinda big, so maybe it is due to some other reason.

There is a lot of variability due to caching.  These numbers are after running once.  The first run can be up to 2s before it starts.  It's hard to nail down due to the variability.

It might be interesting to do more detailed profiling.  About 0.15s of the startup time is updating git submodules.  Resolve is about 0.15 to 0.2. 

Not sure if this is helpful at all...

**Comment by alexcrichton** [comment] 2018-07-28 20:34
Thanks for digging in @ehuss! My profile attempts on OSX didn't show the profile bits as being too much time, but I primarily saw:

<img width="1396" alt="screen shot 2018-07-28 at 1 33 07 pm" src="https://user-images.githubusercontent.com/64996/43360481-ca95b742-926a-11e8-811a-ea07bd9ceed3.png">

I think the largest time here is basically spent in loading crates from the registry, which isn't uncommon for crates I've seen depending on lots of crates from crates.io

In that sense resolution itself may not be taking much time here, but rather things like reading the registry and parsing/walking git repositories (lots of git deps in this lock file)

**Comment by Eh2406** [comment] 2018-07-28 21:43
Note that going from ~.50s -> ~0.6s is consistent with spending ~15% in `build_unit_dependencies`. And consistent with finding that we are spending most of our time in parsing the registry.

Not that I know how to make it faster.

**Comment by Eh2406** [comment] 2019-05-24 13:43
I think this got worked on a lot since this issue, for example #6880 and #6867. Most of the profiling work here is now out of date. I will close this issue, we can open a new one if we find a new slow case.

**Closed by Eh2406** 2019-05-24 13:43 UTC
Labels: A-dependency-resolution, Performance
