### ISSUE TITLE
cargo check --all-targets can generate duplicate messages.

### ISSUE THREAD

**Issue by mooman219** [rust-lang/cargo#5561] opened 2018-05-23 04:54 UTC
When running `cargo check --all-targets`, messages are sometimes duplicated in the output.

Version: cargo 1.27.0-nightly (9e53ac6e6 2018-05-07)

Example erroneous code in a simple new binary project:
```rust
fn main() {}

fn bar(foo: i32 bar: f32) -> f32 {
    return (foo as f32) + bar;
}
```
Corresponding output:
```rust
~/Downloads/test/vscode-test $ cargo check --all-targets
    Checking vscode-test v0.1.0 (file:///C:/Users/Mooma/Downloads/test/vscode-test)
error: expected one of `!`, `(`, `+`, `,`, `::`, or `<`, found `bar`
 --> src\main.rs:3:17
  |
3 | fn bar(foo: i32 bar: f32) -> f32 {
  |                 ^^^ expected one of `!`, `(`, `+`, `,`, `::`, or `<` here

error: expected one of `!`, `(`, `+`, `,`, `::`, or `<`, found `bar`
 --> src\main.rs:3:17
  |
3 | fn bar(foo: i32 bar: f32) -> f32 {
  |                 ^^^ expected one of `!`, `(`, `+`, `,`, `::`, or `<` here

error: aborting due to previous error

error: aborting due to previous error

error: Could not compile `vscode-test`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `vscode-test`.

To learn more, run the command again with --verbose.
```

**Comment by ehuss** [comment] 2018-05-23 05:11
The duplicates are due to the same file (`main.rs` in this case) being used for different targets (binary and unit test).   You can use the various target flags (`--bin`, `--lib`, `--test`, etc.) to limit which targets are checked.  It depends on your use case.  I have my editor set up to automatically check as a test (`cargo check --bin vscode-test --profile=test` in this case) to ensure that any tests get checked (a few lints will be disabled, such as `missing_docs` when checking as a test, but those are rare).

**Comment by alexcrichton** [comment] 2018-05-23 14:18
What's actually happening here is that the library is being compiled twice (once with `--test` and once for doc tests later on), and this is a dupe of https://github.com/rust-lang/cargo/issues/1534, https://github.com/rust-lang/cargo/issues/851, and https://github.com/rust-lang/cargo/issues/1198. This is intended behavior though, and you can use various flags like `--test`, `--lib`, or `-j` to not run `rustc` in parallel, so I'm going to close this.

**Closed by alexcrichton** 2018-05-23 14:18 UTC
