### ISSUE TITLE
Error message colouring broken (on Windows) with 1.74

### ISSUE THREAD

**Issue by StevePitts** [rust-lang/cargo#13104] opened 2023-12-01 20:59 UTC
After upgrading to Rust 1.74.0 some of the message colouring and highlighting disappears when cargo or rustc are used in a Windows 10 console session (Take Command, cmd.exe and Powershell all exhibit the same behaviour):

![image](https://github.com/rust-lang/rust/assets/23247513/0e776d38-f43b-4cd8-82a8-3d43665b308b)

As the above image demonstrates this was working fine with 1.73.0

**Comment by weihanglo** [comment] 2023-12-02 23:18
Transferred.

Haven't yet investigated but is very like due to this PR <https://github.com/rust-lang/cargo/pull/12751>.

**Comment by epage** [comment] 2023-12-04 15:41
I tested `cargo` 1.74.0 within `cmd` on Windows 10.0.19045 and cannot reproduce this.

From [wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#DOS_and_Windows), it sounds like Windows 10 version 1511 is the first version with ANSI escape codes.  Huh, for some reason I thought this was back in the Windows 8 days

Can you confirm what version of Windows you are using?  To better understand the scope of the problem, how come you are on such an old build of Windows 10?

If this is a pre-1511 build of Windows, then that means `wincon` is being used.  By the output, cargo is doing things correctly but we aren't telling rustc to do things correctly.

**Comment by epage** [comment] 2023-12-04 15:53
@StevePitts could you run the following and report the results?
```console
$ git clone https://github.com/rust-cli/anstyle.git
$ cargo run -p anstyle-query --example query
$ cargo run -p anstyle-wincon --example dump-wincon
$ cargo run -p anstream --example query-stream
$ cargo run -p anstream --example dump-stream
```

**Comment by epage** [comment] 2023-12-04 15:56
For example, on my Windows 10 machine
```console
$ cargo run -p anstyle-query --example query
clicolor: None
clicolor_force: false
no_color: false
term_supports_ansi_color: false
term_supports_color: true
truecolor: false
enable_ansi_colors: Some(true)
is_ci: false
$ cargo run -p anstyle-wincon --example dump-wincon
... first two rows are colored, rest are not
$ cargo run -p anstream --example query-stream
stdout:
  choice: Always
  choice: AlwaysAnsi
stderr:
  choice: Always
  choice: AlwaysAnsi
$ cargo run -p anstream --example dump-stream
... all rows colored
```

**Comment by StevePitts** [comment] 2023-12-07 22:55
Sorry for the delayed response folks but I've been in Zurich for work since Sunday night with no access to my home development box.

According to Take Command my Windows is:

Windows 10 [Version 10.0.19045.3693]

and as far as I'm concerned is bang up to date.

Results from a Take Command window:

![image](https://github.com/rust-lang/cargo/assets/23247513/a636dd76-0840-494f-992d-f4776e10ff6f)

Results from a cmd.exe window:

![image](https://github.com/rust-lang/cargo/assets/23247513/cad707eb-1e8f-4790-8be1-6d71902cbd4b)

I hope this helps but I'm unlikely to be of much help for a few days as I'm returned from Zurich and tested positive for COVID

**Comment by epage** [comment] 2023-12-07 23:04
@StevePitts 

> I hope this helps but I'm unlikely to be of much help for a few days as I'm returned from Zurich and tested positive for COVID

Hope you get better quickly!

**Comment by epage** [comment] 2023-12-08 16:56
There are two questions here
- Why can't we enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING`?
  - 19045 is the latest so it should be supported
  - I've updated `cargo run -p anstyle-query --example query` to report the underlying error (though it might be ambiguous on which stream it errored).  If you could `git pull` and run again, that'd be great
- Why are we not showing colors *just for rustc*?
  - At least for this, hacking out `ENABLE_VIRTUAL_TERMINAL_PROCESSING` at least reproduces it.

**Comment by epage** [comment] 2023-12-08 17:11
In debugging this, I found that rustc is correctly emitting the escape codes.  Most likely what is happening is that `anstyle-wincon`, for some reason, can't understand the escape codes and so it prints nothing.

Example of escape codes it can handle
```
\u{1b}[1m\u{1b}[36m    Building\u{1b}[0m
```
Example of escape codes it can't handle
```
\u{1b}[0m\u{1b}[1m\u{1b}[38;5;11mwarning\u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;15m: the `dbg!` macro is intended as a debugging tool\u{1b}[0m\n\u{1b}[0m   \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m--> \u{1b}[0m\u{1b}[0msrc/cargo\\core\\shell.rs:419:9\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m|\u{1b}[0m\n\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m419\u{1b}[0m\u{1b}[0m \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m|\u{1b}[0m\u{1b}[0m \u{1b}[0m\u{1b}[0m        dbg!(String::from_utf8_lossy(message));\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m| \u{1b}[0m\u{1b}[0m        \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;11m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m|\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m= \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;15mhelp\u{1b}[0m\u{1b}[0m: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m= \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;15mnote\u{1b}[0m\u{1b}[0m: requested on the command line with `-W clippy::dbg-macro`\u{1b}[0m\n\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14mhelp\u{1b}[0m\u{1b}[0m: remove the invocation before committing it to a version control system\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m|\u{1b}[0m\n\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m419\u{1b}[0m\u{1b}[0m \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m| \u{1b}[0m\u{1b}[0m        \u{1b}[0m\u{1b}[0m\u{1b}[38;5;10mString::from_utf8_lossy(message)\u{1b}[0m\u{1b}[0m;\u{1b}[0m\n\u{1b}[0m    \u{1b}[0m\u{1b}[0m\u{1b}[1m\u{1b}[38;5;14m|\u{1b}[0m\u{1b}[0m         \u{1b}[0m\u{1b}[0m\u{1b}[38;5;10m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u{1b}[0m\n"
```

**Comment by epage** [comment] 2023-12-08 17:43
`termcolor` only supports outputting "bright" colors via Ansi256 escape codes.  It seems `anstream`s wincon adapter doesn't support those.

```
---- adapter::wincon::test::termcolor stdout ----
thread 'adapter::wincon::test::termcolor' panicked at crates/anstream/src/adapter/wincon.rs:313:9:
assertion `left == right` failed: "Hello \u{1b}[0m\u{1b}[1m\u{1b}[38;5;11mworld\u{1b}[0m!"
  left: [(Style { fg: None, bg: None, underline: None, effects: Effects() }, "Hello "), (Style { fg: Some(Ansi(Green))
, bg: None, underline: None, effects: Effects() }, "world"), (Style { fg: None, bg: None, underline: None, effects: Ef
fects() }, "!")]
 right: [(Style { fg: None, bg: None, underline: None, effects: Effects() }, "Hello "), (Style { fg: None, bg: None, u
nderline: None, effects: Effects(BOLD) }, "world"), (Style { fg: None, bg: None, underline: None, effects: Effects() }
, "!")]
```

**Comment by epage** [comment] 2023-12-08 18:22
@StevePitts 

In addition to re-running `cargo run -p anstyle-query --example query` after a `git pull`, could you also run `rg` with  `--color ansi`?  That would show whether `termcolor` is also able to enable ANSI escape code support which would show whether its a difference in how we interact with windows.

**Closed** 2023-12-08 20:54 UTC
Labels: C-bug, O-windows, A-console-output, regression-from-stable-to-stable, S-triage

**Comment by StevePitts** [comment] 2023-12-10 10:54
> In addition to re-running `cargo run -p anstyle-query --example query` after a `git pull`, could you also run `rg` with `--color ansi`?

@epage not sure if this is still required given that the issue has been closed but:
![image](https://github.com/rust-lang/cargo/assets/23247513/7701e34a-0dfb-48d6-8636-1d08b9de0c7a)

HTH

**Comment by epage** [comment] 2023-12-11 16:27
Thanks @StevePitts !

Basically, this bug is actually two and we solved the more immediate one but it would also be good to figure out why we have to fallback to wincon on your system.  The running assumption has been that wincon support is only needed for legacy Win8 systems and there has been discussion on whether it should be removed.

Understanding why cargo is falling back to wincon on your system can help us withe either
- Undersanding if we need to maintain wincon support longer than we expected
- Fixing the bug which will let cargo use more advanced terminal styling features.

So ripgrep is running into the same problem with its different `ENABLE_VIRTUAL_TERMINAL_PROCESSING` code.  Unfortunately, I don't have much in the way of ideas and worry that sending a lot of one off, incremental debugging steps will be a slow, frustrating, and fruitless process.  **If you would be willing to dig into this some (figuring out the exact call that is failing, etc) that would be a big help.**  Thankfully `anstyle-query` is all you need for that and is relatively small.

## Some random notes

The [docs](https://learn.microsoft.com/en-us/windows/console/setconsolemode) for `ENABLE_VIRTUAL_TERMINAL_PROCESSING` say

> Ensure ENABLE_PROCESSED_OUTPUT is set when using this flag.

but we only `|` in `ENABLE_VIRTUAL_TERMINAL_PROCESSING` to the existing mode.  No idea if `ENABLE_PROCESSED_OUTPUT` is set...

Though the [example](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN#example-of-enabling-virtual-terminal-processing) doesn't do anything with this.

----

The error being returned is `ERROR_INVALID_PARAMETER`

The docs say:

> Checking whether SetConsoleMode returns 0 and GetLastError returns ERROR_INVALID_PARAMETER is the current mechanism to determine when running on a down-level system. An application receiving ERROR_INVALID_PARAMETER with one of the newer console mode flags in the bit field should gracefully degrade behavior and try again.

A [stackoverflow post](https://stackoverflow.com/questions/46030331/enable-virtual-terminal-processing-and-disable-newline-auto-return-failing) references "legacy console".  It looks like this is a "Properties" setting.

**Can you check if "legacy console" is enabled?**
1. Open cmd
2. Click the cmd icon in top left
3. Click "Properties"
4. On the "Options" tab at the bottom is a checkbox for "Use legacy console (requires relaunch; affects all consoles)"

**Comment by StevePitts** [comment] 2023-12-12 13:02
A few things of note:

1. the legacy console was indeed enabled on this system, although I have no particular recollection of doing so
2. this system used to run Windows 8.1 (and 8 before that, which was installed on delivery) and was upgraded to 10 in place just before end of support for 8.1
3. unchecking the legacy console makes the cargo issue go away with the 1.74.0 release version and also enables rg with --color ansi to work properly
4. I spend a lot of time at the command line so it is possible that legacy console was enabled to resolve an issue with the output from some tool or other, so I will keep an eye out over the next few weeks and might have to re-enable it if the tool concerned turns out be fundamental

On the basis of the above is there anything more you'd like me to investigate here?

**Comment by epage** [comment] 2023-12-12 14:36
Thats it; thanks!
