### ISSUE TITLE
Running multiple cargo commands at the same time leads to errors

### ISSUE THREAD

**Issue by pyfisch** [rust-lang/cargo#1152] opened 2015-01-11 15:37 UTC
```
rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)
binary: rustc
commit-hash: 44a287e6eb22ec3c2a687fc156813577464017f7
commit-date: 2015-01-08 17:03:40 -0800
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

If you start multiple instances of commands like cargo build on the same project the compiler will raise errors.

Probably cargo should lock a project if it is running.

**Comment by alexcrichton** [comment] 2015-01-12 16:51
Dupe of https://github.com/rust-lang/cargo/issues/354, but thanks!

**Closed by alexcrichton** 2015-01-12 16:51 UTC
