### ISSUE TITLE
Using --manifest-path, the filenames in error messages are relative to the manifest, not the current working directory

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#11007] opened 2022-08-19 11:50 UTC
### Problem

When using `--manifest-path`, the filenames in error messages are relative to the manifest given, not the directory cargo is invoked from.

### Steps

1. For example in Miri, introduce a build failure in `cargo-miri/src/main.rs`.
2. Run `cargo check --manifest-path cargo-miri/Cargo.toml`
3. Notice the error refers to `src/main.rs:21:17`

### Possible Solution(s)

Cargo could instruct rustc to print the paths relative to a given directory, or it could adjust the paths itself.

### Notes

This also affects the rustc repo, where we have 3 workspaces currently (the main one, bootstrap, and codegen_cranelift). Errors in codegen_cranelift show paths that are quite hard to interpret since they are relative to `src/compiler/rustc_codegen_cranelift`, which is hard to users to even realize.

**Comment by weihanglo** [comment] 2022-10-25 02:22
Some other issues around relative path in error messages:

- https://github.com/rust-lang/cargo/issues/5450
- https://github.com/rust-lang/cargo/issues/5895
- https://github.com/rust-lang/cargo/issues/8506
- https://github.com/rust-lang/cargo/issues/9887
- https://github.com/rust-lang/cargo/issues/11043

Basically, this is by design that always be relative to the workspace root. Most projects have a workspace at the root of the repository, and most IDE also depends on workspace when building Cargo projects.

Maybe we do need a `-Zdiagnose-with-full-path`, so that either IDE or anyone's specialized tool can take advantage of absolute path without ambiguity.

In the meanwhile, could you try if it helps with [`--remap-path-prefix`] or [`-Zremap-cwd-prefix`]? For example,

```
RUSTFLAGS='--remap-path-prefix cargo-miri=' cargo check --manifest-path cargo-miri/Cargo.toml
```

Not ideal I know. Sorry about that :(

[`--remap-path-prefix`]: https://doc.rust-lang.org/stable/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output
[`-Zremap-cwd-prefix`]: https://doc.rust-lang.org/1.64.0/unstable-book/compiler-flags/remap-cwd-prefix.html

**Comment by RalfJung** [comment] 2022-10-25 06:20
> Basically, this is by design that always be relative to the workspace root. Most projects have a workspace at the root of the repository, and most IDE also depends on workspace when building Cargo projects.

I am not talking about workspace projects though. I am talking about using `--manifest-path` to build a different workspace.

If you read the discussion at https://github.com/rust-lang/rust-analyzer/issues/10793 and the other backlinks above, you will see that the current behavior is quite painful for IDEs in multi-workspace projects. 

I can try RUSTFLAGS but then the problem is that all builds inside and outside the IDE need to be somehow configured to use the same flags.

**Comment by RalfJung** [comment] 2022-10-25 11:51
The situation with these multi-workspace (or multi-crate-no-workspace) git repos is that they come with a single script that does all the building (`./miri` or `./x.py`). Right now when `./miri` or `./x.py` prints a path it might be relative to whatever (different errors can even be relative to different paths), which is already ambiguous for people consuming their output and a big problem for tools, such as IDEs, consuming their output.

**Comment by jyn514** [comment] 2023-06-19 18:33
> * My impression is that if you run `cargo check --mainfest-path src/tools/miri/cargo-miri/Cargo.toml`, you'll get diagnostics from `rust-lang/rust` root.

This is not the case. Bootstrap runs all cargo processes from the rust-lang/rust root but still gets the truncated file paths.

**Comment by jyn514** [comment] 2023-06-19 18:40
here is a way to reproduce the issue:
```
$ git apply
diff --git a/src/bootstrap/lib.rs b/src/bootstrap/lib.rs
index d7e77aeb338..6a046b0995f 100644
--- a/src/bootstrap/lib.rs
+++ b/src/bootstrap/lib.rs
@@ -117,7 +117,7 @@ pub unsafe fn setup(_build: &mut crate::Build) {}
 
 /// Extra --check-cfg to add when building
 /// (Mode restriction, config name, config values (if any))
-const EXTRA_CHECK_CFGS: &[(Option<Mode>, &'static str, Option<&[&'static str]>)] = &[
+const EXTRA_CHEK_CFGS: &[(Option<Mode>, &'static str, Option<&[&'static str]>)] = &[
     (None, "bootstrap", None),
     (Some(Mode::Rustc), "parallel_compiler", None),
     (Some(Mode::ToolRustc), "parallel_compiler", None),
$ cargo check -q --manifest-path src/bootstrap/Cargo.toml  --message-format json | jq 'select(.reason = 
"compiler-message") | select((.message.spans | length) != 0) | { package_id, manifest_path, file_name: .
message.spans[0].file_name }'
{
  "package_id": "bootstrap 0.0.0 (path+file:///home/jyn/src/rust/src/bootstrap)",
  "manifest_path": "/home/jyn/src/rust/src/bootstrap/Cargo.toml",
  "file_name": "builder.rs"
}
```

**Comment by jyn514** [comment] 2023-06-19 18:43
I think this is the same problem as https://github.com/rust-lang/cargo/issues/9427.

**Comment by jyn514** [comment] 2023-06-19 19:21
> Would it help if Cargo has a flag to forced print absolute paths, such as what #5450 and #11043 propose?

yes, this would help. i'm looking into adding it as an unstable flag to rustc now, but putting it in cargo would be fine too.

**Comment by jyn514** [comment] 2023-06-25 15:42
> > * My impression is that if you run `cargo check --mainfest-path src/tools/miri/cargo-miri/Cargo.toml`, you'll get diagnostics from `rust-lang/rust` root.
> 
> This is not the case. Bootstrap runs all cargo processes from the rust-lang/rust root but still gets the truncated file paths.

https://github.com/rust-lang/cargo/blob/888100352a35f74dcca728a4ae0403f79f695e94/src/cargo/util/workspace.rs#L97-L124

(note that miri is in a separate workspace, so this effectively strips `src/tools/miri` from the start of each diagnostic)

**Comment by RalfJung** [comment] 2023-08-21 08:27
FWIW, Miri is not a separate workspace, but the cranelift backend is.

**Comment by epage** [comment] 2023-10-19 01:42
#9887 appears to ask for the same thing (shift messages to be relative to CWD), so closing in favor of that

**Closed by epage** 2023-10-19 01:42 UTC
Labels: C-bug, A-errors
