### ISSUE TITLE
Resolver v2 unifies features for tests in workspace

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/cargo#9949] opened 2021-09-28 06:24 UTC
**Problem**
In a workspace where one crate has optional features and another enables some of the optional features, those optional features end up being enabled for the tests in the original crate.

**Steps**
1. Have a workspace with crates `a` and `b` an `resolver = "2"`
2. In crate `a` have an optional feature `foo`
3. In crate `a` have test with `#[cfg(feature = "foo")]` attribute on it
4. Have `b` depend on `a` with `foo` feature enabled
5. `cargo test` - `4` forces `foo` feature for `a` tests to be enabled (unexpected behavior)
6. `cd crates/a && cargo test` - feature `foo` is not enabled and test with `#[cfg(feature = "foo")]` is no longer running (expected behavior)

**Possible Solution(s)**
I would expect dependencies and features resolution to be identical whether I run tests, clippy or anything else in the workspace root or in a specific crate within it.

**Notes**

Output of `cargo version`: cargo 1.56.0-nightly (e515c3277 2021-09-08)

I have a use case for CUDA support in a library where I want to have tests for it, but not necessarily run it unless in a specific environment with corresponding GPU available.

**Comment by ehuss** [comment] 2021-09-28 20:11
Thanks for the report!  This is currently expected behavior, as the features enabled depend on which packages are being built. This is tracked in #4463, so I'm going to close as a duplicate of that.

**Closed by ehuss** 2021-09-28 20:11 UTC
Labels: C-bug
