### ISSUE TITLE
RLS and cargo check run sometimes unnecesary build.rs steps

### ISSUE THREAD

**Issue by robmv** [rust-lang/cargo#6834] opened 2019-04-09 14:51 UTC
When running an IDE using RLS or just running `cargo check`, some large projects using crates that have big static builds of non Rust based native libraries, the `build.rs` of those dependencies run a complete build of the non Rust code.

One example is `openssl`, when using it in vendored mode, takes a lot of time to get feedback on an IDE because it will build openssl entirely, something it isn't needed for getting the information RLS or `cargo check` needs, they don't need a complete build of those crates.

Maybe standardizing some kind of environment variable passed to the `build.rs` program could tell these dependencies that the build is being run for RLS or cargo check, and these scripts could be updated to be smarter, avoiding the native build in these circumstances.

This will require cooperation of `build.rs` users but it is better than than the current status where an IDE takes too much time to give some feedback.

**Comment by nox** [comment] 2019-10-20 10:34
This is also a big issue for Servo, where we have to build SpiderMonkey, osmesa, skia, angle, and a bunch of other C++ projects, which takes a lot of time.

I worked around the issue for RLS by checking that `$CARGO --version` starts with "rls ", but I can't do that for `cargo check`.

**Comment by jyn514** [comment] 2020-12-25 14:59
I think this is the same as https://github.com/rust-lang/cargo/issues/4001.

**Comment by ehuss** [comment] 2021-01-07 02:28
Yea, I'm going to close as a duplicate of #4001.

**Closed by ehuss** 2021-01-07 02:28 UTC
Labels: A-build-scripts, C-feature-request
