### ISSUE TITLE
Feature Request: cargo new --in-workspace [directory] [name]

### ISSUE THREAD

**Issue by jamescostian** [rust-lang/cargo#6378] opened 2018-12-05 05:37 UTC
# The problem

Imagine you're working in a project called `foo` and it's a workspace. You want to create a new member, `bar`, as a subdirectory of `foo`. If you use `cargo new bar` (or `mkdir bar && cd bar && cargo init`) you'll get warnings like this:

```
warning: compiling this new crate may not work due to invalid workspace configuration

current package believes it's in a workspace when it's not:
current:   [new project's Cargo.toml]
workspace: [encompassing workspace's Cargo.toml]

this may be fixable by ensuring that this crate is depended on by the workspace root: 
[encompassing workspace's Cargo.toml]
```

Ideally, that manual work should be automated (if the user wants it).

There's more manual work if you don't want subdirectories. For example, if `foo` is in `code/foo` and you want to make `bar` in `code/bar`, then you have to change the `Cargo.toml` files in *both* directories after using `cargo new`

# The solution

In the case of creating `bar` as a subdirectory, you'd `cd` to the workspace root and use `cargo new --in-workspace . bar` and `foo/Cargo.toml` would be updated to include `bar` in its `[workspace]` section. In the case of creating `bar` outside of the root, you'd use `cargo new --in-workspace ../foo bar` as an example. Similar capabilities should also be given to `cargo init` for consistency

If the directory passed to `--in-workspace` is not a workspace, then there would be an error.

I've never contributed to cargo before (and am pretty new to Rust) but I don't think this is too complicated, and if the idea is accepted I'd love to try and implement it. The changes would take place in [this file](https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs). Add a boolean to [NewOptions](https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs#L27-L35), change [its constructor](https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs#L75-L102), update [this behavior](https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs#L607-L614) to change the `workspaces` section of the root's `Cargo.toml` (and the child's `package.workspace` if the child isn't a subdirectory of the root), and it'll be mostly done.

# Notes

This is *not* a breaking change. The new behavior only goes into effect when a new argument (`--in-workspace`) is specified.

Relevant reading: [the original RFC](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md)

Alternative ideas:
+ `cargo new --root [directory] [name]`
+ `cargo new --member [name]` - strictly for subdirectories (only addresses `foo/bar` example; does not address the issue of creating `code/bar` when your root is `code/foo`)

**Comment by kornelski** [comment] 2018-12-12 15:32
I've ran into "compiling this new crate may not work" error a few times, too. 

It's a bit silly that Cargo makes a non-working crate, knows it, even knows how to fix it, but just leaves it broken.

To me it would make most sense if Cargo just automatically added the new crate to the `workspace.members` in this situation.

**Comment by matklad** [comment] 2019-01-17 10:40
There's a reverse problem as well, exemplified by this thread:

https://salsa.zulipchat.com/#narrow/stream/145099-general/topic/revamped.20API/near/155324150

If a user crates, via `cargo new`, a `parent/Cargo.toml` and a `parent/child/Cargo.toml`, they naively expect that they've created a workspace, while it's not actually the case. What's bad about this situation is that the user doesn't get any warnings: everything works, it just uses path dependencies instead of workspaces. `cargo test` works, it just does not test everything. 

I think it's clear now that workspaces are the default mode for working on multi-crate projects. I suggest the following change to `cargo new` / `cargo init` behavior:

* if the path to the new crate is not a part of the workspace, add an empty `[workspace]` section to Cargo.toml
* if the path *is* part of the workspace, adjust the members key (if it exists), or add the new crate as a path-dependency (printing that this was done).

That is, `cargo new` should always operate with workspaces, by either creating a fresh new one, or adding a member to an existing one.

**Comment by czipperz** [comment] 2019-07-07 17:47
What is the progress here?  I would really like this feature.

**Comment by jamescostian** [comment] 2019-07-07 20:19
I'm no longer using rust, so I'm not interested in contributing to fixing this. But if anyone is willing to take the torch on this, I think it would be beneficial to the rust community (or, at least to the parts of the rust community that like modular code)

**Comment by czipperz** [comment] 2019-07-07 22:45
Now that I think about this more, I'm coming to the conclusion that adding a flag to `new`/`init` is the wrong approach.  This is because the user gets the warning after the action has already completed and these commands cannot be re-ran (they cause an error the second time as it has already been initialized).  Maybe we should have a `cargo add-to-workspace` command?  But then it seems like it's not much better than just doing it yourself since it's a pretty easy change.

**Comment by kornelski** [comment] 2019-07-08 11:13
There are 3 options here:

1. Add to workspace automatically
2. Don't add to workspace automatically
3. Do nothing, and ask user what to do instead


AFAIK 2 is broken, so 3 is asking whether you want a broken crate or a non-broken crate, which is absurd (or a very very edge case at best). So that leaves 1 as the only sensible option?

**Comment by czipperz** [comment] 2019-07-09 01:29
But 1 removes backwards compatibility and makes automation hard.  I do agree, if we were doing this from the ground up we should do the first.

**Comment by kornelski** [comment] 2019-07-09 01:44
Why would any existing users rely on `cargo new` producing a crate that can't be used?

When do you need to automate creation of unusable crates?

**Comment by czipperz** [comment] 2019-07-09 02:41
It's still completely usable.  It's just not part of the workspace.  Try it in a local repository.  It works fine, just there are two `Cargo.lock` files and two `target` directories.

**Comment by czipperz** [comment] 2019-07-09 02:46
So let's that `cargo new` will automatically add the crate to the workspace, which as we all agree on is the most logical path to pursue.  Should it automatically create a workspace entry if one doesn't exist?  IE it adds the following lines to the `Cargo.toml` file:

```
[workspace]
members = ["subcrate"]
```

**Comment by kornelski** [comment] 2019-07-09 12:20
> It's still completely usable. It's just not part of the workspace. 

Are you sure you're reproducing the problem correctly? Two crates can be nested if there is no workspace involved. But as soon as you create a workspace at a higher level, `cargo new` just becomes broken and useless:

```sh
cargo new level1
cd level1
echo "[workspace]" >> Cargo.toml
cargo new level2
cd level2
cargo test
```

> error: current package believes it's in a workspace when it's not:
current:   /private/tmp/level1/level2/Cargo.toml
workspace: /private/tmp/level1/Cargo.toml

> this may be fixable by ensuring that this crate is depended on by the workspace root: /private/tmp/level1/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.

**Comment by arn-the-long-beard** [comment] 2020-07-31 11:56
Hello , I got the error described in this issue when I follow the book there https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html , but with 3 projects instead of one : 

Imagine you have the following `Cargo.toml`

```toml
[workspace]

members = [
    "client",
    "server",
    "shared"
]
```

Then 

`cargo new client --lib`

```warning: compiling this new crate may not work due to invalid workspace configuration

failed to read path/to/server 

Caused by:
  No such file or directory (os error 2)
     Created library `client` package

```

`cargo new server`

```warning: compiling this new crate may not work due to invalid workspace configuration

failed to read path/to/shared

Caused by:
  No such file or directory (os error 2)
     Created library `client` package

```

`cargo new shared`

No error

I understand the error is thrown because cargo tries to read the other crates ( They are not yet created ) so we get error . That is very logical.

But : 

Is this the expected behavior while creating a workspace? 
Is this related to the feature described there ?

Thank you in advance. I am a baby Rustacean, so maybe my question are not smart :P , so you can tell me :D

**Comment by saschanaz** [comment] 2020-11-15 01:23
A workaround: add the crate name to the workspace member list *before* `cargo new`, then it just proceeds without warning.

**Comment by danieleades** [comment] 2020-11-18 12:45
> A workaround: add the crate name to the workspace member list _before_ `cargo new`, then it just proceeds without warning.

That's not really helpful, since this ticket is a feature request for not having to use that workaround.

**Comment by krtab** [comment] 2021-11-18 13:45
So I have started looking at how to implement this feature, and in my opinion it would be quite awkward to do given the current code structure

# Current code structure issue

`cargo::ops::cargo_new::mk` creates a package by (see code at the end of this comment):
1. Writing files from hardcoded "templates".
2. Using `cargo::core::workspace::Workspace::new()` to try to create a `Workspace` struct from these files.  `Workspace::new` is a faillible function, which implements amongst others, the sanity check leading to this issue.
3. Checking whether 2. returned an `Err` and if so, turning that error into a displayed warning using `cargo::display_warning_with_error`.

Importantly, all errors are `anyhow::Error`.

The logical place to put code that add the newly created package to the pre-existing workspace would be in `cargo_new::mk`. Unfortunately, this currently cannot be done without either dirty string comparison or duplicating the whole logic checking for workspace/package nesting, because the error we have access to have been "type erased" (not sure it is the proper term).

# Possible remedies

I am not sure how to move forward on this issue. Possible solutions that come to mind are:

1. Implement some string comparison in `mk` to check if the error message is the relevant one (very very ugly and fragile imo).
2. Create a new function `workspace::new_sanitize` that could write to the disk and sanitize the workspace instead of erroring, taking care to duplicate as little code as possible.
3. Create an `enum` Error and make a new function `workspace::new_precise_error` that would return such enum in the `Err` variant. `Workspace::new` would then only be a wrapper around it.
4. Create a `WriteableWorkspace` struct that can be written to disk, with `&mut` methods to change its attributes and and `write` method to finalize it for example. (this would be a massive code reorganization, I'm not seriously envisioning it as a practical solution here).

# Appendix

https://github.com/rust-lang/cargo/blob/ad50d0d266213e0cc4f6e526a39d96faae9a3842/src/cargo/ops/cargo_new.rs#L708-L847

**Comment by kornelski** [comment] 2021-11-25 01:03
I think it would be good to start using precise error enums in Cargo. For another feature I needed to handle network errors, and I had to downcast Anyhow errors, which didn't feel elegant.

**Comment by magnusdr** [comment] 2022-01-11 17:38
I support this feature request for the sake of having some sort of suggested default to organize workspaces. Let's look at three of the most popular game engines written in Rust:
* [Bevy](https://github.com/bevyengine/bevy) have a separate `crates` folder that all but the errors-crate resides in (this is also what the [RFC1525](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md) suggests).
* [Amethyst](https://github.com/amethyst/amethyst) have these in its project root folder, all prefixed with `amethyst_*`
* [Piston](https://github.com/PistonDevelopers/piston) chose to put this into subfolders inside `src`

It's just a matter of opening `Cargo.toml` and scroll to the workspace section to figure this out, so it's not that hard. It would however be nice if we had some "suggested structure" to people who start new projects, like this feature could provide. This way, it would be easier to spot a workspace and its members at a glance, without having to inspect `Cargo.toml`.

**Comment by epage** [comment] 2023-08-01 20:19
We talked about this issue today in the cargo team meeting.  Particularly with closing #12360, we are interested in removing the `cargo new && cargo check` error case due to a missing `workspace.members` entry

Some potential solutions
- Automatically add to members with a flag to opt-out
  - `cargo new --workspace` to create a workspace table (#8365) is one way to opt-out
    - Should we be encouraging workspace tables and default to only be creating the workspace and require separate `--bin` and `--lib` flags?
    - Side note: I'd like to expand `--bin` to optionally accept a bin name
- Provide a way to not be a workspace member with a flag to opt-in
  - Opt-out could be implemented by adding a `[workspace]` table (see also #8365)  or an idea I've had of allowing `package.workspace = false`
  - The name for an opt-in flag has to be understandable if we separately implement #8365

The general feel I had from the cargo team is that we prefer to opt-in by default
- If nothing else, #12069 will be activated in these cases and removing all of that is much easier than adding it in by hand
- A concern was raised about editing uncommitted files but if you have a workspace, you likely have VCS and likely we won't be changing things in a way that can't easily be undone

On a related note, should we support a flag to explicitly say where the workspace is for when it can't be auto-discovered?  Personally, I would consider being nested under the workspace where it can be auto-detected the golden path and we don't need to be going out of our way to streamline manually discovered workspaces.

A part of me wants this to be:
- Initially, we add `--workspace` which creates a `[workspace]` table and requires separate `--bin` and `--lib` flags
  - If no `[package]` is generated (no `--bin` or `--lib`), add `resolver = "2"`
  - Maybe automatically add `workspace.package.edition = "2021"`?
  - Without `--workspace`, we auto-discover a workspace and, if present, adds "self" to the `workspace.members`
- If we add support for `package.workspace = false` to turn off auto-discover without needing a `[workspace]` table, we could then allow `--workspace=<value>`
  - `--workspace` is a shorthand for `--workspace self`
  - `--workspace auto` (default) auto-discovers a workspace and, if present, adds "self" to the `workspace.members`
  - Maybe automatically add `workspace.package.edition = "2021"`?
  - `--workspace=no[ne]` which sets `package.workspace = false`

However, I'm concerned that is a little too magical but that is also a future problem...

**Comment by fogti** [comment] 2023-08-03 09:18
I think it's necessary for good ergonomics that such feature won't interfere with existing wildcards in `workspace.members`, that is, if the crate would automatically become a member of the correct workspace, the workspace `Cargo.toml` shouldn't be modified.

**Comment by epage** [comment] 2023-08-03 11:10
Sorry that I didn't make it clear but my assumption was only to add if needed.

**Comment by epage** [comment] 2023-08-22 18:39
We talked about this in the cargo team meeting.

We are fine moving forward with `cargo new` implicitly adding itself to the discovered workspace if a glob won't take care of it automatically.

We are fine with deferring an opt-out.  Designing the opt-out will likely require enough of the design of #8365 to make sure they don't cause each other problems.  In finalizing the PR for this Issue, I would recommend creating a separate issue for us to track opt-out support.

The relevant section of code starts [here](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs#L801).  We can load the workspace with [toml_edit](https://docs.rs/toml_edit/latest/toml_edit/) and edit `workspace.members` to have the relative path to the new package.  We'll need [cargo new tests](https://github.com/rust-lang/cargo/tree/master/tests/testsuite/cargo_new) and [cargo init tests](https://github.com/rust-lang/cargo/tree/master/tests/testsuite/cargo_init).  We should ensure we have tests that verify (1) no workspace found, (2) workspace without globs, and (3) workspace with globs.  We should also stress the existing formatting of `workspace.members` to ensure we preserve it as well as possible.

**Closed** 2023-10-29 03:46 UTC
Labels: Command-new, C-feature-request, S-accepted
