### ISSUE TITLE
Cargo hangs with 100% CPU usage

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2376] opened 2016-02-09 14:38 UTC
Trying to `cargo build` https://github.com/swiboe/swiboe prints:

```rust
 Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/carllerche/mio.git`
    Updating git repository `https://github.com/carllerche/nix-rust`
    Updating git repository `https://github.com/alexcrichton/wio`
    Updating git repository `https://github.com/carllerche/bytes`
````

and then after more than 10 minutes (arm) of cargo using 100% cycles:

```rust 
failed to select a version for `libc` (required by `rand`):
all possible versions conflict with previously selected versions of `libc`
  version 0.1.0 in use by libc v0.1.0
  possible versions to select: 0.1.12, 0.1.10, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1
````

After modifying `Cargo.toml` to use newer libc it seems to just hang, but using the `cargo-bake` command suddenly printed this:

````
no matching package named `wio` found (required by `mio`)
location searched: https://github.com/alexcrichton/wio
version required: *
````

It doesn't reproduce since then. Nice non-determinism!

**Comment by alexcrichton** [comment] 2016-02-09 15:49
I think that this is a dupe of https://github.com/rust-lang/cargo/issues/2090, so closing in favor of that, but thanks for the report!

**Closed by alexcrichton** 2016-02-09 15:49 UTC

**Comment by petevine** [comment] 2016-02-09 16:30
Using `-j 1` shows it hangs doing  exactly this:

 `Updating git repository `https://github.com/alexcrichton/wio``

The `swiboe` repo is abandoned at the moment so maybe this dependency shouldn't even be there?

**Comment by alexcrichton** [comment] 2016-02-09 17:48
The `-j` flag doesn't affect the resolution step, and it's likely not hanging on actually updating the git repo, that was just the last error message printed. It's likely stuck in resolve and not making progress nearly as quickly as it should be.
