### ISSUE TITLE
Enabling feature of dependency in one module enables it in each other modules

### ISSUE THREAD

**Issue by jawoznia** [rust-lang/cargo#11573] opened 2023-01-13 11:52 UTC
### Problem

Enabling feature of some dependency in one crate in workspace project enables this feature in other crates that use the same dependency.

Not sure if this is desired behavior.
Cargo-features2 was supposed to deal with similiar issue between dependencies and dev-dependencies https://rust-lang.github.io/rfcs/2957-cargo-features2.html#dev-dependencies but it seems that above case was not done for dependencies in workspace project.

Is it supposed to be implemented in the future or is it intended?

### Steps

https://github.com/jawoznia/cargo-features-shared

cargo test
running 1 test
test tests::is_odd ... FAILED
running 1 test
test tests::is_even ... ok

Then delete `even` feature from even crate 

cargo test

running 1 test
test tests::is_even ... FAILED
running 1 test
test tests::is_odd ... ok

### Version

```text
cargo 1.66.1 (ad779e08b 2023-01-10)
release: 1.66.1
commit-hash: ad779e08be893e57a9e17a810223a3e966f8c0d8
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Pop!_OS 22.04 (jammy) [64-bit]
```

**Comment by weihanglo** [comment] 2023-01-25 11:52
Thanks for your report! This seems to be intentional. See comments below for some alternatives and workarounds:

- https://github.com/rust-lang/cargo/issues/11551#issuecomment-1374535828
- https://github.com/rust-lang/cargo/issues/11225#issuecomment-1276799823

Close as it looks like a duplicate of <https://github.com/rust-lang/cargo/issues/4463>. If that is wrong, let us know and we can reopen it.

**Closed by weihanglo** 2023-01-25 11:52 UTC
Labels: C-bug
