### ISSUE TITLE
-Z build-std prevents build.rs recompilation

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/cargo#13597] opened 2024-03-17 18:50 UTC
### Problem

When `-Z build-std` is used, changing `RUSTFLAGS` environment variable (at least, didn't check other reasons) doesn't result in `build.rs` recompilation.

### Steps

1. Have a project with `build.rs`, I used writing of current time into a file for verification purposes
2. Compile once with `RUSTFLAGS="-C target-cpu=skylake" cargo +nightly build -Z build-std --target x86_64-unknown-linux-gnu`
3. Try to recompile with `RUSTFLAGS="-C target-cpu=x86-64-v2" cargo +nightly build -Z build-std --target x86_64-unknown-linux-gnu` (note different target CPU)

A the result `build.rs` is not recompiled in step 3, which in case of building C libraries there results in libraries compiled for the wrong CPU.

Removing `-Z build-std` from above commands results in `build.rs` recompiled correctly.

### Version

```text
cargo 1.78.0-nightly (7065f0ef4 2024-03-12)
release: 1.78.0-nightly
commit-hash: 7065f0ef4aa267a7455e1c478b5ccacb7baea59c
commit-date: 2024-03-12
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by ehuss** [comment] 2024-03-17 19:07
Thanks for the report! If you removed `-Z build-std`, did you also remove the `--target` flag? Also, when you say whether or not `build.rs` is recompiled, is it important to you that the build script itself is recompiled, or just that it runs again and picks up the new `CARGO_ENCODED_RUSTFLAGS`? It's unclear what C libraries you are referring to, or how they are being built, or how this relates to the build script and RUSTFLAGS. If you can provide a complete and minimal reproduction, it can be helpful to see exactly what you are doing and trying to accomplish.

Assuming that you removed `--target`, and that you only care about running the script again, then this unrelated to `-Z build-std` and is a duplicate of #13003.

**Comment by nazar-pc** [comment] 2024-03-17 19:12
> Thanks for the report! If you removed -Z build-std, did you also remove the --target flag?

No, just `-Z build-std` to minimize changes. `--target` on its own doesn't cause any issues for me.

> Also, when you say whether or not build.rs is recompiled, is it important to you that the build script itself is recompiled, or just that it runs again and picks up the new CARGO_ENCODED_RUSTFLAGS?

Apologies, I meant that whatever `build.rs` compiles to doesn't re-run on CPU change.

> It's unclear what C libraries you are referring to, or how they are being built, or how this relates to the build script and RUSTFLAGS.

`build.rs` calls https://github.com/rust-lang/cc-rs when run. So the first time it compiled libraries for Skylake with certain newer instructions and later when I recompiled for different CPU without clearing `target` I discovered that it crashes on older processors due to newer instructions being still in the library. I later reduced and reported the issue.

**Comment by ehuss** [comment] 2024-03-17 20:43
Hm, I'm not aware of `cc` looking at the target-cpu. Can you please post a complete, minimal reproduction, along with exactly what appears to not be being picked up in the build script? Here's exactly what I'm seeing:

```toml
[package]
name = "foo"

[build-dependencies]
cc = "1.0.90"
```

```rust
// src/main.rs
fn main() {}
```

```rust
// build.rs
fn main() {
    cc::Build::new().file("foo.c").compile("foo");
}
```

```c
/* foo.c */
```

```sh
RUSTFLAGS="-C target-cpu=skylake" CC_ENABLE_DEBUG_OUTPUT=1 cargo build -vv -Zbuild-std --target x86_64-unknown-linux-gnu
```

The exact compiler command this displays as running:

```
[foo 0.0.0] running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/eric/Temp/foo/target/x86_64-unknown-linux-gnu/debug/build/foo-dcda6d277b285a73/out/d1fba762150c532c-foo.o" "-c" "foo.c"
```

Notice that it does not mention `-mcpu` or anything like that. Running with a different CPU:

```sh
cargo clean
RUSTFLAGS="-C target-cpu=x86-64-v2" CC_ENABLE_DEBUG_OUTPUT=1 cargo build -vv -Zbuild-std --target x86_64-unknown-linux-gnu
```

doesn't change the output. `cc` is building it identically.

**Comment by nazar-pc** [comment] 2024-03-17 20:52
```rust
// build.rs
fn main() {
    std::fs::write(
        format!("{}/rustflags.rs", std::env::var("OUT_DIR").unwrap()),
        std::env::var("CARGO_ENCODED_RUSTFLAGS").unwrap_or_default(),
    )
    .unwrap();
}
```
```rust
// src/main.rs
fn main() {
    println!(
        "{}",
        include_str!(concat!(env!("OUT_DIR"), "/rustflags.rs"))
    );
}
```

Now do:
```bash
RUSTFLAGS="-C target-cpu=skylake" cargo +nightly run -Z build-std --target x86_64-unknown-linux-gnu
RUSTFLAGS="-C target-cpu=x86-64-v2" cargo +nightly run -Z build-std --target x86_64-unknown-linux-gnu
```

You will get:
```
-Ctarget-cpu=skylake
-Ctarget-cpu=skylake
```
But should have gotten:
```
-Ctarget-cpu=skylake
-Ctarget-cpu=x86-64-v2
```

**Comment by ehuss** [comment] 2024-03-17 22:04
Thanks! That looks to be a duplicate of #13003, so closing in favor of that.

**Closed by ehuss** 2024-03-17 22:04 UTC
Labels: C-bug, S-triage
