### ISSUE TITLE
Support adding paths to include key

### ISSUE THREAD

**Issue by mathstuf** [rust-lang/cargo#6031] opened 2018-09-15 18:12 UTC
Currently, `include` is a complete list. It would be nice to have a way to just specify additional includes rather than having to list all paths when I just want one extra file to trigger a rebuild (namely a custom derive reading files).

**Comment by mathstuf** [comment] 2018-09-17 20:31
Hmm. For some reason, when setting `include` myself to a list of paths, it still isn't triggering a rebuild when changing a listed input file.

**Comment by lights0123** [comment] 2020-09-05 18:25
That's not what `include` does—it's just an opposite of `exclude`. There's [this feature in build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed), but that doesn't necessarily trigger a rebuild of the whole crate.

**Comment by epage** [comment] 2023-10-24 00:56
@mathstuf Could you give a reproduction case?  It sounds like you are talking about `package.include` which is just about what files to include when running `cargo package` or `cargo publish` and doesn't have anything to do with rebuilding.

**Comment by mathstuf** [comment] 2023-10-24 01:15
We ended up doing this:

https://gitlab.kitware.com/utils/ghostflow-director/-/blob/e1c6c0b828baa8a6a573006a9378fb9dc09b89f6/build.rs#L46-50

because using `include` or `rerun-if-changed=` (seems to?) disable the `rerun-if-changed=` for the paths it does so by default for.

See also:

- https://github.com/graphql-rust/graphql-client/issues/117 (oh, linked above already; I chased links back to here)
- https://github.com/graphql-rust/graphql-client/issues/215
- https://users.rust-lang.org/t/opening-files-in-proc-macros/11387/6

**Comment by epage** [comment] 2023-10-24 01:21
> because using include or rerun-if-changed=

What do you mean by `include`?

**Comment by epage** [comment] 2023-10-24 01:22
btw #4587 is the issue for dealing with built-in heuristics.

**Comment by mathstuf** [comment] 2023-10-24 01:38
> What do you mean by include?

Apparently `package.include`, per a link from the URLO thread I linked: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields

**Comment by weihanglo** [comment] 2023-10-24 13:08
From my understanding, this is essentially a duplicate of #4587, as they all talk about keeping the default file change detection when adding a new `rerun-if-changed` instruction. The main difference is this one has brought the other solution — make `package.include` additive. While this could fix the original issue, it complicates the meaning of `package.include`. It mainly serves for `cargo package` and has a side effect on default rebuild detection coincidentally.

I think we should merge this into #4587 so we won't lose any bit of different possible solutions. Closing.

**Closed** 2023-10-24 13:08 UTC
Labels: A-build-scripts, A-manifest, S-needs-info
