### ISSUE TITLE
Warn when file are not imported in binary package

### ISSUE THREAD

**Issue by robinmoussu** [rust-lang/cargo#7648] opened 2019-12-02 22:22 UTC
Disclaimer: I am extremely new to rust (but not to programming). I am trying to describe a paint-point I encountered when starting with rust, and trying to find a way to solve it for future learners.

**Describe the problem you are trying to solve**
I created my first project. Then I created a new file `my_new_file.rs` with some unit tests inside. Since there was no `use my_new_file` in `main.rs` my unit tests weren't run with `cargo test`, and I didn't get any warning or any other clue that could have help me to understand the problem.

**Describe the solution you'd like**
I think that cargo should try to warn when unit tests exists but are not run.
The solution was quite simple (adding `use my_new_file` to `main.rs`), but it was surprising to have to search on internet for such a basic thing. Also I don't understand yet why it is needed since my researches weren't successful enough. This new warning should explain both the solution and the reasoning (or pointing to external documentation).

**Notes**
I don't have enough experience to know exactly what should trigger this warning. I think that if any files exists in a binary package but are not imported (with the `use` keyword) in `main.rs` is enough. Or maybe cargo should search in the `src/` directory for unit tests and warn when they are not executed when running `cargo test`.
If it leads to a lot of false positive, maybe cargo could have a global flag `--newbie` that would be activated by default unless deactivated in a global file (like in an hypothetic `~/.cargo/config`).

Also, if there is a website somewhere where I could report my paint-points as an early user, please tell me so. In maybe two/three weeks, it will be too late and I will not remember which wall hurt me.

**Comment by ehuss** [comment] 2019-12-03 16:47
Thanks for the report!  I'm going to close this as a duplicate of #3754, which is more or less the same.

This is a non-trivial problem because there is no static view of all files in use.  The compiler can discover most things, but idioms like `#cfg[(foo)] mod foo;` prevent discovering some usages.

**Closed by ehuss** 2019-12-03 16:47 UTC
Labels: C-feature-request
