### ISSUE TITLE
Allow to get both JSON output from Cargo and human output from rust

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3855] opened 2017-03-22 13:03 UTC
This definitely has come up before, but I've failed to find an issue, so I am creating one. 

The use case in IntelliJ is this: when building package before launching debugger, we need `--message-format=json` to get paths to the artifacts. At the same time, we need to show usual Cargo/Rustc output to the user.

~~~This is complicated by the fact that in `rustc`, both human and machine output goes to `stderr`.~~~ We already redirect rustc's json from stderr to stdout. 

In IntelliJ, the easy workaround would be just to launch cargo twice: once for human output, and once for JSON.

**Comment by Jascha-N** [comment] 2017-03-26 09:55
I would like to see this feature too. I'm creating a transparent wrapper around cargo and currently I also run the cargo commands twice. The problem is that not all cargo should be run twice, because of possible side effects (documentation opening twice with `doc --open`, crates being published twice, etc.).

**Comment by roblabla** [comment] 2019-06-17 10:33
I would also like this for cargo-travis. The reasoning is similar: we need the `--message-format=json` to get paths to the test artifacts, but we want to show the usual cargo output anyways. The current solution involves recreating the output ourselves, and that's kinda painful.

**Comment by ehuss** [comment] 2019-09-25 01:10
@matklad I think this is now supported via the `--message-format=json-render-diagnostics` flag hitting stable 1.38 in a few days ([docs](https://doc.rust-lang.org/beta/cargo/commands/cargo-build.html#cargo_build_display_options)).  Does that sufficiently cover the use case here to close this issue?

**Comment by matklad** [comment] 2019-09-25 05:25
Yeah, I think this can be closed now, seems like json-diagnostic-rendered-ansi might even be better for IntelliJ use case cc @mchernyavsky

**Closed** 2019-09-25 11:28 UTC
Labels: A-console-output, C-feature-request
