### ISSUE TITLE
cargo fix --edition-idioms emits broken code when fixing elided lifetimes in a macro that gets expanded more than once

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/cargo#7937] opened 2020-02-26 04:02 UTC
**Problem**

I am running `cargo fix --edition-idioms` on a 2018 edition codebase. This codebase contains a macro that takes a type name and implements `fmt::Display`. The signature for `fmt` in this impl does not include a lifetime on the formatter type.

`cargo fix` adds an explicit anonymous lifetime once for each invocation of the macro which results in `cargo fix` aborting with invalid code.

There are many errors that look like:

```
error[E0050]: method `fmt` has 3 parameters but the declaration in trait `std::fmt::Display::fmt` has 2
   --> artichoke-backend/src/extn/core/exception/mod.rs:349:20
    |
349 |             fn fmt(&self, mut f: &mut fmt::Formatter<'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_><'_>) -> fmt::Result {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters, found 3
...
395 | ruby_exception_impl!(ZeroDivisionError);
    | ---------------------------------------- in this macro invocation
    |
    = note: `fmt` from trait: `fn(&Self, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error>`
```

**Steps**

*Cargo.toml*:
```toml
[package]
name = "cargo_fix_2018"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

*src/main.rs*:
```rust
use std::fmt;

macro_rules! impl_display {
    ($s:ident) => {
        struct $s;

        impl fmt::Display for $s {
            fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
                write!(f, "{}", stringify!($s))
            }
        }
    };
}

impl_display!(Foo);
impl_display!(Bar);
impl_display!(Baz);
impl_display!(Quux);

fn main() {
    println!("Hello, world!");
}
```

1. `cargo fix --edition-idioms`

Results in this error:

```
cargo fix --edition-idioms
    Checking cargo_fix_2018 v0.1.0 (/Users/lopopolo/dev/repos/cargo_fix_2018)
warning: failed to automatically apply fixes suggested by rustc to crate `cargo_fix_2018`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error: expected one of `!`, `)`, `,`, or `::`, found `<`
  --> src/main.rs:8:53
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter<'_><'_><'_><'_>) -> fmt::Result {
   |                                                     ^ expected one of `!`, `)`, `,`, or `::` here
...
15 | impl_display!(Foo);
   | ------------------- in this macro invocation

error: expected one of `)`, `->`, `-`, `_`, `box`, `mut`, `ref`, `where`, `{`, identifier, or path, found `'_`
  --> src/main.rs:8:54
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter<'_><'_><'_><'_>) -> fmt::Result {
   |                                                      ^^ expected one of 11 possible tokens here
...
15 | impl_display!(Foo);
   | ------------------- in this macro invocation

error: aborting due to 2 previous errors

Original diagnostics will follow.

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
15 | impl_display!(Foo);
   | ------------------- in this macro invocation
   |
   = note: `-W elided-lifetimes-in-paths` implied by `-W rust-2018-idioms`

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
15 | impl_display!(Foo);
   | ------------------- in this macro invocation
   |
   = note: `-W elided-lifetimes-in-paths` implied by `-W rust-2018-idioms`

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
16 | impl_display!(Bar);
   | ------------------- in this macro invocation

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
16 | impl_display!(Bar);
   | ------------------- in this macro invocation

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
17 | impl_display!(Baz);
   | ------------------- in this macro invocation

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
17 | impl_display!(Baz);
   | ------------------- in this macro invocation

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
18 | impl_display!(Quux);
   | -------------------- in this macro invocation

warning: hidden lifetime parameters in types are deprecated
  --> src/main.rs:8:35
   |
8  |             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
   |                                   ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
...
18 | impl_display!(Quux);
   | -------------------- in this macro invocation
```

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

The issue is present on these cargos (the only ones I tested):

```
cargo 1.39.0 (1c6ec66d5 2019-09-30)
cargo 1.41.0 (626f0f40e 2019-12-03)
```

**Comment by ehuss** [comment] 2020-02-26 15:15
Thanks for the report!  I believe this is a duplicate of https://github.com/rust-lang/rust/issues/55768 so I'm going to close in favor of that.

**Closed by ehuss** 2020-02-26 15:15 UTC
Labels: C-bug
