### ISSUE TITLE
Can't enable a feature that only exists in a local Cargo override

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#3033] opened 2016-08-23 18:11 UTC
I have a local clone of servo/rust-mozjs, and I have added the path to Servo's .cargo/config. When I add `promises = ['mozjs_sys/promises']` to the clone's `features` section, then add `features = ["promises"]` to Servo's Cargo.toml entry for rust-mozjs, I get this error:

```
error: Package `js v0.1.3 (https://github.com/servo/rust-mozjs#755c8cc8)` does not have these features: `promises`
```

**Comment by alexcrichton** [comment] 2016-08-23 23:05
Yeah this is unfortunately just another limitation of path overrides, we should document it though!

**Comment by kellda** [comment] 2020-06-06 12:50
Looks like a duplicate of #2762, maybe either one can be closed ?

**Comment by kellda** [comment] 2020-06-06 14:45
Looks like a duplicate of #2582, maybe either one can be closed ?

**Closed** 2020-06-07 23:14 UTC
Labels: A-documenting-cargo-itself
