### ISSUE TITLE
Feature request: compile build.rs scripts in release mode even when doing a debug build

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/cargo#2424] opened 2016-03-01 17:42 UTC
Right now, `cargo build` compiles build.rs in debug mode, while `cargo build --release` compiles build.rs in release mode.  However build.rs scripts can potentially be very computationally intensive, and I would like the option to run my build.rs script in release mode even when doing a debug compile of the rest of my crate.

As a motivating example, nikomatsakis/[lalrpop](https://github.com/nikomatsakis/lalrpop) is a parser generator that does source generation during the custom build step.  Just the build.rs step takes 6m30s when compiling in debug, and 33s when compiling in release for a complex grammar.

**Comment by alexcrichton** [comment] 2016-03-01 18:46
cc @nikomatsakis 

I've certainly wanted this in the past as well. The tricky parts I can think of are:

* We need some sort of "nice syntax" for configuring this. We may not want to use `[profile]` as this may want to be a per-package instead of a per-application setting.
* It's not just the build script that needs to be optimized here, but also the dependencies. Sometimes the dependencies can be re-used with the original application, so we need to rationalize that as well.

**Comment by nikomatsakis** [comment] 2016-03-02 21:04
On Tue, Mar 01, 2016 at 10:46:06AM -0800, Alex Crichton wrote:
> cc @nikomatsakis 
> 
> I've certainly wanted this in the past as well. The tricky parts I can think of are:
> 
> * We need some sort of "nice syntax" for configuring this. We may not want to use `[profile]` as this may want to be a per-package instead of a per-application setting.
> * It's not just the build script that needs to be optimized here, but also the dependencies. Sometimes the dependencies can be re-used with the original application, so we need to rationalize that as well.

Yeah, I think the main reason I'd not yet opened an issue requesting
this was not having an answer to these questions. It's also unclear to
me what the defaults ought to be: I'd EXPECT that build.rs typically
wants to be "release by default", but I don't know.

I could also imagine this not being something that one configures, but
rather part of the `cargo build` command. e.g., perhaps build.rs
defaults always to a release build, but you can run `cargo build
--preprocessor debug` or something when you actually want to debug
your build.rs script.

**Comment by sfackler** [comment] 2016-03-03 17:17
The story for lalrpop is kind of interesting here. It's fairly expensive to compile, particularly in release mode (~minutes). For small grammars, total build script time is dominated by compiling lalrpop-snap, in which case you'd probably want a release build, but for larger grammars, the situation inverts and you really need an optimized version of lalrpop.

**Comment by TyOverby** [comment] 2016-03-03 17:45
> `cargo build --preprocessor debug` 

I'd rather not have this.  In the scenario where I have 

`user application` depends on `my library` which uses `lalrpop`

I'd like for `my library` to use a release preprocessor *always* because I know that the trade off is worth it for `my library`.  I don't want to have to tell people "oh, and if you depend on my library, you should really run `cargo build --preprocessor=release`.

**Comment by nikomatsakis** [comment] 2016-03-09 23:16
@TyOverby 

>  I don't want to have to tell people "oh, and if you depend on my library, you should really run cargo build --preprocessor=release. 

My proposal was that release would be the default. You would use debug if you knew you wanted to debug the build.rs script (which would presumably not be the common case). But the point is this is a decision that only the end-user is really in a position to make, not any particular dependency.

**Comment by nikomatsakis** [comment] 2016-03-09 23:17
@sfackler 

> The story for lalrpop is kind of interesting here. It's fairly expensive to compile, particularly in release mode (~minutes). 

I'd much rather always have release mode. Sure, the first compile is slow, but after that it doesn't change, so who cares? In general I feel like the first time I compile anything in cargo (or virtually any build system) it is slow, because it has to run off and grab a bunch of deps.

**Comment by TyOverby** [comment] 2016-03-09 23:44
@nikomatsakis Ok yeah, I agree with this.  Running build scripts in release sounds like a good default.

**Comment by alexcrichton** [comment] 2016-03-10 00:57
There's a few concerns I'd have about having a default release for build dependencies:

* If we still have the option to switch to debug mode, we still have the problem of inventing a syntax for such an operation. Arguably the same syntax at that point could be used for "this should be optimized"
* The problem of dependencies is sort of two-fold. A crate can be used both for a build script *and* for the final artifact generation. In this case do we optimize it or do we not? Unfortunately either choice we make can be the wrong choice depending on how you look at it.

**Comment by Nemikolh** [comment] 2016-03-10 08:20
Considering cross-compilation with cargo, isn't already a thing that build dependencies are compiled in a very different way than crate ones?

Having this scenario in mind, the fact that build script are compiled in release mode with the triplet target of the host is a default that make more sense than being similar to the crate parameter.

In case a crate is used for both dependencies, for a cross-compilation use case you would have to compile it twice anyway so it doesn't seems crazy.

**Comment by nikomatsakis** [comment] 2016-03-10 14:34
On Wed, Mar 09, 2016 at 04:57:18PM -0800, Alex Crichton wrote:
> * If we still have the option to switch to debug mode, we still have the problem of inventing a syntax for such an operation. Arguably the same syntax at that point could be used for "this should be optimized"

I contend that this is the wrong default -- I think the number of
people writing custom logic in their build.rs that they plan to debug
pales in comparison to the numbe of people injecting logic written by
others.

**That said,** it may be that the right fix here is to stop using
build.rs altogether. That is, maybe what we want is a way to declare a
"preprocess-dependency" that compiles and executes the crate as a
preprocessing step automatically, without the need for a user to write
their own `build.rs` script. We could then make the default for that
kind of dependency be release, and keep build.rs as it is today.

This also makes using LALRPOP, syntex, and other similar preprocessors
more ergonomic: you only have to add one line to Cargo.toml, instead
of following several distinct steps.

> * The problem of dependencies is sort of two-fold. A crate can be used both for a build script *and* for the final artifact generation. In this case do we optimize it or do we not? Unfortunately either choice we make can be the wrong choice depending on how you look at it.

My assumption was that the "build-dependencies" are distinct from the
"main" dependencies. That is, `build.rs` is a distinct target, so it's
not clear why it has (or should) to use the same build of the crate?

(Feels a lot like workspaces. :)

**Comment by alexcrichton** [comment] 2016-03-11 06:36
Yeah this may indeed be a different class of dependencies (preprocessors), but those also sound a lot like plugins...

When you're compiling for the host target (e.g. you didn't pass `--target`) then if the application depends on a a crate which is *also* depended on by a build script, we'll only compile that crate once (to avoid unnecessary compilations). I guess we could just decide to compile it twice though

**Comment by nikomatsakis** [comment] 2016-03-11 18:49
> Yeah this may indeed be a different class of dependencies (preprocessors), but those also sound a lot like plugins...

Is this surprising? I guess you're saying that adding something more "first class" than `build.rs` doesn't feel right to you, given that we will (eventually) have some kind of plugin system? I could understand that. I think it may well be that we continue to want "preprocessors" of the current form, which generate "all new" source rather than being triggered by some macro use embedded in a `.rs` file, but I'm not entirely sure about that. It's not clear why that would necessarily be better than some kind of `#![invoke_preprocessor]` attribute (or maybe even something that triggers automatically when given an `extern crate`).

**Comment by alexcrichton** [comment] 2016-03-11 21:31
Hm yeah I guess they're different enough to warrant different systems. Seems plausible as becoming a thing!

**Comment by jdub** [comment] 2016-10-08 03:40
Is the idea of a `host` profile for build dependencies ridiculously naive? The defaults could be same as the `release` profile, but you could change it however you like:

```
[profile.host]
opt-level = 1
debug = true
```

I would *love* to not rebuild all the host build dependencies when using other profiles.

**Comment by alexcrichton** [comment] 2016-10-10 15:26
@jdub that's plausible, yeah!  The only question would be what to do for a crate which needs to be compiled by the host profile *and* the target profile. My guess would be the target takes precedent, but in general doesn't matter too too much.

**Comment by tapeinosyne** [comment] 2016-11-18 20:26
I should like to offer another example: the [hyphenation](https://github.com/tapeinosyne/hyphenation) crate normalizes a corpus of UTF-8 text at build time, an operation that takes an order of magnitude longer in debug mode. This was cause of some perplexity upon first encounter.

Dependencies notwithstanding, for small libraries such as `hyphenation` the problem is easily remedied, but it would be nice to have a dedicated option.

**Comment by joshtriplett** [comment] 2017-01-27 21:17
For another example, see https://github.com/sfackler/rust-phf/issues/104 , which provides an example where PHF's perfect hash generation takes 685 seconds when compiled for debug, or ~16.8 seconds when compiled for release.

**Comment by alexcrichton** [comment] 2017-01-27 21:35
FWIW we don't really need any more examples of where this is helpful, it's clear that there's a well-motivated use case.

What we need now is a solution!

**Comment by nathanaeljones** [comment] 2017-03-10 22:16
There are also cases where `build.rs` depends on crates that take minutes to compile in release mode. 

Some way to turn the optimization level down a bit would greatly speed up the build. I've also found that `opt-level=1` can sometimes offer the best of both worlds.

**Comment by aturon** [comment] 2018-01-22 20:36
Possibly related to https://github.com/rust-lang/rfcs/pull/2282.

**Comment by Boscop** [comment] 2018-04-04 00:35
Any update on this? :)

**Comment by alercah** [comment] 2019-01-08 16:02
I believe RFC 2822 solves this feature request and this can be closed as a dupe of rust-lang/rust#48683.

**Comment by alexcrichton** [comment] 2019-01-08 17:45
Indeed!

**Closed by alexcrichton** 2019-01-08 17:45 UTC
Labels: A-build-scripts, A-profiles, C-feature-request, Needs design
