### ISSUE TITLE
Cargo dependency handling issue making builds longer than they should be

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#5677] opened 2018-07-03 00:59 UTC
During the Firefox build, we build a lot of crates, some of which take forever, expecially when doing LTO. But this is not what this issue is about. The problem we have is that for no apparent reason, some crates wait on other, unrelated ones. Specifically, building the `gkrust` crate never starts before `gkrust-gtest` is finished building, while there's no dependency relationship between both. `Cargo.lock` says this about those crates:

```
[[package]]
name = "gkrust"
version = "0.1.0"
dependencies = [
 "gkrust-shared 0.1.0",
 "stylo_tests 0.0.1",
]

[[package]]
name = "gkrust-gtest"
version = "0.1.0"
dependencies = [
 "gkrust-shared 0.1.0",
 "mp4parse-gtest 0.1.0",
 "nsstring-gtest 0.1.0",
 "xpcom-gtest 0.1.0",
]
```

Note this is happening on builds where `codegen-units` is explicitly set to 1, so this is not a case where there would be CPU congestion if both crates were building at the same time.

The new `--build-plan` flag that was recently added might be giving some light here: it shows the input list for the gkrust crate containing `toolkit/library/gtest/rust/Cargo.toml`, which seems like a red flag.

Cc: @alexcrichton @froydnj

**Comment by alexcrichton** [comment] 2018-07-05 18:59
Oh dear this sounds bad! @glandium could you gist the whole `Cargo.lock`? Also, would it be possible to minimize this a bit as well?

**Comment by glandium** [comment] 2018-07-05 23:41
The `Cargo.lock` is the one from mozilla-central.

**Comment by alexcrichton** [comment] 2018-07-06 14:48
Sorry I don't work much in mozilla-central so I don't know how to easily access the code nor where Cargo.lock is located in the code. Googling and poking around leads to https://dxr.mozilla.org/mozilla-central/source/Cargo.lock though.

With that I'm still not sure what's going on, so to look into this more I think it'll need to get minimized a bit more

**Comment by luser** [comment] 2018-07-12 16:13
Is this happening in the recursive make build? We invoke cargo once per-Cargo.toml file there, right? So once for `gkrust` and once for `gkrust-gtest`? If that's the case, I bet the problem is just that `gkrust-gtest` needs to wait for `gkrust-shared` to finish, but it winds up waiting for all of `gkrust` to finish.

**Comment by glandium** [comment] 2018-07-12 21:47
Oh right, there are two invocations of cargo, and cargo locks itself out of running twice in parallel. But while that explains the timeline we see when building Firefox currently, there still is something weird with the cargo build plan listing toolkit/library/gtest/test/Cargo.toml as an input to building gkrust.

**Comment by ehuss** [comment] 2018-07-12 22:03
> cargo build plan listing toolkit/library/gtest/test/Cargo.toml as an input to building gkrust.

I think that is normal.  `inputs` includes all manifests in a workspace (whether they are relevant or not), and both of those are members.

**Comment by glandium** [comment] 2018-07-12 22:08
So I guess there's no issue, then. Apart maybe that cargo uses a global lock, and that running it twice for different things in the same workspace makes it block entirely, instead of doing something more fine grained.

**Comment by ehuss** [comment] 2020-04-06 01:20
I'm closing as it seems like there isn't really an issue here.

**Closed by ehuss** 2020-04-06 01:20 UTC
