### ISSUE TITLE
Change `cargo check` defaults

### ISSUE THREAD

**Issue by scalexm** [rust-lang/cargo#6486] opened 2018-12-26 15:34 UTC
I was surprised to discover that a plain ` cargo check` is not actually equivalent to `cargo check —all-targets`, in contrast with e.g., `cargo fix`.

Since `cargo check` is usually very fast (compared to e.g., `cargo build`) I’m wondering whether plain uses should be equivalent to `cargo {check, fix} —all-targets`. What do you think?

**Comment by dwijnand** [comment] 2018-12-29 16:41
`cargo fix` is the outlier here, as I (mildly, in retrospect) contested in #5739, this discrepancy makes `cargo fix` irregular.

I disagree with making `cargo check` follow `cargo fix`'s lead and also become irregular, for instance with regards to `cargo build`.

... but I'll give others a chance to weigh in. 🙂

**Comment by scalexm** [comment] 2018-12-29 16:47
@dwijnand I think it would be ok to align `cargo fix` to `cargo check` (i.e. targeting only the main package), but then what about renaming `cargo check —all-targets` to simply `cargo check —all`? And renaming the current `—all` to `—all-packages` for example. I find it very confusing that `cargo check —all` does not check everything :)

**Comment by dwijnand** [comment] 2018-12-29 20:59
When you have multiple axes it can initially be confusing what "all" means.  Perhaps `--all` should've been for targets rather than packages in a workspace, I'm not sure, but I definitely think the ship has sailed a long time ago on that decision by now, I'm afraid.

**Comment by scalexm** [comment] 2018-12-30 15:05
Yeah you’re probably right that it might be too late for that.

Initially, I opened this issue because a few colleagues used to working with Go reported to me that rust tools were « less intuitive » that Go tools. Having worked very little with Go, I cannot tell whether these concerns come from a lack of goodwill or are genuine, and at which level the fact that Rust and Go being very different languages comes to play.

But I can tell how confusing it might be, when you want to check your tests, to start by typing `cargo check`, then trying `cargo check —all`, and finally having to parse `cargo check —help` to figure out how to actually check the tests. On the contrary, *building* and *running* your tests by just typing `cargo test` seems very intuitive.

I’ll let this issue open for a few days in case someone else wants to express their opinion, and close it if nothing more comes out.

**Comment by dwijnand** [comment] 2018-12-30 16:01
I'd be happy to hear feedback on how intuitive rust tools are.  What are the equivalents in go tools for "check/build/compile the test code"?

Rust also has so many different tests: library unit tests, library documentation example tests, integration tests, benchmark tests, examples...

**Comment by scalexm** [comment] 2018-12-30 16:38
I think there is no `go check` because compilation times are small, so I guess you just run `go build` every time? I’ll have to ask about that. But since tests in Go are part of the whole program’s package, `go build` does build them.

**Comment by dwijnand** [comment] 2019-01-02 12:05
That sounds like rust's library tests, which are checked with plain `cargo check`:

```rust
12:05:16 $ cargo check
    Checking t-cargo-compile-lib-test v0.1.0 (/s/t-cargo-compile-lib-test)
error: incorrect close delimiter: `}`
 --> src/lib.rs:6:5
  |
4 |     fn it_works() {
  |                   - close delimiter possibly meant for this
5 |         assert_eq!(2 + 2, 4
  |                   - un-closed delimiter
6 |     }
  |     ^ incorrect close delimiter

error: aborting due to previous error

error: Could not compile `t-cargo-compile-lib-test`.

To learn more, run the command again with --verbose.
```

**Comment by scalexm** [comment] 2019-01-03 18:34
@alexcrichton and what about changing `—all` to behave like the current `—all-targets`?

**Comment by alexcrichton** [comment] 2019-01-03 19:48
Those unfortunately mean different things. It may have been a mistake in naming but `--all` means "all packages" across all subcommands.

**Comment by scalexm** [comment] 2019-01-03 19:53
@alexcrichton Right, but I was thinking that going from « all packages » to actually « all targets » would:
* be more intuitive
* (I believe) not be a breaking change, people relying on `—all` to actually build all packages would just be building more things?

In parallel, a `—all-packages` option would be added (mapping the current behavior of `—all`, and eventually the `—all-targets` option would be deprecated.

**Comment by alexcrichton** [comment] 2019-01-04 16:35
I guess? Such a change would require at least an RFC though

**Comment by dwijnand** [comment] 2019-01-04 22:18
Oh.  I'd assumed it's too late even with an RFC.  In that case, I'd back such a proposal if you'd like to write one, @scalexm.

**Comment by epage** [comment] 2023-10-30 21:19
We've since shifted the focus from `--all` to `--workspace` though changing the meaning for `--all` would be a breaking change.

Considering the other use cases mentioned are working as intended, I'm going to go ahead and close this.

**Closed by epage** 2023-10-30 21:19 UTC
Labels: Command-check, C-feature-request
