### ISSUE TITLE
Command for specifically installing dev-dependencies

### ISSUE THREAD

**Issue by mcandre** [rust-lang/cargo#6196] opened 2018-10-20 21:40 UTC
* Hard build-time library dependencies like `json` can be specified as `[dependencies]`, to be installed when `cargo build` executes.
* Hard built-time dependencies like `thrift` can be specified as `[build-dependencies]`, to be installed when `cargo build` executes.
* Test-time dependencies like `quickcheck` can be specified as `[dev-dependencies]`, to be installed when `cargo test` executes.

But how about *soft* build-time dependencies like `cargo-script` supposed to be managed with `Cargo.toml`, that are not imported by any Rust code but still required for shell commands?

Could we get a cargo subcommand or flag to forcibly install all `[dev-dependencies]`, regardless of whether the dependency is referenced by an `extern crate` or not?

As a workaround, I am currently managing these kinds of development dependencies by manually executing `cargo install <dependency>`, but I would prefer to manage these with the same `Cargo.toml` file as everything else.

**Comment by autoferrit** [comment] 2020-01-12 21:24
Has there been any kind of feature added for this since this issue was opened?

**Comment by epage** [comment] 2023-10-24 20:12
This is a little confusing to read as its using terms from other ecosystems (you don't "install" dependencies).  I'm assuming what is wanted is the ability to make bin dependencies available.  In light of that, it appears to be a duplicate of issues like #5120 and #2267.   Closing in favor of those.  If there is a reason we should re-evaluate this, let us know!

**Closed by epage** 2023-10-24 20:12 UTC
Labels: Command-install, C-feature-request
