### ISSUE TITLE
Cargo installed two the same version of crates

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/cargo#2275] opened 2016-01-12 16:17 UTC
As of now i have;

```
> [master ≡]> cargo uninstall lazy-git-ext
There are multiple `lazy-git-ext` packages in your project, and the specification `lazy-git-ext` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/DoumanAsh/lazy-git-ext#1.0.0
  https://github.com/DoumanAsh/lazy-git-ext#1.0.0
```

Cargo 0.6.0 from Rust 1.5 stable
Crate installed from git

I'm not sure how exactly it happened.
I remember i had issue with re-installing crate, but not sure how i get rid of it previously.

**Comment by alexcrichton** [comment] 2016-01-12 17:01
Oh dear, definitely looks like something has gone awry, can you paste `$CARGO_HOME/.crates.toml`?

**Comment by DoumanAsh** [comment] 2016-01-12 19:26
>> cat .crates.toml
[v1]
"lazy-git-ext 1.0.0 (git+https://github.com/DoumanAsh/lazy-git-ext#24790565da2f0a8ab425fd0f9194db5cc0cb0ee5)" = ["git-ladd.exe", "git-lamend.exe", "git-lclean.exe", "git-lcommit.exe", "git-lpush.exe"]
"lazy-git-ext 1.0.0 (git+https://github.com/DoumanAsh/lazy-git-ext#3e0971cdb8574c9f2506b9c3f5979dfdae5f4387)" = ["git-ladd.exe", "git-lamend.exe", "git-lclean.exe", "git-lcommit.exe", "git-lpush.exe"]
"rustfmt 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt.exe", "rustfmt.exe"]

Well seems like i was able to make him add it twice :D

**Comment by alexcrichton** [comment] 2016-01-12 21:03
Hm that in theory shouldn't have been possible, it shouldn't be possible to install two versions of the same repo.

Do you remember how you installed `lazy-git-ext` to start out with?

**Comment by DoumanAsh** [comment] 2016-01-12 21:25
Not sure. But my guess maybe i deleted manually crate files without using cargo command?
I suppose cargo could not check index, but instead it could check existence of crate?

**Comment by DoumanAsh** [comment] 2016-01-12 21:32
Btw,

Could you please share help for uninstall?

> [master ≡]> cargo help uninstall
Invalid arguments.
Usage:
    cargo uninstall [options] <spec>

**Comment by alexcrichton** [comment] 2016-01-12 23:57
The help message was fixed in 3bbea9cb915ec930cbf53cd7dbd3260aa4299847, and Cargo should at least do something sensible in the face of this sort of toml file, but I'm not sure how Cargo ended up generating it in the first place unfortunately.

**Comment by DoumanAsh** [comment] 2016-01-13 06:01
Well i wanted to try reproduce it again, but i'd like you to share help message as i don't get how to delete these two crates....

**Comment by alexcrichton** [comment] 2016-01-13 17:30
Ah well for now you can just remove `.crates.toml` and the binaries, and you should then be able to reinstall everything

**Comment by DoumanAsh** [comment] 2016-01-13 17:49
Ok here is test case:
1) Install crate
2)Manually delete binaries
3)Re-install from commit with different sha.

It seems cargo thinks of it as different crate when at least sha of master branch is different.

**Comment by alexcrichton** [comment] 2016-01-14 07:17
Ah yes cargo should prevent the install because it already sees an existing one, if that's not happening it's a bug.

Thanks for the repro steps though!

**Comment by DoumanAsh** [comment] 2016-01-14 08:19
I would also suggest not to use commit's hash for name, only version should distinguish crate. It would strange to have some changes without version change also :)

But that's my opinion.

**Comment by dwijnand** [comment] 2018-12-09 10:54
I tried reproducing this and I think it's been solved.

I say "I think" because the first time I installed it (`cargo install --git https://github.com/dwijnand/lazy-git-ext.git`) it:
* added the `"lazy-git-ext 2.0.0 (git+https://github.com/dwijnand/lazy-git-ext.git#1fc59a7a7e640a2af7e146e2be0dbb77b67eb07e)" = ["git-add-all", "git-amend", "git-clean-all", "git-lazy", "git-lcommit", "git-root", "git-sync"]` to ~/.cargo/.crates.toml`
* told me it had installed the binaries in my `~/.cargo/bin`
* but it actually hadn't.

I continued the reproduction anyways, tweaked the README to get a new SHA and installed it the same (no need to delete the binaries as they weren't there).  That time it _did_ install the binaries, but it _didn't_ change the SHA in the `.crates.toml` (separate bug?), so the output said

```
   Compiling lazy-git-ext v2.0.0 (https://github.com/dwijnand/lazy-git-ext.git#2f11b093)
```

but `.crates.yaml` still says `1fc59a7a7e640a2af7e146e2be0dbb77b67eb07e`.

Given there was only one entry it uninstalled without issue:

```
11:48:53 $ cargo uninstall lazy-git-ext
    Removing /Users/dnw/.cargo/bin/git-add-all
    Removing /Users/dnw/.cargo/bin/git-amend
    Removing /Users/dnw/.cargo/bin/git-clean-all
    Removing /Users/dnw/.cargo/bin/git-lazy
    Removing /Users/dnw/.cargo/bin/git-lcommit
    Removing /Users/dnw/.cargo/bin/git-root
    Removing /Users/dnw/.cargo/bin/git-sync
```

So, personally, I'm inclinded to close this one.  But let me know what you think.

**Closed by dwijnand** 2018-12-09 10:54 UTC
Labels: C-bug, Command-install
