### ISSUE TITLE
regression: `cargo test` no longer passing `--extern plugin=...` flag to `rustdoc`

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#1521] opened 2015-04-13 22:56 UTC
### STR

On a new cargo project, add:

``` toml
# Cargo.toml
[package]
name = "foo"
version = "0.0.1"
authors = ["me"]

[dependencies]
debug_unreachable = "*"
```

``` rust
// src/lib.rs
#[macro_use]
extern crate debug_unreachable;
```

``` bash
$ cargo -V
cargo 0.0.1-pre-nightly (72c2e3d 2015-04-10) (built 2015-04-12)
$ cargo test --verbose
Running `rustdoc --test /home/japaric/tmp/foo/src/lib.rs --crate-name foo -L dependency=/home/japaric/tmp/foo/target/debug/deps --extern foo=/home/japaric/tmp/foo/target/debug/libfoo-17dca551ae82458f.rlib`
/home/japaric/tmp/foo/src/lib.rs:2:1: 2:32 error: can't find crate for `debug_unreachable`
/home/japaric/tmp/foo/src/lib.rs:2 extern crate debug_unreachable;
```

Compared to last week:

``` bash
$ cargo -V
cargo 0.0.1-pre-nightly (3499c8e 2015-04-05) (built 2015-04-05)
$ cargo test --verbose
Running `rustdoc --test /home/japaric/tmp/foo/src/lib.rs --crate-name foo -L dependency=/home/japaric/tmp/foo/target/debug/deps --extern debug_unreachable=/home/japaric/tmp/foo/target/debug/deps/libdebug_unreachable-aad5c32c36d9ddf5.so --extern foo=/home/japaric/tmp/foo/target/debug/libfoo-17dca551ae82458f.rlib`
```

**Comment by alexcrichton** [comment] 2015-04-14 01:18
I believe this is a dupe of #1512, but thanks!

**Closed by alexcrichton** 2015-04-14 01:18 UTC
