### ISSUE TITLE
Respect $PATH for tools like rustfmt

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/cargo#8225] opened 2020-05-08 13:19 UTC
Hello,

**Problem**

I'm just out of a long debugging session in the GitHub Actions CI. The `rustfmt` there did not behave in the same way as the `rustfmt` was locally, and this despite the fact that I was using `nix-shell --pure` to ensure that not a single environment variable was making it to `cargo` that I wouldn't have known of.

The issue was, that GitHub Actions apparently comes with a `~/.cargo/bin/rustfmt` preinstalled, and `cargo` preferred it to the one in `$PATH`.

While I understand that, usually, `~/.cargo/bin` should be tried before other folders, to make `rustup` behave like one would expect, I also don't understand why it's tried first even when it's not in `$PATH` -- `rustup` should just setup `$PATH` so that `~/.cargo/bin` comes first, and then `cargo` would just rely on `$PATH` instead of disregarding the end-user's choice.

**Possible Solutions**

One of:
- Make `cargo` respect the `$PATH` (and `rustfmt` prepend to `$PATH` to keep the current behavior, if it is not already the case), or
- Work around it by having a `rm -r ~/.cargo/bin` at the beginning of the CI script -- this doesn't work for eg. cases where I'd want to usually use rustup, but when working on some specific projects only use the $PATH-provided rustfmt.

**Notes**

Output of `cargo version`:
`cargo 1.43.0-nightly (bda50510d 2020-03-02)`

**Comment by ehuss** [comment] 2020-05-08 13:48
Sorry, I'm having a little bit of trouble understanding the issue here. If the issue is that `cargo fmt` prefers `$CARGO_HOME/bin/cargo-fmt`, then that sounds like #6507. If it is that `$CARGO_HOME/bin` is first in `$PATH`, that sounds like https://github.com/rust-lang/rustup/issues/2017.

**Comment by Ekleog** [comment] 2020-05-08 15:29
The issue is indeed that `cargo fmt` prefers `~/.cargo/bin/cargo-fmt` to `$PATH`. However, this also happens when `CARGO_HOME` is not set at all, so I'm not sure it's the same issue? IOW, while I'd be surprised if fixing #6507 didn't fix this issue, this issue could maybe be fixed without fixing #6507 (not sure it'd be something desirable, though).

Feel free to close as a duplicate of #6507, if it's the preferred way to go! I've just subscribed to it too, having not found it while initially searching, most likely due to my searching for `rustfmt` instead of `cargo-fmt` :)

**Comment by ehuss** [comment] 2020-05-08 16:17
`CARGO_HOME` defaults to `.cargo` in your home directory, I was just using that as a shorthand.

Closing as a duplicate of #6507.

**Closed by ehuss** 2020-05-08 16:17 UTC
Labels: C-bug
