### ISSUE TITLE
Spurious rebuild in crate repo with workspace

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/cargo#5262] opened 2018-03-29 19:07 UTC
After clone and `cargo build` with latest nightly of rust:
```
~/Desktop/rust/cargo-local-serve $ cargo build
   Compiling all_crates_storage v0.1.0 (file:///home/aidanhs/Desktop/rust/cargo-local-serve/all_crates_storage)
warning: unused variable: `e`
  --> all_crates_storage/bin/download-all-crates.rs:88:9
   |
88 |                 Err(e) => {
   |                     ^ help: consider using `_e` instead
   |
   = note: #[warn(unused_variables)] on by default

warning: variable does not need to be mutable
  --> all_crates_storage/bin/download-all-crates.rs:60:6
   |
60 |     let mut ctr = 0;
   |         ----^^^
   |         |
   |         help: remove this `mut`
   |
   = note: #[warn(unused_mut)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 3.50 secs
~/Desktop/rust/cargo-local-serve $ cargo build -p all_crates_storage --bin download-all-crates
   Compiling all_crates_storage v0.1.0 (file:///home/aidanhs/Desktop/rust/cargo-local-serve/all_crates_storage)
warning: unused variable: `e`
  --> all_crates_storage/bin/download-all-crates.rs:88:9
   |
88 |                 Err(e) => {
   |                     ^ help: consider using `_e` instead
   |
   = note: #[warn(unused_variables)] on by default

warning: variable does not need to be mutable
  --> all_crates_storage/bin/download-all-crates.rs:60:6
   |
60 |     let mut ctr = 0;
   |         ----^^^
   |         |
   |         help: remove this `mut`
   |
   = note: #[warn(unused_mut)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 3.46 secs
```

i.e. it seems to be building twice for some reason? After the second build it's then happy that both are built.

**Comment by matklad** [comment] 2018-03-29 19:22
Duplicate of https://github.com/rust-lang/cargo/issues/4463.

**Closed by matklad** 2018-03-29 19:22 UTC
