### ISSUE TITLE
Add a flag to `cargo test` to compile & run only doctests

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#1864] opened 2015-08-01 11:34 UTC
When modifying the documentation of a library, it can be useful to run only the doctests.

There's already `--test`, `--lib` and `--bin`, but nothing to run only the doctests (and `--lib` doesn't run doctests).

**Comment by alexcrichton** [comment] 2015-08-03 16:39
Duplicate of https://github.com/rust-lang/cargo/issues/1789, but I definitely like the idea!

**Closed by alexcrichton** 2015-08-03 16:39 UTC
