### ISSUE TITLE
OPT_LEVEL environment variable isn't being passed to build script

### ISSUE THREAD

**Issue by awelkie** [rust-lang/cargo#1226] opened 2015-01-25 21:30 UTC
I have a dummy C file called "some_c.c" and a build script called "build.rs" that uses the `gcc` crate to compile "some_c.c". When I call `cargo bench`, the build script is run but the environment varible "OPT_LEVEL" is set to "0" in build.rs. I expected that to be set to "3" (for the default bench profile). Here's the call to `rustc` that Cargo generates:
```
➤ cargo bench --verbose
unused manifest key: package.link
   Compiling gcc v0.1.6
     Running `rustc /home/allen/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.6/src/lib.rs --crate-name gcc --crate-type lib -C opt-level=3 --cfg ndebug -C metadata=46e0c3c1c2bb4e55 -C
 extra-filename=-46e0c3c1c2bb4e55 --out-dir /home/allen/scratch/optimize/target/release/deps --emit=dep-info,link -L dependency=/home/allen/scratch/optimize/target/release/deps -L dependency=/ho
me/allen/scratch/optimize/target/release/deps -Awarnings`
   Compiling optimize v0.0.1 (file:///home/allen/scratch/optimize)
     Running `rustc build.rs --crate-name build-script-build --crate-type bin -C prefer-dynamic -g --out-dir /home/allen/scratch/optimize/target/release/build/optimize-f17e68d5655bb0cc --emit=de
p-info,link -L dependency=/home/allen/scratch/optimize/target/release -L dependency=/home/allen/scratch/optimize/target/release/deps --extern gcc=/home/allen/scratch/optimize/target/release/deps
/libgcc-46e0c3c1c2bb4e55.rlib`
     Running `/home/allen/scratch/optimize/target/release/build/optimize-f17e68d5655bb0cc/build-script-build`
     Running `rustc src/lib.rs --crate-name optimize --crate-type lib -C opt-level=3 --cfg ndebug --test -C metadata=adf5aa9d53c2e2e7 -C extra-filename=-adf5aa9d53c2e2e7 --out-dir /home/allen/sc
ratch/optimize/target/release --emit=dep-info,link -L dependency=/home/allen/scratch/optimize/target/release -L dependency=/home/allen/scratch/optimize/target/release/deps -L native=/home/allen/
scratch/optimize/target/release/build/optimize-f17e68d5655bb0cc/out -l static=some_c`
     Running `rustc src/lib.rs --crate-name optimize --crate-type lib -C opt-level=3 --cfg ndebug -C metadata=f17e68d5655bb0cc -C extra-filename=-f17e68d5655bb0cc --out-dir /home/allen/scratch/o
ptimize/target/release --emit=dep-info,link -L dependency=/home/allen/scratch/optimize/target/release -L dependency=/home/allen/scratch/optimize/target/release/deps -L native=/home/allen/scratch
/optimize/target/release/build/optimize-f17e68d5655bb0cc/out -l static=some_c`
     Running `/home/allen/scratch/optimize/target/release/optimize-adf5aa9d53c2e2e7 --bench`
```

As you can see, there is no "opt-level=3" in the second invocation of `rustc`.

**Comment by alexcrichton** [comment] 2015-01-26 08:23
I believe that this is a dupe of https://github.com/rust-lang/cargo/issues/1058, but thanks for the issue!

**Closed by alexcrichton** 2015-01-26 08:23 UTC
