### ISSUE TITLE
cargo can't update the registry if git-alias available

### ISSUE THREAD

**Issue by miqlas** [rust-lang/cargo#4522] opened 2017-09-22 07:28 UTC
Testing Rust on Haiku got this error:

```
/P/T/ripgrep-0.6.0  cargo --version
cargo 0.23.0-dev
/P/T/ripgrep-0.6.0  ls -la /system/packages/*rust*
-rw-r--r-- 1 user root 29584801 M09 22 08:59 /system/packages/rust_runtime-1.22~dev-1-x86_64.hpkg
-rw-r--r-- 1 user root 66276111 M09 22 09:00 /system/packages/rust-1.22~dev-1-x86_64.hpkg
/P/T/ripgrep-0.6.0  cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [23/-1] Failed to start SSH session: Failed getting banner
/P/T/ripgrep-0.6.0    
```

The culpriont was my git config file, better to say the aliases. I got this in my git config:

```
[user]
	email = itsme@myemailaddress.com
	name = Itsme
[pack]
	threads = 4
[url "git@github.com:"]
	insteadOf = https://github.com/
[url "git://github.com/ghc/packages-"]
	insteadOf = git://github.com/ghc/packages/
[url "http://github.com/ghc/packages-"]
	insteadOf = http://github.com/ghc/packages/
[url "https://github.com/ghc/packages-"]
	insteadOf = https://github.com/ghc/packages/
[url "ssh://git@github.com/ghc/packages-"]
	insteadOf = ssh://git@github.com/ghc/packages/
[url "git@github.com:/ghc/packages-"]
	insteadOf = git@github.com:/ghc/packages/
[cola]
	fontdiff = Noto Mono,10,-1,5,50,0,0,0,0,0
	blameviewer = lpe
[gui]
	editor = lpe
	historybrowser = lpe
```

If i delete the aliases cargo starts to working. My working git config:

```
[user]
	email = itsme@myemailaddress.com
	name = Itsme
[pack]
	threads = 4
[gui]
	editor = lpe
	historybrowser = lpe
```

And now cargo fetches everything happily.

**Comment by alexcrichton** [comment] 2017-09-22 14:32
Thanks for the report! I think this is a duplicate of https://github.com/rust-lang/cargo/issues/2078, however

**Closed by alexcrichton** 2017-09-22 14:32 UTC
