### ISSUE TITLE
no separate caching for target/host

### ISSUE THREAD

**Issue by davemilter** [rust-lang/cargo#7822] opened 2020-01-23 16:45 UTC
**Problem**

I compile for PC and "Raspberry PI 3" from the same sources,
every time I change target it recomiples from scratch all dependicies what is very strange,
because of data in separate directories:
target/debug
and
target/armv7-unknown-linux-gnueabihf/debug

**Steps**

1. build/check two times 
[myapp.zip](https://github.com/rust-lang/cargo/files/4104253/myapp.zip)
crate in attachment. 
```
cargo check
cargo check
```
2. Cross-compile it
```
cargo check --target=armv7-unknown-linux-gnueabihf
cargo check --target=armv7-unknown-linux-gnueabihf
```
3. Recompile for host again:
```
cargo check
```
and you see that cache for host is gone and `cargo` rebuild all from scratch.

**Notes**

Output of `cargo version`:
cargo 1.40.0 (bc8e4c8be 2019-11-22)

This is happens only if rppal used as dependency, but any way why armv7-unknown-linux-gnueabihf and my host (x86_64-unknown-linux-gnu) can interfere to each other?

rustc 1.40.0 (73528e339 2019-12-16) / linux / amd64, stable installed via rustup.

**Comment by ehuss** [comment] 2020-01-23 17:13
Hm, I'm unable to reproduce your example.  Can you run with the `CARGO_LOG=cargo::core::compiler::fingerprint=trace` environment variable? It should print some debug information explaining why Cargo thinks it needs to be rebuilt.

**Comment by davemilter** [comment] 2020-01-23 17:56
@ehuss 

I find out culprit: 

```sh
$ cat ~/.cargo/config 
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=gold"]
```

If I remove **~/.cargo/config** from my home directory caching starts work,
if I return it back then every target change cause rebuild from scratch.

Have no idea why change of linker for x86_64 breaks cargo caching though.

**Comment by ehuss** [comment] 2020-01-23 19:08
Ah.  The reason is that when using the `--target` flag, rustflags are not included for build scripts.  However, without the `--target` flag, Cargo will include the rustflags for build scripts.  This causes the `libc` build script to switch to being built with and without the flag based on whether or not the `--target` flag is passed.  There are a variety of issues that cover this (#6375, and those linked there).

**Comment by ehuss** [comment] 2020-02-02 23:47
I'm going to close this as it seems like the problem was figured out, and there are other issues tracking handling of RUSTFLAGS.

**Closed by ehuss** 2020-02-02 23:47 UTC
Labels: C-bug
