### ISSUE TITLE
cargo cannot handle long paths on windows everywhere

### ISSUE THREAD

**Issue by jessesna** [rust-lang/cargo#10197] opened 2021-12-13 11:47 UTC
### Problem

I'm trying to execute cargo publish and the process fails with a 

```
error: failed to verify package tarball

Caused by:
  failed to remove file `..........\build_script_build-1355d04cfd9a6cb5.build_script_build.b1cedc92-cgu.0.rcgu.o`

Caused by:
  The system cannot find the path specified. (os error 3)
```

The path is 261 characters long.
The actual problem is the [Maximum Path Length Limitation](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd) which can easily be avoided by using the magic `"\\?\"` prefix.

### Steps

1. create or copy any project to a location where it itself is closely below the MAX_PATH limit and try to publish

### Possible Solution(s)

Use the magic `"\\?\"` prefix for all paths on windows

### Notes

[Long Paths can be globally enabled in Windows 10, Version 1607, and Later](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later) but this is a somewhat intrusive method which can break other applications.

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:Schannel)
os: Windows 10.0.19044 [64-bit]
```

**Comment by ehuss** [comment] 2021-12-13 18:04
Sorry you're running into trouble with the long paths. Unfortunately this isn't a particularly easy thing to fix universally. I'm going to close as a duplicate of #9770 and the issues linked therein.

**Closed by ehuss** 2021-12-13 18:04 UTC
Labels: C-bug
