### ISSUE TITLE
Cargo test makes gtk application crash on OSX

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/cargo#5438] opened 2018-04-28 23:57 UTC
Sorry but I can't get much information out of the run:

```
cargo test
   Compiling gtk-test v0.1.0 (file:///Users/imperio/rust/gtk-test)
    Finished dev [unoptimized + debuginfo] target(s) in 2.33 secs
     Running target/debug/deps/gtk_test-663922f61f003d55

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/basic-4ecdfe72bcff51e8

running 1 test

(process:1424): Gtk-WARNING **: 01:56:43.472: Locale not supported by C library.
	Using the fallback 'C' locale.
error: process didn't exit successfully: `/Users/imperio/rust/gtk-test/target/debug/deps/basic-4ecdfe72bcff51e8` (signal: 11, SIGSEGV: invalid memory reference)
```

It runs perfectly fine when the test code is moved inside a `main` and then run with `cargo run` but it just crashes without reason otherwise...

**Comment by antoyo** [comment] 2018-04-28 23:59
I guess this is [this test](https://github.com/GuillaumeGomez/gtk-test/blob/master/tests/basic.rs).

**Comment by ehuss** [comment] 2018-04-29 01:32
I'd suspect the issue is this:

> The thread where init was called is considered the main thread. OS X has its own notion of the main thread and init must be called on that thread.

AFAIK, you cannot limit libtest to the main thread.

Setting `harness=false` in Cargo.toml, and rewriting your test to be `fn main` makes it pass for me.

**Comment by GuillaumeGomez** [comment] 2018-04-29 09:45
That is what we thought then. Can't we set this behavior as default on OSX in cargo?

**Comment by matklad** [comment] 2018-04-29 09:58
A random idea, but wouldn’t passing test-threads=1 help? By default, tests are multithreaded, so defaulting to main thread on macos does not make sense.

**Comment by ehuss** [comment] 2018-04-29 15:08
> wouldn’t passing test-threads=1 help

It still spins up 1 thread off main to run the tests on.  Not sure if that's fixable (see a very old discussion [here](https://github.com/rust-lang/rust/issues/9373#issuecomment-26475878)).

**Comment by GuillaumeGomez** [comment] 2018-04-29 15:09
Well, it does help in a way since it allows to avoid GTK context conflicts. But that doesn't solve the issue on OSX. I'll just add explanations about this in the README and hope that people will add `harness = false`.

**Comment by dwijnand** [comment] 2019-01-13 10:14
Is it possible to move forward with this ticket in cargo, or should we just close it?

**Closed** 2019-01-13 11:46 UTC

**Comment by ehuss** [comment] 2019-01-13 15:34
There was a recent change (#56243) so that libtest will not spawn a thread when concurrency is set to 1.  That may be good enough.
