### ISSUE TITLE
changing directory results in full rebuild

### ISSUE THREAD

**Issue by kirillkh** [rust-lang/cargo#2542] opened 2016-04-03 16:32 UTC
I'm using a recent nightly Rust version on Windows (10 x64).

The issue that I'm seeing is that "cd myproject;cargo build" followed by "cd src;cargo build" will result in full recompile, including dependencies. I think it has happened with all previous versions of Rust/Cargo that I tried.

P.S. This might be related to the fact that building from rustdt followed by building from console will result in full rebuild (and vice versa).

**Comment by alexcrichton** [comment] 2016-04-04 18:05
Thanks for the report! Could you provide some more information like:

* What version of Rust are you using?
* What version of Cargo are you using?
* What dependencies are you using?

Unfortunately I haven't been able to reproduce locally :(

**Comment by kirillkh** [comment] 2016-04-04 18:09
rustc 1.9.0-nightly (d7a71687e 2016-03-24)
cargo 0.10.0-nightly (4e6434d 2016-03-24)

You can try my project at https://github.com/kirillkh/xword_constructor, but it happens with all my Rust projects.

**Comment by alexcrichton** [comment] 2016-04-04 18:32
Hm unfortunately I still can't reproduce (even with the same versions). Could you try running with `RUST_LOG=cargo::ops::cargo_rustc::fingerprint` and gist the output?

**Comment by kirillkh** [comment] 2016-04-04 18:45
I tried again, and I can no longer reproduce it. It definitely has happened at the past, but now I'm suddenly not sure that I rechecked it before opening the bug.

It still does happen with rustdt though (which may have confused me). Posting that log instead.
https://gist.github.com/kirillkh/25585c8fe8026c0cda905152fcf7e9b6

**Comment by alexcrichton** [comment] 2016-04-04 20:18
Are you alternating between `cargo build --release` and `cargo build` or something like that? Or are `Cargo.toml` profile settings changing? The reason for recompiling is "target configuration has changed" in all those messages which means that something like the flags has changed.

**Comment by kirillkh** [comment] 2016-04-04 21:19
I obtained the log as follows:
1. build the project in Eclipse (using rustdt)
2. run "RUST_LOG=cargo::ops::cargo_rustc::fingerprint  cargo build" from console

I made no changes between the two steps.

**Comment by alexcrichton** [comment] 2016-04-05 00:38
Hm it definitely sounds like something suspicious is going on. Do you know if there's a way to see exactly what rustdt is executing in terms of processes and logs? I've tried a few possible variations locally and unfortunately can't reproduce.

Also, are you sure that rustdt and the command line are using the same compiler?

**Comment by kirillkh** [comment] 2016-04-05 00:45
This is the only log I could find. I tried to read rustdt source code, but it's incredibly complex, very hard to analyze just by reading.

Definitely same compiler.

**Comment by alexcrichton** [comment] 2016-04-06 00:40
And you're *sure* that the same Cargo is being used in both cases as well? A good way to verify is to ensure that only one is installed locally

**Comment by kirillkh** [comment] 2016-04-06 02:33
I have only one installed locally and I have checked the path to cargo.exe in the settings of rustdt.

**Comment by alexcrichton** [comment] 2016-04-06 17:03
Sorry but I'm running out of ideas :(. It may help to try to add some debugging locally to figure out what rustdt is doing, though?

**Comment by kirillkh** [comment] 2016-05-14 16:33
Found a way to reproduce it outside of rustdt.
1) start cmd.exe, navigate to project root, run "cargo build"
2) run "sh -c 'cargo build'"

**Comment by alexcrichton** [comment] 2016-05-16 17:34
Interesting! Does the fingerprint log still contain something like:

```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for rustc_version v0.1.7: target configuration has changed
```

And if so, you're still sure that rustc is the same in both contexts? It may have something to do with path names, but I'm not 100% sure where that difference would come from...

**Comment by kirillkh** [comment] 2016-05-16 17:40
Here is a fresh fingerprint log: https://gist.github.com/kirillkh/a54d0883e02273f6568fc942b364953b

I am using the same rustc.

**Comment by alexcrichton** [comment] 2016-05-16 18:45
Would you be able to build Cargo locally and test out a patch? I'm curious what's going on here...

**Comment by kirillkh** [comment] 2016-05-16 18:56
Sure.

**Comment by alexcrichton** [comment] 2016-05-17 16:08
Ok, can you try apply this patch: https://gist.github.com/alexcrichton/75112eab2324f0e99e987d9272452f6e

and gist the output of both before and after a rebuild? (with the fingerprint log active)

**Comment by kirillkh** [comment] 2016-05-17 16:16
Build fails for me. https://gist.github.com/kirillkh/d3467c17a02476208a7e321c3f87a830

**Comment by alexcrichton** [comment] 2016-05-17 16:23
Looks like you may be using the wrong mingw shell by accident?

**Comment by kirillkh** [comment] 2016-05-17 16:45
I don't have any other shell :)

**Comment by kirillkh** [comment] 2016-05-17 17:07
You're right, I was using the 32-bit toolchain by mistake (I think). Let me try and build now...

**Comment by kirillkh** [comment] 2016-05-17 17:32
Now it's failing with this: https://gist.github.com/kirillkh/92a66f218bc9ed5a05072d3d9dca0016

**Comment by alexcrichton** [comment] 2016-05-17 19:43
Could you provide the full logs? That looks like it may be an unrelated error

**Comment by alexcrichton** [comment] 2016-05-17 19:43
Er rather, it looks like half the error

**Comment by kirillkh** [comment] 2016-05-17 19:46
I ran "cargo clean", and now it's a new error!
https://gist.github.com/kirillkh/ef9c5e27f15594b4c7f37ca0dbfa3a2f

This time it fails before reaching the linking stage, which probably means something I did with the system broke it... I did upgrade msys packages in attempt to fix previuos problems.

Fun fun fun.

**Comment by kirillkh** [comment] 2016-05-17 20:44
Well, I managed to sort it out... I was starting the msys2 console with MSYSTEM=MSYS, and it was conflicting with the mingw64 toolchain. Starting it with MSYSTEM=MINGW64 fixed it.

But now I have another problem. I can't start the built cargo.exe from cmd.exe, it complains about missing dlls (libcurl-4.dll, libssh2-1.dll). I have those dlls in the mingw64 distribution, but then seem to be of incompatible versions. I suppose cargo builds its own versions, but I am not able to find them in the target directory.

**Comment by kirillkh** [comment] 2016-05-17 20:50
Not sure how helpful it is, but here's the log: https://gist.github.com/kirillkh/fd0645f5c99182a92f528dc3db6a90db

**Comment by kirillkh** [comment] 2016-05-17 21:17
All right, managed to get it working (a conflicting dll was on the Windows PATH).
https://gist.github.com/kirillkh/420ef904acced8dfbc690dcf1ba9b013

**Comment by alexcrichton** [comment] 2016-05-17 22:24
Nice! To clarify, those last two logs are the logs for cargo in each context? e.g., something like:

```
$ cargo build > log1.txt
$ sh -c 'cargo build' > log2.txt
```

**Comment by kirillkh** [comment] 2016-05-18 00:07
The last log is what you called log2.txt. The previous log you should probably ignore, as it was obtained with an older cargo version.

**Comment by kirillkh** [comment] 2016-05-18 00:27
Let me do it all over again. I do the following:
1. sh -c '<cargo_dir>/target/release/cargo build'
2. "<cargo_dir>\target\release\cargo build"  => log1.txt
3. "sh -c '<cargo_dir>/target/release/cargo build'" => log2.txt

log1.txt: https://gist.github.com/kirillkh/5f65af824c620cf5ab8155c7f1de1bb9
log2.txt: https://gist.github.com/kirillkh/b89ead4b087f0ff98b727951577e9d1e

**Comment by alexcrichton** [comment] 2016-05-18 00:30
Is there perhaps something special with your H: drive? The two shells are disagreeing on that path to this file:

log1.txt contains "C:\\Users\\kirillkh\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\rustc_version-0.1.7\\src\\lib.rs"

log2.txt contains  rustc_version v0.1.7 -- Target { kind: Lib([Lib]), name: "rustc_version", src_path: 
"H:\\devel\\MinGW\\msys\\home\\kirillkh\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\rustc_version-0.1.7\\src\\lib.rs"

**Comment by kirillkh** [comment] 2016-05-18 00:31
It's a regular NTFS drive. C:\Users\kirillkh\.cargo is a totally different directory from H:\devel\MinGW\msys\home\kirillkh\.cargo

**Comment by alexcrichton** [comment] 2016-05-18 00:34
Oh gah of course! This should actually have been fixed by https://github.com/rust-lang/cargo/pull/2681 as Cargo should use the same cache in both instances. How convenient!

**Closed by alexcrichton** 2016-05-18 00:34 UTC

**Comment by kirillkh** [comment] 2016-05-18 00:35
Well, I checked out a fresh git version for testing it, so it is not fixed as of earlier today.

**Comment by alexcrichton** [comment] 2016-05-18 00:39
You may want to try deleting the old location in `H:` first as it's prioritized if it exists

**Comment by kirillkh** [comment] 2016-05-18 00:40
Right, that fixed it.
