### ISSUE TITLE
crate home MSRV bumped in "compatible version"

### ISSUE THREAD

**Issue by tisonkun** [rust-lang/cargo#14944] opened 2024-12-17 13:16 UTC
### Problem

```
error: rustc 1.80.0 is not supported by the following package:
  home@0.5.11 requires rustc 1.81
```

I have this dependency in `cargo.toml`:

```toml
home = "0.5.9"
```

Such breaking changes deserve 0.6.0.

### Steps

<img width="944" alt="Image" src="https://github.com/user-attachments/assets/c7e4821b-5474-4cba-93c7-9bcdcaf62ddb" />

### Possible Solution(s)

yank 0.5.11 and release 0.6.0

### Version

```text

```

**Comment by tisonkun** [comment] 2024-12-17 13:22
cc @ehuss

**Comment by epage** [comment] 2024-12-17 13:41
MSRV bumps are generally recognized as minor, not major changes, see https://doc.rust-lang.org/nightly/cargo/reference/semver.html#env-new-rust

**Comment by epage** [comment] 2024-12-17 13:56
We previously discussed this in #13270. Per that discussion, I'm closing this.

**Comment by tisonkun** [comment] 2024-12-17 13:57
> MSRV bumps are generally recognized as minor, not major changes, see https://doc.rust-lang.org/nightly/cargo/reference/semver.html#env-new-rust

This is reasonable, while I'd ask a bit details on cargo's mechanism.

When I specify "foo = 1.2", will it gets auto resolved to 1.3.x? That is, when I specify "home = 0.5.9", it could be resolved to "home = 0.5.11". But if we specify "foo = 1.2", it would resolves to 1.2.x?

If so, then "minor changes" means different things in these two situations.

**Closed** 2024-12-17 13:56 UTC
Labels: C-bug, S-triage

**Comment by tisonkun** [comment] 2024-12-17 13:59
That said, you can bump MSRV when bump 1.2 to 1.3, and build won't break with the most common dependency string. But from 0.5.9 to 0.5.11 does.

**Comment by tisonkun** [comment] 2024-12-17 14:01
I see https://doc.rust-lang.org/nightly/cargo/reference/resolver.html#semver-compatibility

```
bitflags = "1.1"  # meaning `>=1.1.0,<2.0.0`
```

Then I'm fine with Rust's definition now .. let me see how to get used to it.

**Comment by epage** [comment] 2024-12-17 14:07
`foo = "1.2"` means `foo = ">=1.2.0,<2.0.0"`.

Build environment changes are not usually included in semver in Rust. If not, Rust itself would be on v20 or so with glibc, AndroidNDK, Linux Kernel, etc changes. Foundational crates like `serde` could never change their MSRV. Builds would be slower due to the duplication of dependencies. Users with higher MSRV can be stuck on old, buggy, less featureful versions of their transitive deps because one dep has a lower MSRV.

In 1.84 we'll have an opt-in MSRV-aware resolver. You can have it generate your lockfile and than use whatever version of Cargo you want.

**Comment by tisonkun** [comment] 2024-12-17 14:10
> In 1.84 we'll have an opt-in MSRV-aware resolver. You can have it generate your lockfile and than use whatever version of Cargo you want.

Cool! Is there a tracking issue I can watch on?

**Comment by weihanglo** [comment] 2024-12-17 14:14
* https://github.com/rust-lang/cargo/issues/9930
* https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#msrv-aware-resolver

**Comment by weihanglo** [comment] 2024-12-17 14:18
> This was stabilized in 1.83 in [#14639](https://github.com/rust-lang/cargo/pull/14639).

Hum… the version [here](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#msrv-aware-resolver) seems wrong, @epage ?

**Comment by Ari-suhyeon** [comment] 2024-12-18 12:28
The sudden version restriction is causing problems with my builds too. 
The problem is that it's not easy to find which crate has which dependencies...
Debug works fine, release doesn't. 
Does anyone know how to fix it?

**Comment by weihanglo** [comment] 2024-12-18 13:20
> The problem is that it's not easy to find which crate has which dependencies...

`cargo tree -i home` could help.
See <https://doc.rust-lang.org/nightly/cargo/reference/features.html#inspecting-resolved-features>.

> Does anyone know how to fix it?

`cargo update home --precise 0.5.9`. See also <https://github.com/harryfei/which-rs/pull/103#issuecomment-2548564127>

**Comment by Ari-suhyeon** [comment] 2024-12-18 14:12
I don't use the home crate directly.
Of course I have used the `cargo tree -i home` command, but it only specifies home v0.5.9.
I use polars and kube-rs, and those crates also specify v0.5.9.
I am building docker, and the image uses FROM rust:1.78.0-slim.

**Comment by Ari-suhyeon** [comment] 2024-12-19 04:43
I've identified the cause.
(The dependency was created because kube-client and polars are using home crate)
When I do a Docker build, the Cargo.lock file doesn't exist, so you create it and build it.
In the existing Cargo.lock file on my local PC, the home version was specified as '0.5.9', so it worked fine, but when I built without the lock file, it was changed to '0.5.11' and the lock file was created.
It seems that 0.5.9 and 0.5.11 are compatible according to SemVer compatibility, so it changes to 0.5.11.
https://doc.rust-lang.org/cargo/reference/resolver.html
