### ISSUE TITLE
Book, config: TOML syntax highlighting broken

### ISSUE THREAD

**Issue by felixrabe** [rust-lang/cargo#6932] opened 2019-05-12 15:17 UTC
The syntax highlighting of the long TOML section at https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys looks wrong:

<img width="1288" alt="Screen Shot 2019-05-12 at 17 07 23" src="https://user-images.githubusercontent.com/400795/57584154-723eff80-74d8-11e9-95c4-0faae95fb7a1.png">

The section correctly starts with a `` ```toml `` fence:

https://github.com/rust-lang/cargo/blob/ceb1389037ff4987a9a51066a173012ee18861dc/src/doc/src/reference/config.md#L43

Btw, GitHub seems to display that same section just fine:

https://github.com/rust-lang/cargo/blob/ceb1389037ff4987a9a51066a173012ee18861dc/src/doc/src/reference/config.md#configuration-keys

**Comment by ehuss** [comment] 2019-05-12 15:53
Yea, that's bugged me for a while. The problem is that the highlighting engine (highlight.js) doesn't highlight toml properly.  Either highlight.js needs to be updated to handle comments after keys, or mdbook needs to switch to a different highlighter.  Fixing highlight.js doesn't look too difficult.

**Comment by lzutao** [comment] 2019-05-24 13:29
cc rust-lang-nursery/mdBook#90

**Comment by ehuss** [comment] 2019-07-20 00:06
This is now fixed on nightly.

**Closed by ehuss** 2019-07-20 00:06 UTC
Labels: A-documenting-cargo-itself, C-bug
