### ISSUE TITLE
Respect init.defaultBranch gitconfig option

### ISSUE THREAD

**Issue by Pytal** [rust-lang/cargo#8663] opened 2020-08-30 01:25 UTC
With the recent developments at https://github.com/github/renaming/#readme on defaulting to the `main` branch instead of `master`, I think `cargo new` and `cargo init` should respect the opt-in [init.defaultBranch option](https://git-scm.com/docs/git-config#Documentation/git-config.txt-initdefaultBranch) in `.gitconfig`.

**Comment by sfackler** [comment] 2020-08-30 01:27
Duplicate of https://github.com/rust-lang/cargo/issues/8588.

**Comment by Eh2406** [comment] 2020-08-30 03:58
We are working on this on several fronts. #8522 is also relevant. The direct ask is a dup of #8588, so I will ask that conversation happen there and close for now.

**Closed** 2020-08-30 03:58 UTC
Labels: C-bug
