### ISSUE TITLE
Normalize crate names when reading Cargo.toml

### ISSUE THREAD

**Issue by spinda** [rust-lang/cargo#4383] opened 2017-08-08 22:46 UTC
This seeks to address two problems.

# `-` vs `_`

The Rust community tends to use `-` and `_` as word separators in package/crate names. However, the allowance of both characters, and the fact that `-` is invalid in a crate name in Rust source, has created something of a messy situation. For some crates, users need to write `-` in their Cargo.toml and `_` in their Rust source (`tokio-core`, `rustc-serialize`, `num-traits`). For others, `_` is used in both places (`lazy_static`, `serde_derive`, `symbolic_expressions`). This creates a point of confusion and imposes additional cognitive overhead.

Proposal: teach Cargo to treat these characters as equivalent when reading crate names from Cargo.toml, normalizing them to `_` (matching their representation in Rust source).

[According](https://lobste.rs/s/skzrvt/announcing_http_crate#c_mfhqbd) to @Manishearth:

> - Crates.io considers them to be the same when uploading crates
> - Rustc will always see crate names with hyphens converted to underscores
>
> (So there are no clashing crate names)

# cAsE senSITIvIty

What was that one package called? `inflector`? Oh, no, it's `Inflector`. But crates.io will recognize any of [`inflector`](https://crates.io/crates/inflector), [`Inflector`](https://crates.io/crates/Inflector), or even [`inFLeCtOr`](https://crates.io/crates/inFLeCtOr). And in Rust source, you're expected to write `extern crate inflector`.

Proposal: internally lowercase crate names read from Cargo.toml and treat case variations as equivalent. Since Rust only allows ASCII crate names, there's no need to deal with any of the oddities of Unicode case normalization.

**Comment by matklad** [comment] 2017-08-09 09:06
Yeah, we've been historically lax about `-` vs `_`: https://github.com/rust-lang/cargo/blob/fe56d43b0afbe06709900b4dab4123655929a0e2/src/cargo/util/toml/targets.rs#L74-L77

**Comment by alexcrichton** [comment] 2017-08-09 17:13
Seems like a great idea to me! The actual implementation here though requires crates.io, the index, and Cargo to all agree on a canonicalization of a name. The index right now is keyed off the actual crate's name (e.g. what was uploaded to crates.io). This means there's no efficient mechanism of performing normalization right now in Cargo, and the format of the index would need to change to support this.

I also think that we shouldn't normalize case because rustc itself doesn't do that, just normalize `-` and `_` which rustc does indeed do. For example `extern crate Foo` and `extern crate foo` I believe are considered unique items in the compiler. Cargo, however, for other technical reasons will likely continue to forbid two crates like `Foo` and `foo` existing.

**Comment by carols10cents** [comment] 2017-09-25 20:24
Closing as a duplicate of #2775.

**Closed by carols10cents** 2017-09-25 20:24 UTC
Labels: A-crate-dependencies, A-interacts-with-crates.io, C-feature-request
