### ISSUE TITLE
Override doesn't work for dependency with invalid Cargo.toml

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#1866] opened 2015-08-02 16:27 UTC
I'm trying to upgrade [rust-media](https://github.com/pcwalton/rust-media/) to work with modern Cargo and rustc, and I've hit a wall - the Cargo.toml files for the dependencies contain hyphens in the library targets ([example](https://github.com/pcwalton/giflib/blob/master/Cargo.toml#L11)), and this is apparently checked before any overrides are applied to Cargo's resolution process. This means we end up short-circuiting the build before my local overrides that correct this are seen, which leaves me in a bind.

**Comment by jdm** [comment] 2015-08-02 16:29
I tried moving the call to `registry.add_overrides` above the call to `ops::resolve_pkg`, but that ended in a panic when writing the lockfile:
```
thread '<main>' panicked at 'Path sources are not included in the lockfile, so this is unimplemented', src/cargo/core/source.rs:140
stack backtrace:
   1:        0x10405d3e5 - sys::backtrace::write::hc1f6b3b53a27359aCxs
   2:        0x104063e90 - panicking::on_panic::h36580eaac6600621kYw
   3:        0x10403fa22 - rt::unwind::begin_unwind_inner::h57ec4c9208d0dc0dvGw
   4:        0x10387bb6c - rt::unwind::begin_unwind::h15506328112650259691
   5:        0x10387bd2c - core::source::SourceId::to_url::h4de6e7bdf9f3685a4Va
   6:        0x103b56222 - core::resolver::encode::EncodablePackageId.Encodable::encode::h16613321242307088370
   7:        0x103b5601e - serialize::Vec<T>.Encodable::encode::closure.36765
   8:        0x103b55fb5 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_seq_elt::h7690873610396577249
   9:        0x103b55bf2 - serialize::Vec<T>.Encodable::encode::closure.36759
  10:        0x103b55800 - encoder::Encoder::seq::h2228651658463297836
  11:        0x103b55765 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_seq::h2883634210538938863
  12:        0x103b556f8 - serialize::Vec<T>.Encodable::encode::h4959619539359467056
  13:        0x103b5567e - serialize::Option<T>.Encodable::encode::closure.36756
  14:        0x103b55621 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_option_some::h8402366330963260146
  15:        0x103b555bc - serialize::Option<T>.Encodable::encode::closure.36753
  16:        0x103b55531 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_option::h7485314673123112204
  17:        0x103b554d9 - serialize::Option<T>.Encodable::encode::h10915907600534416848
  18:        0x103b55472 - core::resolver::encode::EncodableDependency...rustc_serialize..Encodable::encode::closure.36750
  19:        0x103b5523b - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_struct_field::h5788726152598560082
  20:        0x103b541df - core::resolver::encode::EncodableDependency...rustc_serialize..Encodable::encode::closure.36731
  21:        0x103b53c3c - encoder::Encoder::table::h28850226048999793
  22:        0x103b5375b - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_struct::h17702489912170245301
  23:        0x103b536b1 - core::resolver::encode::EncodableDependency...rustc_serialize..Encodable::encode::h2931018447555830387
  24:        0x103b535de - serialize::Vec<T>.Encodable::encode::closure.36728
  25:        0x103b53575 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_seq_elt::h2352543185173116841
  26:        0x103b531b2 - serialize::Vec<T>.Encodable::encode::closure.36721
  27:        0x103b52ce0 - encoder::Encoder::seq::h974504862689590219
  28:        0x103b52c45 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_seq::h14494414658044452840
  29:        0x103b52bd8 - serialize::Vec<T>.Encodable::encode::h15214179090937201756
  30:        0x103b52b5e - serialize::Option<T>.Encodable::encode::closure.36715
  31:        0x103b52b01 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_option_some::h9122231503848092811
  32:        0x103b52a9c - serialize::Option<T>.Encodable::encode::closure.36712
  33:        0x103b52a11 - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_option::h6520792473108135727
  34:        0x103b529b9 - serialize::Option<T>.Encodable::encode::h17245204153238084283
  35:        0x103b50ba2 - core::resolver::encode::EncodableResolve...rustc_serialize..Encodable::encode::closure.36694
  36:        0x103b5096b - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_struct_field::h9539531413042240757
  37:        0x103b501f4 - core::resolver::encode::EncodableResolve...rustc_serialize..Encodable::encode::closure.36687
  38:        0x103b4f733 - encoder::Encoder::table::h3277733710865330315
  39:        0x103b4f5eb - encoder::rustc_serialize::Encoder.rustc_serialize..Encoder::emit_struct::h7289585349013306106
  40:        0x103b4f549 - core::resolver::encode::EncodableResolve...rustc_serialize..Encodable::encode::h7034837144950946391
  41:        0x103b4dbc1 - core::resolver::encode::Resolve.Encodable::encode::h1533030809239173978
  42:        0x103b4cd06 - ops::lockfile::write_lockfile::h14b079aa791f535dfLo
  43:        0x1039b4fe3 - ops::lockfile::write_pkg_lockfile::h4e947de5a3a905b1QKo
  44:        0x103986e96 - ops::resolve::resolve_pkg::he82920bf13ad1384QAp
  45:        0x1039813d5 - ops::cargo_compile::compile_pkg::hc36009f581ec621agyh
  46:        0x10397e9fc - ops::cargo_compile::compile::h3e4fa4972335d99eeth
  47:        0x10378d45a - execute::build::execute::h23eb4b5fa84ec32elua
  48:        0x10378780d - call_main_without_stdin::h16608765939240967189
  49:        0x1037716bf - execute::hab60fd546ee1c98cMca
  50:        0x1037626c3 - call_main_without_stdin::h17080792460385943255
  51:        0x103760c35 - execute_main_without_stdin::closure.5964
  52:        0x1037573b6 - process::closure.4906
  53:        0x103756b5e - process::h3886381647654044173
  54:        0x103756ab4 - execute_main_without_stdin::h9231707286382774760
  55:        0x10375683c - main::hba3ad58e01aac5d8Aca
  56:        0x10406378f - __rust_try_inner
  57:        0x1040637ca - __rust_try
  58:        0x104064ada - rt::lang_start::h15bd67087a7fcd0fgTw
  59:        0x10377665e - main
```

**Comment by alexcrichton** [comment] 2015-08-03 17:17
Unfortunately using an override doesn't mean that the actual package itself is totally 100% disregarded, it still needs to be parsed and checked for information to generate a lockfile. Can you just depend on an alternate git fork or path dependency while you're getting things to work?

**Comment by jdm** [comment] 2015-08-03 17:20
Yes, that's what I've ended up doing. It still ended up totally baffling me for a solid 24 hours.

**Comment by alexcrichton** [comment] 2015-08-03 22:14
Ok, in that case this is otherwise working as intended, so closing as such.

**Closed by alexcrichton** 2015-08-03 22:14 UTC

**Comment by jdm** [comment] 2015-08-03 22:45
It would be nice to have better diagnostics here or something?

**Comment by alexcrichton** [comment] 2015-08-04 16:28
What error message did you get originally? That may help see if there's something that could be improved about the output

**Comment by jdm** [comment] 2015-08-04 18:31
The error message kept telling me that the library target in the dependency's Cargo.toml could not contain hyphens. The baffling part for me was that I had set up my overrides like http://doc.crates.io/guide.html#overriding-dependencies told me to and I had no feedback on why that wasn't working.

**Comment by alexcrichton** [comment] 2015-08-04 22:55
Do you have an example I could reproduce with? If it printed the path to the errant Cargo.toml would that have sufficed?

**Comment by jdm** [comment] 2015-08-04 23:29
https://github.com/pcwalton/giflib/ has not yet merged a PR to update the Cargo.toml, so that's a fine example. The problem with the TOML is perfectly clear in the output. The bit I'm grousing about is the confusion I experienced while trying to fix that problem using local overrides; it was not clear to me at all why that wasn't working.

**Comment by jdm** [comment] 2015-08-04 23:30
In case it's unclear - Cargo was very clearly using the Cargo.toml file from the remote package. I couldn't figure out why it was doing that when I had provided an override, however. That's the confusion I'm hoping to address.

**Comment by alexcrichton** [comment] 2015-08-06 00:27
I'm... at a bit of a loss of what should be documented or improved here. Do you have something concrete you'd like to see?

**Comment by jdm** [comment] 2015-08-06 04:20
No ideas at this point. It's enough of an edge case that it's probably not worth spending further time thinking about it.
