### ISSUE TITLE
Crate with a keyword containing space fails during publish, but not during dry run.

### ISSUE THREAD

**Issue by patriksvensson** [rust-lang/cargo#8482] opened 2020-07-13 21:36 UTC
**Problem**
I tried to specify a keyword within `Cargo.toml` that contained a space. Running `cargo publish --dry-run` showed that the package was valid, but submitting it to crates.io failed with an API error.

```toml
keywords = ["foo", "foo bar"]
```

I appreciate that you might not want to tie implementation details in `crates.io` to `cargo publish` in case this theoretically could be supported in other package repository implementations, but I thought I would report this anyway. If you decide that this is a bug, I'm more than happy to submit a pull request for it.

**Steps**
1. Create a new crate
2. Add a keyword with a space in it, such as `keywords = ["foo", "foo bar"]`
3. Run `cargo publish --dry-run`: Does not display any errors.
4. Publish crate using `cargo publish`: Returns an API error.

**Possible Solution(s)**
Display an error after a dry run if there is a space in a keyword.

**Notes**

The output from `cargo publish`:

```
> cargo publish
   Updating crates.io index
   Packaging foo v0.1.0 (D:\Source\github\patriksvensson\foo)
   Verifying foo v0.1.0 (D:\Source\github\patriksvensson\foo)
   Finished dev [unoptimized + debuginfo] target(s) in 1.06s
   Uploading foo v0.1.0 (D:\Source\github\patriksvensson\foo)
error: api errors (status 200 OK): invalid upload request: invalid value: string "foo bar", expected a valid keyword specifier at line 1 column 555
```

**Comment by ehuss** [comment] 2020-07-13 21:47
Thanks for the report. This appears to be a duplicate of #4300, so closing in favor of that.

**Closed by ehuss** 2020-07-13 21:47 UTC
Labels: C-bug
