### ISSUE TITLE
Add .config/cargo/config.toml to probe list

### ISSUE THREAD

**Issue by frogtile** [rust-lang/cargo#9907] opened 2021-09-13 18:23 UTC
**Describe the problem you are trying to solve**

Many programs, like git, also look for config file in their own directory in $XDG_CONFIG_HOME and If $XDG_CONFIG_HOME is not set or empty it looks in  $HOME/.config. It would be nice if cargo also do this.

**Describe the solution you'd like**

Cargo to look for config.toml in $XDG_CONFIG_HOME/cargo and $HOME/.config

**Comment by ehuss** [comment] 2021-09-13 18:49
Thanks for the suggestion!  I believe this is a duplicate of #1734 (or at least a subset of), so I'm going to close in favor of that.

**Closed by ehuss** 2021-09-13 18:49 UTC
Labels: C-feature-request

**Comment by frogtile** [comment] 2021-09-14 01:57
Being a subset it is much easier to implement. And if this is available, CARGO_HOME can be happily assigned to ~/.local/share/cargo

This will for most part match with Go, which stores it's config (env) file at ~/.config/go/env and has GOPATH variable for most other things (which I set it to ~/.local/share/go).
