### ISSUE TITLE
Manifest's conditional dependency feature flag not working

### ISSUE THREAD

**Issue by hydroper** [rust-lang/cargo#12414] opened 2023-07-29 21:13 UTC
### Problem

I've three crates:

- `c1`
- `c2`
- `c3`

What they do:

- `c1::main` calls `c2::f`
- `c2::f` calls `c3::f`
- `c3::f` prints whether it has been called with a feature `c1_some_feature` or not.

I get this after running `cargo run c1 --features c1_some_feature`

```sh
# got
called c3::f() without c1_some_feature

# expected
called c3::f() with c1_some_feature
```

Inside the `features` section of the manifest, I used the `dependency/c1_some_feature` syntax:

- Inside `c1/Cargo.toml`
```toml
[dependencies]
c2 = { path = "../c2" }

[features]
c1_some_feature = ["c2/c1_some_feature"]
```
- Inside `c2/Cargo.toml`
```toml
[dependencies]
c3 = { path = "../c3" }

[features]
c1_some_feature = ["c3/c1_some_feature"]
```

### Steps

1. Clone this simple workspace demonstrating the issue and run the binary `c1`: 
```sh
git clone https://github.com/hydroper/cargo_indirect_features
cd cargo_indirect_features
cargo run c1 --features c1_some_feature
```

### Possible Solution(s)

N/A

### Notes

N/A

### Version

```text
cargo 1.73.0-nightly (1b1555676 2023-07-18)
release: 1.73.0-nightly
commit-hash: 1b15556767f4b78a64e868eedf4073c423f02b93
commit-date: 2023-07-18
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 CoreSingleLanguage) [64-bit]
```
```

**Comment by epage** [comment] 2023-07-30 01:41
I just tried to reproduce this with both stable and the same nightly and it worked
```console
$ cargo +nightly run -p c1
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/c1`
not c1_some_feature

$ cargo +nightly run -p c1 -F c1_some_feature
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/c1`
c1_some_feature
```

`Cargo.toml`:
```toml
[workspace]
resolver = "2"
members = ["c1", "c2", "c3"]
```
`c1/Cargo.toml`:
```toml
[package]
name = "c1"
version = "0.0.0"

[dependencies]
c2 = { path = "../c2" }

[features]
c1_some_feature = ["c2/c1_some_feature"]
```
`c1/src/main.rs`
```rust
fn main() {
    c2::f();
}
```
`c2/Cargo.toml`
```toml
[package]
name = "c2"
version = "0.0.0"

[dependencies]
c3 = { path = "../c3" }

[features]
c1_some_feature = ["c3/c1_some_feature"]
```
`c2/src/lib.rs`
```rust
pub fn f() {
    c3::f()
}
```
`c3/Cargo.toml`
```rust
[package]
name = "c3"
version = "0.0.0"

[features]
c1_some_feature = []
```
`c3/src/lib.rs`
```rust
pub fn f() {
    #[cfg(feature = "c1_some_feature")]
    println!("c1_some_feature");
    #[cfg(not(feature = "c1_some_feature"))]
    println!("not c1_some_feature");
}
```

btw in cases like this, it'd help if you posted a repo that reproduces the issue so its easier for other people to verify, debug, and fix.

**Comment by hydroper** [comment] 2023-07-30 10:30
@epage Thanks for testing it! Actually I did a minimal reproduction at the issue, but didn't mention the repo:

- https://github.com/hydroper/cargo_indirect_features

I tried the exact commands you've shown and, with or without `-F c1_some_features`, it always yields:

```
called c3::f() without c1_some_feature
```

This is so strange. I'm actually creating Rialight, which consists of several crates, and I'm afraid I'll experience this issue there. Specially there I use a feature for detecting the browser (`rialight_browser_export`) and not `target_arch = "wasm23"` (which may end up detecting Nintendo Switch in the future as I may use Rust to target wasm32 and then somthing else)

**Comment by weihanglo** [comment] 2023-07-30 10:59
> * https://github.com/hydroper/cargo_indirect_features
> 
> 
> I tried the exact commands you've shown and, with or without `-F c1_some_feature`, it always yields:
> 
> ```
> called c3::f() without c1_some_feature
> ```

Here is what I've got:

```console
$ cargo +nightly run -p c1
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/c1`
called c3::f() without c1_some_feature
$ cargo +nightly run -p c1 -F c1_some_feature
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/c1`
called c3::f() with c1_some_feature
```

Cannot reproduce what you've got either. Could you set environment variable `CARGO_LOG=cargo::core::resolver::features`, run those commands again, and share logs here?

**Comment by hydroper** [comment] 2023-07-30 11:09
@weihanglo Now it worked (copy-pasting your command). I don't know if I typed something wrongly in my commands. However, with or without `CARGO_LOG=cargo::core::resolver::features` set, it worked. Hmm...

I suppose `-p` is optional, right? And `-f` can still be used as `--features` when desired?

**Comment by hydroper** [comment] 2023-07-30 11:17
I discovered the issue!

I need to specify `-p c1`, not `c1`, otherwise it won't work

**Comment by weihanglo** [comment] 2023-07-30 11:50
Glad you figured it out!

> I need to specify `-p c1`, not `c1`, otherwise it won't work
> 
> Cargo could tell about this?

Unfortunately, no. `cargo run` accepts arbitrary trailing arguments and passes them to the binary you built unconditionally. Cargo doesn't know `c1` is not for your binary.

Given the original problem is resolved, this issue could be closed I guess?

**Comment by hydroper** [comment] 2023-07-30 11:54
@weihanglo I see, but I wonder why Cargo didn't pass the specified features when not specifying the package... I'd like to know if `--features` could be passed without specifying `-p`

It couldn't be a problem, but it'd be nice if it were solved!

**Comment by weihanglo** [comment] 2023-07-30 12:09
> I'd like to know if `--features` could be passed without specifying `-p`

So, this depends on how your workspace looks like. What if there are more than one member having the same feature `feat`? Which feature should be enabled if you run `cargo run -F feat`? To solve this problem, Cargo provides a way to disambiguate by specifying package name, with the syntax `--feature package/feature`. In general, it's a good habit to be aware of `--package` flag if you want to control what is being built.

When you have a workspace, `cargo run` with and without `--package/-p` have different meanings. IIRC the former one usually builds all workspace default members, and does feature unification against those members; with `--package` cargo narrows down the scope to the specific package when doing feature unification. This is also a thing we need to keep in mind.

---

Back to your repro <https://github.com/hydroper/cargo_indirect_features>. This case is a bit special. You can definitely run `cargo +nightly run -F c1_some_feature` without `-p`, as `c1` contains the only binary in this workspace. That says, there is no ambiguity.

**Comment by weihanglo** [comment] 2023-07-30 17:58
Going to close this. This is an expected behavior. If you feel this shouldn't be closed, please call out letting us know.

**Closed by weihanglo** 2023-07-30 17:58 UTC
Labels: C-bug, S-needs-info
