### ISSUE TITLE
Features for targets

### ISSUE THREAD

**Issue by JanLikar** [rust-lang/cargo#2214] opened 2015-12-16 05:27 UTC
I think it would be beneficial to have a way to "attach" a compilation target to a feature, so it will be compiled only if that particular feature would be enabled. I know it's possible to use `#![cfg(feature="foo")]` to achieve a similar effect, but for some use cases this would be better. cargo-extras crate, for instance, could use it, as none of the included binaries actually reside in that crate.
```
[[bin]]
name = "foo"
path = "src/bin/bar.rs"
feature = "foo"

[features]
foo = []
```

**Comment by alexcrichton** [comment] 2015-12-16 06:57
I think that this is a dupe of https://github.com/rust-lang/cargo/issues/1570, so I'm gonna close in favor of that. Thanks for the report though!

**Closed by alexcrichton** 2015-12-16 06:57 UTC
