### ISSUE TITLE
Build fails due to incompatible versions

### ISSUE THREAD

**Issue by Kilte** [rust-lang/cargo#2611] opened 2016-04-23 00:10 UTC
Hello. I have a problem. The problem is that cargo tries to build redis using incompatible version of url crate. I've specified url v0.5.9, but it [compiles](http://pastebin.com/SWkuVHms) v0.5.9 (-C extra-filename=-c89239277d516eaf) and v1.0.0 (-C extra-filename=-**8654f83abfcefeb2**) both and then it uses v1.0.0 when building redis (--extern url=.../liburl-**8654f83abfcefeb2**.rlib).

[Cargo.lock](http://pastebin.com/EMkRgAk3) and Cargo.toml:

```toml
[package]
name = "scrobbler"
version = "0.0.1"
authors = ["Kilte Leichnam <nwotnbm@gmail.com>"]

[dependencies]
log = "0.3.6"
log4rs = { version = "0.4.3", features = ["json"] }
hyper = "0.8.1"
nickel = "0.8.0"
plugin = "0.2.6"
postgres = "0.11.7"
r2d2 = "0.6.4"
r2d2_postgres = "0.10.1"
r2d2_redis = "0.2.0"
redis = "0.5.2"
rust-crypto = "0.2.35"
rustc-serialize = "0.3.19"
time = "0.1.35"
typemap = "0.3.3"
url = "0.5.9"
uuid = "0.2.1"
```

**Comment by Kilte** [comment] 2016-04-23 00:24
Same problem for r2d2

**Comment by Kilte** [comment] 2016-04-23 00:33
When i've changed versions in Cargo.lock manually, it works.

**Comment by alexcrichton** [comment] 2016-04-24 17:32
This looks like it's a bug in the redis crate for having a `*` dependency on `url`, and otherwise I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/2064 where Cargo is a bit too eager to pull in multiple dependencies.

**Comment by alexcrichton** [comment] 2016-04-24 17:32
Thanks for the report though!

**Closed by alexcrichton** 2016-04-24 17:32 UTC
