### ISSUE TITLE
`per-package-target` doesn't seem to work?

### ISSUE THREAD

**Issue by cbiffle** [rust-lang/cargo#9465] opened 2021-05-07 16:28 UTC
**Problem**
I'm attempting to use the `per-package-target` unstable feature on nightly Cargo and it's being refused. Presumably I am holding it wrong, but I haven't been able to work out how.

Builds always fail with
```
error: failed to parse manifest at `/tmp/per-package-target/Cargo.toml`

Caused by:
  unknown cargo feature `per-package-target`
```

I've posted a [minimal repro repo](https://github.com/cbiffle/cargo-per-package-target-repro-case) whose contents are extracted from Cargo's own test case for the feature. It does not build. (I have confirmed that the Cargo tests are, in fact, passing on Cargo's CI.)

I can only find one repo making use of the feature, [kannader by the feature's author](https://github.com/Ekleog/kannader/tree/main), and it also doesn't build with any nightly version I've tried from November to now -- their build is using nix to pull in a toolchain at a specific commit from somewhere odd, with a TODO.

**Steps**
1. `git clone https://github.com/cbiffle/cargo-per-package-target-repro-case.git`
2. `cd cargo-per-package-target-repro-case`
3. `cargo build`

**Notes**

Output of `cargo version`:
`cargo 1.53.0-nightly (65d57e6f3 2021-04-04)`
(pinned by `rust-toolchain`)

**Comment by ehuss** [comment] 2021-05-07 18:37
Thanks for trying to take it for a spin!  It hasn't landed on nightly yet.  It can take up to a week or two for things to make it there.  I plan to try to sync it soon, and I would expect it to be available within a few days.  Unfortunately we don't have any easy mechanism to announce when something is available on nightly.

If you are feeling adventurous, you can clone the cargo repo and build cargo from there (just type `cargo build` or `cargo build --release`).   There's more instructions on building and running [here](https://doc.crates.io/contrib/process/working-on-cargo.html#building-cargo).

**Comment by cbiffle** [comment] 2021-05-07 19:39
I see. It's also not very easy to tell, as a user, whether something is in a nightly build based on the unstable features chapter in the Cargo book, the tracking issues, or the PRs, because I checked all three before reporting this. FWIW.

**Comment by ehuss** [comment] 2021-05-07 23:58
Oh, I'm sorry, I took a closer look and realized it merged a few days ago.  It should be available as of nightly-2021-04-28.  It looks like the date in your repo is 2020-11-30, which is too old.

**Comment by MarkSwanson** [comment] 2021-05-10 16:57
It's merged now, and it might be working but I couldn't fully test it because of what seems to be a regression in underscore handling?
use defmt_rtt as _;
      ^^^^^^^^^^^^^^ no external crate `defmt_rtt`

Cargo.toml:
defmt-rtt = "0.2.0"

$ cargo --version
cargo 1.54.0-nightly (e51522ab3 2021-05-07)

I did not get the 'no external crate' error with this previous nightly:
cargo 1.53.0-nightly (0ed318d18 2021-04-23)

Suggestions?

**Comment by ehuss** [comment] 2021-05-19 23:05
I'm going to close, as it should be available as of nightly-2021-04-28.  If you have any issues testing it, please feel free to open a new issue.

**Closed by ehuss** 2021-05-19 23:05 UTC
Labels: C-bug
