### ISSUE TITLE
Why not have a central directory to store all the built crates?

### ISSUE THREAD

**Issue by sntdevco** [rust-lang/cargo#6711] opened 2019-03-03 10:50 UTC
Cargo creates a copy of the dependencies for every project built. Let's say I was using the `rand` crate. If I created a project called `rand_super` and `rand_awesome` then both of the projects would be given their own copies of `rand`. So why don't we create some kind of central directory for the already downloaded crates, let's say we have _~/.rustup/crates.io/crates/_ or something like that and we store all the deps that are downloaded. Then it doesn't need to be downloaded for each project individually. And we can have a command like `cargo add <http://url/to/crate>`. The crate URL can simply be the crates.io URL say for `rand` it could be something like `cargo add https://crates.io/crates/rand/0.6.5/`. This would be a great advantage. I'll work on this and try to create an experimental version of cargo with this feature. Thoughts?

**Comment by dwijnand** [comment] 2019-03-03 12:24
Configuring the target directory for built crates is already implemented.  This is a duplicate of https://github.com/rust-lang/cargo/issues/482, which has been implemented.

See
* https://doc.rust-lang.org/cargo/reference/environment-variables.html
* https://doc.rust-lang.org/cargo/reference/config.html
* https://stackoverflow.com/questions/37471391/can-i-prevent-cargo-from-rebuilding-libraries-with-every-new-project; and
* https://stackoverflow.com/a/37472558/463761

for more info and thoughts on this.

**Closed by dwijnand** 2019-03-03 12:24 UTC
Labels: C-feature-request
