### ISSUE TITLE
Add `cargo downgrade` or `cargo update --oldest`

### ISSUE THREAD

**Issue by DanielKeep** [rust-lang/cargo#2463] opened 2016-03-10 04:28 UTC
Currently, Cargo will try to use the newest version of dependencies when you invoke `cargo update` or just build for the first time.  This is a pain when you're trying to _write_ a package, as it means the version of dependencies listed in the manifest doesn't necessarily match the version of dependencies that are being tested/developed against.

As such, it would be very convenient if there was a shorthand command or switch that downgraded all dependencies of the current package to the earliest possible versions.  For bonus points, it should signal an error if the version specified by a `^` (and possibly `>=`) constraint is not selectable (_i.e._ "you say I should be able to select `plimsor="1.2.6"`, but I can't _actually_ do so).  Double bonus points for some persistent per-package option that makes this the default and/or prevents implicitly updating dependencies with some explicit override.

This should help keep package authors honest about what dependency versions their code actually works with.

**Comment by carols10cents** [comment] 2017-09-25 17:33
I'm going to close this as a duplicate of #4100, which is part of https://github.com/rust-lang/rfcs/pull/1977 :)

**Closed by carols10cents** 2017-09-25 17:33 UTC
