### ISSUE TITLE
`cargo update -p` produces nondeterministic results

### ISSUE THREAD

**Issue by staktrace** [rust-lang/cargo#4312] opened 2017-07-21 13:28 UTC
I'm seeing behaviour by `cargo update` that appears nondeterministic and I'm not sure why it's happening. The STR I have is like so:

- Take a mercurial clone of mozilla-central at cset 417eea89f792
- cd toolkit/library/gtest/rust
- cargo update -p webrender_api -p webrender
- hg diff

The hg diff (sometimes) will show that the heapsize dependency of webrender_api has been updated from `heapsize 0.3.8` to `heapsize 0.4.0`. However this doesn't happen *every* time. I have two different trees on my machine and right now it happens on one but not the other. I also have some patches in my queue (which touch some files in gfx/webrender, but do not touch any .toml or .lock files) and applying/unapplying those can change the behaviour. If it doesn't happen for you, try doing `touch <m-c root>/gfx/webrender_api/Cargo.toml` and re-running the `cargo update` command. That seemed to be one thing that triggered it for me, although not consistently.

I also tried running the `cargo update` command with `-vv` for verbose output but there was none. Short of digging into the cargo code I don't know how to debug this.

Note also that I've only seen this happen on the `toolkit/library/gtest/rust/Cargo.lock` file, and NOT on the very similar `toolkit/library/rust/Cargo.lock` file. This has resulted in https://bugzilla.mozilla.org/show_bug.cgi?id=1376311 previously.

**Comment by alexcrichton** [comment] 2017-07-21 15:16
This is somewhat expected, albeit surprising behavior. Most Cargo.toml graphs have a large number of crate graphs which actually satisfy the dependency graph, and so there's no way for Cargo to choose amongst them. Depending on crates.io data and such Cargo can reach different conclusions in different orders.

That being said, this may be a bug in Cargo as by default `cargo update` with `-p` should be conservative and try to only touch parts of the crate graph which are affected.

**Comment by jsgf** [comment] 2017-07-31 23:10
I'm seeing similar problems. I have a Cargo.toml where `cargo update` sometimes completes in 0.7s and produces a valid output, and other times where it takes >10s and chooses an ancient version of bzip2:

```
jsgf-mbp:crates.io jsgf$ rm Cargo.lock; time cargo update -v
    Updating registry `https://github.com/rust-lang/crates.io-index`

real	0m0.709s
user	0m0.123s
sys	0m0.057s
jsgf-mbp:crates.io jsgf$ rm Cargo.lock; time cargo update -v
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: Package `bzip2 v0.3.1` does not have these features: `tokio`

real	0m10.253s
user	0m9.688s
sys	0m0.046s
```

It seems to be non-deterministic from run to run.

**Comment by alexcrichton** [comment] 2017-08-01 01:30
@jsgf I think that may be unrelated to this issue, for that I've filed https://github.com/rust-lang/cargo/issues/4347

**Comment by eminence** [comment] 2022-11-26 04:39
Triage:  I can reproduce the originally reported problem using a cargo from back in the day (I tested rust 1.20 to rust 1.25).  The update to the `heapsize` pacakge (as a dependency of the `webrender_api` package) happened about 5 out of 10 times.  Note that heapsize 0.3.8 remains in the graph as other packages depend on it; the behavior of `cargo update` is definitely non-deterministic here.

But in cargo 1.26, the behavior becomes very consistant:  heapsize 0.3.8 gets fully removed from the graph and replaced with heapsize 0.4.0 everywhere (including as a dependency of a package that wasn't specified with `-p`).  Latest cargo stable 1.65 behaves like 1.26 in this regard.

(@staktrace thank you for including the detailed instructions on how to reproduce and info about what you were seeing; that data was very valuable in trying to triage this ancient issue)

**Comment by epage** [comment] 2023-10-17 02:06
Sounds like this is no longer reproducible, so I'm closing this out.  If there is a reason we should leave this open, let us know!

**Closed by epage** 2023-10-17 02:06 UTC
Labels: C-bug, Command-update, A-dependency-resolution
