### ISSUE TITLE
in macos，when i used `cargo build --bin xxx`, the xxx.dSYM  has no any symbols information

### ISSUE THREAD

**Issue by anhkgg** [rust-lang/cargo#4853] opened 2017-12-22 03:10 UTC
In Macos,
I want to debug a rust bin project by lldb in vscode, it can't break in main function.
After checking, i found that, there are no any symbols information in .dSYM.

But, for example `tlsclient` of the [rustls](https://github.com/ctz/rustls) project, i got valid .dSYM file, and could debug it in vscode.

I tested some simple code in c, gcc generate valid .dSYM file.
For the same code in rust, cargo and rustc can't generate valid .dSYM file.

It's sure that, i use cargo build dev project, not release.

So, that's the my problem, please help me !!!

## **Something new**

I found that , rustc stable version can generate valid .dSYM file, but nightly version can't. **Why?!**

**Comment by alexcrichton** [comment] 2017-12-22 16:09
Thanks for the report! I think this was a bug fixed in recent nightlies of rustc itself, so I'm going to close this. If you update rustc the issue is hopefully fixed!

**Closed by alexcrichton** 2017-12-22 16:09 UTC
