### ISSUE TITLE
Duplicate compiler errors

### ISSUE THREAD

**Issue by djc** [rust-lang/cargo#5388] opened 2018-04-18 14:35 UTC
With some regularity, I get duplicate compiler errors from `cargo test` -- it will repeat every error or warning twice. Is this a known issue?

**Comment by alexcrichton** [comment] 2018-04-18 14:43
What's actually happening here is that the library is being compiled twice (once with `--test` and once for doc tests later on), and this is a dupe of https://github.com/rust-lang/cargo/issues/1534, https://github.com/rust-lang/cargo/issues/851, and https://github.com/rust-lang/cargo/issues/1198. This is intended behavior though, and you can use various flags like `--test`, `--lib`, or `-j` to not run `rustc` in parallel, so I'm going to close this.

**Closed by alexcrichton** 2018-04-18 14:43 UTC
