### ISSUE TITLE
Cargo prints compiler errors twice

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3874] opened 2017-03-29 07:15 UTC
`cargo-0.17.0-nightly (f9e5481 2017-03-03)`

```
λ cargo test --all                                                                                            ~/projects/fall
   Compiling fall-gen v0.1.0 (file:///home/matklad/projects/fall/fall_gen)
error: no method named `many_of_type` found for type `fall_tree::node::imp::NodeChildren<'_>` in the current scope
  --> fall_gen/src/lib.rs:48:21
   |
48 |         .children().many_of_type(TOKEN_DEF)
   |                     ^^^^^^^^^^^^

error: no method named `many_of_type` found for type `fall_tree::node::imp::NodeChildren<'_>` in the current scope
  --> fall_gen/src/lib.rs:48:21
   |
48 |         .children().many_of_type(TOKEN_DEF)
   |                     ^^^^^^^^^^^^

error: aborting due to previous error
```

Looks like it's `--depinfo`?

<details>
<summary>
--verbose
</summary>

```
   Compiling fall-gen v0.1.0 (file:///home/matklad/projects/fall/fall_gen)
     Running `rustc --crate-name fall_gen fall_gen/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=a5f4f827a7e1e0a5 -C extra-filename=-a5f4f827a7e1e0a5 --out-dir /home/matklad/projects/fall/target/debug/deps -L dependency=/home/matklad/projects/fall/target/debug/deps --extern file=/home/matklad/projects/fall/target/debug/deps/libfile-35f7e092fbc94f65.rlib --extern clap=/home/matklad/projects/fall/target/debug/deps/libclap-11113a9323543daa.rlib --extern fall_parse=/home/matklad/projects/fall/target/debug/deps/libfall_parse-aadd3fc804a743e6.rlib --extern fall_tree=/home/matklad/projects/fall/target/debug/deps/libfall_tree-0f146101e9341e1d.rlib --extern fall_watch=/home/matklad/projects/fall/target/debug/deps/libfall_watch-2c2b1293660b70b1.rlib -C target-cpu=native`
     Running `rustc --crate-name fall_gen fall_gen/src/lib.rs --emit=dep-info,link -C debuginfo=2 --test -C metadata=8f5d94722fa7faf7 -C extra-filename=-8f5d94722fa7faf7 --out-dir /home/matklad/projects/fall/target/debug/deps -L dependency=/home/matklad/projects/fall/target/debug/deps --extern file=/home/matklad/projects/fall/target/debug/deps/libfile-35f7e092fbc94f65.rlib --extern clap=/home/matklad/projects/fall/target/debug/deps/libclap-11113a9323543daa.rlib --extern difference=/home/matklad/projects/fall/target/debug/deps/libdifference-51300806a4ca13f2.rlib --extern fall_parse=/home/matklad/projects/fall/target/debug/deps/libfall_parse-aadd3fc804a743e6.rlib --extern tempdir=/home/matklad/projects/fall/target/debug/deps/libtempdir-0ee757a585f719dd.rlib --extern fall_tree=/home/matklad/projects/fall/target/debug/deps/libfall_tree-0f146101e9341e1d.rlib --extern fall_watch=/home/matklad/projects/fall/target/debug/deps/libfall_watch-2c2b1293660b70b1.rlib -C target-cpu=native`
error: no method named `many_of_type` found for type `fall_tree::node::imp::NodeChildren<'_>` in the current scope
  --> fall_gen/src/lib.rs:48:21
   |
48 |         .children().many_of_type(TOKEN_DEF)
   |                     ^^^^^^^^^^^^

error: no method named `many_of_type` found for type `fall_tree::node::imp::NodeChildren<'_>` in the current scope
  --> fall_gen/src/lib.rs:48:21
   |
48 |         .children().many_of_type(TOKEN_DEF)
   |                     ^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `fall-gen`.

Caused by:
  process didn't exit successfully: `rustc --crate-name fall_gen fall_gen/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=a5f4f827a7e1e0a5 -C extra-filename=-a5f4f827a7e1e0a5 --out-dir /home/matklad/projects/fall/target/debug/deps -L dependency=/home/matklad/projects/fall/target/debug/deps --extern file=/home/matklad/projects/fall/target/debug/deps/libfile-35f7e092fbc94f65.rlib --extern clap=/home/matklad/projects/fall/target/debug/deps/libclap-11113a9323543daa.rlib --extern fall_parse=/home/matklad/projects/fall/target/debug/deps/libfall_parse-aadd3fc804a743e6.rlib --extern fall_tree=/home/matklad/projects/fall/target/debug/deps/libfall_tree-0f146101e9341e1d.rlib --extern fall_watch=/home/matklad/projects/fall/target/debug/deps/libfall_watch-2c2b1293660b70b1.rlib -C target-cpu=native` (exit code: 101)
Build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: build failed
```

</details>

**Comment by alexcrichton** [comment] 2017-03-29 16:12
Is this https://github.com/rust-lang/cargo/issues/3531 perhaps?

**Comment by carols10cents** [comment] 2017-10-02 23:04
Yep, closing as a duplicate of #3531; the diff of the two invocations is:

- the first has `--crate-type lib` and the second does not
- the second has `--test` and the first does not

which is consistent with the currently intended behavior of compiling once for doc tests and once for regular tests.

**Closed by carols10cents** 2017-10-02 23:04 UTC
