### ISSUE TITLE
New Crate Publisher UX (Check for Crate Issues Before Compiling) | cargo publish

### ISSUE THREAD

**Issue by elibenporat** [rust-lang/cargo#9331] opened 2021-04-05 16:20 UTC
Not sure if this is a "bug" per se, however, given that Rust emphasizes a good experience for newcomers (me, at least for crate publishing), I wanted to highlight this:

**Issue**
When publishing a crate, the first step cargo publish does is compile the crate, followed by a check that the things crates.io wants are satisfied. Being a novice at crate publishing, it became quite irksome to have to wait for the compile, just to get back the fixes I needed to do. Overall, not a big issue, but putting this check first would have been much more pleasant.

**Solution**
Check for crate publishing issues first, then try to compile the crate.

**Comment by ehuss** [comment] 2021-04-05 22:47
Thanks for the report!  Yea, it is bit awkward and frustrating how that works.

If the compilation step succeeded, then you can use the `--no-verify` flag to skip it next time. There is some documentation on how this works on the [`cargo package`](https://doc.rust-lang.org/cargo/commands/cargo-package.html) man page ([`cargo publish`](https://doc.rust-lang.org/cargo/commands/cargo-publish.html) essentially runs `cargo package` first and then uploads it).

This is a pretty well known issue. There is a summary at https://github.com/rust-lang/crates-io-cargo-teams/issues/82 about the pains with how the current publishing works, so I'm going to close as a duplicate of that (and the issues it links to).

**Closed by ehuss** 2021-04-05 22:47 UTC
Labels: C-bug
