### ISSUE TITLE
dev-dependencies not installed for `cargo test -p <non-root-package>`

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1442] opened 2015-03-23 19:27 UTC
Test case:
```sh
cargo new a
cd a
cargo new b
echo '[dependencies.b] path = "b"' >> Cargo.toml
echo '[dev-dependencies] tempdir = "*"' >> b/Cargo.toml
echo '#[cfg(test)] extern crate tempdir;' > b/src/lib.rs
cargo test -p b --verbose
```

Output
```
   Compiling b v0.0.1 (file:///home/simon/tmp/a)
     Running `rustc b/src/lib.rs --crate-name b --crate-type lib -g -C metadata=db71203704f279b3 -C extra-filename=-db71203704f279b3 --out-dir /home/simon/tmp/a/target/debug/deps --emit=dep-info,link -L dependency=/home/simon/tmp/a/target/debug/deps -L dependency=/home/simon/tmp/a/target/debug/deps`
     Running `rustc b/src/lib.rs --crate-name b --crate-type lib -g --test -C metadata=d094fbc60e650295 -C extra-filename=-d094fbc60e650295 --out-dir /home/simon/tmp/a/target/debug/deps --emit=dep-info,link -L dependency=/home/simon/tmp/a/target/debug/deps -L dependency=/home/simon/tmp/a/target/debug/deps`
b/src/lib.rs:1:14: 1:35 error: can't find crate for `tempdir`
b/src/lib.rs:1 #[cfg(test)] extern crate tempdir;
                            ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `b`.

Caused by:
  Process didn't exit successfully: `rustc b/src/lib.rs --crate-name b --crate-type lib -g --test -C metadata=d094fbc60e650295 -C extra-filename=-d094fbc60e650295 --out-dir /home/simon/tmp/a/target/debug/deps --emit=dep-info,link -L dependency=/home/simon/tmp/a/target/debug/deps -L dependency=/home/simon/tmp/a/target/debug/deps` (exit code: 101)
```

**Comment by alexcrichton** [comment] 2015-03-23 20:44
Dupe of https://github.com/rust-lang/cargo/issues/860, but thanks!

**Closed by alexcrichton** 2015-03-23 20:44 UTC
