### ISSUE TITLE
Package not found despite it being in the checked out git repository

### ISSUE THREAD

**Issue by theoparis** [rust-lang/cargo#14819] opened 2024-11-13 21:35 UTC
### Problem

For some reason the inkwell package is not being found, even though it exists both in my inkwell fork and the local ~/.cargo/git/checkouts folder. I can't seem to figure out what is happening so I assumed it was best to report it here. I tried `cargo clean` and `rm -rf ~/.cargo/{git,registry}`, and it didn't fix the issue. 

### Steps

```
git clone https://github.com/theoparis/trippy -b rewrite
cd trippy
cargo run
```

### Version

```text
cargo 1.82.0 (8f40fc59f 2024-08-21)
release: 1.82.0
commit-hash: 8f40fc59fb0c8df91c97405785197f3c630304ea
commit-date: 2024-08-21
host: x86_64-unknown-linux-musl
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Linux Rolling Release (chimera) [64-bit]
```

**Comment by theoparis** [comment] 2024-11-13 21:41
Update: it seems like the issue is this
```
error: failed to parse manifest at `/home/theo/Documents/inkwell/Cargo.toml`

Caused by:
  feature `llvm18-0-force-dynamic` includes `llvm18-0` which is neither a dependency nor another feature

```

However, the error message did not report this and was very confusing.

**Comment by epage** [comment] 2024-11-13 21:47
We defer the error and only show it if no packages are found.  However, there is a package at `internal_macros/Cargo.toml`.

One way of handling this is if we re-parse the manifest to try to get only the name out and then re-report the error if someone is looking for that name.

**Comment by ehuss** [comment] 2024-11-13 21:51
I believe this is a duplicate of #6211, so closing in favor of that. Let me know if there seems to be something different there.

**Closed by ehuss** 2024-11-13 21:51 UTC
Labels: C-bug, A-git, A-diagnostics, S-needs-design
