### ISSUE TITLE
New option: cargo doc --watch

### ISSUE THREAD

**Issue by FauconFan** [rust-lang/cargo#10813] opened 2022-07-02 17:04 UTC
### Problem

Hi, I would like to propose a new feature for the doc subcommand. It would be nice to regenerate the documentation when source code files change. This could be done relatively easily using the notify crate. Like mdbook does. A current workaround could be:

```console
cargo watch -x doc
```

This workaround uses the cargo-watch extension for cargo, but this feature could be handle directly into cargo ?

**Comment by ehuss** [comment] 2022-07-04 01:08
Thanks for the suggestion!  I'm going to close this as a duplicate of #9339 which is more or less the same.

**Closed by ehuss** 2022-07-04 01:08 UTC
Labels: C-feature-request
