### ISSUE TITLE
Cargo vendor fails with git repos if any path to ~/.cargo is a symlink

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/cargo#10270] opened 2022-01-07 00:45 UTC
### Problem

cargo vendor fails with:

```
   Vendoring tokio v0.2.13 (https://github.com/fengalin/tokio?tag=tokio-0.2.13-throttling#2fd15518) (/home/william/.cargo/git/checkouts/tokio-c37f2f85799e8a25/2fd1551/tokio) to /dev/shm/cargo-vendor-repro/vendor/tokio
error: failed to sync

Caused by:
  failed to write `vendor/tokio/.cargo-checksum.json`

Caused by:
  No such file or directory (os error 2)
```

`/home/william/.cargo/git/checkouts/tokio-c37f2f85799e8a25/2fd1551/tokio` exists and is correctly checked out and a valid crate source. vendor/tokio as a folder does not exist.

`/home/william` is a symlink to `/home/886b45ce-98b2-4d79-9069-c9ff25bc0232` which is the stable path of my home content. When running cargo vendor without this link IE from another user or root, it works correctly. There may be a lack of path resolving in some part of the git routines of cargo vendor. 

An example reproducer is described in "steps". 

with CARGO_LOG=trace:

```
   Vendoring syn v1.0.85 (/home/william/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.85) to /dev/shm/cargo-vendor-repro/vendor/syn
[2022-01-07T00:36:32Z DEBUG globset] glob converted to regex: Glob { glob: "benches/**/*", re: "(?-u)^benches(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true }, tokens: Tokens([Literal('b'), Literal('e'), Literal('n'), Literal('c'), Literal('h'), Literal('e'), Literal('s'), RecursiveZeroOrMore, ZeroOrMore]) }
[2022-01-07T00:36:32Z DEBUG globset] glob converted to regex: Glob { glob: "src/**/*", re: "(?-u)^src(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true }, tokens: Tokens([Literal('s'), Literal('r'), Literal('c'), RecursiveZeroOrMore, ZeroOrMore]) }
[2022-01-07T00:36:32Z DEBUG globset] glob converted to regex: Glob { glob: "tests/**/*", re: "(?-u)^tests(?:/|/.*/)[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true }, tokens: Tokens([Literal('t'), Literal('e'), Literal('s'), Literal('t'), Literal('s'), RecursiveZeroOrMore, ZeroOrMore]) }
[2022-01-07T00:36:32Z DEBUG globset] built glob set; 5 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 3 regexes
   Vendoring tokio v0.2.13 (https://github.com/fengalin/tokio?tag=tokio-0.2.13-throttling#2fd15518) (/home/william/.cargo/git/checkouts/tokio-c37f2f85799e8a25/2fd1551/tokio) to /dev/shm/cargo-vendor-repro/vendor/tokio
[2022-01-07T00:36:32Z WARN  cargo::sources::path] list_files_git tokio v0.2.13 (https://github.com/fengalin/tokio?tag=tokio-0.2.13-throttling#2fd15518)
[2022-01-07T00:36:32Z DEBUG cargo] exit_with_error; err=CliError { error: Some(failed to sync

    Caused by:
        0: failed to write `/dev/shm/cargo-vendor-repro/vendor/tokio/.cargo-checksum.json`
        1: No such file or directory (os error 2)), exit_code: 101 }
[2022-01-07T00:36:32Z DEBUG cargo] display_error; err=failed to sync

    Caused by:
        0: failed to write `/dev/shm/cargo-vendor-repro/vendor/tokio/.cargo-checksum.json`
        1: No such file or directory (os error 2)
error: failed to sync

Caused by:
  failed to write `/dev/shm/cargo-vendor-repro/vendor/tokio/.cargo-checksum.json`

Caused by:
  No such file or directory (os error 2)
```

### Steps

1. `mkdir /home/realhome`
2. `ln -s /home/demouser /home/realhome`
3.  `useradd -d /home/demouser demouser`
4. `sudo -u demouser -s`
5. `git clone https://github.com/Firstyear/cargo-vendor-repro.git`
6. cd cargo-vendor-repro
7. cargo vendor

### Possible Solution(s)

the handlers for git sources in cargo vendor should be fixed to properly handle if a symlink exists in the path to .cargo. 

### Version

```text
# cargo version --verbose
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```
```

**Comment by liuw** [comment] 2022-04-17 11:24
I hit the same issue because my `.cargo` directory is a symlink. What help is needed to fix this?

**Comment by liuw** [comment] 2022-04-17 12:38
I did a bit of quick debugging. In this particular loop, `file_path` does not start with `pkg_path` due to symlink is present.

https://github.com/rust-lang/cargo/blob/b75281bee39818bd538f81dd8f82ec2fec059a39/src/cargo/sources/path.rs#L287-L298

For example, my `.cargo` is linked to `/work/dotcargo`. The two paths can be:

```
file_path "/work/dotcargo/git/checkouts/kvm-bindings-c6b55506be61a061/52e56d0e8ef0/.cargo-ok"
pkg_path  "/home/wei/.cargo/git/checkouts/kvm-bindings-c6b55506be61a061/52e56d0e8ef0"
```

**Comment by liuw** [comment] 2022-04-17 12:45
I did a bit of quick debugging. In this particular loop, `file_path` does not start with `pkg_path` due to symlink is present.

https://github.com/rust-lang/cargo/blob/b75281bee39818bd538f81dd8f82ec2fec059a39/src/cargo/sources/path.rs#L287-L298

For example, my `.cargo` is linked to `/work/dotcargo`. The two paths can be:

```
file_path "/work/dotcargo/git/checkouts/kvm-bindings-c6b55506be61a061/52e56d0e8ef0/.cargo-ok"
pkg_path  "/home/wei/.cargo/git/checkouts/kvm-bindings-c6b55506be61a061/52e56d0e8ef0"
```

**Comment by liuw** [comment] 2022-04-17 12:48
I did a bit of quick debugging. In this particular loop, `file_path` does not start with `pkg_path` due to symlink is present.

https://github.com/rust-lang/cargo/blob/b75281bee39818bd538f81dd8f82ec2fec059a39/src/cargo/sources/path.rs#L287-L298

For example, my `.cargo` is linked to `/work/dotcargo`. The two paths can be:

```
file_path "/work/dotcargo/git/checkouts/kvm-bindings-c6b55506be61a061/52e56d0e8ef0/.cargo-ok"
pkg_path  "/home/wei/.cargo/git/checkouts/kvm-bindings-c6b55506be61a061/52e56d0e8ef0"
```

**Comment by liuw** [comment] 2022-04-17 19:24
It appears my attempt to fix this issue has failed because it broke Windows.

For people like me who has `.cargo` symlinked, this issue can be easily worked around by using `CARGO_HOME=$(readlink -f ~/.cargo) cargo vendor`.

**Comment by weihanglo** [comment] 2023-04-18 20:57
This is a duplicate of #8443. Closing in favor of that. Thank you!

**Closed by weihanglo** 2023-04-18 20:57 UTC
Labels: C-bug, E-needs-mentor, Command-vendor, A-filesystem
