### ISSUE TITLE
Missing `cargo install --upgrade`

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/cargo#6475] opened 2018-12-22 00:27 UTC
The current procedure for updating a binary installed via `cargo` isn't ergonomic and is prone to human error, as there is no one-stop process for installing an updated version of a package if it exists, else leaving the current version undisturbed.

The default behavior of `cargo install foo` when `foo` is already installed is to fail to install with an error message that contains enough information to determine whether or not the output is out of date:

```
~> cargo install racer
    Updating crates.io index
  Installing racer v2.1.16
error: binary `racer` already exists in destination as part of `racer v2.1.16`
Add --force to overwrite
```

So the current process for *possibly* upgrading a package requires
1. `cargo install foo` 
2. Observe the output and compare the information about the currently installed version of `foo` vs the version of `foo` that was found in the index.
3. If an upgrade is available, run `cargo install foo` again, but this time with the `--force` flag.

(The alternative is to use `--force` from the beginning, forcing a lengthy recompile process and wasting far more time than the above.)

**Comment by ehuss** [comment] 2018-12-22 01:14
Thanks for the report!  This is a duplicate of #2082, so closing in favor of that.  There's [cargo-update](https://crates.io/crates/cargo-update) which handles upgrades.

**Closed by ehuss** 2018-12-22 01:14 UTC
Labels: C-feature-request
