### ISSUE TITLE
cargo-init would be super nice

### ISSUE THREAD

**Issue by lightsofapollo** [rust-lang/cargo#21] opened 2014-06-14 19:39 UTC
Something like cargo-init to bootstrap a new project would be very nice (mainly creating the toml file if it does not exist and maybe other flags in the future)

**Comment by andrewrk** [comment] 2015-01-13 16:00
The existing directory case is much more common than the new case. So far every time I've used cargo new it's looked like this (cursing and expletives removed):

```sh
~/dev/my-rust-project$ cargo new
Usage:
    cargo new [options] <path>
    cargo new -h | --help
~/dev/my-rust-project$ cargo new .
Destination `~/dev/my-rust-project` already exists
~/dev/my-rust-project$ cargo new my-rust-project
~/dev/my-rust-project$ ls
my-rust-project
$ mv my-rust-project/ ../
mv: overwrite ‘../my-rust-project’? n
~/dev/my-rust-project$ cd ..
~/dev$ mv my-rust-project/ aoeuaoeu
~/dev$ mv aoeuaoeu/my-rust-project/ ./
~/dev$ cp -r aoeuaoeu/* my-rust-project/
~/dev$ rmdir aoeuaoeu/
~/dev$ cd my-rust-project/
```

Not a positive user experience, to say the least.

**Comment by pornel** [comment] 2015-05-15 23:16
I've ran into this when I wanted to convert a C toy project to rust. 

I don't want any fancy autocargoification. I just want a template for Cargo.toml, because I don't remember its syntax.

**Comment by ArielCabib** [comment] 2015-05-19 18:35
@andrewrk If you're working under *nix, run
```
cargo new tmp --bin
mv tmp/Cargo.toml tmp/.git tmp/.gitignore tmp/src .
rmdir tmp
```
It's ugly, but it works

**Comment by andrewrk** [comment] 2015-05-19 18:41
@ArielCabib so, *getting the project working at all* is not an issue. The issue is that it could be much more straightforward. Hence, this issue filed on the cargo project. Thanks for providing a workaround, but it misses the point.

**Comment by shaleh** [comment] 2015-08-28 19:53
Is there opposition to this? I am willing to submit a pull request if it will be accepted.

Do we want `cargo new --dir .` or is `cargo init` as suggested above ok?

My work flow looks a lot like @andrewrk's.

**Comment by pornel** [comment] 2015-08-29 12:22
@shaleh is the `--dir` necessary? I hoped the logic would be that if the argument to `new` is a path that exists, then filename part of resolved path is used, so that `cd foo; cargo new .` and `cargo new /baz/foo/` create a `foo` project.

**Comment by shaleh** [comment] 2015-08-29 18:21
No it is not needed. It was offered to start the conversation.

On August 29, 2015 5:22:14 AM PDT, Kornel <notifications@github.com> wrote:
>@shaleh is the `--dir` necessary? I hoped the logic would be that if
>the argument to `new` is a path that exists, then filename part of
>resolved path is used, so that `cd foo; cargo new .` and `cargo new
>/baz/foo/` create a `foo` project.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/cargo/issues/21#issuecomment-135980676

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by rasendubi** [comment] 2016-01-25 08:43
Now when #2081 is merged, this issue can be finally closed?

**Comment by alexcrichton** [comment] 2016-01-25 17:38
Thanks for the reminder @rasendubi, and thanks again @vi for the implementation!

**Closed by alexcrichton** 2016-01-25 17:38 UTC
Labels: A-new-subcommand, C-new, planned

**Comment by shaleh** [comment] 2016-01-25 17:51
yay!! Bummed my life got in the way but happy someone else stepped in.

**Comment by e-oz** [comment] 2016-11-22 20:42
cargo init still can't init project in existing folder, not sure this issue is closed.

Rust beta 14, macos sierra:

OZ:**repositories** OZ$ cd feed_importer/
OZ:**feed_importer** OZ$ cargo init feed_importer --bin --vcs none
OZ:**feed_importer** OZ$ ls
feed_importer
OZ:**feed_importer** OZ$ ls feed_importer/
Cargo.toml	src

**Comment by carols10cents** [comment] 2016-11-22 21:07
@e-oz It looks like you specified a path, but it seems like you wanted to use the current directory. Instead of `cargo init feed_importer --bin --vcs none`, what if you run `cargo init --bin --vcs none`?

**Comment by e-oz** [comment] 2016-11-22 21:10
@carols10cents I thought I specified `package.name`. Thank you, without name everything works fine. Sorry for false report.

**Comment by DanielJoyce** [comment] 2017-04-28 03:24
Yep, still doesn't work.
