### ISSUE TITLE
Package files are randomly filled with `\u{0}`

### ISSUE THREAD

**Issue by SkyfallWasTaken** [rust-lang/cargo#10689] opened 2022-05-21 14:40 UTC
### Problem

**What I expected to happen:**
No errors
**What actually happened:**
Depedency files are randomly filled with `\u{0}`, causing the build to fail. The file cannot be opened in an editor due to invalid encoding.

This is what the error looks like:
```
error[E0601]: `main` function not found in crate `build_script_build`
 --> C:\Users\Mahad\.cargo\registry\src\github.com-1ecc6299db9ec823\crunchy-0.2.2\build.rs:1:6600
  |
1.| 
  | ^ consider adding a `main` function to `C:\Users\Mahad\.cargo\registry\src\github.com-1ecc6299db9ec823\crunchy-0.2.2\build.rs`
```

### Notes

The bug is quite rare, and afaik there is no correlation between the two errors (the last one was for `diff`)

### Version

```text
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
```

**Comment by gimbles** [comment] 2022-05-22 08:59
Are you using Powershell by any chance?

**Comment by SkyfallWasTaken** [comment] 2022-05-22 17:16
Yep!

**Comment by eminence** [comment] 2022-11-24 04:37
@gimbles can you say why you asked about PowerShell?  I'm wondering if maybe you've seen something like this before, and PowerShell was somehow related

**Comment by weihanglo** [comment] 2024-03-23 21:11
This might be somehow related to <https://github.com/rust-lang/cargo/issues/9455>?

**Comment by weihanglo** [comment] 2024-03-23 21:18
This is a duplicate of <https://github.com/rust-lang/cargo/issues/8242>. Close in favor of that. Thank you.

**Closed by weihanglo** 2024-03-23 21:18 UTC
Labels: C-bug, O-windows, S-needs-info
