### ISSUE TITLE
Cargo needlessly updates a git repository and aborts when that fails (because I’m offline.)

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1265] opened 2015-02-02 23:14 UTC
I was upgrading Servo with to Cargo 174d232 2015-01-29 from a early-ish January version, on an airplane, without connectivity. After a number of changes and operations that went on fine online, Cargo decided that it needed to update the repository for a git dependency:

```
% mach build -p script
    Updating git repository `https://github.com/servo/skia`
Unable to update https://github.com/servo/skia?branch=upstream-2014-06-16
```

I was then unable to do anything else with Cargo until I was back online, even though I know the repository to be up-to-date. Then the error message became:

```
    Updating git repository `https://github.com/servo/skia`
no matching package named `skia-sys` found (required by `azure`)
location searched: https://github.com/servo/skia?branch=upstream-2014-06-16
version required: *
```

This turned out to be because one dependency was declared as:
```
[dependencies.skia-sys]
git = "https://github.com/servo/skia"
branch = "upstream-2014-06-16"
```

… but the crate name is `skia`, not `skia-sys`. Earlier Cargo version apparently tolerated this.

But the point that I’m trying to make is that when a network operation such as updating a git repository fails, Cargo should try to continue with whatever information exists in the local cache.

**Comment by alexcrichton** [comment] 2015-02-04 06:19
I'm a little confused by this, did you have a `Cargo.lock` which was modified while offline? If Cargo doesn't have an entry in `Cargo.lock` for a dependency, then it *must* hit the network to determine what the dependency actually is.

**Comment by SimonSapin** [comment] 2015-02-04 06:34
The sequence of things was roughly:

* Start from Servo master
* Update both Rust and Cargo snapshots
* See tons of build errors
* Run `cargo update`
* See different build errors, but still tons of them
* Fix many things in both Servo and dependencies, adding path overrides one by one
* Go offline
* Fix many more things in both Servo and dependencies, adding path overrides one by one, including in skia and in layers (which had the bogus skia-sys dependency)
* At some points Cargo decides to update the Skia repo (which I know is already up to date) and I’m stuck
* Go back online
* The next build results in ``no matching package named `skia-sys` found`` showing the underlying issue.

Now, I started writing this bug report before I found out about the bogus skia-sys dependency. At the time it really seemed surprising that network access was suddenly needed, but in retrospect it might make sense: Cargo is asked to find skia-sys in git+https://github.com/servo/skia, but the current commit (the one in `Cargo.lock`) doesn’t have it so Cargo assumes it might have been added later and tries to update.

Maybe it shouldn’t try to update outside of `cargo update` when `Cargo.lock` specifies a git commit to use?

**Comment by SimonSapin** [comment] 2015-02-04 06:41
Oops, forget to answer your question. No, I don’t believe `Cargo.lock` was modified while offline. I only ran `cargo build` or `cargo build -p something`, and none of these succeeded.

**Comment by alexcrichton** [comment] 2015-03-03 04:25
Sorry for being a little slow to get back on this! I just gave this a good deal of though, and in the end I'm going to close this as working as intended.

Cargo treats the sources of each package independently so in your example the original dependency on `skia` was a "locked source" but when the accidental dependency on `skia-sys` was introduced it made an "unlocked source" come into existence. Depending on the order of resolution, we could either update `skia` if we see the unlocked source first or we could attempt to use the locked source. 

Right now it's currently nondeterministic which dependency we hit first (presumably because of a `HashMap` somewhere), but regardless I don't think that this can be fixed. There are many different traversals of a dependency graph which could lead us to the locked or unlocked source first, and I can't think of a way that the ones hitting the unlocked source first are "wrong".

In general, I think that Cargo's policy on this is that an unlocked source is basically a scenario where that source *may* be updated to a newer version. There are some cases that it could continue to use the older version, but that can't always be guaranteed. So all in all while I agree that this is unfortunate, I'm going to close this as intended behavior. The only way that Cargo can guarantee that no network requests are made is by requiring a lockfile in addition to all dependencies being downloaded already as if `cargo fetch` was just run.

**Closed by alexcrichton** 2015-03-03 04:25 UTC

**Comment by SimonSapin** [comment] 2015-03-03 07:21
Ok, fair enough. Thanks for taking the time to look into it! I’ll try `cargo fetch` next time I know I’m going to be offline.
