### ISSUE TITLE
`cargo check` recompiles dependencies when checking lib and bin separately

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#3421] opened 2016-12-17 10:34 UTC
For this project:

Cargo.toml:
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
rand = "*"

```

src/lib.rs:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
    }
}
```

src/bin/bar.rs: `fn main() {}`

`cargo check` does this:
```
$ cargo check --lib
   Compiling libc v0.2.18
   Compiling rand v0.3.15
   Compiling foo v0.1.0 (file:///tmp/foo)
    Finished debug [unoptimized + debuginfo] target(s) in 4.87 secs
$ cargo check --bin bar
   Compiling libc v0.2.18
   Compiling rand v0.3.15
   Compiling foo v0.1.0 (file:///tmp/foo)
warning: function is never used: `main`, #[warn(dead_code)] on by default
 --> src/bin/bar.rs:1:1
  |
1 | fn main() {}
  | ^^^^^^^^^^^^

```

**Comment by alexcrichton** [comment] 2016-12-17 22:56
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/3418, so closing in favor of that, but thanks for the report!

**Closed by alexcrichton** 2016-12-17 22:56 UTC
