### ISSUE TITLE
cargo update hangs in cargo::core::resolver::activate_deps_loop

### ISSUE THREAD

**Issue by codewiz** [rust-lang/cargo#4108] opened 2017-05-28 14:05 UTC
I hit this while running "cargo update" on the master branch of https://github.com/paritytech/parity .

Trace: [cargo-update.txt](https://github.com/rust-lang/cargo/files/1034209/cargo-update.txt)
Produced with `RUST_LOG=cargo::core::resolver=trace cargo generate-lockfile`

[Cargo.lock.txt](https://github.com/rust-lang/cargo/files/1034211/Cargo.lock.txt)
[Cargo.toml.txt](https://github.com/rust-lang/cargo/files/1034212/Cargo.toml.txt)

**Comment by codewiz** [comment] 2017-05-28 14:08
Affects both cargo 1.18 and cargo nightly 0.20.0-nightly (9fcdbb44f 2017-05-22)

**Comment by bennofs** [comment] 2017-05-28 14:29
Looks like the problem is that `multihash` depends on `ring ~0.7.1` which has been yanked --> the solver never finds a solution for `ring` and backtracks through the entire search space.

**Comment by bennofs** [comment] 2017-05-28 14:51
The activation/backtracking chain seems to go something like this:

```
... -> isatty -> bitflags -> rpassword -> semver -> pretty_assertions -> difference -> matches -> quine-mc_cluskey -> miow -> multihash -> ring (fail)
```

and for each of the packages in the chain, cargo tries a few possibilities (and the chain is probably longer)

**Comment by alexcrichton** [comment] 2017-05-30 18:30
Thanks for the investigation @bennofs! In that case I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/4066 as I think it's a dupe of that issue.

**Closed by alexcrichton** 2017-05-30 18:30 UTC
