### ISSUE TITLE
Add cargo upgrade

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/cargo#13045] opened 2023-11-24 21:28 UTC
### Problem

cargo-edit's `cargo update` is having problems lately.
It should be uplifted to cargo itself. It's a really useful feature

### Notes

If someone could mentor me I could try to tackle this.

**Comment by weihanglo** [comment] 2023-11-24 22:10
Thanks for the suggestion. If I understand correctly, this is kinda a duplicate of <https://github.com/rust-lang/cargo/issues/10498>?

**Comment by dev-ardi** [comment] 2023-11-24 23:19
Sorry for the duplicate, there are a lot of issues! If this is currently being worked on that's fine, else I could work on this.

**Comment by epage** [comment] 2023-11-24 23:24
The reason I've not been focusing on cargo-upgrade is because that time would be better spent on that issue to merge its behavior.

Things keep coming up so I've not finished it yet. If you'd like to finish it, go ahead. The other issue has notes on the design the cargo team decided on. On our github wiki you can find office hours to talk to us, in addition to on issues/prs and zulip.

**Closed** 2023-11-24 23:24 UTC
Labels: C-feature-request, S-triage

**Comment by dev-ardi** [comment] 2023-11-26 22:11
@epage on second thought this seems too daunting for a first contribution.
