### ISSUE TITLE
Permission denied (os error 13) when cargo build

### ISSUE THREAD

**Issue by yyh1102** [rust-lang/cargo#6757] opened 2019-03-16 18:33 UTC
**Problem**
After i install rust and cargo using `curl https://sh.rustup.rs -sSf | sh`, and try to build a new project, An error threw:

![image](https://user-images.githubusercontent.com/10328169/54479895-f0768100-485c-11e9-8620-9e1caeb4c67c.png)

And if i use `sudo cargo build`, it fix. 
But at some situation i have to use just `cargo build`, how can i solve the problem?

**Notes**
OS: mac OS Mojave 10.14.3
Output of `cargo version`: cargo 1.33.0 (f099fe94b 2019-02-12)

**Comment by ehuss** [comment] 2019-03-22 18:37
It sounds like there are some permission issues in your home directory.  You may have better luck asking on one of the forums (like https://users.rust-lang.org/) or maybe one of the chat platforms (like [Discord](https://bit.ly/rust-community)).

**Comment by collin5** [comment] 2019-03-29 15:32
@yyh1102 Have you tried changing permissions of cargo home dir. i.e 
```bash
$ sudo chown -R $(whoami) /Users/lowesyang/.cargo/
```

**Comment by ehuss** [comment] 2019-04-04 17:14
I'm going to close this, this does not seem to be a cargo issue.

**Closed by ehuss** 2019-04-04 17:14 UTC
Labels: C-bug

**Comment by jeromegn** [comment] 2019-04-10 20:22
I've started getting the same recently, I ran it with RUST_LOG=debug and got:

```
$ RUST_LOG=debug RUST_BACKTRACE=1 cargo build --bin runner
...
[2019-04-10T20:17:35Z DEBUG globset] built glob set; 0 literals, 2 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
[2019-04-10T20:17:35Z INFO  cargo::util::rustc] updated rustc info cache
[2019-04-10T20:17:35Z DEBUG cargo] exit_with_error; err=CliError { error: Some(Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h8d6d9abeadb47698 (0x560037bbe9f3)
   1: failure::backtrace::Backtrace::new::hc66590c50d3d5a2a (0x560037bbe69f)
   2: cargo::sources::path::PathSource::walk::h156df4e3b728b6cd (0x5600376ea601)
   3: cargo::sources::path::PathSource::walk::h156df4e3b728b6cd (0x5600376ea955)
   4: cargo::sources::path::PathSource::list_files::h7bdb580f82226180 (0x5600376e761e)
   5: cargo::sources::path::PathSource::last_modified_file::h327eac454607eb9c (0x5600376eabcd)
   6: <cargo::sources::path::PathSource<'cfg> as cargo::core::source::Source>::fingerprint::he55956dc9cd9bc4c (0x5600376eb815)
   7: cargo::core::compiler::fingerprint::pkg_fingerprint::hc05670626ba10a80 (0x56003775cc9c)
   8: cargo::core::compiler::fingerprint::prepare_build_cmd::hb5f29c2698ba1b07 (0x560037759366)
   9: cargo::core::compiler::custom_build::prepare::h28cf21ba620f65f9 (0x560037511e7b)
  10: cargo::core::compiler::compile::h87829c6f40288c15 (0x56003775ef06)
  11: cargo::core::compiler::compile::h87829c6f40288c15 (0x56003775f4ab)
  12: cargo::core::compiler::compile::h87829c6f40288c15 (0x56003775f4ab)
  13: cargo::core::compiler::context::Context::compile::hc59394fe8834cb3d (0x5600376d2ce4)
  14: cargo::ops::cargo_compile::compile_ws::hcd03deb2dd8e37c3 (0x5600374a5af0)
  15: cargo::ops::cargo_compile::compile::h57d9550ec550a472 (0x5600374a1db8)
  16: cargo::commands::build::exec::hc595c6a2b98b3047 (0x56003742b17d)
  17: cargo::cli::main::hbbce86d40638f2f0 (0x5600373f0c55)
  18: cargo::main::ha6397e0193ae2834 (0x56003740ee1f)
  19: std::rt::lang_start::{{closure}}::h783b28c4e06ed518 (0x560037404ca2)
  20: {{closure}} (0x560037be5812)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:297
  21: __rust_maybe_catch_panic (0x560037bf18f9)
             at src/libpanic_unwind/lib.rs:87
  22: try<i32,closure> (0x560037be63dc)
             at src/libstd/panicking.rs:276
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  23: main (0x560037411441)
  24: __libc_start_main (0x7f6db17d8222)
  25: <unknown> (0x5600373e6028)), unknown: false, exit_code: 101 }
error: Permission denied (os error 13)
```

I've added anything that's chowned by root or any other user to the `exclude` package field in my Cargo.toml.

My `~/.cargo` is all recursively chowned by me.

Not sure how to fix this now. The backtrace is a bit obscur.

**Comment by chanks** [comment] 2019-09-14 19:32
I've run into this a couple of times. The `chown` method above didn't help, but `cargo clean` followed by a `cargo build` has fixed it. Next time I'll try building with `sudo`.

**Comment by joseluisq** [comment] 2019-12-12 21:44
> I've run into this a couple of times. The `chown` method above didn't help, but `cargo clean` followed by a `cargo build` has fixed it. Next time I'll try building with `sudo`.

@chanks answer worked for me. Thanks!

**Comment by zwobill** [comment] 2019-12-25 07:58
I am running into this issue with [VSCode Remote Try Rust](https://github.com/microsoft/vscode-remote-try-rust). Cargo prints `error: Permission denied (os error 13)` I've tried way mentioned above. `chown`, `cargo clean`, didn't help. Now I don't know where it gets access denied. I think we could improve the error message by including a little bit more context.

**Comment by i-schuetz** [comment] 2020-06-13 18:23
@zwobill Could you create an issue for that maybe? Or anyone reopen this? It would be really helpful.

**Comment by i-schuetz** [comment] 2020-06-13 19:45
To me also nothing did work. I ran `chown -R` on my home directory, `cargo clear`, etc. So I've no idea what to do. Prepending `RUST_LOG=debug RUST_BACKTRACE=1` to `cargo build` also isn't showing additional output.

**Comment by bobural** [comment] 2020-06-23 00:22
Not sure if this will help but for me the issue (I am running Ubuntu WSL on windows10) this appeared when using "cargo new project_name --bin". If I am using "cargo new project_name" without the "--bin" the issue was fixed.

**Comment by abcaptainDEV** [comment] 2020-06-26 16:23
I was using VSCode aswell, running `sudo cargo clean` fixed it, now `cargo build` (no sudo) works fine.

**Comment by Groumph** [comment] 2020-07-19 21:47
I just installed rustup and cargo through
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

The system in Ubuntu 20.04 in WSL 2.0.

Executing "cargo build" results in:

> Compiling HelloWorld v0.1.0 (/mnt/d/Development/Rust/HelloWorld/HelloWorld)
> warning: crate `HelloWorld` should have a snake case name
>   |
>   = note: `#[warn(non_snake_case)]` on by default
>   = help: convert the identifier to snake case: `hello_world`
> 
> error: could not exec the linker `cc`
>   |
>   = note: Permission denied (os error 13)
>   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.1el6wjpgj1dkfwf0.rcgu.o" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.3962bg4u1ufd0i2o.rcgu.o" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.3nay2hs8vzowo41p.rcgu.o" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.3y5j67vbwdt6naio.rcgu.o" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.523znc2qtgcslg12.rcgu.o" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.s16bxban93wagks.rcgu.o" "-o" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps/HelloWorld-d682f606e8563e0e.454le8qbyd52a29h.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/mnt/d/Development/Rust/HelloWorld/HelloWorld/target/debug/deps" "-L" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c147cd9c030850ef.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-7e62a3a07bb85bc1.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-000f77165d4d2d36.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-7dc0cb59ed386ac6.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-9248bfbd7273ac3d.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-b75363fb938de39d.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-7bbe96f555da4ad6.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-a145493c64eeb044.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-9577436fc6fce6bc.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-b3376c0a2b35415c.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-5708f6b2b59b6e0f.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-e9fd09201d99d6f4.rlib" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-914c6ef6f5cf354a.rlib" "-Wl,--end-group" "/home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-1445b6c7903692a2.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
> 
> error: aborting due to previous error; 1 warning emitted
> 
> error: could not compile `HelloWorld`.
> 
> To learn more, run the command again with --verbose.

**Comment by dchen327** [comment] 2020-07-30 22:30
I'm having a similar issue: when using the rustup install command from the rust homepage `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`, I get these errors:
```
error: could not amend shell profile: '/home/dchen327/.bash_profile'
error: caused by: could not write rcfile file: '/home/dchen327/.bash_profile'
error: caused by: Permission denied (os error 13)
```

I'm running Pop! OS 20.04.

**Comment by Peter-L-SVK** [comment] 2020-12-03 11:44
Running Fedora 32 after time, I've decided to come back after some time to play with Rust:
error: command failed: 'rustc'
error: caused by: Permission denied (os error 13)

**Comment by rsweeney21** [comment] 2020-12-04 01:31
I was able to fix this this issue on WSL 2.0 by running.

`sudo apt install build-essential`

The Linux Rust installer doesn't check for a compiler toolchain, but seems to assume that you've already got a C linker installed.

Hopefully this helps someone else in the future.

**Comment by JakePi3** [comment] 2020-12-27 20:48
Also on WSL 2.0, the os error 13 doesn't seem to differentiate between being unable to write to a file, failing to execute due to permissions or a missing executable.

To fix my problems, `build-essential` wasn't enough, I also had to install `clang` and `cmake`  through apt, though that probably doesn't affect everyone.

**Comment by Kambaa** [comment] 2020-12-31 22:35
I'm having this problem on my WSL, installing build-essential, clang and cmake did not worked for me. Tried with sudo, that did not work too. Please advise.

**Comment by juhams** [comment] 2021-04-11 19:01
close vscode , carcgo clean , cargo run

**Comment by shiranningning** [comment] 2021-04-18 03:44
> close vscode , carcgo clean , cargo run

it works，but why? How does vscode affect this？

**Comment by M0hammedImran** [comment] 2021-04-25 12:36
In some weird way closing vscode and running cargo working as expected. But when vscode is open in a remote session I get ```console error: caused by: Permission denied (os error 13)``` 
I'm running ```console rustc 1.51.0 (2fd73fabe 2021-03-23)``` on Ubuntu 20.04 ie. WSL1

**Comment by Taptiive** [comment] 2021-04-26 01:31
These are the steps i followed to solve this on WSL 2 with Arch:

1. Close VS Code
2. Reopen WSL Terminal
2. If your project folder is inside your Windows files try moving it into the linux home directory
3. cargo clean
4. cargo run

I hope this is useful for someone.

**Comment by joeftiger** [comment] 2021-05-01 14:30
I have the same issue under Arch Linux. 

I installed `rustup` with the distro's package manager `pacman`. I never had problems until very recently. 
`cargo-config` installed fine, but `xargo` fails with os error 13. I chowned everything in my home directory, reinstalled rustup but still no luck usin `cargo install xargo`.

**Comment by mrl00** [comment] 2021-08-28 21:04
export CARGO=$CARGO_HOME/bin/cargo, where CARGO_HOME=$HOME/.cargo 
worked for me

**Comment by hobbytp** [comment] 2021-12-27 02:26
I fixed it by following steps:

sudo apt install build-essential 
and then https://github.com/rust-lang/cargo/issues/6757#issuecomment-826444331

**Comment by itsezc** [comment] 2021-12-28 10:14
Tried all of the approaches above :

- Chown
-  Installing `build-essential`, `cmake`, `clang`
- Closing VSCode
- Running `cargo clean` and `cargo run`

on WSL 2 with Ubuntu, no luck. Cannot run cargo as sudo as I've used rustup to install cargo.

**Comment by gponce-ars** [comment] 2022-01-11 01:10
This error is also triggered when running things inside `Google Drive` folder.  Is this related to the the type of filesystem sort of thing or just a bad practice of having Git folder inside Google Drive folder?

This is happening on Mac OS version:
```
$uname -a 
Darwin iMac.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
$rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

When I tested in my local folder `/Users/my_user/` everything works fine.

**Comment by fahadalisarwar1** [comment] 2022-03-04 20:02
I has to do following steps

1. remove existing rust installation
2. close wsl
3. open it again
4. sudo apt-get install build-essential cmake clang
5. install rust for wsl
6. close wsl again
7. open it again and it should work 
I am using an AMD based machine

**Comment by appetrosyan** [comment] 2022-05-30 04:55
Can reproduce on Arch. `chown --R` in the `CARGO_HOME`, `RUSTUP_HOME` and the project directory did nothing. What did help was mounting the target dir as tmpfs. The first thing that fails to execute is a build script.
```
sudo mount -t tmpfs none ./target
```

To me, this issue would have been much easier to fix, if the default output included the file which caused the issue. `cargo` spits out a butt load of information in other error cases (e.g. running out of space in the ramdisk, or running out of RAM in general) so please include the offending file in the output (and that is a cargo issue).

**Comment by jackwener** [comment] 2022-08-20 15:16
macOS fixed by [this answer](https://stackoverflow.com/questions/61899041/permission-denied-apply2files-usr-local-lib-node-modules-expo-cli-node-modu/63241724#63241724)

**Comment by dzmitry-lahoda** [comment] 2022-11-29 09:24
i am trying to build vendor in nix and getsame error. knowing where permission denied would help a lot. thank you.

**Comment by cplir-c** [comment] 2023-05-31 06:05
I had this issue yesterday, and running with sudo with the clang and gcc toolchains installed didn't help.
I ended up telling cargo to build targets in `/tmp/cargo-target`:

~/.cargo/config:
```toml
[build]
target-dir = "/tmp/cargo-target"
```

**Comment by themighty1** [comment] 2023-07-21 10:42
fwiw, running `strace cargo build` will show you the offending path which triggered this error.

**Comment by Valerka2307** [comment] 2023-11-03 18:33
I had the same problem. When I reinstalled my os, I downloaded my directories to the cloud. After reinstalling returned my data to home and found this problem. I solved this by recoping code to similar directory which created from scratch.

**Comment by huongnguyenduc** [comment] 2023-11-24 04:23
Just run `sudo rm -rf ./target/debug` and `cargo build`, and it will work again.

**Comment by appetrosyan** [comment] 2023-11-24 09:23
@huongnguyenduc Aside from this being recommended more than 5 times in just this thread, it doesn’t work for everyone.

**Comment by amesy** [comment] 2024-02-20 02:58
> @yyh1102 Have you tried changing permissions of your cargo home dir. i.e
> 
> ```shell
> $ sudo chown -R $(whoami) /Users/lowesyang/.cargo/
> ```

thank you, this very useful.

**Comment by Sberm** [comment] 2024-03-24 16:06
For me it's not having permission to write to target dir,  then the solution becomes
```bash
sudo chown -R $(whoami) <project-dir>
```

**Comment by TAOFOR4** [comment] 2024-05-06 18:59
Hi, my issue is
```
error: failed to read `/Cargo.toml`

Caused by:
  Permission denied (os error 13)
```
I've tried all the methods here but doesn't work. I am in Ubuntu 22 not WSL but a real OS.

**Comment by cplir-c** [comment] 2024-05-07 03:53
> Hi, my issue is
> 
> ```
> error: failed to read `/Cargo.toml`
> 
> Caused by:
>   Permission denied (os error 13)
> ```
> 
> I've tried all the methods here but doesn't work. I am in Ubuntu 22 not WSL but a real OS.

On unix-like systems like Ubuntu, `/` is the root of the file system, like of like the default `C:\\` on Windows. Your path there is in that filesystem root directory. Maybe you meant `./Cargo.toml` or just `Cargo.toml` to refer to one in your current directory?

**Comment by mustzev** [comment] 2024-09-01 21:08
In my case, I was using a Linux system but my project folder was on a mounted hard drive with FAT file system. I formatted the hard drive with Ext4 file system (the same as my Linux system drive), copied over my project folder again, and everything worked okay.

**Comment by cybergazer** [comment] 2024-10-10 21:11
Closed issue, 50+ upvotes, 0 fix. This issue makes tauri unusable

**Comment by kurushimee** [comment] 2024-10-12 05:32
Had this issue on Ubuntu WSL2 under Windows 11. Fixed it by installing gcc and clang which were missing, not sure which of the two was actually required

**Comment by gibbygano** [comment] 2024-12-05 14:13
> Had this issue on Ubuntu WSL2 under Windows 11. Fixed it by installing gcc and clang which were missing, not sure which of the two was actually required

This fixed it for me on WSL.

**Comment by lxl66566** [comment] 2025-01-03 05:27
> Had this issue on Ubuntu WSL2 under Windows 11. Fixed it by installing gcc and clang which were missing, not sure which of the two was actually required

My error message is "could not exec the linker `cc`"; Installing gcc in WSL fixes this.

**Comment by Chaz6** [comment] 2025-02-28 18:42
I am having a similar issue, using the official Rust docker image (running on AlmaLinux 9.5):-

```
$ podman run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/myapp:Z -w /usr/src/myapp rust:1.85.0 cargo build --release
[..]
error: Permission denied (os error 13) at path "/usr/src/myapp/targetyCxYfX"
```

**Comment by ifigueroap** [comment] 2025-04-12 22:27
In my case, I had to install cmake because otherwise the installation of starship wouldn't work.

**Comment by cyrilluce** [comment] 2025-06-25 02:50
FYI
MacOS, I finally found it's cause by `cmake`
> % cmake --help
> zsh: permission denied: cmake

Update cmake by homebrew fix it
> brew install cmake

**Comment by TheCukitoDev** [comment] 2025-07-10 11:26
Hello, for those who has arrived now, i've solved it just using the power of AI. I was using devcontainers so i didn't new how to solve it because i tried all the solutions everyone has listed here but none of them worked so I just asked copilot agent and surprisingly (and after a few minutes) it solved it for me. This is the issue resume that the AI generated for me to share with you:

# Solution: Permission denied (os error 13) in OXC Dev Container

## Problem
When running `just new-nextjs-rule` in the [oxc-project/oxc](https://github.com/oxc-project/oxc) repository (commit: 94796a0), encountering:
```
Permission denied (os error 13)
```

## Root Cause
The error occurs because Cargo cannot write to its global cache directory registry in the dev container environment. This is common in containerized environments where Cargo directories have restrictive permissions.

## Solution
Create a Cargo configuration file to redirect cache and target directories to writable locations:

````toml
[build]
target-dir = "/tmp/oxc-target"

[net]
offline = false
git-fetch-with-cli = true

[http]
timeout = 60
````

## Additional Environment Variables (Optional)
```bash
export CARGO_HOME="/home/vscode/.cargo"
export CARGO_TARGET_DIR="/tmp/oxc-target"
```

## Verification
After applying the solution, the command should proceed successfully:
```bash
just new-nextjs-rule
```

This solution redirects Cargo's build artifacts to oxc-target where the container has write permissions, resolving the permission denied error.
