### ISSUE TITLE
Add a flag to cargo that enables all features

### ISSUE THREAD

**Issue by esclear** [rust-lang/cargo#3035] opened 2016-08-23 21:08 UTC
I'd like to add a feature to cargo that enables building your project with all available features enabled.
This would be especially helpful when (automatically) building documentation, since one does not need to enable all features manually.

I'm thinking of introducing a `--all-features` flag that does exactly that.  
(Allowing wildcards would be nice as well, but I would only do that if there is such an engine already implemented in cargo)

I'm currently looking for all places where this feature might need to be implemented and will attempt to provide an implementation at esclear/cargo.

**Comment by alexcrichton** [comment] 2016-08-23 23:07
Thanks for the report! I believe this is a dupe of https://github.com/rust-lang/cargo/issues/1173, so I'm going to close in favor of that, but don't let that stop you from prototyping at all!

**Closed** 2016-08-23 23:07 UTC
