### ISSUE TITLE
installation fails on "failed to authenticate when downloading repository" 

### ISSUE THREAD

**Issue by cyisfor** [rust-lang/cargo#2422] opened 2016-02-29 00:42 UTC
using rustc 1.8.0-dev, can't install cargo. Default build fails unconditionally.

to reproduce:
1) clone cargo
2) ./configure
3) make

target/snapshot/bin/cargo build --target x86_64-unknown-linux-gnu --release  
    Updating registry `https://github.com/rust-lang/crates.io-index`
An unknown error occurred

Caused by:
  failed to authenticate when downloading repository

**Comment by alexcrichton** [comment] 2016-02-29 17:08
Could you re-run that command with `-v` to get some more error information as well?

**Comment by tristanwietsma** [comment] 2016-03-17 00:07
Running into the same issue. With verbose on,

```
$ make
/Users/taw/local/bin/rustc -V
rustc 1.9.0-dev (c9629d61c 2016-03-10)
target/snapshot/bin/cargo --version
cargo 0.9.0-nightly (c4c6f39 2016-01-30)
target/snapshot/bin/cargo build --verbose --target x86_64-apple-darwin --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository

Caused by:
  [23/-1] error authenticating:
make: *** [cargo-x86_64-apple-darwin] Error 101
```

Additional Notes:
- I have a valid token in my global gitconfig.

**Comment by alexcrichton** [comment] 2016-03-17 06:52
@tristanwietsma is the error intermittent or reproducible? Failing to authenticate with a connection that doesn't need authentication is odd indeed!

**Comment by tristanwietsma** [comment] 2016-03-17 13:00
Reproducible; never succeeds.

**Comment by alexcrichton** [comment] 2016-03-17 18:03
Oh what does your global `.gitconfig` look like? I think this error only shows up when cloning SSH repositories and that may be happening if something is being redirected with the gitconfig

**Comment by tristanwietsma** [comment] 2016-03-18 17:15
yup, that was it. I had this for `go get`ting private repos over SSH:

```
[url "git@github.com:"]
    insteadOf = https://github.com/
```

Removing solved it. Thanks.

**Comment by alexcrichton** [comment] 2016-03-18 17:50
Ah ok, in that case I'm gonna close this in favor of https://github.com/rust-lang/cargo/issues/2078 as I think it's a dupe of that. Thanks for the investigation though!

**Closed by alexcrichton** 2016-03-18 17:50 UTC
