### ISSUE TITLE
Provide `cargo clean --except-locked` to keep `target/` small in re-used CI caches

### ISSUE THREAD

**Issue by LeoniePhiline** [rust-lang/cargo#12138] opened 2023-05-13 19:04 UTC
### Problem

When caching `target/` in CI, the cache is uploaded and downloaded frequently and must remain manageable in size.

Whenever dependencies have been updated, e.g. by renovate-bot, new versions of crates are compiled and cached in `target/deps/` while old versions are never removed.

`cargo clean` removes all build artifacts, including those of current dependencies - which is not desirable.

### Proposed Solution

 `cargo clean --except-locked`  would inspect the `Cargo.lock` file of the project or workspace and keep all build artifacts of currently locked dependency versions. All other artifacts are deleted, as they would be with `cargo clean`.

### Notes

Arguably `cargo clean` should exactly do that (clean up, not delete everything), while its current behavior can be easily done by hand with a `rm -rf ./target`.

I assume, however, that it is too late to change the default behavior at this point.

**Comment by ehuss** [comment] 2023-05-13 19:12
Thanks for the suggestion!  We are currently tracking this in #7150.  Cargo currently doesn't have a way of knowing which artifacts exist for which purpose. That issue contains some more information and links to similar issues.

Closing as a duplicate of #7150.

**Closed by ehuss** 2023-05-13 19:12 UTC
Labels: C-feature-request, S-triage
