### ISSUE TITLE
Why does `cargo run --example specific_example` build all examples?

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/cargo#1357] opened 2015-02-26 07:54 UTC
I have a project that has multiple independent examples in its `examples/` folder, i.e.
```
examples/
    a.rs
    b.rs
    c.rs
```

When I run the command `cargo run --example a` I would anticipate that only the example `a` and it's dependencies would be required to compile, however it seems that the command builds *all* examples, despite none of them depending on each other and specifically giving only `a` as an argument. Is this expected behaviour? If so, how do I achieve the anticipated behaviour that I described above?

**Comment by alexcrichton** [comment] 2015-02-26 08:27
I believe that this is a dupe of #770, but thanks for the issue!

**Closed by alexcrichton** 2015-02-26 08:27 UTC
