### ISSUE TITLE
fingerprint error causing rebuild on feature flag changes

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/cargo#3923] opened 2017-04-14 02:00 UTC
Switching between  building [rocket](https://github.com/SergioBenitez/Rocket) with and without feature flags causes the `cookie` dependency to be rebuilt each item. The following logs show this:

```
$ cargo build
   Compiling rocket v0.2.4
    Finished dev [unoptimized + debuginfo] target(s) in 21.1 secs
$ cargo build --all-features
   Compiling cookie v0.7.4
   Compiling rocket v0.2.4
    Finished dev [unoptimized + debuginfo] target(s) in 24.31 secs
$ cargo build
   Compiling cookie v0.7.4
   Compiling rocket v0.2.4
    Finished dev [unoptimized + debuginfo] target(s) in 23.16 secs
```

Running with `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info` shows that this is caused by a fingerprint error due to `cookie` in turn due to `ring`.

```
 $ RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info cargo build --all-features
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for cookie v0.7.4: new (ring v0.7.5) != old (ring v0.7.5)
   Compiling cookie v0.7.4
   Compiling rocket v0.2.4
    Finished dev [unoptimized + debuginfo] target(s) in 24.29 secs
```

cc @briansmith

**Comment by alexcrichton** [comment] 2017-04-18 01:24
Sounds bad!

Could you try enabling `fingerprint=debug` to get a few more logs? I'm hopeful that may have some extra information but I'm also not holding my breath

**Comment by SergioBenitez** [comment] 2017-04-18 01:42
Here's the full log:

```
$ RUST_LOG=cargo::ops::cargo_rustc::fingerprint=debug cargo build
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rocket-345600c44cd7c0e1/lib-rocket-345600c44cd7c0e1
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/num_cpus-9d46f9850838cbe9/lib-num_cpus-9d46f9850838cbe9
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/libc-133c2936106da144/lib-libc-133c2936106da144
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/smallvec-0a0a78ad45ad7466/lib-smallvec-0a0a78ad45ad7466
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/hyper-1a84cd390831c3ae/lib-hyper-1a84cd390831c3ae
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/typeable-65ff39e1a79225ed/lib-typeable-65ff39e1a79225ed
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/mime-bccdaf777dcff437/lib-mime-bccdaf777dcff437
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/log-72a4331fc2f8629e/lib-log-72a4331fc2f8629e
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/traitobject-bc224b6576d03647/lib-traitobject-bc224b6576d03647
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/unicase-3bb06bfe1c6860a7/lib-unicase-3bb06bfe1c6860a7
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/unicase-da156157c559b4b5/build
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/unicase-95d90fcebb64eeac/build-script-build_script_build-95d90fcebb64eeac
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rustc_version-76e71e47667641c7/lib-rustc_version-76e71e47667641c7
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/semver-21371f1df4b09baa/lib-semver-21371f1df4b09baa
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rustc-serialize-29daaebfc16e55cb/lib-rustc_serialize-29daaebfc16e55cb
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/url-6d842f47cc20a326/lib-url-6d842f47cc20a326
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/matches-dc52e482a85f2c5e/lib-matches-dc52e482a85f2c5e
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/idna-3db054cccbce4cb4/lib-idna-3db054cccbce4cb4
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/unicode-normalization-0380c037f91e7541/lib-unicode_normalization-0380c037f91e7541
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/unicode-bidi-384fe7d92389c1e3/lib-unicode_bidi-384fe7d92389c1e3
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/httparse-b31dfcd369f0dc79/lib-httparse-b31dfcd369f0dc79
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/language-tags-ca27e3e6961d878e/lib-language_tags-ca27e3e6961d878e
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/time-0bbc884d1946f0b1/lib-time-0bbc884d1946f0b1
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/hyper-2991d3239613cfd5/build
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/hyper-92ca72aa2b55879b/build-script-build_script_build-92ca72aa2b55879b
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/term-painter-91afc7f285355627/lib-term_painter-91afc7f285355627
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/term-e1d1158d86029c51/lib-term-e1d1158d86029c51
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/toml-1d42d8ba6745fe04/lib-toml-1d42d8ba6745fe04
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/cookie-136e11922312d484/lib-cookie-136e11922312d484
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for cookie v0.7.4: new (ring v0.7.5) != old (ring v0.7.5)
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/base64-84e78143d7e2ea7a/lib-base64-84e78143d7e2ea7a
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/byteorder-361be4c405c73a78/lib-byteorder-361be4c405c73a78
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/ring-71257f4c48d769d2/lib-ring-71257f4c48d769d2
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/untrusted-96f63d538a9429f2/lib-untrusted-96f63d538a9429f2
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/ring-bc00b1b93ac2f828/build
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/ring-a00ba5c693ebcc7d/build-script-build_script_build-a00ba5c693ebcc7d
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/gcc-1604195341ed8041/lib-gcc-1604195341ed8041
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rayon-6ecacfcf784b6a76/lib-rayon-6ecacfcf784b6a76
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rayon-core-3cefb5850366c4a9/lib-rayon_core-3cefb5850366c4a9
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rand-181c3a1f3e956745/lib-rand-181c3a1f3e956745
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/lazy_static-15bf74d66408cb83/lib-lazy_static-15bf74d66408cb83
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/deque-42de4d9eab150772/lib-deque-42de4d9eab150772
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rayon-core-c3a164c795f8c9fa/build
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rayon-core-56379ddd89a27abc/build-script-build_script_build-56379ddd89a27abc
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/pear_codegen-cc62c9c92af30dd1/lib-pear_codegen-cc62c9c92af30dd1
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/state-43fca0fef156b855/lib-state-43fca0fef156b855
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/pear-6e760722afd2bc17/lib-pear-6e760722afd2bc17
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/memchr-f30fddda4c33551d/lib-memchr-f30fddda4c33551d
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rocket-155c4b197dfde48a/build
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/rocket-151022718a5939c8/build-script-build_script_build-151022718a5939c8
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/version_check-6f5d0758724fd92a/lib-version_check-6f5d0758724fd92a
DEBUG:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /Users/sbenitez/Rocket/target/debug/.fingerprint/ansi_term-f51fe439a0e7ebce/lib-ansi_term-f51fe439a0e7ebce
   Compiling cookie v0.7.4
DEBUG:cargo::ops::cargo_rustc::fingerprint: appending /Users/sbenitez/Rocket/target/debug/.fingerprint/cookie-136e11922312d484/dep-lib-cookie-136e11922312d484 <- /Users/sbenitez/Rocket/lib
DEBUG:cargo::ops::cargo_rustc::fingerprint: write fingerprint: /Users/sbenitez/Rocket/target/debug/.fingerprint/cookie-136e11922312d484/lib-cookie-136e11922312d484
   Compiling rocket v0.2.6 (file:///Users/sbenitez/Rocket/lib)
DEBUG:cargo::ops::cargo_rustc::fingerprint: appending /Users/sbenitez/Rocket/target/debug/.fingerprint/rocket-345600c44cd7c0e1/dep-lib-rocket-345600c44cd7c0e1 <- /Users/sbenitez/Rocket/lib
DEBUG:cargo::ops::cargo_rustc::fingerprint: write fingerprint: /Users/sbenitez/Rocket/target/debug/.fingerprint/rocket-345600c44cd7c0e1/lib-rocket-345600c44cd7c0e1
    Finished dev [unoptimized + debuginfo] target(s) in 10.97 secs
```

**Comment by alexcrichton** [comment] 2017-04-19 02:02
So much for being more illuminating, alas!

**Comment by alexcrichton** [comment] 2017-04-19 02:16
Oh wait sorry I think I misunderstood the issue, I believe I see the problem now.

So cargo recently started caching crates based on features as well as debug/release, meaning that `cargo build` and `cargo build --feature foo` should have two separate caches and shouldn't thrash if you go back in forth. Cargo is indeed successfully doing that here but the problem is that Cargo's not taking dependencies into account.

So for one compilation graph here no features are enabled. Next a feature in Rocket and transitively, *ring*, a feature is enabled. Now cookie depends on *ring* so when it's recompiled it means cookie is recompiled, and later Rocket is recompiled. This basically means that the Rocket with no features uses a different version of the cookie crate than the version of Rocket with features. Both versions of the cookie crate have no features enabled, but the dependencies are different.

I believe the solution here, and one we forgot to do earlier, is to simply has dependencies when hashing a crate. I believe the [relevant function](https://github.com/rust-lang/cargo/blob/89ca25e1c0944c79bc025c4012f26b3e2f04a369/src/cargo/ops/cargo_rustc/context.rs#L372-L425) already has all the information necessary to do this, we basically just need to call `target_deps` on the `unit` provided recursively and throw a bunch of hashes into what we're working with. Note that to be efficient we're going to want some memoization here as well.

**Comment by udoprog** [comment] 2017-09-26 01:11
I've been troubleshooting this in nikomatsakis/lalrpop#266, and I've put togethe a [small project to easily reproduce it][repro-project].

I can only reproduce this on stable cargo (`0.21.1`), but on on cargo compile from master. So this might have been fixed.

[repro-project]: https://github.com/udoprog/lalrpop-rebuild-repro

**Comment by alexcrichton** [comment] 2017-09-26 01:41
Ah yes, this was indeed fixed on master!

https://github.com/rust-lang/cargo/pull/4469

**Closed by alexcrichton** 2017-09-26 01:41 UTC
