### ISSUE TITLE
Wrong PackageId generation when using --manifest-path

### ISSUE THREAD

**Issue by dotdash** [rust-lang/cargo#497] opened 2014-09-01 09:28 UTC
Using `--manifest-path` I get different PackageIds (and thus bogus rebuilds) depending on whether I specify just the directory or the full path including the `Cargo.toml` part.

Just the directory:

```
$ RUST_LOG=cargo cargo build --release --verbose --manifest-path src/sdl-demo/ |& grep ids
5:cargo::core::registry: getting packags; sources=1; ids=[sdl v0.3.4 (file:///home/bs/src/rust-sdl/src), sdl-demo v0.3.4 (file:///home/bs/src/rust-sdl/src)]
5:cargo::sources::path: getting packages; ids=[sdl v0.3.4 (file:///home/bs/src/rust-sdl/src), sdl-demo v0.3.4 (file:///home/bs/src/rust-sdl/src)]
```

Path incl. filename:

```
$ RUST_LOG=cargo cargo build --release --verbose --manifest-path src/sdl-demo/Cargo.toml |& grep ids 
5:cargo::core::registry: getting packags; sources=1; ids=[sdl-demo v0.3.4 (file:///home/bs/src/rust-sdl/src/sdl-demo), sdl v0.3.4 (file:///home/bs/src/rust-sdl/src/sdl-demo)]
5:cargo::sources::path: getting packages; ids=[sdl-demo v0.3.4 (file:///home/bs/src/rust-sdl/src/sdl-demo), sdl v0.3.4 (file:///home/bs/src/rust-sdl/src/sdl-demo)]
```

Notice how the `sdl-demo` part is only present when the filename is given.

I also wonder if the path for `sdl v0.3.4` should really point to `src/sdl-demo´ instead of the sdl root, but that's a different issue.

**Comment by alexcrichton** [comment] 2015-06-08 22:20
At this point the package id generation I don't believe will change, but the symptom of this, #1694, I should have a fix for shortly.

**Comment by alexcrichton** [comment] 2016-02-29 19:07
I think this is also the cause of https://github.com/servo/servo/issues/9794, which is unfortunately much more serious.

**Comment by alexcrichton** [comment] 2016-12-29 01:01
I believe this has since been fixed, so closing.

**Closed by alexcrichton** 2016-12-29 01:01 UTC

**Comment by nagisa** [comment] 2019-06-06 00:56
This appear to be an outstanding bug still.

**Comment by nagisa** [comment] 2019-06-06 00:57
See https://github.com/rust-lang/rust/issues/61553
