### ISSUE TITLE
Debug symbols not created on mac osx with the default options

### ISSUE THREAD

**Issue by deepaksubu** [rust-lang/cargo#9623] opened 2021-06-25 04:29 UTC
**Problem**
I am on MacOS Mohave [10.14.6] and I am starting out with rust. The debugger does not identify any breakpoints.

**Steps**

1. Create a new cargo project in Mac OSX Mojave 10.14 [It may apply to other versions as well]
     `cargo new hello-rust`
2. Run cargo build
    `cargo build -v`
3. Put a breakpoint in line 2 using lldb
   `lldb target/debug/hello-rust`
   `breakpoint set --file src/main.rs --line 2`
4.  You see the following error

````
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.0.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.1.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.2.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.3.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.4.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.5.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.6.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
error: hello-rust debug map object file '<workspace>/hello-rust/target/debug/deps/hello_rust.hello_rust.2vvlp69f-cgu.7.rcgu.o' has changed (actual time is 2021-06-24 21:15:36.000000000, debug map time is 1969-12-31 16:00:00.000000000) since this executable was linked, file will be ignored
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
````
    

**Possible Solution(s)**

1. I changed the setting in Cargo.toml to the following so that the split-debuginfo is set to "packed" and now the breakpoint can be set correctly. 

```[profile.dev]
split-debuginfo = "packed"
```

**Notes**

Output of `cargo version`:
`cargo 1.53.0 (4369396ce 2021-04-27)`

Output of lldb version:

````
lldb-1001.0.13.3
  Swift-5.0
````

Output of rustc version

`rustc 1.53.0 (53cb7b09b 2021-06-17)`

**Comment by alexcrichton** [comment] 2021-06-25 14:33
The above steps work for me locally, and I don't see any issues. I'm using a more recent LLDB though (`lldb-1205.0.28.2`), so this is perhaps a bug fixed in LLDB? (or a feature added?)

**Comment by ehuss** [comment] 2021-06-25 15:17
I can reproduce this in older versions of Xcode.  The reason is that the object files have 0 timestamps (for deterministic builds).  This was fixed in later versions of Xcode via https://github.com/llvm-mirror/lldb/commit/f6ba8da08fdfbdb2ec190a5725729493a7ce5e51.  I have no idea how to determine which xcode that commit was first added, though.

**Comment by deepaksubu** [comment] 2021-06-25 16:54
Many thanks for quick confirmation. If this is not applicable to newer versions of LLDB then I probably ran into an edge case.  Feel free to close this out.

**Closed** 2021-06-25 16:57 UTC
Labels: C-bug
