### ISSUE TITLE
cargo publish fails if a feature enables a dev-dependency feature

### ISSUE THREAD

**Issue by maia-s** [rust-lang/cargo#13363] opened 2024-01-28 20:57 UTC
### Problem

If a feature enables a feature on a dev-dependency, `cargo publish` fails with an error that it's not a dependency. The crate works as expected otherwise.

### Steps

1. Have a dev-dependency with feature flags.
2. Have a feature in your own crate that enables one of those features.
3. Run `cargo publish --dry-run`

### Possible Solution(s)

I made a separate crate for tests as a workaround.

### Version

```text
cargo 1.77.0-nightly (1ae631085 2024-01-17)
release: 1.77.0-nightly
commit-hash: 1ae631085f01c1a72d05df1ec81f3759a8360042
commit-date: 2024-01-17
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0 (sys:0.4.70+curl-8.5.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.2.1 [64-bit]
```

**Comment by weihanglo** [comment] 2024-01-28 21:15
Thanks for the report. This seems to be a duplicate of <https://github.com/rust-lang/cargo/issues/12225>

**Comment by epage** [comment] 2024-01-29 15:20
Hard to tell if its a dupe without a full reproduction case and error message.

**Comment by maia-s** [comment] 2024-01-30 17:08
Okay. To reproduce, create two new crates with cargo:
```shell
% cargo new --lib a
% cargo new --lib b
```
change `a/Cargo.toml` to this:
```toml
[package]
name = "a"
version = "0.1.0"
edition = "2021"

[features]
feature = ["b/feature"]

[dev-dependencies]
b = { path = "../b" }
```

change `b/Cargo.toml` to this
```toml
[package]
name = "b"
version = "0.1.0"
edition = "2021"

[features]
feature = []
```
(my original dev-dependency was optional and a proc-macro, but that's not required to reproduce)

Now enter the `a` crate. You can verify that `cargo build`, `cargo build --features feature`, `cargo test` and `cargo test --features feature` all run without error. Run `cargo publish --dry-run`
```
% cargo publish --dry-run --allow-dirty
    Updating crates.io index
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
   Packaging a v0.1.0 (/private/tmp/a)
   Verifying a v0.1.0 (/private/tmp/a)
error: failed to verify package tarball

Caused by:
  failed to parse manifest at `/private/tmp/a/target/package/a-0.1.0/Cargo.toml`

Caused by:
  feature `feature` includes `b/feature`, but `b` is not a dependency
```

**Comment by epage** [comment] 2024-01-30 17:44
Thanks!

This does look like #12225 to me.  Closing in favor of that.  If there is a reason to keep this open, let us know!

**Closed by epage** 2024-01-30 17:44 UTC
Labels: C-bug, S-needs-info
