### ISSUE TITLE
Failed to get source from registry

### ISSUE THREAD

**Issue by hh9527** [rust-lang/cargo#1400] opened 2015-03-10 12:54 UTC
I use `cargo fetch --verbose` and got:

```
Downloading bitflags v0.1.1
unable to get packages from source


Caused by:
  Failed to download package `bitflags v0.1.1` from https://crates.io/api/v1/crates/bitflags/0.1.1/download

Caused by:
  Failed to verify the checksum of `bitflags v0.1.1`
```

And use `curl -v https://crates.io/api/v1/crates/bitflags/0.1.1/download`, and got following result:

```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8880 (#0)
* Establish HTTP proxy tunnel to crates.io:443
> CONNECT crates.io:443 HTTP/1.1
> Host: crates.io:443
> User-Agent: curl/7.35.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 200 Connection established
< Connection: close
< 
* Proxy replied OK to CONNECT request
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=GT87339749; OU=See www.rapidssl.com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=crates.io
* 	 start date: 2014-11-06 11:11:23 GMT
* 	 expire date: 2015-11-09 14:30:14 GMT
* 	 subjectAltName: crates.io matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET /api/v1/crates/bitflags/0.1.1/download HTTP/1.1
> User-Agent: curl/7.35.0
> Host: crates.io
> Accept: */*
> 
< HTTP/1.1 302 Found
< Connection: keep-alive
* Server nginx is not blacklisted
< Server: nginx
< Date: Tue, 10 Mar 2015 12:48:03 GMT
< Transfer-Encoding: chunked
< Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/bitflags/bitflags-0.1.1.crate
< Set-Cookie: cargo_session=--3c156d7a3629aa08a1a0d538832f99ea30835cc8; HttpOnly; Secure; Path=/
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 vegur
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by hh9527** [comment] 2015-03-10 13:17
Additional information: I use cntlm at localhost to bridge to my company's windows proxy.

`cat ~/.cargo/config`

```
[http]
proxy = "http://127.0.0.1:8880/"

[https]
proxy = "http://127.0.0.1:8880/"
```

And curl/git works well.

**Comment by alexcrichton** [comment] 2015-03-10 17:33
Hm, this could be a legitimate download error or some form of corruption. If you download manually and then check the file in `~/.cargo/registry` are they actually the same file?

**Comment by hh9527** [comment] 2015-03-11 11:28
@alexcrichton
It seemed that no file existed in ~/.cargo/registry/cache.
I use `ls -R ~/.cargo/registry/cache` and got
```
.cargo/registry/cache:
github.com-1ecc6299db9ec823

.cargo/registry/cache/github.com-1ecc6299db9ec823:
```

And I use `curl -k https://crates.io/api/v1/crates/bitflags/0.1.1/download` got nothing.
But if I use `wget https://crates.io/api/v1/crates/bitflags/0.1.1/download`, it seemed got a corrected tar file.

**Comment by alexcrichton** [comment] 2015-03-11 18:43
Oh right we don't actually write out the file until we've verified the contents. Alas :(

**Comment by hh9527** [comment] 2015-03-12 02:27
@alexcrichton

More, after I `curl -v https://crates.io/api/v1/crates/bitflags/0.1.1/download`, I got
```
...
HTTP/1.1 302 Found
...
Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/bitflags/bitflags-0.1.1.crate
...
```
And then, I use `curl https://crates-io.s3-us-west-1.amazonaws.com/crates/bitflags/bitflags-0.1.1.crate`, It seemed got the right file either.

So, what information can I show you to locate the issue?

**Comment by alexcrichton** [comment] 2015-03-12 17:12
Unfortunately I think debugging this issue would require modifications to Cargo itself and a reliable way to reproduce :(

**Comment by hh9527** [comment] 2015-03-20 01:32
@alexcrichton
 I tried to compile cargo by myself, I thought that would help to locate the issue. But the compiling process also needs to fetch sources from the registry, and it also still failed.

Can you tell me how the sources fetched from registry organized int `~/.cargo/` ? I think i could manual download the files and rename them as cargo expect. And then I can compile cargo, and do some hack on its source to help locating the issue.

**Comment by alexcrichton** [comment] 2015-03-20 17:33
Right now it would be pretty difficult to set it up manually as there's lots of hashes in filenames here and there. Is this error specific to your machine or perhaps a particular network?

**Comment by yonkeltron** [comment] 2015-06-22 14:37
I can confirm this issue on my Mac. Running OSX Mavericks 10.9.5:

```
$ uname -a
Darwin REDACTED.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

The error I get:

```
$ cargo build --verbose
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  Failed to verify the checksum of `libc v0.1.8`
```

Also connected via VPN (Cisco AnyConnect) and behind a proxy/firewall. Please let me know if I can provide any additional information.

**Comment by alexcrichton** [comment] 2015-06-23 06:46
@yonkeltron that looks like the Cargo may not be playing well with the proxy, are you sure it's configured correctly?

**Comment by yonkeltron** [comment] 2015-06-23 18:27
@alexcrichton yes, the VPN/Firewall is configured just fine and I don't have any issues with other traffic or sites. I can browse crates.io without issue, it's only cargo build that fails. I am on a corporate network and my concern is that if cargo can't deal with setups like this, it could hamper enterprise adoption.

**Comment by alexcrichton** [comment] 2015-06-23 20:17
@yonkeltron well let's not jump to conclusions! Cargo most certainly wants to accommodate all forms of network environments, this is just perhaps a bug in Cargo itself. Unfortunately this is going to be very difficult to fix as I can't reproduce this.

**Comment by yonkeltron** [comment] 2015-06-25 15:46
@alexcrichton no conclusions yet, got it. So what can we do to debug this issue? There's a limit to how much information I'm permitted to share regarding the corporate network but I am willing to try as much as I can on my end. Is there anything I can do to enable additional diagnostic output from cargo? Is there a log file somewhere?

**Comment by alexcrichton** [comment] 2015-06-25 16:31
Is it possible for you to recompile Cargo? Currently these transient errors are intentionally never written to disk, but if you can [move this line](https://github.com/rust-lang/cargo/blob/b030d35d5cf6b35bf8a6bfd218ab4df9d6a86361/src/cargo/sources/registry.rs#L334) above [this line](https://github.com/rust-lang/cargo/blob/b030d35d5cf6b35bf8a6bfd218ab4df9d6a86361/src/cargo/sources/registry.rs#L329) then you should be be able to see what Cargo downloaded (which may be corrupted).

**Comment by southerngs** [comment] 2015-06-25 21:42
@alexcrichton I'm having a similar problem (also behind a firewall).  But when I try to build Cargo I'm getting an error when the build process uses the snapshot version of cargo itself during the build process. Rerunning with the `cargo build` command with --verbose shows the same error that I'm trying to debug in the first place.

```
 target/snapshot/cargo/bin/cargo build --target x86_64-unknown-linux-gnu --verbose
 Downloading bufstream v0.1.1
Unable to get packages from source

Caused by:
  Failed to download package `bufstream v0.1.1` from https://crates.io/api/v1/crates/bufstream/0.1.1/download

Caused by:
  Failed to verify the checksum of `bufstream v0.1.1`
```

I was wondering if you had any suggestions for other steps to try.

**Comment by southerngs** [comment] 2015-06-25 22:25
Some additional information.  I think that in my case the firewall might be changing the file that it downloads.  As an example I was trying one of the tutorials and I get the following error running cargo:

```
:~/tutorials/rust/guessing_game$ cargo build --verbose
 Downloading rand v0.3.8
Unable to get packages from source

Caused by:
  Failed to download package `rand v0.3.8` from https://crates.io/api/v1/crates/rand/0.3.8/download

Caused by:
  Failed to verify the checksum of `rand v0.3.8`
`````
I was able to download the file using wget, but when I compute the sha256sum I get:

````
sha256sum rand-0.3.8.crate
cb31ca2d033ec41f4e9ee0eae0f3f1a2a24594d1a0791895d409cee815079be8  rand-0.3.8.crate
````

But looking at https://github.com/rust-lang/crates.io-index/blob/master/ra/nd/rand it appears the hash should be should be `b674087a811e0f96133764b93f2f95ab843c0ade512ca52fd5df732c93d4c596`

I'm going to try connecting to another network to see if I can get the file without going through my firewall, but I wanted to post this update now before switching my connection.

**Comment by alexcrichton** [comment] 2015-06-25 22:29
@southerngs fascinating! Can you perhaps upload the `rand-0.3.8.crate` you download somewhere I could take a peek at it? I'm curious to see what's different between that file and the one that was uploaded to crates.io

**Comment by southerngs** [comment] 2015-06-25 22:54
@alexcrichton I'm not sure if I'm authorized to upload the whole file, but here's a screenshot showing what it looks like when I view it in vim.  The `^@` characters indicate embedded nulls (other editors display it differently) which I'm guessing aren't in the original file, although I don't have any way to know using my current network.

![image](https://cloud.githubusercontent.com/assets/3270868/8367242/26d5a3da-1b51-11e5-8172-9b900d09b263.png)

I tried using a different network here but it still downloads the same file.  I'll try at home later to see what the diff between the two files is and then probably talk to the IT people tomorrow to see if I can figure out what the firewall is doing.  But my guess is that this error is related to some transformation my firewall/proxy is doing on the content.  If I have any more useful information I'll update the issue at that time.

**Comment by alexcrichton** [comment] 2015-06-25 22:57
Hm, interesting! I think the diff would definitely be helpful here. If the firewall is performing a fairly benign modification of the files then we could perhaps hash a subset of the crate file (e.g. not the metadata, just the file contents), but it would be good to know concretely what's changing.

**Comment by southerngs** [comment] 2015-06-26 01:15
It turns out that a diff is not helpful.  It looks like the crate files distributed via cargo are tar files compressed with gzip (at least the `rand-0.3.8.crate` file is).  When I download the file on my home network the sha256 hash matches what is on crates.io and the file size is 51KB.  Viewing the file in a text editor shows the sort of thing you would expect for a compressed file.

But the file that I downloaded through my firewall is 192 KB and is mostly readable plaintext that looks like a concatenation of the contents of the files that make up the package.

I don't know much about my firewall and whether this is the same problem that others are having.  But in my case it looks like the firewall is doing deep packet inspection and not recompressing the file after it's done.

**Comment by alexcrichton** [comment] 2015-06-26 15:38
Weird! This... seems bad? It does sound like your network is pre-decompressing the tarballs Cargo is downloading, *even over an SSL connection*. The hash listed for each crate is the hash of the compressed contents.

**Comment by yonkeltron** [comment] 2015-06-26 18:44
I can confirm that the firewall on my end decompresses the crate file itself. When I `wget` the crate directly, it comes back the same 192KB that @southerngs found! Inspecting the file confirms that it's a decompressed POSIX tar archive. The crate file was also downloaded over an SSL connection which confirms some of the suspicions elsewhere on this thread. If I manually gzip the file and put it in the correct directory in `.cargo/registry/cache/github-whatever`, then it will install without issue.

@alexcrichton If this behavior of corporate firewalls is common, this could cause a stubbornly-durable complication, right? What about your idea to hash the contents rather than the gzipped container?

**Comment by southerngs** [comment] 2015-06-26 20:34
Regarding the SSL connection, in my case the firewall decrypts and re-encrypts the connection with amazonaws.  I discovered this while debugging an issue I was having that was similar to #976.  I had to add my proxy server's certificate as a trusted cert on my development machine to fix the CA error.

My thoughts about this issue is that it points to a configuration problem with the firewall that hopefully can be changed.  I am able to download tar.gz files in compressed form.  So hopefully some sort of exception can be added for .crate files so that they firewall treats them the same way as tar.gz.  I don't think it makes sense for Cargo to change its design to hash crate file contents rather than the file itself.

However, in the long term it might make sense to think about how to make rust and cargo work on systems that don't have internet access.  There should be a way to do some sort of bulk download that allows organizations to have their own internal repository for a specific version of the software they are developing.

**Comment by alexcrichton** [comment] 2015-06-28 21:43
@yonkeltron, @southerngs ok I have [deployed a change](https://github.com/rust-lang/crates.io/commit/53cbb26d022a88f7f311740f35ec5c6d4a5a9ab0) to crates.io which stops setting the `Content-Encoding: gzip` header. I think this may force firewalls/proxies to not assume the gzip encoding, preventing the stream from being automatically decompressed. 

This currently does not retroactively apply to previous uploads, only future uploads. Could one of you test to see if this change actually helps? For example, try to publish a crate and then download it on the firewall'd network and see if it works.

**Comment by southerngs** [comment] 2015-06-29 20:54
@alexcrichton it looks to me like this fixes this issue for me (and probably other as well).  I created the crate `test_crate_firewall_gzip_problem` and it downloads correctly over my firewalled connection.  

What is the process for updating the existing crates so that they will be usable too?

**Comment by alexcrichton** [comment] 2015-06-29 22:41
I'll try to write a script to delete the Content-Encoding header from all previously uploaded crates soon.

**Comment by southerngs** [comment] 2015-07-06 18:16
@alexcrichton any update on fixing this for previously uploaded crates?  I'm not in a huge rush, but it would be helpful to have an idea of when this will be fixed.

**Comment by alexcrichton** [comment] 2015-07-07 00:03
I'll try to get to this over the next week or so, but it's basically just going to be a script to crawl the index and then post requests to S3 deleting the `Content-Encoding` header. If a script doing so appears before I get around to writing it then I could get this done much faster :)

**Comment by alexcrichton** [comment] 2015-07-09 00:44
Ok, done!

**Closed by alexcrichton** 2015-07-09 00:44 UTC

**Comment by southerngs** [comment] 2015-07-10 17:08
@alexcrichton thanks it works for me now.

**Comment by neetabisht** [comment] 2024-02-07 09:50
Hi All,
I have cargo.toml file present in windows 11 machine where trying to use rumqtt 0.31.0 version.

![cargo-toml](https://github.com/rust-lang/cargo/assets/105039104/4ea663a5-0887-44e2-8afd-a227cd96fbc8)

But when i am running "cargo build" cli, I'm getting below error:

**$ cargo build
    Updating crates.io index
  Downloaded autocfg v0.1.8
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to verify the checksum of `autocfg v0.1.8`**

can anyone please help me with this error.

**Comment by Eh2406** [comment] 2024-02-07 15:25
This issue was closed almost a decade ago. None of the conversation here is still relevant. If you are having an problem open a new issue. (or as on a user focused venue like users.rust-lang.org.)
