### ISSUE TITLE
`cargo update` infinite recursion.

### ISSUE THREAD

**Issue by DiamondLovesYou** [rust-lang/cargo#2300] opened 2016-01-21 00:34 UTC
Put these deps into a new crate (created with `cargo new`):
```toml
glium = "0.13.3"
skia = "0.1.0"
```

Then try to build. [Log](https://gist.github.com/DiamondLovesYou/89554ad6cc26f47bd4a8).

**Comment by alexcrichton** [comment] 2016-01-25 17:23
I suspect this is a dupe of https://github.com/rust-lang/cargo/issues/2090 which is in turn due to https://github.com/rust-lang/cargo/issues/2064, but unfortunately I haven't had the chance to investigate it yet.

**Comment by alexcrichton** [comment] 2016-02-09 16:12
Ok, I think this is indeed a dupe of #2090, so closing in favor of that.

**Closed by alexcrichton** 2016-02-09 16:12 UTC
