### ISSUE TITLE
`[replace]` ignored if root crate is virtual manifest

### ISSUE THREAD

**Issue by gifnksm** [rust-lang/cargo#3116] opened 2016-09-25 15:29 UTC
The following project cannot `build` with nightly cargo `0.13.0-nightly (9399229 2016-09-14)`

``` toml
# root/Cargo.toml
[workspace]
members = ["foo", "bar"]

[replace]
"foo:0.1.0" = { path = "./foo" }
```

``` toml
# root/foo/Cargo.toml
[package]
name = "foo"
version = "0.1.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[dependencies]
```

``` toml
# root/bar/Cargo.toml
[package]
name = "bar"
version = "0.1.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[dependencies]
foo = "0.1.0"
```

```
$ cd root/foo
$ rustup run nightly cargo build                                                                                        (git)-[master]
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `foo` found (required by `bar`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.1.0
```

**Comment by alexcrichton** [comment] 2016-09-27 18:14
Note that replaced crates are still required to exist on crates.io, so perhaps that's the problem here? Looking back at the implementation this is specifically handled, so perhaps this is just related to unpublished crates?

**Comment by SergioBenitez** [comment] 2016-09-28 23:04
This appears to be a dupe of #3099.

**Comment by alexcrichton** [comment] 2016-09-29 00:59
I don't think it's quite the same because here `[replace]` is in the root crate, Cargo just still requires crates to be published on crates.io (which it looks like this may not be using)

**Comment by SergioBenitez** [comment] 2016-09-29 01:00
You're absolutely right. Sorry, I only glanced at the issue initially.

**Comment by sanmai-NL** [comment] 2017-01-11 19:12
@alexcrichton: why is this requirement in place? Projects are likely to start out as an exclusively local workspace, but it is desirable to architect them for a future in which the crates are published and developers use local workspaces. But you not only require them to be hosted in a Git remote, but be published as crates on crates.io as well. Is this requirement sensible in a context of commercial and/or non-open source software development managed with `cargo` tooling?

**Comment by alexcrichton** [comment] 2017-01-12 18:05
@sanmai-NL this is basically how `[replace]` is defined. Cargo resolves the dependency edge, then it applies `[replace]`. The dependency edge can't be resolved if it doesn't exist.

Coming back to this it looks like this is working as intended, so closing.

**Closed by alexcrichton** 2017-01-12 18:05 UTC
