### ISSUE TITLE
Allow dependency to forcibly override profile settings

### ISSUE THREAD

**Issue by DanielKeep** [rust-lang/cargo#2506] opened 2016-03-22 07:58 UTC
Currently, I'm using `lalrpop` as part of a project.  Because of the mammoth compile times involved, I've contained the parser in its own crate.

The problem is that not only is the parser very slow to compile, it is *catastrophically slow* in debug builds.  As in, a release build runs around 20x faster.  As such, I want my parser package to *always* be compiled with optimisations enabled to keep from going completely insane.

But, I can't.  I want to be able to have a debug build that isn't heavily optimised (save for this *one* dependency).  A way to specify that a package's profile settings take precedence would be great, although I'd also settle for a way to specify the profile settings for particular dependencies in the top-level package's manifest, too.

Please.  It's taking *eight seconds* to parse a few KBs worth of text.  It's ridiculous.

**Comment by alexcrichton** [comment] 2016-03-22 18:37
Thanks for the report! There's been some discussion over on https://github.com/rust-lang/cargo/issues/2424, https://github.com/rust-lang/cargo/issues/1359, and this is kinda a dupe of those so I'm going to close in favor of them.

**Closed by alexcrichton** 2016-03-22 18:37 UTC
