### ISSUE TITLE
cargo allows pulling non-library dependencies

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/cargo#8382] opened 2020-06-19 05:52 UTC
**Problem**

I am not sure if this is bug or a feature (if so, I would appreciate explanation of it)..

The question is about https://crates.io/crates/cargo-insta. From what I see (and what cargo tells me), it has only binary target, no lib / proc or anything like that.

```
Downloads/rust-cargo-insta/cargo-insta-0.16.0 is 📦 v0.16.0 via 🦀 v1.44.0 
❯ cargo metadata --no-deps | jq '.packages[0].targets[]'
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
{
  "kind": [
    "bin"
  ],
  "crate_types": [
    "bin"
  ],
  "name": "cargo-insta",
  "src_path": "/home/brain/Downloads/rust-cargo-insta/cargo-insta-0.16.0/src/main.rs",
  "edition": "2018",
  "doctest": false
}
```

Apparently specifying it in a dependencies section in Cargo.toml pulls it in and even compiles it, but I don't see any final binary (in target/) produced from that crate.

**Steps**

1. Add `cargo-insta = "0.16"` into the `[dependencies]`
2. Try to compile a project

**Possible Solution(s)**

* Show warning
* Abort with an error

**Notes**

Output of `cargo version`: `cargo 1.44.0`

This is happening on Fedora 33 (x86_64) with rust/cargo provided by a distribution.

**Comment by ehuss** [comment] 2020-06-25 18:53
It should probably be a warning at least.  Closing as a duplicate of #4226.  There are also some vague ideas of making it a valid use-case (like #4316).

**Closed by ehuss** 2020-06-25 18:53 UTC
Labels: C-bug
