### ISSUE TITLE
Cargo doc, documentations of dependances is not always updated according to enabled features

### ISSUE THREAD

**Issue by YruamaLairba** [rust-lang/cargo#7961] opened 2020-03-03 13:03 UTC
**Problem**

Hello, 
I was testing the use of "features" to do conditional compilation and i wanted to check how behave the documentation. So i set up a package "b" with an optional feature "foo" , and a package "c" using package "b" with or without the "foo" feature in the Cargo.toml. see the joined .zip
[report.zip](https://github.com/rust-lang/cargo/files/4281265/report.zip)
Inside package "c", i did sequentially the following manipulations with the corresponding result:

1. `cargo doc` with feature "foo" => Ok, i get the doc for b, thing enabled by "foo", and c
2. `cargo doc` without feature "foo" =>Ok, all doc are rebuild, i get the doc of b but without "foo" thing and doc for c
3. `cargo doc` with feature "foo" => not Ok, only doc for c is rebuild, i still have the doc for b without "foo".

**Possible Reason**
It's look like a caching issue with doc artifacts.

**Notes**
I'm under Debian and i'm using the stable toolchain.
Output of `cargo version`:
cargo 1.41.0 (626f0f40e 2019-12-03)

**Comment by ehuss** [comment] 2020-03-03 17:30
Thanks for the report!   There is a nearly identical issue to this #7370, so I'm going to close as a duplicate of that.

**Closed by ehuss** 2020-03-03 17:30 UTC
Labels: C-bug
