### ISSUE TITLE
A status bar that doesn't log history

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/cargo#10234] opened 2021-12-27 01:13 UTC
### Problem

Most of the time, `cargo build` takes up the entire terminal by logging what was installed. It would be nice if it didn't do this, and instead, it just showed in the progress bar what was currently installing. This could be configured via the global cargo config.

### Proposed Solution

Only show the current thing being installed

### Notes

**Comment by ehuss** [comment] 2021-12-27 16:21
Thanks for the suggestion.  I think this is more or less a duplicate of #8889 (revamping the output in general), so closing in favor of that.

**Closed by ehuss** 2021-12-27 16:21 UTC
Labels: C-feature-request
