### ISSUE TITLE
`cargo test` does not give any warning when the specific test case does not exist

### ISSUE THREAD

**Issue by yipu3** [rust-lang/cargo#14813] opened 2024-11-13 05:27 UTC
### Problem

If I run `cargo test xxx` when xxx does not exist. cargo does not give any warning but output a bunch of green output.

For example. I have a test case `test_foo`. Every time I change foo I run this test case by running `cargo test test_foo`. Then I change the name from `test_foo` to `test_foo_` and forget to change the test command(For example, by using bash history). So every time I run cargo test I still got a bunch of green output which make me take the test as passed for granted, causing more confusion in the future.

### Steps

cargo test xxx
xxx is a non-existing test case

### Possible Solution(s)

Give warnings if the test case does not exist.

### Version

```text

```

**Comment by weihanglo** [comment] 2024-11-13 05:49
Thanks for the proposal.

This is a duplicate of <https://github.com/rust-lang/cargo/issues/11875>, and is not a thing Cargo can control at this moment.

<https://github.com/rust-lang/testing-devex-team/issues/1> is an effort of providing a JSON output so that Cargo and other tools may have more chances to control how tests are executed.

Close in favor of aforementioned issues.

**Closed by weihanglo** 2024-11-13 05:49 UTC
Labels: C-bug, S-triage
