### ISSUE TITLE
Latest released version does not compile

### ISSUE THREAD

**Issue by ia0** [rust-lang/cargo#9124] opened 2021-02-02 09:39 UTC
**Problem**

The `cargo` library doesn't build at 0.50.0 (latest released version) and 0.52.0. However it does at master.

**Steps**
1. `git checkout 67a00f95b` (supposedly 0.50.0) or `git checkout 60143816b` (supposedly 0.52.0)
2. `cargo build --release --lib`
3. The following error is displayed:
```
error[E0283]: type annotations needed
   --> src/cargo/util/config/de.rs:530:63
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`
help: use the fully qualified path for the potential candidates
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<OsStr>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<std::path::Path>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<str>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<[u8]>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: could not compile `cargo`

To learn more, run the command again with --verbose.
```

**Possible Solution(s)**

Bump and release version 0.53.0.

**Notes**

Output of `cargo version`: `cargo 1.51.0-nightly (c3abcfe8a 2021-01-25)`
Output of `rustc version`: `rustc 1.51.0-nightly (04caa632d 2021-01-30)`

**Comment by est31** [comment] 2021-02-02 11:18
Hitting this issue in the cargo-udeps CI as well. cargo install --locked works, which means it's likely due to a dependency update. If I do the following, I can reproduce the issue on cargo-udeps master:
```
$ cargo update -p syn -p serde
    Updating serde v1.0.121 -> v1.0.123
    Updating serde_derive v1.0.121 -> v1.0.123
    Updating syn v1.0.59 -> v1.0.60
```

(It doesn't reproduce without that)

cc @dtolnay

**Comment by est31** [comment] 2021-02-02 11:23
Already happens when I do:

```
$ cargo update -p syn && cargo update -p serde --precise 1.0.122
    Updating crates.io index
    Updating syn v1.0.59 -> v1.0.60
    Updating crates.io index
    Updating serde v1.0.121 -> v1.0.122
    Updating serde_derive v1.0.121 -> v1.0.122
```

And it does *not* happen when I run it for syn only, so I suspect it's either due to a serde or serde_derive change, between the 1.0.121 and 1.0.122 versions. [changes link](https://github.com/serde-rs/serde/compare/v1.0.121...v1.0.122).

**Comment by est31** [comment] 2021-02-02 11:24
See f097d02ea62111493b9f06d096a94dfddd020415 and #9101

**Comment by est31** [comment] 2021-02-02 11:25
and https://github.com/serde-rs/serde/issues/1967

**Comment by ia0** [comment] 2021-02-02 12:16
I didn't mention in the initial post, but I actually got the issue when building `cargo-outdated` with `cargo install cargo-outdated`. So besides `serde`, this should also break CIs of projects where `cargo-outdated` is built with the command above. At least it did for https://travis-ci.org/github/ia0/data-encoding/jobs/757173491.

Not sure what is the release policy of `cargo` but when debugging this I was surprised to see that the latest published version is 0.50.0 while master is past 0.52.0. I was also surprised to see that the issue is not present in master, so the fix should just be to publish a new version.

**Comment by est31** [comment] 2021-02-02 12:21
@ia0 release policy of the cargo crate is to release the new version on crates.io whenever there is a new release of rust/rustc. There is also a 6 week beta waiting period. So if the fix arrives in an "ordinary" way it'll take until March 25... hopefully it's realized that this is untenable, but let's see.

**Comment by ia0** [comment] 2021-02-02 12:24
Oh I see, that's good to know. Thanks for the info! I guess I'll just disable the cargo outdated test in my CI until this is fixed. This is not a big issue for me. I just felt I had to report it.

**Comment by est31** [comment] 2021-02-02 12:27
You can also try if `cargo install --locked` works for you.

**Comment by ia0** [comment] 2021-02-02 12:31
Yes it works, thanks!

**Comment by Eh2406** [comment] 2021-02-02 20:05
We discussed it in today's Cargo meeting. We are good to do a patch release of the library when a PR bacporting #9101 is merged.

**Comment by est31** [comment] 2021-02-02 20:37
@Eh2406 that'd be awesome!

**Comment by est31** [comment] 2021-02-06 01:12
1.50.1 is out now (and the latest released version). I confirm that running `cargo update` on cargo-udeps does not break the build any more.

**Closed** 2021-02-06 01:31 UTC
Labels: C-bug

**Comment by arkonbob** [comment] 2021-02-10 12:26
Did 0.50.1 get taken down again? I amended the HomeBrew formula on my mac to pull 0.50.1 and it failed "fatal: couldn't find remote ref refs/tags/0.50.1".

Just had a look under tags/releases here and I don't see it.

**Comment by est31** [comment] 2021-02-10 12:53
@arkonbob the release is available on crates.io, but it seems to not have been tagged in git. If you obtain cargo via the git dependency, you will have to use the raw commit hash of the release (or maybe maintainers can tag it).

The vcs info json accompanying the crates.io release [indicates](https://docs.rs/crate/cargo/0.50.1/source/.cargo_vcs_info.json) that the release commit is d61c808dda8029721042618f22e8e15d01328af4.

**Comment by Eh2406** [comment] 2021-02-10 13:47
Tagged. Thank you for finding the relevant links.

**Comment by arkonbob** [comment] 2021-02-10 13:54
@est31 @Eh2406 perfect timing, thanks both.

Confirm HomeBrew is now able to pull with

```
resource "cargo" do
      url "https://github.com/rust-lang/cargo.git",
          tag: "0.50.1",
          revision: "d61c808dda8029721042618f22e8e15d01328af4"
    end
```
