### ISSUE TITLE
`cargo add bar --features x, y, z` is completely broken

### ISSUE THREAD

**Issue by elfeiin** [rust-lang/cargo#14333] opened 2024-08-01 03:06 UTC
### Problem

The documentation says:
```
--features features
Space or comma separated list of [features to activate](https://doc.rust-lang.org/cargo/reference/features.html#dependency-features). When adding multiple crates, the features for a specific crate may be enabled with package-name/feature-name syntax. This flag may be specified multiple times, which enables all specified features.
```
but doing the obvious `cargo add bar --features x, y, z` results in:
```
error: feature `x` must be qualified by the dependency it's being activated for, like `bar/x`, `y,/x`, `z/x`
```

**Comment by weihanglo** [comment] 2024-08-01 03:49
For `cargo add bar --features x, y, z` specifically, you need to quote the feature list when providing value to `--features` flag if you want to activate `x`, `y`, and `z` features. Like

```
cargo add bar --features "x, y, z"
```

Because they are not quoted, `y,` and `z` turn into trailing positional arguments, which becomes crate names as if you ran `cargo add "y," "z"`. Therefore, this behavior is expected.

Also the doc of the [`--features`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-add.html#option-cargo-add---features) flag explicitly tells that if mutiple crates are provided, the value to the `--features` flag must in the form of `<crate>/<feature>` to disambiguate.

Given there is no version info and reproducible step in the issue description, and with my naive guess the behavior is expected, so going to close this. If you are ready to share a minimal reproduction with Rust version info. Feel free to comment or reopen.

**Closed by weihanglo** 2024-08-01 03:49 UTC
Labels: C-bug, S-triage

**Comment by elfeiin** [comment] 2024-08-06 05:57
Examples could be added to the docs or the help info in the binary itself.

**Comment by weihanglo** [comment] 2024-08-06 12:14
> Examples could be added to the docs or the help info in the binary itself.

Feel free to do so.

To me, I may add some examples like `cargo add tokio -F fs,rt,net`. I would avoid quoting in examples as they might not cross-platform. (It's hard to say if the above example is cross-platform. CLI is hard)

**Comment by epage** [comment] 2024-08-06 19:21
In general, I recommend avoiding spaces and would prefer for examples to not use them.  Comma separated cases "just work" and they don't seem like they really need their own examples.

Maybe what we should do is adjust the help text to emphasize "comma" over "space".
