### ISSUE TITLE
Cargo wrote a circular dependency to crates index on cargo publish

### ISSUE THREAD

**Issue by bright-star** [rust-lang/cargo#3877] opened 2017-03-29 19:24 UTC
See https://github.com/rust-lang/crates.io-index/commit/89e90c19adfdc3ba19946b939fc5880bf568afba for the resulting commit.

The actual repo doesn't have this circular dependency in its [Cargo.toml](https://gitlab.com/bright-star/finite-fields/blob/master/Cargo.toml).

**Comment by bright-star** [comment] 2017-03-29 19:26
Replicated through the following steps:

1. Increment minor version number of crate in Cargo.toml
2. Commit, push, and cargo publish
3. Discover that the crate is now dependent on itself *twice*: https://github.com/rust-lang/crates.io-index/commit/1e3865e52f2ffe95a169781668410f09525f49ad

**Comment by rphmeier** [comment] 2017-03-29 19:51
A few more examples from IRC: 

https://github.com/rust-lang/crates.io-index/commit/acc71e3c3d26ad4bb1eaa7b3328e272ad2b45d63

https://github.com/rust-lang/crates.io-index/commit/b8e3b3ec17c50751b48a23abf7c7c9f83b4f1e34

**Comment by mbrubeck** [comment] 2017-03-29 20:39
Likely related to rust-lang/crates.io#653.

**Comment by carols10cents** [comment] 2017-03-29 20:40
I rolled back the deploy, so it should be fixed in the live site. Triaging the index now.

**Comment by asajeffrey** [comment] 2017-03-29 20:43
Me too: https://github.com/rust-lang/crates.io-index/commit/930fb19a34ce9854374cd3634ea51a9998aa384a

**Comment by carols10cents** [comment] 2017-03-29 20:48
The first bad index commit is https://github.com/rust-lang/crates.io-index/commit/edaaa4b26c2839decce640f743dc9baeed499edb
The last bad index commit is https://github.com/rust-lang/crates.io-index/commit/d34b8b7007497508b3068b1a6537cfccbc801393

**Comment by carols10cents** [comment] 2017-03-29 20:51
Before deploying crates.io today, it was running the code at 2772cbc. I deployed 1e02ca3 at 2017/03/29 12:14:47 -0400, which is when the bad index commits started happening, so the problem is somewhere in between there.

Going to work on fixing the files in the index before fixing the code though.

**Comment by carols10cents** [comment] 2017-03-29 20:57
Crates and versions affected:

d34b8b7 Updating crate `ethabi#1.0.3`
1d8a77b Updating crate `newton#0.3.2`
930fb19 Updating crate `serde_roundtrip_derive#0.1.1`
717471e Updating crate `gauc#0.2.0`
b8e3b3e Updating crate `git-workarea#2.0.1`
caae577 Updating crate `serde_roundtrip_derive#0.1.0`
1e3865e Updating crate `finite-fields#0.10.1`
89e90c1 Updating crate `finite-fields#0.10.0`
8e46e86 Updating crate `mediumvec#1.0.0`
38c6da0 Updating crate `pretty_assertions#0.1.1`
f4b7009 Updating crate `thrussh#0.10.0`
a5e2d3f Updating crate `sovrin-client#0.1.0-19`
bd9e9fe Updating crate `lichen#0.1.0`
acc71e3 Updating crate `ethabi#1.0.2`
4197c7f Updating crate `easybench#0.1.1`
923da31 Updating crate `devicemapper#0.4.1`
4f1b80b Updating crate `gleam#0.4.2`
e97a115 Updating crate `u256#0.1.0`
edaaa4b Updating crate `rustbreak#1.2.0`

**Comment by carols10cents** [comment] 2017-03-29 20:59
Note that crates.io's database was not affected, so the dependencies listed for these crates on crates.io is correct

**Comment by carols10cents** [comment] 2017-03-29 21:48
The following crates don't have any dependencies so their index files aren't affected by this bug:

* mediumvec#1.0.0
* easybench#0.1.1
* u256#0.1.0
* lichen#0.1.0

I have pushed https://github.com/rust-lang/crates.io-index/commit/9917d828acd2e091c9e87bba0e300d9199e3fd13 that should fix all the affected crate versions.

Please let me know if there are any remaining issues from this. Thank you all for your patience, and I'm sorry for the inconvenience.

**Comment by bright-star** [comment] 2017-03-29 22:01
Thanks @carols10cents ! Works for me.

**Comment by asajeffrey** [comment] 2017-03-29 22:11
Thanks!

**Comment by alexcrichton** [comment] 2017-03-30 16:53
Thanks for the fix @carols10cents! Sounds like this is handled so I'm going to close.

**Closed by alexcrichton** 2017-03-30 16:53 UTC
