### ISSUE TITLE
Fasten the speed of updating crates.io-index with local repository mirror source

### ISSUE THREAD

**Issue by Fancyflame** [rust-lang/cargo#9471] opened 2021-05-10 04:52 UTC
**Describe the problem you are trying to solve**
![无标题](https://user-images.githubusercontent.com/31250625/117607193-07d7fd00-b18e-11eb-994d-14b0deb7dd0b.png)

( The screenshot means nothing but help to know what I'm talking about )
The first time cargo updating mirror repository of crates.io-index on local storage is extremly slow, which costs me nearly 3 hours, compared with remote mirror which only cost few minutes. I don't understand what is the difference between local mirror and remote mirror except one stored on local disk and the other one stored on remote host.

**Describe the solution you'd like**

Shorten the update speed of local mirror.

**Notes**

It was the same when I did it on Linux device, which just not cost as many as 3h, but also costed about an hour.

**Comment by PaulDance** [comment] 2021-05-10 15:13
@Fancyflame Can you show us what the contents of your `.cargo/config.toml` file are?

**Comment by ehuss** [comment] 2021-05-10 15:53
Yea, if you are using a `file://` URL, this is an issue in libgit2.  I believe this is the same as #9167, which includes a workaround.

**Comment by Fancyflame** [comment] 2021-05-11 01:15
@PaulDance 
![Screenshot_20210511_091036_com termux](https://user-images.githubusercontent.com/31250625/117743171-d9fbc280-b238-11eb-86ac-60de36da455f.jpg)

Here is it, just simply replaced its source. ( Please ignore I running Rust on Android 🌚  )

**Comment by PaulDance** [comment] 2021-05-11 02:27
@Fancyflame Thanks for the information. Glad the workaround works for you as well.

Indeed, libgit2 is originally a library implemented in C, but [bindings](https://github.com/rust-lang/git2-rs) to it exist and Cargo uses them.

I have left a message on the [concerned issue](https://github.com/libgit2/libgit2/issues/2836) to try to put this problem back on the front line and hopefully fix this in the near future, but if for whatever reason it cannot ever be fixed, then a warning is not a bad idea.

**Comment by Fancyflame** [comment] 2021-05-11 03:41
@PaulDance Yeah I do hope they could fix this bug, but it is undeniable that the bug has been last for serveral years so I think it must be a tricky problem and has less hope to be fixed in the near future 😂

**Comment by ehuss** [comment] 2021-05-19 23:48
Closing as a duplicate of #9167.  Some workaround in cargo would be nice, though I'm not sure exactly how to approach that.

**Closed by ehuss** 2021-05-19 23:48 UTC
Labels: C-feature-request
