### ISSUE TITLE
Need ability to add dependencies based on `#[cfg()]`

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/cargo#1007] opened 2014-12-03 16:29 UTC
For example, in curl-rust:

Usage: https://github.com/carllerche/curl-rust/blob/5d0f5c8848e3cf1e12480a1923ae888e24d58f63/src/lib.rs#L10
Dependence: https://github.com/carllerche/curl-rust/blob/5d0f5c8848e3cf1e12480a1923ae888e24d58f63/curl-sys/Cargo.toml#L18-L30

Also see https://github.com/carllerche/curl-rust/issues/30

In summary: without this, we end up with ad-hoc lists of triples in various `Cargo.toml` files, which breaks the build for targets with a non-matching triple that do match `#[cfg(...)]`.

**Comment by carllerche** [comment] 2015-05-08 21:43
:+1: (sorry for the useless comment, but its the only way to search for issues!)

**Comment by alexcrichton** [comment] 2015-05-26 16:39
Another alternative mentioned by @larsbergstrom would be:

```toml
[target."x86_64-*".dependencies]
# ...

[target."*-linux-*".dependencies]
# ...
```

**Comment by jmesmon** [comment] 2015-05-26 19:06
I'd like to caution against trying to assume anything about targets from their triples.
Rustc currently just treats targets as arbitrary strings: their contents is entirely up to whomever is adding the target.

Trying to extract meaning about targets out of the triple will be fairly error prone & in some cases will completely fail (or be impossible).

Possibly: rustc would expose a way of determining the attributes of a given target (looking at it's builtin targets & the requested json target) and cargo would query that.

Alternately: we could remove all the builtin target knowledge and push it into json files installed in rustlib, and cargo could read them directly.

**Comment by metajack** [comment] 2015-07-31 15:55
I'd like to push on this feature a little bit. After dealing with this in Servo and living with having to specify the same dependency multiple times (2x for linux and 2x for arm!), we now have a dependency on rand, which would have to have 4 target triples listed for windows. The upstream author is unwilling to do this, so we're back to conditional compilation of win32api on Linux and OS X.

If this doesn't get fixed soon, the community norm is going to be do make builds inefficient by using conditional compilation, and it's going to be confusing to people who are watching platform specific deps scroll by the build window.

**Comment by carllerche** [comment] 2015-07-31 16:14
@metajack I agree. I am already depending on the windows crate unconditionally in mio because of this. It has confused people but I really don't want to manage huge lists of repeated deps

**Comment by alexcrichton** [comment] 2015-08-03 16:47
@metajack, @carllerche 

I agree this is a problem that needs to be fixed, but I don't understand your concerns about unconditionally including crates. The compile time for a crate which is entirely `#[cfg]`'d away should be nothing and otherwise it should have basically no impact at all. If you have target-specific dependencies then you *already* have conditional compilation somewhere.

I agree that the ergonomics of target-specific dependencies aren't great today and that including Windows crates on a Unix build "feels wrong", but from a technical perspective I don't think there are many downsides of just unconditionally depending on the Windows crates on Unix.

**Comment by metajack** [comment] 2015-08-03 17:01
My concern is that when you are debugging the Servo build and trying to isolate problems, having 30 extra dependencies to sort through makes your life harder.

Switching this later could potentially leave a slew of crates which #[cfg] out the whole crate all the time and mean adoption of target dependencies will never take off. And for many of Servo's crates, this added a lot of annoying things since every lang item in lib.rs needs to be cfged out; you can't just have a crate level one (or at least you couldn't back when I originally did this for Servo). See https://github.com/servo/io-surface-rs/commit/fba38ef4471288c9e85fddb06b764d12025a341a for an example cleanup.

Also, everyone keeps telling me that this free, and yet everyone seems to ignore that Servo has probably the largest dependency graph and surfaces a lot of performance problems that other projects don't see. This will not always be the case; I assume there will be lots of large Rust projects. The fact that people still write build systems to eke out better build times in C and C++ gives some reason to believe that there will be demand to shave these wasted cycles.

**Comment by carllerche** [comment] 2015-08-03 17:06
@alexcrichton the main issue is that it confuses people who are new as it is pretty unexpected behavior.

**Comment by alexcrichton** [comment] 2015-08-03 21:20
@metajack 

> My concern is that when you are debugging the Servo build and trying to isolate problems, having 30 extra dependencies to sort through makes your life harder.

Isn't this just inherent problems in a project of Servo's size? If you take out all non-relevant dependencies, aren't you still working with ~100 dependencies? 

> And for many of Servo's crates, this added a lot of annoying things since every lang item in lib.rs needs to be cfged out

By "lang item" do you mean just normal item? This has actually since been fixed in the compiler so you can just place `#![cfg(target_os = "macos")]` at the top of the crate and then the entire crate is omitted whenever you compile on something other than OSX. An example of this is [`winapi-rs`](https://github.com/retep998/winapi-rs/blob/3af842cc6b20f1859890d44988cbb8dee24591a4/src/lib.rs#L7).

> Also, everyone keeps telling me that this free, and yet everyone seems to ignore that Servo has probably the largest dependency graph and surfaces a lot of performance problems that other projects don't see. This will not always be the case; I assume there will be lots of large Rust projects.

Right I don't mean to say that it's literally free, just that in the time it takes to compile the script crate I think that hundreds of empty crates could possibly be compiled. I don't think that have a few extra leaf dependencies (even up to 30) would add much to a build time. That being said I want to clarify if you've measured something to the contrary in this regard. 

Overall I don't mind putting more effort into solving this, but I just want to make sure that it's not being prioritized because it's a "nice to have" and instead has some solid technical motivation. If Servo does indeed see an noticeable improvement in build times or general "Cargo is doing things" times then that's a pretty solid reason.

---

@carllerche 

> the main issue is that it confuses people who are new as it is pretty unexpected behavior.

Sure, I can totally understand that, just wanted to clarify if there was a technical reason for wanting to fast-track this.

**Comment by metajack** [comment] 2015-08-03 23:32
Fair points. The reasons are clearly mostly social ones. Platform deps are too difficult now, and I feel that if we don't make them usable soon (especially for Windows) then we risk them not getting community buy in.

I'm glad to hear that you can use `#![cfg()]` at a crate level now.

**Comment by alexcrichton** [comment] 2015-08-04 16:25
Yeah I'm also worried about community buy in, but thanks for the clarifications!

**Comment by jethrogb** [comment] 2015-08-10 00:57
This should be easy to implement using rustc_back::target::Target, but I guess using unstable features in Cargo is a no-go?

**Comment by lfairy** [comment] 2015-09-01 07:50
I think we can solve this by adding a `--cfg-matches` option to `rustc`.

`rustc --cfg-matches EXPR` will evaluate `EXPR` as if it were a `#[cfg(..)]` expression. It will return 0 if it matches, or 1 if it doesn't match.

Then in Cargo, something like

```toml
[target.cfg.unix.dependencies]
# ...
```

would trigger a call to `rustc --cfg-matches unix`, adding the dependencies if the call succeeds.

**Comment by jpernst** [comment] 2015-09-09 10:05
I'd also like to voice support for this feature as it pertains to private production deployments. Even if a dependency happens to compile away to nothing, we still become responsible for including it in our build environment and are exposed to transitive breakage if it ever fails to build for any reason. While Rust itself may be providing strong stability guarantees, libraries on crates.io are under no such obligation. I'm concerned that the status quo is becoming the blanket inclusion of dependencies that aren't really necessary for the core functioning of the libraries that include them. This adds noise to the dependency graph and complicates the evaluation of a library for use in production.

**Comment by mvdnes** [comment] 2015-09-24 08:05
I would also like a feature like this.

If the cfg or "*-linux-*" matching is not desirable, maybe we could also let the target be specified in the dependency, rather than the other way around:

```toml
[dependencies.winapi]
target = ['i686-pc-windows-gnu', 'i686-pc-windows-msvc', 'x86_64-pc-windows-gnu', 'x86_64-pc-windows-msvc']
```

This way the version and path and other data would only have to be specified once. In some cases this would seem to make more sense than the other way around.

**Comment by retep998** [comment] 2015-09-24 13:25
@mvdnes That still suffers the issue where if a new windows target triple is working, all the libraries using that form won't work on the new triple until they're updated.

**Comment by alexcrichton** [comment] 2015-11-10 19:07
I've now [opened an RFC](https://github.com/rust-lang/rfcs/pull/1361) to help close this issue.

**Comment by SimonSapin** [comment] 2015-11-28 18:26
Here is an example where we’d like to reduce duplication somehow:

https://github.com/servo/skia/commit/8678fb6486e#diff-80398c5faae3c069e4e6aa2ed11b28c0R30

**Comment by alexcrichton** [comment] 2016-02-26 23:38
Oh, right! Implemented in https://github.com/rust-lang/cargo/pull/2328

**Closed by alexcrichton** 2016-02-26 23:38 UTC
Labels: P-high
