### ISSUE TITLE
Makefile not regenerated when Makefile.in changes

### ISSUE THREAD

**Issue by cesarb** [rust-lang/cargo#1993] opened 2015-09-20 16:20 UTC
The `Makefile` should be regenerated when `Makefile.in` or `configure` is changed.

```
$ ls -l Makefile Makefile.in
-r--rw-r--. 1 cesarb cesarb 6994 Jul 29 09:20 Makefile
-rw-rw-r--. 1 cesarb cesarb 7038 Set 20 11:04 Makefile.in
$ fgrep CFG_RELEASE_NUM= Makefile Makefile.in
Makefile:CFG_RELEASE_NUM=0.4.0
Makefile.in:CFG_RELEASE_NUM=0.6.0
$ make
"/home/cesarb/opt/rust-git/bin/rustc" -V
rustc 1.5.0-dev (25aaeb40b 2015-09-20)
"target/snapshot/cargo/bin/cargo" --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-04-01)
target/snapshot/cargo/bin/cargo build --target x86_64-unknown-linux-gnu   
$ ls -l Makefile Makefile.in
-r--rw-r--. 1 cesarb cesarb 6994 Jul 29 09:20 Makefile
-rw-rw-r--. 1 cesarb cesarb 7038 Set 20 11:04 Makefile.in
$ ls -l config.stamp 
-rw-rw-r--. 1 cesarb cesarb 0 Jul 29 09:20 config.stamp
$ cargo --version
cargo 0.4.0 (4080ea8 2015-09-20) (built 2015-09-20)
```

As you can see, this leads to the version banner being incorrect.

**Comment by alexcrichton** [comment] 2015-09-20 16:57
Duplicate of https://github.com/rust-lang/cargo/issues/587, but thanks for the report!

**Closed by alexcrichton** 2015-09-20 16:57 UTC
