### ISSUE TITLE
Extending accepted metadata is a potential backcompat hazard

### ISSUE THREAD

**Issue by Ryman** [rust-lang/cargo#3291] opened 2016-11-14 17:47 UTC
I had a [library dependency](https://github.com/nickel-org/rust-mustache/pull/40) on serde_json 0.7 building on rustc 1.4.0 which [used to build](https://travis-ci.org/nickel-org/rust-mustache/jobs/145106291#L185). It no longer builds as the registry information fails to parse with the error "the given version requirement is invalid". 

Debugging this, it looks like the parser bails out when parsing the version number [` 0.8.0-rc1`](https://crates.io/crates/serde_json/0.8.0-rc1) (when parsing the `summaries`) which was published shortly after the [successful build](https://travis-ci.org/nickel-org/rust-mustache/jobs/145106291). Building continues to fail until rustc 1.8.0, and if I use the lockfile generated by the successful build then it still fails on 1.4-1.7 with the parse failure. 

This is unfortunate as if one publishes a new crate version (e.g. [a prerelease](https://github.com/rust-lang/cargo/issues/2222)) which is accepted by a newer cargo, you run the risk of breaking all the builds depending on older versions of your crate & older rustc/cargo combinations.

I'm unsure if there's a fix here as my understanding of cargos interaction with the registry doesn't give us an opportunity for indirection to filter problematic information for older clients? Perhaps the best we can do is audit other points where we should try to be more liberal in what we accept (or ignore) in order to allow more forward compatability.

The issue is actually a bit more annoying in the linked library as the serde feature is intended to be optional, but the mention of `serde_json` or `serde_codegen` in the manifest *even as optional non-active dependencies* causes the build to fail.

[Failure build log](https://travis-ci.org/nickel-org/rust-mustache/jobs/175605844#L221) - probably incompatible with rust 1.4 since it bumps serde, but it has the same error so I can't actually determine what the legitimate minimum version is.

Related issue: #2751 - specifying the min-rustc/cargo version could help ensure that what we publish does indeed parse/build with the version we're trying to maintain compatability with.

**Comment by alexcrichton** [comment] 2016-11-14 19:55
Yeah unfortunately there's not really anything we can do here. All the relevant bugs have been fixed, so...

**Comment by carols10cents** [comment] 2017-09-29 17:13
Closing this issue because I think solving the root cause is best addressed by RFCs like these:

- https://github.com/rust-lang/rfcs/pull/1707
- https://github.com/rust-lang/rfcs/pull/1709
- https://github.com/rust-lang/rfcs/pull/1953

None of these have been accepted, but I know there are people working on the successors to these RFCs.

**Closed by carols10cents** 2017-09-29 17:13 UTC
