### ISSUE TITLE
Better progress report

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#3448] opened 2016-12-23 16:09 UTC
Currently, `cargo` only outputs "Compiling xxx" when starting a job. I propose using ANSI control sequences to have a more finer progress report while keeping the same number of line output.
PoC with jobs in WiP or done state:
```bash
#!/usr/bin/env bash

a=(10 4 3 2 5 7 8 1 6 9)

for i in $(seq 1 10); do
    echo "doing $i"
done

for i in $(seq 1 10); do
    # \033[nA moves the cursor up n lines
    printf "\033[$((11 - i))A"
    # Print done jobs. \033[K clears the current line
    printf "\033[Kdone $i\n"
    # Print jobs still running
    for x in "${a[@]}"; do
        if [[ $x -gt $i ]]; then
            printf "\033[Kdoing $x\n"
        fi
    done
    sleep 1
done
```
The basic idea is with n jobs running, when a job finishes we erase the n previous lines, print the finished jobs then print the jobs still working.
When this setup is working, we can expand it to show a more finer progress report for each job.
Windows [seems to support it](https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx), MacOS and Linux does.
See https://github.com/rust-lang/cargo/issues/833, maybe also others.

**Comment by est31** [comment] 2016-12-28 16:09
(somewhat) related: #2536

**Comment by eminence** [comment] 2022-11-23 04:31
Triage:  Cargo these days has a more advanced progress output than it did 5 years ago.   Unless there's some specific deficiency in the current output, I think this issue can be closed

**Comment by ehuss** [comment] 2022-11-23 05:33
I think we're still interested in improving Cargo's progress output. #8889 contains the most recent discussion along with some examples. I'm going to close this as a duplicate of #8889 since it has the most recent information.

**Closed by ehuss** 2022-11-23 05:33 UTC
Labels: C-feature-request, A-console-output
