### ISSUE TITLE
Avoid compiling a local crate for each crate depending on it

### ISSUE THREAD

**Issue by lyptt** [rust-lang/cargo#5052] opened 2018-02-18 10:53 UTC
Currently it seems that when adding a local crate like this:

```
my-crate = { path = "../my-crate }
```

Every crate will build its own copy of that local crate.

Ideally it would be nice if you could build it once and link to it from all of the other crates, which would save on build times.

**Comment by alexcrichton** [comment] 2018-02-20 01:12
Thanks for the report! Can you provide a sample project to reproduce this with?

**Comment by lyptt** [comment] 2018-02-20 10:32
Sure, I've attached a series of crates that reproduce this.

To reproduce, `cargo build` testbin, then `cargo build` testbin2. Note that `testlib` is compiled twice. I would've thought the library would only need to be compiled once, with the resulting binary being present in its target directory. Instead, the crate is treated the same as one pulled from crates.io, and built every time for each dependent crate.

If the former behaviour was added this would massively boost my compile times, which is the main reason I'm interested in this. I use a local crate to contain shared behaviour between a bunch of microservices, and the microservices themselves are quite small, so this would end up shaving off a ton of time in my CI process.

[projects.zip](https://github.com/rust-lang/cargo/files/1739707/projects.zip)

**Comment by lyptt** [comment] 2018-02-20 14:39
I've discovered a workaround which is to define all of the binaries in a workspace, like so:

```
[package]
name = "testbinws"
version = "0.1.0"
authors = ["rhys"]

[dependencies]
testlib = { path = "./testlib" }

[[bin]]
name = "testbin"
path = "testbin/src/main.rs"

[[bin]]
name = "testbin2"
path = "testbin2/src/main.rs"

[workspace]
```

This is far from ideal though. This would mean all of the binaries would be versioned together, and would share the same set of dependencies.

**Comment by alexcrichton** [comment] 2018-02-26 15:20
Ah ok, thanks for the extra information! I'm going to close this as this is intended behavior, but to reduce your build times you've got a few options:

* Primarily you can organize crates into a workspace. For example placing a `Cargo.toml` with `[workspace]` and filling out `members` should get this working.
* You can also compile with a shared `CARGO_TARGET_DIR` by explicitly configuring that.

Otherwise it's intentional that all projects have their own isolated build directory, so this is working as intended.

**Closed by alexcrichton** 2018-02-26 15:20 UTC

**Comment by lyptt** [comment] 2018-02-26 15:25
Looks like `CARGO_TARGET_DIR` is exactly what I want. Thanks! 🎉
