### ISSUE TITLE
fix: allow fixing of trivial errors

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#5853] opened 2018-08-02 11:50 UTC
````rust
fn main() {
    let a = String::from("hello");
    print(a);
}

fn print(input: &str) {
	println!("{}", input);
}
````

````
error[E0308]: mismatched types
 --> src/main.rs:3:11
  |
3 |     print(a);
  |           ^
  |           |
  |           expected &str, found struct `std::string::String`
  |           help: consider borrowing here: `&a`
  |
  = note: expected type `&str`
             found type `std::string::String`
error: aborting due to previous error
````

The correct fix is already suggested, it would be great if cargo fix could apply that to the codebase.
````
cargo 1.29.0-nightly (2cd36b4ed 2018-07-25)
````

**Comment by dwijnand** [comment] 2018-08-02 11:52
Duplicate of #5846

**Comment by alexcrichton** [comment] 2018-08-02 13:34
Indeed!

**Closed by alexcrichton** 2018-08-02 13:34 UTC
