### ISSUE TITLE
It should be possible to tell cargo when to rerun the build script

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#1769] opened 2015-06-29 15:59 UTC
I have a static C library I am building with make.
I'd like to work on that library and my crate that depends on it simultaneously.
However, if I only change the C library, and not touch the Rust source code, the build script is never rerun, even if the C library's source code was modified.

There should be a way to run a custom script that checks whenever the build script should be re-run.

Perhaps there could be a pre-build script that would output whether the build script should be rerun or not.

**Comment by crumblingstatue** [comment] 2015-06-29 16:01
Possibly related to https://github.com/rust-lang/cargo/issues/1162.
Maybe the pre-build script solution could be used for solving both issues.

**Comment by alexcrichton** [comment] 2015-06-29 18:00
Could you elaborate a little more on the directory structure and layout? With a build script Cargo will automatically re-run it and rebuild the library if any file in the directory tree changes, but if you have the C library hosted *outside* the directory of the Rust library then Cargo will not see the changes.

**Comment by crumblingstatue** [comment] 2015-06-29 18:07
Yes, the C library is hosted outside of the project directory, as it is a separate project.
What I want to do is work on the C library, and test it with the Rust project without having to separately build the C library and copy it over whenever I want to test a change.

**Comment by alexcrichton** [comment] 2015-06-29 22:37
Does the build script build the library from source? Or is the build script just printing out information of how to link to the library?

Now that I've done some digging I'm also going to close this as a duplicate of https://github.com/rust-lang/cargo/issues/1162 which is a way for the build script to print out what its dependencies are.

**Closed by alexcrichton** 2015-06-29 22:37 UTC

**Comment by crumblingstatue** [comment] 2015-06-30 07:35
It's building the library from source.

**Comment by alexcrichton** [comment] 2015-06-30 17:00
If it's building the library from source then you'll want to move the source into the directory for `cargo package` to succeed, otherwise it won't package up the source to be shipped to crates.io

**Comment by crumblingstatue** [comment] 2015-06-30 17:21
This isn't a project that's intended to be published to crates.io.
