### ISSUE TITLE
Don't force recompilation when setting/removing the --error-format compiler flag

### ISSUE THREAD

**Issue by excaliburHisSheath** [rust-lang/cargo#3141] opened 2016-09-30 12:59 UTC
Over in AtomBuild/atom-build-cargo#65 I'm running into the issue that building my project from the editor includes `RUSTFLAGS=--error-format=json`, so switching between building in the editor and building from my terminal causes my entire project, including all dependencies, to be recompiled. Would it be possible to not force recompilation on all crates if the error format flag changes?

I suspect that this would piggy-back off #2982, but if it could be implemented without waiting on direct support for a `--error-format` cargo flag or be made to work with `RUSTFLAGS`, then I would appreciate that greatly.

**Comment by alexcrichton** [comment] 2016-09-30 16:06
Thanks for the report! I think this is indeed a dupe of https://github.com/rust-lang/cargo/issues/2982 which is being fixed in https://github.com/rust-lang/cargo/issues/3000. In general though this is expected behavior as `RUSTFLAGS` is opaque to Cargo so it must assume the worst and bust all caches if it changes. With #3000 though it has specific knowledge that this *doesn't* break the cache!

**Closed by alexcrichton** 2016-09-30 16:06 UTC

**Comment by excaliburHisSheath** [comment] 2016-09-30 16:32
Excellent, thanks for the info!
