### ISSUE TITLE
Cargo requires a registry update when switching toolchains

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2906] opened 2016-07-22 17:22 UTC
If I run `cargo build`, then `rustup override set $someothertoolchain`, then `cargo build` again the first thing Cargo does is update the registry. It's not going to learn anything by doing this, and testing with multiple toolchains is something people may well do while disconnected from the network. Cargo should recognize this case and not do the update.

cc https://github.com/rust-lang/cargo/issues/2895

**Comment by brson** [comment] 2016-07-22 17:26
Hm, it looks to me like it also may redownload all crates in this case.

**Comment by alexcrichton** [comment] 2016-07-22 17:47
This can happen over time because Cargo's representation of the registry directory structure changes, mainly the `hash` implementation of `Url` which affects the characters in a directory. Recently the hash has become more stable, though, so it should be working? What versions of Cargo were you changing between?

**Comment by carols10cents** [comment] 2017-09-26 16:40
I just switched from cargo 0.21.0 (5b4b8b2ae 2017-08-12) (rustc 1.20.0 (f3d6973f4 2017-08-27), current stable) to cargo 0.22.0-beta (3d3f2c05d 2017-08-27) (rustc 1.21.0-beta.3 (ea1fd7d42 2017-09-15), current beta) and I did not see any "updating registry" or "downloading" output, so closing as unable to reproduce!

**Closed by carols10cents** 2017-09-26 16:40 UTC
