### ISSUE TITLE
Cargo book should explain that features must be additive

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/cargo#8458] opened 2020-07-06 18:45 UTC
Cargo features must be additive, because if two crates agree on the version of a common dependency, but want different features from it, that dependency is built only once, with the union of the features requested. So if a crate can meet a dependent's expectations with a given set of features enabled, it must still meet those expectations if additional features are enabled.

This is a pretty fundamental restriction on how you can use features, but the Cargo book doesn't mention it in the section on features. It would be a natural fit in the 'Rules' section.

**Comment by Eh2406** [comment] 2020-07-06 18:50
That is an important restriction on features, Yes. If there is a good place to add it to docs I'd be open to seeing a PR. 

Thank you!

**Comment by ehuss** [comment] 2020-07-07 01:32
Thanks for the report!  This is a duplicate of #4328, so closing in favor of that.

**Closed by ehuss** 2020-07-07 01:32 UTC
Labels: C-bug

**Comment by jimblandy** [comment] 2020-07-07 02:11
@ehuss D'oh, thanks. I did search, but I guess I didn't find the magic set of terms...
