### ISSUE TITLE
`cargo publish --dry-run` should report unsupported category slugs

### ISSUE THREAD

**Issue by gendx** [rust-lang/cargo#14184] opened 2024-07-03 21:04 UTC
### Problem

When running `cargo publish --dry-run` on a crate with a category unsupported on crates.io, the dry run succeeds, but when running the real `cargo publish`, this now triggers a hard error (since https://github.com/rust-lang/crates.io/pull/8930):

```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): The following category slugs are not currently supported on crates.io: voting

  See https://crates.io/category_slugs for a list of supported slugs.
```

It would be good if the dry run could detect that.

### Proposed Solution

Cargo could contact an endpoint on the registry (be it crates.io or wherever the package is being published) to fetch the list of existing categories, and match that locally against the categories defined in the Cargo.toml.

Apart from the rare TOCTOU when the list of categories changes (does it ever change?), this should be sufficient to make the dry run more representative of the real run.

**Comment by ehuss** [comment] 2024-07-03 21:09
Thanks for the report! The issue looks like a duplicate of https://github.com/rust-lang/cargo/issues/4377, so closing in favor of that.

**Closed by ehuss** 2024-07-03 21:09 UTC
Labels: C-feature-request, S-triage
