### ISSUE TITLE
Output rustc version when running with --verbose

### ISSUE THREAD

**Issue by sunjay** [rust-lang/cargo#3945] opened 2017-04-23 20:51 UTC
Sorry in advance if this is a duplicate.

Cargo hides most of the details of the build process. This is usually a really great thing! Most Rust programmers, including myself, never have to invoke `rustc` manually thanks to cargo.

One point of frustration about cargo is that it doesn't give you any information about which *version* of rustc it is using to build your code. 

This usually doesn't matter, but sometimes it really can. For example, today, I found out that I have been building my crate targeted at stable rust on nightly for the past two months. The only reason I caught it at all is because I have Travis CI setup and it failed to build stable while nightly and beta both worked. Someone else without that extra tool would have missed that entirely. Had cargo logged a bit more information, I would have known about this much sooner.

This is also an issue when sharing code. If my crate is targeted at a specific version of nightly, I can debug why someone is unable to build it just by looking at the top line of their compiler output. I can verify, within seconds, that the right/wrong version is being used. It's nice to be reassured that what you expect to happen is in fact happening.

There's some issues out there about making the rustc version configurable through a file or something like that. That's not what this issue is about. This is an even simpler thing we can do to let people know a bit more about what cargo is doing. 

I think cargo would really benefit, if we logged the rustc version (or toolchain, or whatever makes sense) when starting a build. It's an easy way to let people know if they're running on what they expect.

## Example

Let's go from this:
```bash
$ cargo run examples/hello-world.bf 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/brainfuck examples/hello-world.bf`
Hello World!
```

To something like this:
```bash
$ cargo run examples/hello-world.bf 
       rustc nightly-2017-03-04
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/brainfuck examples/hello-world.bf`
Hello World!
```

It's one more line of output, but it gives you a whole lot more insight into what's going on.

The version could be just the version number (e.g. 1.17), or the nightly date (nightly-2017-03-04), or something else that makes sense.

**Comment by alexcrichton** [comment] 2017-04-24 16:12
Thanks for the report! I know I've been bitten by this before and it's always a pain to debug.

That being said though, I'm wary of adding more info with few data points. I'm sure everyone's got their own story for something like this, and "that one piece of output" that'd have helped fixed the problem is pretty small. The problem though is that in the limit we become autoconf, where everyone's "one piece of small output" is somewhere in there if you hunt long enough.

I personally value the quality of output from Cargo today, and I'd even consider it too verbose for larger projects where there's just a mountain of "Compiling ...". I'm not super keen on extending it continually over time.

All that being said, though, I think it's totally fine to add more output. I think we just need some broader consenus that it needs to happen (this is how the "Finished ..." line was added). Along those lines...

cc @wycats @matklad @carols10cents @brson

**Comment by Mark-Simulacrum** [comment] 2017-04-24 20:59
We could change the existing `Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs` to `Finished dev [unoptimized + debuginfo] target(s) on nightly-YYYY-MM-DD in 0.0 secs`. That is a minimal change that also avoids adding more lines to the output. This might be a "best of both worlds," though it has the unfortunate side effect that it only outputs once the build is finished, which means you can't catch this at build-start, but I think this is a minor downside.

**Comment by sunjay** [comment] 2017-04-25 00:58
@alexcrichton I was also iffy about adding the extra line. I like @Mark-Simulacrum's suggestion since it avoids the extra line while still providing the output we want. 

I think this is definitely a problem and we should address it in some reasonably visible way. Cargo should be magical in the sense that it hides the majority of the build from you, but it shouldn't hide things that can result in subtle breakages.

**Comment by carols10cents** [comment] 2017-04-25 13:01
> We could change the existing Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs to Finished dev [unoptimized + debuginfo] target(s) on nightly-YYYY-MM-DD in 0.0 secs.

I do like the idea of adding the rust version to an existing line, but the "Finished" line doesn't show up if there were compiler errors :( That means it wouldn't be useful for this case:

> This is also an issue when sharing code. If my crate is targeted at a specific version of nightly, I can debug why someone is unable to build it just by looking at the top line of their compiler output. I can verify, within seconds, that the right/wrong version is being used. It's nice to be reassured that what you expect to happen is in fact happening.

I'd be in favor of adding a new line that is output immediately, before any other build output, personally, even given the slippery slope of adding "just one more line".

Another option could be adding this new line only to the verbose output, which would mean you'd have to know to try and ask for `cargo build -v` output.

**Comment by Mark-Simulacrum** [comment] 2017-04-25 13:32
We could also add a `Errored ..` line to pair with the successful `Finished` line.

**Comment by alexcrichton** [comment] 2017-04-26 04:41
I *definitely* think we can make the `-v` output have this, that to me is a no-brainer and I think we could r+ a PR for that today. I'd only hesitate at tweaking the current stable output.

It seems reasonable to me to have Cargo print something on an error. Knowing how long it took to generate the error is also useful! In that sense if we fold this into the "finished" line that seems plausible to me to happen on both success/error.

> it shouldn't hide things that can result in subtle breakages.

I somewhat disagree with this. For example any number of these could cause subtle breakages, but we don't print them:

* Cargo's version
* Rustc's version
* Rustc's host 
* Cargo's target for the compilation
* Precise profile settings like LTO, optimization, debuginfo, etc
* Where cargo/rustc are located
* Version of rustup and/or whether rustup is being used
* Version of all dependencies (if they're already built)
* Information about native libraries getting compiled

Depending on who you talk to "things that result in subtle breakage" can be totally different. Literally all of those have caused subtle breakage for myself in the past.

**Comment by matklad** [comment] 2017-04-27 15:53
I am mildly against adding this for non verbose builds: adding a tiny amount of noise in the majority of cargo runs seems to outweigh  the addition of an important information  for the tiny amount of runs. 

I definitely  have a problem remembering which rustup overrides I have enabled for which projects, but I would prefer a command-line prompt status solution, like the one with Python's virtualenvs.

**Comment by epage** [comment] 2023-10-11 21:50
Looks like you can use [starship to show the rust version](https://starship.rs/config/#rust)

I also agree this shouldn't be in the default output.  I kind of doubt people will notice this to help their situation if its in the verbose output.  It seems like for people using a lot of versions of rust, a shell prompt is the best path forward.  As such, I'm going to propose to the cargo team that we close this.

**Comment by weihanglo** [comment] 2023-10-12 00:27
Is there any thing that might make `cargo +toolchain -vV` get a different version of Rust from `cargo +toolchain build --verbose`? If not, I also lean toward closing this, as people can always have `cargo -vV` output either in the interactive shell, or in CI.

**Comment by epage** [comment] 2023-10-12 02:27
I can't think of any and I would expect if there were, it would cause problems because cargo can have some coupling to specific rustc behavior (even though I occasionally am running `master` cargo with stable rustc...)

**Comment by weihanglo** [comment] 2023-10-12 17:23
Indeed. Let's close it.

**Closed by weihanglo** 2023-10-12 17:23 UTC
Labels: C-feature-request, A-console-output, S-propose-close
