### ISSUE TITLE
`error: package ID specification `panic_unwind` did not match any packages` with `-Zbuild-std`

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/cargo#14935] opened 2024-12-15 03:25 UTC
Update to latest rust nightly: `cargo 1.85.0-nightly (769f622e1 2024-12-14)` got `error: package ID specification `panic_unwind` did not match any packages` when build with `-Zbuild-std` option.

It happened only on today's update, all builds before have no problems.

What does it mean? And how to fix it...

**Comment by weihanglo** [comment] 2024-12-15 04:15
Could you share a minimal reproducible example, with the complete error mesaage? Like the content of your `.cargo/config.toml`, crates and features specified in `-Zbuild-std` and `-Zbuild-std-feature, env var like RUSTFLAGS, and the target platform you're building.

It might be related to <https://github.com/rust-lang/cargo/pull/14899>, which automatically determine building `core` or `std`, if `-Zbuild-std` has no crate specified.

**Comment by Wyvern** [comment] 2024-12-15 08:40
> Could you share a minimal reproducible example, with the complete error mesaage? 

This is the *`complete error mesaage`*, the only output content before actually start building.

>Like the content of your `.cargo/config.toml`, crates and features specified in `-Zbuild-std` and `-Zbuild-std-feature`

`-Zbuild-std=std,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort"`

**Comment by Wyvern** [comment] 2024-12-15 08:42
>It might be related to https://github.com/rust-lang/cargo/pull/14899, which automatically determine building core or std, if -Zbuild-std has no crate specified.

I try to remove `-Zbuild-std-features=panic_immediate_abort` and build succeeded. NOT sure it related to https://github.com/rust-lang/cargo/pull/14899.

**Comment by weihanglo** [comment] 2024-12-17 04:07
This failed because since 125e873dffc4b68b263c5decd88750ec10fd441e
[`std_resolve`][1] only includes `sysroot` as primary package.
When any custom Cargo feature is provied through `-Zbuild-std-feature`,
the default feature set `panic-unwind` wouldn't be gone, so
no `panic_unwind` crate presents in `std_resolve`.

When then calling [`std_resolve.query`][2] with the default set of
crates from [`std_crates`][3], which automatically includes
`panic_unwind` when `std` presents, it'll result in spec not found
because `panic_unwind` was not in `std_resolve` anyway.

[1]: https://github.com/rust-lang/cargo/blob/addcc8ca715bc7fe20df66afd6efbf3c77ef43f8/src/cargo/core/compiler/standard_lib.rs#L96
[2]: https://github.com/rust-lang/cargo/blob/addcc8ca715bc7fe20df66afd6efbf3c77ef43f8/src/cargo/core/compiler/standard_lib.rs#L158
[3]: https://github.com/rust-lang/cargo/blob/addcc8ca715bc7fe20df66afd6efbf3c77ef43f8/src/cargo/core/compiler/standard_lib.rs#L156

**Comment by Manishearth** [comment] 2024-12-17 20:32
A simple reproduction for this is `cargo +nightly rustc   -Z build-std=std,panic_abort   -Zbuild-std-features=panic_immediate_abort` on an empty `cargo new --lib foo` crate.


I was able to cargo bisect-rustc it down to https://github.com/rust-lang/rust/pull/134278

@weihanglo can that commit be reverted?

**Comment by weihanglo** [comment] 2024-12-17 20:39
@Manishearth 
I have a patch pending for review #14938.
Prefer getting it merged and do a submodule update.

A revert of #14899 or rust-lang/rust#134278 isn't better IMO. Some target platforms unsed to compile std successfully and now are just rejected to build just because they have `metadata.std: false`.

**Comment by Manishearth** [comment] 2024-12-17 20:46
Ah, that works, I didn't realize there was a PR.

**Comment by epage** [comment] 2024-12-17 23:20
In reviewing #14938, I am concerned about the state of the implementation of build-std.  It feels like we've accumulated a mountain of patches on  top of each other without a clear goal of where its going and out of expediency for each problem that is run into.  I feel like build-std doesn't just need a clear picture of what it is and where its going to be stabilized, but to clean up the implementation so its possible to understand what is being reviewed.

CC @davidtwco

**Closed** 2024-12-18 01:25 UTC
Labels: Z-build-std, S-needs-info, regression-from-stable-to-nightly
