### ISSUE TITLE
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

### ISSUE THREAD

**Issue by ddt-tdd** [rust-lang/cargo#2783] opened 2016-06-12 09:41 UTC
I saw issue #886 with the same title but it did' solve my issue.
I have forked sflacker's openssl library to add a functionality ca_generate(cacert, pkey) to generate a certificate signed by certification authority.
Now my web server, based on hyper, uses openssl 0.7.13 (probably from sflacker) and eidonkey also uses openssl 0.7.13 (my patched version (https://github.com/ddt-tdd/rust-openssl)).
I get the error:
error: native library `openssl` is being linked to by more than one package, and can only be linked to by one package

  openssl-sys v0.7.13 (https://github.com/ddt-tdd/rust-openssl.git#17bed784)
  openssl-sys v0.7.13

My question is how I can patch/extend the openssl-crate, test it locally with hyper without conflicts? 
This is probably not only for the openssl-crate, but all other crates which developers want to extend.

Greetings,
DDT

PS: Afterwards I ask sflacker for a pull-request, when I'm certain it works.

**Comment by alexcrichton** [comment] 2016-06-12 10:25
Thanks for the report! This is currently working as expected, yeah, but what you'll want to do is to use the `[replace]` section of `Cargo.toml` while you're working on this library. The idea is that all other dependencies on `openssl-sys` need to be rewritten to your fork as well.

If you need more help though, please feel free to let me know! I'm just gonna close this because it's expected behavior, but I want to make sure it works out for you as well!

**Closed by alexcrichton** 2016-06-12 10:25 UTC
