### ISSUE TITLE
Published crates with binaries should contain Cargo.lock

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/cargo#3706] opened 2017-02-15 09:32 UTC
As it's seen as a good and recommended practice to track Cargo.lock in git for binaries, it's a little awkward not to dist them during `cargo publish`.
Is that intentional or was it just forgotten?

**Comment by alexcrichton** [comment] 2017-02-15 14:51
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/2263, but thanks for the report!

**Closed by alexcrichton** 2017-02-15 14:51 UTC
