### ISSUE TITLE
proc-macro + `-Zsanitizer=address` = Linking error

### ISSUE THREAD

**Issue by Volker-Weissmann** [rust-lang/cargo#10666] opened 2022-05-12 23:57 UTC
### Problem

If you give `-Zsanitizer=address` and use a proc-macro crate, you get an ugly linking error. It should either compile, or give a nicer error message.

### Steps

Take [this example crate](https://github.com/rust-lang/cargo/files/8683156/mycrate.zip)

`cargo build` works fine, but

```
$  RUSTFLAGS="-Zsanitizer=address" cargo build                                                                                                                                                         
   Compiling otherlib v1.0.0 (/home/volker/Documents/bug/mycrate/otherlib)
   Compiling mycrate v1.0.0 (/home/volker/Documents/bug/mycrate)
error: /home/volker/Documents/bug/mycrate/target/debug/deps/libotherlib-b3d905195a09f55e.so: undefined symbol: __asan_register_elf_globals
 --> src/lib.rs:1:5
  |
1 | use otherlib;
  |     ^^^^^^^^

error: could not compile `mycrate` due to previous error
```

### Notes

```
$ rustc --version -v                                                                                                                                                                            
rustc 1.62.0-nightly (52ca603da 2022-04-12)
binary: rustc
commit-hash: 52ca603da73ae9eaddf96f77953b33ad8c47cc8e
commit-date: 2022-04-12
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.0
```

### Version

```text
cargo 1.62.0-nightly (e2e2ddd 2022-04-05)
release: 1.62.0-nightly
commit-hash: e2e2dddebe66dfc1403a312653557e332445308b
commit-date: 2022-04-05
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by ehuss** [comment] 2022-05-13 00:19
Thanks for the report!  The issue is that RUSTFLAGS is passed to proc-macros without the `--target` flag. The workaround is to use `--target`. I believe sanitizers only fully work with `build-std` as well. This is discussed a bit in the documentation [here](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#build-scripts-and-procedural-macros).

I'm going to close as a duplicate of https://github.com/rust-lang/rust/issues/63986, https://github.com/rust-lang/rust/issues/48199, #3739 and others.  If you have further issues with using sanitizers, I would recommend filing issues at https://github.com/rust-lang/rust/issues as Cargo doesn't really have any interaction with them.

**Closed by ehuss** 2022-05-13 00:19 UTC
Labels: C-bug
