### ISSUE TITLE
workspace.dependencies appears to cause git-based references to fail as of 1.71

### ISSUE THREAD

**Issue by rtyler** [rust-lang/cargo#12452] opened 2023-08-05 20:31 UTC
### Problem

This issue was originally reported via @cmackenzie1 in delta-io/delta-rs#1580 but in essence we moved delta-rs to use workspace.dependencies and then the latest tagged release can no longer be loaded properly from git by cargo on any version prior to 1.71, e.g.

```
$ rustup install 1.70.0
$ cargo +1.70.0 update
    Updating crates.io index
    Updating git repository `https://github.com/delta-io/delta-rs.git`
error: no matching package named `deltalake` found
location searched: https://github.com/delta-io/delta-rs.git?tag=rust-v0.14.0
```

The same code reference with 1.71 works just fine, e.g.

```
$ rustup install 1.71.0
$ cargo +1.71.0 update
    Updating crates.io index
    Updating git repository `https://github.com/delta-io/delta-rs.git`
```

Both examples use the same `Cargo.toml`: 

```toml
[dependencies]
deltalake = { git = "https://github.com/delta-io/delta-rs.git", tag = "rust-v0.14.0", features = [
    "s3",
    "parquet",
    "arrow",
    "datafusion",
] }
```

I can attest that the tag [exists in our repo](https://github.com/delta-io/delta-rs/releases/tag/rust-v0.14.0). I am guessing that the presence of `workspace.dependencies`, or the change for the `rust/Cargo.toml` to rely on them for some reason causes older Cargo versions to break.

### Version

```text
cargo 1.71.1 (7f1d04c00 2023-07-29)
release: 1.71.1
commit-hash: 7f1d04c0053083b98fa50b69b6f56e339b0556a8
commit-date: 2023-07-29
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: openSUSE 20230601 [64-bit]
```
```

**Comment by Muscraft** [comment] 2023-08-05 20:59
I think this is caused by [`debug = "line-tables-only"`](https://github.com/delta-io/delta-rs/blob/2f9a67f79f3d06367108925424609dfa1d24786e/Cargo.toml#L13) not `[workspace.dependencies]`. `debug = "line-tables-only"` was added in `1.71.0` and can only be read by `cargo v1.71.0+`. On Cargo versions before this, it will fail to parse the `Cargo.toml` with the following error:
```
error: failed to parse manifest at `{dir}/rust/delta-rs/Cargo.toml`

Caused by:
  expected a boolean or an integer
  in `profile.test.debug`
```

**Comment by rtyler** [comment] 2023-08-06 19:02
@Muscraft interesting, thanks for the insight. Would it be a bug that the error message isn't propagated clearly when referencing the Git branch?  I am wondering if you have a suggestion for making the `Cargo.toml` compatible with older versions of Cargo while still supporting `line-tables-only`

**Comment by ehuss** [comment] 2023-08-06 19:25
I think the error message issue is tracked in #6211. The comments there should explain why the correct error message isn't always displayed, and some of the complexities around fixing that. Manifests that fail to parse are intentionally ignored, so there would probably need to be some set of deferred errors that get displayed if nothing is found.

I don't think there is a way to support older Cargos when using new syntax or features, at least for this specific circumstance.

**Comment by Muscraft** [comment] 2023-08-06 21:42
I created #12455 as an idea to ensure problems like this do not happen in the future.

**Comment by weihanglo** [comment] 2023-08-16 10:04
Going to close this since we have both #6211 and #12455 tracking it. Let us know if this should be remain open or if you have any question.

**Closed by weihanglo** 2023-08-16 10:04 UTC
Labels: C-bug, S-triage
