### ISSUE TITLE
Wrong `depending on same version` detection

### ISSUE THREAD

**Issue by nico-abram** [rust-lang/cargo#7171] opened 2019-07-23 22:50 UTC
Depending on the same crate twice using two different, but similar, versions gives me an error about depending on the same version. Changing it to depend on a more different version fixes it.
Example:
```

[dependencies]
glium =  "0.25"
imgui =  "0.1.0"
imgui-glium-renderer = "0.1.0"
imgui-winit-support = "0.1.0" 
imgui_copy = { version = "0.1.0-rc.1", package = "imgui" }
```
Output:
`error: the crate `test-imgui v0.0.2 (C:/_)` depends on crate `imgui v0.1.0` multiple times with different names`
Changing one to version "0.0.X" works.

**Comment by ehuss** [comment] 2019-07-23 23:49
I think this is to be expected.  The semver requirement `^0.1.0-rc.1` will resolve to `0.1.0`, and you can't have two of the same version.  You can use `=0.1.0-rc.1` to force the use of a pre-release, but that still won't work in your situation because it is still considered semver-compatible to `0.1.0` and it won't let you do that.

**Comment by ehuss** [comment] 2019-09-21 19:11
I'm going to close this as somewhat expected, and a duplicate of #6016.  Pre-releases don't quite work very well now (see #2222 which covers some of what is wrong).

**Closed by ehuss** 2019-09-21 19:11 UTC
Labels: C-bug
