### ISSUE TITLE
target.'cfg(debug_assertions)'.dependencies doesn't work as expected

### ISSUE THREAD

**Issue by benediktwerner** [rust-lang/cargo#7634] opened 2019-11-27 03:50 UTC
**Problem**
Specifying conditional dependencies using `target.'cfg(debug_assertions)'.dependencies` does not work as expected (i.e. only building the dependencies when debug assertions are enabled) and instead always includes the dependencies. The same applies for `cfg(test)` and `cfg(proc_macro)` although `dev-dependencies` can be used instead of `cfg(test)`.

I guess it kind of makes sense that only `cfg`-attributes that have something to do with a target work in this context however it is still very confusing and unexpected. Also, the [documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) explicitly mentions that `cfg(feature = ...)` doesn't work so I would expect everything else to work.

**Steps**
Using this Cargo.toml
```toml
[package]
name = "test"
version = "0.1.0"
authors = []
edition = "2018"

[target.'cfg(debug_assertions)'.dependencies]
color-backtrace = "0.3"
```
and compiling with `cargo build --release` still compiles `color-backtrace`.

**Possible Solutions**
1. Clarify in the [documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) that only `cfg`-attributes related to targets work in this context. In that case, it would be good to add another way to include dependencies only for debug or release builds e.g. using `profile.dev.dependencies`. (This might be a good idea in any case).
2. Allow all `cfg`-attributes in the target context. The main problem why this currently doesn't work is that the `cfg` values are taken from `rustc --print cfg` which always includes `debug_assertions`. One option would be to call `rustc` using the correct attributes for optimization, crate type, etc. but this would require some changes as this is currently computed as part of [`TargetInfo`](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/build_context/target_info.rs) which is independent of any flags related to profiles. Another option would be to fix the `cfg` list at the uses where profile flags would be available. Although this is kinda hacky it would be fairly easy to do as there are only 5 uses of the `cfg` list and they all have profile information available.

Personally I think solution 2 will always be a bit messy so it's probably best to add something like `profile.dev.dependencies` instead. I would be happy to implement this if it sounds like a good idea.

**Comment by ehuss** [comment] 2019-11-27 04:44
I think this is essentially a duplicate of #5777.

I'd be a little uneasy about trying to set debug-assertions in TargetInfo because there isn't one profile, but instead a profile per unit, based on various factors (cargo target, package, cli flags, etc.).

**Comment by benediktwerner** [comment] 2019-11-27 06:23
Yeah, you are right, it's basically the same issue. But that issue also doesn't have a solution so the question is still what the best solution for this would be.

As for setting `debug_assertions` in `TargetInfo`, that's exactly what I meant when I said it's independent of any flags related to profiles. It doesn't really make sense to include it there. I think the main question is if `target.cfg(...).dependencies` should even support all configuration values in the first place. Features already don't work after all. It looks like this wasn't really supposed to be a real `cfg` check but only a more advanced target selection with a pretty unfortunate syntax but now it's probably already too late to change that. However, in the end, this would of course also be more powerful, it just isn't really correct to put this under `target`.
But if we want to get proper `cfg` checking the best way would probably be to separate it out of TargetInfo. The thing is this also gets a bit nasty with stuff like `cargo fetch` which doesn't even care about profiles. It should probably ignore all attributes that aren't about targets.

**Comment by ehuss** [comment] 2019-12-01 16:13
I think it would be best for now if Cargo generated an error if it sees `debug_assertions` or `feature=…`.

**Comment by benediktwerner** [comment] 2019-12-04 04:02
Ok, I guess that's the simplest solution for now. I'm going to have a shot at implementing that error and probably also create a PR to update the docs. What do you think about something `profile.dev.dependencies`? Would it make sense to create a proposal/RFC or something for that?

**Comment by ehuss** [comment] 2019-12-04 19:52
I don't know how profile-specific dependencies would work.  A single artifact can consist of multiple profiles, and a single invocation can do multiple things with different profiles.  It seems like it would be difficult.

**Comment by benediktwerner** [comment] 2019-12-05 10:31
Interesting, I thought there was always only one profile active for a specific build/run. To me, it looks like the CompileOptions also only have a single profile. But whatever, I guess this isn't really that important.

**Closed** 2019-12-09 17:50 UTC
Labels: A-configuration, A-errors, C-bug

**Comment by huntc** [comment] 2021-12-08 08:50
Is it also true that the following is not permitted in the `config.toml`?

```
[target.'cfg(not(debug_assertions))']
```

i.e. without the `.dependencies` suffix?
