### ISSUE TITLE
cargo-installed tools broken after Rust updates

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#3802] opened 2017-03-07 14:48 UTC
Tools installed by `cargo install` depend on specific versions of Rust libraries. Rust upgrades update the libraries without updating the tools, which breaks the tools.

```sh
cargo install clippy
rustup update
cargo clippy # crashes, can't find its specific library version
```

I suspect ideal solution would be for Rust to have a stable ABI, but that may not happen anytime soon, so it would be good to have an interim solution. 

For example, when a cargo-installed command is run via cargo (e.g. `cargo clippy`), Cargo should check if it was build for the current Rust version and rebuild it if necessary.

[Lack of easy tool updates](https://github.com/rust-lang/cargo/issues/2082) makes the problem worse.

**Comment by alexcrichton** [comment] 2017-03-07 19:45
I believe this is a dupe of https://github.com/rust-lang-nursery/rustup.rs/issues/765, but thanks for the report!

**Closed by alexcrichton** 2017-03-07 19:45 UTC
