### ISSUE TITLE
features on workspace

### ISSUE THREAD

**Issue by driftluo** [rust-lang/cargo#5251] opened 2018-03-27 12:48 UTC
Today, I encountered a problem with the overall compilation of the workspace and the inconsistent compilation of each crate.

We have a public logger crate, the default is output to a file, open console features will be output to the terminal.

Some crates in the workspace have this feature turned on, while others do not need to be turned on.

`Cargo bulid --all` will cause the entire workspace's crates to be output to the terminal.

Compile each crate separately, it will normal to open different logger modes.

This behavior makes me very confused.

relate: #4463

**Comment by matklad** [comment] 2018-03-27 12:56
@driftluo yep, this is a duplicate of #4463, so closing the issue in favor of that one. 


Note, however, that Cargo features are intended to be additive. That is, from Cargo's point of view, it's never a semantic error to activate more features than actually necessary. So in that sense, using a cargo feature to determine if the logging should go to file or to the console might not be the best approach.

**Closed by matklad** 2018-03-27 12:56 UTC
