### ISSUE TITLE
Expose "debugging" flags like --explain and --emit

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1204] opened 2015-01-21 12:27 UTC
rustc flags like the above don't fundamentally change the final output, so it shouldn't get in the way of the goal of reliable builds to expose them. The latter is very useful when writing a performance-oriented project where it might be required to dig into why some example is optimising as well as one hopes, e.g. `cargo build --release --emit=asm,llvm-ir --example underperforming`.

Currently, one has to invoke `rustc` by hand, passing in `-L` flags manually to get it link dependencies, it would be nice to be able to leverage cargo's knowledge to do it automatically.

**Comment by alexcrichton** [comment] 2015-01-23 03:59
Closing as a dupe of https://github.com/rust-lang/cargo/issues/544 and https://github.com/rust-lang/cargo/issues/595, I think we want to avoid many top-level flags in `cargo build` to the compiler (where to draw the line?) but one of those two issues would definitely help out with this.

**Closed by alexcrichton** 2015-01-23 03:59 UTC
