### ISSUE TITLE
cargo update: show updating instead of add/remove if other incompatible versions were added/removed

### ISSUE THREAD

**Issue by djc** [rust-lang/cargo#12325] opened 2023-07-03 09:46 UTC
### Problem

<img width="309" alt="Screenshot 2023-07-03 at 11 43 48" src="https://github.com/rust-lang/cargo/assets/158471/b0e60042-96ed-471b-913b-8c142773b1cd">

In this case, it seems Cargo's analysis of the dependency changes kind of "fails" in that it could/should be showing "Updating rustifx v0.37.20 -> v0.37.22" but doesn't, presumably because there's also an "Adding rustix 0.38.2". It seems to me that condensing "Removing + Adding + Adding" to "Updating + Adding" based on the semver compatibility of the versions would be a superior experience, but maybe I'm missing something?

(I would probably be open to implementing this if the team agrees that it makes sense.

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: aarch64-apple-darwin
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 7.88.1 (sys:0.4.61+curl-8.0.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.4.1 [64-bit]
```

**Comment by weihanglo** [comment] 2023-07-03 13:18
Thanks for the suggestion! The current implementation only shows `Updating` if it is exact 1-to-1 upgrade for a package:

https://github.com/rust-lang/cargo/blob/be42872358db9c2a073fe161fcddb3d7caf2f247/src/cargo/ops/cargo_generate_lockfile.rs#L135

It is doable but a bit hard to say whether it is an upgrade if a package becomes two different versions after `cargo update`. We may need a clearer definition of each status before working on it.

**Comment by ehuss** [comment] 2023-07-03 14:47
I believe this is a duplicate of #12325. Feel free to reopen if that is not the case.

**Closed by ehuss** 2023-07-03 14:47 UTC
Labels: C-bug, Command-update, A-console-output, S-needs-design, S-triage

**Comment by djc** [comment] 2023-07-03 15:02
You linked to this issue as the duplicate... I'm guessing you had another one in mind but not in your clipboard? 🙂

**Comment by ehuss** [comment] 2023-07-03 15:18
Ah, sorry, it was #9408.
