### ISSUE TITLE
cargo clippy and cargo check don't recognize source code changes without --release flag

### ISSUE THREAD

**Issue by felix-pb** [rust-lang/cargo#9004] opened 2020-12-21 04:24 UTC
**Problem**
`cargo clippy` and `cargo check` don't recognize source code changes unless they are run with the `--release` flag (see steps below). I expect that both commands should output the same thing (e.g. same lints for `cargo clippy`) with or without the `--release` flag when the source code changes.

**Steps**
1. Run `cargo new playground` and `cd` into the project root.
2. Run `cargo clippy` and the output is:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.02s
```
3. Run `cargo clippy --release` and the output is:
```
Checking playground v0.1.0 (/Users/felix-pb/Desktop/playground)
Finished release [optimized] target(s) in 0.04s
```
4. Add `()` on a new line after the print statement in `src/main.rs`.
5. Run `cargo clippy` and the output is:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```
6. Run `cargo clippy --release` and the output is:
```
Checking playground v0.1.0 (/Users/felix-pb/Desktop/playground)
warning: unneeded unit expression
 --> src/main.rs:3:5
  |
3 |     ()
  |     ^^ help: remove the final `()`
  |
  = note: `#[warn(clippy::unused_unit)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

warning: 1 warning emitted
```

**Notes**

Output of `cargo version`: cargo 1.48.0 (65cbdd2dc 2020-10-14)

I'm using the current latest stable version of rustc.
Output of `rustc --version`: rustc 1.48.0 (7eac88abb 2020-11-16)
The problem is happening on both my personal and work laptops, both of which are macOS. My personal laptop is running macOS Big Sur (version 11.1) and my work laptop is running macOS Catalina (version 10.15.7). As far as I know, I haven't modified the default cargo settings on either of my laptops.

**Comment by felix-pb** [comment] 2020-12-21 04:39
I just realized that the issue happens when I run the commands inside the VS Code terminal, but not when I run the commands inside the macOS built-in "Terminal" app. Although I'm not sure of it, this is probably a problem with VS Code and not with Cargo. I'll investigate more later this week.

**Comment by taiki-e** [comment] 2020-12-21 04:45
I believe this is https://github.com/rust-lang/rust-clippy/issues/4612

**Comment by Eh2406** [comment] 2020-12-21 04:47
There are known bugs with clippy reusing caches from `check`, and so in effect clippy not being run. And @taiki-e found the link before me. It has been a long time cumming but Cargos part of the fix is coming in https://github.com/rust-lang/cargo/pull/8976

**Comment by felix-pb** [comment] 2020-12-21 04:49
Alright, but just to be clear, the issue happens even if I never run `cargo check` nor `cargo build` nor `cargo run` on the project.

**Comment by taiki-e** [comment] 2020-12-21 05:02
> the issue happens even if I never run `cargo check` nor `cargo build` nor `cargo run` on the project. Perhaps there is an implicit `cargo check` when I run `cargo clippy` though?

I guess this is due to rust-analyzer (or rls) automatically run `cargo check`.

**Comment by felix-pb** [comment] 2020-12-21 05:11
Bingo! That explains both why the issue happens even if I don't run `cargo check` before and why it only happens in VS Code and not in the built-in Terminal app. I confirmed this by performing step #4 (add `()` after the print the statement) in VS Code, and then running `cargo clippy` in the Terminal app where I get the unexpected output (because `cargo check` was ran by rust-analyzer). Thanks, can't wait for this fix!

**Comment by ehuss** [comment] 2020-12-21 17:15
Closing as a duplicate of https://github.com/rust-lang/rust-clippy/issues/4612.

**Closed by ehuss** 2020-12-21 17:15 UTC
Labels: C-bug
