### ISSUE TITLE
Searching for `ieee` does not show `ieee754` as a result.

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#3871] opened 2017-03-27 18:34 UTC
Check [here](https://crates.io/search?q=ieee) and[here](https://crates.io/search?q=ieee754)

**Comment by bluss** [comment] 2017-04-04 03:37
This is basically issue rust-lang/crates.io/issues/159

**Comment by carols10cents** [comment] 2017-08-02 23:27
Closing as a duplicate of rust-lang/crates.io#159

**Closed by carols10cents** 2017-08-02 23:27 UTC
