### ISSUE TITLE
`RUSTFLAGS` + `cargo build … --target <TARGET>` = error

### ISSUE THREAD

**Issue by regexident** [rust-lang/cargo#10275] opened 2022-01-08 16:42 UTC
### Problem

The combination of `RUSTFLAGS` + `cargo build … --target <TARGET>` results in (confusing) cargo error.

### Steps

1. Create a project:

    ```bash
    cargo new example
    cd example
    ```

3. Host build: ✅

    ```bash
    cargo build
    ```

4. Host build with warnings silenced: ✅

    ```bash
    RUSTFLAGS="-Awarnings" cargo build
    ```

3. Cross-platform build: ✅

    ```bash
    cargo build --target "<TARGET>"
    ```

4. Cross-platform build with warnings silenced: ❌

    ```bash
    RUSTFLAGS="-Awarnings" cargo build --target "<TARGET>"
    ```

    Result:

    ```console
    error: output of --print=file-names has changed in the compiler, cannot parse
    command was: `rustc - --crate-name ___ --print=file-names -Awarnings --target aarch64-apple-ios --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg`

    --- stdout
    ___
    lib___.rlib
    lib___.a
    /Users/vincent.esche/.rustup/toolchains/stable-x86_64-apple-darwin
    debug_assertions
    proc_macro
    target_arch="aarch64"
    target_endian="little"
    target_env=""
    target_family="unix"
    target_os="ios"
    target_pointer_width="64"
    target_vendor="apple"
    unix
    ```

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.64.1 (sys:0.4.49+curl-7.79.1 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 11.6.1 [64-bit]
```

**Comment by ehuss** [comment] 2022-01-08 16:56
Thanks for the report!  This is a known issue where the `-Awarnings` interferes with how cargo discovers the crate types of a target.

Closing as a duplicate of #8010.

**Closed by ehuss** 2022-01-08 16:56 UTC
Labels: C-bug

**Comment by regexident** [comment] 2022-01-08 17:34
Oh, my search somehow didn't return that existing issue.
