### ISSUE TITLE
Cargo test DYLD error

### ISSUE THREAD

**Issue by th0114nd** [rust-lang/cargo#1046] opened 2014-12-13 00:25 UTC
On version `22413d2`, `cargo` does not pass its tests because of a library not being able to be loaded.

```
$ cargo test
 Compiling hamcrest v0.1.0 (https://github.com/carllerche/hamcrest-rust.git#2b9bd6cd)
   Compiling cargo v0.1.0 (file:///Users/tim/cargo)
open     Running target/cargo-39287a133529d146
dyld: Library not loaded: /opt/local/lib/libcurl.4.dylib
  Referenced from: /Users/tim/cargo/target/cargo-39287a133529d146
  Reason: Incompatible library version: cargo-39287a133529d146 requires version 8.0.0 or later, but libcurl.4.dylib provides version 7.0.0
Process didn't exit successfully: `/Users/tim/cargo/target/cargo-39287a133529d146` (status=5)
```

The version of `curl` I have is the latest MacPorts has to offer, and I believe even the latest that curl.haxx.se has.
```
$ curl --version
curl 7.39.0 (x86_64-apple-darwin14.0.0) libcurl/7.39.0 OpenSSL/1.0.1j zlib/1.2.8 libidn/1.29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

It looks like something is requesting a version (>= 8.0.0) of `libcurl` that doesn't exist.

**Comment by alexcrichton** [comment] 2015-05-18 23:03
I believe this is probably because `pkg-config` detected a libcurl library at `/opt/local/lib` but your `DYLD_LIBRARY_PATH` didn't have that directory in your path, so the generated binary was linked against one library but then ran with another, causing the error.

I think that this will be fixed by just adjusting your `DYLD_LIBRARY_PATH`, but please feel free to reopen if it reproduces!

**Closed by alexcrichton** 2015-05-18 23:03 UTC
Labels: I-wrong
