### ISSUE TITLE
Allow any string for version field if publish = false

### ISSUE THREAD

**Issue by wiiznokes** [rust-lang/cargo#14083] opened 2024-06-16 19:54 UTC
### Problem

I'm creating an application, and i would like to use a different type of version format that semver. I know i could use an env var for this, and i will probably do this, but specify the version in the `version` field will have some benefit for me:
- automatic support for `clap`
- automatic support for `cargo-packager`

### Proposed Solution

Allow any string to be used when `publish = false`.

**Comment by weihanglo** [comment] 2024-06-16 22:05
Thanks for the proposal. Looks like it is a duplicate of #6583? See also questions in this comment <https://github.com/rust-lang/cargo/issues/6583#issuecomment-1785493031>. Note that if it is meant to be published to crates.io, then the version is required to follow SemVer. If not, https://github.com/rust-lang/cargo/pull/12786 makes `package.version` optional so you can just omit the field.

**Comment by weihanglo** [comment] 2024-06-16 22:13
Okay it is not effectively a duplicate. I can see the benefit of clap auto-populating the value. However, the proposed change will complicate Cargo internals and how external tools parsing the field quite a bit. We may need more use cases so can weigh between those options.

**Comment by epage** [comment] 2024-06-21 16:14
While not a duplicate of #6583, an important shared part to them is whether the version string is meant solely for the use of publishing or to also meet other needs (marketing version, PIP version, etc).

This also has the workaround that tools that want a non-registry version could use `package.metadata`.

With that, I would lean towards closing this as not planned.

**Closed** 2024-06-21 16:18 UTC
Labels: C-feature-request, A-manifest, S-needs-info, S-propose-close
