### ISSUE TITLE
Garbled error messages when building multiple binaries from same sources

### ISSUE THREAD

**Issue by osklil** [rust-lang/cargo#3041] opened 2016-08-25 12:01 UTC
If you build two different binaries from the same source files, error messages are repeated and mostly garbled.

**How to reproduce**
```
cargo new demo
echo -e '\n[[bin]]\nname = "p1"\npath = "src/main.rs"\n\n[[bin]]\nname = "p2"\npath = "src/main.rs"' >> demo/Cargo.toml
echo something > demo/src/main.rs
cd demo; cargo build
```

**Actual output**
```
   Compiling demo v0.1.0 (file:///home/usel/_t2/demo)
src/main.rs:1:1: 1:10 error: expected item, found `something`
src/main.rs:1:1: 1:10 src/main.rs:1 errorsomething:
              expected item, found `something`^~~~~~~~~

errorsrc/main.rs: aborting due to previous error:1
something
              ^~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `demo`.

To learn more, run the command again with --verbose.
```
**Expected output**
```
   Compiling demo v0.1.0 (file:///[...]/demo)
src/main.rs:1:1: 1:10 error: expected item, found `something`
src/main.rs:1 something
              ^~~~~~~~~
error: aborting due to previous error
error: Could not compile `demo`.
  
To learn more, run the command again with --verbose.
[more text]

**Comment by osklil** [comment] 2016-08-25 12:01
cargo 0.12.0-nightly (6b98d1f 2016-07-04)

**Comment by alexcrichton** [comment] 2016-08-25 17:35
Thanks for the report! This is actually a dupe of https://github.com/rust-lang/cargo/issues/1198 which is also being fixed over at https://github.com/rust-lang/rust/pull/35975, so I'm going to close in favor of those.

**Closed by alexcrichton** 2016-08-25 17:35 UTC
