### ISSUE TITLE
Error in .gitignore

### ISSUE THREAD

**Issue by fprijate** [rust-lang/cargo#5582] opened 2018-05-28 06:00 UTC
first line of .gitignore, created by cargo new,  should be
**target/** 

instead of 

**/target**

**Comment by matklad** [comment] 2018-05-28 07:11
Hm, I think this is the intended behavior: with `/target`, we'll ignore the target dir only at the root of the project. With `target/`, any target dir anywhere will be ignored, so, for example, you won't be able to have `src/target/mod.rs`.

**Comment by dragonmaus** [comment] 2018-07-06 14:45
Technically it should be /target/ , but either works.

**Comment by ehuss** [comment] 2019-08-08 15:21
I'm going to close this as intended behavior.

**Closed by ehuss** 2019-08-08 15:21 UTC
