### ISSUE TITLE
cargo build tries to download packages

### ISSUE THREAD

**Issue by engstad** [rust-lang/cargo#2229] opened 2015-12-18 19:39 UTC
When issuing 
```
cargo build
```
It will install packages from the internet. From my very slow internet connection, that is no good.

**Comment by steveklabnik** [comment] 2015-12-18 19:56
If you have dependencies, this is expected behavior, yes. Otherwise, how would you get them?

If you've already downloaded said dependencies, though, it should not.

**Comment by alexcrichton** [comment] 2015-12-18 20:02
Yeah as @steveklabnik mentioned this is expected behavior because the dependencies need to come from *somewhere*, so I'm going to close this as working as intended.

**Closed by alexcrichton** 2015-12-18 20:02 UTC

**Comment by engstad** [comment] 2015-12-18 22:05
Perhaps I wasn't clear? I asked cargo to *build* not to *download*. If it needs to download, I expect that to be another command.

**Comment by alexcrichton** [comment] 2015-12-18 22:32
Ah yeah there are a number of other issues in the repo about intentionally telling Cargo to not touch the network, such as https://github.com/rust-lang/cargo/issues/2111

**Comment by engstad** [comment] 2015-12-18 22:45
I think the way that `git` does it is quite good. There is an explicit command to download (and sync) anything. I feel that `cargo` does too much with the commands. For instance, I might not care that the up-streams have released new versions - why then should `cargo` check for it?

**Comment by steveklabnik** [comment] 2015-12-18 23:02
>  For instance, I might not care that the up-streams have released new versions - why then should cargo check for it?

It doesn't. I think you may be conflating a few different behaviors here.

If you don't have the requirements to build, `cargo build` will go get them. Yes, in theory, we could make it two commands, but that introduces friction for the majority case at the expense of the minority case.

If you _do_ have the requirements, then it shouldn't check the network. There may be bugs, and they should be fixed.

**Comment by engstad** [comment] 2015-12-18 23:25
Yes, I may have been bitten by previous bugs. I just remember the network being off-line, I had all the files in the registry already, yet still I couldn't build because `cargo` tried to sync to the latest. I'll check it again.
