### ISSUE TITLE
libtest no such file or directory on proc macro with sudo -E runner

### ISSUE THREAD

**Issue by leshow** [rust-lang/cargo#11462] opened 2022-12-06 22:23 UTC
### Problem

I've got a project in workspace whose tests need to be run with `sudo`. If I run:
```
sudo -E cargo test
```
The tests are successful, if I use the `runner` config 
```
[target.x86_64-unknown-linux-gnu]
runner = 'sudo -E'
```
in `.cargo/config.toml`

then all tests pass except for a derive macro crate:
```
/home/leshow/dev/rust/dora/target/debug/deps/register_derive_impl-e8d0ce754e8fcea8: error while loading shared libraries: libtest-b8b77fa76430964e.so: cannot open shared object file: No such file or directory
error: test failed, to rerun pass `-p register_derive_impl --lib`

Caused by:
  process didn't exit successfully: `sudo -E /home/leshow/dev/rust/dora/target/debug/deps/register_derive_impl-e8d0ce754e8fcea8` (exit status: 127)
```

There are no actual tests in that directory, so I'm not quite sure what's going on here.

### Steps

I've got a test project that is a workspace with 2 crates, one of them has:

```
[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1"

[lib]
proc-macro = true
```

if you include `runner = "sudo -E"` then `cargo test` will fail with on the derive crate, even if it is empty.

I can publish the test project if necessary.

### Version

```text
❯ cargo --version verbose
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```

**Comment by ehuss** [comment] 2022-12-06 23:32
Linux does not allow LD_LIBRARY_PATH to be inherited across, even with `-E`. This is required for a proc macro to operate correctly. You'll likely need to make a custom runner that will set `LD_LIBRARY_PATH` to something like ``` `rustc --print=sysroot`/lib``` after running sudo. I think setting rpath in the profile might also work, though I'm not sure I would recommend it.

**Comment by weihanglo** [comment] 2022-12-07 11:35
I am going to close this since it is a limitation from [`sudoers`], and it seems like by design in terms of security and maybe preventing from DLL hijacking. Also, ehuss has already provided useful ideas that should be enough to resolve this IMO.

Thank you for the report anyway!

[`sudoers`]: https://linux.die.net/man/5/sudoers

**Closed by weihanglo** 2022-12-07 11:35 UTC
Labels: C-bug
