### ISSUE TITLE
cargo new doesn’t handle empty directories

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#1065] opened 2014-12-19 14:54 UTC
`cargo new .` or `cargo new existing-directory` doesn’t work even if the directory in question is empty.

This is filled again because #526 and https://github.com/rust-lang/cargo/issues/21#issuecomment-50994208 are already closed.

**Comment by vi** [comment] 2015-09-27 23:44
+1

```
$ mkdir rustquickchecktest
$ cd rustquickchecktest
$ cargo init
No such subcommand

	Did you mean `new`?

$ cargo new
Invalid arguments.

Usage:
    cargo new [options] <path>
    cargo new -h | --help
$ cargo new .
Destination `/home/vi/code/_/rustquickchecktest/.` already exists
$ cd ..
$ rmdir rustquickchecktest
$ cargo new rustquickchecktest
$ cd rustquickchecktest/ 
```

I'd like `cargo init` to be alias to `cargo new`, but also allowing pre-existing empty (or almost-empty, e.g. with `.git`/`.gitignore`) directory.

**Comment by alexcrichton** [comment] 2015-09-28 05:12
Oh this is actually a dupe of https://github.com/rust-lang/cargo/issues/21, so closing for that, certainly a desired feature!

**Closed by alexcrichton** 2015-09-28 05:12 UTC
Labels: C-new

**Comment by vi** [comment] 2015-09-28 12:42
There are many duplicates, but no pull requests, although the problem seems easy.

Are there some problem preventing `cargo init` or `cargo new .` to be done?

**Comment by steveklabnik** [comment] 2015-09-28 14:37
Nobody to write the patch.
