### ISSUE TITLE
[target.'cfg(target_os = "macos")'.dependencies] is used on Windows 10 during compile

### ISSUE THREAD

**Issue by fedor-rusak** [rust-lang/cargo#7402] opened 2019-09-21 10:10 UTC
**Problem**
Can't build project with dependency specified via cfg-expression on Windows 10.

**Steps**
1. cargo new win-10-issue
2. cd win-10-issue
3. add depenencies (from Notes) to Cargo.toml.
4. cargo run
5. Got: Get error: failed to run custom build command for `gfx-backend-metal v0.3.3`

**Notes**
Dependencies:
```
[target.'cfg(target_os = "macos")'.dependencies]
rendy = {git = "https://github.com/amethyst/rendy", rev = "08df51d", features=["metal"]}

[target.'cfg(windows)'.dependencies]
rendy = {git = "https://github.com/amethyst/rendy", rev = "08df51d", features=["vulkan"]}
```
Installation details:
```
cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)
```

When trying to build cargo itself on my machine (which uses these cfg-expressions) everything works as expected.

Also removing macos-specific dependency makes mentioned Error go away.

**Comment by ehuss** [comment] 2019-09-21 14:21
Thanks for the report!  This is essentially a duplicate of #1197, so I'm going to close in favor of that.

**Closed by ehuss** 2019-09-21 14:21 UTC
Labels: C-bug
