### ISSUE TITLE
`unused-crate-dependencies` conflicts in lib and bin crates

### ISSUE THREAD

**Issue by tae-soo-kim** [rust-lang/cargo#12854] opened 2023-10-19 09:30 UTC
### Problem

`Cargo.toml`

```toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "*"
```

`src/lib.rs`

```rust
#![deny(unused_crate_dependencies)]
```

`src/main.rs`

```rust
#![deny(unused_crate_dependencies)]

use hello as _;
use libc;

fn main() {
    let _: libc::size_t = 0;
}
```

In package `hello`, `libc` is needed by bin crate, not lib crate.

### Steps

To reproduce, run `cargo build`. The build fails.

### Possible Solution(s)

Because `libc` is needed by the bin crate, we have to list it as a package dependency. But then the lib crate complains.

One possible solution is to have each crate specify its own dependencies. The package-level dependencies would then be the union of all crate-level dependencies. But crate-level dependencies make more sense because users of a package may not want everything in the package. For example a user merely interested in using the library crate shouldn't be forced to pull dependencies required by binary crates.

**Comment by weihanglo** [comment] 2023-10-19 12:00
Thanks for the report. This seems like a duplicate of #95513 and #57274 and others alike. Close in favor of those.

**Closed** 2023-10-19 12:06 UTC
Labels: C-bug, A-cargo-targets, S-blocked-external

**Comment by tae-soo-kim** [comment] 2023-10-19 16:44
I don't really understand https://github.com/rust-lang/rust/issues/57274, but https://github.com/rust-lang/rust/issues/95513 and below links seem relevant.

- https://github.com/rust-lang/cargo/issues/1982
- https://github.com/rust-lang/rfcs/pull/2887
- https://github.com/dmarcuse/rfcs/blob/master/text/0000-cargo-artifact-specific-dependencies.md
- https://github.com/apple/swift-evolution/blob/main/proposals/0226-package-manager-target-based-dep-resolution.md
