### ISSUE TITLE
Provide better error message if library is being linked to by more than one package

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/cargo#4459] opened 2017-09-01 16:01 UTC
The current error message while building the topmost crate goes something like

> error: native library `freetype` is being linked to by more than one package, and can only be linked to by one package
> 
>   freetype-sys v0.4.0
>   servo-freetype-sys v4.0.3

I have no idea what that means.

Of course, I actually do, at least somewhat. But I have no idea what I'm supposed to do with this message. Did I make a mistake? Where in the dependency tree do those crates actually come from, I have never heard of them. Do I need to bump some version numbers? May downgrading help? Or is the native library `freetype` on an incompatible version? Which packages is Cargo talking about? Those in the list below? If not, what are those crates? How come they link to `freetype` ?  Is it a dependency? Maybe I should `git clone` them and check their `Cargo.toml`. Why is there no punctuation mark at the end of that sentence

**Comment by alexcrichton** [comment] 2017-09-01 16:32
Thanks for the report! I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/1006, so closing in favor of that

**Closed by alexcrichton** 2017-09-01 16:32 UTC
