### ISSUE TITLE
building workspaces can't use --features flag

### ISSUE THREAD

**Issue by SamPeng87** [rust-lang/cargo#5015] opened 2018-02-06 03:21 UTC
i define feature in some sub-create
```
    [features]
    default=["product","dangerous_configuration"]
    dangerous_configuration=[]
    develop=[]
    product=[]
```
then,execute cargo `cargo build --features="develop"`

it can't work,only work in sub-create `default` features selectors.

`cargo build --no-default-features --all` not work too

Is it a Bug?

**Comment by alexcrichton** [comment] 2018-02-06 17:09
Yes right now `[features]` is only allowed on individual crates rather than workspace configurations.

**Comment by SamPeng87** [comment] 2018-02-06 17:40
Thank your report.Wish this feature can quick complete. I use two [[bin]] point some other needed feature.it is too low.but thank god this can good work.

**Comment by SamPeng87** [comment] 2018-02-06 17:45
En..Can I push feature arguments with 'cargo build' pass to sub-creat?like my example. I think that looks very natural

**Comment by alexcrichton** [comment] 2018-02-06 20:04
You should be able to do `--features foo/bar` I think?

**Comment by sanmai-NL** [comment] 2018-02-24 14:43
@SamPeng87: could you please test alexcrichton’s suggestion, so that the issue can perhaps be closed?

**Comment by Nemo157** [comment] 2018-03-05 09:38
Attempting to reference a feature in a sub-crate of a workspace does not work:

```
.../futures-rs > cargo build --features futures-core/std -p futures-core -v
error: Package `futures-core v0.2.0 (file:///.../futures-rs/futures-core)` does not have these features: `futures-core`

.../futures-rs > cd futures-core

.../futures-rs/futures-core > cargo build --features futures-core/std -p futures-core -v
error: Package `futures-core v0.2.0 (file:///.../futures-rs/futures-core)` does not have these features: `futures-core`

.../futures-rs/futures-core > cargo build --features std -p futures-core -v
   Compiling futures-core v0.2.0 (file:///.../futures-rs/futures-core)
     Running `rustc --crate-name futures_core futures-core/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="atomic"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=314425e352544566 -C extra-filename=-314425e352544566 --out-dir .../futures-rs/target/debug/deps -C incremental=.../futures-rs/target/debug/incremental -L dependency=.../futures-rs/target/debug/deps`
    Finished dev [unoptimized + debuginfo] target(s) in 0.85 secs
```

Also, `--no-default-features` does not work in a workspace

```
.../futures-rs > cargo build --no-default-features -p futures-core -v
   Compiling futures-core v0.2.0 (file:///.../futures-rs/futures-core)
     Running `rustc --crate-name futures_core futures-core/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="atomic"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=314425e352544566 -C extra-filename=-314425e352544566 --out-dir .../futures-rs/target/debug/deps -C incremental=.../futures-rs/target/debug/incremental -L dependency=.../futures-rs/target/debug/deps`
    Finished dev [unoptimized + debuginfo] target(s) in 0.41 secs
```

I'm not sure whether there's a good behaviour for these to all have, but if they're not going to apply when building from a virtual manifest then maybe they should warn/error to inform the user?

**Comment by Nemo157** [comment] 2018-04-16 12:58
See also #5364, that appears to cover most of the relevant behaviour and should hopefully close this.

**Comment by jhpratt** [comment] 2019-04-16 02:26
@alexcrichton Passing a feature flag works for crates in a workspace, but how can one _disable_ a default feature flag?

**Comment by alexcrichton** [comment] 2019-04-16 14:49
There is no way to selectively disable on default feature, rather you need to turn them all off with `--no-default-features` (or `default-features = false`) and then re-enable the other default features you still need manually

**Comment by jhpratt** [comment] 2019-04-16 18:52
It _is_ possible to use the `--no-default-featurees` flag when building a workspace though? When I tried yesterday it didn't seem to work.

**Comment by alexcrichton** [comment] 2019-04-17 14:21
Ah no, not currently, it has to be directed at a package not a workspace

**Comment by Manishearth** [comment] 2019-07-26 17:44
> You should be able to do `--features foo/bar` I think?

@alexcrichton this isn't working for me in https://github.com/servo/webxr/ (try `--features webxr/ipc`, it compiles but doesn't pull in ipc_channel)

This bug is particularly annoying because this forces me to build from a subfolder, but cargo sets the error message root as the workspace root, so i can't click on the errors to have them open in my editor

**Comment by Manishearth** [comment] 2019-07-26 17:54
Ah, you can use `--manifest-path` to make it work (but you don't need to `foo/bar` it then)

**Comment by jonhoo** [comment] 2019-07-28 16:06
I think having `--features foo/bar` work would still be better though. It would allow you to do things like "run all tests across all subcrates, and keep this feature enabled" without having to explicitly enumerate every crate (handy for things like general-purpose CI scripts).

**Comment by nox** [comment] 2019-08-17 11:13
Is there any ongoing work for `--features foo/bar`? Or guidelines as to where to look at in the code to implement such a thing?

**Comment by m4b** [comment] 2019-09-15 20:34
What happened here? This seems like a pretty big usability paper cut; I just refactored into a workspace, and now it's very unpleasant to build...

**Comment by paddyhoran** [comment] 2019-09-18 01:51
Ran into this also, the fact that `--no-default-features` is not applied silently at the workspace level is misleading as CI builds all pass.

**Comment by Josh-Thompson** [comment] 2019-10-04 23:49
Would also love this ability.

**Comment by nixpulvis** [comment] 2020-03-12 03:36
I'm sure there's a few reasons why this doesn't work, but a naive attempt to use `--no-default-features` in a workspace lead me here.

I feel like I'd expect a workspace to have effectively the union of the features of it's members. Members could even have the same features and they would be controlled as one. For example, in a workspace with:

```toml
[workspace]
members = [
    "foo",
    "bar",
]
```

I may have the following two manifests:

```toml
# foo/Cargo.toml
[features]
default = ["a", "c"]
a = []
b = []
c = []
d = []
```

```toml
# bar/Cargo.toml
[features]
default = ["a", "e"]
a = []
b = []
e = []
f = []
```

Here I think I'd expect the following:

- `cargo ... --no-default-features` would disable all of `foo/a`, `foo/c`, `bar/a` and `bar/e`
- `cargo ... --features=b` would enable both `foo/b` and `bar/b`

What am I missing? This seems somewhat straightforward. Could I take a stab at implementing this in cargo?

**Comment by gilescope** [comment] 2020-03-23 18:24
Isn't this a dupe of https://github.com/rust-lang/cargo/issues/4753 - can we close this one and continue the discussion there?

**Comment by nixpulvis** [comment] 2020-03-23 20:26
@gilescope I tried collecting all the related (possibly duplicate) issues in https://internals.rust-lang.org/t/features-and-workspaces-request-for-meta-issue/11964 hoping to aggregate them. No responses as of yet however.

**Closed** 2020-04-09 16:00 UTC
Labels: A-errors, A-features, A-workspaces, C-feature-request
