### ISSUE TITLE
dev-dependencies are built even when unused

### ISSUE THREAD

**Issue by kpcyrd** [rust-lang/cargo#5385] opened 2018-04-18 07:17 UTC
I ran into a weird combination of problems:
- I have a library crate that uses the example/ folder for tooling related to that library
- the library does not depend on openssl
- one of my examples (lets call it bar) has a dependency to openssl (in dev-dependencies)
- a different example (lets call it foo) needs to build with `cargo build --example foo --release --target x86_64-unknown-linux-musl` (without workarounds)
- cross compiling is non-trivial with openssl-sys (https://github.com/sfackler/rust-openssl/issues/603)

Since `foo` has no direct or indirect dependency to openssl-sys, `cargo build --example foo --release --target x86_64-unknown-linux-musl` should work just fine. This is currently not the case since cargo builds all dev-dependencies as well when doing a build, even if those are unused.

I currently have a weird workaround in place where I moved the openssl related dev-dependency to the normal dependencies so I can control it with feature flags. This means I have to start `bar` with that feature flag. This makes CI more complicated. Also, since the crate is a library, moving a dev dependency to the normal dependencies is problematic.

I think cargo could determine that openssl-sys is not needed for the build I've started and therefore skip it. What do you think?

**Comment by matklad** [comment] 2018-04-18 09:48
Cargo at this moment can not determine if a dependency is used by one example, but not the other. We'll need target-specific dependencies for this I think. That is, we need an ability to say, in Cargo.toml, that bar depends on openssl, but foo does not.

**Comment by kpcyrd** [comment] 2018-04-18 15:52
This might cross the rustc-cargo boundary, but in theory it should be possible to tell if an example depends on a crate based on its `extern crate` imports?

**Comment by ehuss** [comment] 2020-03-18 17:00
`extern crate` is usually no longer used in the 2018 edition, and `rustc` would require dependencies to be built to run expansion anyways.

Considering the solution here is cargo target-specific dependencies, I'm going to close this as a duplicate of #1982.

**Closed by ehuss** 2020-03-18 17:00 UTC
Labels: A-features, C-feature-request
