### ISSUE TITLE
cargo audit --version reports wrong version

### ISSUE THREAD

**Issue by al-cheb** [rust-lang/cargo#10699] opened 2022-05-25 07:23 UTC
### Problem

If you run `cargo audit --version` you get a wrong version of cargo-audit:
![image](https://user-images.githubusercontent.com/47745270/170204153-84ac436b-e932-4635-9152-00f97f419cc8.png)

### Steps

cargo audit --version

### Possible Solution(s)

cargo-audit --version

### Version

```text
$ cargo version --verbose
cargo 1.61.0 (a028ae4 2022-04-29)
release: 1.61.0
commit-hash: a028ae42fc1376571de836be702e840ca8e060c2
commit-date: 2022-04-29
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by weihanglo** [comment] 2022-05-25 08:07
Thanks for your report!

If I interpret it correctly, this is by design. 
Running `cargo ${command} --version` will invoke the custom subcommand as `cargo-${command} ${command} --version`. Here is [a more detailed explanation](https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands) if you're interested in. 

Applying this patch to cargo-audit might help. The actual fix is up to rustsec maintainers.

```patch
diff --git a/cargo-audit/src/commands/audit.rs b/cargo-audit/src/commands/audit.rs
index 74c933e..77309bb 100644
--- a/cargo-audit/src/commands/audit.rs
+++ b/cargo-audit/src/commands/audit.rs
@@ -20,6 +20,7 @@ use clap::Subcommand;
 
 /// The `cargo audit` subcommand
 #[derive(Command, Default, Debug, Parser)]
+#[clap(version)]
 pub struct AuditCommand {
     /// Optional subcommand (used for `cargo audit fix`)
     #[cfg(feature = "fix")]
@@ -30,10 +31,6 @@ pub struct AuditCommand {
     #[clap(short = 'h', long = "help", help = "output help information and exit")]
     help: bool,
 
-    /// Get version information
-    #[clap(long = "version", help = "output version and exit")]
-    version: bool,
-
     /// Colored output configuration
     #[clap(
         short = 'c',
```

Closing as it is a documented convention between Cargo and subcommands.

**Closed by weihanglo** 2022-05-25 08:07 UTC
Labels: C-bug
