### ISSUE TITLE
cargo panics when stdin to it is closed

### ISSUE THREAD

**Issue by soenkehahn** [rust-lang/cargo#6723] opened 2019-03-07 05:09 UTC
**Problem**

When `exec`ing e.g. `cargo build` with a closed `stdin` file descriptor, it panics with:
```
thread '<unnamed>' panicked at 'failed to acquire jobserver token: early EOF on jobserver pipe', src/librustc_codegen_ssa/back/write.rs:1348:29
```

Expected behavior: `cargo` should treat this the same as if `stdin` was a valid file descriptor that nothing gets written to.

**Steps**

This can be reproduced e.g. by a rust program that:
1. calls `libc::close(libc::STDIN_FILENO)`,
2. calls `nix::unistd::execvp` to run `cargo build` on a project.

Here's an example repo including a `reproduce.sh` script to show the bug: https://github.com/soenkehahn/entr-cargo-bug

**Possible Solution(s)**

I think `cargo` could check with `fcntl(libc::STDIN_FILENO, libc::F_GETFD)` whether `stdin` is still open.

**Notes**

This is motivated by trying to use `cargo` in conjunction with [`entr`](http://eradman.com/entrproject/). Since [this commit](https://bitbucket.org/eradman/entr/commits/ec5e793ae710c480b30dda99a07be5f8aaf4f2ea) it closes the `stdin` of the called command when using the `-r` (restart) option.

Output of `cargo version`:

`cargo 1.33.0 (f099fe94b 2019-02-12)`

On linux.

**Comment by joshtriplett** [comment] 2019-10-27 20:00
Interesting! I suspect I might know what happened here, and if I'm correct, it isn't exactly cargo's or rustc's fault.

With stdin closed, the next file opened will become file descriptor 0.

So, when rustc or cargo creates a jobserver pipe, one end of it ends up as file descriptor 0.

Then, something else in the build process ends up either closing or reading from stdin, which confuses the jobserver.

It is not, in general, safe to run an arbitrary program with stdin closed. It's much safer to make stdin come from `/dev/null`.

**Comment by kevincox** [comment] 2020-04-03 01:03
This seems related to https://github.com/rust-lang/rust/issues/46981

**Comment by sanmai-NL** [comment] 2023-08-30 11:10
@ehuss is this solved since https://github.com/rust-lang/rust/issues/46981?

**Comment by ehuss** [comment] 2023-08-30 21:48
I'm not sure. The particular reproduction given above started working in Rust 1.42. I'm not sure which change in that release altered the behavior (it was probably https://github.com/rust-lang/rust/pull/68012). I'm going to close since this seems effectively resolved.

**Closed by ehuss** 2023-08-30 21:48 UTC
Labels: C-bug, A-console-output, A-jobserver
