### ISSUE TITLE
--manifest-path forces recompile when using vendoring

### ISSUE THREAD

**Issue by sebastianblunt** [rust-lang/cargo#6999] opened 2019-05-31 23:27 UTC
**Problem**

If vendoring dependencies instead of pulling from crates.io, then using `--manifest-path` will cause cargo to recompile whenever switching from inside the repo to outside.

**Steps**

1. I created a minimal repository to reproduce this: https://github.com/sebastianblunt/cargo-6999
2. `cd` into the repo and run `cargo build`
3. `cd ..`
4. `cargo build --manifest-path example/Cargo.toml`
5. Notice that it will recompile both the dependency and example.

If you go into the example repo and remove/rename the .cargo directory, thereby removing the vendoring, then cargo will not recompile when you do the above.

It does not seem to make any difference whether you use absolute or relative paths in the `.cargo/config`.

**Possible Solution(s)**

**Notes**

Output of `cargo version`: `cargo 1.37.0-nightly (545f35425 2019-05-23)`

**Comment by ehuss** [comment] 2019-06-04 00:34
Thanks for making the repro!  Cargo doesn't read the `.cargo/config` file when using `--manifest-path` (it uses the current working directory).  I believe this is a dupe of #2930.

**Comment by ehuss** [comment] 2019-06-24 16:37
Closing in favor of #2930.

**Closed by ehuss** 2019-06-24 16:37 UTC
Labels: C-bug
