### ISSUE TITLE
Cargo should throw an error when run recursively instead of deadlocking

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#8967] opened 2020-12-11 00:01 UTC
Build scripts are free to run whatever they want, and one of the things they may run is cargo. I seem to remember I've heard of crates doing that. This is necessary in scenarios where cargo doesn't support what one would want (like building against a cdylib or staticlib crate).

The problem is that there are cases where cargo prevents itself from running, pausing its own execution, until a lock is released. This can lead to dead-lock situations when the cargo waiting is run as a subprocess of the cargo that holds the lock, such as the following setup:

```
cargo new --lib foo
cat > foo/build.rs <<EOF
fn main() {
    std::process::Command::new("cargo").arg("build").spawn().unwrap();
    panic!("foo");
}
EOF
mkdir bar
cd bar
cat > Cargo.toml <<EOF
[workspace]

members = [ "bar" ]
EOF
cargo new --lib bar
echo 'foo = { path = "../../foo" }' >> bar/Cargo.toml
cargo build
```

Here what we have is:
- a foo external crate, simulating a crate we'd pull from crates.io as a dependency, that executes cargo build in its build script
- a workspace with a bar crate that depends on foo.

Building in the workspace dead-locks.

It would be better if cargo could detect this situation and abort with a clear message rather than dead-lock.

I'd argue cargo shouldn't allow to `cargo build` from build scripts in the first place, but that would be a breaking change, and there are a bunch of scenarios it currently doesn't support that would be killed by such a restriction.

**Comment by ehuss** [comment] 2021-01-07 03:01
Thanks for the report!  I think this is essentially a duplicate of #8938, so closing in favor of that.

**Closed by ehuss** 2021-01-07 03:01 UTC
Labels: C-feature-request
