### ISSUE TITLE
Cargo should help devs have their tags in order.

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#2291] opened 2016-01-17 19:40 UTC
This is inspired by: https://www.reddit.com/r/rust/comments/419pm5/psa_please_please_please_tag_your_git/cz0qz4y

Cargo already does a lot of git related things, why couldn't it automatically create annotated tags on `cargo publish`? Optionally it could make a `git push --tag`. Or it could go all the way generic and have a hooks for `cargo publish` so anyone can customize their `cargo publish` policy.

**Comment by jonas-schievink** [comment] 2016-01-17 21:30
Duplicate of #841

**Comment by alexcrichton** [comment] 2016-01-18 18:25
I agree this is a dupe, but thanks for the report!

**Closed by alexcrichton** 2016-01-18 18:25 UTC
