### ISSUE TITLE
Cargo does not track the lock information for dependency overrides

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#1413] opened 2015-03-13 09:12 UTC
If a local override to dependency `foo` adds an additional dependency to `foo`, it does not get written to `Cargo.lock`.
This might be by design, although I do not know the rationale behind it.

The problem is, because of the lock information not being tracked, Cargo updates the remotes (registry, git repo, ...) every time one does `cargo build` or `cargo run`. These updates are "lazy", but there is still a noticeable delay, especially when one just wants to run their project with `cargo run`.

Is this necessary, or could the lock information for local dependency overrides be stored somewhere?

**Comment by alexcrichton** [comment] 2015-03-13 16:42
Hm, this is an unfortunate side effect, perhaps best classified as "unintentionally working as intended". We do not serialize lockfile information of overrides into `Cargo.lock` because it is not state which is persisted once you commit the changes upstream (no others have the same set of overrides). In general overrides are meant to make small local modifications to a dependency, but if more substantial changes are being made I'd recommend using a temporary `path` dependency itself in the manifest.

**Comment by crumblingstatue** [comment] 2015-03-13 16:51
Strangely, sometimes cargo does write the dep info of the override to Cargo.lock, but I can't figure out what makes it do that.
For example, https://github.com/crumblingstatue/crusty-chip-sfml writes it, but https://github.com/crumblingstatue/sokoban-rs/tree/master/sfml doesn't.

**Comment by alexcrichton** [comment] 2015-11-11 20:02
I'm gonna close this in favor of https://github.com/rust-lang/cargo/issues/2041 which I think may be a bit more searchable, but otherwise they're actually the same issue.

**Closed by alexcrichton** 2015-11-11 20:02 UTC
