### ISSUE TITLE
cargo-install unnecessarily rebuilds everything

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/cargo#5667] opened 2018-06-29 14:50 UTC
Starting with rust 1.27, if I run `cargo build --release` then `cargo install`, the latter syncs its crates.io local copy and rebuilds everything.
This didn't happen with rust 1.26.

Might be related to the latest failure in https://github.com/rust-lang/rust/pull/51717#issuecomment-401370538 ?

**Comment by ehuss** [comment] 2018-06-29 16:28
I think this change was intentional, see #5327.  You should have gotten a warning:

```
warning: To build the current package use `cargo build`, 
to install the current package run `cargo install --path .`
```

**Comment by Keruspe** [comment] 2018-07-02 11:12
@ehuss I fail to see how that could be related.

I'm a distribution packager and our install phase doesn't have access to the network so resyncing crates.io breaks stuff, and rebuilding everything that was built just before during the compile phase doesn't seem necessary...

**Comment by Keruspe** [comment] 2018-07-02 11:17
Actually, this is probably a duplicate of #5662

**Comment by ehuss** [comment] 2018-07-02 14:51
Ah, sorry, I misunderstood.  Indeed using `cargo install` in a workspace does not seem to be working as intended.

**Comment by alexcrichton** [comment] 2018-07-02 18:19
Indeed I believe this is a duplicate! Closing in favor of https://github.com/rust-lang/cargo/issues/5662

**Closed by alexcrichton** 2018-07-02 18:19 UTC
