### ISSUE TITLE
cargo is incompatible with the `insteadOf` URL rewriting of `git-config(1)`

### ISSUE THREAD

**Issue by Gottox** [rust-lang/cargo#10203] opened 2021-12-16 09:45 UTC
### Problem

I'm using git's URL rewrite feature to force git pulls/pushes to be established via ssh instead of http(s). This allows me to define git submodules to be defined as http and still benefit from from all the ssh features. Unfortunately, this breaks cargo as described below:

### Steps

1. Set git config:
```bash
$ git config --global 'url.git+ssh://git@ssh.github.com:443/.insteadOf' https://github.com/
```
2. create a new project:
```bash
$ cargo init /tmp/test-project && cd /tmp/test-project
```
3. add a dependency to `Cargo.toml`. For example serde:
```bash
$ echo 'serde = "*"' >> Cargo.toml
```
4. Run `cargo update`
```bash
$ cargo update
    Updating crates.io index
warning: spurious network error (2 tries remaining): unknown scheme for URL 'git+ssh://git@github.com/rust-lang/crates.io-index'; class=Net (12); code=InvalidSpec (-12)
warning: spurious network error (1 tries remaining): unknown scheme for URL 'git+ssh://git@github.com/rust-lang/crates.io-index'; class=Net (12); code=InvalidSpec (-12)
error: failed to get `serde` as a dependency of package `test-project v0.1.0 (/tmp/test-project)`

Caused by:
  failed to load source for dependency `serde`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unknown scheme for URL 'git+ssh://git@github.com/rust-lang/crates.io-index'; class=Net (12); code=InvalidSpec (-12)

``` 

### Notes

As a workaround to this issue on can set `CARGO_NET_GIT_FETCH_WITH_CLI=true`.

### Version

```text
$ cargo version --verbose 
cargo 1.58.0-nightly (294967c53 2021-11-29)
release: 1.58.0
commit-hash: 294967c53f0c70d598fc54ca189313c86c576ea7
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Linux Rolling Release (void) [64-bit]
```

**Comment by alexcrichton** [comment] 2021-12-16 15:09
I believe that this is a duplicate of https://github.com/rust-lang/cargo/issues/2078, so I'm going to close in favor of that.

**Closed by alexcrichton** 2021-12-16 15:09 UTC
Labels: C-bug
