### ISSUE TITLE
Error: failed to get core-foundation as a dependency of package myapp

### ISSUE THREAD

**Issue by silvioprog** [rust-lang/cargo#11515] opened 2022-12-28 21:06 UTC
### Problem

Hi.

I'm trying to use the `core-foundation` in a small project, but it is failing at the build stage:

```bash
    Updating crates.io index
error: failed to get `core-foundation` as a dependency of package `myapp v0.1.0 (~/myapp)`

Caused by:
  failed to load source for dependency `core-foundation`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository: git@github.com:rust-lang/crates.io-index

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  no authentication available
```

### Steps

1. `cargo new myapp`
2. `cd myapp/`
3. `echo 'core-foundation = "0.9.3"' >> Cargo.toml`
4. `cargo check`

### Notes

[jdm](https://github.com/jdm) from [servo/core-foundation-rs](https://github.com/servo/core-foundation-rs) commented:

> That's an issue with Cargo, not with this package.

Issue: https://github.com/servo/core-foundation-rs/issues/534

### Version

`cargo 1.66.0 (d65d197ad 2022-11-15)`

**Comment by silvioprog** [comment] 2022-12-28 21:41
Fixed by:

```
eval `ssh-agent -s`
ssh-add
cargo check
```

Reference: https://github.com/rust-lang/cargo/issues/3381#issuecomment-308460530

**Comment by weihanglo** [comment] 2022-12-29 00:34
Thanks for the report. I believe this is kinda a duplicate of #2078. Close in favor of that.

**Closed by weihanglo** 2022-12-29 00:34 UTC
Labels: C-bug
