### ISSUE TITLE
cargo test shows the error by twice

### ISSUE THREAD

**Issue by kless** [rust-lang/cargo#2785] opened 2016-06-15 17:51 UTC
That builds your crate once normally for the integration tests, and once as the unit test library. So two compiles with the same code base: two errors.

It would better if were showed only one error; so, one option could be if there are any error at integration tests, then do not compile unit test library.

**Comment by alexcrichton** [comment] 2016-06-16 09:07
Thanks for the report! What's actually happening here is that the library is being compiled twice (once with `--test` and once for doc tests later on), and this is a dupe of https://github.com/rust-lang/cargo/issues/1534 and https://github.com/rust-lang/cargo/issues/851 (now tracked at https://github.com/rust-lang/cargo/issues/1198). This is intended behavior though, and you can use various flags like `--test`, `--lib`, or `-j` to not run `rustc` in parallel, so I'm going to close this.

**Closed by alexcrichton** 2016-06-16 09:07 UTC
