### ISSUE TITLE
Feature selection when testing specific packages has no effect

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/cargo#5909] opened 2018-08-18 23:17 UTC
I have a workspace with two crates: `foo`, and `bar`. The crate `foo` has 3 features, `a`, `b`, and `c`. I wrote a shell script that tests that each feature works when individually enabled. The script is run from the crate root. It is:

```sh
FEATURES=(a b c)
for feature in "${FEATURES[@]}"; do
  cargo test -v -p foo --no-default-features --features "${feature}"
done
```

Instead of compiling the crate with each feature individually enabled and running those tests, cargo seems to always compile the crate with the default set of features. Here's what the verbose output emits when feature `c` is being tested, where `a` and `b` are default features:

```
> cargo test -v -p foo --no-default-features --features c
rustc --crate-name foo lib.rs --emit=dep-info,link -C debuginfo=2 --test --cfg 'feature="default"' --cfg 'feature="a"' --cfg 'feature="b"''
```

Note that `feature="c"` isn't enabled at all, and the default features _are_ enabled. Everything works fine if I run `cargo test --no-default-features --features "${feature}"` from the root of the `foo` crate.

**Comment by alexcrichton** [comment] 2018-08-20 17:16
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/5849, but thanks for the report!

**Closed by alexcrichton** 2018-08-20 17:16 UTC
