### ISSUE TITLE
Can't build newly initialized project caused by "no such file or directory"

### ISSUE THREAD

**Issue by singachea** [rust-lang/cargo#987] opened 2014-11-27 15:56 UTC
Hi

I just installed cargo and tried to get my first hello world project to run, but I get the following error:

``` bash
~/lab/rust  ᐅ cargo new myapp --bin && cd myapp
~/lab/rust/myapp (master ✘)✭ ᐅ cargo build --verbose
   Compiling myapp v0.0.1 (file:///Users/ream/lab/rust/myapp)
     Running `rustc /Users/ream/lab/rust/myapp/src/main.rs --crate-name myapp --crate-type bin -g --out-dir /Users/ream/lab/rust/myapp/target --dep-info /Users/ream/lab/rust/myapp/target/.fingerprint/myapp-8a3779e77173e633/dep-bin-myapp -L /Users/ream/lab/rust/myapp/target -L /Users/ream/lab/rust/myapp/target/deps`
Could not compile `myapp`.

Caused by:
  Could not execute process `rustc /Users/ream/lab/rust/myapp/src/main.rs --crate-name myapp --crate-type bin -g --out-dir /Users/ream/lab/rust/myapp/target --dep-info /Users/ream/lab/rust/myapp/target/.fingerprint/myapp-8a3779e77173e633/dep-bin-myapp -L /Users/ream/lab/rust/myapp/target -L /Users/ream/lab/rust/myapp/target/deps` (status=never executed)

Caused by:
  no such file or directory
~/lab/rust/myapp (master ✘)✭ ᐅ rustc /Users/ream/lab/rust/myapp/src/main.rs --crate-name myapp --crate-type bin -g --out-dir /Users/ream/lab/rust/myapp/target --dep-info /Users/ream/lab/rust/myapp/target/.fingerprint/myapp-8a3779e77173e633/dep-bin-myapp -L /Users/ream/lab/rust/myapp/target -L /Users/ream/lab/rust/myapp/target/deps
~/lab/rust/myapp (master ✘)✭ ᐅ ./target/myapp
Hello, world!
```

As you can see, I can't build a simple hello world, but if I just run the command directly it can compile normally. Any idea why?

**Comment by lovedboy** [comment] 2015-01-10 09:11
I got the same problem  when run  `cargo run` command.

**Comment by alexcrichton** [comment] 2015-01-11 07:18
@singachea, @lovedboy sorry but I'm having real trouble trying to reproduce this.

Could you also give me the value of your `PATH` environment variable?

@lovedboy, could you try running the `sudo dtruss -f cargo build` and paste the output here?

**Comment by singachea** [comment] 2015-01-12 17:19
I just reinstalled new alpha but still got same problem

```bash
~/lab/rust/myapp (master ✘)✹ ᐅ ls
Cargo.lock Cargo.toml src        target
~/lab/rust/myapp (master ✘)✹ ᐅ cargo build --verbose
   Compiling myapp v0.0.1 (file:///Users/ream/lab/rust/myapp)
     Running `rustc /Users/ream/lab/rust/myapp/src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/ream/lab/rust/myapp/target --emit=dep-info,link -L dependency=/Users/ream/lab/rust/myapp/target -L dependency=/Users/ream/lab/rust/myapp/target/deps`
Could not compile `myapp`.

Caused by:
  Could not execute process `rustc /Users/ream/lab/rust/myapp/src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/ream/lab/rust/myapp/target --emit=dep-info,link -L dependency=/Users/ream/lab/rust/myapp/target -L dependency=/Users/ream/lab/rust/myapp/target/deps` (status=never executed)

Caused by:
  no such file or directory
~/lab/rust/myapp (master ✘)✹ ᐅ echo $PATH
/usr/local/heroku/bin:/Users/ream/.rvm/gems/ruby-2.1.2/bin:/Users/ream/.rvm/gems/ruby-2.1.2@global/bin:/Users/ream/.rvm/rubies/ruby-2.1.2/bin:/Users/ream/bin:/Users/ream/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin/:/Users/ream/bin:/usr/local/Cellar/go/1.3.3/bin:/usr/local/Cellar/go/1.3.3/libexec/bin
~/lab/rust/myapp (master ✘)✹ ᐅ sudo dtruss -f cargo build
Password:
dtrace: failed to execute cargo: file is set-id or unreadable [Note: the '-c' option requires a full pathname to the file]

~/lab/rust/myapp (master ✘)✹ ᐅ which rustc
/usr/local/bin/rustc
~/lab/rust/myapp (master ✘)✹ ᐅ rustc -V
rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)
~/lab/rust/myapp (master ✘)✹ ᐅ which cargo
/usr/local/bin/cargo
~/lab/rust/myapp (master ✘)✹ ᐅ cargo -V
cargo 0.0.1-pre-nightly (8c01b6b 2015-01-08 20:52:43 +0000)
```

Again, if I copy that command rust `rustc /Users/ream/... `  and paste, it worked fine.

**Comment by ismaelga** [comment] 2015-01-14 01:40
@alexcrichton I got the same error. Here is a dtruss like you asked https://gist.github.com/ismaelga/7ce902babe356b7cae3f

**Comment by alexcrichton** [comment] 2015-01-14 01:50
@ismaelga is your compiler installed in `/usr/local/bin`?

**Comment by ismaelga** [comment] 2015-01-14 10:53
I think so. I've used the rustup.sh script to install it

**Comment by ismaelga** [comment] 2015-01-14 14:24
Isn't this related to https://github.com/rust-lang/cargo/issues/1112 ?

Interesting. Today in a different machine I installed rust the same way (I had it installed with homebrew but did unlink and uninstall before installing with rustup.sh) and I could run `cargo build` successfully. Will later check on the other machine if I can see any difference between the two.

**Comment by alexcrichton** [comment] 2015-01-14 16:21
Oh interesting, so is homebrew mixed in here for you? Did you have a homebrew installation before you used rustup?

I'm quite puzzled because the [calls to execve](https://gist.github.com/ismaelga/7ce902babe356b7cae3f#file-gistfile1-txt-L3415-L3418) don't even try /usr/local/bin/rustc, it almost looks like they're the sudo PATH...

**Comment by ismaelga** [comment] 2015-01-14 18:59
I had rust installed on both machines with homebrew before using `rustup.sh`. I cleaned it up before running `rustup.sh` with `brew unlink` and `brew uninstall rust` so I don't see how could it mess with `cargo build`.

One difference though, is that I had installed (with homebrew) on the broken one, version 1.0.0-alpha and on the working one, version 0.12.0

But by looking at the commits for the homebew formula https://github.com/Homebrew/homebrew/commits/master/Library/Formula/rust.rb I can't see any significant changes from 0.12.0 to 1.0.0-alpha.

**Comment by alexcrichton** [comment] 2015-01-14 23:34
Unfortunately I can't reproduce via any methods of trying :(

**Comment by greggawatt** [comment] 2015-02-23 17:50
Hey @singachea are you using zsh?

**Comment by singachea** [comment] 2015-02-23 18:37
@greggawatt : yep, i'm using zsh

**Comment by greggawatt** [comment] 2015-02-23 18:38
So i'm getting this error with #1337 and i'm going to start blaming zsh, does it work for you in normal terminal?

**Comment by singachea** [comment] 2015-02-23 18:43
omg... it works in bash with normal terminal... 

confirm: it doesn't work for my comp with zsh + iterm2

weird.... I have another comp with zsh + iterm2, but it works flawlessly.

**Comment by greggawatt** [comment] 2015-02-23 18:44
@alexcrichton Mind seeing if you can recreate in Zsh?

**Comment by singachea** [comment] 2015-02-23 18:56
Ok... this is my case now:

Terminal + bash/zsh -> work
ITerm2 + zsh -> doesn't work on start of the session, but if I do this:

```bash
~/lab/rust/myapp (master ✘)✹ ᐅ bash
bash-3.2$ zsh
~/lab/rust/myapp (master ✘)✹ ᐅ cargo run --verbose
   Compiling myapp v0.0.1 (file:///Users/ream/lab/rust/myapp)
     Running `rustc src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/ream/lab/rust/myapp/target --emit=dep-info,link -L dependency=/Users/ream/lab/rust/myapp/target -L dependency=/Users/ream/lab/rust/myapp/target/deps`
     Running `target/hello_world`
Hello guys
```
I guess there is something wrong with iTerm2 + zsh on new session.

**Comment by alexcrichton** [comment] 2015-02-24 00:34
Interesting! I personally use zsh as well, but I'm still unable to reproduce this. I also switched to iTerm2 and could not reproduce this (I normally use the normal Terminal.app)

**Comment by unknowndevice** [comment] 2015-02-25 21:14
I started getting this error today. I've been installing from nightly 
```bash
curl -s https://static.rust-lang.org/rustup.sh | sudo sh'
```
Here's the output from ```bash sudo dtruss -f cargo build ``` https://gist.github.com/unknowndevice/9009c25a6a482c345792#file-sudo-dtruss-f-cargo-build

I use fish in iTerm2, but I still get the error if I use bash in Terminal or iTerm2.

**Comment by unknowndevice** [comment] 2015-02-27 15:53
Updated today and this has stopped happening :/

**Comment by greggawatt** [comment] 2015-03-01 06:21
Still not working for me, here is my path:

    export PATH="/Users/gregg/.rvm/gems/ruby-1.9.3-p547@webpass/bin:/Users/gregg/.rvm/gems/ruby-1.9.3-p547@global/bin:/Users/gregg/.rvm/rubies/ruby-1.9.3-p547/bin:/Users/gregg/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin"

**Comment by lovedboy** [comment] 2015-03-05 13:27
@singachea @alexcrichton 
So am i.  `cargo build` CMD works fine with normal terminal, not works with iTerm2.

**Comment by alexcrichton** [comment] 2015-03-06 01:02
This does kinda sound like it's an iTerm2-specific problem, so I should ask: has anyone seen this problem and **not** been using iTerm2?

Also, for those seeing this problem, did you all install rust via rustup? Homebrew? Curious if there's a trend there as well.

**Comment by greggawatt** [comment] 2015-03-06 01:06
i used 
````
curl -L https://static.rust-lang.org/rustup.sh | sudo sh
````

**Comment by pariz** [comment] 2015-03-24 07:52
@alexcrichton i have the same problem using iTerm2. Switched to terminal and everything works fine.

**Comment by alexcrichton** [comment] 2015-03-24 17:23
Very interesting! Now it should just be figuring out what the difference between iTerm2 and Terminal are...

**Comment by bruno-medeiros** [comment] 2015-05-20 14:23
> This does kinda sound like it's an iTerm2-specific problem, so I should ask: has anyone seen this problem and not been using iTerm2

As referenced above ( https://github.com/RustDT/RustDT/issues/31) , it seems the RustDT users have been encountering the same problem. The running theory is that in some OS X version (possibly Mac OSX 10.10 Yosemite), the PATH for GUI applications is not set the same as for terminal processes. The full explanation can be found here (https://github.com/GoClipse/goclipse/issues/91#issuecomment-82555504)

Maybe you haven't been able to reproduce this because you are not running OS X 10.10? I don't have Mac OS X, so I haven't tried any of this myself, but other users seem to confirm this theory (for example if Eclipse RustDT is started from the command-line, the problem above no longer occurs).

**Comment by greggawatt** [comment] 2015-05-20 16:03
I solved this by giving up iterm, terminal for mac is good enough for me.

On Wed, May 20, 2015 at 7:23 AM, Bruno Medeiros <notifications@github.com>
wrote:

> This does kinda sound like it's an iTerm2-specific problem, so I should
> ask: has anyone seen this problem and not been using iTerm2
>
> As referenced above ( RustDT/RustDT#31
> <https://github.com/RustDT/RustDT/issues/31>) , it seems the RustDT users
> have been encountering the same problem. The running theory is that in some
> OS X version (possibly Mac OSX 10.10 Yosemite), the PATH for GUI
> applications is not set the same as for terminal processes. The full
> explanation can be found here (GoClipse/goclipse#91 (comment)
> <https://github.com/GoClipse/goclipse/issues/91#issuecomment-82555504>)
>
> Maybe you haven't been able to reproduce this because you are not running
> OS X 10.10? I don't have Mac OS X, so I haven't tried any of this myself,
> but other users seem to confirm this theory (for example if Eclipse RustDT
> is started from the command-line, the problem above no longer occurs).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/cargo/issues/987#issuecomment-103904159>.
>



-- 
Gregg Horton
510-283-8734
gregghorton.com

**Comment by alexcrichton** [comment] 2015-05-26 14:49
@bruno-medeiros fascinating! I wonder why running `rustc` manually works but executing it through `cargo` doesn't? If `PATH` isn't set up correctly for GUI apps, I would expect both to fail...

**Comment by bruno-medeiros** [comment] 2015-05-27 11:00
> @bruno-medeiros fascinating! I wonder why running rustc manually works but executing it through cargo doesn't? If PATH isn't set up correctly for GUI apps, I would expect both to fail...

Dunno, again, I'm not a OSX guy, so I'm just relaying what others found. Though I reckon in RustDT's case it could be because `cargo` is invoked with an absolute path, so that would always work regardless of how `PATH` is setup.

**Comment by doosik71** [comment] 2015-06-03 11:20
Eclipse RustDT seems to fail to find rustc in /usr/local/bin.
Following is a simple trick for me to overcome this problem.
$ sudo ln -s /usr/local/bin/rustc /usr/bin/rustc

**Comment by remram44** [comment] 2015-07-26 22:38
For multirust users:

Symlinking rustc wasn't enough for me (rustc is just a proxy, so it just failed with a different error as it couldn't find multirust. I supposed I could have symlinked that as well, but...)

My fix was to set the PATH variable at the top of /usr/local/bin/cargo:

```shell
#!/bin/sh
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin
```

It's enough at least for RustDT.

**Comment by nicholasguyett** [comment] 2016-11-30 05:26
Seeing the same issue using rustup, but only when trying to build for a windows target from bash for windows.  It builds correctly when building for linux, though.

**Comment by alexcrichton** [comment] 2016-12-29 01:03
I believe this has since been fixed, so closing.

**Closed by alexcrichton** 2016-12-29 01:03 UTC
