### ISSUE TITLE
Miss

### ISSUE THREAD

**Issue by Thewsthews** [rust-lang/cargo#14616] opened 2024-09-30 09:00 UTC
I hope this is the correct avenue to explain my problem. Ive done a small project after which i ran the cargo build command in the terminal but im unable to locate the executable file after

 Finished `dev` profile [unoptimized + debuginfo] target(s) in 3m 21s

This is the message im getting and an empty build folder in the target location

Thanks!

**Comment by epage** [comment] 2024-09-30 14:19
By default, `cargo build` will put the binary in `target/debug/<name/>`.  You mentioned `target/` is empty.  That is suspicious as there has to be something from the build.  Do you have any `.cargo/config.toml` set to move your `target-dir`?

I'd recommend running `cargo run` as it prints the path of the binary its running.

**Comment by epage** [comment] 2024-10-01 18:15
I think more clear reproduction steps are needed.  You say you are trying to access a built binary but `cargo run` says there are no bin targets to access.

**Comment by Thewsthews** [comment] 2024-10-01 20:05
> I think more clear reproduction steps are needed.  You say you are trying to access a built binary but `cargo run` says there are no bin targets to access.

Yes
After running cargo build, i presumed an executable would be created in the target folder...which didnt happen.
After running `cargo run` i got the response there are no bin targets to access.

Im puzzled as i expected to find executables in the build folder

**Comment by epage** [comment] 2024-10-01 20:42
Could you provide a sample project that reproduces this problem?

**Comment by Thewsthews** [comment] 2024-10-05 20:17
Okay below is the link to project repository:
 [https://github.com/Thewsthews/Tasker.git]()

**Comment by epage** [comment] 2024-10-07 16:16
I ran
```console
$ git clone https://github.com/Thewsthews/Tasker.git
$ cd Tasker
$ cargo build
error: unexpected closing delimiter: `}`
   --> src/main.rs:351:1
    |
154 |                         _ => {
    |                              - this delimiter might not be properly closed...
...
180 |                             }
    |                             - ...as it matches this but it has different indentation
...
351 | }
    | ^ unexpected closing delimiter

error: could not compile `todo` (bin "todo") due to 1 previous error
```
I even checked out that specific commit and got the same thing.

That error would prevent any binary from being created.

**Comment by Thewsthews** [comment] 2024-10-08 13:05
What would be the correct remedy for the above?

Ive spent sometime going over the issue but i seem not to get it

**Comment by weihanglo** [comment] 2024-10-08 13:27
Perhaps you need to delete the extra closing on line 158? I am not sure. The code is not well indented and formatted. I am not the one created it, so only the author knows what it should be like.

Since this is a general Rust question, not a Cargo issue nor feature request, I am going to close this issue. Would suggest trying one of the user forums such as <https://users.rust-lang.org/> to see if someone can help. Thank you :)

**Closed by weihanglo** 2024-10-08 13:27 UTC
Labels: C-question, S-needs-info
