### ISSUE TITLE
Allow specifying platform scoped dependencies without having to list the entire set of platform tuple permutations

### ISSUE THREAD

**Issue by carllerche** [rust-lang/cargo#1594] opened 2015-05-08 17:48 UTC
Sorry if this is a dup. I couldn't find anything obvious.

My crate needs a dependency for windows platforms and a dependency for *nix platforms. Right now, it seems that the only way to do this is to list every single possible platform tuple and assign it the appropriate dependency. This is clunky and error prone. It would be nice if there were a simpler way to do this.

**Comment by alexcrichton** [comment] 2015-05-08 17:52
Dupe of https://github.com/rust-lang/cargo/issues/1007, but thanks for the report!

**Closed by alexcrichton** 2015-05-08 17:52 UTC
