### ISSUE TITLE
Omit test categories when unused.

### ISSUE THREAD

**Issue by Dworv** [rust-lang/cargo#12750] opened 2023-09-28 21:16 UTC
### Problem

Unused test categories clutter results, making them much less digestible on smaller terminals.

E.g. default output on a repository with a single unit test and no docs or `main.rs` tests:

```
cargo test
   Compiling game v0.1.0 (/Users/dworv/Coding/ubiquitous/game)
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running unittests src/lib.rs (target/debug/deps/game-8b0a87aac65c670c)

running 1 test
test tests::server::test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/game-349d00b1b415c1f8)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests game

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

### Proposed Solution

Instead of showing these 0-test categories, omit them for a cleaner output:

```
cargo test
   Compiling game v0.1.0 (/Users/dworv/Coding/ubiquitous/game)
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running unittests src/lib.rs (target/debug/deps/game-8b0a87aac65c670c)

running 1 test
test tests::server::test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

You could even make debugging easier for people that wonder why tests they add wrong don't show up with an extra line:
```
2 categories with 0 tests omitted
```

**Comment by epage** [comment] 2023-09-28 21:20
At a quick glance, this looks like a duplicate of #2832.  Closing in favor of that.  If I missed something, let us know and we can re-open it if needed!

**Closed by epage** 2023-09-28 21:20 UTC
Labels: Command-test, C-feature-request, S-triage
