### ISSUE TITLE
Compiling cargo v0.46.1 as a dependency fails.

### ISSUE THREAD

**Issue by npes-95** [rust-lang/cargo#8751] opened 2020-10-04 07:53 UTC
With `cargo 1.42.0`, `rustc 1.42.0` on macOS Catalina 10.15.7. This happened when trying to install `cargo-generate`.

```
cargo install cargo-generate
.
.
.
.
Compiling cargo v0.46.1
error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.46.1/src/cargo/core/resolver/conflict_cache.rs:178:79
    |
178 |         let out = self.find(dep, &|id| cx.is_active(id), must_contain, usize::MAX);
    |                                                                               ^^^ associated item not found in `usize`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use rand::distributions::weighted::alias_method::Weight;`
help: you are looking for the module in `std`, not the primitive type
    |
178 |         let out = self.find(dep, &|id| cx.is_active(id), must_contain, std::usize::MAX);
    |                                                                        ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `cargo-generate v0.5.1`, intermediate artifacts can be found at `/var/folders/xz/tc9gy0vn5v5b1qp5rv36vcqr0000gn/T/cargo-installxdWOL1`

Caused by:
  could not compile `cargo`.

To learn more, run the command again with --verbose.
```

I was able to fix the issue on my machine by applying the compiler suggestion.

**Comment by Mark-Simulacrum** [comment] 2020-10-04 12:52
Cargo requires that the stable released at the same time is used for compilation, for 0.46.1 that would be 1.45. Closing as this is not a bug.

**Closed by Mark-Simulacrum** 2020-10-04 12:52 UTC
Labels: C-bug
