### ISSUE TITLE
Allow specifying extra files to install in Cargo.toml

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/cargo#3680] opened 2017-02-10 09:58 UTC
Some software might want to install extra files like some sample configuration file or init systems integration.
That would be great to be able to specify that in Cargo.toml so that cargo install actually installs those.

**Comment by alexcrichton** [comment] 2017-02-10 15:05
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/2729, though, so I'm going to close in favor of that.

**Closed by alexcrichton** 2017-02-10 15:05 UTC
