### ISSUE TITLE
Cargo.lock is unexpectedly included in packaged library crate

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/cargo#9317] opened 2021-04-01 01:53 UTC
**Problem**
The latest update i this topic I found was #7026, which says that `Cargo.lock` is included by default with executable crates.
However, [my crate](https://github.com/nazar-pc/mediasoup/tree/1021dc6c13196afe8f47c81ccdfe76f19635c5d8) is not executable, yet I found that it still includes lock file for some reason.

**Steps**
1. Clone https://github.com/nazar-pc/mediasoup/tree/1021dc6c13196afe8f47c81ccdfe76f19635c5d8
2. `cd rust`
3. `cargo package`
4. Check generated package, it will include `Cargo.lock`

**Possible Solution(s)**
Would be nice to not include it I think, especially since root `Cargo.lock` is excluded in `.gitignore`.

**Notes**

Output of `cargo version`: cargo 1.51.0 (43b129a20 2021-03-16)

UPD: Excluding `Cargo.lock` in `Cargo.toml` explicitly doesn't seem to have any effect either :thinking:

**Comment by ehuss** [comment] 2021-04-01 02:06
Your package includes examples, which will trigger the inclusion of `Cargo.lock`.  There shouldn't be any concern for including it, as it is otherwise ignored.

**Comment by nazar-pc** [comment] 2021-04-01 02:10
Hm... but examples don't make crate an executable, there are even separate parameters for them like `autobins` and `autoexamples`.
It was discovered accidentally in https://github.com/rust-lang/docs.rs/issues/1338#issuecomment-811569692
Not a huge issue for sure, but it was certainly surprising to me.

**Comment by ehuss** [comment] 2021-06-02 22:03
This is intended behavior, as examples can be potentially installed with `cargo install`.  Closing as intended behavior, which is documented at https://doc.rust-lang.org/cargo/commands/cargo-package.html, but thanks for opening the issue!

**Closed by ehuss** 2021-06-02 22:03 UTC
Labels: C-bug
