### ISSUE TITLE
registry paths hard coded in binary

### ISSUE THREAD

**Issue by chemsaf3** [rust-lang/cargo#9311] opened 2021-03-28 22:09 UTC
**Problem**

hardcoded paths in binary with username and fs paths. bloats binary, prevent reproducibility, and violates privacy. even in `release` mode

`strip` command does not properly remove everything too

redacted EXAMPLES

```
internal error: entered unreachable codeD:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.15\src\ahocorasick.rs
D:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.15\src\prefilter.rssetRareByteOffsets
called `Option::unwrap()` on a `None` valueD:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.15\src\classes.rs
D:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.15\src\packed\pattern.rs
internal error: entered unreachable codeD:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.15\src\packed\teddy\compile.rs
D:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\rand-0.8.3\src\rngs\thread.rs
D:\REDACTED\.cargo\registry\src\github.com-1ecc6299db9ec823\rand_chacha-0.3.0\src\guts.rs
D:\REDACTED\git\PROJECT\target\release\deps\PROJECT.pdb
```

**Steps**

1. install rust
2. write an app using a dep
3. compile app
4. check strings for user id

**Possible Solution(s)**

auto strip this info (preferred) or provide wildcard way to mangle paths

**Notes**

Output of `cargo version`:
```
> cargo version
cargo 1.50.0 (f04e7fab7 2021-02-04)
```

**Related**

https://github.com/rust-lang/cargo/issues/5505
https://github.com/rust-lang/rust/issues/40374
https://github.com/rust-lang/rust/issues/40552
https://github.com/rust-lang/rust/issues/75263

**Comment by ehuss** [comment] 2021-03-29 16:49
Thanks for the report!  It looks like you found several other issues related to this, so I'm unclear if this issue is covering anything new.  It seems like #5505 covers dealing with remapping, can you clarify what is different here?

**Comment by pthreat** [comment] 2021-04-03 23:17
@ehuss seems like this time you should address it instead of closing it

**Comment by geraldo-netto** [comment] 2021-04-05 15:11
+1

**Comment by ehuss** [comment] 2021-05-29 17:39
I'm going to close this issue as a duplicate of #5505. I realize this is an important issue for some, and hopefully there will be some progress in the future.  You may want to also check out https://github.com/rust-lang/rfcs/pull/3127 which is a recent proposal to work towards resolving this.

**Closed by ehuss** 2021-05-29 17:39 UTC
Labels: C-bug
