### ISSUE TITLE
Latest nightly seems to cause issue with `libc::isatty`

### ISSUE THREAD

**Issue by saghm** [rust-lang/cargo#2522] opened 2016-03-26 02:23 UTC
The behavior of `libc::isatty()` seems to depend on whether `cargo run` is used (as opposed to just running the binary in `target` in the latest nightly (2016-03-24). For example, with the following code:

```rust
fn main() {
    let fileno = unsafe { libc::STDIN_FILENO as i32 };
    let isatty = unsafe { libc::isatty(fileno) };
    println!("fileno: {}, isatty: {}", fileno, isatty);
}
```

When run with the 2016-03-23 nightly, it prints out `fileno: 0, isatty: 1` (whether run with `cargo run` or directly from the binary). However, with the 2016-03-24 nightly, it prints out `fileno: 0, isatty: 1` when run directly from the binary and `fileno: 0, isatty: 0` when run with `cargo run`. This leads me to believe that the difference might be caused by some change in cargo in dealing with standard input. Obviously a workaround is just not to use `cargo run`, but I'm curious about whether the previous behavior might be worth restoring at some point in the future.

I tried to look through the recent commits to see if I could track down where the change occurred, but unfortunately had no luck. Sorry about not being able to point somewhere specific in the code!

**Comment by alexcrichton** [comment] 2016-03-26 05:16
I believe this is a dupe of https://github.com/rust-lang/rust/issues/32254 caused by https://github.com/rust-lang/rust/pull/31618 and fixed in https://github.com/rust-lang/rust/pull/32257, so closing in favor of https://github.com/rust-lang/rust/issues/32254 but thanks for the report!

**Closed by alexcrichton** 2016-03-26 05:16 UTC
