### ISSUE TITLE
Target specific examples

### ISSUE THREAD

**Issue by cujomalainey** [rust-lang/cargo#11169] opened 2022-10-02 02:33 UTC
### Problem

Building system depending libraries with examples that vary based on the OS (e.g. embedded-hal integrations or USB functionality) causes example tests to constantly fail if you write examples to fail when running `cargo test.` 

### Proposed Solution

Allow for examples to be scoped to specific targets and possibly allow for cross compilation.

**Comment by weihanglo** [comment] 2022-10-07 22:16
Thanks for the report! This seems effectively a duplicate of #9208. Close this in favour of #9208.

**Closed by weihanglo** 2022-10-07 22:16 UTC
Labels: C-feature-request
