### ISSUE TITLE
Conditional features for conditional dependencies

### ISSUE THREAD

**Issue by vberger** [rust-lang/cargo#6658] opened 2019-02-13 16:26 UTC
In short, being able to reflect this kind of dependencies of features:

- if feature `foo` is enabled, depend on crate `krate`
  - if additionally feature `bar` is enabled, depend on `krate/bar`
- if feature `foo` is not enabled, don't depend on `krate`, *even if `bar` is enabled*

I don't see any way to reflect this currently:

- if `bar` depends on `krate/bar`, enabling it will always pull `krate`, even if foo is not enabled
- if it doesn't, enabling `foo` and `bar` does not pull `krate/bar`, which in my case would cause a compilation error

**Comment by Nemo157** [comment] 2019-08-12 11:29
Duplicate of https://github.com/rust-lang/cargo/issues/3494

**Comment by ehuss** [comment] 2019-08-12 13:38
Yea, looks the same, thanks!

**Closed by ehuss** 2019-08-12 13:38 UTC
Labels: A-features, C-feature-request
