### ISSUE TITLE
`cargo test` ignores rustc-link-search

### ISSUE THREAD

**Issue by astraw** [rust-lang/cargo#1872] opened 2015-08-03 14:56 UTC
When `cargo test` calls `rustdoc --test` it neglects to pass the results of rustc-link-search as an option.

For example, I just made [this commit](https://github.com/astraw/lapack/commit/4600abd058547a33932bb0fde0694fc56dab9fab) which allows the lapack library to build on Mac OS X when gfortran is installed in `/usr/local/gfortran/lib`. However, when I run `cargo test`, the doctests fail because this file is not specified and thus linking fails. If I manually add "-L /usr/local/gfortran/lib" to the call to `rustdoc --test`, the linking succeeds and the doctests run.

So I think this is an issue with cargo not passing rustc-link-search to `rustdoc --test`.

rustc 1.3.0-nightly (2a309b7f5 2015-08-02)
rustdoc 1.3.0-nightly (2a309b7f5 2015-08-02)
cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)

**Comment by alexcrichton** [comment] 2015-08-03 17:59
Dupe of https://github.com/rust-lang/cargo/issues/1592, but thanks for the report!

**Closed by alexcrichton** 2015-08-03 17:59 UTC
