### ISSUE TITLE
Passing quote escaped options to rustc doesn't work

### ISSUE THREAD

**Issue by mvtec-bergdolll** [rust-lang/cargo#11404] opened 2022-11-22 09:02 UTC
### Problem

I'm trying to build a project with mcount instrumentation, however due to https://github.com/rust-lang/rust/issues/92109 I have to specify a custom set of passes. I tried `RUSTFLAGS="-Z instrument-mcount -C passes=\"ee-instrument post-inline-ee-instrument\"" cargo +nightly build --release` and `RUSTFLAGS="-Z instrument-mcount -C passes=ee-instrument post-inline-ee-instrument" cargo +nightly build --release` and some other combinations and I always get errors that look something like this:

process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Z instrument-mcount -C 'passes="ee-instrument' 'post-inline-ee-instrument"' --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)

To me it seems it doesn't forward the escaped string in an intuitive way to rustc.

### Steps

1. Build project with `RUSTFLAGS="-Z instrument-mcount -C passes=\"ee-instrument post-inline-ee-instrument\"" cargo +nightly build --release`
2. Error

### Notes

Happens on Linux with zsh and bash.

### Version

```text
cargo 1.67.0-nightly (9286a1beb 2022-11-04)
```

**Comment by ehuss** [comment] 2022-11-22 13:37
Indeed RUSTFLAGS does not support spaces. I think it is unlikely we will add any sort of shell-parsing for that. There are some alternatives now:

* use `CARGO_ENCODED_RUSTFLAGS` which allows spaces
* use `--config 'build.rustflags=["arg1", "arg2"]'`
* Set `build.rustflags` in `config.toml`

I'm going to close as a duplicate of #3686.

**Closed by ehuss** 2022-11-22 13:37 UTC
Labels: C-bug

**Comment by mvtec-bergdolll** [comment] 2022-11-25 11:45
@ehuss could you please give an example how to achieve the cargo equivalent `rustc -C passes="ee-instrument post-inline-ee-instrument" ...`. I failed to achieve this with any of your provided alternatives. Note that some versions such as `--config 'build.rustflags=["-C", "passes=ee-instrument post-inline-ee-instrument"]'` build but don't actually achieve the desired effect, as checked with `nm <binary> | rg mcount`

**Comment by ehuss** [comment] 2022-11-25 13:18
If you are using a bash-like shell, something like this should work:

```
CARGO_ENCODED_RUSTFLAGS=$'-Zinstrument-mcount\u001f-Cpasses=ee-instrument aa-eval' cargo b -v
```

With `-v` you should be able to inspect that flags being passed to `rustc`. If your desired passes/instrumentation aren't showing up, I would suspect its an issue with rustc or the passes being used.
